### ISSUE TITLE
CLLocationManager with specified accuracy

### ISSUE THREAD

**Issue by josejulio** [mxcl/PromiseKit#100]
Consider the current usage of [CLLocationManager promise], it will be fulfilled when any location info arrives, but i believe that most times you want to assure that the accuracy is within a range, so i propose an alternative method **promiseIf**, its usage could be something like:

```
[CLLocationManager promiseIf:^(CLLocation*l, NSArray* locations) {
       NSMutableArray* validLocations = [NSMutableArray array];
       for (CLLocation* loc in locations) {
              if (loc.horizontalAccuracy > 0 && loc.horizontalAccuracy < 20) {
                     [validLocations addObject: loc];
              }
       }
       return validLocations;
}].when(^(CLLocation* l, NSArray* location) {
      // if validLocations is nonEmpty, it returns the first location on that array and the validLocationArray
}];
```

In that way you don't have to start new promises if you don't get the desired accuracy (or other condition that you would like to impose to your locations).

**Comment by mxcl** [comment]
Added +until
