### ISSUE TITLE
Using `after` Guarantees is sometimes leading to "pending guarantee deallocated" warnings

### ISSUE THREAD

**Issue by jlew-nevo** [mxcl/PromiseKit#1001]
* PromiseKit 6.8.1, CocoaPods install.

Since updating to 6.8.x, we are seeing the warning `PromiseKit: warning: pending guarantee deallocated`.
The simplest repro I have for this so far is:

```
let p = Promise.value(6)
p.timeout(seconds: 1.5).done { _ in
   print("Fulfilled")
}.catch { err in
}
```

where `timeout` is defined as:

```
extension Promise {
    func timeout(seconds: TimeInterval) -> Promise<T> {
        return race(asVoid(), after(seconds: seconds).done {
            throw TimeoutError()
        }).map {
            self.value!
        }
    }
}
```

**Comment by mxcl** [comment]
Yeah, makes sense, `race()`’s promise deallocates when the first of its arguments resolves, so the others arguments will deallocate too.

Solution is probably to unset the deallocation monitor for all Thennable arguments.

**Comment by jlew-nevo** [comment]
Well, my initial version did not use race and had the same problem.  Is the pending tuple's `resolve` member supposed to retain the promise?  Because I can also produce it like so:
```
let pending = Guarantee<Void>.pending()
        let resolve = pending.resolve
        DispatchQueue.global().async {
            resolve(())
        }
```

**Comment by jlew-nevo** [comment]
A little more info: notice if you run this repro (below), you will see the warning come up immediately, well before the `fulfill` executes. 
```
 let p = Promise<Int>.pending()
        
        p.promise.timeout(seconds: 5.0).done { val in
            print("Fulfilled \(val)")
            }.catch { err in
        }
        
        DispatchQueue.global().asyncAfter(deadline: .now() + 2.5) {
            p.resolver.fulfill(10)
        }
```

**Comment by jlew-nevo** [comment]
Same early-warning behavior in the following implementation, when `race` is not in the mix:
```
extension Promise {
    func timeout(seconds: TimeInterval) -> Promise<T> {
        let pending = Promise<T>.pending()
        after(seconds: seconds).done {
            pending.resolver.reject(TimeoutError())
        }
        self.done { result in
            pending.resolver.fulfill(result)
            }.catch { err in
                pending.resolver.reject(err)
        }
        return pending.promise
    }
}
```

**Comment by mxcl** [comment]
Yes this is the same as `race`’s implementation. Once the `pending.resolver` is resolved, it deallocates, this cascades through and causes the `after` to be deallocated.

**Comment by mxcl** [comment]
Please note your `timeout` function follows the common misusage pattern of doubling up promises, please don't do this, it is a code smell. See our
[Troubleshooting Guide](https://github.com/mxcl/PromiseKit/blob/master/Documentation/Troubleshooting.md) for more information.

**Comment by jlew-nevo** [comment]
Fair enough, I haven't read up on pipes yet, will do so.  However, the warning does seem to be happening *before* pending.resolver is resolved.  In my demo code up there, the warning appears immediately, but the async resolve doesn't happen for 2.5 seconds.

**Comment by mxcl** [comment]
K, I have confirmed that #973 is broken. I will have to revert.

**Comment by jlew-nevo** [comment]
Many thanks!

**Comment by mxcl** [comment]
K I'm waiting on CI for the fix. I have tested the warning works as intended now, though I have not added tests to prevent regression, will do after release, which seems more urgent currently.

Will release 6.8.2 once CI passes.

**Comment by mxcl** [comment]
Deployment: https://travis-ci.org/mxcl/PromiseKit/builds/485611249

**Comment by mxcl** [comment]
Deploy failed, and I'm having to download Xcode 10 (10.1 is broken with CocoaPods) to figure out why. The tag is released though if you use something else.

**Comment by mxcl** [comment]
Deploy happened last night.

**Comment by jlew-nevo** [comment]
Upgrading, thanks!
