### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found:

### ISSUE THREAD

**Issue by Jarvey** [mxcl/PromiseKit#1006]
[PLEASE READ THE TROUBLESHOOTING GUIDE](https://github.com/mxcl/PromiseKit/blob/master/Documentation/Troubleshooting.md).

---

You read the guide but it didn’t help? OK, we’re here to help.

* Please specify the PromiseKit major version you are using
* [Please format your code in triple backticks and ensure readable indentation](https://help.github.com/articles/creating-and-highlighting-code-blocks/)
* Please specify how you installed PromiseKit, ie. Carthage, CocoaPods, SwiftPM or other. If other provide DETAILED information about how you are integrating PromiseKit.

If you ignore this template we will close your ticket and link to this template until you provide this necessary information. We cannot help you without it.

**Comment by Jarvey** [comment]
yesterday Xcode was telling me that Promisekit and foundation where outdated so I updated Promisekit and foundation to the latest version via Carthage.
I use two targets watchOS and iOS, when my watch app is making a network request in the simulator I now receive the following error in NSURLSession+Promise.swift
<img width="1286" alt="screenshot 2019-02-04 at 10 01 30" src="https://user-images.githubusercontent.com/5406216/52200169-4b818500-2868-11e9-9239-b11409d0221c.png">

dyld: lazy symbol binding failed: Symbol not found: _$S10PromiseKit8ThenablePAAE3map2on5flags_AA0A0Cyqd__GSo17OS_dispatch_queueCSg_8Dispatch0J13WorkItemFlagsVSgqd__1TQzKctlFfA_
  Referenced from: /Users/maikel/Library/Developer/CoreSimulator/Devices/DC4F77ED-0B0B-4ED2-AF58-B5806AE6507C/data/Containers/Bundle/Application/1FD7EE54-8758-456A-8BB9-83611DBCD5A1/Treingids WatchKit App.app/PlugIns/Treingids WatchKit Extension.appex/Frameworks/PMKFoundation.framework/PMKFoundation
  Expected in: /Users/maikel/Library/Developer/CoreSimulator/Devices/DC4F77ED-0B0B-4ED2-AF58-B5806AE6507C/data/Containers/Bundle/Application/1FD7EE54-8758-456A-8BB9-83611DBCD5A1/Treingids WatchKit App.app/PlugIns/Treingids WatchKit Extension.appex/Frameworks/PromiseKit.framework/PromiseKit

dyld: Symbol not found: _$S10PromiseKit8ThenablePAAE3map2on5flags_AA0A0Cyqd__GSo17OS_dispatch_queueCSg_8Dispatch0J13WorkItemFlagsVSgqd__1TQzKctlFfA_
  Referenced from: /Users/username/Library/Developer/CoreSimulator/Devices/DC4F77ED-0B0B-4ED2-AF58-B5806AE6507C/data/Containers/Bundle/Application/1FD7EE54-8758-456A-8BB9-83611DBCD5A1/testApp WatchKit App.app/PlugIns/testApp WatchKit Extension.appex/Frameworks/PMKFoundation.framework/PMKFoundation
  Expected in: /Users/username/Library/Developer/CoreSimulator/Devices/DC4F77ED-0B0B-4ED2-AF58-B5806AE6507C/data/Containers/Bundle/Application/1FD7EE54-8758-456A-8BB9-83611DBCD5A1/testApp WatchKit App.app/PlugIns/testApp WatchKit Extension.appex/Frameworks/PromiseKit.framework/PromiseKit

**Comment by mxcl** [comment]
Clean and rebuild.

**Comment by Jarvey** [comment]
If you mean 'Clean Build Folder' in Xcode I already tried with no succes. Any other ideas?

**Comment by mxcl** [comment]
You have to delete the Carthage folder in order to clean a Carthage installation.

**Comment by Jarvey** [comment]
That did it, thanks for the quick reply!

**Comment by mxcl** [comment]
No problem! If you found my help useful, please consider reimbursing my time by contributing to [my Patreon](https://patreon.com/mxcl). Thank you so much!
