### ISSUE TITLE
API documentation is offline

### ISSUE THREAD

**Issue by aaronbarsky** [mxcl/PromiseKit#1008]
When I follow the link:
https://promisekit.org/reference/

404ed.

**Comment by mxcl** [comment]
Link from where?

**Comment by mxcl** [comment]
I updated what I could find, thanks for the report.

**Comment by aaronbarsky** [comment]
Thanks for the super fast response.  It was the API Reference link from the Readme.md.  Glad to see the docs back.

**Comment by mxcl** [comment]
nps. Thanks for the report! And if you find my work useful, please consider reimbursing my time by contributing to [my Patreon](https://patreon.com/mxcl). Thank you so much!
