### ISSUE TITLE
Something off with PromiseKit 6 release notes

### ISSUE THREAD

**Issue by GarthSnyder** [mxcl/PromiseKit#1013]
I know this isn't the new hotness anymore, but if 6 is going to be retained for backward compatibility, it would be nice to keep the docs accessible. The URL in README.md points to 
[http://mxcl.github.io/PromiseKit/news/2018/02/PromiseKit-6.0-Released/](http://mxcl.github.io/PromiseKit/news/2018/02/PromiseKit-6.0-Released/), which currently looks like it might be missing CSS and/or supporting files.

Maybe bring this doc into the project tree?

**Comment by mxcl** [comment]
Thanks, I'll fix, I recently decided to let promisekit.org lapse which is probably what broke here.

**Comment by mxcl** [comment]
Should be fixed.

**Comment by mxcl** [comment]
There's some remaining broken links that I’m looking into.
