### ISSUE TITLE
Type of expression is ambiguous without more context

### ISSUE THREAD

**Issue by farllight** [mxcl/PromiseKit#1014]
- PromiseKit - 6.8.3
- Swift 4.2
- CocoaPods version 1.6.0

```
    func getFolders(folderId: String? = nil) -> Promise<[Folder]> {
        return Promise<[Folder]> {
            self.getFolders(folderId: folderId, completion: $0.resolve)
        }
    }
```

I have problem in this source with error "Type of expression is ambiguous without more context". In other project this work perfect. What is this?

**Comment by farllight** [comment]
Solved in project. Completion don't return Error.

**Comment by mxcl** [comment]
More information for this and many other compile issues in our [Troubleshooting Guide](https://github.com/mxcl/PromiseKit/blob/master/Documentation/Troubleshooting.md).
