### ISSUE TITLE
Cascading chains into one chain

### ISSUE THREAD

**Issue by shi-rudo** [mxcl/PromiseKit#1020]
I understand I should not double up promises (cascading chaines). What would be the right approach if I have multiple PromiseChains which I use independently in many places but have to combine in a few places?

In order to have it clearer and more low-maintenance, the respective promise chains should have their own error handling. Since their main purposes are in other classes than where they are occasionally shared (sequentially).

```swift
// this routine is often used in isolation
func checkThis() {
   firstly {
      restoreData()
   }.then { _ in
      verifyData()
   }.then { payload in
      writeDataStatus(payload)
   }.done { _ in
      log.info("Data is valid and active")
   }.catch { error in
      log.error(error)

   //Error handling on every error
      someManager.presentSomeVC()
   }
}

// this routine is often used in isolation too
func checkThat() {
   firstly {
      getUserData()
   }.then { currentUserData in
      manipulateUserData(currentUserData)
   }.then { user in
      writeClonedUser(user)
   }.done { _ in
      log.info("User has been backed up")
   }.catch { error in
      log.error(error)

      switch error {
      case error1 : 
         doSomethingForError1()

      ...

      case error10 : 
         doSomethingForError10()
      }
   }
}

// this too
func foobar(data) {
	firstly {
      sendData(data)
   }.then { _ in
      sendNotification()
   }.done { _ in
      populateUI()
   }.catch { error in
      log.error(error)

      switch error {
      case error1 : 
         doSomethingForError1()

      ...

      case error5 : 
         doSomethingForError5()
      }
   }
}
```

So now I would do something like this:

```swift
func runCombined() {
   firstly {
      checkThis()
   }.then {
      checkThat()
   }.done {
      foobar()
   }
} 
```

I tried several ways, but I always end up with some compiler error, mostly like "to expected argument type '() -> Guarantee<_>'".  Could somebody help me out? Thanks!

**Comment by mxcl** [comment]
That is how you combine them yes. If you have compiler problems, see our [Troubleshooting Guide](https://github.com/mxcl/PromiseKit/blob/master/Documentation/Troubleshooting.md)

**Comment by shi-rudo** [comment]
Sorry, I don't understand how I can chain the subroutines (promise chains) into one main routine as promise chain without sealing the subroutines? 

Or did I misunderstand the principle of doubling up promises? Because the subroutine has to make its own promise (so no doubling up here?) **to run sequentially in the main routine**. If I don't seal the fullfill/rejection in the subroutines, promises maybe are going to be deallocated.

This is how I do it at the moment, have I gotten used to something bad here?
THANK YOU!!

```swift
func subChainOne() -> Promise<Void> {
    return Promise { seal in
        firstly {
        ...
        }.then { _ in
        ...
        }.done { _ in
        seal.fullfill(())
        }. catch { error in
        seal.reject(error)

        //error handling for this subroutines happens here
        ..
        } 
    }
}

func subChainTwo() -> Promise<Void> {
    return Promise { seal in
        firstly {
        ...
        }.then { _ in
        ...
        }.done { _ in
        seal.fullfill(())
        }. catch { error in
        seal.reject(error)

        //error handling for this subroutines happens here
        ..
        } 
    }
}

func mainChain() {
    
    firstly {
    subChainOne() 
    }.then { _ in
    subChainTwo()
    }.catch { error in
    print(error)
    }
}
```

**Comment by mxcl** [comment]
`catch` doesn’t return a Promise. You have to do this or use `recover`, for documentation on how to use `recover` see our documentation.

```swift
func subChainOne() -> Promise<Void> {
    firstly {
      //…
    }.then { _ in
      //…
    }
}

func subChainTwo() -> Promise<Void> {
    firstly {
        //…
    }.then { _ in
        //…
    }
}

func mainChain() {   
    firstly {
        subChainOne() 
    }.then { _ in
        subChainTwo()
    }.catch { error in
        print(error)
    }
}
```

**Comment by donileo** [comment]
@mxcl using recover though in `mainChain()` so that other callers can use the promise now results in having to do .cauterize() at the end of it though since the error is already printed out in recover..

```
func mainChain() -> Promise<Void> {   
    firstly {
        subChainOne() 
    }.then {
        subChainTwo()
    }.recover { error in
        log(error)
        throw(error)
    }
}

// Caller
mainChainOne().done { 
...
}.cauterize() <--- Don't want to have to log any errors myself
```

In my example above isn't having to do cauterize code smell as well?

**Comment by mxcl** [comment]
If you don’t want to `cauterize`, convert it to a `Guarantee` before returning otherwise you are telling the caller that they *have* to handle the error.

This is just the same as Swift error handling, if you return a Promise it's like annotating the function `throws`.
