### ISSUE TITLE
Argument labels '(resolvers:)' do not match any available overloads

### ISSUE THREAD

**Issue by karthicknachimuthu** [mxcl/PromiseKit#1021]
I have faced following issue when updating PromiseKit(6.8.3) to latest version in Xcode 10.1. Can you please have a look into and help to me to resolve it?

The error is,

![screenshot 2019-03-06 at 6 24 03 pm](https://user-images.githubusercontent.com/46484221/53882702-10c46580-403d-11e9-8634-6702ad2085c4.png)

Thanks!!

**Comment by mxcl** [comment]
This function no longer exists, please read the PMK6 migration guide or read the API docs.
