### ISSUE TITLE
Where is the Podspec?

### ISSUE THREAD

**Issue by pascalbros** [mxcl/PromiseKit#1025]
In the current version there is no Podspec file, hence the Pod cannot be resolved.
Is it right or not? Thanks

**Comment by mxcl** [comment]
https://github.com/mxcl/PromiseKit/blob/master/.github/PromiseKit.podspec

I don’t know what you mean by “cannot be resolved”. The podspec is not part of the resolution process, all specs are JSON and hosted by CocoaPods.

**Comment by pascalbros** [comment]
Sorry man, there was something wrong with my Macbook, now it's fine. Cheers!
