### ISSUE TITLE
Xcode 10 complains about dependency cycle in PromiseKit when using New Build System

### ISSUE THREAD

**Issue by jlew-nevo** [mxcl/PromiseKit#1032]
* PromiseKit 6.8.3
* Xcode 10.1
* CocoaPods 1.6

This started happening when we upgraded to the new build system in the XCode 9 timeframe and has persisted through multiple versions of PromiseKit, Xcode 10.1, and CocoaPods 1.4 thru 1.6. Our workspace is multi-target (app + several frameworks + pod project) workspace, and all of our targets depend on PK.  This issue seems to happen most often after switching git branches and doing an incremental build.  The incremental build will get most of the way through and then fail with an error like: 

`Dependency cycle detected between targets`
...
`Cycle path: Account -> Core -> Contracts -> Pods-Apps-Contracts -> PromiseKit -> Account
Account, Core, and Contract`

Further incremental builds continue to fail, `Project | Clean Build Folder`  followed by a normal build will always succeed.

This seems to be Xcode's issue, since there is clearly no dependency from `PromiseKit` to `Account` (which is ours), but I'm opening this issue in case we can find a workaround.

**Comment by mxcl** [comment]
Try turning implicit dependency detection off for your Account target.

**Comment by nmaniatis** [comment]
@jlew-nevo I happens to me sometimes, with clean build folder it fixes the problem always.
