### ISSUE TITLE
Swift 5.0 with PromiseKit pod install problem

### ISSUE THREAD

**Issue by nmaniatis** [mxcl/PromiseKit#1033]
Hello Max, 

I am trying to install the latest version 6.8.4 with cocoapods but the latest I can install is 6.8.3.

Do you have an estimation if when 6.8.4 with Swift 5.0 is going to come out ?

Thanks

**Comment by mxcl** [comment]
Sorry seems the deployment failed, I'll try to trigger it again.

**Comment by mxcl** [comment]
Notably we've supported Swift 5 on macOS for over a month.

The latest GM broke on Linux for annoying reasons, but unless you care about Linux 6.8.3 should work fine.

**Comment by nmaniatis** [comment]
@mxcl Thank you ! 🙏 Yes I used the 6.8.3 for my iOS project.

**Comment by mxcl** [comment]
Closing unless you have a specific issue, 6.8.3 should not be required for 5.0 support. Reopen if you can provide a specific compile error.
