### ISSUE TITLE
PromiseKit.Result type conflicts with Swift.Result type

### ISSUE THREAD

**Issue by jlaws** [mxcl/PromiseKit#1035]
Using the blanket framework import
```
import PromiseKit
```
causes conflicts in files that want to use the Swift.Result type.  

To avoid conflict with the standard library, can PromiseKit.Result be updated to a new name or embedded in another class like PromiseKit.Promise.Result?  

I searched my codebase and for 2802 explicit declarations of the word Promise I have 0 explicit uses of Result. Because of this, the latter suggestion of keeping the Result name, but nesting it inside Promise class, would be a better solution.

**Comment by clarkcox3** [comment]
Wouldn’t it make more sense to just have PromiseKit adopt Swift.Result?

**Comment by mxcl** [comment]
We cannot change its name without breaking semantic versioning. We removed `Result` in PromiseKit 7 which is in beta.

You will have to differentiate with `Swift.Result` or `PromiseKit.Result`.

**Comment by mxcl** [comment]
If you want to use PromiseKit 7 alpha, it is tagged and can be imported with all packaging solutions.

**Comment by jlaws** [comment]
Great thanks!

**Comment by ParceledTongue** [comment]
@mxcl This is probably not standard practice for alpha branches, but would you consider adding an `.xcodeproj` folder defining the package there? Using carthage at the moment, the package has to be built and configured manually on each new pull.

**Comment by mxcl** [comment]
We’re not adding an xcodeproj, but instead waiting on Carthage to support SwiftPM which they have an active ticket open for. You can generate a project with SwiftPM.
