### ISSUE TITLE
Encapsuling promise kit chain into another chain

### ISSUE THREAD

**Issue by ZaweSK** [mxcl/PromiseKit#1040]
*  xCode v 10.1, PromiseKit major version 6  installed via CocoaPods

Hello there,

II have a question about promise kit code structuring and enclosing one promise chain into another if that is even possible.

Let's say I have two classes. GroupsViewController,  and DatabaseManager.  In DM I would like to declare function which includes the promise kit chain:

createNewGroup {
promise kit chain: 
  1. create userGroup in DB 
  2. add yourself to users of that userGroup
  3. update user info
}

From GroupViewController, I would like to call this functionality just by calling createNewGroup(), and also handle the possible error here. Therefore GroupViewController would not have access to the implementation of the separate functions in promise kit chain. Something like this: 

```swift
//inside GroupViewController

dbManager.newGroup(named: "Something").done {

}.catch {
    // present the user with error
}
```
How would you approach this. Is something like this even possible or am I barking at the wrong tree here ? 

Is something like this legit ? 

```swift
//inside DatabaseManager

func newGroup(named groupName: String){
        
        createUserGroup(named: groupName).then {  groupID in
            
            addYourselfToGroup(with: groupID)
            
            }.then { groupID in
                
                updateUserGroupsForUser(with: groupID)
                
            }.catch { error in
               // shoot the error one level higher (to groupViewController )
        }
    }
```

Thanks

**Comment by mxcl** [comment]
This looks like standard chaining to me. So yes…? This is what promises are for.

**Comment by ZaweSK** [comment]
So, I am on the right track ? Then, how do I shoot up the error to the GroupViewController, since obviously I do not want to catch it / handle it in Datbase Manager.

**Comment by mxcl** [comment]
Return the promise and don't catch.

**Comment by djtech42** [comment]
If you return the promise, you can use it chained up a level and use `done` and `catch`.

```swift
func newGroup(named groupName: String) -> Promise<SomeType> {
    return createUserGroup(named: groupName).then { groupID in
        addYourselfToGroup(with: groupID)
    }.then { groupID in
        updateUserGroupsForUser(with: groupID)
    }
}
```

```swift
dbManager.newGroup(named: "Something").done {

}.catch {
    // present the user with error
}
```

However, if you are trying to provide access control to `newGroup` to prevent from calling any of the other `Promise` related operations except `done` and `catch`, that will be more difficult. In that case, you might be able to provide `done` and `catch` handlers. I wasn't sure if that's what you meant by encapsulating it. Note that you won't be able to chain `Promise` operations off of this function then.

```swift
func newGroup(
    named groupName: String, 
    done doneHandler: (SomeType) -> Void, 
    catch catchHandler: (Error) -> Void) {
        return createUserGroup(named: groupName).then { groupID in
            addYourselfToGroup(with: groupID)
        }.then { groupID in
            updateUserGroupsForUser(with: groupID)
        }.done {
            doneHandler($0)
        }.catch {
            catchHandler($0)
        }
}
```

```swift
dbManager.newGroup(named: "Something", 
done: {
    
}, 
catch: {
    // present the user with error
})

**Comment by ZaweSK** [comment]
This was really valuable piece of advice in the context of my current level of PromiseKit knowledge. Return the promise and don't catch. How simple. Thanks guys, I went with djtech42's first solution.

**Comment by mxcl** [comment]
Glad to hear. Our docs are relatively brief and recommended: https://github.com/mxcl/PromiseKit/blob/master/Documentation/GettingStarted.md
