### ISSUE TITLE
How can I use retry/polling in ObjC?

### ISSUE THREAD

**Issue by thomers** [mxcl/PromiseKit#1043]
How would I write this `attempt` method from the [docs ](https://github.com/mxcl/PromiseKit/blob/master/Documentation/CommonPatterns.md) in ObjC?

```
func attempt<T>(maximumRetryCount: Int = 3, delayBeforeRetry: DispatchTimeInterval = .seconds(2), _ body: @escaping () -> Promise<T>) -> Promise<T> {
    var attempts = 0
    func attempt() -> Promise<T> {
        attempts += 1
        return body().recover { error -> Promise<T> in
            guard attempts < maximumRetryCount else { throw error }
            return after(delayBeforeRetry).then(on: nil, attempt)
        }
    }
    return attempt()
}

attempt(maximumRetryCount: 3) {
    flakeyTask(parameters: foo)
}.then {
    //…
}.catch { _ in
    // we attempted three times but still failed
}
```

I have read the comments in https://github.com/mxcl/PromiseKit/issues/350#issuecomment-377243360 about `catch` behaving the same as `recover`, but I'm struggling with translating it into ObjC.

Thanks!

---

* Please specify the PromiseKit major version you are using

PromiseKit 4.5.2 (mainly because I'm not sure about changes to Obj-C support in later versions)

* Please specify how you installed PromiseKit

Cocoapods 1.5.3

**Comment by mxcl** [comment]
```objc
- (void)attempt:(int)maximumRetryCount, delay:(NSTimeInterval)delay provider:(PMKPromise* (^)()) {
    __block int attempts = 0;
    PMKPromise *(^attempt)() = ^{
        attempts++;
        return provide().catch(^(id error) {
            if (attempts >= maximmumRetryCount) @throw error;
            return PMKAfter(delay).then(attempt);
        })
    };
    return attempt()
} 
```

My objc is rusty so may not compile.

**Comment by mxcl** [comment]
> mainly because I'm not sure about changes to Obj-C support in later versions

6 is the same as 4 for objc. No need to upgrade, but we don't typically back port fixes to v4.

**Comment by thomers** [comment]
Wow, that is some serious block syntax action going on.

I got it to compile with these modifications:

```
- (AnyPromise *) attempt:(NSUInteger) maximumRetryCount delayBeforeRetry:(NSTimeInterval) delay provider:(AnyPromise* (^)()) provide {
	__block NSUInteger attempts = 0;
	AnyPromise *(^attempt)() = ^{
		attempts++;
		return provide().catch(^(id error) {
			if (attempts >= maximumRetryCount) @throw error;
			return PMKAfter(delay).then(attempt);
		});
	};
	return attempt();
}
```
Does this look right?

I got these warnings:

On the empty () in the method signature `provider:(AnyPromise* (^)()) provide {` 
"This block declaration is not a prototype."

On `AnyPromise *(^attempt)() = ^{` :
"Blcok pointer variable 'attempt' is unintialized when captured by block.

Thanks so much for your help and your work on such an awesome library!

**Comment by mxcl** [comment]
[self attempt:3 delayBeforeRetry:2 provider:^{ return [self fetchIdentityId]; }]

**Comment by mxcl** [comment]
Like you could probably use a selector rather than a block. It's been a long time since I did any objc.

**Comment by thomers** [comment]
Perfect! Again, thank you!
