### ISSUE TITLE
6.8.4 not working (Carthage)

### ISSUE THREAD

**Issue by Prince2k3** [mxcl/PromiseKit#1046]
I'm using latest version of Carthage 0.33 and running PromiseKit 6.8.4 and this was working before not sure what happened. BUT the message I am getting is 

```
A shell task (/usr/bin/env git checkout --quiet e0b3a9274560393328a7b08cec77676726b863b4 (launched in .../Carthage/Checkouts/PromiseKit/Extensions/AddressBook)) failed with exit code 128:
fatal: reference is not a tree: e0b3a9274560393328a7b08cec77676726b863b4
```

It is definitely the same as this issue https://github.com/mxcl/PromiseKit/issues/959

**Comment by keefertaylor** [comment]
I also see this failure.

**Comment by xinsight** [comment]
I am only seeing this error with `6.8.3`. `carthage update` i was able to successfully install `6.8.4`.

**Comment by mxcl** [comment]
Delete the Carthage cache

**Comment by Prince2k3** [comment]
Doing `rm -rf ~/Library/Caches/org.carthage.CarthageKit` to clear the cache worked
then running it again worked.

**Comment by mattrubin** [comment]
I just encountered this error. A month ago, PromiseKit 6.8.4 resolved to https://github.com/mxcl/PromiseKit/commit/d6b3b93bbdb9e6668fdcc3e0b0029e635e7915c9, but I see now (after manually resolving the resulting Carthage and git errors) that the tag is at https://github.com/mxcl/PromiseKit/commit/fe1e9c5b62465227cceb7b0e6e79489ba7b824af. Moving semver tags after they are published is very bad practice and can cause a lot of headaches for users of the library.

**Comment by mxcl** [comment]
I know it's a pita, but it was unavoidable.

**Comment by mxcl** [comment]
Like honestly this kind of snarky feedback is really unpleasant. I have dedicated huge amounts of time and effort to this library and all my other open source, being nice is really the least you could do.
