### ISSUE TITLE
6.7.1 fails with carthage update

### ISSUE THREAD

**Issue by sathishkraj** [mxcl/PromiseKit#1048]
This issue is similar to https://github.com/mxcl/PromiseKit/issues/959

I'm using 6.7.1 for a while, it started to fail with carthage update today

A shell task (/usr/bin/env git checkout --quiet e0b3a9274560393328a7b08cec77676726b863b4 (launched in /Users/2019/April/foodt/Carthage/Checkouts/PromiseKit/Extensions/AddressBook)) failed with exit code 128:
fatal: reference is not a tree: e0b3a9274560393328a7b08cec77676726b863b4

Even tried with 6.8.0 and found the same error.

**Comment by mxcl** [comment]
Upgrade to 6.8.4 if you can

**Comment by sathishkraj** [comment]
@mxcl tried 6.8.4, got the same error

**Comment by jeremycbutler** [comment]
@sathishkraj  I had to follow the recommendation in #1046 and clear the cache with `rm -rf ~/Library/Caches/org.carthage.CarthageKit`.

**Comment by mxcl** [comment]
Yeah sorry, had to force push 6.8.4 a few times due to deployment issues.

**Comment by mxcl** [comment]
I will fix 6.7.1 I must have broken a ref.

**Comment by mxcl** [comment]
I was able to clone 6.7.1 with:

    git clone -b '6.7.1' --single-branch https://github.com/mxcl/PromiseKit --recursive

**Comment by mxcl** [comment]
Probably it is a Carthage cache issue.

**Comment by sathishkraj** [comment]
@mxcl 6.8.4 seems to be working now but 6.7.1 is still failing

**Comment by mxcl** [comment]
K, found the stray ref, dunno why Carthage failed but the clone for the tag did not. But fixed. Sorry for the hassle.
