### ISSUE TITLE
Possible to use version 6 in a Swift 5 project already using Result?

### ISSUE THREAD

**Issue by sarbogast** [mxcl/PromiseKit#1054]
I'm trying to integrate PromiseKit 6.8 in a Swift 5 project already using plenty of Result instances, Result being the Swift 5 standard library type, and the compiler complains because of the number of parameters for the Result type.
Do I have to use PromiseKit 7 alpha in that case? And if yes, how can I install it with CocoaPods?

**Comment by mxcl** [comment]
Specify `Swift.Result` or `PromiseKit.Result` to fully qualify `Result`.

Possibly `typealias Result = PromiseKit.Result` will work, never tried it.
