### ISSUE TITLE
Question About ConcurrentQueue.sync

### ISSUE THREAD

**Issue by longjianjiang** [mxcl/PromiseKit#1057]
Today i read PromiseKit source code, i found in lot of place use a concurrent dispatch queue sync execute some task like below:

```
override func seal(_ value: T) {
     barrier.sync(flags: .barrier) { 
           do_work()
     }
}
```

Adding a synchronization task to the concurrent queue will synchronize the execution of the current thread. This behavior is as same as normal code execution - sequential execution.

So, i am confused about this, why add ` barrier.sync` explicitly.

please give some hint. Thanks!

**Comment by GarthSnyder** [comment]
As you note, the `sync` call won't return until the closure has been executed. The `.barrier` option requires _all_ closures in that queue to have completed before execution of the barrier block begins. And while the barrier is executing, no other closures can be dispatched, even though the queue itself is concurrent.

This feature is most commonly used to implement "N concurrent readers but only 1 exclusive writer" semantics. PromiseKit also uses it for "once all these concurrent and independent tasks have completed...". 

More [here](https://developer.apple.com/documentation/dispatch/1452917-dispatch_barrier_sync?language=objc).

**Comment by longjianjiang** [comment]
It's true. but `.barrier` works when add a async task to concurrent queue.  async tasks are not executed until the barrier task completes.

I saw in `Box.swift` and `when.swift`, only synchronization task added in barrier(concurrent queue).
Correct me if I’m wrong, so i think if remove `barrier.sync`, code will execute as same as before.

**Comment by GarthSnyder** [comment]
I'm not entirely sure that I understand the point you're making, so let me restate it to be sure I've got it right. I _think_ it is "`.barrier` is sufficient to guarantee the desired serialization/exclusivity behavior here, so use of `sync` is not necessary. There's no reason to block the current thread. You can just use `async`." Is that right?

If so, you are correct that `.barrier` is all that's needed as far as the serialization behavior. However, the closures dispatched with `sync` either yield values back to the calling thread, or they are required by virtue of the PromiseKit API definition to have completed by the time control returns to the caller. So synchronous execution is explicitly needed in addition to the barrier behavior.

For example, part of the code collapsed into `do_work()` in your `EmptyBox.seal` example above is to set the value of the `handlers` variable.

**Comment by mxcl** [comment]
> Correct me if I’m wrong, so i think if remove barrier.sync, code will execute as same as before.

~30% of our tests will fail. Thus it will not be the same, provably so.
