### ISSUE TITLE
Xcode 10.2 error

### ISSUE THREAD

**Issue by wMellon** [mxcl/PromiseKit#1059]
Showing Recent Messages
:-1: Undefined symbol: protocol conformance descriptor for Swift.Int64 : Swift.SignedInteger in Swift

:-1: Undefined symbol: (extension in Swift):Swift.Collection.isEmpty.getter : Swift.Bool

:-1: Undefined symbol: (extension in Swift):Swift.SetAlgebra< where A.ArrayLiteralElement == A.Element>.init(arrayLiteral: A.ArrayLiteralElement...) -> A

:-1: Undefined symbol: protocol requirements base descriptor for Swift.IteratorProtocol

:-1: Undefined symbol: _swift_getTupleTypeMetadata2

:-1: Undefined symbol: protocol conformance descriptor for [A] : Swift.Collection in Swift

:-1: Undefined symbol: (extension in Swift):Swift.Collection< where A.Iterator == Swift.IndexingIterator<A>>.makeIterator() -> Swift.IndexingIterator<A>

:-1: Undefined symbol: Swift.print(_: Any..., separator: Swift.String, terminator: Swift.String) -> ()

:-1: Undefined symbol: (extension in Swift):Swift.SignedInteger< where A: Swift.FixedWidthInteger>.init<A where A1: Swift.BinaryInteger>(A1) -> A

:-1: Undefined symbol: method descriptor for Foundation.LocalizedError.recoverySuggestion.getter : Swift.String?

:-1: Undefined symbol: method descriptor for Foundation.LocalizedError.errorDescription.getter : Swift.String?

:-1: Undefined symbol: protocol descriptor for Foundation.LocalizedError

:-1: Undefined symbol: method descriptor for Swift.Error._getEmbeddedNSError() -> Swift.AnyObject?

:-1: Undefined symbol: base conformance descriptor for Foundation.LocalizedError: Swift.Error

:-1: Undefined symbol: method descriptor for Swift.Error._userInfo.getter : Swift.AnyObject?

:-1: Undefined symbol: static (extension in Foundation):Swift.String._unconditionallyBridgeFromObjectiveC(__C.NSString?) -> Swift.String

:-1: Undefined symbol: protocol conformance descriptor for Foundation.CocoaError.Code : Foundation._ErrorCodeProtocol in Foundation

:-1: Undefined symbol: protocol conformance descriptor for Foundation.URLError.Code : Foundation._ErrorCodeProtocol in Foundation

:-1: Undefined symbol: type metadata accessor for Foundation.CocoaError.Code

:-1: Undefined symbol: type metadata accessor for Foundation.URLError.Code

:-1: Undefined symbol: Swift.IndexingIterator.next() -> A.Element?

:-1: Undefined symbol: Swift._getErrorEmbeddedNSError<A where A: Swift.Error>(A) -> Swift.AnyObject?

:-1: Undefined symbol: static Foundation.CocoaError.userCancelled.getter : Foundation.CocoaError.Code

:-1: Undefined symbol: Swift.== infix<A, B where A: Swift.Equatable, B: Swift.Equatable>((A, B), (A, B)) -> Swift.Bool

:-1: Undefined symbol: (extension in Foundation):Foundation.LocalizedError.helpAnchor.getter : Swift.String?

:-1: Undefined symbol: method descriptor for Swift.Error._code.getter : Swift.Int

:-1: Undefined symbol: (extension in Foundation):Foundation.LocalizedError.recoverySuggestion.getter : Swift.String?

:-1: Undefined symbol: (extension in Foundation):Foundation.LocalizedError.failureReason.getter : Swift.String?

:-1: Undefined symbol: (extension in Swift):Swift.Error._getEmbeddedNSError() -> Swift.AnyObject?

:-1: Undefined symbol: (extension in Swift):Swift.Error._code.getter : Swift.Int

:-1: Undefined symbol: (extension in Swift):Swift.Sequence< where A.Element: Swift.Comparable>.sorted() -> [A.Element]

:-1: Undefined symbol: protocol conformance descriptor for (extension in Dispatch):__C.OS_dispatch_queue.Attributes : Swift.SetAlgebra in Dispatch

:-1: Undefined symbol: dispatch thunk of Swift.Collection.isEmpty.getter : Swift.Bool

:-1: Undefined symbol: dispatch thunk of Swift.Collection.endIndex.getter : A.Index

:-1: Undefined symbol: dispatch thunk of Swift.Collection.index(_: A.Index, offsetBy: Swift.Int) -> A.Index

:-1: Undefined symbol: dispatch thunk of Swift.Collection.subscript.read : (A.Index) -> A.Element

:-1: Undefined symbol: dispatch thunk of Swift.Sequence.makeIterator() -> A.Iterator

:-1: Undefined symbol: _swift_getAssociatedConformanceWitness

:-1: Undefined symbol: dispatch thunk of Swift.IteratorProtocol.next() -> A.Element?

:-1: Undefined symbol: method descriptor for Swift.Error._domain.getter : Swift.String

:-1: Undefined symbol: (extension in Swift):Swift.Collection.first.getter : A.Element?

:-1: Undefined symbol: (extension in Swift):Swift.Sequence.map<A>((A.Element) throws -> A1) throws -> [A1]

:-1: Undefined symbol: type metadata for Swift.Int64

:-1: Undefined symbol: protocol requirements base descriptor for Swift.Sequence

:-1: Undefined symbol: value witness table for Builtin.BridgeObject

:-1: Undefined symbol: _swift_once

:-1: Undefined symbol: type metadata for Swift.String

:-1: Undefined symbol: protocol witness table for Swift.String : Swift.Equatable in Swift

:-1: Undefined symbol: _swift_isEscapingClosureAtFileLocation

:-1: Undefined symbol: (extension in Dispatch):__C.OS_dispatch_queue.sync<A>(flags: Dispatch.DispatchWorkItemFlags, execute: () throws -> A) throws -> A

:-1: Undefined symbol: (extension in Swift):Swift.Sequence.forEach((A.Element) throws -> ()) throws -> ()

:-1: Undefined symbol: type metadata accessor for (extension in Dispatch):__C.OS_dispatch_queue.AutoreleaseFrequency

:-1: Undefined symbol: associated conformance descriptor for Swift.Sequence.Iterator: Swift.IteratorProtocol

:-1: Undefined symbol: type metadata accessor for (extension in Dispatch):__C.OS_dispatch_queue.Attributes

:-1: Undefined symbol: static (extension in Dispatch):__C.OS_dispatch_queue.Attributes.concurrent.getter : (extension in Dispatch):__C.OS_dispatch_queue.Attributes

:-1: Undefined symbol: associated type descriptor for Element

:-1: Undefined symbol: Swift._assertionFailure(_: Swift.StaticString, _: Swift.String, file: Swift.StaticString, line: Swift.UInt, flags: Swift.UInt32) -> Swift.Never

:-1: Undefined symbol: _swift_allocateGenericValueMetadata

:-1: Undefined symbol: protocol conformance descriptor for Swift.Int : Swift.BinaryInteger in Swift

:-1: Undefined symbol: _OBJC_CLASS_$__TtCs12_SwiftObject

:-1: Undefined symbol: Swift.Hasher.combine<A where A: Swift.Hashable>(A) -> ()

:-1: Undefined symbol: _swift_getWitnessTable

:-1: Undefined symbol: Swift.!== infix(Swift.AnyObject?, Swift.AnyObject?) -> Swift.Bool

:-1: Undefined symbol: protocol conformance descriptor for Dispatch.DispatchWorkItemFlags : Swift.SetAlgebra in Dispatch

:-1: Undefined symbol: _swift_getMetatypeMetadata

:-1: Undefined symbol: method descriptor for Swift.Hashable._rawHashValue(seed: Swift.Int) -> Swift.Int

:-1: Undefined symbol: _swift_initEnumMetadataMultiPayload

:-1: Undefined symbol: method descriptor for Swift.Hashable.hash(into: inout Swift.Hasher) -> ()

:-1: Undefined symbol: static (extension in Foundation):Foundation._ErrorCodeProtocol.~= infix(A, Swift.Error) -> Swift.Bool

:-1: Undefined symbol: base conformance descriptor for Swift.Hashable: Swift.Equatable

:-1: Undefined symbol: method descriptor for static Swift.Equatable.== infix(A, A) -> Swift.Bool

:-1: Undefined symbol: protocol descriptor for Swift.Equatable

:-1: Undefined symbol: value witness table for Builtin.NativeObject

:-1: Undefined symbol: associated type descriptor for Iterator

:-1: Undefined symbol: _swift_dynamicCast

:-1: Undefined symbol: _swift_getEnumCaseMultiPayload

:-1: Undefined symbol: _swift_allocateGenericClassMetadata

:-1: Undefined symbol: protocol witness table for Swift.Int : Swift.CustomStringConvertible in Swift

:-1: Undefined symbol: _swift_getGenericMetadata

:-1: Undefined symbol: _swift_unknownObjectRetain

:-1: Undefined symbol: method descriptor for Swift.CustomDebugStringConvertible.debugDescription.getter : Swift.String

:-1: Undefined symbol: _swift_getFunctionTypeMetadata1

:-1: Undefined symbol: protocol descriptor for Swift.CustomDebugStringConvertible

:-1: Undefined symbol: static Dispatch.DispatchWorkItemFlags.barrier.getter : Dispatch.DispatchWorkItemFlags

:-1: Undefined symbol: _swift_initClassMetadata2

:-1: Undefined symbol: protocol witness table for Swift.Int : Swift.Hashable in Swift

:-1: Undefined symbol: _swift_beginAccess

:-1: Undefined symbol: _swift_endAccess

:-1: Undefined symbol: __swift_FORCE_LOAD_$_swiftMetal

:-1: Undefined symbol: Swift.Array.count.getter : Swift.Int

:-1: Undefined symbol: type metadata for Any

:-1: Undefined symbol: type metadata for Swift.Int

:-1: Undefined symbol: Swift.DefaultStringInterpolation.appendInterpolation<A where A: Swift.CustomStringConvertible>(A) -> ()

:-1: Undefined symbol: _swift_getDynamicType

:-1: Undefined symbol: Swift.Array.append(__owned A) -> ()

:-1: Undefined symbol: type metadata for ()

:-1: Undefined symbol: __swift_FORCE_LOAD_$_swiftUIKit

:-1: Undefined symbol: _swift_getErrorValue

:-1: Undefined symbol: protocol conformance descriptor for [A] : Swift.Sequence in Swift

:-1: Undefined symbol: _OBJC_METACLASS_$__TtCs12_SwiftObject

**Comment by louwailou** [comment]
1. Open ios/YourAppName.xcodeproj in Xcode
2. Right-click on Your App Name in the Project Navigator on the left, and click New File…
3. Create a single empty Swift file to the project (make sure that Your App Name target is selected when adding)
4. when Xcode asks, press Create Bridging Header and do not remove Swift file then. re-run your build.
This should fix the problem

**Comment by mxcl** [comment]
Rebuild your CocoaPods or Carthage checkouts, it works fine with Xcode 10.2, I have 5 projects using it and we've been passing in CI for 5 months with no errors or warnings.

**Comment by wMellon** [comment]
> * Open ios/YourAppName.xcodeproj in Xcode
> * Right-click on Your App Name in the Project Navigator on the left, and click New File…
> * Create a single empty Swift file to the project (make sure that Your App Name target is selected when adding)
> * when Xcode asks, press Create Bridging Header and do not remove Swift file then. re-run your build.
>   This should fix the problem

thanks!

**Comment by mxcl** [comment]
Closing assume fixed. Re-open if not.

**Comment by dhaval-dobariya** [comment]
> > * Open ios/YourAppName.xcodeproj in Xcode
> > * Right-click on Your App Name in the Project Navigator on the left, and click New File…
> > * Create a single empty Swift file to the project (make sure that Your App Name target is selected when adding)
> > * when Xcode asks, press Create Bridging Header and do not remove Swift file then. re-run your build.
> >   This should fix the problem
> 
> thanks!



> * Open ios/YourAppName.xcodeproj in Xcode
> * Right-click on Your App Name in the Project Navigator on the left, and click New File…
> * Create a single empty Swift file to the project (make sure that Your App Name target is selected when adding)
> * when Xcode asks, press Create Bridging Header and do not remove Swift file then. re-run your build.
>   This should fix the problem

Thanks, this works for me.

**Comment by ShaneMatthias** [comment]
> 1. Open ios/YourAppName.xcodeproj in Xcode
> 2. Right-click on Your App Name in the Project Navigator on the left, and click New File…
> 3. Create a single empty Swift file to the project (make sure that Your App Name target is selected when adding)
> 4. when Xcode asks, press Create Bridging Header and do not remove Swift file then. re-run your build.
>    This should fix the problem

Oh thank you kind sir!

**Comment by pedrohcdo** [comment]
> 1. Open ios/YourAppName.xcodeproj in Xcode
> 2. Right-click on Your App Name in the Project Navigator on the left, and click New File…
> 3. Create a single empty Swift file to the project (make sure that Your App Name target is selected when adding)
> 4. when Xcode asks, press Create Bridging Header and do not remove Swift file then. re-run your build.
>    This should fix the problem

YOU SAVE MY DAY!!! BUT WHY THIS IS WORK NOW?

**Comment by 1453alabanda** [comment]
> 1. Open ios/YourAppName.xcodeproj in Xcode
> 2. Right-click on Your App Name in the Project Navigator on the left, and click New File…
> 3. Create a single empty Swift file to the project (make sure that Your App Name target is selected when adding)
> 4. when Xcode asks, press Create Bridging Header and do not remove Swift file then. re-run your build.
>    This should fix the problem

what kind of king are you Thanx

**Comment by yersever** [comment]
> 1. Open ios/YourAppName.xcodeproj in Xcode
> 2. Right-click on Your App Name in the Project Navigator on the left, and click New File…
> 3. Create a single empty Swift file to the project (make sure that Your App Name target is selected when adding)
> 4. when Xcode asks, press Create Bridging Header and do not remove Swift file then. re-run your build.
>    This should fix the problem

Thanx

**Comment by eramudeep** [comment]
> 1. Open ios/YourAppName.xcodeproj in Xcode
> 2. Right-click on Your App Name in the Project Navigator on the left, and click New File…
> 3. Create a single empty Swift file to the project (make sure that Your App Name target is selected when adding)
> 4. when Xcode asks, press Create Bridging Header and do not remove Swift file then. re-run your build.
>    This should fix the problem

Yo Thanks, it worked for me!!!

**Comment by inderarora1996** [comment]
1. Open ios/YourAppName.xcodeproj in Xcode
2.Right-click on Your App Name in the Project Navigator on the left, and click New File…
3. Create a single empty Swift file to the project (make sure that Your App Name target is selected when adding)
4. when Xcode asks, press Create Bridging Header and do not remove Swift file then. re-run your build.
This should fix the problem
Thank You , it worked for me!!!

**Comment by ReemaVinodGangdev** [comment]
> 1. Open ios/YourAppName.xcodeproj in Xcode
> 2. Right-click on Your App Name in the Project Navigator on the left, and click New File…
> 3. Create a single empty Swift file to the project (make sure that Your App Name target is selected when adding)
> 4. when Xcode asks, press Create Bridging Header and do not remove Swift file then. re-run your build.
>    This should fix the problem

You are a gem. Thanks.

**Comment by fabiocberg** [comment]
> 1. Open ios/YourAppName.xcodeproj in Xcode
> 2. Right-click on Your App Name in the Project Navigator on the left, and click New File…
> 3. Create a single empty Swift file to the project (make sure that Your App Name target is selected when adding)
> 4. when Xcode asks, press Create Bridging Header and do not remove Swift file then. re-run your build.
>    This should fix the problem

Simply genius! Work like charm!

**Comment by tgreco** [comment]
You are the man (or woman)! 
I was stuck on this all morning.

**Comment by VishalMahesh** [comment]
Not worked for me. 
Xcode: 12.4
OS: 11.3 Big Sur

Please let me know how to get rid of this issue.

**Comment by alersenkevich** [comment]
> Not worked for me.
> Xcode: 12.4
> OS: 11.3 Big Sur
> 
> Please let me know how to get rid of this issue.

same problem, react-native build doesnt work in xcode(12.5), after ios update on 14.5, version of macos Big Sur 11.4

**Comment by VishalMahesh** [comment]
> > Not worked for me.
> > Xcode: 12.4
> > OS: 11.3 Big Sur
> > Please let me know how to get rid of this issue.
> 
> same problem, react-native build doesnt work in xcode(12.5), after ios update on 14.5, version of macos Big Sur 11.3

I was able to fix the issue by
- commenting use_flipper!() from podfile.
- Reinstalling pods.

**Comment by muzhaqi16** [comment]
It doesn't work for me either on Xcode 12.4 and Mac mini (M1 2020) with macOS Big Sur version 11.3

**Comment by alersenkevich** [comment]
> > > Not worked for me.
> > > Xcode: 12.4
> > > OS: 11.3 Big Sur
> > > Please let me know how to get rid of this issue.
> > 
> > 
> > same problem, react-native build doesnt work in xcode(12.5), after ios update on 14.5, version of macos Big Sur 11.3
> 
> I was able to fix the issue by
> 
> * commenting use_flipper!() from podfile.
> * Reinstalling pods.

commenting use_flipper!() doesn't help me, have you got some other advices?

**Comment by Ricardoi1** [comment]
> 1. Open ios/YourAppName.xcodeproj in Xcode
> 2. Right-click on Your App Name in the Project Navigator on the left, and click New File…
> 3. Create a single empty Swift file to the project (make sure that Your App Name target is selected when adding)
> 4. when Xcode asks, press Create Bridging Header and do not remove Swift file then. re-run your build.
>    This should fix the problem

thank you so much!

**Comment by ShobhitChourasia** [comment]
For me what worked here is:
1. Update cocoapods to latest version using `sudo gem install cocoapods`
2. Update pod spec using `pod repo update`

**Comment by kainy** [comment]
> 1. Open ios/YourAppName.xcodeproj in Xcode
> 2. Right-click on Your App Name in the Project Navigator on the left, and click New File…
> 3. Create a single empty Swift file to the project (make sure that Your App Name target is selected when adding)
> 4. when Xcode asks, press Create Bridging Header and do not remove Swift file then. re-run your build.
>    This should fix the problem

Thanks for your solution，so why is this OK？

**Comment by RomanPodymov** [comment]
Hello @kainy 
Are you still using Xcode 10.2?
