### ISSUE TITLE
Cache first, network later

### ISSUE THREAD

**Issue by mbuchetics** [mxcl/PromiseKit#1060]
Our networking framework has built-in caching with various caching policies. One of them is „cache first, network later“, which returns the cached response (if available) and then the network response.
I would like to wrap the whole thing using PromiseKit. I read that Promises only resolve once, so I am not sure if that’s even possible in our case. Has anyone used a similar approach or do you have any pointers on how to use PromiseKit in such a way?
We are currently using ReactiveSwift but I am eager to try something simpler and more lightweight.

**Comment by mxcl** [comment]
You can't resolve twice, so promises cannot work for this.

**Comment by mbuchetics** [comment]
Thank you 👍
