### ISSUE TITLE
Unable to find a specification for 'PromiseKit'.

### ISSUE THREAD

**Issue by anilabsinc-ajay** [mxcl/PromiseKit#1061]
Pre-downloading: `PromiseKit` from `https://github.com/mxcl/PromiseKit.git`, tag `7.0.0-alpha3`
[!] Unable to find a specification for 'PromiseKit'.

While using cocoa pods 1.7.0

**Comment by mxcl** [comment]
Yes, there is no specification. Basically I don't think we actually support CocoaPods for 7.0 alphas/betas.

**Comment by anilabsinc-ajay** [comment]
@mxcl I think we should support that one too as it is easy to manage the dependencies  through manger like cocoa pods and Carthage, 
We can easily move to the backward if any thing goes wrong

**Comment by mxcl** [comment]
7.0 release will be supported obviously. Just not the alpha. Thanks.

**Comment by educobuci** [comment]
That's a bit confusing since it is literally in the readme:

pod 'PromiseKit', :git => 'https://github.com/mxcl/PromiseKit.git', :branch => 'v7' 

And it doesn't work at all. May I recommend pulling it off or update with a way to try the v7?

**Comment by mxcl** [comment]
done.

**Comment by szotp** [comment]
Documentation is still misleading.
