### ISSUE TITLE
has no shared framework schemes for any of the platforms: watchOS

### ISSUE THREAD

**Issue by JustBetterIOS** [mxcl/PromiseKit#1062]
I want to use "promisekit 1.7.7“in my Apple Watch App ,but Carthage report  error " Dependency "PromiseKit" has no shared framework schemes for any of the platforms: watchOS"，
Do you have any plan to support it?

**Comment by mxcl** [comment]
We support the PromiseKit / watchOS / Carthage combination already. I made a watch app that used it about 18 months ago.
