### ISSUE TITLE
Async queue dispatch blocks calling queue

### ISSUE THREAD

**Issue by cjmconie** [mxcl/PromiseKit#1063]
I have an issue dispatching a closure to a non-main queue asynchronously. The calling queue (in my case the main queue) is blocked for the duration that the non-main queue is busy.
 
So far, I have gathered information from:

- [Starting a chain on a background queue](https://github.com/mxcl/PromiseKit/blob/master/Documentation/Appendix.md#starting-a-chain-on-a-background-queuethread)
- [Issue 743's comments](https://github.com/mxcl/PromiseKit/issues/743#issuecomment-365054414)

#### Info

- Major: PromiseKit 6.0
- Method: Cocoapods

#### Code

My attempt to perform expensive work on a non-main queue is as follows:

1. I defined a serial worker queue:
```swift
let queue = DispatchQueue(label: "com.cam8io.pkit", qos: .userInitiated)
```

2. I created a function which dispatches a closure to the worker queue asynchronously, all of which is wrapped in `Guarantee`'s initialiser.

```swift
func execute() -> Guarantee<Int> {
    
    var total = 0
    return Guarantee { resolver in
        
        queue.async {
            for value in 1...1_000_000_000 {
                total += value
            }
            
            print("[pkit] (custom queue) \(total)")
            resolver(total)
        }
        
    }
    
}
```

3. Then called the function (on the main queue):

```swift
execute().done { total in
      print("[pkit] caller total: \(total)")
}
```

When this executes, the non-main worker queue runs at 100% CPU for 6 or so seconds (which I expected). The issue I have is the main queue also runs at 100% during this interval too. This is as if the closure was dispatched synchronously.

What am I doing wrong? Thanks.

**Comment by GarthSnyder** [comment]
Hi Cameron - your code looks fine to me, and it runs as expected in an iOS app harness under iOS 12.2/Xcode 10.2/PromiseKit 6.8.4. Do you have a complete test project you can upload?

**Comment by cjmconie** [comment]
Hi Garth, after splitting the code out into a separate project I noticed everything ran as expected. So my code above it correct, and PromiseKit is behaving as designed. The issue must due to some other subtle queue interaction in my project - I will investigate further.

Thanks for looking into this! I think it's safe to close this issue.

**Comment by GarthSnyder** [comment]
OK, thanks. Feel free to reopen if necessary.
