### ISSUE TITLE
Firstly failed, recover then do firstly again

### ISSUE THREAD

**Issue by lyc2345** [mxcl/PromiseKit#1064]
* Please specify the PromiseKit major version you are using
`6.8.4`

* Please specify how you installed PromiseKit, ie. Carthage, CocoaPods, SwiftPM or other. If other provide DETAILED information about how you are integrating PromiseKit.
`CocoaPods`

**Here is my question, I want to execute `getPlatforms` first, if it tell you unauthorized, execute `renewAuth`, if new success, execute again `getPlatforms` and there's my code below.**

But what I do `.recover` block I think is reduntant and it must another good way to do my need.

And I also have idea to implement `.then` and pass a `Bool` which represent `renewAuth` success but still think it it not a good way to do it. 

Any help or suggestion is appreciated!

I also found a related issue but there was not any solution for it.
https://github.com/mxcl/PromiseKit/issues/826#issue-311979276

``` swift
func getPlatformListFlow() -> Promise<String> {
        
    func getPlatformPromise() -> Promise<String> {
        return getPlatforms(success: false).recover { error -> Promise<String> in
                
            // if error is unauthorized. do renew auth
            guard let responseError = error as? PlatformResponseError, responseError == .unauthorized else {
                // otherwise throw error to catch
                throw error
            }
            return self.renewAuth(success: true).then { (token) -> Promise<String> in
                return self.getPlatforms(success: true)
            }
        }
    }
    return getPlatformPromise()
}

private func getPlatforms(success: Bool) -> Promise<String> {
    print("action: get platform list success: \(success)")
    let promise = Promise<String> { (seal) in
        after(seconds: 2).done {
            if success {
                seal.fulfill("data: platform list")
            } else {
                seal.reject(PlatformResponseError.unauthorized)
            }
        }
    }
    return promise
}
    
private func renewAuth(success: Bool) -> Promise<String> {
    print("action: renew auth success: \(success)")
    let promise = Promise<String> { seal in
        after(seconds: 2).done {
            if success {
                seal.fulfill("data: token1")
            } else {
                seal.reject(PlatformResponseError.unauthorized)
            }
        }
    }
    return promise
}

```

**Comment by GarthSnyder** [comment]
It looks like you're using `attempt()` as it it's outlined in the Common Patterns document, so I'm interpreting the gist of your question to be, "I understand how to do retries, but I have an additional recovery procedure that I need to perform after each failure, and I'm not sure how to integrate that into the pattern." Is that right?

Your impulse to use `recover()` is, I think, on target. But don't try to actually recover; just run `renewAuth()` and then fail anyway. Leave it to `attempt()` to rerun `getPlatforms()`.

Something like this:

```swift
func getPlatformList(completion: (PlatformResponse<String>) -> Void) {
    attempt(maximumRetryCount: 4) {
        getPlatforms().recover { error in renewAuth().done { throw error }}
    }.done { content in
        completion(.success(content))
    }.catch { error in
        completion(.failure(error))
    }
}
```

Depending on how you want to handle errors originating within `renewAuth()`, you may need to elaborate on this a bit. But the basic idea remains the same: put everything that might have to be in the loop into one chain and let `attempt()` manage repetition.

Incidentally, unless you're dealing with an API boundary beyond which promises aren't allowed, `getPlatformList()` should just be returning a promise itself:

```swift
func getPlatformList() -> Promise<PlatformResponse> {
    return attempt(maximumRetryCount: 4) {
        getPlatforms().recover { error in renewAuth().done { throw error }}
    }
}
```

**Comment by lyc2345** [comment]
Hi, @GarthSnyder 
Thanks for answering me.

The retry method is for this api which has a retry solution for other user who use this api. 
And I think I post retry make misleading my question from the real one.

So I removed the misleading information of my code maybe better for understanding.
``` swift 
private func getPlatformListFlow(allSuccess: Bool) -> Promise<String> {
        
    func getPlatformPromise() -> Promise<String> {
        return getPlatforms(success: false).recover { error -> Promise<String> in
                
            guard let responseError = error as? PlatformResponseError, responseError == .unauthorized else {
                throw error
            }
            return self.renewAuth(success: allSuccess).then { (token) -> Promise<String> in
                 ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                 // how can I use the same `getPlatforms(success:) outside this block
                return self.getPlatforms(success: allSuccess)
                ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
            }
        }
    }
    return getPlatformPromise()
}
```

**Comment by derpoliuk** [comment]
@GarthSnyder off-topic questions: when I do this I get compiler errors:

```swift
// Cannot convert return expression of type 'Promise<String>' to return type 'Guarantee<String>'
getPlatforms().recover { error in renewAuth().done { throw error }}
```

Am I doing something wrong here? Sorry if it's a basic question, I'm relatively new to PromiseKit.

**Comment by GarthSnyder** [comment]
Stan, I'm very sorry, but I am still not understanding the question. What do you mean by "using the same 'getPlatforms(success:)' outside this block"?

**Comment by GarthSnyder** [comment]
> derpoliuk wrote: As usual shortly after asking question I figured out the solution: explicitly write return type of closure.

Good instincts! That is the solution to many PromiseKit errors.

**Comment by lyc2345** [comment]
@GarthSnyder because I use the same function of `getPlatfroms` and I handle `renewAuth` and `getPlatforms` in recover block that I think a little bit callback hell. So I want to know is there any way to make this more elegant.

**Comment by GarthSnyder** [comment]
> because I use the same function of getPlatfroms twice and I handle renewAuth and getPlatforms in recover block that I think a little bit callback hell...is there any way to make this more elegant...I want one block just return only one promise, is that possible?

Well, elegance is in the eye of the beholder.  I don't think there's anything wrong with your current structure.

The `renewAuth/getPlatforms` promise chain is a completely separate chain from the original `getPlatforms` chain. They become related through the agency of `recover`, but trying to format all these components as if they were one linear chain would be somewhat misleading.

As with any code, if you think there's too much complexity visible locally, you're free to separate out parts of the logic into distinct functions. E.g., 

```swift
func performWithRecovery<T>(_ makeWorkPromise: @escaping () -> Promise<T>,
        _ makeRecoveryPromise: @escaping () throws -> Promise<Void>) -> Promise<T>
{
    return makeWorkPromise().recover { error in
        try makeRecoveryPromise().then { makeWorkPromise() }
    }
}

performWithRecovery(getPlatforms, renewAuth).done {
    ...
}
```

But this is really just a variant of `attempt(1)`. In this particular case, it seems to complicate more than it simplifies.

**Comment by lyc2345** [comment]
OK, I got it. At the first time I thought there maybe a better solution for my need. 

Thanks for the kindness help. Appreciated!
