### ISSUE TITLE
Use promise and gurantee interchangeably

### ISSUE THREAD

**Issue by Yannmm** [mxcl/PromiseKit#1067]
Hey, I'm new to PMK. So I start by reading [GettingStarted.md](https://github.com/mxcl/PromiseKit/blob/master/Documentation/GettingStarted.md).

It says we can use Use promise and guarantee interchangeably. And here's the sample provided:

```
func fetch() -> Promise<String> {
    return Guarantee { seal in
        fetch { result in
            seal(result)
        }
    }
}
```

However, this won't build and the compiler says:

`Cannot convert return expression of type 'Guarantee<String>' to return type 'Promise<String>'`

I went through the source code. It seems `Promise` and `Guarantee` are two different classes, only share common ground by `Thenable` protocol.

So is the guide wrong or I miss something?

Thank you for the great work.

**Comment by mxcl** [comment]
Docs are wrong I think, you have to do `Promise(guarantee)`.

You can use them interchangeable if you return `Thenable` but this requires a lot of generics trickery to get right and I wouldn't recommend it.

**Comment by Yannmm** [comment]
Got it, many thanks. 😊
