### ISSUE TITLE
Can't cast to the same type - Please help

### ISSUE THREAD

**Issue by chadbrochill317** [mxcl/PromiseKit#1069]
Hello, 
I have figured nearly everything, but am having some issues using casting a custom object from a promise. I have attached the error and code below, please help! 

Thanks. 
<img width="519" alt="Screen Shot 2019-06-06 at 9 55 55 PM" src="https://user-images.githubusercontent.com/11186917/59107569-f1bcc480-8906-11e9-8c64-764a507f8659.png">

**Comment by GarthSnyder** [comment]
The error message is obscuring some of the code, but it looks like you’re not returning a promise there. So you want “done“ rather than “then“.

**Comment by chadbrochill317** [comment]
Can you use multiple dones?

**Comment by mxcl** [comment]
> Can you use multiple dones?

Despite the naming making it sound otherwise, yes you can chain `done`.

**Comment by chadbrochill317** [comment]
Thanks guys! 
Appreciate the help.

**Comment by mxcl** [comment]
Closing, reopen if you need more help.

**Comment by chadbrochill317** [comment]
Hello, 
Sorry just one more thing. The "bob in" is not carrying over the value from the promisegetdata() function, which doesn't build my geocode object, which essentially makes this whole thing useless. Could you please give suggestion as to why that is?

**Comment by chadbrochill317** [comment]
I already changed the done. 
So i have 
Firstly
Then
Done
Done

**Comment by chadbrochill317** [comment]
Never mind i figured it all out.
Now just wondering if i could squeeze a when in there, as its still completing too fast for me to download, geocode, then write to DB.

**Comment by chadbrochill317** [comment]
I am getting this error
Cannot invoke 'when(fulfilled:)' with an argument list of type '(fulfilled: Promise<String>)'

**Comment by GarthSnyder** [comment]
Can you paste your code?

**Comment by chadbrochill317** [comment]
func whammy() {
        if (counter == 9100){
            return
        }
        firstly {
            promiseGetData()
            }.then { bob in
                self.promiseForwardGeocode(address: bob)
            }.done { (obj: GeocodeObject) in
                self.promiseWriteToDatabase(data: obj)
            }.ensure {
                self.counter = self.counter + 1
                self.whammy()
            }.catch { error in
                // handle error
                print(error.localizedDescription)
        }
    }

**Comment by chadbrochill317** [comment]
I need each block to wait. So I need to use when, but it keeps giving me those errors.

**Comment by GarthSnyder** [comment]
OK, but there's no `when` in that code.

In general, you should just chain together everything that needs to run in sequence. If some operations need to run N times (for some relatively small N), just add N instances to the chain.

```
func readAndGeocode() -> Promise<Void> {
    return promiseGetData().then { bob in
        self.promiseForwardGeocode(address: bob)
    }.then { obj in
        self.promiseWriteToDatabase(data: obj)
    }
}

func multiRead() -> Promise<Void> {
    var promise = Promise.value(())
    for _ in 1...3 {
        promise = promise.then {
            self.readAndGeocode()
        }
    }
    return promise.catch { error in
        print(error.localizedDescription)
    }
}
```

Whatever you need to do after all iterations are complete, just chain it onto the promise returned by `multiRead`. (I'm assuming `promiseWriteToDatabase` returns `Promise<Void>`).

**Comment by chadbrochill317** [comment]
Hello, 
I am still lost, and I can't get when to work. 
The data gets downloaded too slow, and the Geocode never works because the address is not there to be fulfilled. How does When work?

**Comment by chadbrochill317** [comment]
func whammy4() {
        if (counter == 50){
            return
        }
        firstly {
            when(fulfilled: promiseGetData())
            }.then { bob in
                self.promiseForwardGeocode(address: bob)
            }.ensure {
                self.counter = self.counter + 1
                self.whammy3()
            }.catch { error in
                // handle error
                print(error.localizedDescription)
        }
        print(latArray.count)
    }

**Comment by GarthSnyder** [comment]
Did you read the previous answer?
