### ISSUE TITLE
race function type inference

### ISSUE THREAD

**Issue by Yannmm** [mxcl/PromiseKit#1070]
Given the signature of `race`:

```
public func race<U: Thenable>(_ thenables: U...) -> Promise<U.T>
```

It's reasonable to infer that it receive a sequence of `Thenable`s as paramter.

However, when I use it like this:

```
let timeout = after(seconds: 4)
race(Promise.value(1).asVoid(), timeout)
```

The compiler says: 

>Cannot convert value of type 'Guarantee<Void>' to expected argument type 'Promise<Void>'

Change timeout to Promise explicitly:

```
race(Promise.value(1).asVoid(), Promise(timeout))
```

It works.

I thinks it's has something to do with the type inference system. plz check.

**Comment by Yannmm** [comment]
BTW, the array-parameter-type `race` won't work neigher.

```
public func race<U: Thenable>(_ thenables: [U]) -> Promise<U.T>
```

**Comment by mxcl** [comment]
Swift won’t allow variadic mixing of types, it’s a known issue they plan to fix, nothing we can do.
