### ISSUE TITLE
Cocoapod install of PromiseKit submodule CoreLocation

### ISSUE THREAD

**Issue by timbms** [mxcl/PromiseKit#1072]
* Please specify the PromiseKit major version you are using: 6.8.4
* PromiseKit and the submodule are installed with CocoaPods' Podfile
```
  pod 'PromiseKit', '~> 6.8'
  pod 'PromiseKit/CoreLocation'
```
* Installation of both modules is complete. Though CocoaPods only reports the installation of
```
pod install: 
Analyzing dependencies
Downloading dependencies
Using DZNEmptyDataSet (1.8.1)
Using LicensesViewController (0.7.0)
Using OHHTTPStubs (8.0.0)
Using PromiseKit (6.8.4)
Using SQLite.swift (0.12.0)
Using SimulatorStatusMagic (2.4.1)
Generating Pods project
Integrating client project
Sending stats 
```
But PromiseKit/CoreLocation lags behind recent version that takes into account swift 5 update.
For instance in CLLocationManage+Promise.swift line
`@available(*, deprecated: 5.0, renamed: "requestLocation") 
`warnings are still thrown
> Unexpected version number in 'available' attribute for non-specific platform '*'

**Comment by mxcl** [comment]
Thanks. What's the problem?

**Comment by timbms** [comment]
There are still warnings when compiling PromiseKit/CoreLocation though fixes for warnings are already
in code base

**Comment by mxcl** [comment]
I pushed a new revision of everything. Wait a few hours for CI to push it to CocoaPods
