### ISSUE TITLE
Cannot convert value of type 'PMKFinalizer' to expected argument type 'Promise<Void>'

### ISSUE THREAD

**Issue by YMaxim** [mxcl/PromiseKit#1076]
PromiseKit version: 6.8.4
Previous PromiseKit version: 4.5.2
Xcode version: 10.2.1
CocoaPods version: 1.7.1

This code worked with **PromiseKit v.4.5.2**.

```
func getReminderIds(idArray: [Int]) {

    var reminderPromises: [Promise<Void>] = []

    for id in idArray {
        if let prom = self.delegate?.getReminders(id).then({ (reminderArray) -> Promise<Void> in
            Utils.logMessage("Reminders for asset \(id): \(reminderArray)")
            self.reminders[String(id)] = reminderArray
        }).catch({ (err) in
            self.reminders[String(id)] = nil
            Utils.logMessage("Error getting reminders for asset \(id): \(err)")
        }){

            reminderPromises.append(prom)
        }

    }

    _ = when(fulfilled: reminderPromises).done { results -> Void in
        self.collectionView?.refreshCollection(collection: 0)
    }

}
```

But after updating to **PromiseKit v.6.8.4** I get the error "Cannot convert value of type 'PMKFinalizer' to expected argument type 'Promise'" in this line:
`reminderPromises.append(prom)`
 
When did I change to `if let prom = self.delegate?.getReminders(assetId: ID).done({ (reminders) in` I also saw this error.

**Comment by mxcl** [comment]
`catch` returns `PMKFinalizer` and not `Promise<Void>`, move the catch to a higher level. See our documentation for more details.
