### ISSUE TITLE
How to properly cancel URLSessionTasks

### ISSUE THREAD

**Issue by geraldeersteling** [mxcl/PromiseKit#1077]
I'm using PromiseKit 6 together with `URLSession`, but I'm confused as how to properly cancel the tasks I create in promises.

I've read the [part about cancellation](https://github.com/mxcl/PromiseKit/blob/master/Documentation/CommonPatterns.md#cancellation) and understand that PromiseKit is not able to 'just create' a `cancel()` for promises (without referring to PromiseKit 7). But I'm not sure how to implement it and forgive me if it has been asked before; I'm unable to find an answer.

Currently I'm using the following method to start a data task:

 `dataTask(_: PMKNamespacer, with convertible: URLRequestConvertible) -> Promise<(data: Data, response: URLResponse)>` 

And a snippet of my code:

```swift

func start(_ request: URLRequest) -> Promise<(data: Data, response: URLResponse)> {
    return firstly {
            DispatchQueue.main.async {
                UIApplication.shared.isNetworkActivityIndicatorVisible = true
            }
            return after(seconds: 0)
        }
        .then(on: queue) {
            session.dataTask(.promise, with: request) ///  <-- [ 1 ]
        }
        .ensure { UIApplication.shared.isNetworkActivityIndicatorVisible = false }
}
```

The line `session.dataTask(.promise, with: request)` doesn't give back the task, but rather a promise. I'm confused as to how this task can then be cancelled if needed.

If someone has an example, I'd be really grateful.

**Comment by mxcl** [comment]
You have to create the URLSession promise yourself, you cannot use PromiseKit’s extensions. Then you have access to the actual URLSessionTask object and can expose its `cancel` function.

**Comment by geraldeersteling** [comment]
Hmm that's too bad then, but now I know. Thanks!
