### ISSUE TITLE
Combination of `ensure` and `then`

### ISSUE THREAD

**Issue by Jon889** [mxcl/PromiseKit#1081]
I'm using PromiseKit 6.10.0 installed, by CocoaPods.

I've read the docs and the troubleshooting guide, so I've tried to solve this by myself, but haven't been able to. I'm new to PromiseKit so apologies for any misuse of terminology.

I'm wanting to have a body that is executed whether the chain has previously been rejected or not, in the same way that `ensure` works. But unlike `ensure` the body returns a `Thenable` (the types could be the same or different).

This is the (pseudo) code I have at the moment:

```
fetchUsersFromServer()
.then { rawUserData in
  processAndSaveUsersToCache(rawUserData)
}.ensure {
  readUsersFromCache()
  .done { users in
    presentUserList(users)
  }.catch { error in
    presentError(error)
  }
}.catch { error in
  presentError(error)
}
```

This just fetches the users, caches it and displays it. If there is no connection and the `fetchUsersFromServer` fails, then the `readUsersFromCache` is still executed and hopefully the data was fetched previously and can be retrieved.

The problem here is the duplicate `catch`es and having to have an indented chain.

Ideally the code would look like this:

```
fetchUsersFromServer()
.then { rawUserData: Data in
  processAndSaveUsersToCache(rawUserData) // returns Promise<Void>
}.ensureThen { // *** This is the bit I'm missing (some other name might be better) ***
  readUsersFromCache()
}.done { users: [User] in
    presentUserList(users)
}.catch { error in
  presentError(error)
}
```

I thought `recover` was almost what I wanted but that is only executed when there's an error, and it also has a requirement that the type in the Promise doesn't change.

I think this is the signature of the method I'm looking for (on `Thenable`):
```
func ensureThen<U: Thenable>(on: DispatchQueue? = conf.Q.map, flags: DispatchWorkItemFlags? = nil, _ body: @escaping(Result<T>) throws -> U) -> Promise<U.T>
```

Am I missing something, or is there a reason this doesn't exist? Would there be a better way to write the code?

**Comment by mxcl** [comment]
https://github.com/mxcl/PromiseKit/blob/master/Sources/Catchable.swift#L152-L170

**Comment by Jon889** [comment]
@mxcl sorry should’ve used a different temporary name. That one doesn’t pass anything into the body, and requires a `Garantee<Void>` is returned. It should be possible to return a promise/thenable.

**Comment by mxcl** [comment]
We decided not to offer one that can return a Promise since this would make it possible for the `ensure` to trump any previous error that may have been emitted if it also fails, which would lead to unreliable error handling.

**Comment by mxcl** [comment]
I suggest changing `processAndSaveUsersToCache` to return `Promise<[User]>` and altering the chain thus:

```swift
firstly {
    fetchUsersFromServer()
}.then { data -> Promise<[User]> in
    processAndSaveUsersToCache(data)
}.recover { _ -> Promise<[User]> in
    readUsersFromCache()
}.done { users: [User] in
    presentUserList(users)
}.catch { error in
    presentError(error)
}
```

**Comment by Jon889** [comment]
Thanks for your speedy replies :)

> We decided not to offer one that can return a Promise since this would make it possible for the ensure to trump any previous error that may have been emitted if it also fails, which would lead to unreliable error handling.

Ah I thought that is what recover does? As in if an earlier error happens you can instead return a valid promise, and the chain continues? I guess a better name for this post might have been a combination of ensure and recover, as in a recover that is also called on success.

**Comment by Jon889** [comment]
> I suggest changing `processAndSaveUsersToCache` to return `Promise<[User]>` and altering the chain thus:
> 
> ```swift
> firstly {
>     fetchUsersFromServer()
> }.then { data -> Promise<[User]> in
>     processAndSaveUsersToCache(data)
> }.recover { _ -> Promise<[User]> in
>     readUsersFromCache()
> }.done { users: [User] in
>     presentUserList(users)
> }.catch { error in
>     presentError(error)
> }
> ```

That would work but wouldn't be ideal as there are other places the data is saved but doesn't need to be read.

I guess this would work, and its what I'm looking to combine:

```
firstly {
    fetchUsersFromServer()
}.then { data in
    processAndSaveUsersToCache(data)
}.then { _ -> Promise<[User]> in
    readUsersFromCache() // It'd be nice if this and the below block could be deduplicated
}.recover { _ -> Promise<[User]> in
    readUsersFromCache()
}.done { users: [User] in
    presentUserList(users)
}.catch { error in
    presentError(error)
}
```

**Comment by mxcl** [comment]
I don't see the harm in having `processAndSaveUsersToCache` return the users array, but either way we don't provide a better mechanism, sorry. So pick either my option or yours. LMK if you need more help.

**Comment by Jon889** [comment]
That's probably the correct way of doing it :) Having to deal with an existing system, and really shouldn't be writing to the cache and then reading it back out. Thanks!
