### ISSUE TITLE
Re-execute failed promise chain

### ISSUE THREAD

**Issue by marcuswu0814** [mxcl/PromiseKit#1082]
PromiseKit version: *6.10*

According to [**Chaining Sequences**](https://github.com/mxcl/PromiseKit/blob/master/Documentation/CommonPatterns.md#chaining-sequences), I chain my job and execute them one by one.

For example, job queue like this: `A -> B-> C -> D -> E`, and code:

```swift
let jobs: [JobPromise] = [a, b, c, d, e]

var p = Promise()
  for job in jobs {
    p = p.then {
	  job.execute()
    }
}

p.done {
  // success
}.catch {
  // fail
}

```

If my job `C`  fail and catch the error, is there have better way to restart the chain from job `C` ?

**Comment by mxcl** [comment]
Promises cannot be “restarted” but you could instead have an array of `[() -> Promise]` and then add a `recover` to the chain and loop again.

**Comment by marcuswu0814** [comment]
Thanks for quick response, finally I solve my issue used linked list to execute my jobs, and store fail job then re-execute it.
It work well. 😀
