### ISSUE TITLE
6.8.4 failing with Carthage

### ISSUE THREAD

**Issue by fallenhaivision** [mxcl/PromiseKit#1083]
Cathage update is failing with the following
****
git checkout --quiet 456a18dd73cf3cd9763bfb407af5e75d66468227 (launched in /Users/allenf/repo/mobi/Vendor/Carthage/Checkouts/PromiseKit/Extensions/CoreBluetooth)) failed with exit code 128:
fatal: reference is not a tree: 456a18dd73cf3cd9763bfb407af5e75d66468227
****

I've tried "rm -rf ~/Library/Caches/org.carthage.CarthageKit" with no success

Thank you

**Comment by danmurrelljr** [comment]
This seems to be an issue with the 6.11.0 release from this morning.

Hardcode your cartfile to 6.10.0 for now until it gets resolved.
