### ISSUE TITLE
Carthage issue with Xcode 11 betas 4 & 5

### ISSUE THREAD

**Issue by ivan-konov** [mxcl/PromiseKit#1084]
* PromiseKit major version:
6.x and V7 branch

* Install method:
Carthage 

Hello,

I have been getting this error when trying to update/build PromiseKit through Carthage with the last 2 betas of Xcode 11. I am not sure which side is the problem on since Carthage needs fixes to work properly with the betas but wanted to share with you.

Thanks!

This is the console message:

> *** Fetching PromiseKit
> A shell task (/usr/bin/env git fetch --prune --quiet https://github.com/mxcl/PromiseKit.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/* (launched in /Users/my_home_directory/Library/Caches/org.carthage.CarthageKit/dependencies/PromiseKit)) failed with exit code 1
>

**Comment by mxcl** [comment]
Report to Carthage.

**Comment by ivan-konov** [comment]
I found this in their issues list:
[https://github.com/Carthage/Carthage/issues/2786](url)

You might want to check your tags just in case.
