### ISSUE TITLE
Use promiseWithValue in Swift code

### ISSUE THREAD

**Issue by piyushg098** [mxcl/PromiseKit#1087]
We have a project with both Objc and Swift.
I am a newbie to PromiseKit

**Version details**
**PromiseKit version**: 6.8.3
**Swift version**: 5
**Pods used**:  PromiseKIt and PromiseKit/Alamofire
 
Now ObjC **`AnyPromise.h`** there's a method:
`+ (instancetype __nonnull)promiseWithValue:(__nullable id)value NS_REFINED_FOR_SWIFT;`
I need to use this method in Swift and send `NSError` as a parameter
Something like this but in Swift:
`[AnyPromise promiseWithValue:TheInternet.cannotBeTrusted]`

Now although the method declaration in `**AnyPromise.h**` says `NS_REFINED_FOR_SWIFT`, how do I find its redefined version for Swift?

**Comment by mxcl** [comment]
`AnyPromise(Promise(error:  myError))`
