### ISSUE TITLE
Struggling with chaining network requests

### ISSUE THREAD

**Issue by danmartyn** [mxcl/PromiseKit#1098]
Hi there, I've just started using PromiseKit, and am struggling with chaining requests together instead of embedding them...

I'm using PromiseKit 6.11.0 and PMKFoundation 3.3.3 (using SwiftPM in Xcode 11) targeting iOS 13 in a sample project.

I'm using the JSONPlaceholder API to try and get things working. I've created a networking engine that has 2 methods:

```
import Foundation
import PromiseKit

class JSONPlaceholderNetworkEngine: NetworkEngine {

    func getPosts() -> Promise<GetPostsRequest.Response> {
        return execute(GetPostsRequest())
    }

    func getPost(id: Int) -> Promise<GetPostRequest.Response> {
        return execute(GetPostRequest(id: id))
    }

}
```

The base class execute method looks like this:
```
func execute<Request: NetworkRequest>(_ request: Request) -> Promise<Request.Response> {
    guard let urlRequest = request.urlRequest(schemeOverride: scheme, hostOverride: host, additionalHeaders: defaultHeaders) else {
        return Promise(error: NetworkError.badURLRequest)
    }
    return session.dataTask(.promise, with: urlRequest).compactMap { (data, response) -> Request.Response? in
        guard self.validate(response) else { throw NetworkError.invalidResponse }
        return try request.jsonDecoder.decode(Request.Response.self, from: data)
    }
}
```

NetworkRequest's have an associated type, `Response` that is `Decodable`.

What I'm trying to accomplish is in the ViewController `viewDidLoad` method, load the posts using `getPosts()` then once they are loaded, pick a random one and load it's details using `getPost(id: randomPost.id)`, like this:

```
jsonNetworkEngine.getPosts().then { posts in
    let randomPost = posts.randomElement()!
    print("Got \(posts.count) posts! Choosing post \(randomPost.id) to load details:")

    self.jsonNetworkEngine.getPost(id: randomPost.id)
}.then { post in
    print(post)
}.catch { error in
    print("Error: \(error)")
}
```

But it errors at the first line `jsonNetworkEngine.getPosts().then { posts in` highlighting the `{` and saying `Unable to infer complex closure return type; add explicit type to disambiguate`.

I can make it work if I write the code like this:
```
jsonNetworkEngine.getPosts().done { posts in
    let randomPost = posts.randomElement()!
    print("Got \(posts.count) posts! Choosing post \(randomPost.id) to load details:")

    self.jsonNetworkEngine.getPost(id: randomPost.id).done { post in
        print(post)
    }.catch { error in
        print("Error: \(error)")
    }
}.catch { error in
    print("Error: \(error)")
}
```

But that seems to break the whole idea of not ending up in "call back hell" if the subsequent calls all need to be embedded?

**Comment by mxcl** [comment]
Please see our 
[Troubleshooting Guide](https://github.com/mxcl/PromiseKit/blob/master/Documentation/Troubleshooting.md)

**Comment by danmartyn** [comment]
Ah, it was the return type! I did read the trouble shooting guide and was trying to specify the type but that still wasn't working. Somehow missed the return part though. Thanks for the incredibly fast reply!
