### ISSUE TITLE
Swift Package Manager and CLLocationManager extension

### ISSUE THREAD

**Issue by anestis1000** [mxcl/PromiseKit#1100]
I try to use the Swift Package Manager. I have no problem using with the promises classes and functions. But I can't use the CLLocationManager extension. I imported the PromiseKit, but the extensions folder is outside the Sources folder of Swift Package Manager. I think this is the problem. Any suggestion? # #

**Comment by mxcl** [comment]
As per our copious documentation, SwiftPM is not currently supported for the CoreLocation extensions. Feel free to add it here:

https://github.com/PromiseKit/CoreLocation

**Comment by Overcot** [comment]
I guess this is done already in CoreLocation library

**Comment by RomanPodymov** [comment]
Hello @anestis1000 
SPM is supported for https://github.com/PromiseKit/CoreLocation, please close the issue.
