### ISSUE TITLE
PMKManifold Not returning two values in Swift

### ISSUE THREAD

**Issue by bmalumphy** [mxcl/PromiseKit#1106]
PromiseKit version = 6.10.0 
-Installed via Cocoapods

We're having some issues incorporating legacy code in Obj-C into new Swift classes. What we'd like to do is have a function in Obj-C that returns a PMKManifold as an AnyPromise to return it's tuple equivalent in Swift. Right now because it's an AnyPromise it only returns the first value of the PMKManifold in Swift. So we can't capture both variables.

Below is an example:

```Objective-C
//ObjcClass
+ (AnyPromise *)foo {
    //Do Stuff
    return resolve(PMKManifold(variable1, variable2));
}
```
```Swift
//Swift Class
func bar(){
    ObjcClass.foo().map{ variable1, variable2 in
        //Do stuff
    }
}
```

We can return the first object and cast it into its appropriate Type in Swift, but not the second. A compiler error shows that 1 variable is expected, not 2. We've tried experimenting with .then and such variations on .map. We've also investigated alternatives to PMKManifold for returning Tuple-like structures in Obj-C, but documentation on such an old version of PromiseKit seems sparse on Google and on here. Apologies if the answer is obvious. Also, it would be very expensive to start rewriting the old code into Swift. Like a lot of legacy code from the beginning of a company it's highly coupled.

**Comment by mxcl** [comment]
Yeah, known issue, probably the ideal thing to do is for Swift pass through an `NSArray *`, this would be breaking behavior, but probably the right thing to do.

**Comment by bmalumphy** [comment]
The team and I managed to hobble together a solution.  The code was highly coupled, but this hack solution worked.

-Isolating the case we needed with a BOOL argument within the Objective-C Code
-Returning a Custom Object (Written in Swift, bridged to Objective-C) for the case we needed
```Objective-C
+(AnyPromise *)fooWithParameters:(Any *)parameters caseBool:(BOOL)caseBool {
    ...
    if(caseBool){
        CustomObject *customObject = [[CustomObject alloc] initWithParameters1:parameter1 andParameter2:parameter2];
        return resolve(customObject);
    }
    return resolve(PMKManifold(oldParameter1, oldParameter2);
}
```

Write the custom object in Swift (Or Objc if you're a masochist) like this
```Swift
public class CustomObject: NSObject {
    public parameter1: Object1
    public parameter2: Object2

    @objc(initWithParameter1:andParameter2:)
    public init(parameter1:Object1, parameter2:Object2){
        self.parameter1 = parameter1
        self.parameter2 = parameter2
    }
}
```
The public tag is necessary and don't neglect it.

**Comment by mxcl** [comment]
Glad you found something that worked, but if you care to fix the bridging code we'll take the PR. Otherwise this will be a useful resource for others should they need it. Thanks.
