### ISSUE TITLE
Resolve on 'Resolver' requires the types 'String' and 'Void' be equivalent

### ISSUE THREAD

**Issue by koko236** [mxcl/PromiseKit#1108]
- PromiseKit v6.11 installed using Swift Package Manager integrated into XCode.
- iOS Swift 5 Project in XCode 11.1

Hi, 
I'm trying to use PromiseKit v6 in iOS Swift 5 app but I trip on a very basic issue. The code below throws a compiler error.

```
let p1 = Promise<String> { seal in
    seal.resolve("Foo"); /// Referencing instance method 'resolve' on 'Resolver'
                          /// requires the types 'String' and 'Void' be equivalent
} 
```
Actual code was a bit more involved but even this most stripped down example results in the same problem. I suspect this is something utterly stupid but what am I missing? I temporarily switched to to google/promises and it works fine but I would prefer to use PromiseKit once I make it work. :-)

**Comment by mxcl** [comment]
https://github.com/mxcl/PromiseKit/blob/master/Sources/Resolver.swift#L28

Resolve takes `Result`, you want to be using `fulfill`. Read the docs.
