### ISSUE TITLE
Running .then synchronously if on the same queue

### ISSUE THREAD

**Issue by michaeleisel** [mxcl/PromiseKit#1110]
* version: 4.5.1 (but happy to upgrade)
* method: Cocoapods

There are many places where I need to run a promise synchronously. For example, if I'm about to push a view controller and I try to update a view using `.then`, even if the promise is resolved already it will still enqueue for later on the main thread, so the push animation's frames are generated without the updated view. Or in other cases, a chain of `.then`s that are sometimes already completed causes an unnecessary slowdown since each one is being enqueued rather than run synchronously. I see that there's zalgo and saldo, but they don't allow me to specify the queue, and in the first case I mentioned it needs to update the view on the main thread. I see they point out a race condition:
```
       var x = 0
       foo.then(on: zalgo) {
           print(x)  // => 0 or 1
       }
       x++
```
But the guarantee that `.then` will execute after `x++` (notwithstanding zalgo and salgo) does not seem obvious anyways, so my code is generally written not to assume that.

So, I'm curious, is there an established way to do (pseudocode):
```
if (promise.isResolved()) {
  then(promise.value!)
} else {
  promise.enqueueForLater(then)
}
```

**Comment by mxcl** [comment]
`zalgo` will execute immediately if the promise is resolved, but if not it will run on the queue the previous part of the chain used, so maybe not the main thread.

Honestly I don’t see your problem precisely.

>  For example, if I'm about to push a view controller and I try to update a view using .then, even if the promise is resolved already it will still enqueue for later on the main thread

CoreAnimation itself is heavily optimized, and almost certainly does nothing for off screen views.

> Or in other cases, a chain of .thens that are sometimes already completed causes an unnecessary slowdown since each one is being enqueued rather than run synchronously

What is the slowdown you refer to? Promises are pretty light-weight.

**Comment by michaeleisel** [comment]
CoreAnimation would create the animation frames with the view prior to it being updated, so for the duration of the push animation, the view does not appear updated. The slowdown I'm referring to is from each `.then` being scheduled. It doesn't impact overall CPU usage much, but it does cause each `.then` to be executed later

**Comment by mxcl** [comment]
Well either way, there is no better way to do what you want. You could write your own extension if you need it.
