### ISSUE TITLE
Recommended pattern for chaining multiple promises

### ISSUE THREAD

**Issue by SolorzanoJose** [mxcl/PromiseKit#1111]
I read the design patterns document and I've been using when(fulfilled:) and when(resolved:) to wait on multiple promises, however, I would like to organize these type of calls with a vertical chaining approach, I currently resort to nesting them instead:

```
_ = self.onePromise().done { result in

            _ = when(fulfilled: multiplePromises).done { results in

                      _ = when(fulfilled: morePromises).done { results in
                
                       }
            }
}
```

**Comment by mxcl** [comment]
This isn’t chaining, you will lose errors. You need to use `then`.

```swift
return self.onePromise().then { result in
    when(fulfilled: multiplePromises)
}.then { results in
    when(fulfilled: morePromises).done { results in
}
```

**Comment by SolorzanoJose** [comment]
@mxcl I'm trying to use this but I'm getting pending promise deallocated? in "multiplePromises"

**Comment by mxcl** [comment]
We have documentation to help you with that. You're doing more stuff wrong. You should read our documentation. Thanks.
