### ISSUE TITLE
Request: Wait for one promise to fulfill while ignoring rejections

### ISSUE THREAD

**Issue by pimnijman** [mxcl/PromiseKit#1114]
I have multiple promises that can be pending for a long time, or get rejected early on. I'm looking for a way to find out which is the first to fulfill.

For example: One promise gets rejected, another fulfills and a third is still pending.
In this case I would like the new promise to fulfill.
When all promises get rejected I would like the new promise to reject with an array of errors.

I can't use `race`, since it will reject once my first promise will reject.
I can't use `when(fulfilled:)`, since it will reject once one of my promise rejects and will continue after the first promise fulfills.
I can't use `when(resolved:)`, since it will continue after the first promise resolves.

What I'm looking for might not exist (yet) but I would expect it to be called something like  `race(fulfilled:)`

**Comment by mxcl** [comment]
`when(resolved:)` may work, but it still waits for all promises. `race` will work, hold onto the promises and check each one before deciding what to do.

**Comment by icedice** [comment]
> `when(resolved:)` may work, but it still waits for all promises. `race` will work, hold onto the promises and check each one before deciding what to do.

Could you show an example on how to this? I'm using race for caching. I want to call cache and network at the same time and then return what ever finish first, however right now if cache is empty and the promise rejects I will not get the result from the network.

**Comment by mxcl** [comment]
Implemented.
