### ISSUE TITLE
EXC_BAD_ACCESS when using PromiseKit installed with SwiftPM

### ISSUE THREAD

**Issue by jimmya** [mxcl/PromiseKit#1115]
**Edit: I just noticed the other issues regarding this. Apologies. Can someone please close this or mark it as duplicate?**

I'm working on a project where I'm importing my dependencies using SwiftPM but when creating a new promise I get a EXC_BAD_ACCESS on the `init` of a promise.

My code looks like this:
```swift
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        
        test().done { result in
            print(result)
        }.catch { error in
            print(error)
        }
    }

    func test() -> Promise<String> {
        Promise.value("Hello world!")
    }
```
This result in the bad access error in this piece of code (Promise.swift line 100):
```swift
init(_: PMKUnambiguousInitializer) {
    box = EmptyBox()
}
```
If I change my code to:
```swift
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.

        test().done { result in
            print(result)
        }.catch { error in
            print(error)
        }
    }

    func test() -> Promise<String> {
        return Promise { seal in
            seal.fulfill("Hello world!")
        }
    }
```
It results in the same error on this piece of code (Promise.swift line 58):
```swift
/// Initialize a new promise that can be resolved with the provided `Resolver`.
    public init(resolver body: (Resolver<T>) throws -> Void) {
        box = EmptyBox()
```

The weird thing is. When adding PromiseKit using CocoaPods everything is working fine!

**Comment by jimmya** [comment]
I just noticed the other issues regarding this. Apologies.

**Comment by lucasmpaim** [comment]
How you fixed it? I'm with the same problem

**Comment by jimmya** [comment]
@lucasmpaim good call, I should have mentioned that: https://github.com/mxcl/PromiseKit/issues/1099#issuecomment-548976601

**Comment by bimawa** [comment]
Guys, how to add  DEAD_CODE_STRIPPING = NO to Package.swift?
