### ISSUE TITLE
Canceling nested Promise gives warning: "pending promise deallocated"

### ISSUE THREAD

**Issue by vinczebalazs** [mxcl/PromiseKit#1119]
**PromiseKit 6.1.2 (CocoaPods)**

Hi! 👋 

I have the following code snippet which gives me the warning: "_pending promise deallocated_", when canceling the underlying task. 

``` swift
func pingGoogle() -> Promise<Void> {
    Promise { seal in
        firstly {
            URLSession.shared.dataTask(.promise, with: URLRequest(url: URL(string: "https://google.com")!))
        }.done { _ in
            seal.fulfill_()
        }.catch {
            seal.reject($0)
        }
    }
}
    
pingGoogle()
URLSession.shared.getAllTasks { tasks in tasks.forEach { $0.cancel() } }
```

I am not entirely sure why this is happening, nor how to solve it. 
Could someone with more experience point me in the right direction?

Any help is greatly appreciated, thanks!

**Comment by vinczebalazs** [comment]
Found the error, it was on my end. Because the task is canceled and `.catch` does not catch cancelation errors by default, so my Promise was deallocated without being rejected.

This fixed it:

```
.catch(policy: .allErrors) {
    seal.reject($0)
}
```

I'll leave this here for future reference, should anyone have a similar problem!

**Comment by mxcl** [comment]
This code is doubling promises, just do this:

```swift
func pingGoogle() -> Promise<Void> {
    return URLSession.shared.dataTask(.promise, with: URLRequest(url: URL(string: "https://google.com")!))
}
```
