### ISSUE TITLE
Promisekit Thenable.swift 151lines error crash

### ISSUE THREAD

**Issue by jjy4880** [mxcl/PromiseKit#1120]
![image](https://user-images.githubusercontent.com/28885318/71791334-01a4ae80-3078-11ea-9a43-b5b293aea264.png)

### **Is it associated with this error(memory issue)?**  

![image](https://user-images.githubusercontent.com/28885318/71791278-cdc98900-3077-11ea-80f2-7fa5e95089c9.png)

![image](https://user-images.githubusercontent.com/28885318/71791457-6bbd5380-3078-11ea-95d3-fbc832a82f65.png)

**Comment by mxcl** [comment]
This is not likely PromiseKit crashing, it is likely something else outside of PromiseKit, we are in the trace because you are using promises.
