### ISSUE TITLE
Extending PromiseKit to run a version of `then` inside CoreData's ManagedObjectContext's queue

### ISSUE THREAD

**Issue by augusto2112** [mxcl/PromiseKit#1127]
I'm using PromiseKit version 6.10.

I'm trying to integrate PromiseKit with my Core Data class, to make the async workflow better to use. With Core Data, you can only access entities [in the context's queue passing it blocks](https://developer.apple.com/documentation/coredata/nsmanagedobjectcontext/1506578-performblock) .

I was able to able to write a helper to create new promises who's block run inside the context's queue (the database code is all in Objective-C):
```
- (AnyPromise *)performBlockInPromise:(void (^ __nonnull)(__nonnull PMKResolver))block
{
    // self.queue is a serial queue so promises run in order
    return dispatch_promise_on(self.queue, ^{  
        return [AnyPromise promiseWithResolverBlock:^(PMKResolver resolver) {
            [self.context performBlock: ^{
                block(resolver);
            }];
        }];
    });
}
```

This seems to works, but now I'd like to write a `then` version that runs inside the context's queue by extending AnyPromise.

I tried writing this, but I have no idea how to achieve what I want. I took a look at the source code, and it is mystifying to me, `_PMKCallVariadicBlock` looks kinda crazy.

I'd be really grateful if someone could help me work out how to run a block inside the context's queue and return a promise with `then`, respecting my serial queue order, so I could write code like:

```
promiseThatReturnsEntity.then(^(CoreDataEntity *entity) {
// inside context's here, safe to access the entities fields
```

**Comment by GarthSnyder** [comment]
This is one of the motivations for (the upcoming) V7's Dispatcher system. 

```
promiseThatReturnsEntity.then(on: myManagedObjectContext.dispatcher) { entity in
    // safe to access entity
}
```

You can access the v7 branch to try it out.

**Comment by augusto2112** [comment]
@GarthSnyder Nice! I'll take a look at it
