### ISSUE TITLE
Fix warning 'Header build phase contains duplicate references' when using cocoapods

### ISSUE THREAD

**Issue by sticksen** [mxcl/PromiseKit#113]
![screen shot 2014-11-24 at 11 40 28](https://cloud.githubusercontent.com/assets/2657113/5163694/c4a89be2-73ce-11e4-851a-a9eb5c898328.png)
![screen shot 2014-11-24 at 11 33 55](https://cloud.githubusercontent.com/assets/2657113/5163695/c7912342-73ce-11e4-84fd-df9d37293255.png)
![screen shot 2014-11-24 at 11 41 42](https://cloud.githubusercontent.com/assets/2657113/5163702/eb2ac2d6-73ce-11e4-8efc-e79ba223f745.png)

**Comment by mxcl** [comment]
It's a bug in CocoaPods, multiple subspecs request the same headers and it adds them multiple times. Can't fix! Thanks.
