### ISSUE TITLE
AnyPromise never Triggers .then

### ISSUE THREAD

**Issue by AnthonyTTaylor** [mxcl/PromiseKit#1130]
PromiseKit 6.5.3
Installed with Cocoapods

I've recently tried updating an application that used PMKPromiseKit to AnyPromise 6.5.3 and I am running into an issue of Promises not resolving.

The issue is with .then, its not getting inside the promise.

```
 [self updateCityList].then(^{
    return [self syncCity: city];
}).catch(^(NSError* error){
    //This is a background load; do not present errors to the user
    NSLog(@"Error while loading city or routes: %@", error);
}).ensure(^{
    [self hideLoadingScreen];
});
```

The updateCityList will fire, but it will not enter into the .then to sync the city data.

The UpdateCityList is here

```
- (AnyPromise*) sync {
if (self.syncPromise != nil) {
    return self.syncPromise;
}
[self doesDatabaseNeedPurging];
self.syncPromise = [AnyPromise promiseWithResolverBlock:^(PMKResolver resolve){


    NSError* error;
    CBLDatabase* database = [self loadDatabaseWithError: &error];

    if(!database) {
        NSErrorDomain errorDomain = @"com.com.com";
        NSInteger code = 10042;
        @throw [NSError errorWithDomain:errorDomain code:code userInfo:nil];

    }

    NSURL* url = [self databaseURL];
    self.pullReplication = [database createPullReplication: url];

    [[NSNotificationCenter defaultCenter] addObserver: self
                                             selector: @selector(replicationChanged:)
                                                 name: kCBLReplicationChangeNotification
                                               object: self.pullReplication];

    [self.pullReplication start];
}].ensure(^(){
    [self unregisterCurrentReplication];
});
return self.syncPromise;
}
```
The self.syncPromise is just a AnyPromise variable. As well, the .ensure also doesnt trigger.

Am I missing something after refactoring the code?

---

**Comment by mxcl** [comment]
If the `.then` doesn’t fire either it errors, or cancels, or you aren't causing the `then` to fire because the asynchronous operation has not called a promise kit callback.

**Comment by AnthonyTTaylor** [comment]
Is the only promise kit callback to fulfill, reject, or throw an error? 
Do you need to fulfill a promise before returning it, or does the act of returning it, fulfill it. Pretty much, as long as it does not reject or error, its considered fulfilled if returned.

**Comment by mxcl** [comment]
In your above code nothing calls `resolve`.
