### ISSUE TITLE
Best way to decide which promises to call

### ISSUE THREAD

**Issue by Sergozh** [mxcl/PromiseKit#1133]
Hello! Could you provide any idea of how to decide which promises should I use according to local data?

For example: I have to register user this is promise No.1, also I have promise No.2 for sending his Push notifications token to server. The problem is how to call fulfilling promises No.1 & No.2 if I have enough data for promise No.2 and how to call just No.1 when I haven't data for promise No.2?
Should I use nested closures such as:
```
promise1()
.done {
  promise2()
  .done {
  }
}
```

Big Thanks!

**Comment by mxcl** [comment]
Your question is not clear enough for me I’m afraid.

**Comment by Sergozh** [comment]
I'll try to describe:
I have number of API calls which are already return Promise<T> and I try to understand which is the right way to use promises in situation when: I receive some data from first API call and then I should decide to call next promise or not according to previous response

**Comment by CristianCardosoA** [comment]
This is not a promise question, is an architecture question.

**Comment by mxcl** [comment]
It is not clear to me still, one does not “call” a promise.

Try reading our documentation.
