### ISSUE TITLE
Compatibly with latest version of Alamofire (5.1)

### ISSUE THREAD

**Issue by MiltonPacheco89** [mxcl/PromiseKit#1145]
Hello.

I'm trying to update my pods libraries but I'm getting an error from cocoa pods indicating that 'PromiseKit/Alamofire' requires an older version of Alamofire to work?, is that correct? or maybe I'm doing something wrong in my Podfile, I'll leave an example of how it looks like.

 

```
pod 'Alamofire', '~> 5.1'
 pod 'AlamofireImage', '~> 4.1'
 pod 'Moya', '~> 14'
 pod 'PromiseKit', '~> 6'
 #comment pod 'PromiseKit/Alamofire'
 pod 'RxSwift', '~> 5.1'
 pod 'RxCocoa', '~> 5.1'
 pod 'Moya/RxSwift', '~> 14'
```

if I remove the " #comment" tag I receive this error:

```
PromiseKit/Alamofire (~> 6) was resolved to 6.13.1, which depends on
      Alamofire (~> 4.0).
```

I want to double check if it is possible to have PromiseKit/Alamofire with Alamofire 5 and PromiseKit 6, and if that's the case, what could be wrong in the example above?.

Sorry for my English, it is not my native language.

I appreciate your help, thanks.

**Comment by RomanPodymov** [comment]
Hello @MiltonPacheco89 
I think this issue is not related to mxcl/PromiseKit and you already discussed it in [PromiseKit/PMKAlamofire](https://github.com/PromiseKit/PMKAlamofire/issues/44). You can close the issue.
