### ISSUE TITLE
how can I throws error earlier when I got wrong data

### ISSUE THREAD

**Issue by cleexiang** [mxcl/PromiseKit#1147]
[PLEASE READ THE TROUBLESHOOTING GUIDE](https://github.com/mxcl/PromiseKit/blob/master/Documentation/Troubleshooting.md).

---

You read the guide but it didn’t help? OK, we’re here to help.

* Please specify the PromiseKit major version you are using
* [Please format your code in triple backticks and ensure readable indentation](https://help.github.com/articles/creating-and-highlighting-code-blocks/)
* Please specify how you installed PromiseKit, ie. Carthage, CocoaPods, SwiftPM or other. If other provide DETAILED information about how you are integrating PromiseKit.

If you ignore this template we will close your ticket and link to this template until you provide this necessary information. We cannot help you without it.

**Comment by RomanPodymov** [comment]
Hello @cleexiang 
Please provide some code.

**Comment by mxcl** [comment]
No context = no help
