### ISSUE TITLE
How to treat different errors in a promise chain

### ISSUE THREAD

**Issue by bvirlet** [mxcl/PromiseKit#1149]
I'm using PromiseKit 6.

I'm trying to find a way to properly structure the following code. The idea is that depending on which step returned the error I want to do a different treatment in the catch block:

```
firstly {
    return createFileOnAPI()
}.then { file in
    self.upload(file)
}.then { 
    self.notifyAPIOfUpload()
}.catch { error in
    self.markAsFailedLocally(error)
    
    if this was NOT a createFileOnAPI error {
      self.markAsFailedOnServer(error, onSuccess: {
          self.finish()
      }, failure: { error in
          self.finish()
      })
    }
}
```

One possibility is to return a different type of error for `createFileOnAPI()`. However, this step that communicates with the API would not return the same type of error as the `notifyAPIOfUpload()` step which also talks to the API. As a consequence, we would need a little "dance" to extract the underlying error.

```
firstly {
    return createFileOnAPI()
}.then { file in
    self.uploadFile(file)
}.then {
    self.updateFileOnAPI()
}.catch { error in
    if let error = error as? APICreationError {
        self.markAsFailedLocally(error.underlyingError)
    } else {
        self.markAsFailedLocally(error)

        self.markAsFailedOnServer(error, onSuccess: {
            self.finish()
        }, failure: { error in
            self.finish()
        })
    }
}
```

That doesn't feel quite right either. 

Any recommendation on how to better structure that code?

**Comment by GarthSnyder** [comment]
This is a style question, so there isn't going to be an answer per se. But I think you might find it helpful to consider the options opened by `recover`.

Also keep in mind that your promise chain needn't be linear. Something like this might be more what you're seeking (pseudocode, probably needs some additional type info to compile):

```
firstly {
    return createFileOnAPI()
}.then { file in
    self.uploadFile(file).then {
        self.updateFileOnAPI()
    }.recover { error in
        self.markAsFailedOnServer(error, onSuccess: self.finish, failure: self.finish)
        raise error
    }
}.catch { error in
    self.markAsFailedLocally(error)
}
```

If it's a problem to call `markAsFailedOnServer` or `finish` out of order, you can just set a flag in the recover block that you check later in `catch`.

**Comment by bvirlet** [comment]
Thanks. Maybe the following code will do what I need (I turned `markAsFailedOnServer` into a Promise as well)? But I cannot find a good way to ensure I always throw the recovered error whether markAsFailedOnServer fails or not:

```
firstly {
    createFileOnAPI().recover { error in
        self.markAsFailedLocally(error)
        throw error
    }
}.then {
    try self.uploadFile(file).then {
        self.updateFileOnAPI()
    }.recover { error in
        self.markAsFailedLocally(error)
        self.markAsFailedOnServer(error).ensure { <---- Invalid conversion from throwing function of type '() throws -> Void' to non-throwing function type '() -> Void'
            throw error
        }
    }
}.catch { _ in
    self.notifyUserOfFailure()
}.finally {
    self.finish()
}
```

**Comment by GarthSnyder** [comment]
This version seems less clear to me. The error message is correct that you can't throw an error from `ensure`. It's chain-terminating, so there's no way to add extend the chain past that point. 

You'd probably be best off with a flag, as shown below. It's a bit inelegant, but at least the flow is linear and clear.

```
var reachedServerPhase = false

firstly {
    return createFileOnAPI()
}.then { file in
    reachedServerPhase = true
    return self.uploadFile(file)
}.then {
    self.updateFileOnAPI()
}.catch { error in
    self.markAsFailedLocally(error)
    if reachedServerPhase {
        self.markAsFailedOnServer(error)
    }
    self.notifyUserOfFailure()
}.ensure {
    self.finish()
}
```

**Comment by bvirlet** [comment]
@GarthSnyder thanks, this is very helpful. I agree that the flag is more clear.

Ideally, I want `finish()` to be called when `markAsFailedOnServer` has finished, as well (but I don't really care if `markAsFailedOnServer` has been successful or failed).

Is there a way to refactor the `catch` to make it more clear:

```
firstly {
    createFileOnAPI()
}.done {
    successfullyCreatedFileOnAPI = true
}.then {
    try self.uploadFile(self.file)
}.then {
    self.updateFileOnAPI()
}.recover { error -> Promise<Void> in
    self.markAsFailedLocally(error)

    if successfullyCreatedFileOnAPI {
        return self.markAsFailedOnServer(error).done {
            throw error
        }.recover { apiError in
            DDLogError("Failed to mark file as failed on server: \(apiError)")
            throw error
        }
    } else {
        return Promise(error: error)
    }
}.catch { error in
    self.notifyUserOfFailure()
}.finally {
    self.finish()
}
```

**Comment by GarthSnyder** [comment]
Promise chains are self-sustaining as far as memory references. You don't need to weave them all together. It's fine to start a new, independent chain and just let it do its own error handling. It's no concern of your main path since there is apparently no interaction between the two types of errors.

```
firstly {
    createFileOnAPI()
}.then {
    successfullyCreatedFileOnAPI = true
    return try self.uploadFile(self.file)
}.then {
    self.updateFileOnAPI()
}.catch { error -> Promise<Void> in
    self.markAsFailedLocally(error)
    if successfullyCreatedFileOnAPI {
        self.markAsFailedOnServer(error).catch { apiError in 
            DDLogError("Failed to mark file as failed on server: \(apiError)")
        }
    }
    self.notifyUserOfFailure()
}.finally {
    self.finish()
}
```

**Comment by bvirlet** [comment]
@GarthSnyder but in your suggested example, the `finally` block will be called _before_ the markAsFailedOnServer completes? I want to make sure it's called after.

**Comment by GarthSnyder** [comment]
Ah, sorry, I had missed your intent there. Given that requirement, your previous code is pretty much correct. The `done` clause on markAsFailedOnServer needs to come after the `recover`; otherwise, this code will always log an error. And you don't need to create a pre-errored Promise to return, just throw from within `recover`

The DDLogError clause (presumably) doesn't need to interact with the main sequence, so you can hang it off a separate fork of the chain if you want to. The only real advantage is that this avoids the awkwardness of either creating a dummy Promise() to return or adding yet another "throw error" to the mix. If the error handling is on its own fork, it can be a `catch` instead of a `recover`, which is simpler.

```
firstly {
    createFileOnAPI()
}.then {
    successfullyCreatedFileOnAPI = true
    return try self.uploadFile(self.file)
}.then {
    self.updateFileOnAPI()
}.recover { error -> Promise<Void> in
    self.markAsFailedLocally(error)
    guard successfullyCreatedFileOnAPI else { throw error }
    let failPromise = self.markAsFailedOnServer(error)
    failPromise.catch { apiError in 
        DDLogError("Failed to mark file as failed on server: \(apiError)")
    }
    return failPromise.done { throw error }
}.catch { _ in
    self.notifyUserOfFailure()
}.finally {
    self.finish()
}
```

**Comment by bvirlet** [comment]
In that last example, is the error that will reach the last `catch` block can be the error I'm interested in (thrown by file creation, or file upload) or it could be the error returned by `markAsFailedOnServer()`?

```
}.catch { _ in // <-- what is the error that arrives here?
    self.notifyUserOfFailure()
}.finally {
    self.finish()
}
```

That's not a problem here, but in case I was using the content of `error` to notify the user, that could lead to surprises later:

```
}.catch { error in
    self.notifyUserOfFailure(error)
}.finally {
    self.finish()
}
```

**Comment by GarthSnyder** [comment]
Yes, it could be the apiError. If an apiError occurs, it will propagate down both forks of the chain.

**Comment by bvirlet** [comment]
This is very clear now. Thanks a lot for your help and your answers!
