### ISSUE TITLE
When adding swift/PromiseKit.xcodeproj, a linker error occurs if you never `import AssetsLibrary`

### ISSUE THREAD

**Issue by dimroc** [mxcl/PromiseKit#115]
Given a project where you never `import AssetsLibrary`, i.e.:

```swift
import Foundation
//import AssetsLibrary
import PromiseKit
```

Running your project will result in the following:

```bash
dyld: Library not loaded: @rpath/libswiftAssetsLibrary.dylib
  Referenced from: /Users/dimroc/Library/Developer/Xcode/DerivedData/ManhattanForum-ekevinzlbwehjbdjpibmdbxqdqtm/Build/Products/Debug-iphonesimulator/PromiseKit.framework/PromiseKit
  Reason: image not found
```

This might be due to the following lines of code in `PromiseKit/swift/Sources/UIViewController+Promise.swift`:

```swift
4: import AssetsLibrary.ALAssetsLibrary
```

Simply uncommenting the `import AssetsLibrary` in the main application, cleaning, and building fixes the problem.

I'm not sure there is an explicit fix for this, especially with the inevitable cocoapod support for swift. I figured I would document it here in case other people run into the issue. Is there a stackoverflow tag I should use instead?

**Comment by mxcl** [comment]
The new `PromiseKit/Swift` pod imports AssetsLibrary. However I'd rather load it at runtime on demand. Since it is used only to provide the raw NSData for the image, if the user asks for that version of the Promise, so mostly it is a waste to load. So I'll leave this ticket open with that goal in mind.

**Comment by hariseldon78** [comment]
i have the same problem with the CoreAudio library: 
dyld: Library not loaded: @rpath/libswiftCoreAudio.dylib
  Referenced from: /Users/robertoprevidi/Developer/moving-circles/Build/Products/Debug-iphonesimulator/PromiseKit.framework/PromiseKit
  Reason: image not found

**Comment by mxcl** [comment]
Well, this isn't to do with PromiseKit then. We don’t do anything with CoreAudio. You should be able to fix it however by making your *app* target link to CoreAudio.
