### ISSUE TITLE
Missing: Promise convenience constructor

### ISSUE THREAD

**Issue by raygun101** [mxcl/PromiseKit#1150]
Possible missing `convenience` constructor to simplify syntax.

*Do you think this is a valid missing constructor, or if it's not a suggested approach could you please explain why?* (I can only think it could mess with the compiler, confusing bodies that return `Thenable`'s with bodies that return a value. [ambiguous compiler errors])

```
// Allow inlining of promise without using the Resolver syntax. (seal.fulfill(data))
//
extension Promise
{
    convenience init(execute body: () throws -> T)
    {
        self.init
        {
            $0.fulfill(try body())
        }
    }
}

// example of usage:
//
func fetchData() -> Promise<Data>
{
    return Promise { try DataSorce.getData() }
}

// instead of:
//
return Promise { seal in seal.fulfill(try DataSorce.getData())
```

**Comment by ospfranco** [comment]
https://github.com/mxcl/PromiseKit/issues/532

**Comment by raygun101** [comment]
It's a convenience thing, a simpler Promise fulfilling body construct.
The call still needs to be wrapped in a promise to catch an exception as a resolver reject.
`Promise.value` would loose that error.

**Comment by mxcl** [comment]
Unfortunately this would cause Swift to find usage of our constructors ambiguous.

**Comment by raygun101** [comment]
Thank you. That's the answer I was looking for. 👍
I had a feeling it would cause issues, thanks for confirming.
