### ISSUE TITLE
Replacing one error with another

### ISSUE THREAD

**Issue by lmcd** [mxcl/PromiseKit#1152]
Is it possible to catch one error, and rethrow with another?

The solution that comes to mind is catching the error with `catch`, transforming it into something else then `throw`ing it again, but `catch` isn't marked as `throws`.

`recover` doesn't seem appropriate here as it expects a return value

**Comment by lmcd** [comment]
Oh turns out it's possible with `recover`, but one of those annoying situations where you have to hint to the compiler with the whole block signature grrr :(

Would be great if there was a nicer way of doing this.

**Comment by mxcl** [comment]
In practice, there is not really a nicer way to achieve this, we have experimented with other syntax in the past and failed due to issues with how Swift identifies error types.
