### ISSUE TITLE
Question about importing PromiseKit using bridging header

### ISSUE THREAD

**Issue by davidohyer** [mxcl/PromiseKit#1156]
PromiseKit Version: 6.13.1
Installed using Carthage. 
I want to import PromiseKit to my entire app at once. I'm doing this using the following line in my Bridging Header file: 
```
#import <PromiseKit/PromiseKit.h>
```
This works, but I read something that mentioned the Objective-C library is not exactly the same as the Swift library. My question is, can I import the library in this way, or will I have undesirable side effects? Will the PromiseKit implementation be the same doing this as if I used:
```
import PromiseKit
```
in my Swift files?

**Comment by mxcl** [comment]
You won’t get the Swift portions this way.

**Comment by davidohyer** [comment]
Alright, looks like its back to the swift import statements. As a matter of curiosity, is there documentation that lists what portions are swift only features?

**Comment by mxcl** [comment]
The ObjC portion is documented separated in our documentation.
