### ISSUE TITLE
Archive issue Xcode 12 beta

### ISSUE THREAD

**Issue by ElenaVielva** [mxcl/PromiseKit#1159]
I failed to archive app with 12.0 beta 2 and I found that other libraries have similar issues.

https://github.com/Alamofire/Alamofire/issues/3240
https://github.com/SwiftyJSON/SwiftyJSON/issues/1066

* PromiseKit version 6.13
* It's installed using CocoaPods
* The error is the following:

```
Command CompileSwift failed with a nonzero exit code
```

**Comment by mohamadakmalshukri** [comment]
i also got the same issue. 
Undefined symbols for architecture i386: "type metadata for Swift._StringObject.Variant"

**Comment by RomanPodymov** [comment]
Hello @ElenaVielva @mohamadakmalshukri 
Try to install Xcode 12 from AppStore.

**Comment by RomanPodymov** [comment]
Hello @ElenaVielva @mohamadakmalshukri 
Please close the issue if you cannot reproduce it with Xcode 12.

**Comment by Radiksidenko** [comment]
Hello @ElenaVielva @mohamadakmalshukri 
update also Promisekit to the latest version

**Comment by ElenaVielva** [comment]
Archiving from Xcode 12 (no beta) now works fine for me, thanks!
