### ISSUE TITLE
wait method

### ISSUE THREAD

**Issue by fabb** [mxcl/PromiseKit#116]
[`RXPromise` has a `wait` and a `runLoopWait` method](https://github.com/couchdeveloper/RXPromise/blob/master/RXPromise%20Libraries/Source/RXPromise.h#L578) which is extremely helpful for testing. Is there something similar available in PromiseKit?

**Comment by mxcl** [comment]
I'm not sure how to implement this without causing deadlock if any part of the promise in question needs to use the same thread that `wait` is called in.

**Comment by mxcl** [comment]
I guess RXPromise doesn't try to prevent this either. It’s just that with larger chains (which happens easily with Promises), you can't know if any of them will require the thread you are blocking.

The runLoopWait is safer though.

Anyway, as discussed they are just for debugging. So I guess I can add them with the caveat that you may get a deadlock. And the deadlock may not be reproducible.

**Comment by mxcl** [comment]
Added `+hang:`
