### ISSUE TITLE
Use of undeclared type 'AnyPromise' with SPM

### ISSUE THREAD

**Issue by VuduiOSDev** [mxcl/PromiseKit#1161]
* Please specify the PromiseKit major version you are using
  6.13.2
* [Please format your code in triple backticks and ensure readable indentation]
  Use of undeclared type 'AnyPromise'. I can see that AnyPromise.swift/.m is excluded in Package.Swift file. Project is compiling w/o any issue when PromiseKit is installed with Carthage. 
* Please specify how you installed PromiseKit, ie. Carthage, CocoaPods, SwiftPM or other. If other provide DETAILED information about how you are integrating PromiseKit.
 Swift Package Manager

**Comment by mxcl** [comment]
Sorry, your bug report is confusing and I do not know how to help.

**Comment by jeroenleenarts** [comment]
When importing PromiseKit in a project with Swift Package Manager in Xcode it errors out with the error in the title when trying to use AnyPromise from some Obj-C code.

**Comment by VuduiOSDev** [comment]
Yes, I am facing this issue with swift files as well. I am trying to migrate PromiseKit from Carthage to SPM. I see that PromiseKit's Package.Swift is excluding "AnyPromise.swift", "AnyPromise.m" files. Is this something related to this issue?

**Comment by VuduiOSDev** [comment]
`import PackageDescription

let pkg = Package(name: "PromiseKit")
pkg.products = [
    .library(name: "PromiseKit", targets: ["PromiseKit"]),
]

let pmk: Target = .target(name: "PromiseKit")
pmk.path = "Sources"
pmk.exclude = [
    "AnyPromise.swift",
    "AnyPromise.m",
    "PMKCallVariadicBlock.m",
    "dispatch_promise.m",
    "join.m",
    "when.m",
    "NSMethodSignatureForBlock.m",
    "after.m",
    "hang.m",
    "race.m",
    "Deprecations.swift"
]
pkg.swiftLanguageVersions = [3, 4]
pkg.targets = [
    pmk,
    .testTarget(name: "A+", dependencies: ["PromiseKit"]),
    .testTarget(name: "CorePromise", dependencies: ["PromiseKit"], path: "Tests/CorePromise"),
]
`
Please check the first two lines (AnyPromise.swift, AnyPromise.m) of the above Package.swift file of PromiseKit.

**Comment by Tr736** [comment]
Im also having the same issue when installing via SPM

**Comment by chanuuuu** [comment]
@mxcl do you have any update on this? 

Sample code related to this error:
`@objc public var shouldVideoDefaultToFill: AnyPromise {
        // detect in iPhoneX only:
        if !DeviceUtil.isIphoneX() {
            return AnyPromise(Promise<Any>.genericError)
        }
        
        return AnyPromise(self.isThumbWidescreen)
    }`

Error: Cannot find type 'AnyPromise' in scope

**Comment by mxcl** [comment]
SwiftPM does not support AnyPromise. This is documented.

**Comment by chanuuuu** [comment]
How can I expose Promise<T> from Swift to Objc in this case? I can only find this documentation related to AnyPromise: https://github.com/mxcl/PromiseKit/blob/master/Documentation/ObjectiveC.md

Can you point me to the correct documentation or recommend how to bridge b/w Swift and Objc using SPM?
