### ISSUE TITLE
PromiseKit  tagged version 7.0.0-alpha3 not working with carthage

### ISSUE THREAD

**Issue by Kaushal0812** [mxcl/PromiseKit#1162]
I have been trying to use "7.0.0-alpha3"  with carthage. But it's not working out. 

I trying both of these options but luck.

**Carthage Version: 0.35.0**

`github "mxcl/PromiseKit" "7.0.0-alpha3"
`
`git "https://github.com/mxcl/PromiseKit.git" "7.0.0-alpha3"
`

Getting this in terminal response for both commands.

> *** Skipped building PromiseKit due to the error:
> Dependency "PromiseKit" has no shared framework schemes for any of the platforms: iOS
> 
> If you believe this to be an error, please file an issue with the maintainers at https://github.com/mxcl/PromiseKit/issues/new

**Comment by mxcl** [comment]
We do not currently support Carthage with v7. And may not at all since Carthage devs hardly care anymore.
