### ISSUE TITLE
Update to Xcode 12: Cannot convert value of type 'DataRequest' to closure result type 'Void'

### ISSUE THREAD

**Issue by Sinan-Noureddine** [mxcl/PromiseKit#1165]
PromiseKit was working fine for 2 years until i updated to xcode 12.0 today.

The function is now throwing the error "Cannot convert value of type 'DataRequest' to closure result type 'Void'"

The function looks like this:

`func fetchArticlesFromApi (API: String) -> Promise<[Article]> {`
`return Promise<[Article]> { seal in`
`return Alamofire.request(API).validate().responseString(completionHandler: { //Error happening here`
`response in`
`switch (response.result) {`
`case .success(let responseString):`
`//Do something`
`etc...`

Note: The same project and code work just fine when i run it on xcode 11.6!

**Comment by flopshot** [comment]
Also seeing this issue

**Comment by GarthSnyder** [comment]
I think Xcode is correct here. The method signature you're using is

```
public init(resolver body: (Resolver<T>) throws -> Void) 
```

You shouldn't be trying to return anything from the closure passed to `Promise.init`. Just replace the `return` in front of `Alamofire.request...` with `_ =` and see if that fixes the issue.

I'm not sure why this would have compiled without a warning in the past. Xcode bug, perhaps?

**Comment by flopshot** [comment]
@GarthSnyder Your suggestion worked, thanks. I need to look into why Xcode 11 allowed me to compile this code before

**Comment by Sinan-Noureddine** [comment]
Thank you Garth for the help, it worked! It's really weird how it's working on previous Xcode versions

**Comment by GarthSnyder** [comment]
Glad it helped!
