### ISSUE TITLE
Guarantee done not working in sometimes

### ISSUE THREAD

**Issue by CodingPub** [mxcl/PromiseKit#1166]
I use "6.12.0", lauchPrepare() return a Guarantee object, and I ensure Guarantee prepare is resolved, but close method in prepare.done not working for any AppStore user, such as iPhone9,2 iOS 12.1.4, please help me.

![image](https://user-images.githubusercontent.com/7928804/94033071-2e117e00-fdf3-11ea-8d0b-92582d2a5998.png)

**Comment by mxcl** [comment]
If `done` is not called the `Guarantee` is not resolved, re-visit your “sealing” logic.

**Comment by CodingPub** [comment]
Sorry, The problem is not here
