### ISSUE TITLE
Application crashed on launch when BUILD_LIBRARY_FOR_DISTRIBUTION flag is enabled for PromiseKit.

### ISSUE THREAD

**Issue by yo2bh** [mxcl/PromiseKit#1167]
In the current project, I am switching to the XCFramework from all frameworks that use Carthage for the build.
I have downloaded the [Source code](https://github.com/mxcl/PromiseKit/archive/6.13.3.zip) of the PromiseKit.

I want to create the PromiseKit xcframework, I have followed the below steps:

1. Enabled the "BUILD_LIBRARY_FOR_DISTRIBUTION" flag (As of this need to set to create XCFramework)
2. Created archive for Simulator & iphoneos
3. Created PromiseKit XCFramework using the -create-xcframework command.

PromiseKit.xcframework created successfully. 

After that, I have integrated that into the application, which launches an application successfully on Simulator but the application crashed on launch on iPhone 11 device.

PromiseKit XCFramework link - [https://we.tl/t-1YJCXDGMmX](https://we.tl/t-1YJCXDGMmX)

@mxcl - Can you please help me out here?

**Comment by mxcl** [comment]
Provide crash logs

**Comment by yo2bh** [comment]
@mxcl - please check the log image here.
https://we.tl/t-YTxgcwNp6L

**Comment by mxcl** [comment]
These logs do not contain any crash information.

Either way, this is a build problem and not specific to PromiseKit.

**Comment by yo2bh** [comment]
@mxcl - You can also reproduct this scenario at your end.

Just enable the BUILD_LIBRARY_FOR_DISTRIBUTION flag from project setting, you will observed that the .framework is also crashing on device.

Don't understand why PromiseKit is crashed when this flag is set?

**Comment by mxcl** [comment]
This is not a PromiseKit bug.
