### ISSUE TITLE
Xcode 12 - Warning related to iOS 8 support (SPM)

### ISSUE THREAD

**Issue by kikeenrique** [mxcl/PromiseKit#1168]
[PLEASE READ THE TROUBLESHOOTING GUIDE](https://github.com/mxcl/PromiseKit/blob/master/Documentation/Troubleshooting.md).

---

You read the guide but it didn’t help? OK, we’re here to help.

* Please specify the PromiseKit major version you are using
**PromiseKit 6.11.0**

* [Please format your code in triple backticks and ensure readable indentation](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

* Please specify how you installed PromiseKit, ie. Carthage, CocoaPods, SwiftPM or other. If other provide DETAILED information about how you are integrating PromiseKit.
**SwiftPM**

If you ignore this template we will close your ticket and link to this template until you provide this necessary information. We cannot help you without it.

---

Using PromiseKit in SPM on Xcode 12 produces this warning:

_The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99._

According to Xcode 12 release notes, iOS 8 is deprecated, check in https://developer.apple.com/documentation/xcode-release-notes/xcode-12-release-notes:

> Xcode 12 includes SDKs for iOS 14, iPadOS 14, tvOS 14, watchOS 7, and macOS Catalina 10.15.6. The Xcode 12 release supports on-device debugging for **iOS 9 and later**, tvOS 9 and later, and watchOS 2 and later. Xcode 12 requires an Intel-based Mac running macOS Catalina 10.15.4 or later.

The problem could be fixed changing the platforms supported in Package.swift
```
-        .macOS(.v10_10), .iOS(.v8), .watchOS(.v2), .tvOS(.v9)
+        .macOS(.v10_10), .iOS(.v9), .watchOS(.v2), .tvOS(.v9)
```

**Comment by mxcl** [comment]
This is not a PromiseKit issue, I think more likely your Xcode project is misconfigured.

**Comment by kikeenrique** [comment]
It's not a misconfiguration problem, it's a deprecation on Xcode 12 that conflicts with current Package.swift platform definition.
You just need to create a new project on Xcode 12, add SPM dependency on PromiseKit and you'll see the warning.

**Comment by timbms** [comment]
I have the same issue as @kikeenrique. Would love to have it fixed.

**Comment by gajjartejas** [comment]
Xcode 12 does not support iOS 8 deployment, please update v8 to v9 in Package.swift.

**Comment by pushchris** [comment]
Any update on this? Definitely experiencing this as well

**Comment by kikeenrique** [comment]
Please, keep updated in #1170, as this is a closed topic and even can be consider a duplicate of this.
