### ISSUE TITLE
Unable to install PromiseKit 6.13.3

### ISSUE THREAD

**Issue by Veddevoloper** [mxcl/PromiseKit#1181]
Trying to upgrade from PromiseKit 6.13.1 to 6.13.3 using CocoaPods in a Xcode 12.2. project. Changing pod file to target PromiseKit 6.13.3 and running pod update results in the message

 CocoaPods could not find compatible versions for pod "PromiseKit/CoreLocation":
  In Podfile:
    PromiseKit (= 6.13.3)

**Comment by RomanPodymov** [comment]
Hello @Veddevoloper 
Currently, the latest PromiseKit version is 6.13.2.

**Comment by jrtibbetts** [comment]
But [6.13.3 is tagged](https://github.com/mxcl/PromiseKit/releases/tag/6.13.3), so that's what Carthage & CocoaPods will try to grab when you do an update without specifying a version number.

6.13.3's `PMKFoundation` version isn't building when updating PromiseKit from Carthage, either.

**Comment by jalopezcar** [comment]
The latest version available in CocoaPods is still 6.13.1 https://cocoapods.org/pods/PromiseKit

**Comment by jrtibbetts** [comment]
Good point. I use Carthage, which goes by tags.

**Comment by mxcl** [comment]
All PM solutions are updated now.
