### ISSUE TITLE
Unbound memory growth issue with chained promises

### ISSUE THREAD

**Issue by davidchin** [mxcl/PromiseKit#120]
I noticed there's an unbound memory growth issue when executing a chain of promises multiple times. For example:

```
func fetch() {
  fetchImage()
    .then { _ -> Promise<UIImage> in
      return self.fetchImage()
    }
    .then { _ -> Promise<UIImage> in
      return self.fetchImage()
    }
    .then { _ -> Promise<UIImage> in
      return self.fetchImage()
    }
}

func fetchImage() -> Promise<UIImage> {
  let image = UIImage(named: "Image")!
  
  return Promise(value: image)
}
```

Imagine `fetchImage()` is an asynchronous method and I'm calling it in a sequence. If I call `fetch()` multiple times, I would see memory usage increasing indefinitely. For testing purpose, I used a timer to call `fetch` many times in a viewController to illustrate the issue.

```
let timer = NSTimer.scheduledTimerWithTimeInterval(0.1, target: self, selector: "fetch", userInfo: nil, repeats: true)
```

Not sure how to fix this.

**Comment by mxcl** [comment]
I've confirmed this with a test case, but I can't find any leaks. Instruments isn't much use and some cursory logging suggests everything suspect is being deallocated. I'll keep looking.

**Comment by mxcl** [comment]
Actually, when I use Instruments I see that the memory usage stays constant. Xcode's memory meter shows it grow continually.

Googling this I see that the Xcode meter is not reliable here since it is showing the malloc engine behavior for the Mac, Instruments is actually showing what memory is persisting, and it shows no leaks.

How did you confirm the unbound memory usage you describe?

**Comment by mxcl** [comment]
Reference: http://osdir.com/ml/general/2013-12/msg13145.html

**Comment by davidchin** [comment]
Yes, I noticed the difference between the allocation instrument and Xcode memory metre after I reported this issue. But I didn't really understand the reason behind it and which one was more reliable. Anyway, I guessed Instrument was correct so I kept using PromiseKit in our project. Thanks for looking into this issue - now I know why.
