### ISSUE TITLE
Do you want additional documentation?

### ISSUE THREAD

**Issue by philmitchell** [mxcl/PromiseKit#121]
I just found PromiseKit and it is fantastic! Your current docs are excellent, but I found that I had to spend several hours writing a little cookbook for myself before I really grokked how to use it. It's very basic at this point, but it'll probably expand. Do you want it, and if so, how? (I noticed that your docs are not in the repo.)

**Comment by philmitchell** [comment]
Okay, here goes: http://philmitchell.github.io/PromiseKit/

Please feel free to let me know if I've misunderstood anything ...

**Comment by philmitchell** [comment]
Bump ... just in case this fell off the radar!

**Comment by mxcl** [comment]
Yes, I like the approach. Can we put it on the main site in a new tab?

**Comment by philmitchell** [comment]
Glad you like it! That sounds good, is that something you can do?

On Fri, Jan 30, 2015 at 1:51 PM, Max Howell <notifications@github.com>
wrote:

> Yes, I like the approach. Can we put it on the main site in a new tab?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mxcl/PromiseKit/issues/121#issuecomment-72276424>.
>



-- 
Learn Bird Songs, Support Conservation: http://www.larkwire.com
Bikewise: http://www.bikewise.org

**Comment by philmitchell** [comment]
Max, you are obviously passionate about docs, which is awesome. I have no problem with relegating my cookbook to an appendix ... but I do think that you underestimate the need for a more gentle guide for the less sophisticated devs such as myself! Just my $0.02 ...

**Comment by mxcl** [comment]
I was aiming to make something more gentle. Sorry if I didn't succeed.

I however don't feel your cookbook is more gentle, though I'm happy to have it put somewhere in the documentation.

**Comment by mxcl** [comment]
Like by all means, lets work together, submit some PRs to adapt what we have.

**Comment by philmitchell** [comment]
Okay, thanks for the offer! I'll think about whether I have anything useful
beyond what I already sent ... At any rate, huge fan of PK! Thanks, again
...

On Thu, Feb 19, 2015 at 7:43 PM, Max Howell <notifications@github.com>
wrote:

> Like by all means, lets work together, submit some PRs to adapt what we
> have.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mxcl/PromiseKit/issues/121#issuecomment-75185239>.
>



-- 
Learn Bird Songs, Support Conservation: http://www.larkwire.com
Bikewise: http://www.bikewise.org
