### ISSUE TITLE
Missing argument for parameter 'body' in call - nested promise

### ISSUE THREAD

**Issue by ldiqual** [mxcl/PromiseKit#122]
I want to retry a promise when the network call it contains fails. However, calling the promise generator inside itself will produce a error. the following error `Missing argument for parameter 'body' in call`.

Simplified code:

```
class A {}

func doCall(completion: (error: Bool) -> Void) {
    completion(error: true)
}


func createA(a: A) -> Promise<A> {
    return Promise<A>({ (fulfill, reject) -> Void in
        doCall { error in
            if !error {
                let a = A()
                fulfill(a)
                return
            }

            createA(a).then { resultingA -> Void in // Missing argument for parameter 'body' in call
                fulfill(resultingA)
            }.catch {
                reject(true)
            }
        }
    })
}
```

Any idea of what's happening here?
I'm fairly new to swift and my problem could totally be a result of a syntax issue. Let me know if that's the case, and I'll switch to stackoverflow.

**Comment by ldiqual** [comment]
Thanks @mxcl, I fixed it with the unused variable. I really hope we'll have a cleaner solution in the future and I understand that it'll be tricky.

**Comment by mxcl** [comment]
I have a cleaner solution locally, I'm just waiting on a new Xcode release in case it is fixed better.

Getting impatient for the Xcode release though… :/
