### ISSUE TITLE
How to convert multiple completion function to PromiseKit?

### ISSUE THREAD

**Issue by donileo** [mxcl/PromiseKit#1243]
How would one translate a call that has multiple completions into a PromiseKit call. For example:

`func startPresence(forUserId userId: String,  userOnlineCompletion: ((Bool) -> Void)? = nil,  requestCompletion: (Error?) -> Void)` ?

In the call above the userOnlineCompletion closure is needed since startPresence only starts the request. The actual marking of the user as "online" is async and happens after this request is made.

I thought of returning multiple promises but implementing the solution is not obvious. I am not looking to rewrite the startPresence function but instead wrap a new Promise to use its completions properly.

Update: I think I figured something out through the use of .pending() on the Promise by which at then point the solution does become obvious 😄

**Comment by mxcl** [comment]
```swift
Promise { fulfill, reject in
    startPresence(forUserId: foo, userOnlineCompletion: fulfill, requestionCompletion: reject)
}
```

Is what you wanted presumably? I suggest reading our docs where we talk about this in depth.
