### ISSUE TITLE
[6.13.1] pod install 443

### ISSUE THREAD

**Issue by baiyidjp** [mxcl/PromiseKit#1257]
Installing PromiseKit (6.13.1)

[!] Error installing PromiseKit
[!] /usr/bin/git clone https://github.com/mxcl/PromiseKit.git /var/folders/m7/h40mcvgs7j7b1g46p_zjkqy80000gn/T/d20210909-87498-10rz97k --template= --single-branch --depth 1 --branch 6.13.1

Cloning into '/var/folders/m7/h40mcvgs7j7b1g46p_zjkqy80000gn/T/d20210909-87498-10rz97k'...
fatal: unable to access 'https://github.com/mxcl/PromiseKit.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443

**Comment by mxcl** [comment]
This is an issue with your git or libressl installation.

**Comment by RomanPodymov** [comment]
Hello @baiyidjp 
What about v.6.16.0?

**Comment by mxcl** [comment]
This is an issue with your git or libressl installation. It has nothing to do with PromiseKit.

Consider learning how the Internet works.
