### ISSUE TITLE
PromiseKit as xcframework on latest xcode 13

### ISSUE THREAD

**Issue by mmdumi** [mxcl/PromiseKit#1258]
Hi,
I would like to know if there is a way currently to compile PromiseKit into an xcframework for the latest xcode13.
I used to compile it before with carthage but that doesn't seem to be supported any more.
Thank you.

**Comment by mxcl** [comment]
Use v6?

**Comment by mmdumi** [comment]
Yes

**Comment by mxcl** [comment]
Then use Carthage with v6 presumably. It will build xcframeworks.

**Comment by RomanPodymov** [comment]
Hello @mmdumi 
Do you this still to build PromiseKIt as xcframework? Or can we close the issue?

**Comment by mmdumi** [comment]
You can close the issue. Not using PromiseKit for a few years time, but thank you for the work and contributions to this project.
