### ISSUE TITLE
Using PMKError.cancelled unexpectedly (to a newbie) stops chain from completing. Document somehow??

### ISSUE THREAD

**Issue by ConfusedVorlon** [mxcl/PromiseKit#1259]
* Please specify the PromiseKit major version you are using

7.0.0.rc2

installed with SPM

I created a promise wrapper for NSAlert. 
It seemed sensible to use `seal.reject(PMKError.cancelled)` in the case where the user clicked 'cancel'

I didn't realise that this error has a special-case treatment where the `.catch` block isn't called.

Presumably there isn't a good 'code' way to warn about this - but it could be flagged in the troubleshooting section under 'My promise never resolves'
 
Example below. To me, it was very surprising that neither the .done nor the .catch block were called
 
 ```
        let promise:Promise<Void> = Promise {
            seal in
            
            seal.reject(PMKError.cancelled)
        }
        
        firstly {
            promise
        }
        .done {
            print("done")
        }
        .catch {_ in
            print("Catch")
        }
  ```

**Comment by mxcl** [comment]
> Example below. To me, it was very surprising that neither the .done nor the .catch block were called

Cancelation is neither success nor failure. Hence this behavior. Instead use a `finally` if you need to do some clean up. This is a core tenant of our design which apparently is no longer really mentioned.

Considering I don't really understand how it works I'm not sure we should recommend v7 at this point.

**Comment by ConfusedVorlon** [comment]
ok - just tested with 6.15.3 and the behaviour is the same. I'll reopen my doc pull requests!

**Comment by mxcl** [comment]
Yeah we really should print a debug message, this catches people, no pun intended.

**Comment by RomanPodymov** [comment]
Hello @ConfusedVorlon 
Can we close this issue?

**Comment by ConfusedVorlon** [comment]
Hi - years have passed. I no longer have any insight here...
