### ISSUE TITLE
Support NSProgress within when()

### ISSUE THREAD

**Issue by danthorpe** [mxcl/PromiseKit#127]
It would be great if when() created it's own NSProgress from the from current progress object, and incremented the total work when each promise completed.

**Comment by mxcl** [comment]
Agreed.

**Comment by mxcl** [comment]
I had a look at doing this, but it will require a lot of thorough thought on testing it and I don't feel up to it without a personal immediate need. So we'll leave this here in hope of a PR.

I've used NSProgress with Promises in #Homescreen app, and it worked well. So this will work well, when done.

**Comment by danthorpe** [comment]
Thanks Max - appreciate your position. I've also been swamped at the moment to get to it myself.

**Comment by xenadu** [comment]
FYI, I've run into zombie object crashes with nested `NSProgress` objects (specifically `_NSProgressFraction`). `NSProgress` appears to have a fundamental assumption that intermediate child progress objects aren't being simultaneously created and deallocated which only really works if you can create all necessary progress objects up front.

**Comment by mxcl** [comment]
I'm implementing this and can only hope the NSProgress crashes are fixed.

Two things:

* I'm not implementing a cancel handler, but perhaps we should one day, the idea of being able to cancel a promise from the outside is considered “wrong”, but practically it probably isn't sensible to worry that some weird library may cancel your when.
* I'm making it so if one of the input promises is rejected the progress is set to 100%.

Thoughts?

**Comment by russbishop** [comment]
It seems like cancellation makes reasoning about progress in a decoupled way impossible because some later piece of code trying to chain may find that neither its `then` nor its `catch` executes. In the C# world, `Task<T>` cancellation is handled by exceptions so it always appears to be an error condition. I suppose that could be one path forward?


But mostly I'm worried about stability problems. I'd strongly prefer to have a way to turn this off!

**Comment by mxcl** [comment]
```swift
let progress = NSProgress(totalUnitCount: 1)
progress.becomeCurrentWithPendingUnitCount(1)
when(p1, p2, p3, p4).then {
    //…
}
progress.resignCurrent()
```

**Comment by danthorpe** [comment]
Nice! :+1:

**Comment by mxcl** [comment]
@russbishop it can be turned off with a compile time conditional. See the commit message.

**Comment by alexlee002** [comment]
@mxcl Hi,  I read the WhenTestCase code, but I'm not sure how to report the download progress in http download request. Can you please show a sample?
