### ISSUE TITLE
When using wait(), after firstly is fullfilled, then not excute

### ISSUE THREAD

**Issue by karthuszY** [mxcl/PromiseKit#1270]
I want to use wait() to make sure my database is  initial completed.
But when i use wait(), when `initDBTables()` is fullfilled, then not excute.
Another question is when i use cauterize(), the done block not excute

---

You read the guide but it didn’t help? OK, we’re here to help.

* PromiseKit version -> 6.15.3
* Using SPM

```
    init() throws {
        try initDatabase().wait()        
    }
    
     func initDatabase() -> Promise<Bool> {
        return Promise { reslover in
            firstly {
                initDBTables()
            }.then {
                self.migrateDatabase()
            }.then {
                self.migrateDataToV2()
            }.then {
                self.addDBObserver()
            }.done {
                reslover.fulfill(true)
            }.catch { error in
                reslover.reject(error)
            }
        }
    }

```

**Comment by mxcl** [comment]
`.wait()` pauses that thread. You have to ensure everything else in the promise chain does not use that thread.

Refer to the docs for more information: https://github.com/mxcl/PromiseKit/blob/75cc1d4618e893269c46c3536bb7491d470f45b7/Sources/Promise.swift#L105-L108

**Comment by karthuszY** [comment]
> `.wait()` pauses that thread. You have to ensure everything else in the promise chain does not use that thread.
> 
> Refer to the docs for more information:
> 
> https://github.com/mxcl/PromiseKit/blob/75cc1d4618e893269c46c3536bb7491d470f45b7/Sources/Promise.swift#L105-L108

I try to this, it's still not working


```
    init() throws {
        try initDatabase().wait()        
    }
    
     func initDatabase() -> Promise<Bool> {
        let queue = DispatchQueue.global()
        return Promise { seal in
            queue.async {
                firstly {
                    self.initDBTables()
                }.then {
                    self.migrateDatabase()
                }.then {
                    self.migrateDataToV2()
                }.then {
                    self.addDBObserver()
                }.done {
                    seal.fulfill((self))
                }.catch { error in
                    seal.reject(error)
                }
        }
        }
    }

```

**Comment by mxcl** [comment]
Read the docs.
