### ISSUE TITLE
PromiseKit 6.16.x with CocoaPods

### ISSUE THREAD

**Issue by sdc-78** [mxcl/PromiseKit#1272]
Version 6.16.0 was released almost one month ago, but it is still version 6.15.3 which is provided by CocoaPods. Is there a specific reason for this?

**Comment by mxcl** [comment]
Our automation [keeps failing](https://github.com/mxcl/PromiseKit/actions/runs/1381506155) for difficult to understand reasons.

I cannot run it locally, CocoaPods fails for different reasons that seem related to the fact I have an M1.

**Comment by mxcl** [comment]
Fixed.
