### ISSUE TITLE
PromiseKit.podspec file is missing in version 6.8.4 & version 6.8.5

### ISSUE THREAD

**Issue by YangYouYong** [mxcl/PromiseKit#1273]
I have checked the source code for git tag 6.8.4 and 6.8.5.
The PromiseKit.podspec is missing.
Some old project, which depends on these version, May be hold on the CocoaPods update.

**Comment by mxcl** [comment]
The file isn't required to be in the repo for CocoaPods to function. It uses its own data store.

Either way it is impossible to add a .podspec file to an old tag without changing the tag which can cause other problems.

**Comment by mxcl** [comment]
Unless you have a counter, I'm closing. Thanks.
