### ISSUE TITLE
Update podspec to support Swift framework with 0.36.0.beta1

### ISSUE THREAD

**Issue by mowens** [mxcl/PromiseKit#128]
The CocoaPods team has released a beta with Swift support. It would be great to update the podspec against the beta to work out any kinks :)

https://github.com/CocoaPods/CocoaPods/releases/tag/0.36.0.beta.1

**Comment by mowens** [comment]
PR: https://github.com/mxcl/PromiseKit/pull/130

**Comment by mxcl** [comment]
Merged.
