### ISSUE TITLE
PromiseKit 6.15.3 with CocoaPods

### ISSUE THREAD

**Issue by xhzth70911** [mxcl/PromiseKit#1281]
CocoaPods in a Xcode 12.1 ![image](https://user-images.githubusercontent.com/24982706/147713515-194e5891-bb83-4291-ad62-c7fb54d5f4b9.png)[!] Error installing PromiseKit
[!] /usr/bin/git clone https://github.com/mxcl/PromiseKit.git /var/folders/3x/njrxwfk5683gbnpsgvb1l_rw0000gn/T/d20211229-3346-1fjxt1k --template= --single-branch --depth 1 --branch 6.15.3

Version 6.16.0 

![3688A5EB-73C8-49B7-A736-4A5E86CCE0F2](https://user-images.githubusercontent.com/24982706/147714657-e0e458ec-492e-4faf-a8a4-2c6a11c17424.png)

**Comment by mxcl** [comment]
Fixed.
