### ISSUE TITLE
 error: concurrency is only available in iOS 15.0.0 or newer    func async() async throws -> T {

### ISSUE THREAD

**Issue by Aravindios** [mxcl/PromiseKit#1292]
error: concurrency is only available in iOS 15.0.0 or newer
     [exec]      [exec]     func async() async throws -> T {

**Comment by mxcl** [comment]
Thanks for the report, you have not provided enough information for us to fix this.

**Comment by mxcl** [comment]
You need a newer Xcode.

https://stackoverflow.com/questions/69284960/ios-concurrency-is-only-available-in-ios-15-0-0-or-newer-in-protocol

Reopen if I'm wrong.

**Comment by mxcl** [comment]
We believe we fixed this properly in 6.18.1
