### ISSUE TITLE
hi, i want use anypromise in swift, but get a error. 

### ISSUE THREAD

**Issue by a603938361** [mxcl/PromiseKit#1294]
PromiseKit version 6.5.3
Pod version 1.11.3

oc code   
.m
`- (AnyPromise * _Nonnull)fetchThings
{
    return [AnyPromise promiseWithValue:@[@"a", @"b", @"c"]];
}`

and swift code
`let wxModule = WxShareModule()
    wxModule.fetchThings().map {
      $0 as! [String]
    }.done {
}`

and get this error 
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/9567891/184871598-baae58d7-4f72-4950-ad8d-f9e4e288836f.png">

please help me, thanks

**Comment by a603938361** [comment]
Because the network framework returns the data written by OC, the return value is anypromise， I want to use promise in swift, But I don't know how to convert。 Please help me, thank you。

**Comment by mxcl** [comment]
This is fine, chances are the error is hiding. Separate out the steps to see what the error actually is:

```swift
let wxModule = WxShareModule()
let a = wxModule.fetchThings()
let b = a.map{ $0 as! [String] }
let c = b.done { }
```

**Comment by a603938361** [comment]
hi get this error 
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/9567891/184881470-e42cbb33-fe8b-402d-9358-c46bab796510.png">

**Comment by mxcl** [comment]
I suggest you read our tests and use an example from there: https://github.com/mxcl/PromiseKit/blob/v6/Tests/Bridging/BridgingTests.swift
