### ISSUE TITLE
Problems building with Xcode 14.3 beta2

### ISSUE THREAD

**Issue by pepone** [mxcl/PromiseKit#1308]
I got this error when building with Carthage and Xcode 14.3 beta2 

```
/Users/jose/Documents/3.7.9/ice/Carthage/Checkouts/PromiseKit/PromiseKit.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.10, but the range of supported deployment target versions is 10.13 to 13.3.99. (in target 'PromiseKit' from project 'PromiseKit')
** ARCHIVE FAILED **
```

**Comment by mxcl** [comment]
This is a warning not an error.

I cannot help with build/deploy issues, I recommend hiring a contractor with the relevant experience.

**Comment by pepone** [comment]
sorry the actual error was above the warning

```
ld: file not found: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_macosx.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by threema-jarem** [comment]
We are seeing the same issue on Xcode 14.3 RC2. It looks like Apple has stopped shipping libarclite_iphoneos.a separately [1]. Bumping the minimum target to 11.0 which is the lowest supported by Xcode 14 resolves the issue.

@mxcl Would you accept a MR / or consider bumping the minimum target to iOS 11.0?

This error occurs when trying to build `v6` using Xcode 14.3 RC2.
`ld: file not found: /Applications/Xcode-14.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

[1]: https://developer.apple.com/forums/thread/725300

**Comment by mxcl** [comment]
Sure. I don't see what else can done tbh

**Comment by mxcl** [comment]
6.22.1 deploying
