### ISSUE TITLE
Current support of Obj-C PK version in Swift

### ISSUE THREAD

**Issue by mmackowiak** [mxcl/PromiseKit#131]
Hello guys,

should current Obj-C PromiseKit version work fine in Swift? README states:
> but Objective-C promises can be used from Swift

However, I am now hopeless about `then` used in Swift code.

```
promise.then { (mappingResult: RKMappingResult) -> Void
            
}
```

is continuously returning errors: 
```
Cannot convert the expression's type '() -> () -> $T2' to type '() -> ((AnyObject!) -> PMKPromise!)!' 
Cannot convert the expression's type '(RKMappingResult) -> Void' to type '() -> ((AnyObject!) -> PMKPromise!)!'
```

I tried including Swift framework, but I don't see any way to convert from PMKPromise to Promise. I'm using Yosemite and Xcode 6.1.1. Any help would be very appreciated, thanks!

**Comment by mxcl** [comment]
You can use them, but the syntax will suck because the objc then returns a block that takes a block. I haven't got any examples to hand, nor time right now to prepare one.

Ideally we'd create some kind of bridge, but as yet I haven't come up with the code for a good one.
