### ISSUE TITLE
dependabot requests

### ISSUE THREAD

**Issue by RomanPodymov** [mxcl/PromiseKit#1310]
Hello.
What should we do with #1267, #1285, #1290, #1298, #1299 and #1300?

* PromiseKit 6.21.0.
* SPM.

**Comment by mxcl** [comment]
I have tried to merge these before and it just breaks the tests.

It only effects tests so it's not in fact important.

If you close them they just come back… so basically I dunno what to do about it bar turning dependabot off. Which we probably can do, we have no deps really. Just in the tests.
