### ISSUE TITLE
Update Cocoapod Release Version?

### ISSUE THREAD

**Issue by LowAmmo** [mxcl/PromiseKit#1313]
Version: 6.18.1
Installed via: Cocoapods

Just requesting that someone release the latest version of PromiseKit to cocoapods? Cocoapods is currently at 6.18.1, would like to have the newest release available in cocoapods.

-thanks!

**Comment by mxcl** [comment]
ugh, sorry, it was failing and I get no notifications for github actions failure because github suck https://github.com/mxcl/PromiseKit/actions/runs/4583542058/jobs/8094452567#step:4:60

**Comment by LowAmmo** [comment]
@mxcl  - What a fun twist!

Yeah...we're also seeing the other error in that build internally right now - Xcode 14.3 requiring us to make sure all dependencies are using iOS 11 or newer for their minimum supported version.

**Comment by mxcl** [comment]
I dunno when I'll get to this, I am busy. In the meantime you can trivially have cocoapods use the git tag in your Podfile. If you don't know how ask ChatGPT.,

**Comment by cbauer10** [comment]
I just wanted to check and see if there was an update on this since it has been a month?

**Comment by mxcl** [comment]
Thanks for the ping I've re-registered with CocoaPods and now am having difficulty publishing because it insists on doing a 2 hour lint before it will publish anything which keeps failing because Apple’s dev tools… could be better.

**Comment by mxcl** [comment]
v8 is released

**Comment by LowAmmo** [comment]
@mxcl  - thanks for knocking this out!

**Comment by mxcl** [comment]
yw, lmk if any troubles
