### ISSUE TITLE
Request to updated SDK with the Privacy Manifest

### ISSUE THREAD

**Issue by sakshibala-halodoc** [mxcl/PromiseKit#1336]
Subject: We need to incorporate the xcprivacy manifest into our app . Starting March 13, Apple will send notifications when uploading builds to the App Store, and this will become mandatory from May 1. All the SDKs used in our app needs to incorporate the xcprivacy manifest.
Reference: https://developer.apple.com/news/?id=3d8a9yyh

Actions needed: We need the compatible xcprivacy manifest version IOS SDK with xcprivacy manifest. We are expecting a seamless upgrade by upgrading to the latest version.

**Comment by AktivoPallavi** [comment]
Please do needful.

**Comment by RomanPodymov** [comment]
Closing as duplicate #1332
