### ISSUE TITLE
question about PMKError remplacing any NSError subclass

### ISSUE THREAD

**Issue by malaba** [mxcl/PromiseKit#134]
Hi,

I noticed that the error I pass in a rejecter(error) get "simplified" to a PMKError class...

Hence only pure NSError can be handled. If we want to have our hierarchy of subclass of NSError they get tossed away right there, in PMKPromise.m, line 534-5 (on master 2015-01-21 16h40 GMT):

if ([foo isKindOfClass:[NSError class]])
        return [PMKError errorWithDomain:[foo domain] ?: PMKErrorDomain code:[foo code] userInfo:[foo userInfo]];

Why that choice ? Sur UserInfo is kept. But then only pure NSError can be used with PromiseKit.

It just happens that we have a whole hierarchy of NSError subclass, business oriented. What can I do if I get steamrolled like that ? :) 

Thanks

**Comment by mxcl** [comment]
PMKError is not for “simplification” it allows reference counting the error consumption so that unhanded errors can be reported.

However indeed, we shouldn't lose the type of the error the user provides. I can look into fixing that.

**Comment by mxcl** [comment]
Will push a new PromiseKit to cocoa pods this week.
