### ISSUE TITLE
Support errors as generic type in swift promise kit.

### ISSUE THREAD

**Issue by danthorpe** [mxcl/PromiseKit#135]
This is just an idea....

As we know, in Swift, enums allow us to create very succinct and rich types, which is great for describing errors. Also, keeping error application logic in this domain as error propagate through the layers of an application is beneficial, only converting them into `NSError`s when they need to be presented to the user.

To this end, it would be good if PromiseKit accepted errors using a generic type. So, usage could be something like this...

```swift
public protocol ErrorType {
    var code: Int { get }
    var domain: String { get }
    var localizedDescription: String? { get }
    var userInfo: Dictionary<NSObject, AnyObject>? { get }
}

extension NSError: ErrorType {
    public convenience init(_ error: ErrorType) {
        self.init(domain: error.domain, code: error.code, userInfo: error.userInfo)
    }
}

public class Promise<T, E: ErrorType> {

public var error: E?

}
```

Then, an application can define its own Error type, which can be used to reject promises, for example:

```swift
public enum NetworkError: ErrorType {
    case NotAuthenticated
}

public enum Error: ErrorType {

   case Network(NetworkError)
    // etc


    public var code: Int { 
        // etc
    }
    public var domain: String { 
        // etc
    }
}
```

Then, a promise can be rejected like this...

```swift
return Promise(error: .Network(.NotAuthenticated))
```

Using this pattern allows us to transform our custom `Error` type from a potentially vague error which lacks critical detail, to a specific error which can be recovered from with greater ease and clarity. At the moment, at the point I wish to reject the promise, I have to initialise an NSError, and lose the rich type detail.

Thoughts?

**Comment by mxcl** [comment]
The idea sounds useful.

I fear we couldn't do it without bumping to v2 though. As there may be code out there that expects `NSError` and will break if we change it.

**Comment by danthorpe** [comment]
Hmm, that a good point, it is quite a significant change, adding in an extra generic type. 

You don't think it would be sufficient that the error will be something conforming to `ErrorComponents` or whatever, which `NSError` does automatically (or could be made to)?

**Comment by mxcl** [comment]
Actually I guess it could be fine, since it will always be an NSError *unless* you decide to make it something else for your own purposes.

**Comment by mxcl** [comment]
I'm a little nervous about it though. `NSError` sucks, I've found this whole-heartedly since using Promises for 80% of my code paths, since Promises make it possible to do *good* error handling, and then you find you are limited by a code, a domain and a dictionary in what you can do next.

We could do something really special, with some more thought. This seems like the right direction.

**Comment by danthorpe** [comment]
Yeah, it's a like a default type.

I've found the technique to be really handy. My typical use case is in taking a strongly type error, (from and IDL like ProtoBuf, or Thrift) which comes from the server, and then mapping it to the app domain, and then transforming that generic server error to one with richer details, like the failed request, or a model type, which is then used to "handle" the error effectively.

At the very least, it allows me to use Swift's pattern matching on the error type directly, without resorting to status codes.

**Comment by danthorpe** [comment]
Maybe the best way forward is for you to model your own Error type, as you'd like to use with PromiseKit, and see what we can come up with?

**Comment by sdolidze** [comment]
What's wrong with error type being unconstrained like `Promise<T, E> ` not `Promise<T, E: ErrorType> ` or something similar?

**Comment by danthorpe** [comment]
For easy interoperation with `NSError` based APIs.

**Comment by sdolidze** [comment]
I'm sorry, I don't think I understand the problem. Can you give me an example where unconstrained error type would cause problems?

**Comment by danthorpe** [comment]
Well, I just think that if you need to pass the `E` object to some API which is expecting `NSError` (which is the Cocoa convention), then you'll need to be able to create such an object, which will require being able to determine error codes etc.

So... my intention would be that the core `Promise` type in PromiseKit would be able to mediate from `NSError` -> `E: ErrorType` -> `NSError`.

**Comment by sdolidze** [comment]
Oh, now I think I understand what you mean. But why should that be `Promise` type's responsibility? In my opinion, if you have an error type from you domain, it should be client code's responsibility to convert that domain error into `NSError` wherever needed.

**Comment by danthorpe** [comment]
Yes, but this means jumping through conversions whenever your error handling has to interact with PromiseKit. And, unless you write a lot of glue code, any associated types you might define with your own error type get lost. PromiseKit is designed to be used with chains, and error handling will typically be done at different points along that chain. Making the error type a generic will remove, the quite frankly limiting, `NSError` from this process.

**Comment by mxcl** [comment]
I’m interested in supporting some generic error, but I don’t want to make the API more complicated than necessary. I believe APIs should be as flexible as possible, but I also believe they should appear simple. I worry about turning people off PromiseKit because they have to declare every promise as:

    Promise<SomeType, SomeErrorType>(body: …)

If we can work around this then I'm cool with it.

Notably this also makes me not particularly want to support some generic Error protocol since it will make the catch APIs seem strange. If NSError is good enough for the whole of Cocoa, then it will perhaps *just* have to be good enough for us.

Thinking about it, isn't subclassing NSError enough for the desired usage here?

**Comment by danthorpe** [comment]
Yes, the biggest drawback to a generic error parameter is that the definition might look a little daunting.

Subclassing `NSError` is feasible if you want to use enum types for your error type.

One possible solution which i will investigate is just to subclass `Promise<T>` to add my own error type.

**Comment by sdolidze** [comment]
What if `Promise<Value, Error>` had a subclass `PromiseWithNSError<Error>`? (name should obviously be shorter). Here's an example to show what I mean:

```swift
class Pair<L,R> {
    let left: L
    let right: R
    
    init(left: L, right: R) {
        self.left = left
        self.right = right
    }
}

class PairWithString<L>: Pair<L, String> {
    override init(left: L, right: String) {
        super.init(left: left, right: right)
    }
}

let pairWithString: PairWithString<Int> = PairWithString(left: 5, right: "PromiseKit")
let pair: Pair<Int, String> = pairWithString
println(pair.left)
println(pair.right)
```

**Comment by mxcl** [comment]
So further to this. Why not just inherit from NSError for your error type?

**Comment by danthorpe** [comment]
@mxcl because that restricts the error type to being a class, and excludes using an enum.

**Comment by mxcl** [comment]
I guess for PMK2 we can have a baser-Promise so you can do this sort of stuff.

You are the 1% though.

**Comment by danthorpe** [comment]
Maybe, probably not a good idea to try to please the 1% though! :)

Related, have you seen: https://github.com/ReactKit/SwiftTask?

I think we can probably close this issue, as it's not a huge priority for me personally.

**Comment by danthorpe** [comment]
Also, just out of interest, I'm currently at SwiftSummint (https://www.swiftsummit.com) in London. And, so far 50% of the speakers have advocated using an `ErrorType` protocol to make errors a generic type, in a simplified Future pattern, and ReactiveCocoa 3.

**Comment by mxcl** [comment]
I'll believe when I see it.

**Comment by danthorpe** [comment]
Well, it happened 😄 - from the Swift book: https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/Swift_Programming_Language/ErrorHandling.html#//apple_ref/doc/uid/TP40014097-CH42-ID508

    Representing Errors
    In Swift, errors are represented by values of types conforming to the ErrorType protocol.

**Comment by mxcl** [comment]
Well, I meant, I'd believe it when developers were using their own in their own apps. The fact apple has standardized in this manner doesn't surprise me.

NSError conforms and everything in the SDK is throws NSError, we probably should change Promise to reject with ErrorType, but currently I'm having enough battles with the rest of Swift 2 in PMK so I'm not thinking that far ahead.

Though ErrorType is just an empty protocol afaict.

**Comment by mxcl** [comment]
I didn't expect this, but I was more saying I doubt most developers would demand a custom error type in their apps.

For PromiseKit I don't know what to do now, but I'll figure it out as I battle the compiler to make it even compile against Swift 2.

**Comment by mxcl** [comment]
Like ErrorType is just an empty protocol as far as I can tell. Empty objects don't carry much error information. I design APIs for less experienced users than you guys that also scale up and are useful to experienced developers so I'm reluctant to make Promise rejectable with nothing.

**Comment by mxcl** [comment]
Also notably, the SDK still is entirely NSErrors. Nothing, currently is something else.

Not that users shouldn't be allowed to use their own errorTypes. But currently I'm not even sure how users are going to use the new error handling in Swift. I'll have to watch all the sessions and then interpolate.

Maintaining Swift libraries is a constant iteration :/

**Comment by danthorpe** [comment]
Yeah, I'm trying to frantically update my open source projects too. :)

Firstly, I'm not suggesting PromiseKit should adopt a generic error type at all. There are other FRP projects which offer this level of customisation, I think PromiseKit is great when it makes UIKit more FRP ready.

My take-away on the error handling, is that Apple recognise that NSError is a bit of a bloated mess, and enums are a great fit for each API or framework to provide its own error type. And I've only seen this in use in NSFileManager so far, but I wouldn't be surprised if NSError begins to fade away as frameworks go from Objective-C -> Swift.

If I was writing a PromiseKit-like library, in Swift 2.0, then I would try to decompose the `Promise` type into a `PromiseType` protocol which supported a generic error type. And have the concrete implementation `Promise` use `NSError`. And then, extend `PromiseType` constrained with `NSError` for UIKit promise APIs. But, just thinking out loud really. :)

But, seeing as you've just done 2.0 (huge work I'm sure) - then forget about it until Swift 3.0!
