### ISSUE TITLE
dispatch_promise_in_background()

### ISSUE THREAD

**Issue by dbachrach** [mxcl/PromiseKit#141]
Building libraries that return promises, I often find myself wanting to execute work just off the main thread. I care little about which thread it's on other than that it's not the main thread.

The `dispatch_promise()` helper is nice, but it forces a dispatch even if you are already on a background thread.

I'm proposing `dispatch_promise_in_background()` as an API to create promises that will ensure execution is off the main thread.

```objc
PMKPromise *dispatch_promise_in_background(id block) {
    return [PMKPromise new:^(void(^fulfiller)(id), void(^rejecter)(id)){
        void(^executeBlock)() = ^{
            id result = safely_call_block(block, nil);
            if (IsError(result))
                rejecter(result);
            else
                fulfiller(result);
        };
        if ([NSThread isMainThread]) {
            dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), executeBlock);
        }
        else {
            executeBlock();
        }
    }];
}
```

**Comment by mxcl** [comment]
This “unleashes zalgo” and we should avoid that. I understand the desire for it, but think it should either reside in its own pod, or we can devise some strategy to make this pattern more elegant.

**Comment by mxcl** [comment]
I guess calling it `dispatch_promise_unleashing_zalgo` would suffice for me.

**Comment by mxcl** [comment]
Or `dispatch_zalgo` perhaps.

**Comment by mxcl** [comment]
For zalgo reference: http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony

**Comment by dbachrach** [comment]
Yeah looks like unleashing zalgo is the definition of what I'm looking for. I guess I'll switch back to just doing another dispatch. The only thing I'm tossing around is if you `dispatch_promise_in_background` inside of a queue that's already previously `dispatch_promise_in_background`ed then you are releasing zalgo internally but not externally to the root promise creation.

As an example, I have an API that provides:

```objc
- (PMKPromise*)fetchStuff {
    dispatch_promise_in_background(^{
         // do some work, take some locks, whatever
         return [networkManager fetchRequest:xyz];
}
```

Where networkManager's `fetchRequest` method is also a promised API whose implementation dispatches in background.

The caller of `fetchStuff` should see no zalgo because the promise is already forced to dispatch_async.

**Comment by mxcl** [comment]
Yes I am planning to release some zalgo APIs for Promise libraries to use.

IMO provided there are tests that prove that zalgo does not go public, this is the sort of efficiency gains *libraries* should aim for.

If the API is named with zalgo in it, then we are at least marking our code as dangerous for future maintainers to note.
