### ISSUE TITLE
Integration with Dash

### ISSUE THREAD

**Issue by iosengineer** [mxcl/PromiseKit#144]
Congrats on the new documentation site. It's a beauty! I'd like to be able to offline it for fast reference in Dash. Any ideas on how that's even possible? Or perhaps if the CocoaPods Documentation (which is Dash-supported) could be updated to include all content from the new site?

BTW. Thank you so much for this beautiful tool. As soon as I have pulled my head out of my butt in the Bitcoin revolution, you're the first donation.

**Comment by mxcl** [comment]
Sounds good. I'll look into it.

And don't worry about the donation :) I put that there mostly out of interest, in case anyone every would do it. I do this work for free without qualm: it's fun.

**Comment by mxcl** [comment]
Seems like you can add it via the CocoaPods option. Is that enough?

**Comment by iosengineer** [comment]
What comes through is a single information page rather than all of the new documentation. Perhaps I need to re-import it?

**Comment by mxcl** [comment]
Can you provide an example of something you want to emulate?

**Comment by mxcl** [comment]
I guess something like Backbone.js is a good example.

**Comment by iosengineer** [comment]
Hi Max,

Terribly sorry for the delay. Work went off the rails and then I was bedridden sick for a week. Not fun. I'm catching up on email so I'll try to review this in context shortly.

Thanks,
Adam.

**Comment by jordanbrown** [comment]
+1

**Comment by mxcl** [comment]
Closing. I have no time for this really, sorry. A PR would be accepted however.
