### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by LinusU** [mxcl/PromiseKit#145]
It would be great if I could just add `github "mxcl/PromiseKit" ~> 1.2.2` to my `Cartfile` and directly get going with PromiseKit.

Possibly the only thing needed is to share our xcode schemes.

> Carthage will only build Xcode schemes that are shared from your .xcodeproj. You can see if all of your intended schemes build successfully by running carthage build --no-skip-current, then checking the Carthage/Build folder.

> If an important scheme is not built when you run that command, open Xcode and make sure that the scheme is marked as “Shared,” so Carthage can discover it.

I don't know how it will handle the `objc` and `swift` folders thought...

Thanks!

**Comment by mxcl** [comment]
Yes, I've been pondering Carthage support for a couple weeks. I think I can get it working, this ticket will motivate me.

**Comment by LinusU** [comment]
Nice! I could really use it. You know you been doing too much Node.js programming when your swift code looks like this: :laughing: 

```swift
typealias Callback = (NSError?, AnyObject?) -> Void

func send(method: NSString, params: NSDictionary?, cb: Callback) {
    ...
}
```

**Comment by mxcl** [comment]
Carthage can now import the Swift version of PromiseKit.

**Comment by LinusU** [comment]
Nice! Thank you so much for the quick update :+1:
