### ISSUE TITLE
UIImagePickerController & Promise

### ISSUE THREAD

**Issue by frizzy75** [mxcl/PromiseKit#146]
1) UIViewController+Promise.swift, line 78 has the private method:
`imagePicker<T>(UIImagePickerController, Bool, ()->(), (NSDictionary)->T) -> Promise<T?>`
What is its purpose? As far as I can tell, it's never called?

2) I'm trying to call the method on line 90:
`promiseViewController(vc: UIImagePickerController, animated: Bool = false, completion:()->() = {}) -> Promise<UIImage?>`
But even when I explicitly cast the vc arg as a UIImagePickerController, the compiler chooses the method on line 68 instead:
`public func promiseViewController<T>(nc: UINavigationController, animated: Bool = false, completion:(Void)->() = {}) -> Promise<T>`
It works if I assign to a var like this:
`let p: Promise<UIImage?> = promiseViewController...`
Is there a better way to call the method and get the correct, overloaded version?

Thank you very much for this framework!

**Comment by mxcl** [comment]
1) yes I think this needs deletion
2) yes, this is a bug in the compiler. UIImagePickerController inherits nav controller and this seems to confuse it. I did find a work around for this personally, but can't recall what I did. I'll try to remember.

**Comment by frizzy75** [comment]
Thank you @mxcl

**Comment by mxcl** [comment]
Yeah, pretty sure my workaround was your workaround. Hopefully this will be fixed with Swift 1.2.
