### ISSUE TITLE
Compilation fails with Swift 1.2 (Xcode 6.3 beta)

### ISSUE THREAD

**Issue by ldiqual** [mxcl/PromiseKit#147]
Compiling PromiseKit in Xcode 6.3 fails because of new breaking language changes.

@mxcl Do you have something in the pipeline for 1.2 support? I know that there is a tool to convert from 1.1 to 1.2 automatically, and I guess we could detect the compiler version and `if/else` the affected parts of the code.

I'll spend some time on it this week.

**Comment by LinusU** [comment]
@ldiqual I don't know if you have already seen it but just wanted to point out that there is a branch for swift 1.2 support. You might want to base your work on that one if you are tinkering this week, happy hacking :)

**Comment by mxcl** [comment]
I started a branch called `swift-1.2` and reached impassable compile issues. I got the attention of the Swift people on Twitter and they agreed that something in Swift itself needs to be fixed, so we'll just have to wait on the next beta I'm afraid.

**Comment by mxcl** [comment]
If you want, you can check out the branch and try to find workarounds. I tried to find some, and eventually decided it wasn't going to happen.

**Comment by ldiqual** [comment]
I see, thanks for the details. Let's hope that improvements will come in the next beta, incremental compilation and no-crashes are really what play with my nerves now :/

**Comment by mxcl** [comment]
Compiles with Xcode 6.3 beta2
