### ISSUE TITLE
Join category is not in the podspec

### ISSUE THREAD

**Issue by frizull** [mxcl/PromiseKit#148]
The documentation mentions a "join" method that looks tasty, but I can't seem to find it when installed from CocoaPods.

**Comment by mxcl** [comment]
Just pushing to CocoaPods trunk…

**Comment by frizull** [comment]
Well, that was quick. Thank you so much!

**Comment by frizull** [comment]
Unfortunately, it would seem the pod is unusable as it is. The updated Podspec has not been picked up in the CocoaPods repo. And forcing the spec URL in the Podfile yields "xcodebuild: error: 'swift/PromiseKit.xcodeproj' does not exist." when trying to `pod install`.

**Comment by mxcl** [comment]
Sorry I think the push failed, looking into it.

**Comment by mxcl** [comment]
Seems pushed now.
