### ISSUE TITLE
CLLocationManager extension: add requestWhenInUseAuthorization

### ISSUE THREAD

**Issue by tp** [mxcl/PromiseKit#151]
I would propose to add a requestWhenInUseAuthorization function to CLLocationManager, since I would assume that this is also a common scenario and iOS scares the user all the when one is using the location "always".

I would quickly add it myself, but don't know how to best do it with regards to the open pull request also concerning AuthorizationCatcher.

**Comment by mxcl** [comment]
The default `promise` function already does this:

https://github.com/mxcl/PromiseKit/blob/master/Swift%20Sources/CLLocationManager%2BPromise.swift#L22

**Comment by mxcl** [comment]
So I saw where you were coming from and implemented your request and added more spice! Check it out.

**Comment by tp** [comment]
Awesome solution!

Since you're already checking `hasInfoPListKey("NSLocationAlwaysUsageDescription")`, would this be a good place to return an error if the required one is not set?

If I recall correctly, iOS does not error when the developer has not set these keys, but just does not show the dialog.

**Comment by mxcl** [comment]
Sure, that makes sense.
