### ISSUE TITLE
sendAsynchronousRequest returns nil rsp causes crash - swift

### ISSUE THREAD

**Issue by pieisgood** [mxcl/PromiseKit#153]
When handling an error returned by 
```
NSURLConnection.sendAsynchronouseRequest(request, queue:Q)
```
the rejecter function is called, but the rsp variable is nil. When checking if data is not nil there is no check that rsp is not nil before attempting to access its stringEncoding member. This causes a crash and bad instruction exception. 
This is all in NSURLConnection+Promise.swift
Is there a reason it is not checked for nil before this?  Is this a problem on my end?

**Comment by mxcl** [comment]
Fixed, I'll update CocoaPods later today.

**Comment by pieisgood** [comment]
awesome thanks!

**Comment by pieisgood** [comment]
to clarify, I believe this happens when the server sends back a 401. In my case I was sending an incorrect token to the server and got back a 401 because of this.

**Comment by mxcl** [comment]
Seems crazy you would get data, but no `NSURLResponse`, but the code should handle this now.
