### ISSUE TITLE
Could not build module 'OMGHTTPURLRQ' When trying to archive

### ISSUE THREAD

**Issue by bevbomb** [mxcl/PromiseKit#155]
I've spent the last hour trying to figure out why this won't archive, but it will happily build on device and simulator?

**Comment by mxcl** [comment]
I need more details. How did you install PromiseKit? What Xcode? Can you provide the build errors from the build log in Xcode? Thanks.

**Comment by mxcl** [comment]
I'm guessing this is Swift. I've had similar issues, in order to diagnose this specific one I'll need the full log from the “report navigator”.

**Comment by bevbomb** [comment]
It's swift, I've had promisekit installed for quite awhile now and hadn't updated it till the other day, I've submoduled it and installed it in the exact same manner as you would alamofire, but because promise kit now relies on a third party framework, I've also submoduled that and added it, but promisekit doesn't seem to recognise the framework

**Comment by mxcl** [comment]
Xcode cannot use it for some reason.

Verify that you have correctly linked the framework as as embedded library and not just as a linked library.

If you provide the full build output I can help more effectively.

**Comment by bevbomb** [comment]
I've had it installed as a submodule since the day I started using it months ago, 
I did also try installing as cocoa pods but that doesn't install them as frameworks, which means that it still won't import because it isn't a framework

**Comment by bevbomb** [comment]
I will provide images shortly of my settings

**Comment by bevbomb** [comment]
![promisekit intergration](https://cloud.githubusercontent.com/assets/7086909/6537704/9cb1a568-c4ad-11e4-82c0-843c15f5a790.png)

**Comment by bevbomb** [comment]
I can now see that OMGHTTPURLRQ framework is red.. Which is weird because it came straight from the git repo, I've also tried manually downloading and its still red

**Comment by bevbomb** [comment]
![promisekit archive error](https://cloud.githubusercontent.com/assets/7086909/6537873/37c43574-c4af-11e4-9907-cc2f388dd1fd.png)
Its weird because it will build fine and run on both simulator and device, but won't archive

**Comment by mxcl** [comment]
Try putting OMG ahead of PromiseKit in the target dependencies. Since PMK depends on OMG, that may be the problem. If not, we'll figure it out!

**Comment by bevbomb** [comment]
Ok so now its recognising it, but i have a new problem, it seems to think OMGHTTPURLRQ is a OS X framework and giving me a code signing error: 
Code Sign error: No matching codesigning identity found: No codesigning identities (i.e. certificate and private key pairs) matching “iPhone Developer” were found.

**Comment by mxcl** [comment]
Without the build output (click the lines next to the error message) I cannot help.

**Comment by mxcl** [comment]
I think I understand what is going on here. As a workaround: remove PromiseKit from the "target dependencies" list of for your app target. Build. Add PromiseKit. Build.

I am trying to determine a proper solution in the mean time.

**Comment by mxcl** [comment]
If you update I think I fixed it. Sorry for the trouble.

**Comment by bevbomb** [comment]
![screenshot 2015-03-10 09 18 03](https://cloud.githubusercontent.com/assets/7086909/6565733/7106b286-c706-11e4-9078-dd1c9a02f136.png)

**Comment by mxcl** [comment]
Anything here help? https://www.google.com/search?client=safari&rls=en&q=invalid+bundle+contains+disallowed+file+frameworks&ie=UTF-8&oe=UTF-8

**Comment by bevbomb** [comment]
They seem to all be pointed at extensions, PromiseKit isn't an extension, i assume it has something to do with the actual Project file containing references to the OMG framework,

**Comment by bevbomb** [comment]
As far as i can gather, you can't directing link a framework to another framework which is exactly what your doing with PromiseKit

**Comment by bevbomb** [comment]
Also if your plans for the future involve it being an umbrella framework, http://stackoverflow.com/questions/27484997/how-to-create-an-umbrella-framework-in-ios-sdk

**Comment by rodsfreitas** [comment]
Are you using Carthage? I'm having a problem that probably is related. 
`dyld: Library not loaded: @rpath/PromiseKit.framework/PromiseKit
  Referenced from: /var/containers/Bundle/Application/596AA7ED-98FB-4704-BF1D-897DA3492262/App.app/App
  Reason: image not found
(lldb) `

I added the OMGHTTPURLRQ to the linked frameworks.
