### ISSUE TITLE
PromiseKit: Unhandled error.  Don't understand why.

### ISSUE THREAD

**Issue by webdevotion** [mxcl/PromiseKit#156]
Hello

I have a API call from which I might manually return an NSError, for example when the returned list is nil / empty or the returned data is not adhering to a certain structure.  In those cases I `reject` the promise and pass in this `NSerror` instance that I just created on the fly.

Although my promise calls the `catch` block at the expected moment in the chain, 
`PromiseKit` still throws:

```
PromiseKit: Unhandled error: Error Domain=DSHMenuFactory Code=1 
"The operation couldn’t be completed. (DSHMenuFactory error 1.)" 
UserInfo=0x7ff27992d830 {description=Given parameter 'menu' is not of type NSDictionary as expected}
```

Makes me wonder if I should use `reject` in these cases.
I am not using GCD in these promises.  Thoughts are appreciated.

**Comment by webdevotion** [comment]
Fixed my problem by reading http://promisekit.org/breaking-the-chain/.

TIL: just return the `NSError` instance in stead of `reject(myError)`.

**Comment by mxcl** [comment]
Can you show the original code? There may be a bug in PromiseKit here still. It depends if an error escaped a chain somehow.

**Comment by webdevotion** [comment]
Thanks for your interest @mxcl. I went back in my git repo and checked different version up to 4 days ago but could not find a single instance in which I am returning `NSError` in stead of `rejecter(error)`.  So while the docs as mentioned above are still valid, I do not and did not find an issue that could help you.  I will keep this problem in mind and will post relevant code.  Thanks for PMK.
