### ISSUE TITLE
EXC_BreakPoint on UIViewController.reject()

### ISSUE THREAD

**Issue by liujuncheng** [mxcl/PromiseKit#160]
The demo code is here https://github.com/liujuncheng/PromiseKitViewContoller

libswiftCore.dylib`swift_dynamicCastClassUnconditional:
0x10032a4f0:  cmp    x0, #1
0x10032a4f4:  b.lt   0x10032a528               ; swift_dynamicCastClassUnconditional + 56
0x10032a4f8:  ldr    x8, [x0]
0x10032a4fc:  adr    x9, #347084               ; swift_isaMask
0x10032a500:  nop    
0x10032a504:  ldr    x9, [x9]
0x10032a508:  and    x8, x9, x8
0x10032a50c:  cmp    x8, x1
0x10032a510:  b.eq   0x10032a520               ; swift_dynamicCastClassUnconditional + 48
0x10032a514:  ldr    x8, [x8, #8]
0x10032a518:  cbnz   x8, 0x10032a50c           ; swift_dynamicCastClassUnconditional + 28
0x10032a51c:  b      0x10032a528               ; swift_dynamicCastClassUnconditional + 56
0x10032a520:  cbz    x0, 0x10032a528           ; swift_dynamicCastClassUnconditional + 56
0x10032a524:  ret    
0x10032a528:  brk    #1

**Comment by mxcl** [comment]
Apologies, I'll look into it.

**Comment by mxcl** [comment]
Sorry for the delay. But it's fixed now. 1.4.3 being pushed.
