### ISSUE TITLE
Add promise block method macros

### ISSUE THREAD

**Issue by stefanfisk** [mxcl/PromiseKit#161]
This is just a random small idea I'm toying with:

```
#define PMKBeginPromiseBlockMethod(name, ...) \
- (PMKPromise* (^)(__VA_ARGS__))name \
{ \
    return ^PMKPromise*(__VA_ARGS__) {

#define PMKEndPromiseBlockMethod() \
    }; \
}
```

Would let you define methods that return blocks that return promises with the following syntax:

```
PMKBeginPromiseBlockMethod(echo, NSString* string)
{
    return [PMKPromise promiseWithValue:string];
}
PMKEndPromiseBlockMethod()
```

Which IMHO is quite a bit cleaner and safer than:

```
- (PMKPromise *(^)(NSString* string))echo {
    return ^(NSString* string){
        return [PMKPromise promiseWithValue:string];
    };
}
```

From what I can tell they play fairly nicely with Xcode as well.

**Comment by stefanfisk** [comment]
```
#define PMKDeclPromiseBlockMethod(name, ...) \
- (PMKPromise* (^)(__VA_ARGS__))name
```

Would probably also make sense.

**Comment by mxcl** [comment]
Is this for `PMKPromise.m`? Or for your code in general? Just interested.

**Comment by stefanfisk** [comment]
For both I'd say, so that it becomes easier to implement methods returning block just like PMKPromise does today.

But I only out like five minutes of thought into it, so YMMV, I've yet to write any functioning code with PMK, although I've used promises a lot on node.

**Comment by mxcl** [comment]
Where do you use this construct in your own code? I'd only ever thought people would just return a promise, so you wouldn't need it.

**Comment by mxcl** [comment]
Closing because I don’t want to encourage people to add these methods (and adding public helper macros would do that) and can’t immediately see why anyone would want to do it outside of PromiseKit when using PromiseKit.
