### ISSUE TITLE
Fulfil and reject instance methods

### ISSUE THREAD

**Issue by lukagabric** [mxcl/PromiseKit#162]
I was wandering why there are no fulfil or reject instance methods?

It would simplify this:
http://promisekit.org/wrapping-delegation/

It would also be easier to use with NSOperation.

PMKPromise *promise = [PMKPromise new];

You could return promise instance and do some work. When you're done you could just do
[promise fulfil:value];
or
[promise reject:error];

**Comment by mxcl** [comment]
If you can fulfill or reject any promise, then any part of your application could fulfill ore reject any promise, which would break encapsulation.

The usual pattern instead is a deferred which would look something like this:

```objc
PMKDeferred *deferred = [PMKPromise deferred];
//…
deferred.fulfill(obj);
return [deferred promise];
```

I provided a Deferred with Swift PromiseKit but not with the objective C version.

**Comment by mxcl** [comment]
Discussion about this welcome though!
