### ISSUE TITLE
Automatically chaining promises

### ISSUE THREAD

**Issue by warpling** [mxcl/PromiseKit#163]
I'm trying to figure out how to **automatically chain an array of promises to execute synchronously** like in [the chaining example](http://promisekit.org/chaining/). Any promise that throws an error should be caught and stop execution of the subsequent promises, returning normally otherwise.

I don't think PMKPromise has a helper like this, so I am trying to create one. Any and all pointers are appreciated!

This is the behavior I'm roughly trying to achieve, but from an array of Promises.

        [self firstPromise].then(^(BOOL success) {
            return [self secondPromise];
        }).catch(^(NSError *error){
            // First promise failed. reject
        }).then(^(BOOL success) {
            if (success) {
                // All promises successful! fulfill
            }
        }).catch(^(NSError *error){
            // Second promise failed. reject
        });

**Comment by mxcl** [comment]
Sorry, I don’t understand the request. The closest I can get is you want to serially iterate over a series of promise chains one at a time and reject a root promise if any of those reject.

**Comment by warpling** [comment]
Sorry I was unclear. What you describe is exactly what im trying to achieve.




I've been unable to find a straightforward way to automatically construct that from an array.

**Comment by mxcl** [comment]
Nothing is provided in PromiseKit explicitly to do this, but this will work:

```objc
@interface PMKPromise (Chain)
+ (PMKPromise *)chain:(NSArray *)promises {
    if (promises.count > 0) {
        PMKPromise *prev = promises[0];
        [promises removeObjectAtIndex:0];
        for promise in promises {
            prev = prev.then(^{ return promise; })
        }
        return prev;
    }
}
@end
```

**Comment by warpling** [comment]
Interesting! I had something similar but I knew was the wrong answer since it was recursive haha
I hadn't realized I could keep appending `.then(...)` to the original Promise but that makes complete sense now. Thank you!

**Comment by mxcl** [comment]
Well it's not the original promise. We keep the new promise from each then each time.

Let me know if you need any further help 👍

**Comment by warpling** [comment]
Ah because calling `.then(...)` on a promise returns a new promise right?

**Comment by mxcl** [comment]
Yes, or you wouldn't be able to call `then` again.

**Comment by warpling** [comment]
Makes sense :)
