### ISSUE TITLE
OS X framework target?

### ISSUE THREAD

**Issue by tonyarnold** [mxcl/PromiseKit#164]
Is the "iOS and OS X" description on the repo a typo? There's no OS X target in the project.

**Comment by mxcl** [comment]
There is for CocoaPod, but not in the xcodeproj right now, however coincidentally I have this in my local branch after some recent OS X work so I'll clean it up and push.

Apologies for this the xcodeproj only recently became more important due to Carthage.

**Comment by mxcl** [comment]
The xcodeproj only builds the swift version currently as well. Something to keep in mind.

I am fixing that for a version 2 bump, but that isn't ready yet.

**Comment by mxcl** [comment]
Pushed https://github.com/mxcl/PromiseKit/commit/161bd47d56ba03d88925376f24be29521add04c3

**Comment by tonyarnold** [comment]
Great stuff, thanks @mxcl!
