### ISSUE TITLE
Use PMKPromise with Swift 

### ISSUE THREAD

**Issue by robertomg** [mxcl/PromiseKit#165]
I have had some troubles using PMKPromise in Swift. We have a big project written in objective-C that uses PromiseKit (PMKPromise) and we would like to start using Swift. 

In more detail, the problem is that when calling ```then``` with a Swift closure as a parameter, the compiler complaints about the types of the parameter.

**Comment by robertomg** [comment]
Since I did not find any solution, I tried to fix it. To address this problem I have created a category of PMKPromise that allows creating promise ```then``` blocks out of a Swift closure:

```swift
extension PMKPromise {
    
    private func objCBlockFromPromiseClosure(closure: (AnyObject) -> (PMKPromise?)) -> AnyObject {
        return unsafeBitCast(closure as @objc_block (AnyObject) -> (PMKPromise?), AnyObject.self)
    }
    
    func swiftThen(closure: (AnyObject) -> (PMKPromise?)) -> PMKPromise {
        return self.then()(objCBlockFromPromiseClosure(closure))
    }
}
```

To use it: 

```swift
let fetchUserPromise : PMKPromise = ...

fetchUserPromise.swiftThen({object in
   if let user = object as? User {
      self.doSomeWorkWithUser(user)
      return nil
   }
})
```

The problem is that it only accepts one object (```AnyObject```) as a parameter of the then closure. But it solves my problem, at least, for the transition time between objective-c and Swift.

**Comment by mxcl** [comment]
You can't use PMKPromise (well) in Swift as described in the documentation.

I am attempting to fix this for version 2. But the objective C version uses a number of tricks that are not interoperable with Swift.

Had I know Swift was coming, I would have made a few changes here and there.

**Comment by mxcl** [comment]
Nice solution though! I'll supplement our docs with it.

**Comment by mxcl** [comment]
https://github.com/mxcl/PromiseKit/commit/61f16ffaf808f00df8949d433fecd382f5fdf394

**Comment by robertomg** [comment]
I know that this is not a last-longing solution but for those developers who use PromiseKit for Obj-C and they would like to start using Swift gradually, it may help. I would be glad to see a better solution to integrate the library in both languages. Thank you for adding it to the documentation page.

**Comment by mxcl** [comment]
2.0 solves this and will be merged in the near future.

**Comment by jspavlick** [comment]
Will 2.0 be iOS 8 and above only?

**Comment by mxcl** [comment]
For Swift it's the same as 1.x, it'll work on 7, it's just CocoaPods and Carthage will both not install Swift libraries to 7.x deployment targets. So you have to do it by hand.

**Comment by mxcl** [comment]
However I intend to attempt to build a static library version of 1 and 2 that can be dropped in (with headers for objc) to an iOS 7 project.
