### ISSUE TITLE
CocoaPods iOS 7 support

### ISSUE THREAD

**Issue by zdenektopic** [mxcl/PromiseKit#167]
cocoapods is weak-linking the frameworks if deployment target is below 8.0. Should work now fine with iOS 7.

Could you test it and lower the deployment target to 7.0 for swift tree? :)

**Comment by mxcl** [comment]
Good news! Sorry to ask rather than Google, is this in the latest gem or a pre-release?

**Comment by ide** [comment]
The discussion at https://github.com/CocoaPods/swift/issues/9 indicates that iOS 7 isn't compatible with dynamic frameworks if you want to publish to the App Store. Your code will run but iTunes Connect will reject it.

**Comment by mxcl** [comment]
Got a link to something @zdenektopic?

**Comment by carlhunterroach** [comment]
Here is a method for using dynamic frameworks with target < iOS 8
https://github.com/quellish/Weakness
