### ISSUE TITLE
Cocoapods use_frameworks! support

### ISSUE THREAD

**Issue by Kirow** [mxcl/PromiseKit#169]
I have a problem when using ```use_frameworks!``` (for Objective-C project if it is matter)
got errors like
```
'NSURLConnection+PromiseKit.h' file not found with <angled> include; use "quotes" instead
'NSNotificationCenter+PromiseKit.h' file not found with <angled> include; use "quotes" instead
```
because of
```
#import <NSURLConnection+PromiseKit.h>
#import <NSNotificationCenter+PromiseKit.h>
```

I've pointed [here](https://github.com/mxcl/PromiseKit/commit/7be0a05fa6883d244989ffff5a5b4de7a02b83f9) what helps me to build pods for myself. But I did not make pull request because I don't know why these files included to podspec.

**Comment by mxcl** [comment]
If you make it into a framework though, you have to import it with a framework import statement:

```
#import <PromiseKit/NSURLConnection+PromiseKit.h>
```

Does that help?

**Comment by Kirow** [comment]
Yep, this will help too, but not sure that someone use these deprecated headers

**Comment by mxcl** [comment]
Closing because if you use frameworks, you have to use them properly.

**Comment by mxcl** [comment]
1.4.3 will remove the deprecations. It's been almost a year, hopefully people who used those headers back when they *were* the proper headers will cope.
