### ISSUE TITLE
Doc mentions 'join' but links to wrong page

### ISSUE THREAD

**Issue by webdevotion** [mxcl/PromiseKit#170]
[http://promisekit.org/when/](http://promisekit.org/when/) links to `join` in the "oh btw!" ([link](http://cocoadocs.org/docsets/PromiseKit/1.2.2/Classes/PMKPromise.html#//api/name/join)).
The resulting page does not mention `join`. Tried to find it with CMD + F.

I understand it's part of a subspec, but that's not made obvious from the docs.

**Comment by mxcl** [comment]
The recent CocoaDocs update changed the links format apparently.
