### ISSUE TITLE
PromiseKit: Unhandled error: when rejecting a promise

### ISSUE THREAD

**Issue by bluemasterflows** [mxcl/PromiseKit#171]
1. I seal my own promise.
2. I call fulfill(NSDictionary) on the success condition, and the guy calling my promise receives the NSDictionary in his .then . 
3. I call reject(NSError) on the failure condition, and the guy calling my promise never has his .catch hit. why?
Is this an issue with PromiseKit?

I have a Gist here: https://gist.github.com/bluemasterflows/4a23f80878333018aeea 
The Reject with "blah1" gets hit, but the calling Catch never receives it.
Calling code: (the urlSession I pass it will cause the call to fail).

        RestTransport *restTransport = [[RestTransport alloc] initWithSession:urlSession];
        [restTransport issueRequest:urlSession].then(^(NSDictionary *response){
            NSLog(@"I don't get hit because the call fails.");
        }).catch(^(NSError *error){
            NSLog(@"I should get hit, but I don't");
        });

Using PromiseKit 1.4.2

**Comment by bluemasterflows** [comment]
Nevermind. Problem on my end. 

Your framework is amazing, btw!

**Comment by mxcl** [comment]
Glad it worked out. Let me know if you have any other problems.
