### ISSUE TITLE
CLLocationManager.promise() never resolves

### ISSUE THREAD

**Issue by khaullen** [mxcl/PromiseKit#174]
Since jumping from `1.4.0` to `1.5.0` and Swift 1.2, I can't seem to get `CLLocationManager.promise()` to ever resolve.  The following test fails each time, due to the unfulfilled expectation:
```
    func testLocation() {
        let expectation = expectationWithDescription("location")
        CLLocationManager.promise().then { (location: CLLocation) -> Void in
            println(location)
            expectation.fulfill()
        }
        waitForExpectationsWithTimeout(13, handler: nil)
    }
```

**Comment by mxcl** [comment]
Fixed with: https://github.com/mxcl/PromiseKit/commit/7fdef1e6e41c6c7c94bb3c45e2ec17a4222b2af7

I'm really sorry I didn't push a new pod for that. I thought I had.

Related: we need tests for this kind of thing, but I couldn't figure out how to make tests for eg. CLLocationManager that are reliable. Unreliable tests are useless. Any ideas?

**Comment by mxcl** [comment]
Pushing 1.5.1…

**Comment by mxcl** [comment]
Pushed.

**Comment by khaullen** [comment]
Thanks for the quick fix. What kinds of tests do you have in mind? Is the one above unreliable?

**Comment by mxcl** [comment]
Yes, because the simulator is buggy when it comes to simulating location.

**Comment by khaullen** [comment]
Ah yes, this is what stubs are for right? Could we stub out CLLocationManager to always provide a fixed set of coordinates?

**Comment by mxcl** [comment]
Yeah true, that would be fine for this case.

**Comment by mxcl** [comment]
In fact, would stubbing have detected this? What we needed to do is trigger the CLLocationManager to call its delegates. Stubbing probably would have worked here while in actual usage it would not have because our delegate was invisible to the location manager (which seems like a Swift bug).
