### ISSUE TITLE
"Ambiguous use of 'catch'"

### ISSUE THREAD

**Issue by donnywals** [mxcl/PromiseKit#175]
When I try to catch an error like this:

``` swift
func fetchFeed() {
    feedPromise().then{ [weak self] (data:[FeedItem]) -> () in
        self?.data = data
        return
    }.catch(onQueue: dispatch_get_main_queue(), body: {(error: NSError) -> Void in
        println("error caught")
    })
}

func feedPromise() -> Promise<[FeedItem]> {
// rest of the code..
```

I get the following error:
__Ambiguous use of 'catch'__

I saw issue #56 but the code that worked in that issue doesn't seem to work for me. Any ideas on how to fix / work around this?

**Comment by mxcl** [comment]
If this indeed doesn’t work, can you provide the exact error message when it doesn’t work?

```swift
func fetchFeed() {
    let _:() = feedPromise().then{ [weak self] (data:[FeedItem]) -> () in
        self?.data = data
        return
    }.catch { error -> Void in
        println("error caught")
    }
}
```

**Comment by mxcl** [comment]
The title of this bug report is a favorite.

**Comment by donnywals** [comment]
The code sample you put here seems to work, thanks a lot!

 I've been messing for way too long..

**Comment by mxcl** [comment]
PromiseKit 2 fixes this. I hope to release it within the month.

With study I believe the ambiguity cannot be determined by the compiler without a layer of analysis Apple will never write.

I can't fix it for PMK1 without breaking source compatibility.
