### ISSUE TITLE
Missing argument for parameter 'body' in call

### ISSUE THREAD

**Issue by Naoto-Ida** [mxcl/PromiseKit#176]
Hi,
I'm not that aware enough of PromiseKit to tell if this is due to my code or a issue-worthy bug,
but I am receiving an error with "Missing argument for parameter 'body' in call".

Here is my code.

It only happens when I add a second line of code with in the `.then` part.

```
let json = API.getSomething()
        json.then { (v: <Array<String>>) in
                println(v)
                println("hello")
        }
        json.catch { (e: NSError) in
                println(e.domain)
        }
```

It can be countered by adding ` -> Void` before each `in` to specify a type.
Is this a bug, or is it something I am not understanding?

Thanks,

Naoto Ida

**Comment by mxcl** [comment]
Yes, this is a Swift bug. It fails to infer the return type. Hopefully it'll be fixed in 1.3.
