### ISSUE TITLE
Compilation Error: expected unqualified-id

### ISSUE THREAD

**Issue by Kirow** [mxcl/PromiseKit#177]
Can not compile **.mm** file with ```.catch(^(NSError *error) { } )```

**Comment by mxcl** [comment]
I see, well I expect this means objective c promise kit won't work with objective c++ then.

To me this sounds like a compiler bug though as the syntax is fine.

I'll test it, but I wouldn't get your hopes up.

**Comment by csotiriou** [comment]
Same here. It seems an Objective C++ issue. Could it be because C++ doesn't allow any keywords to be used as parameter names, even if they are used in a totally different context?

**Comment by mxcl** [comment]
Yes, of course. Catch is a c++ keyword.

I guess we can put `#if __cplusplus` around the catch and change its name slightly.

**Comment by mxcl** [comment]
For objc++ one will just have to use `promise.catchOn(dispatch_get_main_queue(), ^{ /*…*/ });`, which is less pleasant but I think is the choice of “least surprise”.
