### ISSUE TITLE
Swift: Use of unresolved identifier 'dispatch_promise '

### ISSUE THREAD

**Issue by thegreatmichael** [mxcl/PromiseKit#180]
Thanks for the work on promisekit! I am trying to use it in swift. It seems that `import PromiseKit` works because it will let me construct a promise via `Promise(value:someStr)`. But whenever I try to use `dispatch_promise`, I get the error in the title. What am j doing wrong?

**Comment by mxcl** [comment]
There is no `dispatch_promise` in Swift. I removed it because people were usually using it incorrectly to start a promise chain and that is not the way that promise chains should be started. Here’s the equivalent:

```swift
return Promise { fulfill, _ in
    dispatch_async(dispatch_get_global_queue(0,0)) {
        // do work
        fulfill(foo)
    }
}
```

Leaving open for discussion.
