### ISSUE TITLE
PromiseKit integration problem when supporting iOS7

### ISSUE THREAD

**Issue by avdwerff** [mxcl/PromiseKit#184]
For a project we used to use PromiseKit 1.2 with success. The complete swift source was added to the project. However we want to upgrade to xcode 6.3.1, because of swift 1.2 support.
I can't use the dynamic lib option (Carthage or Pod >= 0.3.6), because support for iOS7 is still required.
I tried to just add the source files again, but now it complains for NSTask stuff. 
Also the sub module option didn't work out, the problem with that was that it will create a framework for iOS >=8 and we need iOS7 support. 
If I change the deployment targets for PromiseKit and OMGHTTPURLRQ to iOS 7, the today extension (we use in the app) will nag about a framework build with iOS7....

I'm lost here.. any help/ideas would be appreciated.

**Comment by mxcl** [comment]
Well there's a few problems here.

1. If you add the sources manually, then remove the OS X specific files, e.g.. NSTask.swift
2. Dynamic frameworks are not supported on iOS 7, so Carthage cannot support iOS 7.
3. Today extensions are iOS 8 only

If you want to use Swift PromiseKit with iOS 7 then your only option right now is to compile by hand because both CocoaPods and Carthage required iOS 8 for Swift dependencies. If you add all the sources that you need (don't add *all* the categories) and exclude any OS X specific files (NSTask is the only one I believe), you should be OK.

I'm sorry there isn't a better way currently, but Swift is new and there aren't many options yet.

**Comment by Dridus** [comment]
FWIW I have this working on Xcode 6.3.1 targeting iOS 7. I did the whole source approach, including both the OMGHTTPURLRQ and PromiseKit sources in my project, sticking this in my bridging header:

```objc
#import "OMGHTTPURLRQ.h"
#import "PromiseKit.h"
```

and with this diff to the PromiseKit sources:

```diff
diff --git a/Swift Sources/NSURLConnection+Promise.swift b/Swift Sources/NSURLConnection+Promise.swift
index db860d2..18552b7 100644
--- a/Swift Sources/NSURLConnection+Promise.swift
+++ b/Swift Sources/NSURLConnection+Promise.swift
@@ -1,5 +1,5 @@
 import Foundation
-import OMGHTTPURLRQ
+//import OMGHTTPURLRQ


 extension NSURLResponse {
diff --git a/Swift Sources/PromiseKit.h b/Swift Sources/PromiseKit.h
index 9316b59..4b25f31 100644
--- a/Swift Sources/PromiseKit.h
+++ b/Swift Sources/PromiseKit.h
@@ -8,4 +8,4 @@ FOUNDATION_EXPORT const unsigned char PromiseKitVersionString[];

 // for convenience and better error messages if you don’t
 // have OMGHTTPURLRQ available and to hand
-@import OMGHTTPURLRQ;
+//@import OMGHTTPURLRQ;
```

also I had this hanging around in my sources to fix an old linking error but I'm not sure if it's still required:

```swift
import AssetsLibrary

// reference this to force libswiftAssetsLibrary to be linked
let assetsLibrary = ALAssetsLibrary()
```

**Comment by mxcl** [comment]
I should add some documentation for supporting iOS 7 with the Swift version.

**Comment by avdwerff** [comment]
Thanks, guys, I guess I didn't realise I was also adding the osx sources (NSTask etc.). 
Do I as well need to include the OMGHTTPURLRQ manually..? Or that could be a pod install, right?
I will try it again.

**Comment by mxcl** [comment]
You can just pod install OMG since it is not Swift and thus you won't have the above problems.

You only need OMG with the NSURLConnection category, so don't include either if you don't need that.
