### ISSUE TITLE
What's the meaning of the logo?

### ISSUE THREAD

**Issue by lexrus** [mxcl/PromiseKit#185]
This lib is amazing. But I can't get the point of the logo.

Thanks.

**Comment by mxcl** [comment]
I don’t know if it has a meaning. I asked an artist to draw me something with elephants and this is what I got.

I chose elephants as they never forget which is the kind of quality you want in a promise.

**Comment by robrix** [comment]
Further, since promises enjoy monadic properties, it’s only fitting that one elephant defines the shape of another elephant. Put another way: Elephants, like promises and other monads, have the closure property.

**Comment by christianbundy** [comment]
This is now officially the stupidest thing I've ever fell in love with.

My ex will be *thrilled*.
