### ISSUE TITLE
Enable Cocoapod Support for Swift/Promise for iOS 7 + OSX 10.9

### ISSUE THREAD

**Issue by aleffert** [mxcl/PromiseKit#186]
As best I can tell there's nothing preventing just the core Swift/Promise from being used on earlier operating systems, but Cocoapods won't let me use it claiming it requires iOS 8. I tried updating the podspec for that subspec as best I understood it, but ``pod lib lint`` failed. Is there an easy way to make this work? Am I missing something and there's actually a problem using the core Promise API on the older operating systems? Thanks!

**Comment by mxcl** [comment]
CocoaPods does not support iOS 7 and Swift.

**Comment by mxcl** [comment]
This is the only resource that I could find that includes a (truly terrifying) work around: https://medium.com/ios-os-x-development/how-to-use-swift-cocoapods-and-still-support-ios-7-0-f9dc29b3628b

**Comment by mxcl** [comment]
Reopening as I will experiment with this: https://github.com/SnapKit/SnapKit/issues/12

Note I won't be able to make it work with CocoaPods, but it will be a solution that is simpler than manually compelling the sources.

**Comment by jessepollak** [comment]
:+1: 

Thank you for all of your hard work, you're awesome.

**Comment by mxcl** [comment]
Here is a solution: https://github.com/PromiseKit/EZiOS7

**Comment by mxcl** [comment]
As said, I can't support CocoaPods, although in theory a static library could be provided via a different podspec.
