### ISSUE TITLE
PMKManifold with a promise

### ISSUE THREAD

**Issue by eytanbiala** [mxcl/PromiseKit#187]
Is there a way to return a promise as part of `PMKManifold`?
I am trying to keep access to a dictionary that I need in a later part of the chain, but not quite sure how to go about it.

For example, how can I pass the `requests` array from the first block to the second block?
```
[self generateRequests].thenInBackground(^(NSArray *requests) {
	return [myApi postRequests:requests]; // this is a network request, returns a promise
}).thenInBackground(^(NSArray *requests, NSArray *responses) {
       // do other stuff here, need access to "requests"
});
```

I tried using `PMKManifold` to do `PMKManifold([myApi postRequests:requests], requests)`, but that is just for passing multiple return values, not waiting for a promise to resolve.

Thanks in advance for any suggestions.

**Comment by mxcl** [comment]
Yes, PMKManifold does not wait for promises. This bug was reported and we decided to leave it like this as the manifold is like a "box", but tickets like this make me reconsider.

Maybe this isn't satisfying, but here's your option:

```objc
[self generateRequests].thenInBackground(^(NSArray *requests) {
    return [myApi postRequests:requests].thenInBackground(^(NSArray *responses) {
        // do other stuff here, need access to "requests"
    }):
});
```

or:


```objc
[self generateRequests].thenInBackground(^(NSArray *requests) {
    return [myApi postRequests:requests].then(^(id responses){
        return PMKManifold(requests, responses);
    });
}).thenInBackground(^(NSArray *requests, NSArray *responses) {
       // do other stuff here, need access to "requests"
});
```

**Comment by eytanbiala** [comment]
While it would be nice to have PMKManifold handle it, I think you are correct to keep it as is. The alternatives you provided are perfectly fine, I don't think this kind of functionality is frequently need.
