### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Vaseltior** [mxcl/PromiseKit#188]
Hi, 

I wrote this function: 

    func getBlogs() -> Promise<[AnyObject]> {
        return Promise{ fulfill, reject in
            Alamofire.request(Router.GetBlogs(query: "")).response { (_, _, data, error) in
                if error == nil {
                    if let xwsse = data as? [String:AnyObject] {
                        Swell.debug { data!.description }
                        
                        if let result = data as? [AnyObject] {
                            fulfill(result)
                        }
                    }
                    
                } else {
                    reject(error!)
                }
            }
        }
    }

based on your answer here: http://stackoverflow.com/questions/28634995/chain-multiple-alamofire-requests

And I get compilation issues 
Global is external, but doesn't have external or weak linkage!

    Global is external, but doesn't have external or weak linkage!
    i8* ()* @_TFFFC8Haunters11SFAPIClient8getBlogsFS0_FT_GC10PromiseKit7PromiseGSaPSs9AnyObject___U_FTFGSaPS3___T_FCSo7NSErrorT__T_auL_6rejectFS4_T_
    invalid linkage type for function declaration 
    i8* ()* @_TFFFC8Haunters11SFAPIClient8getBlogsFS0_FT_GC10PromiseKit7PromiseGSaPSs9AnyObject___U_FTFGSaPS3___T_FCSo7NSErrorT__T_auL_6rejectFS4_T_
    Global is external, but doesn't have external or weak linkage!
    i8* ()* @_TFFFC8Haunters11SFAPIClient8getBlogsFS0_FT_GC10PromiseKit7PromiseGSaPSs9AnyObject___U_FTFGSaPS3___T_FCSo7NSErrorT__T_auL_7fulfillFGSaPS3___T_
    invalid linkage type for function declaration
    i8* ()* @_TFFFC8Haunters11SFAPIClient8getBlogsFS0_FT_GC10PromiseKit7PromiseGSaPSs9AnyObject___U_FTFGSaPS3___T_FCSo7NSErrorT__T_auL_7fulfillFGSaPS3___T_

As soon as `fulfill(result)` is in the *Alamofire* closure I'm not able to compile. Do you have any idea? Is it XCode 6.3.1, is it a bug in *PromiseKit* or am I definitely doing it wrong?

Thx

**Comment by mxcl** [comment]
Never seen this before. The error doesn’t look like our fault though. It's a link error not a compile error FYI.

A cursory google suggests some work arounds based on how you write your code:

https://www.google.com/search?client=safari&rls=en&q=Global+is+external,+but+doesn't+have+external+or+weak+linkage!&ie=UTF-8&oe=UTF-8

**Comment by Vaseltior** [comment]
Can't you reproduce, I was on google all day long with this search query

**Comment by mxcl** [comment]
OK, I'll construct an test project and try to reproduce, however you owe me a beer. This is my free time.

**Comment by Vaseltior** [comment]
How could I know? :-)

**Comment by mxcl** [comment]
You didn't even try to provide me with a test project or anything, but straight up demanded I try to reproduce and fix your problem. It's rude.

**Comment by Vaseltior** [comment]
Sorry for that! I can do it if you prefer.

**Comment by mxcl** [comment]
Compiles:

The bug is in `swiftc`, I suggest you report the bug to Apple.

```swift
    func getBlogs() -> Promise<[AnyObject]> {
        let (promise, fulfill, reject) = Promise<[AnyObject]>.defer()

        Alamofire.request(NSURLRequest()).response { (_, _, data, error) in
            if error == nil {
                if let xwsse = data as? [String:AnyObject] {

                    if let result = data as? [AnyObject] {
                        fulfill(result)
                    }
                }

            } else {
                reject(error!)
            }
        }

        return promise
    }
```

**Comment by Vaseltior** [comment]
Thx for your time, it was nice from you ta have a look.

**Comment by mxcl** [comment]
The Promise constructor in general compiles, but seemingly for this arrangement of code, swiftc crashes.

I can confirm that it works in general because the test suite passes and that constructor is heavily used.

**Comment by Vaseltior** [comment]
You're great! I owe you one pack of beer

**Comment by camapblue** [comment]
I got the same problem with Vaseltior, it's not from XCode I sure. The root cause is from Alamofire.request(...) => it's return an Alamofire.Request() object, not Void (although you don't call return, it's automatically revoke in a closure with single-expression. 
You can fix it by: 
func getBlogs() -> Promise<[AnyObject]> {
    return Promise{ fulfill, reject in
        Alamofire.request(Router.GetBlogs(query: "")).response { (_, _, data, error) in
            if error == nil {
                if let xwsse = data as? [String:AnyObject] {
                    Swell.debug { data!.description }

                    if let result = data as? [AnyObject] {
                        fulfill(result)
                    }
                }

            } else {
                reject(error!)
            }
        }
        return
    }
}
The code isn't nice anymore but it works for me. :D

**Comment by mxcl** [comment]
No doubt Swift 2 has this fixed.
