### ISSUE TITLE
What's a good way to identify the promise that should have handled an error?

### ISSUE THREAD

**Issue by eytanbiala** [mxcl/PromiseKit#189]
Thanks again for working on this library, it really is very useful.

Sometimes during development I will notice there is an unhandled error caught by PromiseKit which means some part of my code is not correctly catching the error.

Is there a good way to debug which promise threw the error?
The only way I have done it so far is to look at the error and try to trace back to the possible sources of the error.

**Comment by mxcl** [comment]
Well, the error domain should be a good clue. There is no sure-fire way to know though.

If it happens a lot it suggests you need to combine more chains so they end in a sensible terminating catch handler. Sensible in that: it's a good spot to show the user the error.

in my code most of my promises will be returned where I make them. Then the caller is responsible for adding a catch. If I find the chain does not end where I want a catch I reconsider the chain.

**Comment by eytanbiala** [comment]
Sure, thanks for the advice.

**Comment by eytanbiala** [comment]
I found my issue - in some parts of the code a promise is returned, but I am not attaching then or catch handlers to that promise.
I am thinking to add catch handlers to any calling code where a promise is returned, but it seems like it should not be necessary to do that. Do you have any suggestions?

**Comment by mxcl** [comment]
If you don't need a catch handler, don't add one. I wouldn't write code simply to suppress the unhandled error handler. It's just an informational message.

**Comment by eytanbiala** [comment]
I suppose it depends on your use case for promises. I am using it extensively now, so if I need to debug an unhandled promise later on it will be difficult since so many are not handled.

**Comment by mxcl** [comment]
Well, if they are clouding the output then add an empty handler. Or perhaps an extension:

```objc
@interface PMKPromise (NomNom)
- (void)failSilently {
    self.catch(^{});
}
@end
```

Though I advise caution, it seems a code-smell to me: that so many errors go unhandled, though obviously every situation is different.

**Comment by eytanbiala** [comment]
I agree - for most cases this would be a pretty bad practice. In my case it is for network requests that should fail silently so the category is helpful, thanks!
