### ISSUE TITLE
Conflicting types for alias 'AnyPromise'

### ISSUE THREAD

**Issue by SilverEnderman** [mxcl/PromiseKit#192]
While attempting to bridge a `Promise<T>` type in a Swift file to `AnyPromise` (for my Objective-C AppDelegate), a compiler error is thrown in the AnyPromise.h file: "`Conflicting types for alias 'AnyPromise'`". As shown in the image below, the compiler blames the `@compatibility_alias AnyPromise PMKPromise;` line.

![screen shot 2015-05-15 at 4 21 27 pm](https://cloud.githubusercontent.com/assets/1500092/7663396/917e3088-fb1e-11e4-8f1f-35f566279beb.png)

Upon further inspection of the debug log, the other declaration of `AnyPromise` appears in my `ProjectName-swift.h` file. The only explanation I can find is that in declaring the helper method, as described [in the current documentation] (http://promisekit.org/PromiseKit-2.0-Released/), Xcode generates an `@class` reference for it.

I'm not entirely sure how this issue could be helped, so any assistance would be very welcome. Thanks for the help.

**Comment by mxcl** [comment]
> declaring the helper method

What helper method exactly?

Could you provide the other line in the code that is the other half of the conflicting type?

**Comment by mxcl** [comment]
Great this is an Xcode bug. I now have a choice between forwards or backwards compatibility.

For now you can get around it by not generating a Swift compat header, you can manually provide the @interface just like PromiseKit does in AnyPromise.h.

**Comment by SilverEnderman** [comment]
Will do. Thanks for the help!

**Comment by SilverEnderman** [comment]
In case it's still relevant, I have a method wrapping a Parse save, which I'm trying to call in my AppDelegate. As mentioned in the ParseKit documentation, a bridge a Promise to AnyPromise is done similar to the generalized example of my current code below:

```swift
@objc func createObjectWithName(name: String) -> AnyPromise {
        return AnyPromise(bound: createObject(name: name))
    }

    func createObject(#name: String) -> Promise<AnyObject> {
        return Promise() { (fulfill, reject) -> Void in
            
            let newObject = PFObject(className: "Object", dictionary: ["name" : name])
            
            newObject.pinInBackgroundWithBlock { (success, error) -> Void in
                
                if error == nil {
                    newTopic.saveEventually { (success, error) -> Void in
                        if error == nil {
                            fulfill(success)
                        } else {
                            reject(error!)
                        }
                    }
                    
                } else {
                    reject(error!)
                }
            }
            
        }
    }
```

**Comment by mxcl** [comment]
Oddly I cannot reproduce. I have a Swift file:

```swift
public class ViewController: UIViewController {
    override public func viewDidLoad() {
        Foo().foo()
    }

    @objc public func foo() -> AnyPromise {
        return AnyPromise(bound: Promise(1))
    }
}
```

Then I call this:

```
@interface Foo : NSObject
@end

@implementation Foo

- (void)foo {
    [[ViewController new] foo];
}

@end
```

My generated `…-Swift.h`:

```objc
// snip…

@class AnyPromise;

SWIFT_CLASS("_TtC6hgsdaf14ViewController")
@interface ViewController : UIViewController
- (AnyPromise * __nonnull)foo;
@end
```

**Comment by mxcl** [comment]
Uploaded for comparison: https://github.com/PromiseKit/testcase

**Comment by mxcl** [comment]
K reproduced.

It depends on #import order. :(

Make sure you import PromiseKit first.

**Comment by mxcl** [comment]
Please re-open if it isn't fixed for you.

I think the only long term solution here will be to remove the `@compatability_alias`, so I'll aim to do this at 2.2. It's there for full source compatibility with PromiseKit 1.x’s `PMKPromise`.

**Comment by SilverEnderman** [comment]
Awesome, import order fixed the issue! Thanks!
