### ISSUE TITLE
promiseAnimation leaks?

### ISSUE THREAD

**Issue by andrei4002** [mxcl/PromiseKit#196]
Hello, I'm trying to convert an example app which uses normal CAAnimation and delegate into something that uses the promiseAnimation from your CALayer category. 

The example can be found [here]
(https://github.com/GabrielMassana/CAKeyframeAnimationExample/blob/master/KeyAnimation/ViewController.m)

What I'm doing is replacing adding the animation to the imageView from there to this:

    [self.animationImageView.layer promiseAnimation:keyframeAnimation forKey:@"girlAnimation"].then(^(NSNumber *done, CAAnimation *anim){

        [self.view bringSubviewToFront:self.button];

        self.animationImageView.image = [UIImage imageNamed:@"frame_016"];
        [self.animationImageView.layer removeAnimationForKey:@"girlAnimation"];  // just in case
    });

Problem is, every time this is ran, the memory allocation literally doubles, as in it's not releasing the previous images. Anything I'm doing wrong here?

**Comment by mxcl** [comment]
PMK 1 or 2? I am assuming 2 with my reproduction test.

**Comment by andrei4002** [comment]
i've actually tried both and got the same result

**Comment by mxcl** [comment]
It’s a one-line patch, so if you can, apply it to your checkout and see if it fixes it. Or I can upload my testcase.

**Comment by mxcl** [comment]
2.0.2 is pushed with the fix.
