### ISSUE TITLE
'finally()' in Objective C and Swift in PromiseKit 2.0

### ISSUE THREAD

**Issue by csotiriou** [mxcl/PromiseKit#197]
Hello,

Is there any difference between Objective C and Swift in the case of finally?

In ObjC, I can very easily do this:
```
[self getJsonFromNetwork].then(^(){
return [self anotherAction]
}).catch(^(NSError *error){
//do things, maybe present an error
}).finally(^(){
//dismiss activity indicator
})
```

but in Swift, when I try to do this:

```
firstly { () -> Promise<AnyObject?> in
	HTTPClient.sharedClient.getJSONP("test1", parameters: nil);
}.then { object -> Promise<AnyObject?> in
	HTTPClient.sharedClient.getJSONP("test2", parameters: nil);
}.catch(policy: CatchPolicy.AllErrors) { (error) in
	HTTPClient.sharedClient.getJSONP("test3", parameters: nil);
}.finally{} ......
```
(getJSONP() makes an asynchronous operation ans returns a Promise<AnyObject?>)

The compiler gives me an error, saying that it 'cannot invoke "finally" with an argument list of type (() -> _)' Although the error is the common Swift compiler BS, I imagine that chaining a 'finally' after a 'catch' cannot be done here, since the 'catch' returns a Void, by definition. This is not the case in ObjC, where AnyPromise's '-catch' returns an 'AnyPromise', thus allowing it to be chained with a '-finally'.

Is there any change in the use of finally() between ObjC and Swift, or I am missing something in terms of syntax? If there is a change, what is the proper chaining methodology in order to have an action run regardless of whether a Promise has been fulfilled or rejected?

**Comment by csotiriou** [comment]
I feel I must answer my own question here:

By testing the following code:

```
firstly { () -> Promise<AnyObject?> in
	println("one");
	return Promise("one");
}.then { object -> Promise<AnyObject?> in
	println("two");
	return HTTPClient.sharedClient.getJSONP("test2", parameters: nil);
}.finally(on: dispatch_get_main_queue()) { () -> Void in
	println("finally called");
}.catch(policy: .AllErrors) { (error) -> Void in
	println(error);
}
```

I get the following output:
```
one
two
finally called
Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo=0x7f8733d86fd0 {NSUnderlyingError=0x7f8733c9e600 "The operation couldn’t be completed. (kCFErrorDomainCFNetwork error -1002.)", NSErrorFailingURLStringKey=test2, NSErrorFailingURLKey=test2, NSLocalizedDescription=unsupported URL}

```

Which means that the 'finally()' which I placed before the 'catch()' was called, even if there was an error in the chain (in this case, there was a, invalid URL passed as parameter). This seems different from the Objective C implementation, but I suppose it's clearer to have just one 'catch()' clause at the end of a chain, handling all errors.

**Comment by mxcl** [comment]
This should not compile:

```swift
firstly { () -> Promise<AnyObject?> in
    HTTPClient.sharedClient.getJSONP("test1", parameters: nil);
}.then { object -> Promise<AnyObject?> in
    HTTPClient.sharedClient.getJSONP("test2", parameters: nil);
}.catch(policy: CatchPolicy.AllErrors) { (error) in
    HTTPClient.sharedClient.getJSONP("test3", parameters: nil);
}.finally{}
```

Because `catch` in swift returns `Void` (for a history of this there is a ticket that describes why we do this).

It compiled?!

**Comment by mxcl** [comment]
I can’t make such code compile:

![screen shot 2015-06-01 at 5 31 31 pm](https://cloud.githubusercontent.com/assets/58962/7926215/185bafb4-0884-11e5-910a-740b64002588.png)

With PromiseKit 2 at least.

**Comment by mxcl** [comment]
K I re-read. Yes you can't add a finally after a catch in Swift anymore.

The ticket justifying this is #175

I understand this is weird, the only option I can see is having catch return a special object that is not a promise but allows a `finally`. But this may only make the situation even more confusing.

**Comment by csotiriou** [comment]
Thanks for answering this. It don't believe it should be considered bug, since this is done by design. 

I just would like to know, if putting a "finally()" before a "catch()" is the proper way of having both a 'catch' and a 'finally' present in a chain, with PromiseKit 2.0, as per my observation in my second post on this thread.

**Comment by mxcl** [comment]
Yes it's the proper way. Swift's catch is terminating in PMK2. Nothing can happen in that branch of the chain after the catch.
