### ISSUE TITLE
Alamofire failing with a strange error

### ISSUE THREAD

**Issue by TYRONEMICHAEL** [mxcl/PromiseKit#198]
Why does this fail with `Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1`:?

     func makeRequest(method: Alamofire.Method, url: String, parameters: [String: AnyObject]? = nil) -> Promise<AnyObject> {
        return Promise { fulfill, reject in
            Alamofire.request(method, url, parameters: parameters)
                .responseJSON{ (request, response, JSON, error) in
                    var statusCode = response?.statusCode
                    
                    if(error != nil) {
                        return reject(error!)
                    }
                    
                    if(statusCode < 200 || statusCode > 299) {
                        return reject(NSError(domain: url, code: statusCode!, userInfo: [:]))
                    }
                    
                    fulfill(JSON!)
            }
        }
    }

And passes with:

    func makeRequest(method: Alamofire.Method, url: String, parameters: [String: AnyObject]? = nil) -> Promise<AnyObject> {
        return Promise { fulfill, reject in
            let request = Alamofire.request(method, url, parameters: parameters)
            request.responseJSON{ (request, response, JSON, error) in
                var statusCode = response?.statusCode
                
                if(error != nil) {
                    return reject(error!)
                }
                
                if(statusCode < 200 || statusCode > 299) {
                    return reject(NSError(domain: url, code: statusCode!, userInfo: [:]))
                }
                
                fulfill(JSON!)
            }
        }
    }

**Comment by mxcl** [comment]
Swift compiler bug. Hopefully the next Xcode will work better.

**Comment by TYRONEMICHAEL** [comment]
Awesome - thanks.

**Comment by cesar-oyarzun-m** [comment]
@TYRONEMICHAEL hey I have the same problem I'm using xcode 6.4, How did you solved this problem???

**Comment by TYRONEMICHAEL** [comment]
Ya exactly. Does that solve your issue?
