### ISSUE TITLE
OMGHTTPURLRQ 2.1.4 seems to have broken PromiseKit

### ISSUE THREAD

**Issue by mcudich** [mxcl/PromiseKit#202]
The reference to OMGHTTPURLRQ.GET in PromiseKit's NSURLConnection extension (NSURLConnection+Promise) is not currently being unwrapped, even though GET returns an optional value.

**Comment by tdansel88** [comment]
+1, PromiseKit should be specifying a OMGHTTPURLRQ version for the podspec.  It's unsafe to assume Swift libraries will maintain backwards compatibility at this point.

**Comment by mxcl** [comment]
My bad I didn't think through the addition of nullable to OMG.

>  It's unsafe to assume Swift libraries will maintain backwards compatibility at this point.

OMG is objc, I guess the semantic versioning here would mandate a bump top the major version for nullability.

The world of pods is kinda messy right now.

Will fix with a quick bump to PMK that forces OMG 2.1.3

**Comment by mxcl** [comment]
K pushing, but it takes 30 minutes for cocoa pods to lint us.

**Comment by mxcl** [comment]
I guess since the objc interface is the same, the minor minor update is acceptable, we just must accept that if you a library incorporating swift and that swift code depends on something you should not allow cocoapods/carthage to update that dependency without vetting.

**Comment by mxcl** [comment]
Live. Let me know if there are any other problems.

**Comment by pgherveou** [comment]
shouldn't we do the same for the cartfile?
right now its specifying github "mxcl/OMGHTTPURLRQ" >= 2.1.3
but this cause the 3.x to be downloaded by default and this break the NSURLConnection + Promise extension

**Comment by mxcl** [comment]
Carthage cannot see 2.1.4 or 2.1.5. They are deleted.

**Comment by mxcl** [comment]
Carthage users can specify 2.1.3 in their own Cartfiles for now. I will amend this for the next release, but I'm not pushing that for a bit.
