### ISSUE TITLE
Class extension not working in main project

### ISSUE THREAD

**Issue by bruceflowers** [mxcl/PromiseKit#203]
I have an issue using the latest Swift 2.0 branch (“swift-2.0”) inside my project. 

When I try to invoke something like this from my main project:
let p:Promise = NSURLConnection.GET(url:"http://httpbin.org/get")

The compiler gives me this error:
Cannot invoke 'GET' with an argument list of type '(url: String)'

But this method is clearly in the pod's NSURLConnection+Promise.swift file and XCode is giving me code hinting for it.

Any ideas?

**Comment by mxcl** [comment]
Probably a dupe of: #202

Swift is probably giving you the wrong error message.

Will update the swift 2 branch today, though be warned this branch is transitory anyway so you may have further issues in the future. Though if so, I'm always happy to help.

**Comment by bruceflowers** [comment]
Thanks! I'll look for the new change.

**Comment by mxcl** [comment]
K I've had OMGHTTPURLRQ 2.1.4 and 2.1.5 removed from CocoaPods.

In theory you should be able to pod update and get OMG 2.1.3. If that doesn't work you will probably need to delete your Pods directory then remove the CocoaPods cache, then `pod update` again. I don't know how to remove the CocoaPods cache, but I'm sure googling will help.
