### ISSUE TITLE
How to transform a promise's value to something else without triggering it?

### ISSUE THREAD

**Issue by PrideChung** [mxcl/PromiseKit#207]
If you're familiar with ReactiveCocoa, what I want it's something like `RACSignal`'s `map:` method, transform the promise's value to something else only when the promise's value is delivered. One overload of PromiseKit's `then` method  can transform the promise's value but will also trigger the promise. Maybe I should roll my own `map:`  method?

**Comment by mxcl** [comment]
I don't understand what you mean by: trigger.

**Comment by mxcl** [comment]
`then` has no side-effects to the Promise. It is the answer you are asking for I believe.

If trigger means “start” then `then` does not start a promise. The promise is started by whoever created it. Typically promises are started as soon as they are created. Though that is up to the creator.

**Comment by PrideChung** [comment]
You're right, `then` is all I need. By the way, according to your last answer, there's a way to defer a `Promise`'s execution? That would be quite handy, because I want to past a `Promise` between objects as data source, and I don't want to start that `Promise` until it's actually needed.

**Comment by mxcl** [comment]
The only way to defer a promises’ execution is to not create it until you need it.

Technically if you wrote the promise you could defer its execution eg:

```swift
func foo() -> (Promise, NSURLSessionTask) {
    var task: NSURLSessionTask
    return Promise { fulfill, reject
        task = NSURLSession.dataTaskWithRequest(rq) { data, _, error in
            fulfill(data)
        }
    }
}

let (promise, task) = foo()

task.resume()
```

**Comment by PrideChung** [comment]
Thanks, now I'm crystal clear.
