### ISSUE TITLE
How to wrap delegation in Swift

### ISSUE THREAD

**Issue by licx** [mxcl/PromiseKit#209]
Is there a way to wrap delegation in Swift? The documentation only has an Objective-C example and PMKResolver doesn't seem available in Swift.

http://promisekit.org/wrapping-delegation/

**Comment by mxcl** [comment]
There's some good examples in our Categories:

https://github.com/mxcl/PromiseKit/blob/master/Categories/UIKit/UIAlertView%2BPromise.swift

```swift
extension UIAlertView {
    public func promise() -> Promise<Int> {
        let proxy = PMKAlertViewDelegate()
        delegate = proxy
        proxy.retainCycle = proxy
        show()
        return proxy.promise
    }
}

private class PMKAlertViewDelegate: NSObject, UIAlertViewDelegate {
    let (promise, fulfill, reject) = Promise<Int>.defer()
    var retainCycle: NSObject?

    @objc func alertView(alertView: UIAlertView, didDismissWithButtonIndex buttonIndex: Int) {
        fulfill(buttonIndex)
    }
}
```

And yes, the documentation is not yet up-to-date for Swift.

**Comment by licx** [comment]
@mxcl  Thank you very much! That's really helpful.

**Comment by mxcl** [comment]
Don’t forget to nil out the retainCycle!

**Comment by mehmetbaykar** [comment]
Is there any update on new Swift examples for migration from delegates to Promises?

**Comment by mxcl** [comment]
https://github.com/mxcl/PromiseKit/blob/master/Documents/CommonPatterns.md#wrapping-delegate-systems

Please read the docs before forcing me to fetch links for you for free.
