### ISSUE TITLE
[Swift2.0] Missing return in a closure expected to return 'AnyPromise'

### ISSUE THREAD

**Issue by katopz** [mxcl/PromiseKit#210]
This is working
```swift
        basicDelegate!.signUp(_PSRegisterData).then { result in
            self.afterSignUpSucceed()
        }
```
This is not and got `Missing return in a closure expected to return 'AnyPromise'`
```swift
        basicDelegate!.signUp(_PSRegisterData).then { result in
            if result {
                self.afterSignUpSucceed()
            } else {
                self.afterSignUpFailed()
            }
        }
```
I think I missing something here, Any hint?

**Comment by mxcl** [comment]
Swift bug. This probably is the solution:

```swift
        basicDelegate!.signUp(_PSRegisterData).then { result -> Void in
            if result {
                self.afterSignUpSucceed()
            } else {
                self.afterSignUpFailed()
            }
        }
```

**Comment by katopz** [comment]
@mxcl Thanks for workaround, working like charm! :D

**Comment by mxcl** [comment]
FFR, this is because Swift was confused about which then to pick (it shouldn't have been). They will fix this or improve the error message, but this category of compile errors will always be around.

**Comment by weien** [comment]
The first question at the FAQ is also relevant: http://promisekit.org/faq/
