### ISSUE TITLE
Consumption/unconsumption based on NSError crashes in Swift2.0

### ISSUE THREAD

**Issue by mallexxx** [mxcl/PromiseKit#212]
Swift is now wrapping an `NSError` object passed to any function to `_NSSwiftNativeNSError`, so associating a promise to the `NSError` object is causing random EXC_BAD_ACCESS crashes as soon as `_NSSwiftNativeNSError` object is autoreleased.
So, basically consume/unconsume methods are receiving temporary `_NSSwiftNativeNSError` object instead of real `NSError`.

I've managed to fix it by eliminating all `NSError` passing to functions and replacing all vars storing Error from `NSError` to `AnyObject` and doing casting only if needed, e.g.:

`if obj is NSError {
  unconsume(obj!)
  resolve(.Rejected(obj!))
}`
instead of
`if let error = obj as? NSError {
  unconsume(error)
  resolve(.Rejected(error))
}`

and 
`(error as! NSError).cancelled` in `rescue(policy policy: RescuePolicy = .AllErrorsExceptCancellation, _ body: (AnyObject) -> Void) -> RejectedPromise`

I can share the updated code if needed, but I think the whole system of consumables (associating objects to NSError) should be redone.

**Comment by mxcl** [comment]
I'll push something that fixes this for beta2 shortly.

Indeed the unhandled error system has to be revised.

I've reported a nserror -> ErrorType conversion bug at radar. So we can assume this stuff is not really ready yet anyway.
