### ISSUE TITLE
EXC_BAD_ACCESS crash in -[PMKPromise dealloc]

### ISSUE THREAD

**Issue by yangmeyer** [mxcl/PromiseKit#213]
I am porting some spaghetti (synchronous methods with completion blocks, wrapped in NSOperations, managed by an NSOperationQueue…) to PromiseKit. The code now looks _much_ nicer… but it’s crashing at some semi-random point at runtime in `-[PMKPromise dealloc]` with a EXC_BAD_ACCESS while trying to `dispatch_release(_promiseQueue);`

![promisekit crash in dealloc](https://cloud.githubusercontent.com/assets/323386/8427452/c9f5efec-1f17-11e5-8710-72c00b888410.png)

Here is the code:

    // YMAssetsViewController.m
    - (PMKPromise *)pullRemoteChanges
    {
    	return [PMKPromise promiseWithResolver:^(PMKResolver resolve) {
    		[self updateStatus:@"Checking for remote changes…"];
    		resolve(self.repository);
    	}]
    	.thenInBackground(^(YMGitRepository *repo){
    		return [repo fetch]; // crashes...
    	})
    	.then(^(YMGitRepository *repo) {
    		[self updateStatus:@"Pulling remote changes…"];
    		return repo;
    	})
    	.thenInBackground(^(YMGitRepository *repo){
    		return [repo pullWithConflictHandler:nil]; // crashes...
    	})
    	.catch(^(NSError *error) {
                // ...
    	});
    }

    // YMGitRepository+Promises.m
    - (PMKPromise *)fetch
    {
    	return [[YMGitFetchPromise alloc] initWithRepository:self];
    }

    // YMGitFetchPromise.m
    - (instancetype)initWithRepository:(YMGitRepository *)repository
    {
    	NSParameterAssert(repository);
    	self = [[super class] new:^(PMKFulfiller fulfill, PMKRejecter reject) {
    		NSError *error;
    		if ([repository fetchWithError:&error]) {
    			fulfill(repository);
    		} else {
    			reject(error);
    		}
    	}];
    	return self;
    }

Any idea what is going on here?

(I’m using PromiseKit 1.5, cause I couldn't get the module-based PromiseKit 2.0 to be friends with my build setup…)

**Comment by mxcl** [comment]
Hey, seems bad.

I think the problem is certainly related to `OS_OBJECT_USE_OBJ` being `0`, this is pretty unconventional and so probably is not well tested.

Can you detail:
* Your deployment target
* How you are installing PromiseKit
* Xcode version

Can you log out `_promiseQueue` at that line? Can you try commenting out that line, does that fix it? Thanks.

**Comment by yangmeyer** [comment]
Thanks for replying.

- Deployment target is OS X 10.10 (Yosemite).
- I'm installing PromiseKit through CocoaPods (`pod "PromiseKit", "~> 1.5"`).
- Xcode 6.3.2.

    (lldb) po _promiseQueue
    <OS_dispatch_queue: org.promiseKit.Q[0x608000102e20] = { xrefcnt = 0x1, refcnt = 0x1, suspend_cnt = 0x0, locked = 0, target = com.apple.root.default-qos[0x100a0ad80], width = 0x7fff, running = 0x0, barrier = 0 }>

If I comment out the dealloc, the app doesn't crash – but I’m assuming this will leak memory?

**Comment by yangmeyer** [comment]
Googling `OS_OBJECT_USE_OBJC`, I found this: http://stackoverflow.com/questions/26339672/cocoapods-how-to-enable-os-object-use-objc-gcd-queues-as-proper-objc-objects

Apparently Cocoapods uses 10.6 as the default deployment target if I don’t specify otherwise. So I added the platform to my Podfile:

    platform :osx, "10.10"
    
    target :Gemba do
      # ...
      pod "PromiseKit", "~> 1.5"
    end

Still crashes, though.

**Comment by mxcl** [comment]
K I think I understand why `OS_OBJECT_USE_OBJ ` is `0`: http://guides.cocoapods.org/syntax/podspec.html#deployment_target

Our deployment target on OS X is 10.7.

However I don’t understand why the pointer is `nil`. There is no way I can see for a `PMKPromise` to be instantiated without the accompanying `_promiseQueue `.

You’re using ARC right?

**Comment by yangmeyer** [comment]
Yep, using ARC.

Is there a way I can override PromiseKit's deployment target for my project, e.g. in the Podfile or Xcode build settings? (I’d really like to avoid having to fork the repo just to delete those lines…)

**Comment by mxcl** [comment]
It’s possible a fix is to do an `if` check first. The only idea I have currently for the cause here is that ARC is handling the `_promiseQueue` even though it is documented to not when `OS_OBJECT_USE_OBJ` is `0`.

However I am not familiar with if ARC also sets pointers to `nil` when it deallocates. I wouldn't be surprised if:

1) It only does this in debug mode
2) It's nothing to do with ARC

If 2) I'm still stuck.

**Comment by mxcl** [comment]
Regarding your question about being able to stop CocoaPods setting `OS_OBJECT_USE_OBJ`. I think the answer is that you could have a local `PromiseKit.podspec` and use that.

If you don't mind first adding the if guard and compiling a release build and seeing if it crashes I'd appreciate it.

Or if you could provide me with a test case I could try and reproduce.

**Comment by mxcl** [comment]
I'd have tried to reproduce this myself, but I don't have a machine with a working Xcode 6 install currently. Hopefully I will next month.

**Comment by mxcl** [comment]
Here’s your problem:

```objc
- (instancetype)initWithRepository:(YMGitRepository *)repository
{
    NSParameterAssert(repository);
    self = [[super class] new:^(PMKFulfiller fulfill, PMKRejecter reject) {
        NSError *error;
        if ([repository fetchWithError:&error]) {
            fulfill(repository);
        } else {
            reject(error);
        }
    }];
    return self;
}
```

This confuses ARC and it over releases the object. You can’t do this.
