### ISSUE TITLE
CocoaPods PromiseKit Swift2beta installation error

### ISSUE THREAD

**Issue by Avtolic** [mxcl/PromiseKit#215]
I have tried to install PromiseKit swift2.0 version using podfile:

    pod 'PromiseKit', :git => 'https://github.com/mxcl/PromiseKit.git', :branch => 'swift-2.0-beta2'

but received an error:

    [!] Unable to satisfy the following requirements:
    - `OMGHTTPURLRQ (~> 3.0.0)` required by `PromiseKit/Foundation (2.0.6)`

https://cocoapods.org/?q=OMGHTTPURLRQ says that only 2.1.5 version is available.
How it could be fixed? I would like to use swift2.0 version now, not to wait until Swift2.0 will be released.

Thank you for the great lib!

**Comment by Avtolic** [comment]
Not sure it is the best solution (I am new to CocoaPods) but I have fixed this error by explicitly adding OMGHTTPURLRQ git URL to pod file:

    pod 'OMGHTTPURLRQ', :git => 'https://github.com/mxcl/OMGHTTPURLRQ'
    pod 'PromiseKit', :git => 'https://github.com/mxcl/PromiseKit.git', :branch => 'swift-2.0-beta2'

**Comment by mxcl** [comment]
I pushed 3.0.0 to CocoaPods.
