### ISSUE TITLE
v1.5.3 and OMGHTTPURLRQ

### ISSUE THREAD

**Issue by paulwcy** [mxcl/PromiseKit#216]
I'm using v1.5.3 and noticed that OMGHTTPURLRQ was updated to 3.0.0. It's causing compilation issues. Can we fix the dependency to OMGHTTPURLRQ to 2.1.3?

Thanks

**Comment by mxcl** [comment]
Sorry, I meant to do this but got distracted and forgot.

**Comment by rizhang** [comment]
I just added to my PodFile as a temp fix:	
pod 'OMGHTTPURLRQ', '~> 2.1.3'

**Comment by mxcl** [comment]
1.6.0 pushed.

* OMG dev corrected
* Swift support removed (use 2.0 branch)
