### ISSUE TITLE
Not possible to use a PMKPromise from Objective C in Swift?

### ISSUE THREAD

**Issue by tnorman42** [mxcl/PromiseKit#217]
This could be incorrect syntax on my part, but I'm unable to use a PMKPromise that was created in Objective C code in my Swift code.

Objective C code:

    @interface FooTest : NSObject
    + (PMKPromise *)promise;
    @end

Swift code (I've tried a number of variations, none of which work. This one is closest to the example given at http://promisekit.org/PromiseKit-2.0-Released/):

    FooTest.promise().then { (obj: AnyObject?) in
        self.obj = obj
    }

Compiler error: Cannot invoke 'then' with an argument list of type '((AnyObject?) -> _)'

This doesn't work either:

    FooTest.promise().then { (obj: AnyObject?) -> AnyPromise in
        return AnyPromise()
    }

Similar error: "Cannot invoke 'then' with an argument list of type '((AnyObject?) -> AnyPromise)'"

SO question here: http://stackoverflow.com/questions/31232627/bridging-from-objective-c-to-swift-with-promisekit

**Comment by mxcl** [comment]
Yes, you can't use them directly like this. You have to return the AnyPromise from a swift `then` handler. 

```
NSURLConnection.POST(url, multipartFormData: formData).then {
    return SCNetworkReachability()
}.then { (obj: AnyObject?) in
    // AnyPromise always resolves with `AnyObject?`
}
```

**Comment by mxcl** [comment]
I'll write more here later. There should be something else added to the API.

**Comment by mxcl** [comment]
See referenced commit, I added a `then` for your use-case.

**Comment by mxcl** [comment]
2.1.0 is pushed which allows your example:

```swift
FooTest.promise().then { (obj: AnyObject?) in
    self.obj = obj
}
```

Though you may need to provide the return type for it to compile with Swift 1.2 (compiler bug):

```swift
FooTest.promise().then { (obj: AnyObject?) -> Void in
    self.obj = obj
}
```

This is probably enough:

```swift
FooTest.promise().then { obj -> Void in
    self.obj = obj
}
```
