### ISSUE TITLE
Catch handler not invoked

### ISSUE THREAD

**Issue by peres** [mxcl/PromiseKit#218]
I've got this code (simplified):

	return [PMKPromise promiseWithResolverBlock:^(PMKResolver resolve) {
		resolve([NSError cancelledError]);
	}].catch(^(NSError *error) {
		NSLog(@"I expected this to be printed");
	});

I expected the catch handler to run, since the promise resolves with NSError, but that doesn't happen. I have been using PromiseKit a bit and I thought I understood it more or less: what am I doing wrong?

**Comment by mxcl** [comment]
tl;dr: use anything *EXCEPT* `cancelledError` and the catch handler will be called.

You chose to use `cancelledError` so probably you should understand what that means.

Documented here: http://promisekit.org/PromiseKit-2.0-Released/

Question: why did you use `cancelledError`?

**Comment by peres** [comment]
Thank you. The actual code shows a UIAlertController in the first promise, and cancelledError is used to handle cancellation. I had looked at the documentation before, and was tricked by the swift example which handles that case in its catch branch. Next time I will read the text between the samples in the docs before wasting your time :P

**Comment by mxcl** [comment]
np, I appreciate these tickets as I worry about the whole cancellation thing catching people out and need to be aware of how to document these things so people can use the library effectively.
