### ISSUE TITLE
Promise that only invokes its body only when `.then` is called?

### ISSUE THREAD

**Issue by ldiqual** [mxcl/PromiseKit#219]
Hey there,

I'd like to do something like this:

```
let promise1 = Promise<Void> { resolve, reject in
    performAsyncCall1(resolve, reject)
}

let promise2 = Promise<Void> { resolve, reject in
    performAsyncCall2(resolve, reject)
}

promise1.then {
    return promise2
}.then {
    // Profit
}
```

and I want `promise1` and `promise2` to only seal when `.then` is called, in order to be a bit clearer on what the chaining is, or potentially pick only a few promises to execute.

I see that the default `init` invokes its body right away, which prevents me from creating promises while expecting them to only execute when `.then` is called.

Is there a common practice to achieve what I want?

**Comment by mxcl** [comment]
The common practice here would be to make `promise2` a function and then call it and return it in the `then`.

**Comment by ldiqual** [comment]
Cool, thanks Max!

**Comment by mxcl** [comment]
So:

```swift
func foo() {
    let promise1 = Promise<Void> { resolve, reject in
        performAsyncCall1(resolve, reject)
    }

    func promise2() -> Promise<Void>
        return Promise { resolve, reject in
            performAsyncCall2(resolve, reject)
        }
    }

    promise1.then {
        return promise2()
    }.then {
        // Profit
    }
}
```

However I think it’s notable that if your promise2 is that simple then you can just do this:

```swift
let promise1 = Promise<Void> { resolve, reject in
    performAsyncCall1(resolve, reject)
}

promise1.then {
    return Promise { performAsyncCall2($0.resolve) }
}.then {
    // Profit
}
```
