### ISSUE TITLE
Support Xcode 7 beta 3

### ISSUE THREAD

**Issue by mcudich** [mxcl/PromiseKit#221]
There are a few issues with the current Swift 2.0 branch. I've supplied a set of fixes in this pull request: https://github.com/mxcl/PromiseKit/pull/220. Thanks in advance!

**Comment by mxcl** [comment]
I have updates for this locally. I'd pull your PR anyway as it is ready now, however I notice you remove `import PromiseKit` from all the categories and like: I can't merge that.

**Comment by mcudich** [comment]
The reason I pulled out those imports is that Xcode was complaining about importing a module while it's being compiled (this is perhaps a new beta 3 requirement?). I got this compilation error by importing PromiseKit as a pod - do you not see the same error if you do so?

**Comment by mxcl** [comment]
K I understand, and makes sense, I'm surprised it has worked this long. I can fix with:

```swift
#if !COCOAPODS
import PromiseKit
#endif
```

The imports are required for Carthage or with the pre-built frameworks.

**Comment by mcudich** [comment]
Right on - that makes sense. Thanks!
