### ISSUE TITLE
chaining promises

### ISSUE THREAD

**Issue by pgherveou** [mxcl/PromiseKit#223]
Hello Max,
I run into this problem yesterday 
I wrote this code to chain a few promises based on some conditions

```swift
var promise = Promise(0).asVoid()

if (condition1) {
  promise = promise.then { return otherPromise() }      
}

if (condition2) {
  promise = promise.then { return otherPromise() }
}

if (condition3) {
  promise = promise.then { return otherPromise() }
}

// finally
promise.then { () -> Void in
  println("all done")
}
```

For some reason it was not working and I refactored it into this which works as expected

```swift
firstly {
  return condition1
    ? return Promise(0).asVoid()
    : return otherPromise()
}.then {
  return condition2
    ? return Promise(0).asVoid()
    : return otherPromise()  
}.then {
  return condition3
    ? return Promise(0).asVoid()
    : return otherPromise()  
}.then {
   println("all done")
}
```

Do you see any reason why the first snippet of code is not working? Let me know if its sounds like a bug I could add a test case to make sure things works as expected

**Comment by mxcl** [comment]
First example is fine. What didn't work?

**Comment by pgherveou** [comment]
Yes thats what I thought too, but It didn't go through all the promises even though the condition flags where set to true,  instead it when straight to the last one

**Comment by mxcl** [comment]
I have tests that prove what you have written works. Can you provide a test case that demonstrates it not working?

**Comment by mxcl** [comment]
I made this test case:

https://github.com/mxcl/TestCase-223

Here's the example output:

![screen shot 2015-07-18 at 12 30 09 pm](https://cloud.githubusercontent.com/assets/58962/8762503/c7ea8fc0-2d48-11e5-89b7-d16d7d75a402.png)

The test case was made with Xcode 7, but could be adapted to Xcode 6.

**Comment by pgherveou** [comment]
Thks Max i will try to reproduce the test case and see why it was not working for me

**Comment by pgherveou** [comment]
THks for the test case, Couldnt reproduce the bug, closing for now I let you know if I find anything

**Comment by mxcl** [comment]
It may have been you forgot to return in a `then`, for a `Void` promise returning nothing would fulfill one variant of `then`, and in that case the Promise would not chain.
