### ISSUE TITLE
Swift-2.0 branch gone?

### ISSUE THREAD

**Issue by bruceflowers** [mxcl/PromiseKit#226]
We were pinning to the "swift-2.0' branch, specifically commit 550b5690e28cfcb7ce78ef5ae2a7e6cd046fcbe0, which seems to have been deleted.  Pod install complains that the commit doesn't exist at all.

The reason for pinning here is that we're not ready to upgrade to Xcode beta 3 or 4 yet, as we have a lot of swift 2 dependencies in our project which are in active development and it's fragile. So the best approach for now is to freeze all the dependencies at a point where they all work together.

Can someone suggest how to locate this commit?

**Comment by katopz** [comment]
@bruceflowers  Same situations and here's workaround.

![screen shot 2558-07-30 at 23 53 54](https://cloud.githubusercontent.com/assets/97060/8989417/4c74031c-3716-11e5-9125-500dbb36e0ab.png)

Just fork and checkout before beta3 commit and you're good to go. which is https://github.com/katopz/PromiseKit/commit/f9896a86d1d662c6a58d793ade5b421914df293d
or temporary point to here https://github.com/katopz/PromiseKit/tree/xcode7-beta2

PS : I promise I won't delete/rebase it tho ;)

**Comment by mxcl** [comment]
Apologies. I never made any promises to keep those branches but I would have kept them if I'd known you were using them.

I'm a neat freak about branches.

I'll keep all current branches until 2.0 is released properly.

I'll try to push that commit again. Specifically which beta was it for?

**Comment by mxcl** [comment]
Restored as https://github.com/mxcl/PromiseKit/tree/swift-2.0-beta2

**Comment by bruceflowers** [comment]
@mxcl @katopz  I looked away from this repo for a day and just saw this - thanks to both of you for your help!
