### ISSUE TITLE
what's the best way to have a timeout in the promise?

### ISSUE THREAD

**Issue by hariseldon78** [mxcl/PromiseKit#227]
Hello. I would like to add a timeout to some promises that make them to "reject" if waiting for some conditions takes too long. Is there any "suggested" or "standard" way to do this? 

is something like this correct: 
```
let p=Promise<Void>(resolvers:
{
    (fulfill, reject) -> Void in
    NSOperationQueue().addOperationWithBlock({
        () -> Void in
        NSThread.sleepForTimeInterval(10)
        NSOperationQueue().mainQueue().addOperationWithBlock({
            () -> Void in
            reject(NSError(... TIMEOUT MESSAGE ...))
        })
    })
    var finished = false

    NSOperationQueue().addOperationWithBlock({
        () -> Void in
        while true {
            NSOperationQueue().mainQueue().addOperationWithBlock({
                () -> Void in
                if condition {
                    finished = true
                    fulfill()
                }
            })
            if finished {
                break
            }
        }
    })
}
```

and, if it's correct, it's still awful; is there a better way?

**Comment by mxcl** [comment]
There is no standard way to do this, (though it would be a welcome addition). I suggest:

```swift
let p = Promise<Void> { fulfill, reject in

    after(10).then {
        reject(NSError(…))
    }

    async {

        // do stuff
    
        if condition {
            fulfill()
        }
    }
}
```

It is safe to call `reject` or `fulfill` after the promise is already resolved, it is a `noop`.

However if you want to avoid some work, then you can ask the promise if it is resolved:

```swift
var promise: Promise<Void>!
promise = Promise<Void> { fulfill, reject in

    after(10).then {
        reject(NSError(…))
    }

    async {

        while promise.pending {
            // do stuff
        }
    
        if condition {
            fulfill()
        }
    }
}
```

You don’t need to switch back to the main queue with Promises. See http://promisekit.org/dispatch-queues/

**Comment by fastboatster** [comment]
This doesn't seem to work with PromiseKit 6 because `after` now returns a `Guarantee` instead of `Promise`. What do I need to change to make this code work with PK6?
I'm doing this:
```
return Promise { seal in
            // automatic rejection after the timeout?
            after(seconds: MyTimeoutInterval)
                .then { Guarantee { $0(TimeoutError) }
            }
            self.doLongOperation() { success, error in
               seal.resolve(success, error)
           }
        }
```
If I do
```
after(seconds: MyTimeoutInterval)
                .then { seal.reject(TimeoutError) }
```
it first complains that `Contextual type for closure argument list expects 1 argument, which cannot be implicitly ignored` and suggests to insert `_ in` before `seal.reject`. However, it brings up another error:
`Cannot convert value of type '(_) -> ()' to expected argument type '(Void) -> Guarantee<_>'`

**Comment by mxcl** [comment]
```swift
let p = Promise<Void> { seal in

    after(.seconds(10)).done {
		seal.reject(MyError)
    }

    someAsyncFunctionWithCompletionHandler {

        // do stuff

        if condition {
            seal.fulfill()
        }
    }
}
```

**Comment by fastboatster** [comment]
Whoa, that was fast! Will try this now.

**Comment by mxcl** [comment]
Glad to hear 👍🏻

If you found my work helpful, please consider [supporting its development](https://patreon.com/mxcl).

**Comment by jlew-nevo** [comment]
I have a similar situation.  In PK4, I would `race(promise,timeout)` but now that `timeout` is a Guarantee, the generic parameter on `race` will not work out.  Any opinion on this as a solution:
```
extension Promise {
    func timeout(seconds: TimeInterval, timeoutError: Error) -> Promise<T> {
        return Promise<T> { seal in
            after(seconds: seconds).done {
                seal.reject(timeoutError)
            }
            self.done { result in
                seal.fulfill(result)
                }.catch { err in
                    seal.reject(err)
            }
        }
    }
}
```
I assume it's safe (no-op) to resolve a seal more than once.

**Comment by jlew-nevo** [comment]
Thanks, ended up doing something similar.  In 6.8.x, this is triggering the new "PromiseKit: warning: pending guarantee deallocated" on the `after` guarantee.  Not sure why exactly.  I will update if I find the cause.

**Comment by mxcl** [comment]
If you have an issue please open a new ticket.
