### ISSUE TITLE
Can't use "@class AnyPromise" because of compiler error

### ISSUE THREAD

**Issue by alexvimpekable** [mxcl/PromiseKit#228]
Hello,

If I place `@class AnyPromise;` to any of my Objective-C headers instead of `#import <PromiseKit/PromiseKit.h>` Xcode fails to compile with error: `Reference to 'AnyPromise' is ambiguous`, pointing both to `@compatibility_alias AnyPromise PMKPromise;` at Umbrella.h line 68 and mine `@class AnyPromise;` line as candidates. What's going on and is any way to fix it?

Thanks,
Alex

**Comment by mxcl** [comment]
Indeed. There is no AnyPromise class due to backwards compatibility with PromiseKit 1.x.

I've deprecated this for PromiseKit 3.

Instead you can do:

```objc
@class PMKPromise;
@compatibility_alias AnyPromise PMKPromise;
```

**Comment by alexvimpekable** [comment]
Got it! Thanks!
