### ISSUE TITLE
Multiple promises in 'when' and error 

### ISSUE THREAD

**Issue by ivanovvitaly** [mxcl/PromiseKit#229]
Hello,

I'm using 'when' function with 3 promises. When one of the promises fails the success code is not run. As I understood from the documentation this is expected behavior.

```objc
when(api.getUser(self.ticket.requesterId),
    api.getUser(self.ticket.assigneeId),
    api.listComments(self.ticket.id)).then { requester, assignee, comments -> () in
        // success code
    }
    .finally {
        // finally code
    }
```

Is it possible to let success code run, but receive nil for the failed argument? For instance if assignee promise failed I receive tuple like (request, nil, comments)

Please advice how to better solve this

Thanks!

**Comment by mxcl** [comment]
From docs:

> if any promise fails, the next catch is called.

**Comment by ivanovvitaly** [comment]
Right, but is any promise fails, the success code is not called at all. 
Is is possible to run success code in any case even if any promise fails ? (like in jquery deferred)

**Comment by mxcl** [comment]
No. It is not possible. jQuery promises are widely considered broken.

If you want something to run every time, use `finally`.

If you want a promise to not fail a `when` you must make it not fail:

```swift
let p1 = api.getUser(self.ticket.requesterId)
let p3 = api.listComments(self.ticket.id)

// if the promise fails “recover” it. Note you will need to massage the closure’s return type
let p2 = api.getUser(self.ticket.assigneeId).recover { nil }

when(p1, p2, p3).then { requester, assignee, comments -> () in
    // success code
}.finally {
    // finally code
}
```
