### ISSUE TITLE
Can't chain AnyPromise in Swift when using obj-c Promises

### ISSUE THREAD

**Issue by dbachrach** [mxcl/PromiseKit#231]
Now that #225 is fixed, I'm having trouble chaining AnyPromises. I emailed you a full example for you to test, but in summary this is what I have:

```swift
// This does work
MHSDK.sharedSDK().configureWithClientId("__", clientSecret: "__").then { _ -> Void in
    MHObject.fetchByMhid("__").then { obj in
        println("Unchained: \(obj)")
    }
}

// This does not work
MHSDK.sharedSDK().configureWithClientId("__", clientSecret: "__").then { _ -> AnyPromise in
    return MHObject.fetchByMhid("__")
}.then { obj in
    println("Chained: \(obj)")
}
```

The top example does not use chaining, and the println prints out the resolved object. The bottom example uses chaining and prints out a PMKAnyPromise (e.g. `<PMKAnyPromise: 0x7f80794b08d0>`) instead of the value that promise resolves to.

**Comment by mxcl** [comment]
Nuts, I'm on it.

**Comment by mxcl** [comment]
I’m on El Capitan beta 6, thus I cannot load this project in Xcode 6.4. A fix will have to wait on a fix from Apple :(

Certainly, this *should* work, we have tests for it.

What specifically happens?

**Comment by dbachrach** [comment]
So the `then` behavior I expect is that if a return an Int from a then, the promise chain resolves with that Int value. If I return a `PMKAnyPromise` from a `then`, I do not expect the promise chain to resolve with a `PMKAnyPromise`. The chain should continue and resolve with the result of that promise. 

I am not seeing that behavior though. It resolves directly with a `PMKAnyPromise` rather than the value that that promise resolves with.

Does that make any sense?

**Comment by mxcl** [comment]
I see, it seems that Xcode is not seeing the `then` that takes an `AnyPromise`.

This is most likely again due to the Objective-C framework imports Objective-C PromiseKit (which is built on Swift) which is then imported into Swift issue.

**Comment by mxcl** [comment]
A workaround for now would be to then off the AnyPromise and return that.

**Comment by mxcl** [comment]
This wasn't module weirdness, it was missing functions.

I remember now why I didn't add a Swift then to `AnyPromise`, as it required a few others in order to ensure that it handled various cases. Instead I expected users to adapt them into `Promise<T>`s.

So my bad.

**Comment by mxcl** [comment]
I'm pretty sure this is fixed, but I can't run your test project on El Capitan beta 9 and right now I have no other macs to try it on.

Let me know if it isn't.

And very sorry about this.

**Comment by dbachrach** [comment]
Ah gotcha. Hey thanks so much for taking a look and fixing this so quickly. Really appreciate it. I will check this tomorrow morning and let you know if it fixes our bug.

**Comment by mxcl** [comment]
i appreciate you using the library to its full extent 👍🏻

I wrote new tests to verify the behavior, so I presume it is fixed. Hopefully my tests are extensive enough.

**Comment by dbachrach** [comment]
:+1: 2.2.0 fixes the issue and we can now chain our promises. Awesome work!

**Comment by mxcl** [comment]
Great, glad to hear it. 🍺
