### ISSUE TITLE
Swift Syntax question

### ISSUE THREAD

**Issue by ded** [mxcl/PromiseKit#232]
Hi Max,
Thanks for all the hard work you put into this library. I've been a longtime user of [when.js](https://github.com/cujojs/when), which I'm sure you're familiar with and now I'm transitioning into more iOS Swift Development and was looking for something similar.

I've spent a good amount of time reading through most (not all) of your documentation, and even went through the tutorial. All is good :+1: 

I mainly wanted to confirm a few things to verify that I am understanding things correctly.

Take this typical flow in JS using when. All is what you would expect (and how that library works)

``` js
when(thing())
.then(function (value) {
  // lets say value is Number(5)
  return value * 2
})
.then(function (value) {
  console.log(10 === value)
})
.catch(function (err) {
  console.log(err instanceof Error)  
})
.finally(function () {
  console.log('always called')
})

function thing() {
  return when.promise(function (resolve, reject) {
    ajax('/foo', function (err, resp, body) {
      if (!err && resp.statusCode == 200) resolve(body)
      else reject(new Error(err))
    })
  })
}
```

With your library, could I assume the following would be the equivalent? 

``` swift
when(thing())
.then val in -> CGFloat {
  // lets say value is Number(5)
  return val * 2
}
.then val {
  println(10 == val)
}
.catch err {
  // err is NSError
}
.finally {
  println('always called')
}


func thing() -> Promise {
  return Promise { resolve, reject in   
      ajax('/foo', (err: NSError?, resp: AnyObject?, body: String?) in {
        if err == nil && resp?.statusCode == 200 {
          resolve(body)
        } else {
          reject(err)
        }
      }
  }
}
```

Would love to know if I got the syntax right or wrong. Swift-Foo is growing and not as strong as my JavaScript.

**Comment by mxcl** [comment]
Looks good! Some notes:

* `finally` cannot come after `catch` (yes it's unfortunate, but Swift was difficult about it any other way)
* The `when` is unnecessary, but it will work. You can just `then` off of `thing()`. In JS maybe you always use `when` because JS is dynamic and thus `when` will accept anything, not just promises, but Swift is strict, so we decided to be strict and don't provide a `when` that can take anything but promises (ObjC PromiseKit is different, `PMKWhen` can take anything).
* If you are using `when` so you can stylistically `then` on the next line then we provide `firstly`.
* Probably also you will need to specify the Promise’s type:
```
func thing() -> Promise<String> {
  return Promise { resolve, reject in   
      //…
  }
}
```
* Because Swift is a bit flakey, you may need to specify the return type of the final `then` closure.
* If you want promises more like JS then I suggest ObjC since it is dynamic where Swift is strict which is *more* like JS, though obviously ObjC has a lot of quirks.
* Your syntax for Swift closures was a little off.

So I’d write it more like this:

```swift
firstly {
    thing()
}.then { val -> Double in
    Double(val) * 2.0
}.then { val -> Void in
    println(10 == val)
}.finally {
    println('always called')
}.catch { err in
    // err is NSError
}


func thing() -> Promise<String> {
    return Promise { resolve, reject in   
        ajax("/foo", (err: NSError?, resp: AnyObject?, body: String?) in {
            if err == nil && resp?.statusCode == 200 {
                resolve(body)
            } else {
                reject(err)
            }
        }
    }
}
```

**Comment by mxcl** [comment]
If you do use Swift PromiseKit beware the incoming Xcode 7, we’re having to rename `catch`.

**Comment by ded** [comment]
Awesome! Some responses
- `finally` cannot come after `catch` (yes it's unfortunate, but Swift was difficult about it any other way)

Ok good to know! I will keep that in mind.

- The `when` is unnecessary, but it will work.
Right. I forgot about that for a quick sec. The same is true for `when.js` (I don't know why I added the extra `when`). The good part about the `when()` wrap is that would at least wrap a known value, and then "Promisy" it.

- Your syntax for Swift closures was a little off.... So I’d write it more like this:

Thank you! This was exactly what I was looking for! I'll leave a lil something in the tip jar :+1: 
Will definitely be moving forward with this in my future iOS projects.

**Comment by cesar-oyarzun-m** [comment]
@mxcl Hi I'm trying to create a promise and then save the function fulfill and reject into in array or dictionary . I don't know if this is possible to do I get some compiler erros. I know you can store functions inside array but I think since is inside the promise I need to do something else, here is my code 
 
        let requestPromise = Promise<Bool> { fulfill, reject in
            self.socket.emit(message,dic)
            let dicFunc = [ "fulfill": fulfill, "reject":reject]
        }
I get error
Type of expression is ambiguous without more context
 '_' is not convertible to '(NSError) -> Void'

**Comment by cesar-oyarzun-m** [comment]
I was able to save the fulfill but when I add the reject I get error

       var request = Dictionary<String,Any>()
       let requestPromise = Promise<Any> { fulfill, reject in
           self.socket.emit(message,dic)
           var resolved = Dictionary<String,Any -> Void>()
           resolved  = [ "fulfill": fulfill,"reject":reject]
           self.request.updateValue(resolved, forKey: uuid)
       }
Cannot assign a value of type '[String : (NSError) -> Void]' to a value of type 'Dictionary<String, Any -> Void>' I think must be because of the type

**Comment by mxcl** [comment]
`reject` and `fulfill` have different signatures, so you need:

     var resolved = Dictionary<String, Any>()

**Comment by cesar-oyarzun-m** [comment]
thanks that will work to save it in the same Dictionary, but the problem is when I take it out of there and call the function, do I need to cast.

                    var dictionary:Dictionary<String,Any> = self.request[id] as! Dictionary
                    if((error?.isEmpty) == nil){
                        let fun = dictionary["fulfill"]
                        fun(true)
                    }else{
                        let rej = dictionary["reject"]
                        rej(NSError())
                    }

**Comment by cesar-oyarzun-m** [comment]
I think this will work 
                    
                   if((error?.isEmpty) == nil){
                        let fun = dictionary["fulfill"] as! Any -> Void
                        fun(true)
                    }else{
                        let rej = dictionary["reject"] as! Any -> Void
                        rej(NSError())
                    }
thanks for the help! @mxcl

**Comment by mxcl** [comment]
You may prefer to use `defer`, Swift doesn't much like dictionaries and `Any` in these contexts:

```swift
let (promise, fulfill, reject) = Promise<Any>.defer()
socket.emit(message, dic)
request.updateValue((fulfill, reject), forKey: uuid)
return promise
```

Also, please beware, Swift 2 is coming, and the name of `defer` has to change.

**Comment by cesar-oyarzun-m** [comment]
Thanks @mxcl I will make that change, but how will be the syntax to take it out from the dictionary I have this 

     var dictionary:Dictionary<String,Any> = self.request[id] as! Dictionary
     let fun = dictionary["fulfill"] as! Any -> Void

but I think I will need something else I get cast error, How do I get out from the dictionary? also updateValue is a method from Dictionary
