### ISSUE TITLE
Allow access to the header fields in the response when using NSURLConnection.promise

### ISSUE THREAD

**Issue by paultsui** [mxcl/PromiseKit#234]
A possibility is to make [fetch](https://github.com/mxcl/PromiseKit/blob/2ff12d7c2c0491879b5c6b86e88127c330e29a1d/Categories/Foundation/NSURLConnection%2BPromise.swift#L174) an extension of NSURLConnection public, and one can then read the header fields from [rsp (NSURLResposne)](https://github.com/mxcl/PromiseKit/blob/2ff12d7c2c0491879b5c6b86e88127c330e29a1d/Categories/Foundation/NSURLConnection%2BPromise.swift#L182).

**Comment by mxcl** [comment]
Thanks for the suggestion, indeed, was missing.

**Comment by paultsui** [comment]
Thanks for the quick response! : )

**Comment by mxcl** [comment]
Always 👍🏻
