### ISSUE TITLE
PMKHTTPURLResponseIsJSON doesn't support application/x-javascript

### ISSUE THREAD

**Issue by jefferythomas** [mxcl/PromiseKit#235]
I'm an sample application for a talk I'm doing. I'm using the Duck Duck Go API which returns a content type of application/x-javascript for it's JSON.

It would be nice to set the array of MIME types programmatically instead of it being hardcoded.

**Comment by mxcl** [comment]
Seems to me Duck Duck Go should be passing `application/json` when they are not return JSON-P.

**Comment by mxcl** [comment]
The fix will be in 2.2.2 which should be released later today.

**Comment by jefferythomas** [comment]
Thanks for the quick turnaround. I also added in some code which could solve the problem in a more generic way.
