### ISSUE TITLE
Unable to build for Xcode 7 beta 5 using Carthage

### ISSUE THREAD

**Issue by marlowcharite** [mxcl/PromiseKit#237]
Hey all, looking for a bit of guidance here. I'm able to retrieve this library using cocoapods by pointing to the branch `swift-2.0-beta5` but am completely unable to build through carthage using `github "mxcl/PromiseKit" "swift-2.0-beta5"`. 

EDIT: 

I continuously get the same error.

>The following build commands failed:
	Check dependencies
(1 failure)
warning: Capabilities that require entitlements from "Tests/Entitlements.plist" may not function in the Simulator because no provisioning profiles with a valid signing identity (i.e. certificate and private key pair) matching the bundle identifier “org.promisekit.PMKiOSUITestsHost” were found.
Code Sign error: No matching provisioning profiles found: No provisioning profiles with a valid signing identity (i.e. certificate and private key pair) matching the bundle identifier “org.promisekit.PMKiOSUITestsHost” were found.
CodeSign error: code signing is required for product type 'Application' in SDK 'iOS 9.0'
CodeSign error: code signing is required for product type 'Application' in SDK 'iOS 9.0'
A shell task failed with exit code 65:
** BUILD FAILED **

>The following build commands failed:
	Check dependencies
(1 failure)

**Comment by mxcl** [comment]
#worksforme

```sh
~$ sudo xcode-select --switch /Applications/Xcode-beta.app/
~$ mkdir tmp && cd tmp
~/tmp$ carthage update
*** Fetching PromiseKit
*** Fetching OMGHTTPURLRQ
*** Checking out OMGHTTPURLRQ at "3.0.0"
*** Checking out PromiseKit at "39495e0212792d3cc158b3bca92ddcc417679f55"
*** xcodebuild output can be found in /var/folders/9p/55y6r8hs3yz2qkhvf74gc0gh0000gn/T/carthage-xcodebuild.hikZiR.log
*** Building scheme "OMGiOS" in OMGHTTPURLRQ.xcodeproj
*** Building scheme "OMGOSX" in OMGHTTPURLRQ.xcodeproj
*** Building scheme "PMKiOS" in PromiseKit.xcodeproj
*** Building scheme "PMKOSX" in PromiseKit.xcodeproj
warning: All interface orientations must be supported unless the app requires full screen.
warning: A launch storyboard or xib must be provided unless the app requires full screen.
~/tmp$ ls Carthage/*/*/*.framework
Carthage/Build/iOS/PromiseKit.framework
Carthage/Build/Mac/PromiseKit.framework
~/tmp$ cat Cartfile
github "mxcl/PromiseKit" "swift-2.0-beta5"
```

**Comment by mxcl** [comment]
Can you build anything else with Carthage?

Have you set your xcode-select to use Xcode-beta.app rather than Xcode.app?

**Comment by marlowcharite** [comment]
Hmmmmm interesting @mxcl. I can now build. I looked through my past commands and don't know what the problem could've been. I'm going to chalk it up to hazards of coding late. Thanks for the response @mxcl, Love the library!

**Comment by mxcl** [comment]
In fact, I've had similar temperamental problems building with xcodebuild.
