### ISSUE TITLE
Feature request: Core Bluetooth

### ISSUE THREAD

**Issue by gerchicov-bp** [mxcl/PromiseKit#238]
When you work with pure CoreBluetooth it means you need to use a chain or even a tree of delegate methods` asynchronous calls.
Could you wrap this code in your library's style?

**Comment by mxcl** [comment]
Probably. I have no experience with Core Bluetooth, but I could probably whip something up.

Can you provide a list of the classes and methods you need?

**Comment by mxcl** [comment]
#worksforme

```sh
~/tmp$ carthage update
*** Fetching PromiseKit
*** Fetching OMGHTTPURLRQ
*** Checking out OMGHTTPURLRQ at "3.0.0"
*** Checking out PromiseKit at "39495e0212792d3cc158b3bca92ddcc417679f55"
*** xcodebuild output can be found in /var/folders/9p/55y6r8hs3yz2qkhvf74gc0gh0000gn/T/carthage-xcodebuild.hikZiR.log
*** Building scheme "OMGiOS" in OMGHTTPURLRQ.xcodeproj
*** Building scheme "OMGOSX" in OMGHTTPURLRQ.xcodeproj
*** Building scheme "PMKiOS" in PromiseKit.xcodeproj
*** Building scheme "PMKOSX" in PromiseKit.xcodeproj
warning: All interface orientations must be supported unless the app requires full screen.
warning: A launch storyboard or xib must be provided unless the app requires full screen.
~/tmp$ ls Carthage/*/*/*.framework
Carthage/Build/iOS/PromiseKit.framework
Carthage/Build/Mac/PromiseKit.framework
~/tmp$ cat Cartfile
github "mxcl/PromiseKit" "swift-2.0-beta5"
```

**Comment by mxcl** [comment]
Can you build anything else with Carthage?

Have you set your `xcode-select` to use Xcode-beta.app rather than Xcode.app?

**Comment by gerchicov-bp** [comment]
I worked with bluetooth beacons. I meaned a code to find peripherals and get their characteristics. Here is an example of the tutorial:
https://www.invasivecode.com/weblog/core-bluetooth-for-ios-6-core-bluetooth-was/
Sorry but I don't have a code now and I also don't have any bluetooth device to rewrite it again. But the main idea is:
1)to look for a device
2)to try to connect to the discovered one
3)to "discover services" of the connected one
4)to "discover characteristics" for the discovered service
5)to read characteristic's values
And there is error handling somewhere here.

Each action from the listed above is a separate delegate method which is called asynchronously and may be called multiple times for the same device. I think it could be better to link all these methods into one "promise sequence".
But anyways you need at least a BLE device. I recommend you a beacon for 2 reasons:
- it is enough cheap
- specifically for beacons apple added iBeacon library which you can also use to check the result.

**Comment by foobar8675** [comment]
@gerchicov-bp you can also look bluetoothkit. doesn't take u all the way there, but might be helpful, if you only have 1 char on ur services

**Comment by mxcl** [comment]
Merged
