### ISSUE TITLE
Reloading tableview in Promisekit's then

### ISSUE THREAD

**Issue by vskr** [mxcl/PromiseKit#242]
I am trying to make async. request using Promisekit's promises. I have the following code in a subclass of UITableViewController, to reload tableview with data that is fetched from async. request.

     my_promise.then { asynly_fetched_data in 
        self.data = asyncly_fetched_data
        self.tableView.reloadData()
    } 
However, the following statement is causing the following build error.

Offending statement:       
        
    self.tableView.reloadData()

 
    Missing return in a closure expected to return 'AnyPromise' 

However, following code with ensure (I think finally is renamed to ensure in swift2 version of PromiseKit) works

     my_promise.then { asynly_fetched_data in 
        self.data = asyncly_fetched_data
        // self.tableView.reloadData()
     }.ensure{
        self.tableView.reloadData() 
     }

**Comment by marlowcharite** [comment]
Sometimes in your `then` block you do have to specify that there is no return value so:

```swift
my_promise.then { asynly_fetched_data -> Void in 
    self.data = asyncly_fetched_data
    self.tableView.reloadData()
} 
```
should work

**Comment by mxcl** [comment]
Indeed, it's a swift bug. Specify the return type. More details in the PromiseKit documentation.
