### ISSUE TITLE
Cocoapods doesn't work (xCode 6.4)

### ISSUE THREAD

**Issue by gerchicov-bp** [mxcl/PromiseKit#243]
```
platform :osx

use_frameworks!

pod "PromiseKit", "~> 2.0"
```

or even without concrete version:

```
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `PromiseKit (~> 2.0)` required by `Podfile`
```

**Comment by gerchicov-bp** [comment]
but carthage seems to be workable

**Comment by mxcl** [comment]
Works-for-me:

```bash
$ pod update
Update all pods
Analyzing dependencies

CocoaPods 0.38.2 is available.
To update use: `sudo gem install cocoapods`

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Downloading dependencies
Installing PromiseKit (2.2.1)
Generating Pods project
Integrating client project
```

I’m not sure what to suggest.

**Comment by gerchicov-bp** [comment]
sorry. Since that time I have found that this trouble is because I try to import PromiseKit into "xcode plugin" project. I have already tried cocoapods, carthage and simply framework importing - nothing works.

I could suggest to import PromiseKit as simply source code files but I don't know how to detach it from the project correctly.

Maybe could you advice something?
