### ISSUE TITLE
PromiseKit in xCode plugin?

### ISSUE THREAD

**Issue by gerchicov-bp** [mxcl/PromiseKit#244]
Cocoapods doesn't work at all.

Carthage seems to be workable but NOT for plugin. I install the carthage and add a link to the generated framework manually but I get this:
```
2015-08-19 12:14:57.587 Xcode[4406:133411] WARNING: Failed to load plugin at path: "/Users/gerchicov/Library/Application Support/Developer/Shared/Xcode/Plug-ins/AdvancedSearchPlugin.xcplugin", skipping. Error: Error Domain=NSCocoaErrorDomain Code=3587 "The bundle “AdvancedSearchPlugin” couldn’t be loaded because it is damaged or missing necessary resources." (dlopen_preflight(/Users/gerchicov/Library/Application Support/Developer/Shared/Xcode/Plug-ins/AdvancedSearchPlugin.xcplugin/Contents/MacOS/AdvancedSearchPlugin): Library not loaded: /Library/Frameworks/PromiseKit.framework/Versions/A/PromiseKit
  Referenced from: /Users/gerchicov/Library/Application Support/Developer/Shared/Xcode/Plug-ins/AdvancedSearchPlugin.xcplugin/Contents/MacOS/AdvancedSearchPlugin
  Reason: image not found) UserInfo=0x608000266fc0 {NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Users/gerchicov/Library/Application Support/Developer/Shared/Xcode/Plug-ins/AdvancedSearchPlugin.xcplugin/Contents/MacOS/AdvancedSearchPlugin, NSDebugDescription=dlopen_preflight(/Users/gerchicov/Library/Application Support/Developer/Shared/Xcode/Plug-ins/AdvancedSearchPlugin.xcplugin/Contents/MacOS/AdvancedSearchPlugin): Library not loaded: /Library/Frameworks/PromiseKit.framework/Versions/A/PromiseKit
  Referenced from: /Users/gerchicov/Library/Application Support/Developer/Shared/Xcode/Plug-ins/AdvancedSearchPlugin.xcplugin/Contents/MacOS/AdvancedSearchPlugin
  Reason: image not found, NSBundlePath=/Users/gerchicov/Library/Application Support/Developer/Shared/Xcode/Plug-ins/AdvancedSearchPlugin.xcplugin, NSLocalizedDescription=The bundle “AdvancedSearchPlugin” couldn’t be loaded because it is damaged or missing necessary resources.}
objc[4406]: Class IDEBlockScrollView is implemented in both /Applications/Xcode.app/Contents/Frameworks/IDEKit.framework/Versions/A/IDEKit and /Applications/Xcode.app/Contents/PlugIns/IDEProductsUI.ideplugin/Contents/MacOS/IDEProductsUI. One of the two will be used. Which one is undefined.
2015-08-19 12:14:58.165 Xcode[4406:133486]  DeveloperPortal: Using pre-existing current store at URL (file:///Users/gerchicov/Library/Developer/Xcode/DeveloperPortal%206.4.db).
2015-08-19 12:14:58.611 Xcode[4406:133411] [MT] DSMDocSetLoading: Error loading docSet file:///Library/Developer/Shared/Documentation/DocSets/com.db-in.NinevehGL.docset/: Error Domain=com.apple.DADocSetAccess Code=12 "Documentation set could not be read." UserInfo=0x610000472480 {NSLocalizedDescription=Documentation set could not be read., NSLocalizedFailureReason=Unable to find the database or 'Nodes.xml' configuration file.}
```

The standalone method contains such silly instruction that I can't understand and use it at all.

**Comment by mxcl** [comment]
The AdvancedSearchPlugin is something you installed yourself. Maybe you should uninstall it?

**Comment by gerchicov-bp** [comment]
```AdvancedSearchPlugin``` is the name of my project in which I try to import PromiseKit. It doesn't work even if I try to remove it from the xcode plugins folder with the same error.

**Comment by mxcl** [comment]
Your plugin target is not correctly copying PromiseKit.framework into its built bundle. This doesn't seem likely a CocoaPods problem.

It's hard to help you further unless you provide more information.

**Comment by gerchicov-bp** [comment]
contrawise it seems more common problem (which belongs to cocoapods too). Plugin target doesn't have "general" section so for example you can't simply drag a framewok into your project. If cocoapods depends pn the same or similar feature then it is the problem of xcode or cocoapods, or the similar importing system but not because of the target.

**Comment by mxcl** [comment]
If you need further help here I can try and assist, but it seems to be a CocoaPods bug.

The standalone instructions are simply: drag and drop three files. Sorry you found that “silly”, I can try and help further if you have more questions.

**Comment by gerchicov-bp** [comment]
When I said "silly" I just meaned that the included instructions are totally unclear and ambiguous. But yes, anyway that won't solve my problem

**Comment by mxcl** [comment]
If you can specify how the instructions are unclear I can improve them. These are the instructions:

1. Download the zip.
2. Drag and drop the three PromiseKit.* files into your project.
3. Drag and drop any of the sources from the Categories directory that you need.

I'm not sure what I can do to improve that. It seems pretty clear to me.

**Comment by mxcl** [comment]
Unless you meant the standalone binary instructions.

 1. Drag and drop either the iOS or OS X PromiseKit.framework into your
    xcodeproj, ensure it is added to your application target.
 2. In your project’s settings, ensure the framework is set to be embedded and
    not just linked.
 3. Add the sources for any categories/extensions you require to your project
    from the Categories directory in this distribution.
 4. If you add the category for NSURLConnection, you also need to drag and drop
    OMGHTTPURLRQ.framework.
 5. Ensure “embedded content contains Swift” is checked in your build settings.

I haven't found any clearer instructions for other projects. Maybe you can provide a clearer example?

**Comment by gerchicov-bp** [comment]
unclear for me:
2. ?
3. ? And a lot of errors occur if I just try to import something which uses your framework. And in general doesn't your framework already include these sources?
5. Just for swift project or for objective C too?

**Comment by mxcl** [comment]
2. In the project settings there are two sections clearly labeled Linked Frameworks and Embedded Frameworks. I'm not sure how to make this clearer.
3. There are sources in a directory called Categories in the distribution. Add the sources you want. I'm not sure how to reword this so it is clearer.
5. For both or it would be clearer.

**Comment by gerchicov-bp** [comment]
Thanks. But this extended info is necessary to include in that txt file with instructions.
