### ISSUE TITLE
PromiseKit documentation for PromiseKit:when shows incorrect code

### ISSUE THREAD

**Issue by tomblah** [mxcl/PromiseKit#246]
Not an issue with the code, rather the documentation.

http://promisekit.org/when/ shows:

PMKWhen(@[search1, search2]).then(^(NSArray *results){
    //…
}).catch(^{
    // called if either search fails
});

Whereas should be:

[PMKPromise when:@[search1, search2])].then(^(NSArray *results){
    //…
}).catch(^{
    // called if either search fails
});

Cheers,

**Comment by mxcl** [comment]
But the documentation Is correct for PromiseKit 2, which is the current release. You are documenting PromiseKit 1, which is no longer recommended.

**Comment by tomblah** [comment]
Ah, whoops, good point, sorry

**Comment by mxcl** [comment]
np 👍🏻
