### ISSUE TITLE
Standalone Binary URL 404s

### ISSUE THREAD

**Issue by tupakapoor** [mxcl/PromiseKit#247]
`https://github.com/mxcl/PromiseKit/releases/download/2.2.2/PromiseKit-2.2.2.zip`
https://github.com/mxcl/PromiseKit/commit/ab09a5ab28233b7ffab2821601e6f56291486c39#diff-0a369498a5a8db3ac8fa606b544c9810R56

Can't download the binary :)

**Comment by mxcl** [comment]
Yes, for some reason Carthage won’t build the binaries, and usually this is what I use to build the distribution.

2.2.1 exists however: https://github.com/mxcl/PromiseKit/releases

**Comment by mxcl** [comment]
Uploaded.
