### ISSUE TITLE
PUT and PATCH support

### ISSUE THREAD

**Issue by shyamvala** [mxcl/PromiseKit#251]
Hi,

I am just curious if there is any support for PATCH Http Method using NSURLConnection. I could not find any ?

Also, when using PUT method I see that the only support exists for passing params as urlencodedparams but not json body. Is there any support for passing a JSON request body with PUT ?

Thanks
Shyam

**Comment by mxcl** [comment]
There is no support. It's easy enough to add. PR welcome.

**Comment by mxcl** [comment]
The task would involve adding functions here:

https://github.com/mxcl/PromiseKit/blob/master/Categories/Foundation/NSURLConnection%2BPromise.swift

And adding PATCH to `OMGHTTPURLRQ`: https://github.com/mxcl/OMGHTTPURLRQ/blob/master/Sources/OMGHTTPURLRQ.h

**Comment by mxcl** [comment]
The alternative would be AFNetworking and one of the AFNetworking+Promise libraries in CocoaPods.
