### ISSUE TITLE
Code Signing Issue

### ISSUE THREAD

**Issue by marlowcharite** [mxcl/PromiseKit#254]
So I'm running into a weird issue when building using Carthage from time to time. I have 2 machines, on one I'm able to checkout and build PromiseKit through Carthage just fine but on the other when I run `carthage update` or `carthage bootstrap` I get the following error: 

```Code Sign error: No matching provisioning profiles found: No provisioning profiles with a valid signing identity (i.e. certificate and private key pair) matching the bundle identifier “org.promisekit.PMKiOSUITestsHost” were found.```

Any thoughts?

**Comment by marlowcharite** [comment]
This is so weird as I've opened up an issue a little while back about the same error. But then it started to work... so now I'm even more confused on what the issue is. 

*SN:* the previous issue was #237

**Comment by mxcl** [comment]
Seems like a carthage bug. It shouldn't be trying to build that target/scheme.

**Comment by marlowcharite** [comment]
Yeah it might definitely be a Carthage bug as I've been building fine on my MacBook Pro

**Comment by pidjay** [comment]
Hi there! Did you have any luck with this code signing error? I've just got the same issue today, and I can't seem to figure out how to solve it...
