### ISSUE TITLE
I'm trying to use this SwiftKit

### ISSUE THREAD

**Issue by reduxdj** [mxcl/PromiseKit#255]
What's missing is a more *simple* example of how to resolve a simple promise... maybe a couple that show how to return a tuple. I'm new to swift and wrapping my head around rolling my own httpswift call to resolve a promise and return a tuple is a little difficult. (Forgive me I'm newer to Swift, and I know the pleasure of writing clean code)

**Comment by mxcl** [comment]
Please provide example code.

**Comment by mxcl** [comment]
```swift
func httpswiftCall() -> Promise<(Int, String)> {
    return Promise { fulfill, reject in
        myHTTPFunc(url) { statusCode, responseString in
            fulfill(statusCode, responseString)
        }
    }
}
```

Sorry if there isn't a more simple example in the documentation.
