### ISSUE TITLE
Compile error when Swift UIViewController implements Promisable

### ISSUE THREAD

**Issue by brianhv** [mxcl/PromiseKit#258]
I apologize if this is the wrong place to go for support, but I didn't find anyplace else.

In swift, I have a class `class ChangePasswordViewController: UIViewController, Promisable`. In this class, I have `@objc let promise: AnyObject` which is populated from defer(). The idea is to use this with `promiseViewController()` which seems to mostly compile.

The problem arises in the ObjC header that is generated from the Swift. Although this header contains `@interface ChangePasswordViewController : UIViewController <Promisable>` and `@import PromiseKit;` I get the error `Cannot find protocol declaration for 'Promisable'` on the aforementioned `@interface` line.

Additional details: I've installed PromiseKit with Cocoapods, obviously using `use_frameworks!`. I'm still on XCode 6.4.

Any idea what might be going wrong here?

**Comment by brianhv** [comment]
For the moment I've been able to work around this by creating a header with the following:
```
@protocol Promisable
@end

#import "MyProductModule-swift.h"
```
...and having my ObjC code import that instead of importing `MyProductModule-swift.h` directly.

**Comment by mxcl** [comment]
The swift and objc implementations of the categories sources are separate. Perhaps this will work, but currently at least, it's not supported. 

You'll notice there is code for promiseViewController in the objc portion of the categories.

**Comment by brianhv** [comment]
To be clear, I'm not actually trying to use the class in question in ObjC at all. It gets put into the autogenerated header even though I don't want it to be. Just implementing the protocol in a Swift class causes the compilation to fail.

**Comment by mxcl** [comment]
I see. I'm not sure if this is a bug in the toolchain or a problem with the PromiseKit bridging header.

I believe you can annotate `@notobjc` (or something like that) to prevent it being put in that header though.

**Comment by mxcl** [comment]
I guess this is our fault. Our Swift-objc bridge doesn't include the `Promisable` protocol.
