### ISSUE TITLE
Carthage framework does not include categories

### ISSUE THREAD

**Issue by toddrick** [mxcl/PromiseKit#259]
Ex: [UIView promiseWithDur...] is not available when importing PromiseKit using Carthage.  Looks like more public header files need to be added.

P.S. Huge fan of the kit

**Comment by mxcl** [comment]
Yes, this is documented. It cannot contain the categories or linking to PromiseKit would link almost all possible system frameworks. You have to manually copy the categories in from the Carthage checkout.

**Comment by mxcl** [comment]
In fact, it is not documented. I cannot modify this project legally currently, maybe someone could do a PR?

**Comment by nathanhosselton** [comment]
Fixed in https://github.com/nathanhosselton/PromiseKit/commit/8071b65a3a9a3bcd86bd245450efb426921a035b
