### ISSUE TITLE
Support a progress handler

### ISSUE THREAD

**Issue by inf0rmer** [mxcl/PromiseKit#26]
Some Promise libraries support the addition of a `progress` handler. It is meant for communicating progress in long-running operations (some more discussion [here](https://github.com/promises-aplus/progress-spec/issues/1)).

What are your thoughts on implementing this handler in PromiseKit? I have a specific use case that I've seen other libraries deal with using `progress` handlers:
- I have a network request (that returns a Promise) that may or may not hit a shared `NSURLCache`. In case it does, and if the user explicitly sets it (via a new `NSURLRequestCachePolicy`), the request serves the cached data and then fetches from the network anyway. This is so that the user gets potentially stale data immediately while fresh data is being fetched in the background.

I would possibly like to use `progress` to support this use case, serving the cached data through this handler and then the final, fresh, data through the normal `fulfillment` handler.

Other than using `progress`, do you see any potential way of supporting this behaviour using just the two currently supported handlers?

Thank you!

**Comment by Igor-Palaguta** [comment]
Looks like progress in URLSessionTask is lazy now. Currently NSURLSession+Promise hides task inside, so there is no way to access to task's progress to initiate its creation.

In mentioned below code parentProgress not changing:

```swift
    let parentProgress = Progress(totalUnitCount: 1)
    parentProgress.becomeCurrent(withPendingUnitCount: 1)
    let promise = URLSession.shared.dataTask(.promise, with: request)
    parentProgress.resignCurrent()
```

but, after adding `_ = task.progress`, it will work properly:

```swift
    public func dataTask(_: PMKNamespacer, with convertible: URLRequestConvertible) -> Promise<(data: Data, response: URLResponse)> {
        return Promise { seal in
            let task = dataTask(with: convertible.pmkRequest, completionHandler: adapter($0))
            _ = task.progress
            task.resume()
        }
    }
```

**Comment by mxcl** [comment]
Ticket pls
