### ISSUE TITLE
Can't run `carthage update` (or tests) due to Bolts failure

### ISSUE THREAD

**Issue by bgerstle** [mxcl/PromiseKit#263]
Not a PromiseKit error, but I tried to be diligent by running the tests before submitting #262 and couldn't due to this error with Bolts:

> error: cannot parse the debug map for "/Users/bgerstle/Code/PromiseKit/Carthage/Build/iOS/Bolts.framework/Bolts": The file was not recognized as a valid object file

Tried rolling back to Bolts 1.2.0, but no luck. Using Carthage 0.8.

**Comment by mxcl** [comment]
Yes, Bolts apparently doesn’t build with Carthage currently. It affects me also. Hopefully Facebook will fix it.

Not building Bolts allows the rest of the Carthage deps to build, but then the iOS tests will fail.

**Comment by nathanhosselton** [comment]
I believe this is resolved now as I have no longer have an issue building Bolts with Carthage. But feel free to reopen if it persists.
