### ISSUE TITLE
How to use Array with promises in Swift 2?

### ISSUE THREAD

**Issue by johanwigmo** [mxcl/PromiseKit#264]
With Swift 1.2 it was possible to do like this:

```swift
let promises: [Promise<Any>] = [
  getGames().asAny(), // func getGames() -> Promise<[Game]>
  getUser().asAny() // func getUser() -> Promise<User>
]

when(promises).then {
  results -> Void in

  if let games = results[0] as? [Game] {
    self.games = games
  }

  if let user = results[1] as? User {
    self.user = user
  }

}
```

But as asAny() is not available in the branch `swift-2.0-beta5` I have no idea how to accomplish this. Any ideas?

**Comment by ldiqual** [comment]
@johanwigmo What I do is this:

```
let promise1 = myPromise1()
let promise2 = myPromise2()

when([promise1.asVoid(), promise2.asVoid()]).then {
    let value1 = promise1.value
    let value2 = promise2.value
}
```

Might not be the prettiest solution though. Maybe @mxcl can hint on a better one?

**Comment by mxcl** [comment]
You can do this with Swift `when` now:

```swift
when(getGames(), getUser()).then {
  games, user in
  self.games = games
  self.user = user
}
```

This works up to four parameters. If you need more then they must all be the same type, and yeah, I recommend the `asVoid()` method. `asAny` was removed because `Any` is dangerous and I feel responsible to promise safe `Promise` use, you can still do it though if you like:

`promise.then { $0 as Any }`

**Comment by johanwigmo** [comment]
I tried the `asVoid()` method as @ldiqual mentioned but sometimes `promise.value` returns nil and I can't figure out why. 

``` swift

let promise1 = getGames() // func getGames() -> Promise<[Game]>
let promise2 =  getUser() // func getUser() -> Promise<User>
var promises: [Promise<Void>] = [promise1.asVoid(), promise2.asVoid()]

when(promises).then {
  _ -> Void in

  if let games = promise1.value {
    self.games = games
  }

  if let user = promise2.values {
    self.user = user
  }

}
```

**Comment by mxcl** [comment]
It returns nil if the promise was rejected. So if it returns nil in the then it is a bug. It seems unlikely it is doing so though. We have SOOOO many tests.

**Comment by mxcl** [comment]
Anyway how about the solution I gave? It is type safe and the suggested route for Swift.
