### ISSUE TITLE
watchOS 2 support

### ISSUE THREAD

**Issue by sahandnayebaziz** [mxcl/PromiseKit#265]
I would love to use PromiseKit on watchOS 2. If the Pod and PromiseKit can be updated easily to support watchOS 2 as a deployment target, even better! 

[Podspec syntax for adding watchOS 2 deployment target](https://guides.cocoapods.org/syntax/podspec.html#watchos)

**Comment by mxcl** [comment]
Does it not work? Most of the spec only specifies sources for *all* platforms.

**Comment by sahandnayebaziz** [comment]
I don't believe it does. These are the messages I get when trying ```pod install```.

master:
```[!] The platform of the target `FSWatchKit Extension` (watchOS 2.0) is not compatible with `PromiseKit (2.2.1)`, which does not support `watchOS`.```

swift-2.0-beta5:
```[!] The platform of the target `FSWatchKit Extension` (watchOS 2.0) is not compatible with `PromiseKit (3.0.0)`, which does not support `watchOS`.```

**Comment by mxcl** [comment]
I guess it's because we do:

```ruby
  s.ios.deployment_target = '8.0'
  s.osx.deployment_target = '10.9'
```

It needs a `watchos` one too.

**Comment by sahandnayebaziz** [comment]
I forked to add the deployment target and discovered this! 

```The platform of the target `FSWatchKit Extension` (watchOS 2.0) is not compatible with `OMGHTTPURLRQ (3.0.0)`, which does not support `watchOS`.```

Should I create an issue with OMGHTTPURLRQ?

**Comment by mxcl** [comment]
Please.

You may not need OMGHTTPURLRQ for watchOS though. Using any networking there?

**Comment by sahandnayebaziz** [comment]
No, not using any of the networking. I just want to make this as easy as possible for you. 

Made an issue in OMGHTTPURLRQ and made PR's in both.

**Comment by sahandnayebaziz** [comment]
I just discovered something that I'm not sure how to handle. 

Including all of PromiseKit into a watchOS target doesn't build because it hits a snag trying to import QuartzCore/QuartzCore.h. Including only CorePromise works just fine (and maybe makes more sense?).

How do you think we should handle this?

**Comment by nathanhosselton** [comment]
QuartzCore is only used within the CALayer+PromiseKit category. Many of the categories will not be relevant on watchOS, so CorePromise should be all that you need.

**Comment by sahandnayebaziz** [comment]
Great. That makes sense. Do you think that should be in the documentation?

**Comment by nathanhosselton** [comment]
Which part? The documentation currently includes direction for excluding/including the categories. There's no mention of watchOS or tvOS, so that could be added.

**Comment by mxcl** [comment]
You may want the Foundation categories:

`pod 'PromiseKit/Foundation'`

We should make a `Foundation-HTTP` subspec so stuff can avoid requiring OMG.

**Comment by morten-holm** [comment]
Could you please add a target 'PMKWatchOS' to PromiseKit so it's possible to use with Carthage?

**Comment by nathanhosselton** [comment]
@morten-holm This is currently planned for inclusion in 3.0.0 which will be released soon (hopefully).

**Comment by mxcl** [comment]
So, is this fixed?

**Comment by nathanhosselton** [comment]
Resolved by #272

**Comment by x-l-ent** [comment]
Is it possible to use CocoaPods to get PromiseKit working on watchOS 2? If so, how? Thanks.

**Comment by mofirouz** [comment]
Please refer to this if you are using PromiseKit 1.6.x:

https://github.com/mxcl/PromiseKit/issues/311#issuecomment-187140360
