### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by bruceflowers** [mxcl/PromiseKit#268]
I would love to be able to use PromiseKit in a tvOS project... Is there any plan to add support for this in the near future?

**Comment by wovencharlie** [comment]
+1

**Comment by mxcl** [comment]
Does it not work?

**Comment by dbachrach** [comment]
We've got promises working in tvOS as is.

**Comment by bruceflowers** [comment]
I'm trying to build the swift2-beta5 branch (a413bbad4c539dadf36312d471e932e0ce980fd4) using carthage update --platform tvOS.

Perhaps there's a more current swift2 branch I didn't see, or maybe I'm missing something else?

Anyway, this is the output I get:

carthage update --platform tvOS
*** Fetching PromiseKit
*** Fetching OMGHTTPURLRQ
*** Checking out PromiseKit at "a413bbad4c539dadf36312d471e932e0ce980fd4"
*** Checking out OMGHTTPURLRQ at "3.0.0"
*** xcodebuild output can be found in /var/folders/66/7ttbxjv94md42tvryd7ww0fc0000gn/T/carthage-xcodebuild.ehAk9Q.log
*** Skipped building OMGHTTPURLRQ due to the error:
Dependency "OMGHTTPURLRQ" has no shared framework schemes for any of the platforms: tvOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/mxcl/OMGHTTPURLRQ/issues/new
*** Skipped building PromiseKit due to the error:
Dependency "PromiseKit" has no shared framework schemes for any of the platforms: tvOS

**Comment by dbachrach** [comment]
Hmmm. We integrated with cocoapods and used that branch.

**Comment by bruceflowers** [comment]
What version of CocoaPods?

I ask because it looks like tvOS support was worked on, but only lives in this PR right now:
https://github.com/CocoaPods/CocoaPods/pull/4152

But it doesn't look like it's been merged in...

**Comment by dbachrach** [comment]
We are on cocoa pods 0.38.2, and here's our podfile:

```ruby
platform :ios, '8.0'
use_frameworks!

inhibit_all_warnings!
pod 'PromiseKit'

post_install do |installer|
    installer.pods_project.targets.each do |target|
    	target.build_configurations.each do |config|
           	config.build_settings['SUPPORTED_PLATFORMS'] = ['appletvos', 'appletvsimulator'];
    	end
    end
end
```

This doesn't use the new tvOS branch, and just manually updates the build settings to support tv and tv simulator.

**Comment by bruceflowers** [comment]
I've got problems with some other pods not being compatible with use_frameworks!, so it's Carthage for any swift libraries in the project. But your fix is interesting!

**Comment by JALsnipe** [comment]
@dbachrach has a great solution, but also causes PromiseKit to import some `UIKit` extensions that are unavailable on tvOS.  I modified his Podfile to import only the modules I needed:

```
# https://github.com/mxcl/PromiseKit/issues/268

platform :ios, '8.0'
use_frameworks!

inhibit_all_warnings!
pod 'PromiseKit/CorePromise'
pod 'PromiseKit/Foundation'
pod 'PromiseKit/SystemConfiguration'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SUPPORTED_PLATFORMS'] = ['appletvos', 'appletvsimulator'];
        end
    end
end
```

**Comment by lagerkoller** [comment]
it does not seem like this still works in the current version of cocoa pods (1.0.0.beta.2). my podfile requires this as the platform: 'platform :tvos, '9.0''

so this does not work:
	platform :tvos, '9.0'
	#link_with 'Cappalogue'
	use_frameworks!
	
	target 'XYZ' do  
	  inhibit_all_warnings!
	  pod 'PromiseKit'
	  
	  post_install do |installer|
	      installer.pods_project.targets.each do |target|
	          target.build_configurations.each do |config|
	              config.build_settings['SUPPORTED_PLATFORMS'] = ['appletvos', 'appletvsimulator'];
	          end
	      end
	  end
	end

any ideas on how this could work in the current cocoa pods version?

**Comment by nathanhosselton** [comment]
The latest version (3.0.2, just released) includes proper tvOS support so the workarounds mentioned here should no longer be necessary. Please test and report back. Thanks!
