### ISSUE TITLE
UIAlertView promise (PromiseKit 3.0.0)

### ISSUE THREAD

**Issue by warpling** [mxcl/PromiseKit#269]
Hey Max,

Thank you for all the speedy updates. I hate to bother you but I'm stuck in the middle of an upgrade of a Obj-C project to PromiseKit 3.0.0 and could use some help.

I've been unable to remedy this error: `No visible @interface for 'UIAlertView' declares the selector 'promise'` for my use of:
````
UIAlertView *alert = [UIAlertView …];
[alert promise].then(^(NSNumber *dismissedButtonIndex){...}));
````
After multiple pod reinstalls, clean builds, I'm not sure what to try next.

---
In this file I import PromiseKit like so:
````
@import PromiseKit;
````

In my Podfile I install PromiseKit like this:
````
    use_frameworks! pod 'PromiseKit', :git => 'https://github.com/mxcl/PromiseKit.git', :branch => 'swift-2.0-beta5'
    use_frameworks! pod 'PromiseKit/CoreLocation', :git => 'https://github.com/mxcl/PromiseKit.git', :branch => 'swift-2.0-beta5'
    use_frameworks! pod 'PromiseKit/UIKit', :git => 'https://github.com/mxcl/PromiseKit.git', :branch => 'swift-2.0-beta5'
````

**Comment by mxcl** [comment]
You have to import PromiseKit with the old syntax:

```objc
#import <PromiseKit/PromiseKit.h>
```

Otherwise none of the categories get imported.

It's a limitation of modules.

**Comment by warpling** [comment]
Ah! Thank you, that did the trick!
I feel really stupid saying this, but I first gave up on that route when Xcode wouldn't autocomplete that path. I obviously don't know enough about linking/modules yet.

Thank you again.

**Comment by mxcl** [comment]
np imo it's not intuitive. I document it in various places, but there's a lot of docs so I'd miss it too.
