### ISSUE TITLE
Xcode 7 has issues with the standalone distribution

### ISSUE THREAD

**Issue by franksrevenge** [mxcl/PromiseKit#270]
Seeing couple of issues with Xcode 7 and the standalone distribution (2.2.2):

* If including the framework as is, Xcode complains that the library hasn't been built with bitcode enabled (ENABLE_BITCODE)

* When disabling bitcode, Xcode builds, but running the application fails, unable to find libswiftSecurity.dylib

Downloading the source and building from scratch on Xcode 7 appears to solve the issue.

**Comment by chimp7** [comment]
How did you include it into your existing project, I'm having some problems

**Comment by mxcl** [comment]
Swift is not ABI compatible. The binaries were built against swift 1.2. Xcode comes with Swift 2. You need to build from source.

**Comment by franksrevenge** [comment]
@chimp7: Downloaded the project, loaded it in Xcode, let Xcode auto-convert the Swift code, and built. Very straight-forward.

@mxcl: Understood. Could you consider a Swift 2 build at some point, though? This is stopping use of the standalone build on Xcode 7, after all.

**Comment by mxcl** [comment]
There already is a swift 2 build. Check the swift 2 branch.

**Comment by mxcl** [comment]
Don't auto convert master. Use one of the swift 2 branches.

There will be a rebuilt standalone distribution for Xcode 7 or it will be removed altogether.

**Comment by toddrick** [comment]
Is there a timeline for this? Pretty obnoxious to build from source if you're using Carthage, means you have to remove PromiseKit altogether and re-add.

**Comment by mxcl** [comment]
I have to release 3.0 and it has issues. Before that there cannot be a new Carthage release.

I'm not sure I entirel

**Comment by cjhenck** [comment]
The 2.2.2 download also doesn't seem to have the framework in the iOS folder (or am I missing something?)

**Comment by fallback** [comment]
@cjhenck Observing the same.

**Comment by mxcl** [comment]
I am sorry about this. I wish I could be more responsive. The issues are beyond our control to promptly deal with. In the meantime you can try to build them yourself. It should be a simple enough matter. We can help with any issues.

**Comment by mxcl** [comment]
I've removed the references to the standalone distributions since it is a foolish errand to provide them in this time of no Swift ABI compatibility.
