### ISSUE TITLE
Chaining promises inside for

### ISSUE THREAD

**Issue by gPinato** [mxcl/PromiseKit#273]
I'm trying to chain a number of promises that need to be resolved before returning.

In my case, for each element of databaseResult I need to fetch some data with a method that returns a promise.

Once I've fetched the data for every single element of the array ( so all the promises have returned), toReturn is complete and I'm happy

    static func fetchList() -> Promise<[MatchModel]> {

    var toReturn = [MatchModel]()
    //get my array of data
    let databaseResults = [ArrayWithMyData]
    
    //not sure what I'm doing
    var promise = dispatch_promise{ 0 }
    if(databaseResults.count > 0) {

        return Promise { fulfill, reject in
            
            for index in 0..<databaseResults.count {
                promise = promise.then { y -> Promise<Int> in
                    //Fetch the data I need ...    
                    DataProvider.fetch((databaseResults[y].id)!)
                        .then {(model) in {
                            //and use it to create the data I need to return
                            toReturn.append(MatchModel(
                                databaseResults[y], partnerProfile: model))
                            
                            }
                    }       
                    return dispatch_promise { index }
                }
            }
            //Once all the promises are fulfilled, toReturn contains the data I need and I can return it
            promise.then{ x in {
                fulfill(toReturn)
                }
            }
        }
    }

If I run this I get
     PromiseKit: Pending Promise deallocated! This is usually a bug

I've looked at some exapmles but I'm new to both swift and promisekit so I'm having a hard time understanding how to solve this problem.
Can I please get some help?

**Comment by nathanhosselton** [comment]
Hey there. Have you checked out [when](http://promisekit.org/when/)? Like you, I am not strong in Swift, so you'll have to forgive me if I haven't discerned all of your requirements. But I've dealt with the scenario you describe multiple times by passing `when` an array of promises that represent each of the tasks I need completed. If this doesn't meet your needs or if you would like additional examples let me know.

**Comment by gPinato** [comment]
That's exaclty what I was looking for, I dont' know how I missed it.
I manage to get it work by pushing all promises into an array and put that array into a when.
(Seems to) work like a charm.

Thanks!

**Comment by mxcl** [comment]
Here’s the minimal version:

```swift
static func fetchList() -> Promise<[MatchModel]> {
    return when(databaseResults.map{ dbresult in 
        DataProvider.fetch(dbresult!).then { model in
            return MatchModel(dbresult, partnerProfile: model))
        }
    })
}
```
