### ISSUE TITLE
Property 'then' not found on object of type 'PMKPromise *'

### ISSUE THREAD

**Issue by opfeffer** [mxcl/PromiseKit#275]
I recently tried updating my PromiseKit pod from version `~> 1.5.0` to latest (`2.2.2`). My project is entirely written in ObjC and I'm receiving the following compiler error from Xcode6.4:

> Semantic Issue
> Property 'then' not found on object of type 'PMKPromise *'.

Sample code:
```objc
- (PMKPromise *)bar {
    return [PMKPromise new:^(PMKFulfiller fulfill, PMKRejecter reject) {
        fulfill();
    }];
}

- (void)foo {
    self.bar.then(^{
        NSLog(@"yay");
    });
}
```

It's worth mentioning that `-bar` also shows a number of errors after upgrading:

> Parse Issue
> Expected ')'

> No known class method for selector 'new:'

Weirdly enough, when cmd+clicking on `-new:` Xcode does resolve me to `Pods/PromiseKit/CorePromise/PMKPromise.m:13`

Same is true for when resolving `-then`: Xcode resolves to `AnyPromise.h:47`.

My imports look as follows:

```
@import PromiseKit;
#import <PromiseKit/PromiseKit.h>
```

Any idea why the compiler is complaining?

**Comment by nathanhosselton** [comment]
I believe the `@import PromiseKit` is unnecessary and (potentially) the source of the issue, though this is mostly a hunch. Have you tried removing it?

**Comment by opfeffer** [comment]
Tried every possible variation. No luck.

Weirdly enough, including `<PromiseKit/PromiseKit.h>` in my *-Prefix.pch seems to fix it. Can't really make sense out of that though.... Open for ideas!

**Comment by mxcl** [comment]
PromiseKit 2 does not work as a modular import. This is documented.

Sorry. I know it sucks.

**Comment by mxcl** [comment]
So what this means is: you must import it with a #
