### ISSUE TITLE
Broken link for "Language Bridging" on promisekit.org

### ISSUE THREAD

**Issue by todd1251** [mxcl/PromiseKit#278]
Couldn't find a public repository for the website... :-)

In the _PromiseKit Handbook_ section of the [website navigation](http://promisekit.org/introduction/) there is a broken link: _[2. Language Bridging](http://promisekit.org/swift)_.

It links to [`/swift`](http://promisekit.org/swift) but should be [`/language-bridging`](http://promisekit.org/language-bridging). The link is correct in the footer of the previous page.

**Comment by cmckni3** [comment]
I just ran into the same problem.

Is there additional documentation available? I don't mind looking through the code but it's not as convenient.
