### ISSUE TITLE
Unable to build ObjC project with PromiseKit/all pod in iOS 8

### ISSUE THREAD

**Issue by ivanovvitaly** [mxcl/PromiseKit#279]
I have used PromiseKit/all 1.3 so far in project written in ObjC and everything worked fine.
 
I updated pod file to following and now unable to compile, it fails with a lot of errors in swift files. The installed version is PromiseKit 2.2.1

platform :ios, "8.0"

target "MyProject" do
...
pod "PromiseKit/all"
...
end

Please advice, I need PromiseKit/all for ObjC iOS 8 that compiles.

Thanks!

**Comment by nathanhosselton** [comment]
Can you share some of the errors that you're receiving?

**Comment by mxcl** [comment]
Also, please specify your Xcode version.

**Comment by ivanovvitaly** [comment]
xcode version 7.0 (7A220). Attached images with errors, please let me know if its works for you.

<img width="347" alt="2015-09-28 12 42 38" src="https://cloud.githubusercontent.com/assets/1336292/10132303/77d1ea1e-65de-11e5-85fe-4900cc03523a.png">
<img width="786" alt="2015-09-28 12 47 55" src="https://cloud.githubusercontent.com/assets/1336292/10132468/38bbf670-65df-11e5-8c2d-d5bd88b22c1f.png">

Please note, that if I use following pod file, application compiles without errors and works fine.

platform :ios, "8.0"

target "MyProject" do
...
pod "PromiseKit", :git => "https://github.com/mxcl/PromiseKit.git", :branch => "swift-2.0-minimal-changes"
pod "PromiseKit/CoreLocation", :git => "https://github.com/mxcl/PromiseKit.git", :branch => "swift-2.0-minimal-changes"
...
end

Thanks!

**Comment by mxcl** [comment]
Xcode 7 is Swift 2, PromiseKit 2 is Swift 1. You need to use PromiseKit 1 or PromiseKit 3. PromiseKit 3 has not been released yet.
