### ISSUE TITLE
Add ability to use custom queue for `report`

### ISSUE THREAD

**Issue by ldiqual** [mxcl/PromiseKit#280]
In Xcodo 7's UI Tests, the main queue is blocked when calling `waitForExpectationsWithTimeout(timeout:handler:)`, which means you can't call a Promise and use the default queue in the `report` block. It would be perfect if we had the ability to call the report block in another queue than the main one.

**Comment by mxcl** [comment]
PromiseKit's tests use report and expectations all over the place.

Can you provide a test project that verifies your bug? Thank you.

**Comment by ldiqual** [comment]
@mxcl The problem only occurs in UI test targets when `waitForExpectationsWithTimeout` is called right after a `then/catch` is chained on a promise. The `then` block is not blocked when performed on another queue than the main queue. Alamofire has the same issue with its default queue here: https://github.com/Alamofire/Alamofire/issues/809. I'll provide a test project asap, thanks for asking.

Side note: I tried to checkout the project and run the tests but I'm unable to setup the carthage dependencies (it keeps asking me for my github credentials when I run `carthage bootstrap`). How do you usually proceed to checkout and run your tests?

**Comment by ldiqual** [comment]
@mxcl Here's the example project: https://www.dropbox.com/s/2c6vfqgxtuzltlj/PromiseKitReportQueueExample.zip?dl=0

The interesting stuff is in PromiseKitReportQueueExampleUITests.swift, you'll see 3 tests as part of the UI test target:
 - A successful promise with a `then` on the default queue (fail)
 - A successful promise with a `then` on a concurrent queue (pass)
 - An unsuccessful promise with a `report` on the default queue (fail)

I couldn't find any documentation on the behavior of `waitForExpectationsWithTimeout` in a UI test target, but I believe that it blocks the main queue from receiving further messages until all expectations are met. It doesn't block the actual UI though (you can still interact with the app in the simulator), which is weird.

**Comment by ldiqual** [comment]
@mxcl More info on the `waitForExpectationsWithTimeout` behavior: http://masilotti.com/xctest-documentation/Classes/XCTestCase.html#//api/name/waitForExpectationsWithTimeout:handler:

> -waitForExpectationsWithTimeout:handler: runs the run loop while handling events until all expectations are fulfilled or the timeout is reached. Clients should not manipulate the run loop while using this API.

**Comment by mxcl** [comment]
We don’t manipulate the run loop. We just `dispatch_async` onto it. This seems weird to me, Xcode UI tests can't work this way, so much stuff would break.

**Comment by mxcl** [comment]
OK so for PromiseKit’s UI tests the Promise logic is in the app. Why is your Promise code in the test bundle?

**Comment by ldiqual** [comment]
@mxcl I think it's totally reasonable to have async logic in a UI test bundle, a real world example from my app is this:
 - Signup
 - Validate email by querying an email service API (this logic is in the test)
 - Wait for the "please verify your email" view to disappear automatically

> Xcode 7’s UITest stuff is not designed to have logic in the testing portion

I don't think I agree with this, you can pretty much write any kind of code, perform http calls, do async stuff, as long as you don't try to perform stuff on the main queue while it's blocked with `waitForExpectationsWithTimeout:handler:`. I've never seen any documentation saying that there shouldn't be any logic in UI tests.

I'd even go one step further and say that being unable to choose the `catch` queue is a blocker for making performant threaded apps since you can't control where your code is executed. If your logic in `catch` is heavy, you block the UI for a while and this may be an issue. You could add a few lines to execute your `catch` code in another queue, but there'd be a performance hit if the queue doesn't exist already (potentially creating another thread), in addition to being inelegant.

> I am reluctant to add a queue parameter to catch

I think I see one issue in the order of arguments (you'd have to specify a policy before specifying a queue), but aside from this, what drawback do you think there is?

**Comment by mxcl** [comment]
I'm not saying it is unreasonable to do it, I'm saying it is technically impossible. The UI tests run in a separate process to your app. You can't interact with your code from the tests.

This is a known limitation to Xcode 7 UI tests.

> > I am reluctant to add a queue parameter to catch
>  what drawback do you think there is?

Developers make mistakes because they are trying to be performant. Error handling really must succeed or an end-user’s data may be at risk. By forcing all error handling to occur serially on the main thread PromiseKit is helping create a world of robust applications.

**Comment by ldiqual** [comment]
Oh yes sure, I misunderstood your comment. You can't interact with the code of your app, but your tests can contain logic (async or not) that's separated from the running app.

> Error handling really must succeed or an end-user’s data may be at risk. By forcing all error handling to occur serially on the main thread PromiseKit is helping create a world of robust applications.

I think it makes a lot of sense as the default behavior for the `catch` handler. In this case though, there's definitely an issue because the handler cannot be called at all since the main queue is blocked. With that in mind, can you think of another way to deal with this?

**Comment by jefferythomas** [comment]
If `-waitForExpectationsWithTimeout:handler:` is blocking the main thread of execution, then it is the problem. Before expectations, I created something similar for my unit testing called [JLTWaiter](https://github.com/jefferythomas/JLTWaiter). Swapping JLTWaiter for expectations allowed the tests to succeed. Perhaps you need to roll your own wait mechanism, if your UI tests must dispatch promises.

    func testSuccessOnDefaultQueue() {

        let waiter = JLTWaiter()

        Promise<Void>().then { Void -> Void in
            XCTAssert(true)
            waiter.finished = true
        }

        waiter.waitWithTimeOut(2)
    }

and 

    func testFailureOnDefaultQueue() {
        
        let waiter = JLTWaiter()

        let error = NSError(domain: "com.ldiqual.PromiseKitReportQueueExample.UITests", code: 500, userInfo: nil)
        Promise<Void>(error: error).report { error in
            XCTAssert(true)
            waiter.finished = true
        }
        
        waiter.waitWithTimeOut(2)
    }

**Comment by crazymaik** [comment]
+1 for having a report/error with a custom queue. I'm currently integrating PromiseKit into an existing application where the error handling is not executed on the main thread most of the time. Not having this functionality changes the threading behavior of the app. It would be easier to simply replace the current dispatch_* and queues with promises if error/report could be executed on a custom queue, instead of doing it in one big change.

**Comment by mxcl** [comment]
K. I'm cool with this. PR welcome.

**Comment by mxcl** [comment]
In case it isn't clear, we merged a PR adding this and pushed a new release.
