### ISSUE TITLE
can't use when() with more than a tuple of 3

### ISSUE THREAD

**Issue by ded** [mxcl/PromiseKit#283]
I don't know if this has to do with Swift 2.0, or PromiseKit....

but I'm running into this issue...

This works fine...
``` swift
when(p1(), p2(), p3()).then { (a, b, c) -> Void in
  //
}
```

But this does not...

``` swift
when(p1(), p2(), p3(), p4()).then { (a, b, c, d) -> Void in
  //
}
```

See here:

![image](https://cloud.githubusercontent.com/assets/372683/10238199/4e14d016-6871-11e5-8b86-1df8ce9a973c.png)

![image](https://cloud.githubusercontent.com/assets/372683/10238196/4644eba0-6871-11e5-9667-98e91a985603.png)

I'm super confused :/

**Comment by mxcl** [comment]
We only provide for up to 3. After three you have to use an array. See when.swift for the documentation.

**Comment by mxcl** [comment]
So:

```swift
when(p1(), p2(), p3(), p4()).then { results -> Void in
  //
}
```

would work.
