### ISSUE TITLE
Issue when getting PromiseKit 3.0.0 with Carthage

### ISSUE THREAD

**Issue by soundbites** [mxcl/PromiseKit#285]
Hey I'm getting the following error when I run carthage (0.8.0) update with PromiseKit (3.0.0) dependency;

---

Build settings from command line:
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = watchsimulator2.0

=== BUILD TARGET PMKwatchOS OF PROJECT PromiseKit WITH CONFIGURATION Release ===

Check dependencies
target 'PMKwatchOS' has bitcode disabled (ENABLE_BITCODE = NO), but it is required for the 'watchos' platform

---

**Comment by zdenektopic** [comment]
I cant actually get it in Podspec working. Getting:
```
[!] Invalid `lib-fastrpc+PromiseKit.podspec` file: [!] Unsupported version requirements. Updating CocoaPods might fix the issue.

 #  from /Users/zdenek.topic/Seznam/FastRPC-PromiseKit/lib-fastrpc+PromiseKit.podspec:36
 #  -------------------------------------------
 #    s.dependency 'lib-fastrpc', '~> 2.0'
 >    s.dependency 'PromiseKit/CorePromise', :git => 'https://github.com/mxcl/PromiseKit.git', :branch => 'changes-for-3.0'
 #  end
 #  -------------------------------------------
```

**Comment by Sljux** [comment]
+1

**Comment by nathanhosselton** [comment]
Looking into this. Bitcode is, in fact, enabled in the scheme and the scheme builds fine with xcodebuild.

**Comment by kanekin** [comment]
+1

**Comment by kanekin** [comment]
Do you need to use PromiseKit for watch development?
Otherwise, you can avoid the error by using:

      carthage update --platform iOS
      carthage update --platform Mac

**Comment by soundbites** [comment]
thx @kanekin this will work for now.

**Comment by nathanhosselton** [comment]
This should be resolved with the latest version of Carthage. Feel free to reopen if the issue persists.
