### ISSUE TITLE
How to use classic completionBlock inside promises ?

### ISSUE THREAD

**Issue by loryhuz** [mxcl/PromiseKit#289]
Hey,

I started to use promises to make my asyncrone code more beautiful. But I didn't manage everything with it yet so I wonder how to deal with my previous async does.

For example I've this promise call:

```
[self getCleanAddressFrom:userInputDic].then(^(SSStreetAddressResponse *addressResponse){
                cleanAddress = addressResponse;
            }).catch(^(NSError *error){
                NSLog(@"%@", error);
                
            }).finally(^{
                [self saveAddress:NO];
            });
```

I thought "finally" would do the stuff but it's seems it's still wrapped in the promise so my async code in saveAddress method will not work. I'm calling stuff like this:
```
[[DataController sharedController]
         saveAddressWithParameters:parameters
         andOnCompletion:^(BOOL success, NSString *message, GDataXMLDocument *xmlDoc) {
             // Stuff
         }];
```
I've also tried to wrap my non-promise with promiseWithResolverBlock, but it never resolve ending with this in console: PromiseKit: Pending Promise deallocated! This is usually a bug

Is there a solution to deal in case like mine ? It's doesn't crash or throwing an error, it's just do nothing. Thanks in advance

**Comment by mxcl** [comment]
> I thought "finally" would do the stuff but it's seems it's still wrapped in the promise so my async code in saveAddress method will not work.

There is no “promise stuff” that it can be “wrapped in”, If the `then` is called, then the `finally` will be called. Are you sure that your promise `getCleanAddressFrom:` resolves?

> I'm calling stuff like this:

    [[DataController sharedController]
         saveAddressWithParameters:parameters
         andOnCompletion:^(BOOL success, NSString *message, GDataXMLDocument *xmlDoc) {
             // Stuff
         }];

I don’t know what you mean here. Is this the contents of `saveAddress`?

**Comment by loryhuz** [comment]
Yes this is the content of saveAddress, which is not executed. Seems to be logic since I've read from the doc I've to use promiseWithResolver. PromiseWithResolver work fine if I just put a native block like "UIView withanimation on completion" but not when I wrap my own block (the one you copy-pasted).

Yes it's resolve since it's catch an error when it fail and continue to the next then after

So at the end I've also tested with these things:
```
- (AnyPromise *)test {
    
    NSMutableDictionary *parameters = [[NSMutableDictionary alloc] init];
    
    DataController *dataController = [DataController sharedController];
    return [AnyPromise promiseWithResolverBlock:^(PMKResolver  _Nonnull resolve) {
        [dataController
         saveAddressWithParameters:parameters
         andOnCompletion:^(BOOL success, NSString *message, GDataXMLDocument *xmlDoc) {
             resolve(message);
         }];
    }];
}
```

And the call in my controller:
```
[self getCleanAddressFrom:userInputDic].then(^(SSStreetAddressResponse *addressResponse){
                cleanAddress = addressResponse;
            }).catch(^(NSError *error){
                NSLog(@"%@", error);
                
            }).then(^(){
                return [self test];
            });
```

**Comment by mxcl** [comment]
Please provide the code to the getCleanAddress promise

**Comment by loryhuz** [comment]
Here it is:

```
#pragma mark - Smartystreets validation

- (AnyPromise *)getCleanAddressFrom:(NSDictionary *)userInputDic {
    NSError *err;
    SSStreetAddressRequest *addressRequest = [[SSStreetAddressRequest alloc] initWithDictionary:userInputDic error:&err];
    
    return [self.smartyStreetClient verifyStreetAddress:addressRequest].then(^(SSStreetAddressResponse *response){
        return response;
    });
}
```

Also the veryfyStreetAddress promise:

```
- (AnyPromise *)verifyStreetAddress:(SSStreetAddressRequest *)address {
    NSMutableDictionary *requestParams = [[NSMutableDictionary alloc] initWithDictionary:[address toDictionary]];
    [requestParams setObject:self.authID forKey:@"auth-id"];
    [requestParams setObject:self.authToken forKey:@"auth-token"];
    
    return [NSURLConnection GET:[self urlForEndpoint:SSServiceEndpointStreetAddresses] query:requestParams].then(^(NSArray *dataAR) {
        if (dataAR && [dataAR count] > 0) {
            NSDictionary *data = [dataAR firstObject];
            NSError *err;
            SSStreetAddressResponse *response = [[SSStreetAddressResponse alloc] initWithDictionary:data error:&err];
            
            if (err) {
                @throw err;
            }
            
            return response;

        } else {
            @throw [[NSError alloc] initWithDomain:@"SmartyStreetsFailure" code:0 userInfo:@{NSLocalizedDescriptionKey:@"Smartystreets API returned nothing"}];
        }
    });
}
```

**Comment by mxcl** [comment]
This chain looks fine.

I think it goes deeper: `PromiseKit: Pending Promise deallocated! This is usually a bug.` a promise is being deallocated before it resolves. If it is any of the promises before the `finally` the `finally` will never trigger, because it never receives a resolution.

What PromiseKit version and Xcode are you using?

**Comment by loryhuz** [comment]
I'm on ```PromiseKit 3.0.0``` and ```Xcode 7.0```

This bug only appear when I wrap chained non-promise async code into a ```promiseWithResolverBlock```

Or I missed that promiseWithResolverBlock can only wrap non chained block ?

Anyway, actually I'm trying to refactor all the DataController to use only promise and it's work fine for the few methods I've re-worked.

**Comment by mxcl** [comment]
> Or I missed that promiseWithResolverBlock can only wrap non chained block ?

Promises from `promiseWithResolverBlock` can be chained.

**Comment by mxcl** [comment]
If you can provide a test-case then we can reopen the bug. Without a test case it's just speculation. Thanks.
