### ISSUE TITLE
PromiseKit.h not found in compile phase

### ISSUE THREAD

**Issue by peres** [mxcl/PromiseKit#292]
I have been using PromiseKit for a while with little trouble, but I had to rebuild the framework since I was getting errors from iTunes Connect (using **swift-2.0-minimal-changes**).

So I rebuilt PromiseKit from **master** using Carthage, and got the usual OMGHTTPURL.framework and PromiseKit.framework under Carthage/Build/iOS. I then included both in my Xcode 7 project, but the compiler started complaining that it cannot `#import <PromiseKit/PromiseKit.h>`. The *Frameworks Search Paths* in my Build Settings contain the path of the built frameworks, and I tried various experiments by adding the frameworks to one of *Embedded Binaries* and *Linked Frameworks and Libraries*, too, but I got the same results.

I am building other frameworks using Carthage in the same project, and they work fine, so my first guess was that something broke after I switched to master, but stuff doesn't work anymore even after reverting back to the minimal-changes branch, not even in a dummy project.

**Comment by peres** [comment]
The framework switch had left a number of stale files in the build directories, which Xcode was picking up instead of the new versions. Once I deleted every possible reference to PromiseKit in the build directories, the problem went away. Sorry for the false alarm.

**Comment by mxcl** [comment]
It's depressing how common such issues our with our tools. Glad you sorted it out.
