### ISSUE TITLE
PromiseKit 3.0.0 depends on beta software

### ISSUE THREAD

**Issue by atheken** [mxcl/PromiseKit#293]
`OMGHTTPURLRQ` (3.0.1) contains support for tvOS, which is great. However, XCode 7.1 is still in beta, which means that in order to build PromiseKit 3.0.0 you'd need to build with XCode 7.1 due to the loose dependency on OMGHTTPURLRQ:

https://github.com/mxcl/PromiseKit/blob/master/Cartfile#L1

Not sure what the best process for handling "beta" requirements in "released" dependencies is, ideas?

Thanks for your awesome contributions, Max, which untold numbers of people have benefitted from.

**Comment by nathanhosselton** [comment]
Sorry about that. Should be fixed. Let me know if it isn't.

**Comment by atheken** [comment]
@nathanhosselton Thanks, not a problem. It looks like you deleted the 3.0.1 tag, which probably will resolve it, but I was able to just explicitly define my my Cartfile:

`github "mxcl/OMGHTTPURLRQ" "3.0.0"`

Which has the same effect, and everything is happy.

I appreciate your work on PromiseKit, it's a really helpful tool.
