### ISSUE TITLE
dispatch_promise that takes a closure of type: () throws -> Promise<T>

### ISSUE THREAD

**Issue by crazymaik** [mxcl/PromiseKit#295]
It would be great to have a 2nd dispatch_promise variant that can take a closure returning a Promise, similar to what has been done with Promise.then(). One can work around this by chaining with then, but shouldn't dispatch_promise provide the same functionality as then itself?

Thanks

**Comment by nathanhosselton** [comment]
From your description I'm having trouble seeing what purpose this would serve outside of the syntactic. Could you maybe provide an example?

**Comment by nathanhosselton** [comment]
Are you simply looking to `then` on a specific queue? If so, you can use `then(on:_:)`. (See [here](http://cocoadocs.org/docsets/PromiseKit/3.0.0/Classes/Promise.html#/s:FC10PromiseKit7Promise4thenu__rFGS0_q__FT2onPSo17OS_dispatch_queue_Fzq_qd___GS0_qd___))

**Comment by crazymaik** [comment]
I have quite a few blocks that look similar to this:

````
func doSomething(param0: String) -> Promise<String> {
    return dispatch_promise(on: queue) {
        if someCheck(param0) {
             throw MyError
        }
    }.then(on: queue) {
        return self.obj.doActualWork(param0)
    }
}
````

The `if` block and `self.obj.doActualWork` belong to each other. They are tied to each other. Having the additional line with `}.then(on: queue) {` adds a mental separation where none should be.

Furthermore, the code should run as one atomic action on `queue`, which is not possible if the additional `then` is necessary.

**Comment by mxcl** [comment]
I don't have a problem with this. I think the reason it is not there is swift compiler bugs. 

Though the specific example could be written without dispatch_promise IMO

**Comment by mxcl** [comment]
The bugs I refer to are probably fixed.

**Comment by crazymaik** [comment]
Still new to PromiseKit. Would this be the way to go then?

````
return Promise().then(on: queue) {
    ....
}
````

I initially thought that init() is not exposed.

**Comment by mxcl** [comment]
I'd have written:

```swift
func doSomething(param0: String) -> Promise<String> {
    guard someCheck(param0) else {
         return Promise(error: MyError)
    }
    return dispatch_promise(on: queue) {
        return self.obj.doActualWork(param0)
    }
}
```

Which is still using `dispatch_promise`, but it doesn't unnecessarily dispatch for the error condition.

**Comment by excaliburnan** [comment]
Hi I am new to Swift and PromiseKit as well. Here is an error when I am trying to use dispatch_promise.
" Cannot invoke 'dispatch_promise' with an argument list of type '(() throws ->())' ". It may related to this issue, can someone give me a hand, thx in advance :)

**Comment by mxcl** [comment]
@excaliburnan this is off topic. If you want help open a new ticket please with the line of code that you are having trouble with included. Thanks.

**Comment by mxcl** [comment]
Honestly, this seems a little pointless, unless you can give me a good example? Because all I can think of is:

```swift
dispatch_promise { 
    return login()
}
```

Which is pretty much pointless unless the instantiation of the login promise is truly intimidating in work load.

Will reopen if there's an example! 👍🏻
