### ISSUE TITLE
Cant cancel a promise

### ISSUE THREAD

**Issue by LukeDefeo** [mxcl/PromiseKit#296]
Using swift if that matters

So i have created my own promise wrapping Alamofire

I kick of my promise specifying what to do when it sucessful/fails in my closure etc. all great, love it so far.

However i have a reference to this promise but i want to be able to cancel it, like this 

promise.cancel()

You might want to do this when the user say leaves a screen where that promise is needed.

Under the hood the implementer of the promise would also have to implement this in the promise constructor and define what cancelation would mean for each type of task/promise.

Eg for a network operation you would cancel the underlying task.

**Comment by LukeDefeo** [comment]
Im not sure what cancelling a promise would mean in terms of its completion, i could call error() and pass a flag to say if was cancel or maybe it would just fall through to always as we probably dont want to do any error handling if we programatically cancel

**Comment by mxcl** [comment]
Since PromiseKit 2 we support the idea of cancellation, it is a special ErrorType, CancellableErrorType. We on’t provide an explicit mechanism to cancel a promise, instead this left as an implementation detail for the author of the Promise. More details [here](http://promisekit.org/PromiseKit-2.0-Released/).

**Comment by LukeDefeo** [comment]
Ive read that but i cant see how i support it, particually in Swift, The construct only takes two closures, fulfill and reject.

Do you have any samples of what i should do, will i need a subclass of Promise<T>?

**Comment by LukeDefeo** [comment]
One other thing it looks like the way to cancel a promise from the consumer side is 

'then(^{
    @throw [NSError cancelledError];
})'

Is there any equivalent for swift?

**Comment by mxcl** [comment]
You don't have to subclass Promise, though it is certainly one option. Here's a functional example:

```swift
enum Error: ErrorType, CancellableErrorType {
    case MyCancellableError
}

func someCancellablePromise() -> (Promise, () -> Void) {

    let (promise, fulfill, reject) = Promise.pendingPromise()
    func cancel() {
        reject(Error.MyCancellableError)
    }
    
    // stuff…
    
    return (promise, cancel)
}


let (promise, cancel) = someCancellablePromise()
cancel()
```

Thus you can see how the consumer is cancelling the promise.

**Comment by LukeDefeo** [comment]
Thanks thats brilliant, i need to learn how to write more functional, do you have any suggestions? You can probably close this now. 

Cheers

**Comment by ScheerMT** [comment]
This exact example may be worthwhile to include in the documentation... Thoughts?

**Comment by LukeDefeo** [comment]
Yeah also the documentation is confusing as it references some deprecated function. If you like I could make a pr to fix the inline docs in the code

Cheers

Luke

**Comment by mxcl** [comment]
PR for the docs is welcome. I would do it myself but am legally unable currently.

**Comment by LukeDefeo** [comment]
Hi could you elaborate on this please max, I am trying to convince my team to use this library but if its main contributor can't work on it then that's not going to fly . Is it a temporary thing, Will you be able to work on it in the future.

Cheers

Luke

**Comment by nathanhosselton** [comment]
@LukeDefeo I'll let Max speak to the time frame (if he can), but in the interim, I will be performing all high priority updates and maintenance. So the library will not be abandoned.

**Comment by mxcl** [comment]
The library is complete. It's in maintenance mode. Nathan is more than capable of maintaining it and I am allowed to advise him. The situation is temporary. Though I have no timescale for when it will change.

It's because I joined Apple and they are very strict about outside work.

**Comment by mxcl** [comment]
I will continue to be available here in the tickets whatever happens.
