### ISSUE TITLE
Unable to install 3.0.0 through cocopods

### ISSUE THREAD

**Issue by ScheerMT** [mxcl/PromiseKit#297]
Not sure whats going on... When I include ``` pod "PromiseKit"``` in my Podfile I get the 2.2.x version. When I try to force it the 3.0.0 using ```pod "PromiseKit", "~> 3.0.0"``` then run ```pod install``` (after uninstalling) I get this:
```bash
Updating local specs repositories

CocoaPods 0.39.0.rc.1 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `PromiseKit (~> 3.0)` required by `Podfile`

[!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`
```

My Podfile when trying to install the 3.0 version is as follows:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

...

pod "PromiseKit", "~> 3.0.0"
```

SO/closed issues haven't reported anything similar.. not really sure whats going on.

**Comment by renatorodrigues** [comment]
Remove the `master`repo and then install the pods:
```
sudo rm -fr ~/.cocoapods/repos/master
pod setup

**Comment by ScheerMT** [comment]
What would be the benefit of removing the master repo?

I did get this working by instead pointing directly to the repo here on github and it compiled just fine.. Swift 2 and Xcode 7

**Comment by mxcl** [comment]
> What would be the benefit of removing the master repo?

If you delete the local cache it will probably fix your issue.

By pointing it directly at the repo it bypassed the CocoaPods local cache.

**Comment by renatorodrigues** [comment]
Like @mxcl said, removing the master repo will simply delete the local cache. No harm done by doing it.

**Comment by ScheerMT** [comment]
Thank you for explaining that to me! I haven't tried this yet but will soon. I will report back if I have any problems
