### ISSUE TITLE
Sealed promise not waiting for the finally clause in a previous sealed promise

### ISSUE THREAD

**Issue by o15a3d4l11s2** [mxcl/PromiseKit#300]
Currently if we chain a sealed promise, containing a .finally clause with another sealed promise, then the execution of the second promise will start immediately after the last .then clause of the first promise.

**Comment by mxcl** [comment]
Please provide sample code for this.

**Comment by mxcl** [comment]
From what I could discern from your description I made this and you can see the order is as expected:

![screen shot 2015-10-25 at 12 10 41 pm](https://cloud.githubusercontent.com/assets/58962/10717322/70814a6e-7b11-11e5-919f-1816ea580a21.png)

Did I understand wrongly?

**Comment by o15a3d4l11s2** [comment]
I am currently using PromiseKit 3 and Xcode 7.1

What I actually refer to is the `finally` clause.
I am also including a code to show what is my point. In short - there is no guarantee that the `finally` clause of `getUsers` will be finished before the next promise `getMessagesForUsers` start execution.

The case that I describe is that we should create a token which is used to execute a query and then destroy it. If the finally logic is not executed on time, the next `createToken` will fail, as the server already has a token created.

```
- (AnyPromise *)getUsers
{
    __block NSString *serverToken = nil;
    
    return [AnyPromise promiseWithResolverBlock:^(PMKResolver  _Nonnull resolve) {
        [self createTokenOnServer:^(NSString *token) {
            serverToken = token;
            resolve(token);
        }];
    }].then(^(NSString *token) {
        return [self fetchServerUsersUsingToken:token];
    }).finally(^{
        if (serverToken) {
            [self destroyToken:serverToken];
        }
    });
}

- (AnyPromise *)getMessagesForUsers:(NSArray *)users
{
    __block NSString *serverToken = nil;
    
    return [AnyPromise promiseWithResolverBlock:^(PMKResolver  _Nonnull resolve) {
        [self createTokenOnServer:^(NSString *token) {
            serverToken = token;
            resolve(token);
        }];
    }].then(^(NSString *token) {
        return [self fetchServerMessagesForUsers:users usingToken:token];
    }).finally(^{
        if (serverToken) {
            [self destroyToken:serverToken];
        }
    });
}

- (AnyPromise *)doTheWork
{
    return [self getUsers].then(^(NSArray *users) {
        [self getMessagesForUsers:users];
    });
}
```

I am doing this whole logic, because I should follow the rules on the server - to create a token, use it for one request only and then destroy it. If there is any other mechanism to achieve this logic, please advise.

**Comment by mxcl** [comment]
I just wrote this test that proves the finally finishes before any subsequent executions can run:

![screen shot 2015-10-27 at 9 55 44 pm](https://cloud.githubusercontent.com/assets/58962/10779984/7d3c00ce-7cf5-11e5-9ceb-747c3c7a6f79.png)

Can you provide a test project that demonstrates your bug?

**Comment by mxcl** [comment]
Is your problem that you are not returning `[self destroyToken:serverToken];`?

Because then that asynchronous operation will not have completed before `getMessagesForUsers` runs.

Perhaps you want:

```objc
- (AnyPromise *)getUsers
{
    __block NSString *serverToken = nil;

    return [AnyPromise promiseWithResolverBlock:^(PMKResolver  _Nonnull resolve) {
        [self createTokenOnServer:^(NSString *token) {
            serverToken = token;
            resolve(token);
        }];
    }].then(^(NSString *token) {
        return [self fetchServerUsersUsingToken:token];
    }).finally(^id{
        if (serverToken) {
            return [self destroyToken:serverToken];
        } else {
            return nil;
        }
    });
}
```

**Comment by o15a3d4l11s2** [comment]
Probably what you mention is the exact cause of the problem - that I am not returning anything from the `finally` block.
With the current version that I use - PromiseKit 3 there is an error if I try to return a result from the `finally`:
```Incompatible block pointer types passing 'id (^)(void)' to parameter of type 'dispatch_block_t  _Nonnull __strong' (aka 'void (^__strong)(void)')```

**Comment by o15a3d4l11s2** [comment]
Since the declaration is `(AnyPromise *(^)(dispatch_block_t))finally`, the finally clause returns `void`. Is there something that I am missing here? How is it possible to return something from the `finally`?

**Comment by mxcl** [comment]
Indeed, you cannot. I’m not sure why I thought this feature existed. The reason it does not is this:

```objc
somePromise1.then(^{
   return @1;
}).finally(^{
    // can't interfere with chain
}).then(^(id obj){
   // obj is @1
});
```

`finally` is for book-keeping, it just passes through the `@1` and thus can't interfere with the chain. If we made it possible to wait on a promise it would introduce ambiguity. Does the promise influence subsequent then values? If not does that mean that users must always manually pipe the value in future?

**Comment by mxcl** [comment]
Still I don't think it is necessarily what you want, you want to ensure create always follows a destroy, so really you need to do something like this:

```objc
- (AnyPromise *)getUsers
{
    __block NSString *serverToken = nil;
    __block static AnyPromise *destroy = [AnyPromise promiseWithValue:@1];

    return [AnyPromise promiseWithResolverBlock:^(PMKResolver  _Nonnull resolve) {
        destroy.finally(^{
            [self createTokenOnServer:^(NSString *token) {
                serverToken = token;
                resolve(token);
            }];
        });
    }].then(^(NSString *token) {
        return [self fetchServerUsersUsingToken:token];
    }).finally(^id{
        if (serverToken) {
            destroy = [self destroyToken:serverToken];
        }
    });
}
```

**Comment by o15a3d4l11s2** [comment]
Actually my case is even trickier - destroy should always happen if a token was successfully created, but not before executing the real request - i.e. `fetchServerUsersUsingToken`. If the destroy happens before the request - the token actually does not exist anymore on the server.

I though for a different scenario:
1. Create the token
`then`
2. Make the request with the token
`then`
3. Destroy the token, passing through the previous token result (the result from 2)
`then`
4. Do anything additional

The only drawback of this logic is that the destroy might not get called if 2. fails

**Comment by mxcl** [comment]
This is not elegant, but without a better idea of how to approach API for the pattern, this is what we have:

```objc
return [AnyPromise promiseWithResolverBlock:^(PMKResolver resolve) {
    [self createToken].then(^(id token){
        AnyPromise *requestPromise =  [self makeRequest:token]
        requestPromise.finally(^{
             [self destroyToken:token].finally(^{ resolve(requestPromise.value) });
        });
    });
}];
```

**Comment by o15a3d4l11s2** [comment]
Thanks you for the good idea. Although not very elegant, it will be sufficient for my needs.
