### ISSUE TITLE
More love for PMKHang

### ISSUE THREAD

**Issue by dbachrach** [mxcl/PromiseKit#308]
We are building a Top Shelf TV extension and are implementing the `- (NSArray*)topShelfItems` method. This method is encouraged to make network calls and block until they finish, at which point you can then return an array of `TVContentItem`s.

All of our networking calls go through PromiseKit, so I wrap our promise that does this work around PMKHang and return the result.

This seems like a safe and valid use-case for PMKHang. You can make a reasonable argument that the `TVTopShelfProvider` should have been designed to take an async completion block, but no luck.

Should we soften the warnings in the PMKHang header?

**Comment by mxcl** [comment]
I'm not convinced our implementation in `PMKHang` is safe, it may lead to deadlocks. Use with caution.
