### ISSUE TITLE
Tapping on PMKAlertController button does not trigger action

### ISSUE THREAD

**Issue by MrAdamBoyd** [mxcl/PromiseKit#309]
I'm using this exact code from the `PMKAlertController.swift` file. Here's the code:
```Swift
let alert = PMKAlertController("OHAI")
let sup = alert.addActionWithTitle("SUP")
let bye = alert.addActionWithTitle("BYE")
promiseViewController(alert).then { action in
     //Print regardless of button push
    print("Button pushed")
}
```

However, no button push results in the code inside the `then` statement being triggered. I believe there's some sort of problem with how PMKAlertControllers are being shown. For example, replacing the last 4 lines above with:
```Swift
promiseViewController(alert, animated: true, completion: { () -> Void in
    print("Presented")
}).then { action in
    print("Button tapped")
}
```
triggers no print statement at all. If I were to replace the `PMKAlertController` with a `UIImagePickerController`, for example, it works:
```Swift
let picker = UIImagePickerController()    
promiseViewController(picker, animated: true, completion:  { () -> Void in
    print("Presented")
}).then { image in ... }

//Results in "Presented" being printed
```

I'm using Xcode 7.1, Swift 2.1.

**Comment by mxcl** [comment]
Possibly the runtime is using the wrong overload of promiseViewController.

**Comment by MrAdamBoyd** [comment]
Actually, I believe I found a bug. I submitted a pull request [here](https://github.com/mxcl/PromiseKit/pull/310). Basically, what is happening now is that only the Cancel button is fulfilling the promise, whereas all other buttons are rejecting it. I reversed that.

**Comment by MrAdamBoyd** [comment]
I closed my pull request because I realized this fix is already a waiting pull request. [Link](https://github.com/mxcl/PromiseKit/pull/303).
