### ISSUE TITLE
PromiseKit 3.0: chaining with loops

### ISSUE THREAD

**Issue by stanchiang** [mxcl/PromiseKit#312]
I'm using promisekit 3.0 to help chain alamofire callbacks in a clean way. The objective is to start with a network call, with a promise to return an array of urls.

Then, I'm looking to execute network calls on as many of those urls as needed to find the next link i'm looking for. As soon as this link is found, I can pass it to the next step.

This part is where I'm stuck.

I can pick an arbitrary index in the array that I know has what I want, but I can't figure out the looping to keep it going until the right information is returned.

I tried learning from this obj-c example, but i couldn't get it working in swift.

http://stackoverflow.com/a/30693077/1079379

He's a more tangible example of what i've done.

Network.sharedInstance.makeFirstPromise(.GET, url: NSURL(string: fullSourceLink)! )
.then {  (idArray) -> Promise<AnyObject> in
    let ids = idArray as! [String]

    //how do i do that in swift? (from the example SO answer)
    //PMKPromise *p = [PMKPromise promiseWithValue: nil]; // create empty promise

    //only thing i could do was feed it the first value
    var p:Promise<AnyObject> = Network.sharedInstance.makePromiseRequestHostLink(.POST, id: ids[0])

    //var to hold my eventual promise value, doesn't really work unless i set it to something first
    var goodValue:Promise<AnyObject>

    for item in ids {
        //use continue to offset the promise from before the loop started
        continue

        //hard part
        p = p.then{ returnValue -> Promise<AnyObject> in

            //need a way to check if what i get is what i wanted then we can break the loop and move on
            if returnValue = "whatIwant" {
                goodvalue = returnValue
                break
            //or else we try again with the next on the list
            }else {
                return Network.sharedInstance.makeLoopingPromise(.POST, id: item)
            }
        }
    }
    return goodValue
}.then { (finalLink) -> Void in
    //do stuck with finalLink
}
Can someone show me how to structure this properly, please?

Is nesting promises like that anti-pattern to avoid? In that case, what is the best approach.

**Comment by stanchiang** [comment]
fixed with "when"

**Comment by mxcl** [comment]
`when` waits for all the promises to succeed. Sounds like you want `race` which succeeds as soon as one of the promises succeeds.

**Comment by stanchiang** [comment]
oh cool. thanks! where would i look to see all my available options when picking functions like this?

**Comment by mxcl** [comment]
http://cocoadocs.org/docsets/PromiseKit/3.0.0
