### ISSUE TITLE
 Library not loaded

### ISSUE THREAD

**Issue by huchenqiang90** [mxcl/PromiseKit#315]
I use the framwork by pod,but get this error:

dyld: Library not loaded: @rpath/OMGHTTPURLRQ.framework/OMGHTTPURLRQ
  Referenced from: /private/var/mobile/Containers/Bundle/Application/4719D6A6-EB97-4928-8A53-31E1CD421914/uit.app/Frameworks/fTest.framework/fTest
  Reason: image not found

here is the code
+ (AnyPromise *)loadDriver{

    return [AnyPromise promiseWithResolverBlock:^(PMKResolver  _Nonnull resolve) {
        
        
        NSLog(@"AnyPromise promiseWithResolverBlock");
    }];

}

**Comment by mxcl** [comment]
This is a project setup error, not a code issue.

It's hard to help without a lot more information, what targets to you have, what is in your Podfile? iPhone app? Mac app? tvOS app?

**Comment by huchenqiang90** [comment]
iPhone framework

可用于iOS的myMail发送


2015年11月6日 星期五 +0800 上午11:44 发件人 Max Howell  <notifications@github.com>:
