### ISSUE TITLE
Conversion issue with 3.0, when and Swift

### ISSUE THREAD

**Issue by adampilks** [mxcl/PromiseKit#316]
Pretty new to swift so this could be pretty simple, but am struggling to get a simple `when` working with 2 custom functions that return promises.  They have the following signatures:

```
func a() -> Promise<Bool> { }
func b() -> Promise<Void> { }

when(a(), b()) { aResponse, bResponse in 

}
```

I get `Cannot convert value of type 'Promise<Bool>' to expected argument type 'Promise<_>'`

Any pointers?

**Comment by mxcl** [comment]
Works for me:

![screen shot 2015-11-05 at 7 42 26 pm](https://cloud.githubusercontent.com/assets/58962/10988881/6812102e-83f5-11e5-944c-4a289735ed4f.png)

**Comment by adampilks** [comment]
Think I missed the `then`... had to be something simple :), thanks for your help
