### ISSUE TITLE
PromiseKit breaks @objc(ClassName)

### ISSUE THREAD

**Issue by hartbit** [mxcl/PromiseKit#318]
PromiseKit breaks @objc(ClassName) swift modifier because of redefined SWIFT_MACRO in PromiseKit. Here is an example project:

https://dl.dropboxusercontent.com/u/7272802/TestingBridge.zip

**Comment by hartbit** [comment]
Found the problem:

* PromiseKit redefines SWIFT_CLASS but not SWIFT_CLASS_NAMED
* Project-Swift.h checks defined(SWIFT_CLASS) before defining both
* So if PromiseKit is imported before Project-Swift.h (as instructed), SWIFT_CLASS_NAMED never gets defined.

I'm preparing a Pull Request with a fix.

**Comment by mxcl** [comment]
Merged: a334234d4248637dbe419b1d6dd7820abc45b75c
