### ISSUE TITLE
Inverted condition in PMKAlertController

### ISSUE THREAD

**Issue by alexd6631** [mxcl/PromiseKit#320]
Hello,

The condition seems flipped in :
https://github.com/mxcl/PromiseKit/blob/master/Categories/UIKit/PMKAlertController.swift#L43

**Comment by mxcl** [comment]
Looks correct to me.

**Comment by alexd6631** [comment]
Seems it was fixed by this commit : https://github.com/mxcl/PromiseKit/commit/cc91705174a4f331b24ebb22fcd12f03f16776e3
