### ISSUE TITLE
iOS PromiseKit.framework missing from 2.2.2 pre-built binaries

### ISSUE THREAD

**Issue by samsonjs** [mxcl/PromiseKit#322]
There is iOS/PromiseKit.framework.dSYM but not the framework itself.

**Comment by hongkongkiwi** [comment]
Agreed with this, seems like a bug.

**Comment by mxcl** [comment]
I have removed the pre-built binaries as it is foolish to build them since Swift ABI is not stable so every Xcode release they will be invalid.
