### ISSUE TITLE
How do you access the status code of a URLError BadResponse error?

### ISSUE THREAD

**Issue by swaffoja** [mxcl/PromiseKit#324]
I'm trying to understand error handling for a URLError BadResponse in the Swift version of PromiseKit 3.0. I have an API that is intentionally returning a 404 response. Example:
    
    firstly {

        return NSURLSession.POST("http://localhost:9000/api/", formData: ["foo":"bar"])

    }.then { (data: NSData) -> Void in

        // process data

    }.error { error in

        // handle error based on http status code: 403, 404, etc...
        // how can I get status code from "error"?
        print(error)
        print(error.dynamicType)
    }

Printing "error" shows this in Xcode debug console:

    BadResponse(<NSMutableURLRequest: 0x7fa51a7bd8e0> { URL: http://localhost:9000/api/ }, Optional(<3c3f786d 6c207665 7273696f 6e3d2231 2e302220 656e636f 64696e67 3d225554 462d3822 203f3e3c 68617368 3e3c6572 726f723e 636f756c 64206e6f 74206669 6e642073 74756479 20617364 663c2f65 72726f72 3e3c2f68 6173683e>), Optional(<NSHTTPURLResponse: 0x7fa51a7f64f0> { URL: http://localhost:9000/api/ } { status code: 404, headers {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-store, no-cache, must-revalidate";
    Connection = "Keep-Alive";
    "Content-Length" = 92;
    "Content-Type" = "; charset=utf-8";
    Date = "Tue, 17 Nov 2015 14:49:24 GMT";
    Expires = 0;
    "Keep-Alive" = "timeout=5, max=100";
    Pragma = "no-cache";
    Server = Apache;
    "X-Powered-By" = "PHP/5.6.10";
    } }))

How would I get the 404 status code from the error using swift?

**Comment by nathanhosselton** [comment]
The NSHTTPURLResponse object is one of the keys in the error's `userInfo` dictionary and contains the status code. I believe you can access it like so:

```swift
let response: NSHTTPURLResponse = error.userInfo[PMKURLErrorFailingURLResponseKey]
print(response.statusCode)
```
But I have not done this in Swift, so let me know if this doesn't work.

**Comment by swaffoja** [comment]
That gave a complier error `Value of type 'ErrorType' has no member 'userInfo'` but I think it set me down the correct track. I have been able to get the statusCode using this:

    if let response: URLError = error as? URLError {
        print(response.NSHTTPURLResponse.URL)
        print(response.NSHTTPURLResponse.statusCode)
        print(response.NSHTTPURLResponse.allHeaderFields)
    }

    // ALTERNATIVELY

    switch error {
        case let response as URLError:
            print(response.NSHTTPURLResponse.statusCode)
            print(response.NSHTTPURLResponse.statusCode)
            print(response.NSHTTPURLResponse.allHeaderFields)
        default:
            print(error.dynamicType)
    }


However, I haven't been able to figure out how to get the body of the response yet. `Error.swift` seems to show that URLError BadResponse knows about the body (i.e. NSData?) but doesn't seem to make it accessible:

    case BadResponse(NSURLRequest, NSData?, NSURLResponse?)


Any thoughts on how to get the body? Thanks for the help!

**Comment by swaffoja** [comment]
"Enumeration > Associated Values" documentation for Swift showed me the correct syntax.
    
    switch error {
    case URLError.InvalidImageData(let request, let data):
        print("\(request) \(data)")
        
    case URLError.UnderlyingCocoaError(let request, let data?, let response?, let nserror):
        print("\(request) \(data) \(response) \(nserror)")
        
    case URLError.BadResponse(let request, let data?, let response?):
        print("\(request) \(data) \(response)")

    case URLError.StringEncoding(let request, let data, let response):
        print("\(request) \(data) \(response)")
        
    default:
        print(error.dynamicType)
    }

https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Enumerations.html#//apple_ref/doc/uid/TP40014097-CH12-ID148
