### ISSUE TITLE
Include full or no license-text in podspec

### ISSUE THREAD

**Issue by tomquist** [mxcl/PromiseKit#327]
Currently the podspec directs to the README file:

    s.license = { :type => 'MIT', :text => '@see README' }

however, if you want to use CocoaPods auto-generated acknowledgement files `Pods-acknowledgements.markdown` or `Pods-acknowledgements.plist` this is suboptimal because it only contains '@see README' which makes the whole acknowledgement file unusable.

Instead, simply remove the `:text`part and add a dedicated `LICENSE` file.

**Comment by mxcl** [comment]
I have changed it to a url to the README.

**Comment by tomquist** [comment]
This isn't better as the previous solution. Now the acknowledgement plist will contain a URL but the MIT licence requires inclusion of the full licence text:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

So people using PromiseKit will not be able to use the auto-generated acknowledgement plist.

**Comment by mxcl** [comment]
I wish I'd just gone with a license without restrictions.
