### ISSUE TITLE
Cannot use free functions from Objective-C++

### ISSUE THREAD

**Issue by peres** [mxcl/PromiseKit#330]
No linkage is specified for free functions (e.g. dispatch_promise_on), so the linker cannot know if they are C or C++.

A workaround is to wrap the #import statement in your Objective-C++ file:
```
extern "C" {
    #import <PromiseKit/PromiseKit.h>
}
```

**Comment by nathanhosselton** [comment]
Thanks for this. Is there some way that PromiseKit could be cleanly updated to resolve this problem that you know of, or should this workaround simply be included in the documentation?

**Comment by peres** [comment]
Since everybody is meant to include PromiseKit.h, it should be enough to wrap its contents like below. This is by the way what my workaround does, except that it's in client Objective-C++ code, and thus doesn't need the #ifdef guards.

````
#if __cplusplus
extern "C" {
#endif

// Regular contents of PromiseKit.h go here.

#if __cplusplus
}   // Extern C
#endif
````

**Comment by nathanhosselton** [comment]
Seems simple enough. If you'd like to submit a PR I will merge. Otherwise I will include this with the next round of updates. Thanks again for pointing this out.
