### ISSUE TITLE
Carthage can't build PromiseKit 3.0

### ISSUE THREAD

**Issue by beingadrian** [mxcl/PromiseKit#331]
It seems to me that the tests are missing OHHTTPStubs which causes the Carthage build to fail (specifically the testNSURLSession Swift file). Any way I can fix this?

**Comment by rlaferla** [comment]
+1  I can't build any versions 2.1, 2.2 or 3.0 using Carthage

**Comment by beingadrian** [comment]
@rlaferla this worked for me (might work for you if you're developing specifically for iOS)

```
carthage build --platform iOS 
````

**Comment by rlaferla** [comment]
I think I tried that but ended up using the CocoaPod.

**Comment by beingadrian** [comment]
@rlaferla Ah, alas. Whatever works for you :+1:
