### ISSUE TITLE
Turn off warning about "Pending Promise deallocated! This is usually a bug"

### ISSUE THREAD

**Issue by rbobbins** [mxcl/PromiseKit#332]
In my tests, I frequently create pending promises. Unless I'm explicitly testing what happens when the promise is fulfilled or rejected, I don't resolve these promises. They stay in the pending state.

Thus, it's not a bug when these promises get deallocated. The warning about `PromiseKit: Pending Promise deallocated! This is usually a bug` is not misleading/not useful. It would be great if there was a way to silence this warning (or get rid of it entirely!).

**Comment by ehuynh** [comment]
I have a question regarding whether not fulling a promise is a practise used often? For example if I was using a promise to replace a delegate pattern on a view where the delegate indicated what item was selected. If I present that view and then it is dismissed with no item is selected, then that promise would go unfulfilled. Is this considered a correct use case for promises? Only wondering as right now, I'm getting the same warning message.
```
PromiseKit: Pending Promise deallocated! This is usually a bug
```

**Comment by nathanhosselton** [comment]
In cases where it makes sense, promises should always be resolved. In @ehuynh's example, I would argue that the user dismissing the view without selection is 'cancellation' and therefore the promise should be rejected with `cancelledError()`. However, I understand that there may be situations where there is no logical flow towards promise resolution, so for these cases I agree that there should be a mechanism for silencing the warnings. At this time I'm not sure what that would look like though. Ideas and PRs welcome.

**Comment by ehuynh** [comment]
@nathanhosselton thanks for that. Didn't realise you can cancel a promise with an error that won't be caught. Maybe thats something that can be added to the documentation?

**Comment by mxcl** [comment]
@ehiynh it is documented at PromiseKit.org

**Comment by mxcl** [comment]
I have added a new feature to 4.0 allowing you to define `PMKDisableWarnings` to remove this warning.

**Comment by mcfedr** [comment]
This warning comes up when using `race` as well, is there any way it could be avoid for that specific use?

**Comment by mxcl** [comment]
It shouldn't come up for race. If it does it is literally a bug (IME). The promises should be retained by the tasks that they represent until the tasks are complete, if it is only race that is holding them then it is a bug.

**Comment by mcfedr** [comment]
Ah, interesting, I had better investigate further.

**Comment by basememara** [comment]
Leaving promises unresolved are generally bad practice and a sign to code smell. Even if you don't need to resolve promises, `always` and other API's will not fire as expected if you leave things unresolved which can lead to several bugs.
