### ISSUE TITLE
Chaining promises leads to `PromiseKit: Pending Promise deallocated! This is usually a bug`

### ISSUE THREAD

**Issue by zaneclaes** [mxcl/PromiseKit#333]
When I invoke the `loadObject` function below, I get `PromiseKit: Pending Promise deallocated! This is usually a bug`

The backtrace reveals that it's being triggered by the `fulfill(snapshot)` in the `loadSnapshot`. This suggests that the `loadSnapshot` promise is being deallocated.

I have read this thread: https://github.com/mxcl/PromiseKit/issues/273 however it does not apply to me, because I cannot use `when` due to the fact that the 2nd promise is dependent upon the first promise, and they therefore need to be chained.
```
/**
   * Uses loadSnapshot to infer and create a GameObject
   * In GameObject land, an ID is a path
   * Therefore, we can separate on the `/` character and infer
   * the type of class to use to instantiate the object.
   */
  static func loadObject(id: String!) -> Promise<Void> {
    if self.promiseObjects[id] == nil {
      DDLogInfo("Loading Object \(id)")
      promiseObjects[id] = loadSnapshot(id).then { (snapshot) -> Promise<Void> in
        return GameObject.factory(id, snapshot: snapshot)
      }.then { () -> Void in
        promiseObjects.removeValueForKey(id)
      }
    }
    return promiseObjects[id]!
  }
  /**
   * Given a path to a firebase object, get the snapshot with a timeout.
   */
  static func loadSnapshot(firebasePath: String!) -> Promise<FDataSnapshot> {
    return Promise { fulfill, reject in
      after(life: Config.timeout).then {
        reject(Errors.network)
      }

      let connection = Firebase(url: Config.firebaseUrl + firebasePath)
      connection.observeEventType(.Value, withBlock: { snapshot in
        connection.removeAllObservers()
        fulfill(snapshot)
      })
    }
  }
```

<img width="1083" alt="screen shot 2015-12-01 at 10 54 53 am" src="https://cloud.githubusercontent.com/assets/2084821/11510838/8127eeba-981a-11e5-858e-b936ac926879.png">

**Comment by bbqbaron** [comment]
`loadSnapshot` is returning a Promise whose execution block dispatches two further async processes, one of them a Promise. If the `fulfill` condition in `observeEventType` completes first, won't the Promise returned by `after` be deallocated before resolution? What if you `race` the `after` and a Promise that only contains the call to `observeEventType`? I haven't used `race`, but the doc suggests that it's the whoever-resolves-first condition that you want.

**Comment by zaneclaes** [comment]
@bbqbaron this was a pattern for timeouts I copied from elsewhere (and the problem persists if I remove the `after`). What's more, I use the `loadSnapshot` function many other places in the code without any problems. The problem ended up being that the `GameObject.factory` had a `when()` call that could be fired with an empty array. Apparently, `when([])` leads to the error above.
