### ISSUE TITLE
when/always/error like README example yields XCode error

### ISSUE THREAD

**Issue by rlaferla** [mxcl/PromiseKit#334]
This project needs more working examples.  Using the example in the readme, I tried to create something similar but I'm getting this error:

Missing return in a closure expected to return 'AnyPromise'

I am using the CocoaPods version of PromiseKit.  Feel free to use this code as an example if you can fix it.

```
import Foundation
import UIKit
import PromiseKit

class ViewController: UIViewController {    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        UIApplication.sharedApplication().networkActivityIndicatorVisible = true
        
        when(getUsers(), getPhotos(), getComments()).then { (userData, photoData, commentData) -> AnyPromise in
            let json = JSON(data: userData)
            print("\(json[0]["name"])")
        }.always {
            UIApplication.sharedApplication().networkActivityIndicatorVisible = false

            }.error { error in
        }
        
        self.getUsers().then { (data:NSData) -> Void in
            let json = JSON(data: data)
            print("\(json[0]["name"])")
            }.then {
                self.getPhotos().then { (data:NSData) -> Void in
                    let json = JSON(data: data)
                    print("\(json[0]["title"])")
                    }.then {
                        self.getComments().then { (data:NSData) -> Void in
                            let json = JSON(data: data)
                            print("\(json[0]["name"])")
                        }
                }
        }
    }
    
    func getUsers() -> URLDataPromise {
        return NSURLConnection.GET("http://jsonplaceholder.typicode.com/users")
    }
    
    func getPhotos() -> URLDataPromise {
        return NSURLConnection.GET("http://jsonplaceholder.typicode.com/photos")
    }
    
    func getComments() -> URLDataPromise {
        return NSURLConnection.GET("http://jsonplaceholder.typicode.com/comments")
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    
}


    
```

**Comment by swaffoja** [comment]
Here's how I would write it. If you don't want to use `firstly` then I can rewrite it without... I just really like how it reads.

    import Foundation
    import UIKit
    import PromiseKit
    import SwiftyJSON

    class ViewController: UIViewController {
        override func viewDidLoad() {
            super.viewDidLoad()
            // Do any additional setup after loading the view, typically from a nib.

            UIApplication.sharedApplication().networkActivityIndicatorVisible = true

            firstly {

                return when(getUsers(), getPhotos(), getComments())

            }.then { (userData: NSData, photoData: NSData, commentData: NSData) -> Void in

                let userJson = JSON(data: userData)
                print(userJson)

            }.always {

                UIApplication.sharedApplication().networkActivityIndicatorVisible = false

            }.error { error in

                print(error)

            }

        }

        func getUsers() -> URLDataPromise {
            return NSURLConnection.GET("http://jsonplaceholder.typicode.com/users")
        }

        func getPhotos() -> URLDataPromise {
            return NSURLConnection.GET("http://jsonplaceholder.typicode.com/photos")
        }

        func getComments() -> URLDataPromise {
            return NSURLConnection.GET("http://jsonplaceholder.typicode.com/comments")
        }

        override func didReceiveMemoryWarning() {
            super.didReceiveMemoryWarning()
            // Dispose of any resources that can be recreated.
        }


    }

**Comment by swaffoja** [comment]
Here is a version that shows you chaining...

    import Foundation
    import UIKit
    import PromiseKit
    import SwiftyJSON

    class ViewController: UIViewController {
        override func viewDidLoad() {
            super.viewDidLoad()
            // Do any additional setup after loading the view, typically from a nib.

            UIApplication.sharedApplication().networkActivityIndicatorVisible = true

            firstly {

                return getUsers()

            }.then { (userData: NSData) -> NSData in

                let userJson = JSON(data: userData)

                return getPhotos()

            }.then { (photoData: NSData) -> NSData in

                let photoData = JSON(data: photoData)

                return getComments()

            }.then { (commentData: NSData) -> Void in

                let commentData = JSON(data: commentData)

                // Not returning anything, so closure returns Void... not AnyPromise

            }.always {

                UIApplication.sharedApplication().networkActivityIndicatorVisible = false

            }.error { error in

                print(error)

            }

        }

        func getUsers() -> URLDataPromise {
            return NSURLConnection.GET("http://jsonplaceholder.typicode.com/users")
        }

        func getPhotos() -> URLDataPromise {
            return NSURLConnection.GET("http://jsonplaceholder.typicode.com/photos")
        }

        func getComments() -> URLDataPromise {
            return NSURLConnection.GET("http://jsonplaceholder.typicode.com/comments")
        }

        override func didReceiveMemoryWarning() {
            super.didReceiveMemoryWarning()
            // Dispose of any resources that can be recreated.
        }


    }

**Comment by rlaferla** [comment]
Thank you!!!!  Let's put this example in the project.  I think it will help others.  Also, is PromiseKit being used in any shipping apps?  Is it stable enough?

**Comment by swaffoja** [comment]
I probably wouldn't include these exact examples as they rely on SwiftyJSON, but I agree that updated Swift documentation on promisekit.org would be appreciated. I know there are are swift compiler issues that cause some of the existing examples to fail. It comes down to who is willing to revist the documentation and who has access to make changes.

My mastery of Swift isn't even close to that of the original PromiseKit author's mastery, so I have been hesitant to suggest updates to the documentation. It's also not clear on how someone would contribute as I haven't found a github repo that maps to the promisekit.org site. I actually enjoy writing documentation and would be willing to take a stab at updating Swift examples.

I would assume there are apps in production that use PromiseKit. I've been writing an app for a few months and I think PromiseKit is amazing. I certainly plan to use it for all of my future projects. I'm secretly hoping that Apple implements Promises because the resulting code is so much cleaner.
