### ISSUE TITLE
GET .then example doesn't work

### ISSUE THREAD

**Issue by rlaferla** [mxcl/PromiseKit#338]
When I try this example from http://promisekit.org/PromiseKit-2.0-Released ,

```
        NSURLConnection.GET("http://placekitten.com/\(width)/\(height)").then { (image: UIImage) in
            self.imageView.image = image
            }.catch { error in
                // If PromiseKit could not decode an image (for example, if you made
                // a mistake and the endpoint actually provides JSON), then Promise<T>
                // errors. AnyPromise would instead `then` a JSON NSDictionary, and if
                // you then tried to set the imageView’s image to that dictionary,
                // your code would crash.
        }
```

it results in an error:

```
Expected member name following '.'
Unable to infer closure return type in current context
```

**Comment by rlaferla** [comment]
I then removed the catch and added a -> Void but that doesn't work either.

**Comment by swaffoja** [comment]
Are you using PromiseKit 2 or 3? There were some changes between the two versions. `catch` was renamed to `error`. PromiseKit 3 would be:

    NSURLConnection.GET("http://placekitten.com/\(width)/\(height)").then { (image: UIImage) in
        self.imageView.image = image
    }.error { error in
        // do stuff
    }

**Comment by rlaferla** [comment]
I'm using the PromiseKit CocoaPod - not sure of the version.  The code you provided doesn't work with it.  I could only get it to work using NSData:

```
            NSURLConnection.GET(imageURL).then { (data:NSData) in
            self.imageView.image = UIImage(data: data)
        }

```

**Comment by mxcl** [comment]
This has changed with 3.0, it's easy enough to tell, refer to the source documentation for details, alt-clicking in Xcode is sufficient:

```swift
NSURLConnection.GET("http://placekitten.com/\(width)/\(height)").asImage().then { (image: UIImage) in
    self.imageView.image = image
}.catch { error in
    // If PromiseKit could not decode an image (for example, if you made
    // a mistake and the endpoint actually provides JSON), then Promise<T>
    // errors. AnyPromise would instead `then` a JSON NSDictionary, and if
    // you then tried to set the imageView’s image to that dictionary,
    // your code would crash.
}
```

The docs you reference are technically correct since they refer to the 2.x release, and at that time the code you used was correct.
