### ISSUE TITLE
There are no some categories in Pods

### ISSUE THREAD

**Issue by syzdykov** [mxcl/PromiseKit#340]
I install PromiseKit via CocoaPods. 
There are no some categories.
I really need CLLocationManager promise
<img width="409" alt="screen shot 2015-12-09 at 11 29 50" src="https://cloud.githubusercontent.com/assets/2590077/11680310/459477fc-9e68-11e5-9427-b938f957613c.png">

**Comment by nathanhosselton** [comment]
What are you including in your Podfile?

**Comment by syzdykov** [comment]
pod 'PromiseKit'

**Comment by nathanhosselton** [comment]
Also include `pod 'PromiseKit/CoreLocation'`

Including all categories was the default prior to 3.0.0 but appears to be no longer.

**Comment by syzdykov** [comment]
Thank you!
