### ISSUE TITLE
Nonexistent method (promiseWithResolver:) referred to in documentation.

### ISSUE THREAD

**Issue by thaterikperson** [mxcl/PromiseKit#342]
The class method `promiseWithResolver:` has three references in documentation, but the correct use is the instance method `initWithResolver:`.

**Comment by nathanhosselton** [comment]
Good catch. And sorry for the delay. In reviewing, I noticed that `promiseWithAdapter:` on line 219 in the same file similarly needs updated to `promiseWithAdapterBlock:`. If you wouldn't mind also including that in your PR I will merge.

Thanks for the contribution!

**Comment by thaterikperson** [comment]
Included your suggestion in the PR. Looked like the only remaining reference to `promiseWithAdapter:`.
