### ISSUE TITLE
PromiseKit crashes when promise is nil

### ISSUE THREAD

**Issue by toddrick** [mxcl/PromiseKit#344]
This is not how it should behave in objc.

AnyPromise *promise = nil;
promise.then(^{
   NSLog(@"Hello World");
});

This will crash in objective c. However, the objective-c paradigm is that calling a method on a nil object should send a message to a nil object which is refused, thereby not executing. Therefore my expectation is that in this case we would not log "hello world."

However, PromiseKit crashes in this situation. I think this stems from the _nonnull qualifier on then, catch, and finally, but I'm not sure.

**Comment by mxcl** [comment]
The crash is because you are calling the then block:

```objc
promise.then(^{
    //…
});
```

Calling a `nil` block crashes:

```objc
void (^block)() = nil;
block();  //CRASH!
```

This cannot be fixed. It is because of the dot-notated syntax, and is unfortunate. This is documented at http://promisekit.org.
