### ISSUE TITLE
Ambigous use of recover error while using PromiseKit

### ISSUE THREAD

**Issue by vskr** [mxcl/PromiseKit#345]
Running into a strange error when using recover while handling errors that can be thrown while executing a promise.

Chaining .recover with .then results in compilation if there is more than one statement in recover block.

Having single statement in recover block works and having recover alone (promise.recover{} without then works)

Attaching screenshots of single statement recover (which works) and multiple statement recover (which throws a compilation error with the message: Ambigous use of recover(on:__:)

Any help on how to debug this would be appreciated.

<img width="1156" alt="multiplestatements in recover" src="https://cloud.githubusercontent.com/assets/1729153/12027126/07237e64-ad77-11e5-8f42-c82ce6766776.png">
<img width="387" alt="singlestatementinrecover" src="https://cloud.githubusercontent.com/assets/1729153/12027127/07246b9e-ad77-11e5-83de-a1aabfd48db5.png">

**Comment by swaffoja** [comment]
This should be covered on StackOverflow now. I added a longer example that I think will explain what is going on.

http://stackoverflow.com/questions/34501537/ambigous-use-of-recover-error-while-using-promisekit/34502275#34502275

**Comment by nathanhosselton** [comment]
Yes, the return type must be specified for complex closures or the Swift compiler becomes confused. So the following should correct the error:

```swift
}.recover{ error -> () in
    //...
}
```
