### ISSUE TITLE
Error callback not executed when authentication challenge fails

### ISSUE THREAD

**Issue by Retolinho** [mxcl/PromiseKit#349]
I can observe a strange behavior when PromiseKit 3.0.0 handles Authentication challenges. 
I am using the following kind of request:
```
let promise = Promise<T> {
            fulfill, reject in
            Alamofire.Manager.request(.GET, pathURL, encoding: .JSON)
                .authenticate(user: username, password: password, persistence: .None)
                .validate()
                .responseObject { (response: Response<T, NSError>) -> Void in
                if response.result.error == nil {
                    if let obj = response.result.value {
                        mainQ {
                            fulfill(obj)
                        }
                    } else {
                        let error = NSError(domain: myDomain, code: 1, userInfo: [:])
                        mainQ {
                            reject(noResultError)
                        }
                    }
                } else {
                    let error = NSError(domain: myDomain, code: 1, userInfo: [:])
                    mainQ {
                        reject(validateError)
                    }
                }
            }
        }

```

This kind of request works well as long as the username and password given to the authenticate function are valid. I can observe a first network request returning with a HTTP status of 401 and the auth challenge. The second request then includes the given credentials, the server response is successful and the promise gets fulfilled. 
If the given username or passwords are invalid, the second request returns with HTTP status of 401 again. PromiseKit tries to reject the Promise, but the promise already has been deallocated. I can see the following message in the console: `PromiseKit: Pending Promise deallocated! This is usually a bug`
Since I cannot identify any problems in my request implementation above, i suspect an error in PromiseKit 3.0.0.

**Comment by nathanhosselton** [comment]
I'm not sure if this is related to your issue, but why are you seemingly calling `fulfill` and `reject` on the main queue? Even if it's not the issue, this could certainly cause side effects. Allow PromiseKit to execute as designed. You can access the value of the promise on the main queue via `then` and `catch` after it resolves. See [error handling](http://promisekit.org/error-handling).

**Comment by nathanhosselton** [comment]
If this doesn't resolve your issue let me know. Nothing else in your example immediately stands out to me, so I may need more detail.

**Comment by Retolinho** [comment]
Thank you for the hint with the main queue. I removed the manual queue handling now, but that does not resolve the issue. 
Since the provider of my API decided to move away from Basic Auth and use another kind of authentication, i can no longer reproduce the behavior. I am sure the problem is still out there, but with that API change i do not see it anymore...
