### ISSUE TITLE
Add Changelog to track changes between versions

### ISSUE THREAD

**Issue by ldiqual** [mxcl/PromiseKit#354]
I just ran `pod oudated` today and noticed that PromiseKit has a new 3.0.2 version. I have no way to know what's new in this version because there's no changelog and the tag doesn't have release notes.

Would you mind adding a `CHANGELOG.md` for future versions? Or add release notes to your tags? Thank you :)

**Comment by nathanhosselton** [comment]
Currently there is a changelog maintained at [promisekit.org](promisekit.org) but I will begin including release notes in the tags as well for future releases. Thanks for the recommendation!

**Comment by ldiqual** [comment]
@mxcl @nathanhosselton would you be open to the addition of a changelog file as part of the repo? From experience I know that maintaining release notes in tags can be painful, and it doesn't seem like it consistently done in the recent releases. A changelog might help with that.
For context: was trying to see what's new in 6.2.0 but there was no release note and the commit history was hard to read.

**Comment by mxcl** [comment]
We had one, it didn't get maintained, so I removed it.

The commit history has all the information, I don't really understand why it is hard to read.

**Comment by nathanhosselton** [comment]
Indeed, maintaining separate changelogs and even summaries in tags is painful. Especially considering all of the information already exists and GitHub simply doesn't surface it well.

You may already know this, but it's possible to view the repo history by tag via the branch selection dropdown. You can select `Tags` instead and jump to a specific tag's point in time. Maybe this will be helpful to you. Obviously would be more helpful if GitHub only showed commits exclusive to a specific tag.

**Comment by mxcl** [comment]
I added the crux in the release notes: https://github.com/mxcl/PromiseKit/releases/tag/6.2.0

**Comment by ldiqual** [comment]
@mxcl thanks a lot.

Just to clarify my point about commit history, when you look at the diff between [6.1.2 and 6.2.0](https://github.com/mxcl/PromiseKit/compare/6.1.2...6.2.0) this is what you get:

![image](https://user-images.githubusercontent.com/941453/36810095-a81df768-1c7e-11e8-8607-c2e1c725894c.png)

It's pretty cluttered: important changes get buried among all the behind the scene work, it includes irrelevant information like merge commits (usually solved with squash merges), and more importantly: it's unclear how user-facing changes affect the API / user codebase just from the commit title.

My company updates dependencies every 2 weeks – which I think is pretty aggressive – so in this case it's 6 versions of PromiseKit that I need to go over. That's [66 commits](https://github.com/mxcl/PromiseKit/compare/6.0.1...6.2.0). I understand this is most likely a result of releasing a major version but usually PromiseKit is pretty good at getting regular maintenance updates, so a couple versions every 2 weeks is not that rare of an occurrence. I would imagine that most companies don't upgrade this aggressively so it's most likely even harder for them.

Maintaining a changelog is notoriously hard though so I definitely get your point. Thanks again for the release notes, super useful!

**Comment by mxcl** [comment]
Well, sorry, but I haven't time to maintain the entire library and all the other crap. So, tough.

**Comment by ldiqual** [comment]
@mxcl yes, this is why I was asking whether you'd be open to it in https://github.com/mxcl/PromiseKit/issues/354#issuecomment-369117769.

One way to maintain a changelog that is low effort for maintainers is to enforce authors to modify the changelog as part of their PRs. This is what [Cocoapods does](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md) and I believe it's been working pretty well for them. This can even be enforced with tools like `danger`. I'm happy to help adding this process in place if you think it's valuable. I agree that maintaining it manually is too much work.

**Comment by mxcl** [comment]
Mostly I’m the one doing the “PRs” so…

Really GitHub should auto generate the changelog, all it has to do is allow us to specify which files to exclude and then put all the commit messages together. It could even link to the code.

Having this file exist separately seems like working harder not smarter.
