### ISSUE TITLE
PromiseKit 3 with obj-c only app?

### ISSUE THREAD

**Issue by chrisze** [mxcl/PromiseKit#356]
Hi,

Is it possible to use PromiseKit 3 from obj-c only app? Is PromiseKit 1.5 the only option today? Are there significant differences between v1.5 and 3 (in obj-c promises)?

I would love to avoid including Swift runtime in our app if possible (with regret obviously cause I love the language). PromiseKit is incredibly useful, so we'd like to use it, but adding Swift means adding dynamic frameworks, and that unfortunately translates to occasional slow cold startup times when device framework cache gets purged. Basically, if I kill our app, then run a bunch of "chunky" apps like a regular user (Twitter, Mail, News, Facebook etc), then re-launch our app, it takes 3-5 seconds on iPhone 6 Plus for the app to start. Normally it starts under a second. 

If I just remove `use_frameworks!` from our Podfile, this problem does not exist. The app (statically linked) starts immediately. Ohh and by the way, at this stage, the app doesn't even do anything yet. It's just a skeleton with empty screens and a bunch of frameworks I know I'll use. Here's a thread with details: https://github.com/stepanhruda/dyld-image-loading-performance.

It would be totally awesome to have a pod spec for obj-c only apps.

Thanks,
-Christoph

**Comment by mxcl** [comment]
The core is Swift. You can use PromiseKit 1, it sounds old but really it's just as good. PMK1 is all ObjC.

**Comment by chrisze** [comment]
Fantastic! Thanks for the follow up.
