### ISSUE TITLE
Way to setup Promise with only reject.

### ISSUE THREAD

**Issue by alexth** [mxcl/PromiseKit#360]
Is it possible to setup Promise with only reject block in some way, without making do-catch?
```
func save(newName: String?, newPhotoImage: UIImage?) -> Promise<Entity> {
            let newNameError: NSError? = workerValidator.validateNameLength(newName)
            if newNameError != nil {
                output.showNameValidationError(newNameError!)
                return Promise { fulfill, reject -> Void in
                    reject(nameLengthError)
                }
            }
            return workerDatabase.updateUserFields(newName, image: newPhotoImage)
    }
```

**Comment by alexth** [comment]
Solved by creating enum with custom ErrorType and passing it into reject().
Got rid of NSError usage. Now validateNameLength() returns custom ErrorType

**Comment by nathanhosselton** [comment]
Not sure what exactly you're going for, but you can create a rejected promise with `Promise(yourErrorType)` which is a bit cleaner I think.

**Comment by alexth** [comment]
I did the the same you explained. Thank you @nathanhosselton !
