### ISSUE TITLE
Building process get stuck

### ISSUE THREAD

**Issue by jotajota05** [mxcl/PromiseKit#364]
I'm using PromoseKit with more than 10 promises, but the indexing and building process are getting stuck or taking too much time to finalize and compile my application. Sometimes I have to rename my methods inside the promise in order to compile, other way it just get stuck.

There is a limit o promises the library can handle (number of .then)?  

Im using Xcode7, Swift 2.0 and PromiseKit version 3.0 with CocoaPods

The way Im using it is something like this:

firstly {
                self.method1()
       }.then { _ in
                self.method2()
      }.then { _ in
                self.method2()
      }.then { _ in
                self.method2()   
...
...
...
      }.then { _ in
                self.methodN()
      }.error { error in 
                self.showError(error)
}

And the methods are something like this:

private func methodN() -> Promise<AnyObject> {
        
        return Promise { fulfill, reject in
            
                  self.doSomething()
                  if success {
                        fulfill("")
                  } else {
                        reject(error)
                  }
          }
}

**Comment by nathanhosselton** [comment]
Shouldn't be a limit. Certainly not with 10 anyway. How can you be certain the build hangs are due to PromiseKit? Can you share your specific code? Your examples look fine.

**Comment by jotajota05** [comment]
Unfortunately I cannot share any specific code, but the examples represent what Im doing, the content of the methods is irrelevant. How I know is Promise Kit?, because the compiling time is being increasing with any new promise that I add. Even when I just try to edit one of the methods, Xcode start a very heavy and slow process of indexing, losing my colors in the IDE editor and everything, and then the compiling take ages or get stuck. And this only happens when I modify the file where I have the Promises. If I work in every other file the compiling process runs fine. 

In some cases I reduce the number of promises, putting a bunch of them inside another method that runs in the original promises chain. This got things a little better (at least the code compile in a decent amount of time)

Inside the promises methods normally I run calls to backend using Alamofire, I don't know if this can be messing with something.

The library works like a charm, but everytime I need to modify the specific class that contains the promises is a pain.

**Comment by nathanhosselton** [comment]
The content of the methods and closures may in fact be relevant. Unfortunately I don't think I can offer much assistance without seeing more as I cannot reproduce the issue.

**Comment by jotajota05** [comment]
I understand. Sorry I cannot share the code. Basically every method runs some background operations, use the GCD, call backend services with Alamofire or communicate with devices using the thunder port, They are indeed not trivial methods. And the problem is only during compile time, and only if I modify the file that runs the promises. 

Well, at least keep an eye on this behaviour, so maybe in the future you can have a more concrete scenario where you can replicate it. 

Thank you.

**Comment by mxcl** [comment]
This is almost certainly a bug in Swift itself.

**Comment by mxcl** [comment]
Swift bug, please report to http://bugs.swift.org
