### ISSUE TITLE
Carthage categories

### ISSUE THREAD

**Issue by leoMehlig** [mxcl/PromiseKit#365]
I'm currently looking into this library and am trying to find a solution to use the categories with Carthage. The 'copy the files into the checkout folder'-option doesn't work for me, because I use a automate build system, which updates all the dependencies. 
I agree, that linking all the categories would be a bad idea.
My proposal to solve this problem is, having separate schemes/targets for each category.

These targets would depend on the PromiseKit and include the code of their category.

Pros of this solution are:

- The user can simply add the build binaries of the categories that he requires.
- There is no linking of unnecessary (system) libraries
- Dependency management with carthage would work, even on automated build servers.

Cons:
- A lot of schemes and targets would be required (platforms * categories = something like 60 targets and schemes)
- All schemes of a platform would be build by carthage with every `carthage update --platform ***`

The best solution would be the support of "sub-projects" by carthage, but until then I think this is a possible solution.

I could create thees targets if this is something other user a interested in. 

Would appreciate any feedback.

PS. I've already added the iOS Foundation category on the carthage branch of [my fork](https://github.com/leoMehlig/PromiseKit/tree/carthage).

**Comment by nathanhosselton** [comment]
I agree that this sounds like an issue that needs resolved. I'd like to not have anyone prevented from using PromiseKit just because their configuration is different. And automated build systems are fairly common. However, I'm hesitant to introduce that level of complexity into the project just for Carthage. Forgive me, I haven't used an automated build system myself and am not super familiar with Carthage; can you elaborate a little more on the specifics of the issue?

**Comment by leoMehlig** [comment]
The thing is that I usually don't want to include the code of a external framework in my internal codebase, because this makes updating way more complicated. 

So in my case I want to use only the Foundation category in my iOS App. Obviously it would be inefficient to include all categories and with that link all necessary system frameworks.

**Comment by nathanhosselton** [comment]
Sorry, my questions was why specifically is copying the relevant category files into the Carthage checkout folder not sufficient under your automated build system? Again, I'm asking because I'm not familiar with your situation, so I'm trying to understand.

**Comment by leoMehlig** [comment]
Oh, right.
The Carthage checkout folder isn't in our git (or in our case svn). On our build server we run `carthage update` which downloads all the dependencies and builds them. This is all done automatically with each commit.
For now I include the needed category classes in my project, but I don't really like this solution. 

1. When copying the files into the project you are unable to automatically update them
2. Its third-party code in your project (which I personally don't like). 
3. A small thing is that you don't have the usual access control. Because the classes are in your project you can access `internal` (swift) function/variables instead of only `public`

**Comment by jonasman** [comment]
+1 For me the problem is similar:
We import PromiseKit via another dependency. And then we cannot import the categories because of that.

**Comment by mxcl** [comment]
You could add a copy files phase to your app's project?

**Comment by mxcl** [comment]
Thinking about it, that's even more than necessary, just drop the files into your app's project from the Carthage checkout. On fresh clones the files will show up red until Carthage is run.

**Comment by mxcl** [comment]
We could add another xcodeproj with schemes for each category. But it in: `Categories`. Then we won't pollute the main xcodeproj with all the other schemes which is really our concern since managing the project is already tedious.

**Comment by jonasman** [comment]
just tried to do the import from carthage checkouts. It seems to be a good idea but fails here:
```
#if !COCOAPODS
import PromiseKit
#endif
```

Removing the #if checks solves the problem.

**Comment by jonasman** [comment]
Im still waiting for the day that SPM will be the default :)

**Comment by mxcl** [comment]
> The issue is tricky in this project. We have cocoapods + carthage . Carthage is used to import 1 library. this one lib imports Promisekit.

Ugh. Yeah. I hate that `#if` anyway. Maybe I can figure out a solution by building two Frameworks in CocoaPods…

**Comment by mxcl** [comment]
I honestly don't think we can manage this, it is quite a lofty maintenance burden on top of that which we already have regarding all the categories (podspec + tests).

I maintain the solution is to drop the files from the Carthage checkout into your xcodeproj. Carthage checkouts the files into your source tree, so it seems an acceptable compromise.

When and if Xcode allows one scheme for multiple platforms we will add schemes for the categories, modify our tests to use the schemes and then also be able to easily test tvOS and watchOS which currently we do not for the same reasons outlined above.

Sorry.

**Comment by leoMehlig** [comment]
@mxcl I see you are putting all the categories in separate repo. That solution is way better and cleaner!!!

**Comment by mxcl** [comment]
Since my discovery of [Single-scheme, multiplatform targets](http://promisekit.org/news/2016/08/Multiplatform-Single-Scheme-Xcode-Projects/) I have implemented this as requested.

Each category is now a separate repository at https://github.com/PromiseKit

So you can request them separately in your `Cartfile`.

For CocoaPods we import the sources for the categories using git submodules, so nothing has changed for CocoaPods users.
