### ISSUE TITLE
  Ambiguous reference to member 'when' (swift PromiseKit 3.0)

### ISSUE THREAD

**Issue by peterwarbo** [mxcl/PromiseKit#370]
I have 4 promises which I try to resolve in a when().

Whenever I put 3 promises inside the when() I get no compiler error. But if I try to put 4 promises inside the when() I always get "ambiguous reference..." 

What gives?

**Comment by swaffoja** [comment]
Check out the method signatures for `when`. It takes up to 3 promises. You can however give it an array of promises if you need more than 3.

```
let promise1 = Promise(1)
let promise2 = Promise(2)
let promise3 = Promise(3)
let promise4 = Promise(4)

// SUCCESS, up to 3 promises OK
when(promise1, promise2, promise3).then { response1, response2, response3 in
    print("test promises fulfilled \(response1) \(response2) \(response3)")
}.error { error in
    print("error")
}

// FAIL, when only accepts up to 3 promises. look at method signature
when(promise1, promise2, promise3, promise4).then { response1, response2, response3, response4 in
    print("test promises fulfilled \(response1) \(response2) \(response3) \(response4)")
    }.error { error in
        print("error")
}

// SUCCESS, Just use an array of promises if you need more than 3
let promises = [promise1, promise2, promise3, promise4]

when(promises).then { response in
    print("test promises fulfilled \(response)")
}.error { error in
    print("error")
}
```

**Comment by nathanhosselton** [comment]
Without seeing your code, I'm assuming your promise types are varying. Due to the nature of Swift, `Promise` `when()` can only accept up to three promises when the types do not match (technically we could include more, but we'd just have to keep adding definitions for `when()` with the explicit number of parameters). If you need to have more than three promises of varying type in a `when`, you'll need to use `PMKWhen` on `AnyPromise`, which is more dynamic.

If you believe this isn't your issue, please share the relevant code and I'll review.

**Comment by peterwarbo** [comment]
@nathanhosselton yes that is the case, I'm having varying promise types. So how would I use PMKWhen (which I believe is from the Obj-C library) in my Swift project?

**Comment by nathanhosselton** [comment]
Create a bridging header if you haven't already and in it `#import <PromiseKit/PromiseKit.h>`.

**Comment by nathanhosselton** [comment]
Yes, it should be rejecting immediately if one of the passed promises was rejected. I'm not sure why it would be fulfilling.

**Comment by mxcl** [comment]
One trick is to make them void:

```swift
when(a.asVoid(), b.asVoid(), c.asVoid(), d.asVoid()).then { _ in
    print(a.value, b.value, c.value, d.value)
}
```

There's no other elegant answer since Swift has no mechanism to help us here.
