### ISSUE TITLE
Directory names contain characters that is reserved on some file systems

### ISSUE THREAD

**Issue by DominikDeak** [mxcl/PromiseKit#378]
We are maintaining a cross platform project, which means our codebase needs to be stored on NTFS partitions on some machines. However, certain directories in the PromiseKit project contain characters that is [reserved on NTFS](https://en.wikipedia.org/wiki/Filename#Reserved_characters_and_words), namely the colon character `:`, as shown in the path below. 

`PromiseKit/Tests/Promises:A+ Specs/`

This makes synchronising projects across several platforms quite problematic. Perhaps consider using a character set that is safe on most platforms?

**Comment by mxcl** [comment]
Surely your synchronization tools can handle this?

I understand your pain, but we hardly consider Windows support important. Now, if there is absolutely nothing you can do about this we'll change it, but I think you need to demonstrate that you have tried first before we make PromiseKit slightly less good to support a platform that we don't in fact support.

**Comment by DominikDeak** [comment]
> Surely your synchronization tools can handle this?

We're using both git command line and GitHub's synchronisation tool. PromiseKit was added on a Mac platform, the issue was discovered once we tried to sync with a local copy on Windows. For example, a clone attempt onto an NTFS partition raises the following error:

```
fatal: cannot create directory at 'Carthage/Checkouts/PromiseKit/Tests/Promises:A+ Specs': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

Anyway, at least that part of the source it's not particularly critical for us, so I might have to `.gitignore` that directory for the time being.

> I understand your pain, but we hardly consider Windows support important.

Fair enough, just raising awareness.

**Comment by mxcl** [comment]
> but we hardly consider Windows support important

This was badly phrased. If and when using PromiseKit on Windows is viable and useful, then we'll consider it important.

Anyway, so git itself cannot checkout the folder? Jeez. Well if this is the case then we'll rename it. /cc @nathanhosselton

**Comment by nathanhosselton** [comment]
Will remove the `:` here and give a look through the rest of the directory tree to ensure we're not using any reserved characters elsewhere.

**Comment by Sega-Zero** [comment]
You could use a unicode equivalent, `⠅` for example.

**Comment by mxcl** [comment]
This was fixed.
