### ISSUE TITLE
Unexpected behavior in promise chains (PromiseKit 3.0.0)

### ISSUE THREAD

**Issue by opfeffer** [mxcl/PromiseKit#379]
I'm observing some unexpected behaviors that I'm not sure are intended to work this way:

We work in a mixed ObjC/Swift codebase where a bunch of underlying "Services" are written in ObjC with some ViewControllers written in Swift consuming the aforementioned services. Due to the fact that the services are objc, all methods return instances of `AnyPromise`.

        someService.someAnyPromise().then { (service: AnyObject?) in
            guard let service = service as? SomeService else {
                throw Errors.UnexpectedValueType
            }
            
            return service.someOtherAnyPromise()
        }.then { (value: AnyObject?) in
                print("expecting NSNumber, actual=\(value.self)")
        }

As you can see in the above code snippet, `-someAnyPromise` returns a promise that eventually resolves with a "service" object. In the first `-then` we return another promise, creating a promise chain. 

In the second `-then` I now expect a value object. In our example an instance of `NSNumber`... However the console prints

     expecting NSNumber, actual=Optional(AnyPromise: UnsealedState: Pending with 0 handlers)

I created a sample project demonstrating the behavior: https://github.com/opfeffer/promisekittestbed

Is that expected? Should I now be unwrapping the promise object and attaching a `then` inside my `then` ? Or how _should_ this work?

**Comment by mxcl** [comment]
Last time I tried I could not make the `Optional` variant for AnyPromise work, so you have to unwrap it manually.

I'm assuming `someOtherAnyPromise()` returns an `Optional<Promise>`

**Comment by opfeffer** [comment]
`someOtherAnyPromise()` returns an instance of `AnyPromise` (as it is written in ObjC).
I should have mentioned, in a pure ObjC implementation the second `then` correctly has the NSNumber as parameter..

Its only in Swift where the parameter suddenly is of type `AnyPromise`... which doesn't seem to make sense to me

**Comment by mxcl** [comment]
Be explicit with your return types, Swift is inferring the wrong type apparently. See the API options.

**Comment by opfeffer** [comment]
Yea that was it. Without specifying my return type, Swift did assume the wrong `then()` method..
