### ISSUE TITLE
Best practice for polling and returning a promise?

### ISSUE THREAD

**Issue by RyanWarner** [mxcl/PromiseKit#387]
Thank you for the awesome library. I'm relatively new to Swift and trying my best to find my way.

I'm trying to implement a recursive function that returns a promise that resolves when results are not nil, otherwise wait a second and try again.

In JavaScript I'd use BlueBird's `Promise.delay` function, similar to this gist: https://gist.github.com/wpm/f745ea6478507c6eb72f

How would I do this with PromiseKit? Are promises even the right design pattern here?

**Comment by mxcl** [comment]
We have `after()`, which appears to be the same as Bluebird’s `delay`.

We don’t have anything that satisfies your needs directly.

**Comment by mxcl** [comment]
Here is the linked gist as Swift:

```swift
enum Error: ErrorType {
    case Timeout
}

func poll(signal: () -> Bool, interval: NSTimeInterval, timeout: NSTimeInterval) {
    func pollRecursive() -> Promise<Void> {
        return signal() ? Promise() : after(interval).then(pollRecursive)
    }
    
    return race(after(timeout).then { throw Error.Timeout }, pollRecursive())
}
```

**Comment by danlozano** [comment]
Hi @mxcl great library!

This issue is helping me a lot in my quest to implement an API polling system.

I just have with this sample code. Even if it times out and catches the error, the pollRecursive and signal keeps getting called.

This is my updated version of your code.

```swift
enum PromiseError: Error {
    case Timeout
}

func poll(signal: @escaping () -> Bool, interval: TimeInterval, timeout: TimeInterval) -> Promise<Void> {
    func pollRecursive() -> Promise<Void> {
        return signal() ? Promise(value: ()) : after(interval: interval).then(execute: pollRecursive)
    }

    return race(after(interval: timeout).then { throw PromiseError.Timeout }, pollRecursive())
}

poll(signal: randomSignal, interval: 1, timeout: 2).then {
    print("done")
}.catch { error in
    print("error")
}

func randomSignal() -> Bool {
    let r = arc4random_uniform(4) == 0
    print(r ? "Complete" : "Not complete");
    return r
}
```

Isn't the throwing of the timeout supposed to error out and stop everything?

Thanks for your help, sorry if it's a dumb question.

**Comment by danlozano** [comment]
This is the console output

Not complete
Not complete
Not complete
error                      <- Shouldn't it have stopped here?
Not complete        <- kept calling pollRecursive() & therefore signal()
Not complete        <- kept calling pollRecursive() & therefore signal()
Complete               <- until it completed

**Comment by danlozano** [comment]
Sorry for adding this here. Will add this to it's own issue.

:)

**Comment by mxcl** [comment]
Indeed, there's two separate chains, that later combined, the timeout only stops the left chain, so the right chain will continue until it errors.

Here's the fix:

```
enum PromiseError: Error {
    case Timeout
}

func poll(signal: @escaping () -> Bool, interval: TimeInterval, timeout: TimeInterval) -> Promise<Void> {
    let timeout = after(interval: timeout).then { throw PromiseError.Timeout }

    func pollRecursive() -> Promise<Void> {
        guard timeout.isPending else { return timeout }
        return signal() ? Promise(value: ()) : after(interval: interval).then(execute: pollRecursive)
    }

    return race(after(timeout, pollRecursive())
}

poll(signal: randomSignal, interval: 1, timeout: 2).then {
    print("done")
}.catch { error in
    print("error")
}

func randomSignal() -> Bool {
    let r = arc4random_uniform(4) == 0
    print(r ? "Complete" : "Not complete");
    return r
}
```
