### ISSUE TITLE
Downcasting AnyPromise to Promise<T>

### ISSUE THREAD

**Issue by kominak** [mxcl/PromiseKit#388]
In my recent effort to convert a PromiseKit 1 app (hybrid ObjC+Swift) to use PromiseKit 3, I had to deal with type-less `AnyPromises` coming from ObjC part of the app in the newer Swift part. In order to use the full advantage of typed `Promise<T>`, I came up with this downcasting approach:

```objc
// Legacy ObjC code
@interface Backend
+ (AnyPromise *)fetchUser;
@end
```

Downcasting in Swift:

```swift
Backend.fetchUsers()
.toPromise(User) // downcast to Promise<User>
.then { (user: User) -> Void in
    // ...
}
```

Of course, I can downcast to any type:
```swift
.toPromise(User?)
// or
.toPromise([User])
// etc.
```

All I had to do was adding this category:

```swift
extension AnyPromise {
    func toPromise<T>(type: T.Type) -> Promise<T> {
        return self.then { (value: AnyObject?) -> T in
            if let value = value as? T {
                return value
            }
            throw PromiseError.CastingError
        }
    }
}
```

Do you consider this a generic enough approach? Or is there any better approach, perhaps already supported by PromiseKit 3? I couldn't find anything like that, but I'd be glad if this works out of box. Of course I can prepare a PR, etc., but I'd like to hear your opinions.

Thanks for considering this addition.

**Comment by nathanhosselton** [comment]
> In order to use the full advantage of typed Promise<T>, I came up with this downcasting approach

Can you provide some examples where you're using the converted promise in a way that you could not with its AnyPromise counterpart? This may help me figure out what the best solution here is. I've personally never needed to cast an AnyPromise to Promise<T>, and don't recall it ever coming up before, but that doesn't mean there isn't a valid use case for it.

**Comment by kominak** [comment]
I encountered several annoying obstacles when working with `AnyPromise` in Swift, so this approach brought in several advantages (not only syntactic ones), which unifies the access to both types of promises in Swift code.

* AFAIK there's no way to call `catch`, `recover` nor `finally` on `AnyPromise` in Swift. I had to add a dummy call like `.then { _ -> Void in }`

* I found it nicer to use `.toPromise(Type)` than the code below (although I acknowledge that the second example is perhaps more clear and obvious - but requires a lot more writing):
```swift
.then { value in
    guard let value = value as? Type else { throw SomeError }
}
```
* Then there are the small syntactic differences like `AnyPromise.value()` vs. `Promise.value`

* Imagine a situation where you want to store several promises to an array, or return a promise from a method - and they can originate both from ObjC part (`AnyPromise`) and from Swift (`Promise<T>`). You'll probably want to convert them to be of the same type, and if you plan to use them in Swift, chances are that `Promise` would be a better candidate.

**Comment by nathanhosselton** [comment]
Understood. This makes sense and seems necessary, so I agree this should be added.

Eventually we may have [implicit casting](https://github.com/apple/swift-evolution/blob/master/proposals/0058-objectivecbridgeable.md), but we can't wait for that.

**Comment by mxcl** [comment]
Merged
