### ISSUE TITLE
UIViewController promiseViewControlller does not always dismiss

### ISSUE THREAD

**Issue by jgrantr** [mxcl/PromiseKit#394]
I tracked the problem down, and it has to do with presenting a view controller from a view controller that can't handle the request, and so the view controller forwards it to its parent (as stated in the Apple docs for presentViewController:animated:completion.  The change in PromiseKit is to the finally block.  To be completely correct it should be changed from:

    promise.finally(^{
        //TODO can we be more specific?
        [self dismissViewControllerAnimated:animated completion:nil];
    });

to

    promise.finally(^{
        //TODO can we be more specific?
        [vc2present dismissViewControllerAnimated:animated completion:nil];
    });

or

    promise.finally(^{
        //TODO can we be more specific?
        [vc2present.presentingViewController dismissViewControllerAnimated:animated completion:nil];
    });

It is a pretty simple change, but I can create a pull request if you want.

Thanks, and let me know if you have any questions.

**Comment by nathanhosselton** [comment]
Good find! A PR would be great. And it sounds like you satisfied that TODO.

**Comment by jgrantr** [comment]
I've submitted a pull request.  Let me know if you need anything else.
