### ISSUE TITLE
SLRequest issue

### ISSUE THREAD

**Issue by doncorsean** [mxcl/PromiseKit#398]
Using SLRequest extension, but my token is expired so FB is returning error (400). When I try to catch the error or recover from it to request an updated token I get only:

**Handled:**
Error:Error Domain=PromiseKit.URLError Code=2 "The operation couldn’t be completed. (PromiseKit.URLError error 2.)"

How can I access response to recover from this?

**Unhandled:**
PromiseKit: Unhandled Error: BadResponse(<NSMutableURLRequest: 0x17401d240> { URL: RequestURL }, Optional(<NSData>), Optional(<NSHTTPURLResponse: 0x17403d740> { URL: <RequestURL> } { status code: 400, headers {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-store";
    "Content-Encoding" = gzip;
    "Content-Length" = 218;
    "Content-Type" = "application/json; charset=UTF-8";
    Date = "Mon, 04 Apr 2016 23:29:47 GMT";
    Expires = "Sat, 01 Jan 2000 00:00:00 GMT";
    Pragma = "no-cache";
    Vary = "Accept-Encoding";
    "Www-Authenticate" = "OAuth \"Facebook Platform\" \"invalid_token\" \"Error validating access token: Session has expired on Saturday, 19-Sep-15 23:50:36 PDT. The current time is Monday, 04-Apr-16 16:29:47 PDT.\"";
} }))

**Comment by swaffoja** [comment]
I'm not familiar with SLRequest, but the last post on [this thread](https://github.com/mxcl/PromiseKit/issues/324) may help you access the BadResponse if you are using Swift.
