### ISSUE TITLE
Cancel PMKAlertController programatically

### ISSUE THREAD

**Issue by besi** [mxcl/PromiseKit#400]
Is it possible to cancel an `PMKAlertController` programatically? Let's assume I display an alert like so:

> You are currently offline `[OK]`

Now as soon as I detect that I am no longer offline, I want to dismiss/cancel this alert without the user having to tap `OK`.

**Comment by nathanhosselton** [comment]
Short answer is no. Our `PMKAlertController` does not expose its underlying `UIAlertController` and doesn't currently have a `cancelPromisedViewController` method in its `UIViewController` extension. However, this would be a trivial addition: https://github.com/mxcl/PromiseKit/blob/master/Categories/UIKit/PMKAlertController.swift#L70

PR welcome!

**Comment by nathanhosselton** [comment]
Actually I guess it wouldn't be all that trivial now that I'm really looking at it. We will have no reference to the PMKAlertController instance from the UIViewController extension. So the options then would be to either pass the PMKAlertController instance back into the new `cancelPromisedViewController` method, which does follow UIViewController's `dismissViewController` API that we would be mimicking, else place the method on PMKAlertController itself, which would be inconsistent with our own API.

Still, neither option would be difficult. It's just deciding which one to go with. I think I'm personally leaning towards the former.
