### ISSUE TITLE
Feature Request: UIViewController+Promise.promiseViewController option to fire promise _after_ dismiss completes

### ISSUE THREAD

**Issue by ryanschneider** [mxcl/PromiseKit#407]
First off, I love the library, big thanks for maintaining it.

I'm curious, do you have any plans on your roadmap to support having `promiseViewController` fulfill after the view has been dismissed?  Basically I want to wrap promiseViewController with another promise, and have that promise fulfill inside the `dismissViewController.completion` closure.

I think this can be implemented if there as another optional argument on `promiseViewController`:

```swift
    public func promiseViewController<T>(
        vc: UIViewController, 
        animated: Bool = true, 
        completion: (() -> Void)? = nil, 
        dismissCompletion : (() -> Void)? = nil  // <-- this is new
    ) -> Promise<T> {

        let p: Promise<T> = promise(vc)
        if p.pending {
            presentViewController(vc, animated: animated, completion: completion)
            p.always {
                self.dismissViewControllerAnimated(
                    animated, 
                    completion: dismissCompletion?() // <- this too
                )
            }
        }

        return p
    }
```

Cause then I could do:

```swift
  func waitForDismiss(vc: UIViewController) -> Promise<Void> {
    let (dismissed, fulfill, reject) = Promise<Void>.pendingPromise()
    self.promiseViewController(vc, dismissCompletion: {
      fufill()
    }

    return dismissed
  }

  //.. elsewhere
  self.waitForDismiss(someView).then {
    // fire my animation once th view has been fully dismissed
  }
```

Would you guys be interested in such a PR?  One caveat is the ordering of the arguments, as adding a new final closure changes the semantics of extension method.  So maybe as a new `func promiseViewControllerWithDismissCompletion`?

**Comment by mxcl** [comment]
Well, this isn't very “promisey”. Seems like there should be a `Bool` that defines if the promise fulfills after completion or before completion. Maybe I'm forgetting why we haven't already done this though.

**Comment by ryanschneider** [comment]
I was originally think a `Bool` as well, but realized there needs to be a second promise involved since the `Promisable.promise` is what triggers us to call `dismissViewController`, we still need another promise to fulfill when the dismissal completes.  I thought it'd be wrong in some way if setting the `Bool` actually changed which promise was returned (the `Promisable.promise` or the "dismissed" promise that wraps it), and then decided that passing in the dismissal completion handler is more generic (in case someone wanted to do something non-promise-based in the handler as well).

But if returning the wrapping promise passes the smell test for you I'm all for encapsulating everything in the function with a `Bool`.

**Comment by mxcl** [comment]
```swift
promiseViewController(vc, fulfill: .OnceDismissed).then {
     // other value would be .BeforeDismissal
}
```

Will implement unless you have any thoughts or concerns.

**Comment by denandreychuk** [comment]
@mxcl Do you plan to merge this into original branch?

**Comment by RomanPodymov** [comment]
Hello @denandreychuk 
I think such functions should be added to [PromiseKit/UIKit](https://github.com/PromiseKit/UIKit).

**Comment by RomanPodymov** [comment]
@denandreychuk BTW, have you try [this extension](https://github.com/PromiseKit/UIKit/blob/master/Sources/UIViewController%2BAnyPromise.h)?
