### ISSUE TITLE
Dynamic library loader can't find PromiseKit on tvOS using Carthage integration

### ISSUE THREAD

**Issue by emaloney** [mxcl/PromiseKit#409]
When using Carthage to integrate PromiseKit on tvOS, I get a `dyld: Library not loaded` at app launch when the dynamic library loader tries to load PromiseKit.

I was able to fix the issue by changing some build settings, and have submitted a pull request #408 with those changes. The issue is discussed further in the pull request.

**Comment by mxcl** [comment]
Merged.
