### ISSUE TITLE
Nullable in 2.2 minimal changes branch breaks on cast

### ISSUE THREAD

**Issue by blakebyrnes** [mxcl/PromiseKit#410]
Resolving a promise with nil when the promise <U> is an optional type causes a cast exception.  

The code on line 204 of Promise.swift is the source:
                    body(value as! T).pipe(resolve)

This code worked fine on the 2.0 minimal branch.  Needed to upgrade for swift 2.2 breaking changes.  

Do you know of a workaround?

**Comment by nathanhosselton** [comment]
Can you provide a code example?

**Comment by blakebyrnes** [comment]
Well, strangely.. I don't seem to be able to.  I created a playground that does basically what my code is crashing on, but it's not reproducing that behavior.   This works fine...
`
func getResult() -> Promise<AnyObject?> {
    return Promise { fulfill, reject in
        print("running")
        fulfill(nil)
        print("fulfilled")
        
    }
}

getResult().then { val -> Promise<Int?> in
    print("Got value \(val)")
    return Promise(nil)
}.then { val in
    print("Got number \(val)")
}


XCPSetExecutionShouldContinueIndefinitely()`

Attached you can see where the code is crashing, and the source:

![image](https://cloud.githubusercontent.com/assets/115056/14869620/84751208-0ca2-11e6-9e01-5ed056019c17.png)
![image](https://cloud.githubusercontent.com/assets/115056/14869632/991111e4-0ca2-11e6-948d-a6389564fc83.png)

**Comment by morishin** [comment]
I found the same crash in my app.
This crash was shown not on `swift-2.0-minimal-changes` branch but on `swift-2.2-minimal-changes)` branch.
So It seems to occur because of 1ffca8f.

**Comment by mxcl** [comment]
I cannot reproduce with Xcode 7.3.1 and swift-2.2-minimal-changes:

![screen shot 2016-07-23 at 11 23 46 am](https://cloud.githubusercontent.com/assets/58962/17079533/f4c98728-50c7-11e6-9d13-f9ad41533a2e.png)

**Comment by mxcl** [comment]
I cannot fix this without a TestCase, if someone could help me out…

**Comment by mxcl** [comment]
Closing due to lack of responses.
