### ISSUE TITLE
Not able to create build for TV OS

### ISSUE THREAD

**Issue by mobileexpert1** [mxcl/PromiseKit#411]
Hello team,

I am using Promise kit in my application which is built for iOS, watch OS.
Now, i have added TV OS . I also added Promise Kit to Embedded Binaries to use this framework.
But when i click on Archive, my application is not showing in tv OS Apps but it shows in Other Items.
I need to remove Promise Kit library in order to create build for tv OS.
Please tell me solution for this.

Thanks

**Comment by mobileexpert1** [comment]
![screen shot 2016-04-27 at 4 20 36 pm](https://cloud.githubusercontent.com/assets/9291694/14854125/0c336664-0cac-11e6-8a88-fd15f05c37c5.png)
Here is the screenshot. This is not useful but it is just to show that how i added framework to Embedded Binaries.

**Comment by nathanhosselton** [comment]
Which version of PromiseKit are you using? How are you including it in your project (CocoaPods, Carthage, other...)?

**Comment by mobileexpert1** [comment]
I am using 3.1.1
I include it by downloading the project from github (https://github.com/mxcl/PromiseKit)
I drag the PromiseKit.xcodeproj into my project and framework in Embedded libraries and added PMKtvOS in target dependencies.
It is working for iOS and watch kit but not in tvOS while creating a build.
It is also working on debug time when i run on simulator in tvOS.

**Comment by mobileexpert1** [comment]
Hi,

Now, i am able to make a build because i just update the latest code from github. In this new update, it change the Build Settings SKIP_INSTALL to YES.
But, now i am not able to export build. It gives issue of Bitcode:-
failed to compile bitcode for MarqueeTV

Can you please guide me.

Thanks.

**Comment by mobileexpert1** [comment]
This helps me to resolve my issue:-
https://github.com/mxcl/PromiseKit/pull/408
