### ISSUE TITLE
Problem with Archive with Xcode Version 7.3.1 (7D1014)

### ISSUE THREAD

**Issue by maciejpigulski** [mxcl/PromiseKit#415]
I am having issues with creating an archive when using PromiseKit with the newest Xcode. When trying to run an archive task I get a following error:

`1.	While emitting IR SIL function @_TZFE10PromiseKitCSo20NSNotificationCenter4oncefSSCS_19NotificationPromise for 'once' at /Users/mpigulski/Development/PromiseKitArchiveTest/Pods/PromiseKit/Categories/Foundation/NSNotificationCenter+Promise.swift:22:12
Segmentation fault: 11
`

I have attached a test project that allows to reproduce this:
[PromiseKitArchiveTest.zip](https://github.com/mxcl/PromiseKit/files/248532/PromiseKitArchiveTest.zip)

So to reproduce use Xcode Version 7.3.1 (7D1014):
- open the project using PromiseKitArchiveTest.xcworkspace
- go for Product -> Archive

Archive will fail. Help.

**Comment by robm92** [comment]
Having the same issue after upgrading to 7.3.1 - my project can build correctly but will not archive.

**Comment by nathanhosselton** [comment]
Many thanks for the test project. Looking into this now and will get back on it ASAP.

**Comment by skyebook** [comment]
Can confirm issue in a CocoaPods project using 3.1.1

**Comment by komocode** [comment]
I never seem to learn to wait a few days before updating Xcode. Time to roll back...

**Comment by nathanhosselton** [comment]
Unfortunately I haven't had extensive time to research this today, though I am giving it as much time as I can. More than likely though this is simply a swift bug. And although there may be a way we can work around it in our code, it might be simpler to just revert to the prior version of Xcode for the time being or, if you're not using it, remove the NSNotificationCenter+Promise.swift file. In the meantime I will continue looking for a solution.

**Comment by mxcl** [comment]
IME this happens when there are multiple functions with the same name and different signatures.

**Comment by rad3ks** [comment]
Easy fix for everybody: https://github.com/rad3ks/PromiseKit/tree/bug/415

**Comment by nathanhosselton** [comment]
@rad3ks This doesn't work for me. I receive the same error whether I'm using your branch or modifying my own local source to match your changes. No sure why it is working for you.

A clash between the class method name and the instance method name would be weird anyway. I would expect much more to be breaking if that were the case. Then again, who knows what's really going on right now.

In my testing, commenting out the class `once` moved the seg fault down to the instance `once`. Commenting that one out only moved it down to the `init` on NotificationPromise. So a name clash does not appear to the be the issue.

**Comment by rad3ks** [comment]
I think I rush too much with this one. It worked (somehow) locally. I'm having this issue while running Tests and it just run and passed. I just noticed that CI failed, so sorry for the confusion.

I don't use these categories, so I'm removing those files from `bug/415` branch. Feel free to use it as a workaround if you *don't use* those categories.

**Comment by rlaferla** [comment]
Same issue today with Xcode 7.3.1

**Comment by rlaferla** [comment]
I just commented out the code (didn't use it) and it works.  Seems like this is one of many Xcode bugs.

**Comment by mnespor** [comment]
Seems like a new bug in Swift's type inference? Changing `public class NotificationPromise: Promise<[NSObject: AnyObject]>` to `public class NotificationPromise<T>: Promise<T>` prevents the segmentation fault

**Comment by hiromi2424** [comment]
@mnespor I tried such changes but other errors occurred.
Can you show full code/commit for fix that seg fault?

**Comment by mnespor** [comment]
@hiromi2424 My code is here: https://gist.github.com/mnespor/be0d60bfefc04e54608b3cf67cbf0c43. To be clear, this is an exploration of the problem, not a fix—it breaks anything that uses the NSNotificationCenter extension.

**Comment by esteluk** [comment]
There's a tracker for the compiler bug here: https://bugs.swift.org/browse/SR-1427

**Comment by lammertw** [comment]
The problem is also with CLLocationManager+Promise.swift

**Comment by mildm8nnered** [comment]
Sounds like this issue here: https://bugs.swift.org/browse/SR-1427

Looks like a swift compiler issue, first reported 8 days ago. I suspect that reverting to Xcode 7.3 for now will fix.

**Comment by MikeThomas1** [comment]
This can be fixed temporarily by setting the Swift Compiler Optimization Level for the Pods project to None. 

<img width="721" alt="screen shot 2016-05-20 at 10 17 10 am" src="https://cloud.githubusercontent.com/assets/1894995/15432543/49f3b678-1e74-11e6-8e2e-b4ccf0b0a74d.png">

**Comment by philippeauriach** [comment]
Another temporary fix if you dont use the particular class `NSNotificationCenter+Promise.swift` , I commented it in a fork : https://github.com/philippeauriach/PromiseKit/tree/fix-archive-xcode-7
You can use it with cocoapod :
    `pod 'PromiseKit', :git => 'https://github.com/philippeauriach/PromiseKit.git', :commit => '266cfeb5073277b757efc4a37aa049efc96c596f'`

**Comment by CFKevinRef** [comment]
Assuming you don't need that category, here's a `post_install` step for your `Podfile` that doesn't require switching to a fork:
```ruby
post_install do |installer|
    filename = 'Pods/PromiseKit/Categories/Foundation/NSNotificationCenter+Promise.swift'
    contents = '// This file removed due to Swift compiler bug https://bugs.swift.org/browse/SR-1427\\n'\
               '// PromiseKit tracking of this issue: https://github.com/mxcl/PromiseKit/issues/415\\n'
    system("rm -f #{filename}; printf \"#{contents}\" > #{filename}; chmod 444 #{filename}")
end
```
Sorry if there's a more standard way than dropping to bash, I'm not an expert in CocoaPods internals or Ruby for that matter.

**Comment by mxcl** [comment]
> I wonder do we really need
> 
>    extension NSNotificationCenter {
>.       public class func once(name: String) -> NotificationPromise
>.   }

I wish I hadn't added it considering this bug. But sadly we can’t remove it without breaking API compat. OTOH Swift makes keeping API guarantees impossible so maybe we should just drop it. Opinions? We could fix this today if we just removed it.

**Comment by dtartaglia** [comment]
It doesn't make a lot of sense to have it IMHO. Notifications are inherently multi-fire things but Promises aren't.

**Comment by nathanhosselton** [comment]
@mxcl In my testing, removing `once` did not resolve the issue.

**Comment by dtartaglia** [comment]
I pulled the entire file out of the library...

**Comment by mxcl** [comment]
> @mxcl In my testing, removing once did not resolve the issue.

Oh, do you know what is the problem then?

**Comment by nathanhosselton** [comment]
@dtartaglia ah right, with `once` gone there's nothing useful left in the file anyway.

**Comment by nathanhosselton** [comment]
@mxcl wasn't trying to be unconstructive. Misunderstood what you were proposing. Thought you were speaking only to removing `once`.

**Comment by nathanhosselton** [comment]
Removed my prior comments as they were just noise.

I have personally found `once` useful and also dislike the idea of a premature version bump. But if it gets the library back into an archivable state with the current Xcode version perhaps it's worth it.

**Comment by thomasbaldwin** [comment]
@MikeThomas1 setting optimization level to "none" doesn't seem to fix this issue for me when product archiving. I'm using PromiseKit through CocoaPods 3.0.0

**Comment by allen-zeng** [comment]
If you're using Cocoapods, and not using anything in the subspec `PromiseKit/Foundation`, a less hacky solution (not deleting files, changing repo etc.) is to split up the pods in your Podfile:
```ruby
pod 'PromiseKit/CorePromise'
pod 'PromiseKit/UIKit'
# etc.
```

**Comment by lvdaqian** [comment]
I need the subspec `PromiseKit/Foundation`. @MikeThomas1 's solution is working for me. But I am using Cocoapods and do not want to adjusting the pods project setting manually.
So I just add this script to my podfile and it works fine.
``` ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    next unless (target.name == 'PromiseKit')
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
    end
  end
end
```

**Comment by dtartaglia** [comment]
Another work around (if you are using the swift code) is to simply remove NSNotificationCenter+Promise.swift from the PromiseKit target.

**Comment by cesar-oyarzun-m** [comment]
I have the same problem, how can I fix this, I already try with changing the compiler level no luck @mxcl

**Comment by MartinJNash** [comment]
My team found a workaround for this issue. We don't explicitly need the swift versions of the NSNotification and CLLocationManager promise categories, so we commented out those files. The Objective-C versions work fine.

This worked for us in our mixed Swift and Objective-C environment. That said, we can't say how this will work for pure Swift environments.

**Comment by cesar-oyarzun-m** [comment]
anyone has some kind of solution for using podspec file?

**Comment by nathanhosselton** [comment]
Our sincerest apologies that this fix was over two months delayed. Things should be back to normal now with 3.2.1 which is currently being pushed to the Cocoapods trunk.

**Comment by nathanhosselton** [comment]
Well, during linting another seg fault occurrence was revealed. This appears it will be an issue everywhere that we use `pendingPromise()` in a subclass of `Promise`, which is 6 or 7 other places. The current fix I think could be applied in each case, but I'm going to research a little more to see if I can come up with a better fix and maybe identify the specific compiler issue to include in the open radar along the way. I won't delay much longer though, I promise.

**Comment by cesar-oyarzun-m** [comment]
thanks @nathanhosselton I really hope we can fix this I'm just waiting for this to publish my library

**Comment by nathanhosselton** [comment]
@cesar-oyarzun-m You should still be able to use Xcode 7.3

**Comment by nathanhosselton** [comment]
Found a better workaround. Patch incoming either later tonight or early tomorrow.

**Comment by nathanhosselton** [comment]
Alright, I _think_ we're good now. 3.2.1 has the fix and is live on the Cocoapods trunk.

Again, apologies to all and thanks for bearing with us.

**Comment by cesar-oyarzun-m** [comment]
yes I just test it and it works thanks!

**Comment by kaosdg** [comment]
Can confirm works on my projects as well.  Thanks for the hard work!

**Comment by joemcsorley** [comment]
In my Podfile I'm specifying `pod 'PromiseKit', '3.2.1'`, but I get an error on `pod install` indicating that version can't be found.

**Comment by rad3ks** [comment]
@joemcsorley specify `pod 'PromiseKit', '~> 3.2'` and run `pod install` if you didn't have PromiseKit or `pod update`.

**Comment by aziz-boudi4** [comment]
@rad3ks even though I specify `pod 'PromiseKit', '~> 3.2`and then run `pod install` I keep having `PromiseKit 3.2.0`being installed and not the desired `3.2.1'

`Analyzing dependencies
Downloading dependencies
Using DateTools (1.7.0)
Using Firebase (2.5.1)
Using OMGHTTPURLRQ (3.1.2)
**Installing PromiseKit 3.2.0 (was 3.2.0)**
Using SWXMLHash (2.1.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 5 dependencies from the Podfile and 5 total
pods installed.

**Comment by mxcl** [comment]
You want: `pod update PromiseKit`

**Comment by aziz-boudi4** [comment]
@mxcl When I do `pod update PromiseKit` I get this message : 

`Updating local specs repositories
Performing a deep fetch of the `master` specs repo to improve future performance`,
and it get stuck for a long time until I cancel it. 
Is it suppose to take a long time to fetch the repo ?

**Comment by aziz-boudi4** [comment]
@mxcl never mind, it just worked after multiple attempts

**Comment by johneke** [comment]
This might be a stupid question but I cannot find 3.2.1 in cocoa pods. cocoapods.org Says the latest version is 3.4.0 but when I do a `pod search PromiseKit` I only see version 3.1.1 as the latest

Not sure what I am missing :/

**Comment by esteluk** [comment]
@johneke as above, you should run `pod repo update` or similar to update your local cache.

**Comment by johneke** [comment]
@esteluk I knew it was a stupid question!! Thanks a lot, that worked! 👍
