### ISSUE TITLE
PromiseKit 3.1.1 fails to build for Release on Xcode 7.3.1 with Command failed due to signal: Segmentation fault: 11

### ISSUE THREAD

**Issue by clawoo** [mxcl/PromiseKit#420]
Hello

I just updated Xcode to 7.3.1 and noticed it will no longer build for release because of a segfault while compiling PromiseKit. I am using PromiseKit 3.1.1 installed via CocoaPods.

Steps to reproduce:
1. Create new Xcode Swift project
2. Add PromiseKit 3.1.1 via CocoaPods
3. Attempt to build for release.

Expected behavior:
Build would complete.

Actual behavior:
The compiler chokes because of something in the NSNotificationCenter+Promise.swift file.

My temporary solution was to comment out everything in the file above. Attached you can find the full output.

[log.txt](https://github.com/mxcl/PromiseKit/files/251154/log.txt)

**Comment by nathanhosselton** [comment]
Thanks for the report. Currently tracking in #415.

**Comment by LBPPlayer7** [comment]
Lol issue #420 lol.
