### ISSUE TITLE
Can't archive build with Xcode 7.3.1

### ISSUE THREAD

**Issue by dtartaglia** [mxcl/PromiseKit#421]
The compiler is crashing when it tries to archive NSNotificationCenter+Promise.swift `While emitting IR SIL function @_TZFE10PromiseKitCSo20NSNotificationCenter4oncefSSCS_19NotificationPromise for 'once' at /Users/dtartaglia/Projects/atticus-ios/Pods/PromiseKit/Categories/Foundation/NSNotificationCenter+Promise.swift:22:12`

**Comment by nathanhosselton** [comment]
Thanks. Currently tracking at #415.
