### ISSUE TITLE
Trouble importing NSURLSession into objective-c codebase

### ISSUE THREAD

**Issue by Slessi** [mxcl/PromiseKit#422]
Hi!

Successfully installed and imported your wonderful library with `#import <PromiseKit/PromiseKit.h>`.
Also successfully managed to use `[NSURLConnection GET:@"http://ww.magic.com"]`

However it doesn't seem like the `NSURLSession` extensions get imported. I saw in your API documentation that only Swift is mentioned, is it actually the case that I must be using Swift in order to use that particular class?

Asking cause I thought its ok to mix and match the languages. Tried using `@import PromiseKit;` also but didn't work, in fact it stopped `NSURLConnection` from working

p.s. I concede that I'm still a bit new to iOS, any help would be appreciated

**Comment by mxcl** [comment]
Yes we didn't write the `NSURLSession` categories for `ObjC`. If you need them then maybe you could write them?
