### ISSUE TITLE
Resolving promises synchronously

### ISSUE THREAD

**Issue by juanjo-ramos** [mxcl/PromiseKit#423]
I have a class that is a wrapper on top of an array in Swift where I want to guarantee the add, delete and fetch operations always happen on the main thread. So, I have something like this
```
private var array = [MyType]()

func addObject(myObject: MyType) -> Promise<Void> {
    return dispatch_promise(on: dispatch_get_main_queue(), body: { () -> () in
        firstly {
            self.fetchObject(myObject.id)
        }.then({ (existingObject) -> () in
            if let existingObject=existingObject {
                self.deleteObject(existingObject)
            }
            self.array.append(existingObject)
        })
    })
}

func deleteObject(myObject: MyType) -> Promise<Void> {
    return dispatch_promise(on: dispatch_get_main_queue(), body: { () -> () in
        if let i = self.array.indexOf(myObject) {
            self.array.removeAtIndex(i)
        }
    })
}
    
func fetchObject(id: String) -> Promise<MyType?> {
    return dispatch_promise(on: dispatch_get_main_queue(), body: { () -> MyType? in
        return self.array.filter({$0.id == id}).first
    })
}
```

My problem is on `addObject` that I would like the entire closure on `dispatch_promise` to resolve synchronously, blocking the main thread until they finish. So the promises in `firstly` and `then` inside `addObject` resolving synchronously and guarantee that no external call to `deleteObject` or `fetchObject` will be executed in between.

Is it possible to do that? Am I thinking about this completely wrong? I have tried exploring this with `when` but couldn't come up with any solution.

**Comment by mxcl** [comment]
Blocking the main thread just means Apple will reject your app and it will crash (you get 20 ish seconds of block time before the kernel ejects you).

So…

**Comment by mxcl** [comment]
We do provide `PMKHang()` in ObjC, but it is strictly meant for testing purposes.

**Comment by juanjo-ramos** [comment]
I don't want to create a deadlock, just to resolve 2 promises synchronously and on the same thread. So, when calling `addObject` the method doesn't return until both the promises in the `firstly` and `then` clauses have been resolved.

**Comment by mxcl** [comment]
So `when`? http://promisekit.org/when/

**Comment by mxcl** [comment]
This is probably a solution for you:

```swift
var addObjectPromise = Promise()

func addObject() -> Promise<Void> {
    addObjectPromise = addObjectPromise.then {
        return fetchObject()
    }.then { existingObject -> Promise<Void> in        
        self.array.append(existingObject)
        return self.deleteObject(existingObject)
    }
    return addObjectPromise
}

func deleteObject(myObject: MyType) -> Promise<Void> {
    return addObjectPromise.then {
        if let i = self.array.indexOf(myObject) {
            self.array.removeAtIndex(i)
        }
    }
}

func fetchObject(id: String) -> Promise<MyType> {
    return addObjectPromise.then {
    
        // throw instead of returning an Optional
        // -- promise chains should continue with successes only
    
        guard let obj self.array.filter {$0.id == id }.first else { throw Error.NoObject }
        return obj
    }
}
```

It's all main thread, this is the way you would use promises to do what you want. Feel free to ask any questions or re-open the ticket if you need more help.

**Comment by Lidbetter** [comment]
I have a similar need for a method in swift to block/wait for a promise to resolve...

I have a small library which expects data to take a while to build (or be retrieved over the network) and as such, ensures it is not being run on the main thread, it looks something like:
``` 
func load() {
    ...
    dispatch_async {
        data = self.closure()
        // do something with data
    }
}
```

Currently all of my API calls are promises, so I would like to run my regular api calls inside the closure and wait for the results, then return them.

Is there anyway this can be achieved?

**Comment by mxcl** [comment]
Look at the code in `PMKHang.m`, you can do something similar.

**Comment by mxcl** [comment]
I just discovered this which will allow you to wait on promises: https://github.com/yannickl/AwaitKit

**Comment by Lidbetter** [comment]
Thanks! Thats perfect for my usecase.
