### ISSUE TITLE
Typo "messaage"

### ISSUE THREAD

**Issue by TheArtOfEngineering** [mxcl/PromiseKit#424]
There appears to be a typo for one of the userInfo keys here:
https://github.com/mxcl/PromiseKit/blob/b6b129a56831a03a4a196fe70f7d8311040fa461/Sources/race.swift

**Comment by mxcl** [comment]
Good catch, a correct fix would be to specify both `@"message"` and `@"messsage"` so we are backwards combat just in case anyone depends on this key.
