### ISSUE TITLE
PromiseKit + cocoapods 1.0

### ISSUE THREAD

**Issue by jonasman** [mxcl/PromiseKit#427]
I'm having an issue that i cannot use promiseKit+CoreLocation extension and UIView extensions.
PromiseKit installs fine, but these extensions are not available. 

Is this a know issue or am i doing something wrong?

Pod list: 
```ruby
pod 'PromiseKit', '~> 3.0'
pod 'PromiseKit/CoreLocation'
```

XCode 7.3.1, cocoapods 1.0 .
PromiseKit 3.3.1 (latest from repo)

Reverted back to cocoapods 0.39 and the subspecs are loaded again.

**Comment by mxcl** [comment]
Sounds like a *the-horror!* CocoaPods bug.

**Comment by CFKevinRef** [comment]
That spec is somewhat ambiguous. Usually you would specify those dependencies like this:
```ruby
pod 'PromiseKit', '~> 3.0', :subspecs => [ 'UIKit', 'CoreLocation' ]
```
So that's worth a shot. Keep in mind that the default subspecs include Foundation and QuartzCore too.

**Comment by jonasman** [comment]
Same results. I'm guessing this is a bug with cocoapods. Can't get the subspecs to be installed with 1.0.

**Comment by thomasbaldwin** [comment]
I'm having a similar issue

**Comment by jonasman** [comment]
I reported this to cocoapods

**Comment by jonasman** [comment]
I created a completely clean project and it works fine. This is probably something else. Will close for now.

**Comment by thomasbaldwin** [comment]
I got it working by downgrading to cocoapods 0.37 and downgrading to Xcode 7.3.0 from 7.3.1

**Comment by jonasman** [comment]
Downgrading is not my fav

**Comment by jonasman** [comment]
I think the problem is only when updating cocoapods from 0.X to 1.0. Starting fresh works fine :)

**Comment by nathanhosselton** [comment]
@jonasman Interesting. Can anyone else having this problem confirm that a clean cocoapods install resolves the issue?

**Comment by jonasman** [comment]
the project at work still doesn't run. Not sure yet why. At home my projects work fine...
