### ISSUE TITLE
Error : Command failed due to signal : Segmentation fault: 11

### ISSUE THREAD

**Issue by arden** [mxcl/PromiseKit#430]
i'm run in Simulator it's work fine.
but i'm run Arachive, there some errors that:
Error : Command failed due to signal : Segmentation fault: 11

0  swift                    0x0000000109f7366b llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 43
1  swift                    0x0000000109f72956 llvm::sys::RunSignalHandlers() + 70
2  swift                    0x0000000109f73ccf SignalHandler(int) + 287
3  libsystem_platform.dylib 0x00007fff9865f52a _sigtramp + 26
4  libsystem_platform.dylib 0x00000000000003b4 _sigtramp + 1738149540
5  swift                    0x0000000107e0f16d emitApplyArgument((anonymous namespace)::IRGenSILFunction&, swift::SILValue, swift::SILParameterInfo, swift::irgen::Explosion&) + 365
6  swift                    0x0000000107e0e971 (anonymous namespace)::IRGenSILFunction::visitFullApplySite(swift::FullApplySite) + 2497
7  swift                    0x0000000107dfc23b swift::irgen::IRGenModule::emitSILFunction(swift::SILFunction*) + 9787
8  swift                    0x0000000107d575c8 swift::irgen::IRGenModuleDispatcher::emitGlobalTopLevel() + 600
9  swift                    0x0000000107de304e performIRGeneration(swift::IRGenOptions&, swift::ModuleDecl*, swift::SILModule*, llvm::StringRef, llvm::LLVMContext&, swift::SourceFile*, unsigned int) + 1278
10 swift                    0x0000000107de34f6 swift::performIRGeneration(swift::IRGenOptions&, swift::SourceFile&, swift::SILModule*, llvm::StringRef, llvm::LLVMContext&, unsigned int) + 70
11 swift                    0x0000000107cc6c8c performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&) + 15004
12 swift                    0x0000000107cc268d frontend_main(llvm::ArrayRef<char const*>, char const*, void*) + 2781
13 swift                    0x0000000107cbe0ac main + 1932
14 libdyld.dylib            0x00007fff8dbee5ad start + 1
15 libdyld.dylib            0x000000000000006a start + 1916869310
Stack dump:

**Comment by nathanhosselton** [comment]
Yep, this is currently being tracked in #415. Check out that thread for some workarounds while we either wait for Apple to fix this, or commit a workaround ourselves.
