### ISSUE TITLE
Question about -catchWithPolicy in Objective-C

### ISSUE THREAD

**Issue by mdhornet90** [mxcl/PromiseKit#431]
I'm not sure this is documented anywhere, but what does the syntax look like for calling -catchWithPolicy in Objective-C? I seem to get complier errors whenever I substitute it for -catch, namely that the block is expecting 2 args rather than 1.

**Comment by mxcl** [comment]
From the source code:

```objc
/**
 The provided block is executed when the receiver is rejected with the specified policy.
 @param policy The policy with which to catch. Either for all errors, or all errors *except* cancellation errors.
 @see catch
*/
- (AnyPromise * __nonnull(^ __nonnull)(PMKCatchPolicy, id __nonnull))catchWithPolicy;
```

Where `PMKCatchPolicy` is:

```objc
typedef NS_ENUM(NSInteger, PMKCatchPolicy) {
    PMKCatchPolicyAllErrors,
    PMKCatchPolicyAllErrorsExceptCancellation
};
```

So, per the declaration, the usage is:

```objc

promise.catchWithPolicy(PMKCatchPolicyAllErrors, ^(NSError *error){
    //…
});
```

**Comment by mdhornet90** [comment]
A simple case of my complete illiteracy. Thanks for the prompt response, and I love the library!
