### ISSUE TITLE
Archiving an app with promisekit crashes compiler

### ISSUE THREAD

**Issue by jonasman** [mxcl/PromiseKit#435]
<img width="833" alt="screen shot 2016-05-26 at 20 27 46" src="https://cloud.githubusercontent.com/assets/1762910/15583905/865f43f0-2380-11e6-8b09-a68264b348ad.png">

Does this happen to you too?

My solution was to comment out the NSNotificationCenter.swift code.

**Comment by mxcl** [comment]
Dupes #415. Please confirm.

**Comment by jonasman** [comment]
Yeap. Closing it down
