### ISSUE TITLE
PMKURLErrorFailingURLResponseKey not found in NSURLConnection promise error

### ISSUE THREAD

**Issue by KTachyon** [mxcl/PromiseKit#437]
I'm trying to check the status code coming from a REST API and, in the docs it says we should use PMKURLErrorFailingURLResponseKey to get the error response from the server, but on the NSError userInfo dictionary that key is not defined.

When I log the keys coming from the NSError instance's userInfo dictionary, I only get these keys:

`(
    NSErrorFailingURLStringKey,
    NSErrorFailingURLKey,
    PMKURLErrorFailingDataKey,
    NSUnderlyingError
)`

I'm having this behaviour both when using versions 1.5 and of PromiseKit 3.2. Haven't tested other versions.

**Comment by KTachyon** [comment]
It seems that this has something to do with NSURLConnection deprecations. I ended up creating a NSURLSession category that is pretty similar to the current NSURLConnection+AnyPromise implementation (attached).

[NSURLSession+AnyPromise.zip](https://github.com/mxcl/PromiseKit/files/289924/NSURLSession.AnyPromise.zip)

**Comment by nathanhosselton** [comment]
> It seems that this has something to do with NSURLConnection deprecations.

Can you elaborate?

If there is no key, then there was no `NSURLResponse` generated by the underlying `sendAsynchronousRequest:queue:completionHandler:` call on `NSURLConnection`. I'm not sure why this would happen, but you could set a breakpoint on line 91 of NSURLConnection+AnyPromise.m to verify.

**Comment by KTachyon** [comment]
> Can you elaborate?

`sendAsynchronousRequest:queue:completionHandler:` was deprecated on iOS 9.

> If there is no key, then there was no NSURLResponse generated by the underlying sendAsynchronousRequest:queue:completionHandler: call on NSURLConnection. I'm not sure why this would happen, but you could set a breakpoint on line 91 of NSURLConnection+AnyPromise.m to verify.

I'm not sure what you mean with "If there is no key", but the rsp (line 91) is nil.

**Comment by nathanhosselton** [comment]
> `sendAsynchronousRequest:queue:completionHandler:` was deprecated on iOS 9.

Right, I wouldn't expect that to affect the response though. That's why I asked if you had more insight.

> I'm not sure what you mean with "If there is no key", but the rsp (line 91) is nil.

We only create the `PMKURLErrorFailingURLResponseKey ` key in the userInfo dictionary when there is a corresponding value. In this case, response does not have a value.

**Comment by KTachyon** [comment]
Ok, but my problem is that there is a response. I'm returning a 401 status code from the REST API. I can get it with `curl -v`:

`< HTTP/1.1 401 Unauthorized
< Content-Type: text/html; charset=utf-8
< Date: Mon, 30 May 2016 18:22:18 GMT
< ETag: W/"c-4G0bpw8TMen5oRPML4h9Pw"
< Server: nginx/1.8.1
< X-Powered-By: Express
< Content-Length: 12
< Connection: keep-alive`

It works as expected if I use NSURLSession instead.

**Comment by mxcl** [comment]
Code example please.

**Comment by KTachyon** [comment]
I'm having the same issue on iOS 8.4 Simulator (besides 9.0 through 9.3). Code sample:

```
NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:[NSURL URLWithString:@"http://apps.testinsane.com/rte/401"]
                                                       cachePolicy:NSURLRequestReloadIgnoringCacheData
                                                   timeoutInterval:60.0];
        
[NSURLConnection promise:request].catch(^(NSError *error) {
    NSLog(@"%@", error.userInfo[PMKURLErrorFailingURLResponseKey]);
});
```

This is printing `(null)`, but if I run `curl http://apps.testinsane.com/rte/401 -v`, I get this:

```
*   Trying 143.95.247.15...
* Connected to apps.testinsane.com (143.95.247.15) port 80 (#0)
> GET /rte/401 HTTP/1.1
> Host: apps.testinsane.com
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< Cache-Control: no-cache
< Pragma: no-cache
< Expires: -1
< Server: Microsoft-IIS/8.0
< X-AspNet-Version: 4.0.30319
< Date: Wed, 01 Jun 2016 10:46:11 GMT
< Content-Length: 0
< 
* Connection #0 to host apps.testinsane.com left intact
```

It also works as expected if I use NSURLSession. If I add the promise categories I have posted before, I'm getting the correct behaviour:

```
NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:[NSURL URLWithString:@"http://apps.testinsane.com/rte/401"]
                                                       cachePolicy:NSURLRequestReloadIgnoringCacheData
                                                   timeoutInterval:60.0];
    
[NSURLConnection promise:request].catch(^(NSError *error) {
    NSLog(@"NSURLConnection: %@", error.userInfo[PMKURLErrorFailingURLResponseKey]);
});

[NSURLSession promise:request].catch(^(NSError *error) {
    NSLog(@"NSURLSession: %@", error.userInfo[PMKURLErrorFailingURLResponseKey]);
});
```

Result:
```
2016-06-01 11:53:35.282 SamplePMKBugProject[6429:4127293] NSURLSession: <NSHTTPURLResponse: 0x7a21df80> { URL: http://apps.testinsane.com/rte/401 } { status code: 401, headers {
    "Cache-Control" = "no-cache";
    "Content-Length" = 0;
    Date = "Wed, 01 Jun 2016 10:54:34 GMT";
    Expires = "-1";
    Pragma = "no-cache";
    Server = "Microsoft-IIS/8.0";
    "X-AspNet-Version" = "4.0.30319";
} }
2016-06-01 11:53:35.284 SamplePMKBugProject[6429:4127293] NSURLConnection: (null)
```

I'm using XCode 7.3.1 (7D1014). Sample project attached. 

[SamplePMKBugProject.zip](https://github.com/mxcl/PromiseKit/files/293223/SamplePMKBugProject.zip)

**Comment by mxcl** [comment]
Here's the code: https://github.com/mxcl/PromiseKit/blob/master/Categories/Foundation/NSURLConnection%2BAnyPromise.m#L82-L177

As @nathanhosselton says, it will only be `nil` if it is not set.

I will try a non-promised NSURLConnection and see if I get a `URLResponse`.

**Comment by mxcl** [comment]
I made a test project: https://www.dropbox.com/sh/6w1bvpomjpo6sf6/AAA81bFuPMTG255ujK-UmPWha?dl=0

The `NSURLResponse` is indeed `nil`, so there's nothing we can do.

![screen shot 2016-07-23 at 2 27 45 am](https://cloud.githubusercontent.com/assets/58962/17077233/3d624236-507d-11e6-94d6-fe032cfd8efb.png)
