### ISSUE TITLE
Crashed: NSOperationQueue - URLDataPromise

### ISSUE THREAD

**Issue by lammertw** [mxcl/PromiseKit#440]
I'm receiving this crash in 2 completely different apps. So I would asume other people also encountered this issue and was first of all wondering if anyone knows the cause and second if it can be fixed.

Crashed: NSOperationQueue 0x175f8d30 :: NSOperation 0x1b5a9410 (QOS: LEGACY)
EXC_BREAKPOINT 0x00000000e7ffdefe

Crash log:

    Crashed: NSOperationQueue 0x175f8d30 :: NSOperation 0x1b5a9410 (QOS: LEGACY)
    0  PromiseKit                     0x55d854 _TFFZFC10PromiseKit14URLDataPromise2goFTCSo12NSURLRequest4bodyFFTGSqCSo6NSData_GSqCSo13NSURLResponse_GSqCSo7NSError__T_T__S0_U_FTFS2_T_FPs9ErrorType_T__T_U_FTGSqS2__GSqS3__GSqS4___T_ + 780
    1  PromiseKit                     0x55cf60 _TPA__TFFZFC10PromiseKit14URLDataPromise2goFTCSo12NSURLRequest4bodyFFTGSqCSo6NSData_GSqCSo13NSURLResponse_GSqCSo7NSError__T_T__S0_U_FTFS2_T_FPs9ErrorType_T__T_U_FTGSqS2__GSqS3__GSqS4___T_ + 144
    2  PromiseKit                     0x55cf60 _TPA__TFFZFC10PromiseKit14URLDataPromise2goFTCSo12NSURLRequest4bodyFFTGSqCSo6NSData_GSqCSo13NSURLResponse_GSqCSo7NSError__T_T__S0_U_FTFS2_T_FPs9ErrorType_T__T_U_FTGSqS2__GSqS3__GSqS4___T_ + 144
    3  CFNetwork                      0x21007399 __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 16
    4  CFNetwork                      0x21016b83 __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 278
    5  Foundation                     0x21311659 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 8
    6  Foundation                     0x21272723 -[NSBlockOperation main] + 146
    7  Foundation                     0x21264cf9 -[__NSOperationInternal _start:] + 768
    8  Foundation                     0x21313911 __NSOQSchedule_f + 192
    9  libdispatch.dylib              0x2067a423 _dispatch_queue_drain$VARIANT$mp + 1758
    10 libdispatch.dylib              0x20679a61 _dispatch_queue_invoke$VARIANT$mp + 284
    11 libdispatch.dylib              0x2067c15d _dispatch_root_queue_drain + 396
    12 libdispatch.dylib              0x2067bfcd _dispatch_worker_thread3 + 96
    13 libsystem_pthread.dylib        0x20831b29 _pthread_wqthread + 1024
    14 libsystem_pthread.dylib        0x20831718 start_wqthread + 8

**Comment by mxcl** [comment]
Hard to debug without some idea of the input that causes it. Unless you're saying it happens for all NSURLSession promise usage?

**Comment by lammertw** [comment]
It only happens once and a while and I have no idea under which conditions since I never ran into it myself. I also see it back at crash reports.

**Comment by mxcl** [comment]
I think this was: #323
