### ISSUE TITLE
Question About Pending Promises

### ISSUE THREAD

**Issue by mdhornet90** [mxcl/PromiseKit#441]
Bear with me while I try to articulate what my ask is. I'm making a call to a service to retrieve a valid access token. This might take a second or so, so I return a promise that will be fulfilled when I get the response back. This is assuming the token is invalid: I cache the value and as long as it's not due to expire the promise returns almost immediately. This is a typical use case so no big deal.

What I'm having a hard time wrapping my head around is the following: the above scenario happens when the app detects midnight happened. I also have the above request happen when I come to the foreground. The result is that the call to request the token happen one after the other. 

What I'd like to do is ensure that the second request will wait for the result of the first request to complete (instead of making two separate network requests), and then used the cached value when it's ready.

Can I accomplish this by returning the same promise to both of these requests? Is this even something that can be accomplished with promises? I'll do my best to fix any misunderstandings with the above explanation.

**Comment by mxcl** [comment]
Yes, sounds like you should return the same `Promise` in both cases. This is fine, you can `then` off a promise as many times as you like.

**Comment by mdhornet90** [comment]
Works exactly as advertised. Thanks for the guidance!
