### ISSUE TITLE
Archiving with PromisKit (3.2.0) using Cocoapods (1.0.1)

### ISSUE THREAD

**Issue by baltameme** [mxcl/PromiseKit#446]
I was trying to Archive a new build for a project contains PromistKit version (3.2.0 ) with Cocoapods (1.0.1). however, I get every time a compilation error while archiving:

CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
  
1.	While emitting IR SIL function @_TZFE10PromiseKitCSo20NSNotificationCenter4oncefSSCS_19NotificationPromise for 'once' at /Developer/iOS/Offical Projects/DawriPlus/Pods/PromiseKit/Categories/Foundation/NSNotificationCenter+Promise.swift:22:12

<unknown>:0: error: unable to execute command: Segmentation fault: 11
<unknown>:0: error: compile command failed due to signal (use -v to see invocation)

Please, not that I do not use this file  "NSNotificationCenter+Promise.swift" but I made a fork for the Kit's repository and deleted this file and it worked with me fine. However, I want to use the actual repository to keep updated with any changes.

**Comment by mxcl** [comment]
Dupes #415?

**Comment by baltameme** [comment]
Yes it's the same case with the same Xcode version...
