### ISSUE TITLE
CLLocationManager extension can call reject multiple times

### ISSUE THREAD

**Issue by tcunning** [mxcl/PromiseKit#450]
1. In the iOS-9 simulator don't set a default location 
2. Invoke CLLocationManager.promise(.WhenInUse).then { ... }
3. Allow location services
4. The locationManager delegate didFailWithError is getting called twice by location manager.   This is causing the PromiseKit reject method (see CLLocationManager+Promise.swift line 64) to get called twice which cases the following warning:

PromiseKit: Warning: reject called on already rejected Promise: Error Domain=kCLErrorDomain Code=0 "(null)"

**Comment by tcunning** [comment]
Looks like this is resolved in the latest

**Comment by tcunning** [comment]
This issue only effects the swift implementation as the objective-c implementation shuts down the location manager after an error occurs.

**Comment by mxcl** [comment]
Merged: https://github.com/mxcl/PromiseKit/commit/633fa83ca0c309dc54837db889fab820db5f27a3
