### ISSUE TITLE
PromiseKit + Swift 3 + Xcode 8

### ISSUE THREAD

**Issue by warpling** [mxcl/PromiseKit#451]
Xcode 8 now requires Swift 2.3/3.0
@mxcl can't contribute to the project as far as I understand. Is anyone out there actively working on the minor transition to 2.3 or the somewhat more major transition to 3.0? I would offer to help myself if I felt more confident about PromiseKit and Swift's internals. 😰 

I've been trying to build with @TheArtOfEngineering's [3.0 branch](https://github.com/mxcl/PromiseKit/pull/425) but think it may be out of date syntactically at this point?

**Comment by mxcl** [comment]
There will be a branch provided asap.

**Comment by TheArtOfEngineering** [comment]
@warpling That is certainly possible. I was working off of a Swift 3.0 development branch prior to the Preview 1 release. I would be willing to work on a Swift 3.0 transition if I can steal away some time.

**Comment by warpling** [comment]
@TheArtOfEngineering That'd be great! If the only thing in that branch needing a refresh is the syntax I can try to take a stab at it, but as mentioned I unfortunately haven't kept up with Swift much at all.

**Comment by nathanhosselton** [comment]
I have a minimal changes branch for Swift 3.0 incoming. Better updates to follow.

**Comment by warpling** [comment]
@nathanhosselton eagerly looking forward to it :)

**Comment by nathanhosselton** [comment]
Up at https://github.com/mxcl/PromiseKit/tree/4.0.0-beta1

**Comment by warpling** [comment]
Fantastic! Installing…

**Comment by warpling** [comment]
Hitting some build issues in `NSURLConnection+Promise.swift`

Did you use any special config in your podfile?
I'm currently using:
````
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|

      # Turn off code signing (is this a bad thing?)
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"

      # (May be able to remove eventually: https://github.com/CocoaPods/CocoaPods/issues/5521)
      config.build_settings['SWIFT_VERSION'] = "3.0"

      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
  end
end
````

**Comment by nathanhosselton** [comment]
What are the build errors?

**Comment by warpling** [comment]
Guessing it's the symptom of something else? 
![image](https://cloud.githubusercontent.com/assets/220240/16286501/a3c6954e-3891-11e6-817e-4871790d6daf.png)

**Comment by nathanhosselton** [comment]
Yes unfortunately our dependencies need updated as well. So those categories/extensions which depend on third party libraries (such as NSURLConnection/Session) will not compile for now. OMG is ours and so that will be updated next, but the other two are beyond our control. Such is the nature of these things.

**Comment by warpling** [comment]
Got it. What do you think would be the easiest way to get PromiseKit compiling in Xcode 8 so I can work on a project? Should I try to make a 2.3 branch from the 2.2 minimal changes branch?

**Comment by nathanhosselton** [comment]
You can remove those categories. They are unnecessary for core PK.

**Comment by warpling** [comment]
Cool, that's what I was just looking into :)
What would be the best way to do that? Fork and remove them entirely?

**Comment by nathanhosselton** [comment]
Actually I was wrong. This is something I overlooked. Apologies. I will get it updates ASAP.

**Comment by nathanhosselton** [comment]
Updated and pushed. Try it now @warpling.

**Comment by warpling** [comment]
It compiles!! Thank you so much @nathanhosselton 😊
Just to confirm for future readers, there currently is no Swift 2.3 branch right?

**Comment by nathanhosselton** [comment]
Not yet. Hopefully soon. Not really sure what Apple is planning with 2.3 vs 3.0 in terms of Xcode 8 GM. If both are available and non "beta" at that point in time then 2.3 support will probably be merged in for the final PMK 3.x release, with Swift 3.0 support rolled into the PMK 4.0 official release at the same time.

**Comment by warpling** [comment]
Sounds like a plan!
For what it's worth, when I tried doing a conversion to 2.3 I'm pretty sure Xcode 8 told me that swift 2.3 was supported but would be deprecated in the future (insinuating Xcode 9?).

**Comment by djtarazona** [comment]
Ya, at WWDC they informed us Xcode 8 will support both Swift 2 and 3.

**Comment by nathanhosselton** [comment]
There is now a `swift-2.3` branch which should compile.

**Comment by mxcl** [comment]
Ideally PMK4 would support both with `#if`. Pragmatically, I think it would make the code unmaintainable.

**Comment by sryze** [comment]
Sorry for the dumb question, I haven't used PromiseKit in Swift yet, but is there any particular reason why the CorePromise module is not written in Objective-C for maximum compatibility, except strongly typed promises?

**Comment by mxcl** [comment]
Many Swift types cannot be represented by `id` so it would be impossible to use those types in Swift if the core was ObjC. If you need a pure ObjC version of PromiseKit we still maintain version 1.

**Comment by nathanhosselton** [comment]
New branch up with changes for Xcode 8 beta 2: https://github.com/mxcl/PromiseKit/tree/4.0.0-beta2

**Comment by warpling** [comment]
@nathanhosselton you're awesome. Downloading the new beta now; just came here to check ;)
