### ISSUE TITLE
Have onError return a promise

### ISSUE THREAD

**Issue by gsabran** [mxcl/PromiseKit#461]
Would it be possible to have `onError` / `error` return a promise instead of `Void` ?

This is what is happening in javascript (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch) and it's very convenient to keep chaining promises.

**Comment by mxcl** [comment]
We have `recover` for this.

**Comment by gsabran** [comment]
Ah nice! Plus it's in the docs :)
