### ISSUE TITLE
Backtrace not available for PromiseKit calls due to dispatch_async

### ISSUE THREAD

**Issue by programmerdave** [mxcl/PromiseKit#462]
Since PromiseKit uses dispatch_async, it's difficult to get a backtrace to know who called the method for error logging. Has anyone else come across this issue?

**Comment by mxcl** [comment]
Try setting `PMKSetDefaultDispatchQueue(zalgo)`, this will reduce the amount of `dispatch_async`. **Do not do this in production code** (see: http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony)

**Comment by mxcl** [comment]
I have updated the documentation for PMK4 to suggest the above trick.
