### ISSUE TITLE
Cocoapods compiler issue

### ISSUE THREAD

**Issue by cesar-oyarzun-m** [mxcl/PromiseKit#463]
Hi, I'm using cocoapods for my library but when I try to do `pod lib lint` I get compiler error from a promise kit class, here is the log 

    ** BUILD FAILED **

    The following build commands failed:
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal x86_64 /var/folders/mr/msg44lgs0gqg_2y508cl685w0000gn/T/CocoaPods/Lint/Pods/PromiseKit/Categories/Foundation/NSNotificationCenter+Promise.swift

her is my podspec
 
  
    Pod::Spec.new do |s|
      s.name             = "ExpSwift"
      s.version          = "1.0.2"
      s.summary          = "Exp IOS SDK library. Native IOS library for EXP platform."

      s.description      = "Exp IOS SDK library. Native IOS library for EXP platform will allow you to   communicate directly to EXP platform."

      s.homepage         = "https://github.com/ScalaInc/exp-ios-sdk"
      # s.screenshots     = "www.example.com/screenshots_1", "www.example.com/screenshots_2"
      s.license          = 'MIT'
      s.author           = { "Cesar Oyarzun" => "cesar.oyarzun@scala.com" }
      s.source           = { :git => "https://github.com/ScalaInc/exp-ios-sdk.git", :tag => 'v1.0.2' }
      # s.social_media_url = 'https://twitter.com/<TWITTER_USERNAME>'

      s.platform     = :ios, '8.0'
      s.requires_arc = true

      s.source_files = 'Pod/Classes/**/*'
 

      # s.public_header_files = 'Pod/Classes/**/*.h'
      # s.frameworks = 'UIKit', 'MapKit'
       s.dependency 'PromiseKit','3.0.0'
       s.dependency 'Alamofire','3.1.5'
       s.dependency 'Socket.IO-Client-Swift','4.1.2'
       s.dependency 'JSONWebToken','1.4.1'
     end

**Comment by mxcl** [comment]
Dupes #415
