### ISSUE TITLE
PromiseKit is not compatible with Swift 3.0

### ISSUE THREAD

**Issue by ldiqual** [mxcl/PromiseKit#464]
Compiling with Xcode 8 beta 1 triggers 76 issues. It would be great to have a swift-3.0 branch that we could clone.

**Comment by nathanhosselton** [comment]
Our `4.0.0-beta` branches are Swift 3.0 compatable.

**Comment by ldiqual** [comment]
@nathanhosselton Oh cool, thanks for the tip! Closing
