### ISSUE TITLE
Error Handling Bridging Promise<T> to AnyPromise

### ISSUE THREAD

**Issue by zachbai** [mxcl/PromiseKit#470]
I'm having trouble handling errors when bridging a Promise<T> to an AnyPromise in Swift- 

For ex:
```
func p() -> Promise<String> { 
//do some stuff
}

let a = AnyPromise(bound: p())

a.then {
//do some more stuff 
}.catch {
//handle error - how can I do this?
}
```

The issue seems to be in bridging Promise -> AnyPromise. The compiler won't let me use .recover/.error, and I can't seem to find any resources that cover this. Any help is much appreciated.

**Comment by mxcl** [comment]
`then` in swift returns Promise. So error and recover should be available. If they are not then something has gone with your build. Please provide complete build details.

**Comment by zachbai** [comment]
thanks- this resolved my issue; didn't realize I had to definitely use `then` to first return a Promise from the AnyPromise.

**Comment by mxcl** [comment]
Oh right, yeah `AnyPromise` has no catch in Swift.
