### ISSUE TITLE
Branch Xcode8-beta3 does not compile

### ISSUE THREAD

**Issue by cyrille-legrand** [mxcl/PromiseKit#474]
When testing a minimal integration of PromiseKit (branch Xcode-8-beta, commit d2e76e6) on a new, empty project, it does not compile.

Here are the errors:

`PromiseKit/Categories/Foundation/NSURLConnection+Promise.swift:69:31: Cannot convert return expression of type 'Promise<Data>' to return type 'URLDataPromise'`

`PromiseKit/Categories/Foundation/NSURLSession+Promise.swift:55:105: Cannot call value of non-function type 'URLSession'`

`PromiseKit/Categories/Foundation/NSURLSession+Promise.swift:68:31: Cannot convert return expression of type 'Promise<Data>' to return type 'URLDataPromise'`

`PromiseKit/Categories/UIKit/UIViewController+Promise.swift:34:36: Missing argument for parameter 'animated' in call`

`PromiseKit/Categories/UIKit/UIViewController+Promise.swift:47:40: Missing argument for parameter 'animated' in call`

Podfile:

```
# Project Configuration
workspace 'PKTest'
project   'PKTest.xcodeproj'
platform :ios, '9.0'

## Settings
inhibit_all_warnings!
use_frameworks!

abstract_target 'defaults' do
  pod 'PromiseKit', :git => 'https://github.com/mxcl/PromiseKit', :branch => 'Xcode-8-beta'
  target 'PKTest'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
```

**Comment by cyrille-legrand** [comment]
Much better now, thanks.

Two errors remain, though:

`PromiseKit/Categories/UIKit/UIViewController+Promise.swift:34:36: Missing argument for parameter 'animated' in call`

`PromiseKit/Categories/UIKit/UIViewController+Promise.swift:47:40: Missing argument for parameter 'animated' in call`

They're the same, on

    let p: Promise<T> = promise(vc)

**Comment by mxcl** [comment]
Cannot reproduce this other error with my initial tests.

**Comment by Gerst20051** [comment]
Same Here @cyrille-legrand Screenshot Attached

![screenshot 2016-07-21 19 27 44](https://cloud.githubusercontent.com/assets/235372/17041880/548e0cd0-4f77-11e6-82fd-9c7cd683cf7d.png)

**Comment by Gerst20051** [comment]
I don't know if it still works as expected or if this is even a good solution but I got rid of the error by changing the line:

`let p: Promise<T> = promise(vc)`

to:

`let p: Promise<T> = promise(vc, animated: false, completion: nil) as! Promise<T>`

**Comment by mxcl** [comment]
This doesn't make sense, we don't provide a function with that signature anywhere.

**Comment by mxcl** [comment]
I understand the issue, the objective-c variant is being imported by the new Swift importer from `promiseViewController` to `promise(_ viewController:` though that is surprising since it shouldn't drop the parameter name. Whatever I have a fix coming.
