### ISSUE TITLE
Undefined symbols for architecture arm64: v3.2.1

### ISSUE THREAD

**Issue by cesar-oyarzun-m** [mxcl/PromiseKit#476]
Hi I just updated to the last version 3.2.1 and I get a compiler error, but only if I add new methods to my existing classes if I use methods that are already there I don't have compiler issue. These was working on previous version.

        Undefined symbols for architecture arm64:
       "ExpSwift.Feed.getData ([Swift.String : Swift.AnyObject]) ->     PromiseKit.Promise<Swift.AnyObject>", referenced from:
        ExpSwift_Example.ViewController.(viewDidLoad () -> ()).(closure #1).(closure #3) in  ViewController.o
       ld: symbol(s) not found for architecture arm64
       clang: error: linker command failed with exit code 1 (use -v to see invocation)

here is my code

     ExpSwift.findFeeds(["limit":2, "skip":0, "sort":"name"]).then { (feeds: SearchResults<Feed>) -> Void in
                            for feed in feeds.getResults() {
                                debugPrint(feed.get("name"))
                                feed.getData(["name":"test"]).then { (data) -> Void in
                                    print(data)
                                }
                }
                }.error { error in
                    debugPrint(error)
            }

Here is my project config
<img width="923" alt="screen shot 2016-07-21 at 2 51 03 pm" src="https://cloud.githubusercontent.com/assets/7967891/17034900/a7ab1856-4f52-11e6-8ab6-560fd2df423e.png">

Here is my pod config
<img width="923" alt="screen shot 2016-07-21 at 2 51 13 pm" src="https://cloud.githubusercontent.com/assets/7967891/17034899/a7a959d0-4f52-11e6-8ec7-5d998c04fe3a.png">

**Comment by mxcl** [comment]
Sounds like you need a clean build.

**Comment by cesar-oyarzun-m** [comment]
@mxcl I did try with a new clean build, the same problem. Do you think maybe something with overload a method? 

    /**
     Get output from Feed
     @return Promise<AnyObject>.
     */
    public func getData() ->Promise<AnyObject>{

        return Promise { fulfill, reject in
            Alamofire.request(Router.getFeedData(uuid))
                .responseJSON {response in
                    switch response.result {
                    case .Success(let data):
                        fulfill(data)
                    case .Failure(let error):
                        return reject(error)
                    }
                }
        }
    }
    
    /**
     Get output from Feed
     @return Promise<AnyObject>.
     */
    public func getData(query:[String:AnyObject]) ->Promise<AnyObject>{
        
        return Promise { fulfill, reject in
            Alamofire.request(Router.getDynamicFeedData(uuid,query))
                .responseJSON {response in
                    switch response.result {
                    case .Success(let data):
                        fulfill(data)
                    case .Failure(let error):
                        return reject(error)
                    }
            }
        }
    }

**Comment by mxcl** [comment]
K, looking properly I see that the missing symbol is from your code:

    Undefined symbols for architecture arm64:
   "ExpSwift.Feed.getData ([Swift.String : Swift.AnyObject]) ->     PromiseKit.Promise<Swift.AnyObject>

The missing symbol is `Feed.getData(_: [String: AnyObject])`.

Did you also upgrade the compiler when you upgraded PromiseKit? Possibly the compiler is mis-compiling this function. Try renaming it.

**Comment by mxcl** [comment]
Is it possible you haven't added `ExpSwift` to the link phase of `ExpSwift_Example`?

**Comment by cesar-oyarzun-m** [comment]
hey I just clean and build like 5 times and now it works, also I need to do pod update anytime that if I change something on my code, it crash almost every time, but I make it work, thanks

**Comment by mxcl** [comment]
There's definitely a bug in either Xcode, CocoaPods or the Swift compiler here.
