### ISSUE TITLE
Import PromiseKit issue with Carthage

### ISSUE THREAD

**Issue by simonnarang** [mxcl/PromiseKit#478]
I installed PromiseKit for Swift 3 via Carthage: `github "mxcl/PromiseKit" "swift-3.0"`  
However, when I try to do `import PromiseKit` i get an error. 
Also... When trying to add the PromiseKit framework to embedded binaries the `.framework` doesn't show up in the `Build` folder of Carthage, any idea as to what is going on?  
  
Thanks,
Simon

**Comment by simonnarang** [comment]
### Solved
-
I just dragged in the xcodeproj and then the framework showed up 😂

**Comment by simonnarang** [comment]
I am still unable to import

**Comment by mxcl** [comment]
Please specify the exact error message.

**Comment by simonnarang** [comment]
![screen shot 2016-07-26 at 4 43 00 pm](https://cloud.githubusercontent.com/assets/9156815/17154666/0e399812-5350-11e6-9545-1b2d9e0ca41e.png)

**Comment by simonnarang** [comment]
@mxcl

**Comment by mxcl** [comment]
Did you add PromiseKit to your app's dependencies? Seems it is not being built.

**Comment by mxcl** [comment]
Oh OK, Carthage. So, with Carthage you don't drag in the project. You need to add PromiseKit.framework that is built in the `Carthage/Build/` directory to your app’s “Build Phases” link libraries section. Then it will import. Further docs at Carthage's website.

**Comment by simonnarang** [comment]
![screen shot 2016-07-27 at 8 34 42 am](https://cloud.githubusercontent.com/assets/9156815/17175343/0b342a9e-53d5-11e6-9a49-a7ef41567526.png)
Sorry to bother you again but I have done this and it still won't import

**Comment by simonnarang** [comment]
I am using the Swift-3.0 branch if that helps

**Comment by mxcl** [comment]
I just created a new Xcode 8 beta xcodeproj and added a `Cartfile`:

    github "mxcl/PromiseKit" "swift-3.0"

After `carthage bootstrap` I dragged the iOS `PromiseKit.framework` into “embedded frameworks” in the Project settings. I added `import PromiseKit` to one of my swift files and added some PromiseKit code. Built, ran. It works.

So… it should work.

**Comment by simonnarang** [comment]
I put only `github "mxcl/PromiseKit" "swift-3.0"` into my cartfile and ran `carthage bootstrap`
Unfortunately I still get the error:
```
** BUILD FAILED **
The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
```
Here are some of the errors:
`/Carthage/Checkouts/PromiseKit/Sources/URLDataPromise.swift:60:119: error: variable binding in a condition requires an initializer`  
`/Carthage/Checkouts/PromiseKit/Sources/URLDataPromise.swift:62:38: error: boolean condition requires 'where' to separate it from variable binding`  
`/Carthage/Checkouts/PromiseKit/Sources/Zalgo.swift:69:46: error: function produces expected type 'Bool'; did you mean to call it with '()'?`

**Comment by mxcl** [comment]
You didn't `sudo xcode-select --switch /Applications/Xcode-beta.app` first. It's compiling with swift 2.2.

**Comment by simonnarang** [comment]
Ok thanks

**Comment by mxcl** [comment]
Is your problem solved?

**Comment by mxcl** [comment]
Re-open if not solved. Thanks.

**Comment by simonnarang** [comment]
Thanks for the recommendation!
I *only* have the beta of Xcode, so when I ran the command you suggested I switched `xcode-beta.app` to `Xcode.app`
Unfortunately, the error is still persisting😅
Could it have something to do with me using https://github.com/kylef/swiftenv?
I set the local swift version in the directory of my project to 3.0 via swiftenv, so I assumed it would not affect anything

**Comment by simonnarang** [comment]
@mxcl I am not a collaborator so I cannot re-open issues

**Comment by simonnarang** [comment]
@mxcl, I am okay not using Carthage, originally I just dragged in the xcodeproj and imported the framework to the embedded binaries, but I am still wondering why I cannot `import PromiseKit` in my `.swift` files.
Thanks for the help!

**Comment by simonnarang** [comment]
By the new method after adding the framework to embedded binaries I get the error `clang: error: no such file or directory: '/Users/Si/Library/Developer/Xcode/DerivedData/Toast-gezugqvyoyexybguzmdcmqmarefs/Build/Products/Debug-iphonesimulator/PromiseKit.framework/PromiseKit'`

**Comment by mxcl** [comment]
* Don’t drag the xcodeproj into your project with Carthage. I suggest deleting it from your project
* Ensure you drag the correct `.framework` into your embedded binaries section, You need to drag the iOS one.

**Comment by simonnarang** [comment]
No, I am not using Carthage, I could not get that to work so I just manually dragged in the xcodeproj.
The framework I got doing that is giving the error I showed
