### ISSUE TITLE
Not work with CARTHAGE

### ISSUE THREAD

**Issue by rmuhamedgaliev** [mxcl/PromiseKit#479]
> The following build commands failed:
> 	Ld /Users/rinatmuhamedgaliev/Library/Developer/Xcode/DerivedData/PromiseKit-gjsrfcjglnkexhfxuvrzdcwyboqg/Build/Intermediates/PromiseKit.build/Release-iphoneos/PMKiOSUITestsHost.build/Objects-normal/armv7/PMKiOSUITestsHost normal armv7
> 	Ld /Users/rinatmuhamedgaliev/Library/Developer/Xcode/DerivedData/PromiseKit-gjsrfcjglnkexhfxuvrzdcwyboqg/Build/Intermediates/PromiseKit.build/Release-iphoneos/PMKiOSUITestsHost.build/Objects-normal/arm64/PMKiOSUITestsHost normal arm64
> (2 failures)
> A shell task (/usr/bin/xcrun xcodebuild -project /Users/rinatmuhamedgaliev/Projects/xxxxxx-client/Carthage/Checkouts/PromiseKit/PromiseKit.xcodeproj -scheme PMKiOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	Ld /Users/rinatmuhamedgaliev/Library/Developer/Xcode/DerivedData/PromiseKit-gjsrfcjglnkexhfxuvrzdcwyboqg/Build/Intermediates/PromiseKit.build/Release-iphoneos/PMKiOSUITestsHost.build/Objects-normal/armv7/PMKiOSUITestsHost normal armv7
> 	Ld /Users/rinatmuhamedgaliev/Library/Developer/Xcode/DerivedData/PromiseKit-gjsrfcjglnkexhfxuvrzdcwyboqg/Build/Intermediates/PromiseKit.build/Release-iphoneos/PMKiOSUITestsHost.build/Objects-normal/arm64/PMKiOSUITestsHost normal arm64
> (2 failures)

**Comment by JeanAzzopardi** [comment]
I'm having the same issue.

I checked in the logs, I think the issue could lie in the PMKiOSUITestsHost:

`Ld /Users/XXX/Library/Developer/Xcode/DerivedData/PromiseKit-dzbgegkpvalpmqdgfvdnvsgwbmgj/Build/Intermediates/PromiseKit.build/Release-iphoneos/PMKiOSUITestsHost.build/Objects-normal/armv7/PMKiOSUITestsHost normal armv7
    cd /XXX/Carthage/Checkouts/PromiseKit
    export IPHONEOS_DEPLOYMENT_TARGET=8.3
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/XXX/.rvm/gems/ruby-2.3.0/bin:/Users/XXX/.rvm/gems/ruby-2.3.0@global/bin:/Users/XXX/.rvm/rubies/ruby-2.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/XXX/.rvm/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk -L/Users/XXX/Library/Developer/Xcode/DerivedData/PromiseKit-dzbgegkpvalpmqdgfvdnvsgwbmgj/Build/Products/Release-iphoneos -F/Users/XXX/Library/Developer/Xcode/DerivedData/PromiseKit-dzbgegkpvalpmqdgfvdnvsgwbmgj/Build/Products/Release-iphoneos -filelist /Users/XXX/Library/Developer/Xcode/DerivedData/PromiseKit-dzbgegkpvalpmqdgfvdnvsgwbmgj/Build/Intermediates/PromiseKit.build/Release-iphoneos/PMKiOSUITestsHost.build/Objects-normal/armv7/PMKiOSUITestsHost.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=8.3 -dead_strip -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/XXX/Library/Developer/Xcode/DerivedData/PromiseKit-dzbgegkpvalpmqdgfvdnvsgwbmgj/Build/Products/Release-iphoneos -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -Xlinker -add_ast_path -Xlinker /Users/XXX/Library/Developer/Xcode/DerivedData/PromiseKit-dzbgegkpvalpmqdgfvdnvsgwbmgj/Build/Intermediates/PromiseKit.build/Release-iphoneos/PMKiOSUITestsHost.build/Objects-normal/armv7/PMKiOSUITestsHost.swiftmodule -framework PromiseKit -Xlinker -dependency_info -Xlinker /Users/XXX/Library/Developer/Xcode/DerivedData/PromiseKit-dzbgegkpvalpmqdgfvdnvsgwbmgj/Build/Intermediates/PromiseKit.build/Release-iphoneos/PMKiOSUITestsHost.build/Objects-normal/armv7/PMKiOSUITestsHost_dependency_info.dat -o /Users/XXX/Library/Developer/Xcode/DerivedData/PromiseKit-dzbgegkpvalpmqdgfvdnvsgwbmgj/Build/Intermediates/PromiseKit.build/Release-iphoneos/PMKiOSUITestsHost.build/Objects-normal/armv7/PMKiOSUITestsHost
Undefined symbols for architecture armv7:
  "type metadata for (extension in PMKiOSUITestsHost):__ObjC.UIViewController.AnimationOptions", referenced from:
      protocol witness for Swift.SetAlgebraType.init <A where A1: Swift.SequenceType, A.Element == A1.Generator.Element> (A1) -> A in conformance (extension in PMKiOSUITestsHost):__ObjC.UIViewController.AnimationOptions : Swift.SetAlgebraType in PMKiOSUITestsHost in app.o
      protocol witness for Swift.ArrayLiteralConvertible.init (arrayLiteral : [A.Element]...) -> A in conformance (extension in PMKiOSUITestsHost):__ObjC.UIViewController.AnimationOptions : Swift.ArrayLiteralConvertible in PMKiOSUITestsHost in app.o
      (extension in PMKiOSUITestsHost):__ObjC.UIViewController.(promiseViewController <A> (__ObjC.UIViewController, animate : (extension in PMKiOSUITestsHost):__ObjC.UIViewController.AnimationOptions, fulfills : (extension in PMKiOSUITestsHost):__ObjC.UIViewController.FulfillmentType, completion : () -> ()?) -> PromiseKit.Promise<A>).(default argument 1) in app.o
      function signature specialization <Arg[2] = Dead> of generic specialization <(extension in PMKiOSUITestsHost):__ObjC.UIViewController.AnimationOptions with (extension in PMKiOSUITestsHost):__ObjC.UIViewController.AnimationOptions : Swift.SetAlgebraType in PMKiOSUITestsHost, (extension in PMKiOSUITestsHost):__ObjC.UIViewController.AnimationOptions> of static (extension in Swift):Swift.SetAlgebraType.element (A.Element, subsumes : A.Element) -> Swift.Bool in app.o
      function signature specialization <Arg[2] = Dead> of generic specialization <(extension in PMKiOSUITestsHost):__ObjC.UIViewController.AnimationOptions with (extension in PMKiOSUITestsHost):__ObjC.UIViewController.AnimationOptions : Swift.SetAlgebraType in PMKiOSUITestsHost, (extension in PMKiOSUITestsHost):__ObjC.UIViewController.AnimationOptions> of static (extension in Swift):Swift.SetAlgebraType.element (A.Element, isDisjointWith : A.Element) -> Swift.Bool in app.o
  "type metadata for (extension in PMKiOSUITestsHost):__ObjC.SLComposeViewController.Error", referenced from:
      generic specialization <(extension in PMKiOSUITestsHost):__ObjC.SLComposeViewController.Error with (extension in PMKiOSUITestsHost):__ObjC.SLComposeViewController.Error : Swift.ErrorType in PMKiOSUITestsHost> of (extension in Swift):Swift.ErrorType._domain.getter : Swift.String in app.o
  "type metadata for (extension in PMKiOSUITestsHost):__ObjC.UIImagePickerController.Error", referenced from:
      generic specialization <(extension in PMKiOSUITestsHost):__ObjC.UIImagePickerController.Error with (extension in PMKiOSUITestsHost):__ObjC.UIImagePickerController.Error : Swift.ErrorType in PMKiOSUITestsHost> of (extension in Swift):Swift.ErrorType._domain.getter : Swift.String in app.o
  "type metadata for (extension in PMKiOSUITestsHost):__ObjC.UIViewController.Error", referenced from:
      generic specialization <(extension in PMKiOSUITestsHost):__ObjC.UIViewController.Error with (extension in PMKiOSUITestsHost):__ObjC.UIViewController.Error : Swift.ErrorType in PMKiOSUITestsHost> of (extension in Swift):Swift.ErrorType._domain.getter : Swift.String in app.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by mxcl** [comment]
It's odd that it is even building `PMKiOSUITestsHost` since that is a test.

**Comment by mxcl** [comment]
Fixed: https://github.com/mxcl/PromiseKit/commit/78af1260bbf023c13e41b1047a2e34b8fe528c24

3.4.1 tagged.
