### ISSUE TITLE
Carthage Support for 1.x

### ISSUE THREAD

**Issue by mofirouz** [mxcl/PromiseKit#483]
Hi Max,

Apologies for being a pain and asking for this. I saw that you added support for Carthage for Swift on issue #145. I was wondering if you could do the same for the 1.x branch as well please?

The usecase is that some of our users don't like to integrate Cocoapods (as it is very invasive on the XCode project) and then they try to build our project locally which fails since they need to download and link PMK (and other dependencies) manually themselves which isn't fun.

Is there a way you could do this for the 1.x branch?

Your help is much appreciated. 

Cheers, Mo

**Comment by mofirouz** [comment]
This is the error I get when I try to do `carthage update` on the 1.7.2 version:

```A shell task (/usr/bin/xcrun xcodebuild -project /heroiclabs-sdk-ios/Carthage/Checkouts/Promisekit/PromiseKit.xcodeproj -scheme PMKOSX -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -showBuildSettings) failed with exit code 66:
xcodebuild: error: Scheme PMKOSX is not currently configured for the build action.```

**Comment by mxcl** [comment]
Done:

```
$ carthage bootstrap
*** No Cartfile.resolved found, updating dependencies
*** Fetching PromiseKit
*** Checking out PromiseKit at "1.7.3"
*** xcodebuild output can be found in /var/folders/9p/55y6r8hs3yz2qkhvf74gc0gh0000gn/T/carthage-xcodebuild.nOhY3G.log
*** Building scheme "PMKmacOS" in PromiseKit.xcodeproj
*** Building scheme "PMKiOS" in PromiseKit.xcodeproj
$ cat Cartfile
github "mxcl/PromiseKit" ~> 1.7
```

**Comment by mofirouz** [comment]
Hi @mxcl thanks so much for the prompt work. This works as expected now. Cheers.
