### ISSUE TITLE
SwiftPM.swift included in CocoaPods framework

### ISSUE THREAD

**Issue by zachbai** [mxcl/PromiseKit#487]
CatchPolicy in SwiftPM conflicts with declaration in AnyPromise.h, removing SwiftPM from the build phase fixed it locally for me. Do I need this file, or is it only for swift package manager?

**Comment by mxcl** [comment]
My bad. It's not possible for me to test the pod on my machine or travis for some reason.

**Comment by mxcl** [comment]
Pushed a fix. Verified that the podspec parses at least.

**Comment by mxcl** [comment]
Oh one sec

**Comment by mxcl** [comment]
Fixed.
