### ISSUE TITLE
WatchOS: missing framework QuartzCore

### ISSUE THREAD

**Issue by ryanschneider** [mxcl/PromiseKit#488]
I just ran into this issue compiling for WatchOS2.  Everything works fine on the simulator, but on there's a compile error for an actual device.  The issue is in the `QuartzCore` subspec (which is included by default):

```
  s.subspec 'QuartzCore' do |ss|
    ss.ios.source_files = 'Categories/QuartzCore/*'
        ss.osx.source_files = 'Categories/QuartzCore/*'
    ss.dependency 'PromiseKit/CorePromise'
    ss.frameworks = 'QuartzCore'  # <-- Issue here: we add framework to all targets
  end
```

The issue is that QuartzCore *is* available for builds targeting the simulator (it's leaking in from either the iOS Simulator or OS X itself, not sure which), but really shouldn't be (as it's not available on actual WatchOS devices).

I forked and changed the last line to: 

```
    ss.ios.frameworks = ss.osx.frameworks =  'QuartzCore' 
```

And everything builds fine.  I'll send a PR for the change here shortly.

**Comment by mxcl** [comment]
I'll push 3.4.2 presently.

**Comment by ryanschneider** [comment]
Thanks for the quick turnaround!  3.4.2 works perfectly for me.
