### ISSUE TITLE
3.4.2 UIKit extension broken

### ISSUE THREAD

**Issue by allen-zeng** [mxcl/PromiseKit#492]
In the UIKit subspec, `promiseViewController(vc:animated:completion:)` has been deprecated since 3.4. The replacement (`promiseViewController(_:animate:fulfills:completion:)`) asks for a `UIViewController.AnimationOptions` parameter, which has 2 problems.

The first is that it can only be instantiated via the public `init(rawValue:)`. This can be resolved easily enough by marking the members public. This change is in pull request #491.

The second is slightly trickier to fix. When `UIViewController.AnimationOptions` is used in pure Swift, everything works. As soon as it's used in a context marked with `@IBAction` or `@objc`, it causes a compilation error:
![image](https://cloud.githubusercontent.com/assets/7380931/17461513/8c75bff4-5cd2-11e6-9803-0fee87155bba.png)

The root cause seems to be that `UIViewController.AnimationOptions` is a struct. I managed to get things compiling and tests working as they used to by removing the struct, and then introducing an Objective-C counterpart:
```objc
typedef NS_OPTIONS(NSInteger, UIViewControllerAnimationOptions) {
    UIViewControllerAnimationOptionsNone = 1 << 0,
    UIViewControllerAnimationOptionsAppear = 1 << 1,
    UIViewControllerAnimationOptionsDisappear = 1 << 2,
};
```
This translates to the same struct when bridged, so none of the usages need to change.

What I'm having trouble figuring out is where this Objective-C file should be placed. I've managed to get it to work by including it in `Umbrella.h`, which is obviously incorrect, especially that it's only applicable to the UIKit subspec. Any suggestions?

**Comment by mxcl** [comment]
Sorry about this. I'll work on a fix immediately.

**Comment by mxcl** [comment]
Your solution is the only one I could get to work. A pure Swift `OptionsSetType` does not get generated into a `-Swift.h` header by the toolchain, probably there is a solution for that, but I don't know it. Having it be an Objective-C option works and is an acceptable solution. Will push 3.4.3.

**Comment by allen-zeng** [comment]
Thanks for getting on top of this so quickly!
