### ISSUE TITLE
Your documentation is out of date.

### ISSUE THREAD

**Issue by jonahgabriel** [mxcl/PromiseKit#496]
Looks like catch has been a reserved keyword for a while. You may want to update your documentation.

**Comment by mxcl** [comment]
The documentation is for version 4 and Swift 3. Reserved keywords can be used as functions in Swift 3.

**Comment by jonahgabriel** [comment]
Makes sense. Thanks!

**Comment by mxcl** [comment]
Sorry for the confusion.
