### ISSUE TITLE
Consider making PromiseKit/Foundation not depend on OMGHTTPURLRQ

### ISSUE THREAD

**Issue by mxcl** [mxcl/PromiseKit#499]
* This way we could support SwiftPM.
* It would also make our Foundation category seem less heavy.
* It would make using Alamofire and PromiseKit less redundant.

**Comment by mxcl** [comment]
We would still have an OMG extension, just separately. And nothing would change for CocoaPods bar the option to not depend on OMG being more readily available.

**Comment by simonnarang** [comment]
Would be a nice improvement

**Comment by mxcl** [comment]
Done.

I also added an `Alamofire` extension. Now you can chose between OMG and AF as you like.
