### ISSUE TITLE
Currently minimal changes support for swift 2.3

### ISSUE THREAD

**Issue by patrickjquinn** [mxcl/PromiseKit#501]
I see talk of a minimal changes & 2.3 branch being made ( https://github.com/mxcl/PromiseKit/issues/451 )  but this seems to have disappeared. Will there be support for 2.3 anytime soon? Currently unable to build our application using PromiseKit

**Comment by mxcl** [comment]
Yes, as the README says, the master branch supports 2.3. If it doesn't then that's a bug.

**Comment by patrickjquinn** [comment]
Yes brilliant thanks Max, the questions is around the minimal changes compat layer, will there be one for 2.3?

**Comment by mxcl** [comment]
I'm sorry, minimal changes versus what? PMK3 supports Swift 2.2 & Swift 2.3, so it requires no minimal changes.

Do you want a minimal changes branch for PMK2? Or for PMK4?

**Comment by patrickjquinn** [comment]
I'm sorry man, this is far too small fries for you to be worrying about, I'm returning PMKPromises instead of AnyPromise so I'm just being lazy and looking for a way to avoid having to migrate our project over to the new syntax, thanks for all your help and a solid project

**Comment by mxcl** [comment]
No no, this isn't small fry. I want PromiseKit to satisfy all its users. Just need to understand what you are after.

So PMK2 for Swift 2.3? Should be doable.

**Comment by patrickjquinn** [comment]
Yes sorry, to be more specific, PMK2 for Swift 2.3 would be perfect, exactly what I was hoping for, our app is still objective C and due migration to swift but this would make all the difference in terms of timeline for the next couple of release, especially the upcoming iOS10 one

**Comment by mxcl** [comment]
Done, let me know if you have any trouble.

Next time feel free to open this ticket sooner! Only took me 20 minutes to make it work.

**Comment by patrickjquinn** [comment]
Issue is very much resolve! App now builds and runs perfectly on iOS 10 under Xcode 8 and Swift 2.3 👍 Thanks for the amazingly quick turn around I'll report issues like this much sooner instead of looking for workarounds
