### ISSUE TITLE
Wrong argument type with `.when`

### ISSUE THREAD

**Issue by ryancoughlin** [mxcl/PromiseKit#502]
I am chaining several promises, I am using `when()` to pass two of the same type of promises. The only thing different is the data they are decoding.

I thought it might have been Argo (https://github.com/thoughtbot/Argo) that was throwing it off, but I changed the promises below to return simple strings and the same error still popped up.

> Cannot convert value of type 'Promise<Decoded<Array<Wind>>>' to expected argument type 'Promise<Any>' (aka 'Promise<protocol<>>')

Here is the signature for `decodeWind(json: )`

```
func decodeWind(json: [String: AnyObject]) -> Promise <Decoded <Array <Wind>>> {
    return Promise { fulfill, reject in
        if let hourly = json["hourly"] as? [String: AnyObject] {
            let winds: Decoded <[Wind]> = decode(hourly, rootKey: "data")
            fulfill(winds)
        }
    }
}
```

In context:

```
RequestLocation().requestUserLocation().then { locationCoordinate in
    return NetworkRequest().makeRequest(locationCoordinate)
}.then { weatherJSON in
    let decodeWind = DecodeWind().decodeWind(weatherJSON)
    let decodeCurrently = DecodeCurrently().decodeCurrentWeather(weatherJSON)

    return when(decodeWind, decodeCurrently)
}.then { wind, currently in
    print(wind, currently)
}
```

Been digging through docs and source code, any ideas? The other promises in the chain were working great, seems to be isolated to when using `when()`

---

Xcode: 7.3.1
PromiseKit: 2.30

**Comment by mxcl** [comment]
What line is the error on?

**Comment by ryancoughlin** [comment]
Oh yes, sorry about: `return when(decodeWind, decodeCurrently)`

**Comment by mxcl** [comment]
You need to specify the return type for the closure (`Promise<(A,B)>`), this is a Swift issue. Further information in the FAQ.

**Comment by mxcl** [comment]
Let me know if you have other problems as I want to help, but also want to update the docs to be more useful.

**Comment by ryancoughlin** [comment]
Ok great, I read that as it needs to be specified within the promise declaration which I was doing not where I call the promise. 

Would be happy to help with docs as things pop up. Tearing down an old app made with ReactiveCocoa and ObjC and starting a new project with Swift + PromiseKit.

**Comment by mxcl** [comment]
You need to specify the return type like so:

```swift
RequestLocation().requestUserLocation().then { locationCoordinate in
    return NetworkRequest().makeRequest(locationCoordinate)
}.then { weatherJSON -> Promise(<A,B>) in
    let decodeWind = DecodeWind().decodeWind(weatherJSON)
    let decodeCurrently = DecodeCurrently().decodeCurrentWeather(weatherJSON)

    return when(decodeWind, decodeCurrently)
}.then { wind, currently in
    print(wind, currently)
}
```

This is because Swift infers return types for single line closures but otherwise will not.

**Comment by ryancoughlin** [comment]
I noticed `when()` has several signatures and return values: `[]` vs `Promise<(U, V)>`

This worked as the solution:
```
        RequestLocation().requestUserLocation().then { locationCoordinate in
            return NetworkRequest().makeRequest(locationCoordinate)
        }.then { weatherJSON -> Promise<(Decoded <[Wind]>, Decoded <CurrentWeather>)> in
            let decodeWind = DecodeWind().decodeWind(weatherJSON)
            let decodeCurrently = DecodeCurrently().decodeCurrentWeather(weatherJSON)

            return when(decodeWind, decodeCurrently)
        }.then { wind, currently in
            print(wind, currently)
        }
```

Appreciate it.

**Comment by mxcl** [comment]
Cool. It is IMO a pity this is required, but Lattner has been pretty clear that he considers this a feature.

ObjC is more flexible… :/
