### ISSUE TITLE
unknown type name 'AnyPromise'

### ISSUE THREAD

**Issue by evautherin** [mxcl/PromiseKit#504]
Using PromiseKit for months, I'm facing an error with Xcode 8-beta 5, Cocoapod and the latest "swift-3.0" branch.
The pod framework seems to build but when I try to use PromiseKit the "unknown type name 'AnyPromise'" error occurs inside the Objective-C umbrella.

<img width="878" alt="log" src="https://cloud.githubusercontent.com/assets/9949921/17669058/6d00e834-630c-11e6-9106-25a25ba4dcfe.png">

The Podfile is:

```
target 'PKProblem' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PKProblem
	pod 'PromiseKit/CorePromise',
		:git => 'https://github.com/mxcl/PromiseKit.git',
		:branch => 'swift-3.0'

end

```

The whole project is available here:
https://github.com/evautherin/PKProblem

**Comment by mxcl** [comment]
Should be fixed.

Was due to how the generated umbrella header ordered the includes and because PromiseKit does the unusual: Adding objc to a Swift class.

**Comment by mxcl** [comment]
Let me know if it works.

**Comment by evautherin** [comment]
Yes this is now fixed. Thank you!

**Comment by SebastianBoldt** [comment]
Awesome, thank you.
