### ISSUE TITLE
Cocoapods not finding 4.0

### ISSUE THREAD

**Issue by gsabran** [mxcl/PromiseKit#507]
Following the readme in the `swift-3.0` branch, I added `pod "PromiseKit", "~> 4.0"` in my Podfile. Then `pod install` fails with

```
[!] Unable to satisfy the following requirements:

- `PromiseKit (~> 4.0)` required by `Podfile`
- `PromiseKit (~> 4.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `PromiseKit (~> 4.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

```

**Comment by nathanhosselton** [comment]
The `swift-3.0` branch is not yet released, so your podfile will have to be:
```
pod 'PromiseKit', :git => 'https://github.com/mxcl/PromiseKit.git', :branch => 'swift-3.0'
```
until that time.

**Comment by gsabran** [comment]
Thanks. Which version do you prefer to have in the readme atm?

**Comment by nathanhosselton** [comment]
@gsabran There is no released version of PMK with Swift 3.0 support. So the only other thing the readme on that branch could say is the above. Is that what you're asking?

**Comment by gsabran** [comment]
Just that on the `swift-3.0` branch the readMe says to run `pod "PromiseKit", "~> 4.0"` (under [quick start](https://github.com/mxcl/PromiseKit/tree/swift-3.0#quick-start
))
It's pretty minor :)

**Comment by nathanhosselton** [comment]
@gsabran Gotcha. Sorry for the confusion. Eventually the branch will be pushed to pods and merged to master, at which point it will be accurate.

**Comment by gsabran** [comment]
sure thing!
