### ISSUE TITLE
How to use the swift 3 version in xcode 8 beta?

### ISSUE THREAD

**Issue by gsabran** [mxcl/PromiseKit#508]
I sounds like the `swift-3.0` branch can be used with the latest version of xcode 8 beta (currently beta 6) This is great!

However I'm failing to import the pod... My podfile is like

```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PieKit' do
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    workspace 'Pie'
    project 'PieKit'
    
    pod 'PromiseKit', :git => 'https://github.com/mxcl/PromiseKit.git', :branch => 'swift-3.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
```

The last part is needed to get rid of the error
```
Showing All Issues
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
```

Then xcode throw a bunch of errors that look stupid: 
<img width="1174" alt="screen shot 2016-08-16 at 2 38 31 pm" src="https://cloud.githubusercontent.com/assets/4228246/17716832/546426a2-63bf-11e6-97e3-050f62215b5b.png">

Am I doing something wrong ? Is that just Xcode beta not being ready for prime time? Thanks a lot!

**Comment by mxcl** [comment]
Set legacy swift to no. For more information google: Xcode 8 swift legacy version.

**Comment by gsabran** [comment]
Yes I already done that, and googled :) First result is http://stackoverflow.com/questions/38446097/xcode-8-beta-3-use-legacy-swift-issue, which is where my podfile code is coming from. It's still annoyingly not working. But no worries if you have better things to do. I'm just frustrated of not getting Promise in my new project!

**Comment by nathanhosselton** [comment]
@gsabran A thought: ensure the setting is also configured in the Pods project for the PromiseKit target.

**Comment by mxcl** [comment]
Put this in your Podfile:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
```

Presumably when Xcode 8 is released CocoaPods will be updated. Until then read documentation when using pre-release tooling.

**Comment by gsabran** [comment]
Thanks all. I fixed it. I was stupidly running the version 5 of the beta, and I needed to point to the commit that supports that version instead of the latest version of the swift3 branch:

```
pod 'PromiseKit', :git => 'https://github.com/mxcl/PromiseKit.git', :commit => '0e8d157a7b56e6dc1e2c8190dfaea03ddf1059de'
```

Sorry for wasting your time
