### ISSUE TITLE
Cannot build with Xcode 8 Beta 6 and swift-3.0 branch

### ISSUE THREAD

**Issue by eytanbiala** [mxcl/PromiseKit#509]
Here's what I have in my Podfile:
`pod 'PromiseKit/CorePromise', :git => 'https://github.com/mxcl/PromiseKit', :branch => 'swift-3.0'`

I previously had this in my bridging header, but have removed it now:
`import "PromiseKit-Swift.h"`

I'm getting these kinds of errors when building:
![image](https://cloud.githubusercontent.com/assets/1770794/17725067/9f8b5514-6415-11e6-9747-4f8c227e5769.png)

![image](https://cloud.githubusercontent.com/assets/1770794/17725073/b5ad2d72-6415-11e6-80f6-b18b05a188a2.png)

**Comment by mxcl** [comment]
Unknown attribute escaping suggests to me that this isn't Xcode 8 beta 6. Since that was introduced in beta 6. What does About Xcode say?

If it is beta 6, check the SWIFT_VERSION setting in your build settings in both xcodeprojs.

**Comment by eytanbiala** [comment]
This is the Xcode version I'm using: Version 8.0 beta 6 (8S201h)

So in the PromiseKit target, "Use Legacy Swift Language Version" was set to "Yes".
If I change it to "No", then I just get these errors:
![image](https://cloud.githubusercontent.com/assets/1770794/17725160/b5f2bc1a-6416-11e6-8b89-d135b3e6bba8.png)

If I comment out the finally's it complains about, it seems to work for that file. I use finally all the time though, so I haven't gone through to see if the whole project will build if I take them out.

**Comment by mxcl** [comment]
Yes, CocoaPods doesn't have a way to set the Swift version yet, so you have to do that manually.

`finally` has been renamed `always` to be consistent with `Promise<T>`.

**Comment by eytanbiala** [comment]
Ahh ok, that seems to work.

Seems I have one last issue - `No known class method for selector 'promiseWithValue:'.`

I'm using Obj-c, and currently importing `#import <PromiseKit/PromiseKit.h>`. Do I need to be importing something else?

**Comment by mxcl** [comment]
`AnyPromise` `+promiseWithValue` exists, and we use it copiously in our tests, so I'm confused about that. Looks like:

    [AnyPromise promiseWithValue:@1]

?

**Comment by eytanbiala** [comment]
Hmm, I don't think it's specific to that method actually. If I comment out the instance that is causing the build error, it then finds`No known class method for selector 'promiseWithResolverBlock:'` 

What's weird is that the methods show up in autocomplete, and I can cmd+click to go to the definition.

**Comment by mxcl** [comment]
Does it work if you `@import PromiseKit;` instead?

**Comment by eytanbiala** [comment]
Hmm no, unfortunately not, getting the same errors.

**Comment by mxcl** [comment]
Actually I think I know why, will push a fix.

**Comment by mxcl** [comment]
Try now, presumably `pod update` will fetch the new HEAD.

**Comment by eytanbiala** [comment]
Yep works now, thanks for all your help!

**Comment by lchenay** [comment]
We have the same problem with Xcode 8 beta 6.
* Pods/PromiseKit/Sources/dispatch_promise.m:5:24: No known class method for selector 'promiseWithValue:'
* Pods/PromiseKit/Sources/dispatch_promise.m:5:46: Property 'thenOn' not found on object of type 'id'
* Pods/PromiseKit/Sources/after.m:8:24: No known class method for selector 'promiseWithResolverBlock:'

As @eytanbiala we do see in autocompletion. But it failed during compilation of PromiseKit.

**Comment by mxcl** [comment]
Open new ticket.
