### ISSUE TITLE
Building from SwiftPM-generated .xcodeproj file gives errors

### ISSUE THREAD

**Issue by mattdeckard** [mxcl/PromiseKit#516]
I have a simple demo app with the following `Package.swift`:
```
import PackageDescription

let package = Package(
    name: "OutOfOffice",
    dependencies: [
       .Package(url: "https://github.com/mxcl/PromiseKit", majorVersion: 4)
    ]
)
```
Using Swift 3.0 beta 6, I'm able to `swift build` with success, but when I `swift package generate--xcodeproj` and try to build the resulting project, I get errors like the following:
```
/Users/dev1/dev/OutOfOffice/Packages/PromiseKit-4.0.0/Sources/Error.swift:115:15: error: use of unresolved identifier 'PMKErrorDomain'
    ErrorPair(PMKErrorDomain, PMKOperationCancelled),
              ^~~~~~~~~~~~~~
/Users/dev1/dev/OutOfOffice/Packages/PromiseKit-4.0.0/Sources/Error.swift:115:31: error: use of unresolved identifier 'PMKOperationCancelled'
    ErrorPair(PMKErrorDomain, PMKOperationCancelled),
                              ^~~~~~~~~~~~~~~~~~~~~
/Users/dev1/dev/OutOfOffice/Packages/PromiseKit-4.0.0/Sources/Error.swift:97:32: error: use of unresolved identifier 'PMKErrorDomain'
        return NSError(domain: PMKErrorDomain, code: PMKOperationCancelled, userInfo: info)
                               ^~~~~~~~~~~~~~
Foundation.NSErrorDomain:1:18: note: did you mean 'NSErrorDomain'?
public typealias NSErrorDomain = NSString
                 ^
CoreFoundation.CFErrorDomain:1:18: note: did you mean 'CFErrorDomain'?
public typealias CFErrorDomain = CFString
                 ^
/Users/dev1/dev/OutOfOffice/Packages/PromiseKit-4.0.0/Sources/Error.swift:97:54: error: use of unresolved identifier 'PMKOperationCancelled'
        return NSError(domain: PMKErrorDomain, code: PMKOperationCancelled, userInfo: info)
                                                     ^~~~~~~~~~~~~~~~~~~~~
```

Those appear to be defined in `AnyPromise.m` which I noted was not included in the generated `xcodeproj` so I tried adding them manually, but to no avail.

**Comment by mxcl** [comment]
Bug is with SwiftPM. SWIFT_PACKAGE is not defined for generated Xcode projects.

**Comment by mattdeckard** [comment]
Dang. Do you know of any workaround?

**Comment by mxcl** [comment]
You could manually define the constant in the project.

**Comment by mxcl** [comment]
It should be a trivial fix, so we should fix it and submit the PR.

**Comment by mxcl** [comment]
I submitted a fix to swiftpm and it was merged. Let me know if it doesn't fix it.

**Comment by 634750802** [comment]
Is this bug fixed in Xcode8 release version?

**Comment by mxcl** [comment]
Couldn't tell you.

**Comment by 634750802** [comment]
I still need to define SWIFT_PACKAGE manually after I generate .xcodeproj file in that version.
 SwiftPM's recent commit has remove all the building setting including this one.
The commit is [here](https://github.com/apple/swift-package-manager/commit/8b4bf3a424bc9c11d2c61d1f554a8a8d416d0728).
Maybe you should re-generate the .xcodeproj file ?

**Comment by werne2j** [comment]
I am also seeing this error. Using Xcode 8 release on macOS Sierra.
