### ISSUE TITLE
PromiseKit Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by marbetschar** [mxcl/PromiseKit#517]
I've added an embedded framework to my project. In this embedded framework I've configured PromiseKit as a linked framework ...

![linked](https://cloud.githubusercontent.com/assets/392542/17968832/362d7ba4-6acf-11e6-8006-98e2eb3dbbd7.png)

... and added it to the Carthage Copy Frameworks build phase ...

![copy](https://cloud.githubusercontent.com/assets/392542/17968834/38fd85e0-6acf-11e6-8daa-99a51db28109.png)

But when I try to run the app in the iOS Simulator, the build fails with the following error:

```
Undefined symbols for architecture x86_64:
  "PromiseKit.Promise.(then <A> (on : __ObjC.OS_dispatch_queue, (A) throws -> A1) -> PromiseKit.Promise<A1>).(default argument 0)", referenced from:
      Valletti.AppDelegate.application (__ObjC.UIApplication, didFinishLaunchingWithOptions : [__ObjC.NSObject : Swift.AnyObject]?) -> Swift.Bool in App.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

What's wrong?

**Comment by mxcl** [comment]
Your application is not successfully linking at runtime to `PromiseKit.framework`.

I suggest inspecting the application bundle, check `PromiseKit.framework` is there and checking the rpaths and link lines (`otool -L`) of the binaries and frameworks to try and figure out what is wrong.

If you can mail me the project I can do this for you.

**Comment by marbetschar** [comment]
Thanks for the hint! It seems I also have to link the `PromiseKit.framework`with the main app - and not only for the embedded framework. Now everythings working.
