### ISSUE TITLE
PromiseKit requires Swift libraries to be embedded in the binary

### ISSUE THREAD

**Issue by wokalski** [mxcl/PromiseKit#520]
I have an Objective-C codebase. I would prefer not to include Swift libraries because of the impact on size of the app. Those few MBs don't hurt too much, but I'd rather not have them.

I don't know of any magical way to conditionally link Swift, but if there's one, it would be awesome.

A little bit clunkier but more straightforward solution would be adding a new framework, let's say PromiseKitObjC and then statically link it to the main PromiseKit. The outcome would be two frameworks where PromiseKit includes both Swift and Objective-C whereas PromiseKitObjC would only include the Objective-C version.

I know this adds some complexity, but it should be doable (and maintainable) if there's no Swift code included in the Objective-C implementation and if there are no plans to unify them/get rid of one of them. 

I could do this if you find this suggestion useful.

**Comment by mxcl** [comment]
The ObjC implementation is not ObjC it is Swift, so it is impossible not to require the swift runtime.

If you want a pure ObjC PromiseKit, we still maintain PromiseKit 1.x.

**Comment by wokalski** [comment]
Oh, I should've checked. Thanks!
