### ISSUE TITLE
NSURLSession promise extension Data Task is never resumed

### ISSUE THREAD

**Issue by ekazaev** [mxcl/PromiseKit#522]
+ (AnyPromise *)promise:(NSURLRequest *)rq {
    return [AnyPromise promiseWithResolverBlock:^(PMKResolver resolve) {
        [[NSURLSession sharedSession] dataTaskWithRequest:rq completionHandler:PMKMakeURLDataHandler(rq, resolve)];
    }];
}

**Comment by mxcl** [comment]
This was fixed recently: https://github.com/mxcl/PromiseKit/commit/314a9897cebc50ace172104adbec9cfb0f185094

**Comment by mxcl** [comment]
Make sure you `pod update`
