### ISSUE TITLE
import fails

### ISSUE THREAD

**Issue by jonasman** [mxcl/PromiseKit#527]
file `NSURLSession+OMG+AnyPromise.m` 

`#import <PMKFoundation/NSURLSession+AnyPromise.h>` doesn't work
`#import "NSURLSession+AnyPromise.h"` works

Same in UKit extensions.

**Comment by mxcl** [comment]
There is no PMKFoundation with CocoaPods. This is documented in the headers.

**Comment by mxcl** [comment]
Specifically it will be `#import <PromiseKit/NSURLSession+AnyPromise.h>` with CocoaPods, but as you specified for Carthage. This is unfortunate but not avoidable afaict.

**Comment by jonasman** [comment]
Im on cocoapods. If i dont change that line it wont compile

**Comment by mxcl** [comment]
With CocoaPods:

     #import <PromiseKit/NSURLSession+AnyPromise.h>

With Carthage:

    #import <PMKFoundation/NSURLSession+AnyPromise.h>

**Comment by jonasman** [comment]
I mean im using cocoapods and the file NSURLSession+OMG+AnyPromise.m doesnt compile when importing the omg extension. This is not my code but Promisekit code

**Comment by mxcl** [comment]
Can you open a new ticket with error messages etc. ?

**Comment by jonasman** [comment]
cant reproduce this anymore. If it ever happens again i will reopen.
