### ISSUE TITLE
Move Dependency on OMGHTTPURLRQ to Subspec

### ISSUE THREAD

**Issue by orkoden** [mxcl/PromiseKit#528]
I wanted to clean up dependencies, because more frameworks slow app start down. The dynamic loader takes longer the more there are.

The subspec `DietFoundation` does not offer any support for `NSURLSession` because it shouldn't have external dependencies. 
`PromiseKit.Foundation` depends on `OMGHTTPURLRQ`. That dependency really isn't needed. It could be extracted to a different file and moved to its own subspec. 

So the dependency on `OMGHTTPURLRQ` either should
- be moved to its own subspec `PromiseKit.OMGHTTPURLRQ`, so that `DietFoundation` and `Foundation` can be merged.
- stay in `PromiseKit.Foundation`, but add the `NSURL*` extensions like the one below on `NSURLSession` to `DietFoundation`.

```
extension NSURLSession {
    public func promise(request: NSURLRequest) -> URLDataPromise {
        return start(request, session: self)
    }
}

private func start(@autoclosure body: () throws -> NSURLRequest, session: NSURLSession = NSURLSession.sharedSession()) -> URLDataPromise {
    do {
        let request = try body()
        return URLDataPromise.go(request) { completionHandler in
            let task = session.dataTaskWithRequest(request, completionHandler: completionHandler)
            task.resume()
        }
    } catch {
        return URLDataPromise(error: error)
    }
}
```

**Comment by mxcl** [comment]
This is already done in PromiseKit 4, to be released with Xcode 8.

**Comment by mxcl** [comment]
Though we have no plans to do it for 1.x or 2.3-minimal-changes, but we could if desired.

**Comment by orkoden** [comment]
Thanks. I hadn't checked PromiseKit 4, sorry.
