### ISSUE TITLE
Unable to build PromiseKit With xcode 8 beta 6

### ISSUE THREAD

**Issue by lchenay** [mxcl/PromiseKit#529]
* PromiseKit version: 4.0
* Xcode version: 8.0 beta 6
* Installation method:
  - [X] CocoaPods

We are getting errors:

* Pods/PromiseKit/Sources/dispatch_promise.m:5:24: No known class method for selector 'promiseWithValue:'
* Pods/PromiseKit/Sources/dispatch_promise.m:5:46: Property 'thenOn' not found on object of type 'id'
* Pods/PromiseKit/Sources/after.m:8:24: No known class method for selector 'promiseWithResolverBlock:'

**Comment by mxcl** [comment]
I can’t experiment right now but this suggests that the module is badly formed, I suggest deleting the pods directory and doing `pod update` again.

**Comment by lchenay** [comment]
Allready done.
Tried with Pod 0.39.0 and 1.0 and 1.1.0.beta.2.
Each times after cleaning pod cache and deleting Pods folder.

**Comment by nathanhosselton** [comment]
I'm unable to reproduce. Can you provide a test project?

**Comment by mxcl** [comment]
I pushed something that may help here just now.

Also 4.0.0 is now live on CocoaPods so you can remove any hacks in your Podfile that you were using.

**Comment by Sega-Zero** [comment]
Having `Include of non-modular header inside framework module 'PromiseKit.CLGeocoder_AnyPromise'` on latest release in my swift project 😞
cocoapods 0.39.0

**Comment by mxcl** [comment]
New ticket please.

**Comment by mxcl** [comment]
Closing due to lack of response.
