### ISSUE TITLE
Get the “Great Documentation” quality badge on cocoapods.org

### ISSUE THREAD

**Issue by mxcl** [mxcl/PromiseKit#533]
http://cocoapods.org/pods/PromiseKit/quality

**Comment by nathanhosselton** [comment]
According to the [Quality Indexes documentation](https://guides.cocoapods.org/making/quality-indexes.html), greater than 90% of the public API must be documented for the pod to receive this badge. At the time of this comment we are at 80%. The live status can be checked [here](http://metrics.cocoapods.org/api/v1/pods/PromiseKit) under `"doc_percent"`.

**Comment by zlangley** [comment]
FYI `doc_percent` is `-1` right now, now sure how it gets computed.

**Comment by mxcl** [comment]
We have this now, and there are no further positive badges to earn! Great work everyone.
