### ISSUE TITLE
I can't use ".catch"

### ISSUE THREAD

**Issue by touyu** [mxcl/PromiseKit#535]
* PromiseKit version: 3.5.1
* Xcode version: 7.3.1
* Installation method:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Other (please specify)
  
When I use ".catch", I get the error - "Expected member name following '.'"

How can I solve this problem?

**Comment by mxcl** [comment]
There is no `catch` in 3. It is called `error`

**Comment by mxcl** [comment]
Leaving open because we should add this caveat to the revised PromiseKit 4 documentation.
