### ISSUE TITLE
Don't include any extension in the default pod?

### ISSUE THREAD

**Issue by gsabran** [mxcl/PromiseKit#536]
I've recently came across an issue with the UIKit extension conflicting with built in functions in a way that was making Xcode compilation fail (https://github.com/PromiseKit/UIKit/issues/2) I got stuck on that for a long time because I had no idea PromiseKit was coming with extensions and Xcode was not able to point me to the conflicting definitions.

To the best of my knowledge, there is no way to get the PromiseKit pod without the UIKit extension. If that's correct, would it be possible to make it non optional extensions optional as is the case for most of the other extensions?

**Comment by nathanhosselton** [comment]
The default subspecs for PromiseKit include our Foundation, UIKit, and QuartzCore extensions. So we provide the `PromiseKit/CorePromise` subspec for when you don't want those.

Looking into the conflict.

**Comment by gsabran** [comment]
ah nice to have `PromiseKit/CorePromise` thanks for the quick response
