### ISSUE TITLE
MapKit Subspec 4.0.0 isn't compatible with iOS?

### ISSUE THREAD

**Issue by aaronbrethorst** [mxcl/PromiseKit#537]
* PromiseKit version: 4.0.0
* Xcode version: 8.0 GM (8A218a)
* Installation method:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Other (please specify)

I'm trying to upgrade my app to Swift 3. I'm running into what seems to be a blocking issue with the PromiseKit MapKit subspec. 

Full app source code: https://github.com/aaronbrethorst/onebusaway-iphone/tree/swift3
Podfile: https://github.com/aaronbrethorst/onebusaway-iphone/blob/swift3/Podfile

```
$ pod install
Analyzing dependencies
Pre-downloading: `SwiftMessages` from `https://github.com/aaronbrethorst/SwiftMessages.git`, branch `xcode8-gm`
[!] The platform of the target `OBAKit` (iOS 9.0) is not compatible with `PromiseKit/MapKit (4.0.0)`, which does not support `ios`.
```

**Comment by mxcl** [comment]
K, figured it out, seems to be a bug in CocoaPods where specifying any deployment target in the subspec causes the deployment targets for any other platforms to be erased. Work around is to re-specify.

**Comment by mxcl** [comment]
I will push 4.0.1 to CocoaPods as soon as I have determined the issue with #538.

**Comment by mxcl** [comment]
In the meantime you should be able to use what we have with:

```ruby
pod "PromiseKit", git: "https://github.com/mxcl/PromiseKit", commit: "d8d9d95"
```

**Comment by aaronbrethorst** [comment]
Awesome, thanks @mxcl
