### ISSUE TITLE
Can't build 4.0.0: "Include of non-modular header inside framework module 'PromiseKit.AAA_CocoaPods_Hack'"

### ISSUE THREAD

**Issue by allen-zeng** [mxcl/PromiseKit#538]
* PromiseKit version: 4.0.0
* Xcode version: 8 GM Seed
* Installation method:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Other (please specify)
  
I'm doing preliminary work to migrate my app to Swift 3. I've been trying to get 4.0.0 compiling in Xcode 8, but so far haven't had any luck:
![image](https://cloud.githubusercontent.com/assets/7380931/18415527/8af6e834-7838-11e6-8103-475a6db99eba.png)

Cleaning, deleting derived data and rebuilding doesn't make a difference. The build fails pretty quickly with the same error. It's always the one error though, hinting that it hasn't gone further than that.

I'm using Cocoapods 0.39.0. I've added this to my `post_install` to no avail:
```ruby
installer.pods_project.build_configurations.each do |config|
  config.build_settings['SWIFT_VERSION'] = "3.0"
  config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = "YES"
end
```

If it'll help, this is the `Podfile`:
```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire', :branch => 'swift3'

pod 'PromiseKit/CorePromise', '~> 4.0.0'
pod 'PromiseKit/UIKit', '~> 4.0.0'
pod 'PromiseKit/AddressBook', '~> 4.0.0'

pod 'SnapKit', :git => 'git@github.com:SnapKit/SnapKit.git', :branch => 'feature/0.40.0'

pod 'SwiftyJSON', :git => 'git@github.com:danielrhodes/SwiftyJSON.git', :branch => 'swift3'

pod 'MagicalRecord', :git => 'https://github.com/magicalpanda/MagicalRecord.git', :commit => '3bfb4fa70c4286ca77beb25a426a53b45e11d37f'

pod 'SentrySwift', '~> 0.3.3'

target 'UnitTests' do
	pod 'Swifter', '~> 1.2.0'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['SWIFT_VERSION'] = "3.0"
    config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = "YES"
  end

  # https://github.com/CocoaPods/CocoaPods/issues/4421#issuecomment-150372394
  plist_buddy = "/usr/libexec/PlistBuddy"

  installer.pods_project.targets.each do |target|
    plist = "Pods/Target Support Files/#{target}/Info.plist"
    version = `#{plist_buddy} -c "Print CFBundleShortVersionString" "#{plist}"`.strip

    stripped_version = /^([\d\.]*)/.match(version).captures[0]

    version_parts = stripped_version.split('.').map { |s| s.to_i }

    # ignore properly formatted versions
    unless version_parts.slice(0..2).join('.') == version

      major, minor, patch = version_parts

      minor ||= 0
      patch = 999

      fixed_version = "#{major}.#{minor}.#{patch}"

      puts "Changing version of #{target} from #{version} to #{fixed_version} to make it pass iTC verification."

      `#{plist_buddy} -c "Set CFBundleShortVersionString #{fixed_version}" "#{plist}"`
    end
  end
end
```

**Comment by mxcl** [comment]
You should probably upgrade CocoaPods to 1.0.1, though I don't expect that to be the issue, it might help.

**Comment by mxcl** [comment]
What is your project’s setting for allowing non modular includes?

**Comment by allen-zeng** [comment]
The setting is NO, but changing it to YES doesn't make a difference.

I'm able to build PromiseKit project by itself as well, just not when it's imported as a pod

**Comment by mxcl** [comment]
Can’t reproduce. I've also talked to several other users who do not have this issue with CocoaPods. Did you try upgrading CocoaPods to the latest version?

**Comment by allen-zeng** [comment]
That's the one thing I haven't tried. Will give that a go and report back.

**Comment by allen-zeng** [comment]
Yeah CocoaPods 1.0.1 fixes the problem! I'll close this.
