### ISSUE TITLE
No known class method for selector 'promiseDataTaskWithRequest:'

### ISSUE THREAD

**Issue by Slessi** [mxcl/PromiseKit#540]
* PromiseKit version: 4.0.1
* Xcode version: 8.0 (8A218a)
* CocoaPods version: 1.1.0.rc.2
* Installation method:
  - [x] CocoaPods
  - [ ] Carthage
  - [ ] Other (please specify)
 
I import using `@import PromiseKit;` and I can see that [NSURLSession+AnyPromise.h](https://github.com/PromiseKit/Foundation/blob/a0f1c7c58e25042002aa201167b701ca92d68632/Sources/NSURLSession%2BAnyPromise.h) exists in my Pods directory. However I am unable to use `NSURLSession promiseDataTaskWithRequest:`. Other functionality I was using from the library (prior to Xcode 8 update) still works.

Tried doing `@import PMKFoundation;` but PMKFoundation isn't found
Tried doing `#import <PromiseKit/NSURLSession+AnyPromise.h>` and the import doesn't throw an error but compiler still complains that method doesn't exist

Here is my podfile
```
platform :ios, '8.0'
use_frameworks!

target 'Messenger' do
    pod 'PromiseKit', '~> 4.0'
    pod 'PromiseKit/OMGHTTPURLRQ', '~> 4.0'
end

# Swift 3 fix
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
```

**Comment by skyebook** [comment]
Same issue (using `Promise` instead of `AnyPromise`), same system configuration. Not using the umbrella pod, just `PromiseKit/CorePromise` and `PromiseKit/Foundation`

Looked in the Pods/PromiseKit target and confirmed `NSURLSession+Promise.swift` is included for compilation in Build Phases.

**Comment by mxcl** [comment]
Can you post the code that fails to compile?

**Comment by fadedblue** [comment]
same issue. Clean, rebuild, rebuild，it work.

**Comment by Slessi** [comment]
![screen shot 2016-09-15 at 10 22 30 am](https://cloud.githubusercontent.com/assets/3223500/18543088/5bca1880-7b2e-11e6-85f1-886e2c61d4c5.png)

**Comment by mxcl** [comment]
Well indeed. That method is -, not +

https://github.com/PromiseKit/Foundation/blob/master/Sources/NSURLSession%2BAnyPromise.h

**Comment by Slessi** [comment]
... fml.

Was coming from `[NSURLConnection promise:request];` (now deprecated) and totally overlooked that

**Comment by mxcl** [comment]
np we've all done such things.
