### ISSUE TITLE
Missing argument for parameter 'body' in call

### ISSUE THREAD

**Issue by bennettl** [mxcl/PromiseKit#541]
* PromiseKit version: 3.5.1
* Xcode version: 7.3.1
* Installation method: CocoaPods

I'm using promises when creating my api client.

  ```
// Definition of method "createRide"
    func createRide(params: [String: AnyObject]) -> Promise<JSON>{
        
        return Promise { fulfill, reject in
        
            let path = "\(BASE_API_URL)/rides"
            
            Alamofire.request(.POST, path, parameters: params, encoding: .JSON, headers: nil).responseJSON { response in
                self.processResponse(response).then({ json in
                    fulfill(json)
                }).error{ err in
                    reject(err)
                }
            }
        }
    }
```
```
// Using create ride
ApiManager.sharedInstance.createRide(params: params).then({ ride in
// Code to do something with ride
})
```

When using the method `createRide` I get the error message "Missing argument for parameter 'body' in call". I've been getting this error on and off and it hasn't been consistent what's causing this.

**Comment by mxcl** [comment]
Specify `-> Void`.

**Comment by bennettl** [comment]
Thanks @mxcl . It works! I'm guessing because there's a lot of possible overloads? Strange because for my other `.then(...)` i didn't need to specified void.

**Comment by mxcl** [comment]
I think it's a swift compiler bug.
