### ISSUE TITLE
CocoaPods install error

### ISSUE THREAD

**Issue by yangzhixiao** [mxcl/PromiseKit#542]
* PromiseKit version: 4.0.1
* Xcode version: xcode ??
* Installation method: CocoaPods

```
Installing PromiseKit 4.0.1 (was 3.5.0)

[!] Error installing PromiseKit
[!] /usr/bin/git clone https://github.com/mxcl/PromiseKit.git /var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-46795-15l7zxz --single-branch --depth 1 --branch 4.0.1 --recursive

Submodule 'Extensions/AVFoundation' (https://github.com/PromiseKit/AVFoundation) registered for path 'Extensions/AVFoundation'
Submodule 'Extensions/Accounts' (https://github.com/PromiseKit/Accounts.git) registered for path 'Extensions/Accounts'
Submodule 'Extensions/AddressBook' (https://github.com/PromiseKit/AddressBook.git) registered for path 'Extensions/AddressBook'
Submodule 'Extensions/Alamofire' (https://github.com/PromiseKit/Alamofire) registered for path 'Extensions/Alamofire'
Submodule 'Extensions/AssetsLibrary' (https://github.com/PromiseKit/AssetsLibrary.git) registered for path 'Extensions/AssetsLibrary'
Submodule 'Extensions/Bolts' (https://github.com/PromiseKit/Bolts.git) registered for path 'Extensions/Bolts'
Submodule 'Extensions/CloudKit' (https://github.com/PromiseKit/CloudKit.git) registered for path 'Extensions/CloudKit'
Submodule 'Extensions/CoreBluetooth' (https://github.com/PromiseKit/CoreBluetooth.git) registered for path 'Extensions/CoreBluetooth'
Submodule 'Extensions/CoreLocation' (https://github.com/PromiseKit/CoreLocation.git) registered for path 'Extensions/CoreLocation'
Submodule 'Extensions/EventKit' (https://github.com/PromiseKit/EventKit.git) registered for path 'Extensions/EventKit'
Submodule 'Extensions/Foundation' (https://github.com/PromiseKit/Foundation.git) registered for path 'Extensions/Foundation'
Submodule 'Extensions/MapKit' (https://github.com/PromiseKit/MapKit.git) registered for path 'Extensions/MapKit'
Submodule 'Extensions/MessagesUI' (https://github.com/PromiseKit/MessagesUI.git) registered for path 'Extensions/MessagesUI'
Submodule 'Extensions/OMGHTTPURLRQ' (https://github.com/PromiseKit/OMGHTTPURLRQ) registered for path 'Extensions/OMGHTTPURLRQ'
Submodule 'Extensions/Photos' (https://github.com/PromiseKit/Photos.git) registered for path 'Extensions/Photos'
Submodule 'Extensions/QuartzCore' (https://github.com/PromiseKit/QuartzCore.git) registered for path 'Extensions/QuartzCore'
Submodule 'Extensions/Social' (https://github.com/PromiseKit/Social.git) registered for path 'Extensions/Social'
Submodule 'Extensions/StoreKit' (https://github.com/PromiseKit/StoreKit.git) registered for path 'Extensions/StoreKit'
Submodule 'Extensions/SystemConfiguration' (https://github.com/PromiseKit/SystemConfiguration) registered for path 'Extensions/SystemConfiguration'
Submodule 'Extensions/UIKit' (https://github.com/PromiseKit/UIKit.git) registered for path 'Extensions/UIKit'
Submodule 'Extensions/WatchConnectivity' (https://github.com/PromiseKit/WatchConnectivity.git) registered for path 'Extensions/WatchConnectivity'
Submodule path 'Extensions/AVFoundation': checked out '0456c7dea92e676473b56730097a4c2ef8cbfcd0'
Submodule path 'Extensions/Accounts': checked out '6aa7ff68fb19c20e487cff2e1edc8e1fc759cb17'
Submodule path 'Extensions/AddressBook': checked out '42045c9b94421d845fdcb2ba283c12e2af97eaf1'
Submodule path 'Extensions/Alamofire': checked out 'e188ed4f13b9c4bcd9d344e65937ee5edcb3eefd'
Submodule path 'Extensions/AssetsLibrary': checked out '3268184eb1aed4dbb9b1037f02f84ccc401a53ce'
Submodule path 'Extensions/Bolts': checked out '341ec9fe113d795057c3fbfc5ae2cf826678de80'
Submodule path 'Extensions/CloudKit': checked out 'd48a7d862a31af44fbd95e92c594cbcd0efe1d72'
Submodule path 'Extensions/CoreBluetooth': checked out '9a7ed2bffbaca647be50f729b3e45761869d88f7'
Submodule path 'Extensions/CoreLocation': checked out 'bc3e9c9dc7b8659988d7bfb835eb05fa4ec0678f'
Submodule path 'Extensions/EventKit': checked out '6126aae80d9243f5c3bf2c5f04c020db3161f658'
Submodule path 'Extensions/Foundation': checked out 'a0f1c7c58e25042002aa201167b701ca92d68632'
Submodule path 'Extensions/MapKit': checked out 'defb8dd5aa5270e4c1203be2beeb85c02f56aec0'
Submodule path 'Extensions/MessagesUI': checked out '0ebd015a773655b21422cd1a76e472bef0a588d1'
Submodule path 'Extensions/OMGHTTPURLRQ': checked out '3cde4203ef3109445ef41b08a2c95c995266de29'
Submodule path 'Extensions/Photos': checked out '114aa21b2fc6ef29708b6c6dfd8859b7eb3b379b'
Submodule path 'Extensions/QuartzCore': checked out '2dd74072d4332efddf898a30a346066b6834eb53'
Submodule path 'Extensions/Social': checked out '8a0c87e660ba64868fc46e2c5d3b11f877503e7c'
Cloning into '/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-46795-15l7zxz'...
Note: checking out 'f8d7d24ee5c6cfa9cbe691779dd0a7175fc19aab'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-46795-15l7zxz/Extensions/AVFoundation'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-46795-15l7zxz/Extensions/Accounts'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-46795-15l7zxz/Extensions/AddressBook'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-46795-15l7zxz/Extensions/Alamofire'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-46795-15l7zxz/Extensions/AssetsLibrary'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-46795-15l7zxz/Extensions/Bolts'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-46795-15l7zxz/Extensions/CloudKit'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-46795-15l7zxz/Extensions/CoreBluetooth'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-46795-15l7zxz/Extensions/CoreLocation'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-46795-15l7zxz/Extensions/EventKit'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-46795-15l7zxz/Extensions/Foundation'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-46795-15l7zxz/Extensions/MapKit'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-46795-15l7zxz/Extensions/MessagesUI'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-46795-15l7zxz/Extensions/OMGHTTPURLRQ'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-46795-15l7zxz/Extensions/Photos'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-46795-15l7zxz/Extensions/QuartzCore'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-46795-15l7zxz/Extensions/Social'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-46795-15l7zxz/Extensions/StoreKit'...
fatal: unable to access 'https://github.com/PromiseKit/StoreKit.git/': Failed to connect to github.com port 443: Operation timed out
fatal: clone of 'https://github.com/PromiseKit/StoreKit.git' into submodule path '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-46795-15l7zxz/Extensions/StoreKit' failed
```

**Comment by mxcl** [comment]
Try again.

**Comment by yangzhixiao** [comment]
still error...

**Comment by mxcl** [comment]
The error is a timeout, so I can't suggest anything but keep trying.

**Comment by yangzhixiao** [comment]
Installing PromiseKit (4.0.1)

[!] Error installing PromiseKit
[!] /usr/bin/git clone https://github.com/mxcl/PromiseKit.git /var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-53619-z5t07l --single-branch --depth 1 --branch 4.0.1 --recursive

Submodule 'Extensions/AVFoundation' (https://github.com/PromiseKit/AVFoundation) registered for path 'Extensions/AVFoundation'
Submodule 'Extensions/Accounts' (https://github.com/PromiseKit/Accounts.git) registered for path 'Extensions/Accounts'
Submodule 'Extensions/AddressBook' (https://github.com/PromiseKit/AddressBook.git) registered for path 'Extensions/AddressBook'
Submodule 'Extensions/Alamofire' (https://github.com/PromiseKit/Alamofire) registered for path 'Extensions/Alamofire'
Submodule 'Extensions/AssetsLibrary' (https://github.com/PromiseKit/AssetsLibrary.git) registered for path 'Extensions/AssetsLibrary'
Submodule 'Extensions/Bolts' (https://github.com/PromiseKit/Bolts.git) registered for path 'Extensions/Bolts'
Submodule 'Extensions/CloudKit' (https://github.com/PromiseKit/CloudKit.git) registered for path 'Extensions/CloudKit'
Submodule 'Extensions/CoreBluetooth' (https://github.com/PromiseKit/CoreBluetooth.git) registered for path 'Extensions/CoreBluetooth'
Submodule 'Extensions/CoreLocation' (https://github.com/PromiseKit/CoreLocation.git) registered for path 'Extensions/CoreLocation'
Submodule 'Extensions/EventKit' (https://github.com/PromiseKit/EventKit.git) registered for path 'Extensions/EventKit'
Submodule 'Extensions/Foundation' (https://github.com/PromiseKit/Foundation.git) registered for path 'Extensions/Foundation'
Submodule 'Extensions/MapKit' (https://github.com/PromiseKit/MapKit.git) registered for path 'Extensions/MapKit'
Submodule 'Extensions/MessagesUI' (https://github.com/PromiseKit/MessagesUI.git) registered for path 'Extensions/MessagesUI'
Submodule 'Extensions/OMGHTTPURLRQ' (https://github.com/PromiseKit/OMGHTTPURLRQ) registered for path 'Extensions/OMGHTTPURLRQ'
Submodule 'Extensions/Photos' (https://github.com/PromiseKit/Photos.git) registered for path 'Extensions/Photos'
Submodule 'Extensions/QuartzCore' (https://github.com/PromiseKit/QuartzCore.git) registered for path 'Extensions/QuartzCore'
Submodule 'Extensions/Social' (https://github.com/PromiseKit/Social.git) registered for path 'Extensions/Social'
Submodule 'Extensions/StoreKit' (https://github.com/PromiseKit/StoreKit.git) registered for path 'Extensions/StoreKit'
Submodule 'Extensions/SystemConfiguration' (https://github.com/PromiseKit/SystemConfiguration) registered for path 'Extensions/SystemConfiguration'
Submodule 'Extensions/UIKit' (https://github.com/PromiseKit/UIKit.git) registered for path 'Extensions/UIKit'
Submodule 'Extensions/WatchConnectivity' (https://github.com/PromiseKit/WatchConnectivity.git) registered for path 'Extensions/WatchConnectivity'
Submodule path 'Extensions/AVFoundation': checked out '0456c7dea92e676473b56730097a4c2ef8cbfcd0'
Submodule path 'Extensions/Accounts': checked out '6aa7ff68fb19c20e487cff2e1edc8e1fc759cb17'
Submodule path 'Extensions/AddressBook': checked out '42045c9b94421d845fdcb2ba283c12e2af97eaf1'
Submodule path 'Extensions/Alamofire': checked out 'e188ed4f13b9c4bcd9d344e65937ee5edcb3eefd'
Submodule path 'Extensions/AssetsLibrary': checked out '3268184eb1aed4dbb9b1037f02f84ccc401a53ce'
Submodule path 'Extensions/Bolts': checked out '341ec9fe113d795057c3fbfc5ae2cf826678de80'
Submodule path 'Extensions/CloudKit': checked out 'd48a7d862a31af44fbd95e92c594cbcd0efe1d72'
Submodule path 'Extensions/CoreBluetooth': checked out '9a7ed2bffbaca647be50f729b3e45761869d88f7'
Cloning into '/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-53619-z5t07l'...
Note: checking out 'f8d7d24ee5c6cfa9cbe691779dd0a7175fc19aab'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-53619-z5t07l/Extensions/AVFoundation'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-53619-z5t07l/Extensions/Accounts'...
# Uncomment this line to define a global platform for your project
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-53619-z5t07l/Extensions/AddressBook'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-53619-z5t07l/Extensions/Alamofire'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-53619-z5t07l/Extensions/AssetsLibrary'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-53619-z5t07l/Extensions/Bolts'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-53619-z5t07l/Extensions/CloudKit'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-53619-z5t07l/Extensions/CoreBluetooth'...
# Uncomment this line to define a global platform for your project
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-53619-z5t07l/Extensions/CoreLocation'...
fatal: unable to access 'https://github.com/PromiseKit/CoreLocation.git/': Failed to connect to github.com port 443: Operation timed out
fatal: clone of 'https://github.com/PromiseKit/CoreLocation.git' into submodule path '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-53619-z5t07l/Extensions/CoreLocation' failed


[!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`
yangzhixiaodeMacBook-Pro:testnewios jerry$ vim Podfile
yangzhixiaodeMacBook-Pro:testnewios jerry$ pod update

[!] Invalid `Podfile` file: undefined method `latform' for #<Pod::Podfile:0x007fcdb201d218>. Updating CocoaPods might fix the issue.

 #  from /Users/jerry/Documents/Discover/testnewios/Podfile:2
 #  -------------------------------------------
 #  # Uncomment this line to define a global platform for your project
 >  latform :ios, '9.0'
 #  # Uncomment this line if you're using Swift
 #  -------------------------------------------
yangzhixiaodeMacBook-Pro:testnewios jerry$ vim Podfile
yangzhixiaodeMacBook-Pro:testnewios jerry$ pod update
Update all pods
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0`
Updating local specs repositories

CocoaPods 1.1.0.rc.2 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Installing PromiseKit (4.0.1)

[!] Error installing PromiseKit
[!] /usr/bin/git clone https://github.com/mxcl/PromiseKit.git /var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz --single-branch --depth 1 --branch 4.0.1 --recursive

Submodule 'Extensions/AVFoundation' (https://github.com/PromiseKit/AVFoundation) registered for path 'Extensions/AVFoundation'
Submodule 'Extensions/Accounts' (https://github.com/PromiseKit/Accounts.git) registered for path 'Extensions/Accounts'
Submodule 'Extensions/AddressBook' (https://github.com/PromiseKit/AddressBook.git) registered for path 'Extensions/AddressBook'
Submodule 'Extensions/Alamofire' (https://github.com/PromiseKit/Alamofire) registered for path 'Extensions/Alamofire'
Submodule 'Extensions/AssetsLibrary' (https://github.com/PromiseKit/AssetsLibrary.git) registered for path 'Extensions/AssetsLibrary'
Submodule 'Extensions/Bolts' (https://github.com/PromiseKit/Bolts.git) registered for path 'Extensions/Bolts'
Submodule 'Extensions/CloudKit' (https://github.com/PromiseKit/CloudKit.git) registered for path 'Extensions/CloudKit'
Submodule 'Extensions/CoreBluetooth' (https://github.com/PromiseKit/CoreBluetooth.git) registered for path 'Extensions/CoreBluetooth'
Submodule 'Extensions/CoreLocation' (https://github.com/PromiseKit/CoreLocation.git) registered for path 'Extensions/CoreLocation'
Submodule 'Extensions/EventKit' (https://github.com/PromiseKit/EventKit.git) registered for path 'Extensions/EventKit'
Submodule 'Extensions/Foundation' (https://github.com/PromiseKit/Foundation.git) registered for path 'Extensions/Foundation'
Submodule 'Extensions/MapKit' (https://github.com/PromiseKit/MapKit.git) registered for path 'Extensions/MapKit'
Submodule 'Extensions/MessagesUI' (https://github.com/PromiseKit/MessagesUI.git) registered for path 'Extensions/MessagesUI'
Submodule 'Extensions/OMGHTTPURLRQ' (https://github.com/PromiseKit/OMGHTTPURLRQ) registered for path 'Extensions/OMGHTTPURLRQ'
Submodule 'Extensions/Photos' (https://github.com/PromiseKit/Photos.git) registered for path 'Extensions/Photos'
Submodule 'Extensions/QuartzCore' (https://github.com/PromiseKit/QuartzCore.git) registered for path 'Extensions/QuartzCore'
Submodule 'Extensions/Social' (https://github.com/PromiseKit/Social.git) registered for path 'Extensions/Social'
Submodule 'Extensions/StoreKit' (https://github.com/PromiseKit/StoreKit.git) registered for path 'Extensions/StoreKit'
Submodule 'Extensions/SystemConfiguration' (https://github.com/PromiseKit/SystemConfiguration) registered for path 'Extensions/SystemConfiguration'
Submodule 'Extensions/UIKit' (https://github.com/PromiseKit/UIKit.git) registered for path 'Extensions/UIKit'
Submodule 'Extensions/WatchConnectivity' (https://github.com/PromiseKit/WatchConnectivity.git) registered for path 'Extensions/WatchConnectivity'
Submodule path 'Extensions/AVFoundation': checked out '0456c7dea92e676473b56730097a4c2ef8cbfcd0'
Submodule path 'Extensions/Accounts': checked out '6aa7ff68fb19c20e487cff2e1edc8e1fc759cb17'
Submodule path 'Extensions/AddressBook': checked out '42045c9b94421d845fdcb2ba283c12e2af97eaf1'
Submodule path 'Extensions/Alamofire': checked out 'e188ed4f13b9c4bcd9d344e65937ee5edcb3eefd'
Submodule path 'Extensions/AssetsLibrary': checked out '3268184eb1aed4dbb9b1037f02f84ccc401a53ce'
Submodule path 'Extensions/Bolts': checked out '341ec9fe113d795057c3fbfc5ae2cf826678de80'
Submodule path 'Extensions/CloudKit': checked out 'd48a7d862a31af44fbd95e92c594cbcd0efe1d72'
Submodule path 'Extensions/CoreBluetooth': checked out '9a7ed2bffbaca647be50f729b3e45761869d88f7'
Submodule path 'Extensions/CoreLocation': checked out 'bc3e9c9dc7b8659988d7bfb835eb05fa4ec0678f'
Submodule path 'Extensions/EventKit': checked out '6126aae80d9243f5c3bf2c5f04c020db3161f658'
Submodule path 'Extensions/Foundation': checked out 'a0f1c7c58e25042002aa201167b701ca92d68632'
Submodule path 'Extensions/MapKit': checked out 'defb8dd5aa5270e4c1203be2beeb85c02f56aec0'
Cloning into '/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz'...
Note: checking out 'f8d7d24ee5c6cfa9cbe691779dd0a7175fc19aab'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/AVFoundation'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/Accounts'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/AddressBook'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/Alamofire'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/AssetsLibrary'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/Bolts'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/CloudKit'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/CoreBluetooth'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/CoreLocation'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/EventKit'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/Foundation'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/MapKit'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/MessagesUI'...
fatal: unable to access 'https://github.com/PromiseKit/MessagesUI.git/': Failed to connect to github.com port 443: Operation timed out
fatal: clone of 'https://github.com/PromiseKit/MessagesUI.git' into submodule path '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/MessagesUI' failed

**Comment by yangzhixiao** [comment]
[!] Error installing PromiseKit
[!] /usr/bin/git clone https://github.com/mxcl/PromiseKit.git /var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz --single-branch --depth 1 --branch 4.0.1 --recursive

Submodule 'Extensions/AVFoundation' (https://github.com/PromiseKit/AVFoundation) registered for path 'Extensions/AVFoundation'
Submodule 'Extensions/Accounts' (https://github.com/PromiseKit/Accounts.git) registered for path 'Extensions/Accounts'
Submodule 'Extensions/AddressBook' (https://github.com/PromiseKit/AddressBook.git) registered for path 'Extensions/AddressBook'
Submodule 'Extensions/Alamofire' (https://github.com/PromiseKit/Alamofire) registered for path 'Extensions/Alamofire'
Submodule 'Extensions/AssetsLibrary' (https://github.com/PromiseKit/AssetsLibrary.git) registered for path 'Extensions/AssetsLibrary'
Submodule 'Extensions/Bolts' (https://github.com/PromiseKit/Bolts.git) registered for path 'Extensions/Bolts'
Submodule 'Extensions/CloudKit' (https://github.com/PromiseKit/CloudKit.git) registered for path 'Extensions/CloudKit'
Submodule 'Extensions/CoreBluetooth' (https://github.com/PromiseKit/CoreBluetooth.git) registered for path 'Extensions/CoreBluetooth'
Submodule 'Extensions/CoreLocation' (https://github.com/PromiseKit/CoreLocation.git) registered for path 'Extensions/CoreLocation'
Submodule 'Extensions/EventKit' (https://github.com/PromiseKit/EventKit.git) registered for path 'Extensions/EventKit'
Submodule 'Extensions/Foundation' (https://github.com/PromiseKit/Foundation.git) registered for path 'Extensions/Foundation'
Submodule 'Extensions/MapKit' (https://github.com/PromiseKit/MapKit.git) registered for path 'Extensions/MapKit'
Submodule 'Extensions/MessagesUI' (https://github.com/PromiseKit/MessagesUI.git) registered for path 'Extensions/MessagesUI'
Submodule 'Extensions/OMGHTTPURLRQ' (https://github.com/PromiseKit/OMGHTTPURLRQ) registered for path 'Extensions/OMGHTTPURLRQ'
Submodule 'Extensions/Photos' (https://github.com/PromiseKit/Photos.git) registered for path 'Extensions/Photos'
Submodule 'Extensions/QuartzCore' (https://github.com/PromiseKit/QuartzCore.git) registered for path 'Extensions/QuartzCore'
Submodule 'Extensions/Social' (https://github.com/PromiseKit/Social.git) registered for path 'Extensions/Social'
Submodule 'Extensions/StoreKit' (https://github.com/PromiseKit/StoreKit.git) registered for path 'Extensions/StoreKit'
Submodule 'Extensions/SystemConfiguration' (https://github.com/PromiseKit/SystemConfiguration) registered for path 'Extensions/SystemConfiguration'
Submodule 'Extensions/UIKit' (https://github.com/PromiseKit/UIKit.git) registered for path 'Extensions/UIKit'
Submodule 'Extensions/WatchConnectivity' (https://github.com/PromiseKit/WatchConnectivity.git) registered for path 'Extensions/WatchConnectivity'
Submodule path 'Extensions/AVFoundation': checked out '0456c7dea92e676473b56730097a4c2ef8cbfcd0'
Submodule path 'Extensions/Accounts': checked out '6aa7ff68fb19c20e487cff2e1edc8e1fc759cb17'
Submodule path 'Extensions/AddressBook': checked out '42045c9b94421d845fdcb2ba283c12e2af97eaf1'
Submodule path 'Extensions/Alamofire': checked out 'e188ed4f13b9c4bcd9d344e65937ee5edcb3eefd'
Submodule path 'Extensions/AssetsLibrary': checked out '3268184eb1aed4dbb9b1037f02f84ccc401a53ce'
Submodule path 'Extensions/Bolts': checked out '341ec9fe113d795057c3fbfc5ae2cf826678de80'
Submodule path 'Extensions/CloudKit': checked out 'd48a7d862a31af44fbd95e92c594cbcd0efe1d72'
Submodule path 'Extensions/CoreBluetooth': checked out '9a7ed2bffbaca647be50f729b3e45761869d88f7'
Submodule path 'Extensions/CoreLocation': checked out 'bc3e9c9dc7b8659988d7bfb835eb05fa4ec0678f'
Submodule path 'Extensions/EventKit': checked out '6126aae80d9243f5c3bf2c5f04c020db3161f658'
Submodule path 'Extensions/Foundation': checked out 'a0f1c7c58e25042002aa201167b701ca92d68632'
Submodule path 'Extensions/MapKit': checked out 'defb8dd5aa5270e4c1203be2beeb85c02f56aec0'
Cloning into '/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz'...
Note: checking out 'f8d7d24ee5c6cfa9cbe691779dd0a7175fc19aab'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/AVFoundation'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/Accounts'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/AddressBook'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/Alamofire'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/AssetsLibrary'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/Bolts'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/CloudKit'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/CoreBluetooth'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/CoreLocation'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/EventKit'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/Foundation'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/MapKit'...
Cloning into '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/MessagesUI'...
fatal: unable to access 'https://github.com/PromiseKit/MessagesUI.git/': Failed to connect to github.com port 443: Operation timed out
fatal: clone of 'https://github.com/PromiseKit/MessagesUI.git' into submodule path '/private/var/folders/47/5ccv4zrs413f28pwfskx53sh0000gn/T/d20160915-54412-klxhiz/Extensions/MessagesUI' failed

**Comment by mxcl** [comment]
Again, it timed out.
