### ISSUE TITLE
Include of non-modular header inside framework module 'PromiseKit.AAA_CocoaPods_Hack'

### ISSUE THREAD

**Issue by jakjothi** [mxcl/PromiseKit#544]
* PromiseKit version: ~> 4.0 (Swift 3 support)
* Xcode version: 8
* CocoaPods version: 0.39.0

My bridging header looks like
`#import <PromiseKit/PromiseKit.h>`

**Comment by mxcl** [comment]
Dupes #538. You need to upgrade CocoaPods.

**Comment by jakjothi** [comment]
@mxcl 

After upgraing It works, thanks 👍
