### ISSUE TITLE
No known class method for selector 'promiseWithResolverBlock:'

### ISSUE THREAD

**Issue by jonybur** [mxcl/PromiseKit#545]
* PromiseKit version: 4.0.1
* Xcode version: 8.0 (8A218a)
* CocoaPods version: 1.1.0.rc.2

Migrating to Swift 3, I get the "No known class method for selector 'promiseWithResolverBlock:'" in after.m and in AnyPromise.m
Tried to reinstall the pod with same (unsuccessful) result.

Any sort of help would be appreciated

**Comment by jonybur** [comment]
PromiseKit 4.0.1 is being installed as a dependency of a [repo called "AwaitKit"](https://github.com/yannickl/AwaitKit). Should I push a ticket there?

**Comment by nathanhosselton** [comment]
It should be installing `4.0.2`. If it's installing `4.0.1` then something is amiss with cocoapods. Blow away your Pods directory, do `pod repo update` and then `pod install`.

**Comment by mxcl** [comment]
In fact, 4.0.2 is not pushed to CocoaPods yet.

**Comment by mxcl** [comment]
I cannot reproduce this, so we need as much information as you can provide about your situation.

I am actively working on several projects that build PromiseKit via CocoaPods and do not experience this issue.

**Comment by jonybur** [comment]
I'm happy to provide as much info as I possibly can. Anything in particular?

**Comment by mxcl** [comment]
I can't think of anything specific, anything you can provide would be helpful. Sorry :(

**Comment by jonybur** [comment]
Sure. Well, I'm attaching Podfile and Podfile.lock
[Podfile.zip](https://github.com/mxcl/PromiseKit/files/480648/Podfile.zip)
Thanks again

**Comment by jonybur** [comment]
Understood. I'm uploading the Podfile and Podfile.lock
[Podfile.zip](https://github.com/mxcl/PromiseKit/files/480655/Podfile.zip)
Thank you

**Comment by mxcl** [comment]
Try this maybe:

```ruby
platform :ios, '10.0'
use_frameworks!

target 'Bais' do
  swift_version = "3.0"

  pod 'pop'
  pod 'DGActivityIndicatorView'
  pod 'AsyncDisplayKit', '>= 1.9.90'
  pod 'FBSDKCoreKit', '>= 4.15.1'
  pod 'FBSDKLoginKit', '>= 4.15.1'
  pod 'FBSDKShareKit', '>= 4.15.1'
  pod 'GoogleMaps', '>= 2.0.1'
  pod 'Alamofire', '>= 4.0.0'
  pod 'AwaitKit', '>= 2.0.0'
  pod 'ESTabBarController-swift',
    :git => 'https://github.com/jonybur/ESTabBarController.git'
  pod 'SwiftyJSON',
    :git => 'https://github.com/appsailor/SwiftyJSON.git',
    :branch => 'swift3'a
end

project '/Users/Jonathan/Desktop/Claxon/BAIS.xcodeproj'
```

**Comment by jonybur** [comment]
No luck. Now getting this, not sure if related: 

`[!] The `Bais [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Bais/Pods-Bais.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `Bais [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Bais/Pods-Bais.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.`

Which is amazing given that I am using the $(inherited) flag in my build settings and the only lib that is throwing a compiler error is PromiseKit with v4.0.1 being installed.

**Comment by mxcl** [comment]
Yeah the repo would definitely help

**Comment by andreyrd** [comment]
I had this issue as well, and clearing derived data is what ended up fixing it for me.

**Comment by jonybur** [comment]
I duplicated the folder where my repo is located in order to clean the project to upload it here, and after I duplicated it and ran - everything complied and worked just well.
Guess it's one of those days.
Thank you all

**Comment by mxcl** [comment]
4.0.2’s release is pending this bug: https://github.com/CocoaPods/CocoaPods/issues/5880

**Comment by ikaro88** [comment]
sorry if i am a little off topic but i really becoming crazy with this stupid sdk,

if i create a new project and add to my Unity game the GameAnalytics SDK (https://github.com/GameAnalytics/GA-SDK-UNITY)

when i compile the xcode project it give me a lot of error like this:

No known class method for selector 'addBusinessEventWithCurrency:amount:itemType:itemId:cartType:autoFetchReceipt:fields:'

for example on: [GameAnalytics addBusinessEventWithCurrency:currencyString amount:amountInteger itemType:itemTypeString itemId:itemIdString cartType:cartTypeString autoFetchReceipt:TRUE fields:fields_dict];

can everyone help me?
