### ISSUE TITLE
Docs list functions that are actaully constructors

### ISSUE THREAD

**Issue by mcfedr** [mxcl/PromiseKit#547]
Its a small thing, but annoying when trying to get to know the framework

Currently the docs show a function `Promise.resolved(value:)` but actually there is a constructor `Promise(value:)` and similar for creating a rejected promise.

**Comment by mxcl** [comment]
True, sorry. We changed this just before release and didn't realize that the docs had featured these functions.

**Comment by mxcl** [comment]
What docs? I can't find any references to this.

**Comment by mcfedr** [comment]
http://promisekit.org/docs/handbook/Classes/Promise.html

**Comment by mxcl** [comment]
Thanks, this change is pending:

* https://github.com/realm/jazzy/issues/659
* https://github.com/CocoaPods/cocoadocs.org/pull/468

**Comment by mxcl** [comment]
Jazzy was *finally* updated so this is now fixed.
