### ISSUE TITLE
Result Unused

### ISSUE THREAD

**Issue by ignotusverum** [mxcl/PromiseKit#548]
* PromiseKit version:  4.0
* Xcode version:  8.0
* Swift version: 3.0

Doing basic promises like this:

```
somePromise().then { Void in  }
```

Causing warning: Result of call to 'then(on:execute:)' is unused

Couple of other examples:

```
somePromise()
somePromise().then { result-> Void in  }
```

Any idea what's causing it, or how can i fix it (without silencing like this _ = somePromise() )?

Thanks !

**Comment by mxcl** [comment]
This is deliberate, you should always return a promise or terminate it with a `catch`. In the rare case you are attaching a handler that is already error handled elsewhere use `_ = foo.then`

If you believe we are wrong in this decision please provide examples.

**Comment by ignotusverum** [comment]
Understood, thanks for explanation

**Comment by ChristianKienle** [comment]
Just a quick comment: You can also just do something like this:

`then { ... in }.always{}`

**Comment by ChristianKienle** [comment]
And to make it even better you can extend Promise and "give" always a different name that internally just calls always and returns nothing.
