### ISSUE TITLE
Add `@discardableResult` annotation to `then`

### ISSUE THREAD

**Issue by zlangley** [mxcl/PromiseKit#549]
* PromiseKit version: 4.0
* Xcode version: 8.0

I noticed that `catch` and `tap` have the `@discardableResult` annotation, but `then` does not. It seems perfectly reasonable to ignore the result of `then` in many cases.

Adding this annotation allows us to do away with the ugly underscore assignment.
```
// Without an assignment, Swift gives a warning.
_ = PHPhotoLibrary.requestAuthorization().then { authorized in
    print(authorized)  // => true or false
}

// By annotating `then` with `@discardableResult`, Swift allows us to ignore the result without a warning.
PHPhotoLibrary.requestAuthorization().then { authorized in
    print(authorized)  // => true or false
}
```

**Comment by mxcl** [comment]
Dupes #548. This is intentional.

**Comment by zlangley** [comment]
Thanks for the quick reply. Makes sense.

**Comment by mxcl** [comment]
I'm willing to be wrong on this, discussion welcome. IME there aren't *many* times where the chain shouldn't be returned or terminated so the trade off feels right.

**Comment by jomnius** [comment]
I have the same problem and noticed that this ticket is closed. However I couldn't clearly see the fix: just keep using the ugly _ = syntax? Not really complaining, just curious of what is the recommended fix.

**Comment by mxcl** [comment]
Yes, `_ =` is recommended. Or figure out why you are not catching, or provide an example here.

**Comment by donpark** [comment]
Yeah, `_ = ` is what I use too.

I think the most compelling example of *catch-less* Promise is infallible async operations.

**Comment by zlangley** [comment]
> I think the most compelling example of catch-less Promise is infallible async operations.

This is the example I was going to give, but they seem rare in enough in practice. Also, it may still be better to catch anyway and assert your claim:

```
infallibleTask().then {
    // …
}.catch { _ in
    assertionFailure("…")
}
```
