### ISSUE TITLE
PromiseKit build failed

### ISSUE THREAD

**Issue by boardmain** [mxcl/PromiseKit#550]
- PromiseKit version: 4.0
- Xcode version: 8.0
- CocoaPods version: 1.1.0.rc.2
  Mac OS Sierra
  Swift 3

after recets upgrade
build fails withi this errors:

```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/PromiseKit-umbrella.h"
        ^
/Users/francesco/Library/Developer/Xcode/DerivedData/astaLive-akmhaneumiopcdfoxvylaebquksf/Build/Products/Debug-iphonesimulator/PromiseKit/PromiseKit.framework/Headers/PromiseKit-umbrella.h:3:9: note: in file included from /Users/francesco/Library/Developer/Xcode/DerivedData/astaLive-akmhaneumiopcdfoxvylaebquksf/Build/Products/Debug-iphonesimulator/PromiseKit/PromiseKit.framework/Headers/PromiseKit-umbrella.h:3:
#import "AAA-CocoaPods-Hack.h"
        ^
/Users/francesco/Library/Developer/Xcode/DerivedData/astaLive-akmhaneumiopcdfoxvylaebquksf/Build/Products/Debug-iphonesimulator/PromiseKit/PromiseKit.framework/Headers/AAA-CocoaPods-Hack.h:14:9: error: 'PromiseKit/PromiseKit.h' file not found
#import <PromiseKit/PromiseKit.h>
        ^
<unknown>:0: error: could not build Objective-C module 'PromiseKit'

```

**Comment by mxcl** [comment]
Delete `Pods`, remove CocoaPods cache, `pod install` again.

**Comment by teaualune** [comment]
Hi @mxcl , i had exact the same problem with @boardmain but that doesn't work either

I'm using PromiseKit 4.0 (resolved to 4.0.1), Xcode 8.0, CocoaPods 1.1.0.rc.2 and OS X 10.11.8

The error message in `AAA-CocoaPods-Hack.h` simply shows `'PromiseKit/PromiseKit.h' file not found
#import <PromiseKit/PromiseKit.h>`, so it is difficult to figure out what's going on

**Comment by boardmain** [comment]
tried to delete all.. same problem

**Comment by zhenyakoval** [comment]
Same error:
```
.../Build/Products/Debug-iphonesimulator/PromiseKit/PromiseKit.framework/Headers/AAA-CocoaPods-Hack.h:14:9: error: 'PromiseKit/PromiseKit.h' file not found
<unknown>:0: error: could not build Objective-C module 'PromiseKit'
```
I'm using PromiseKit (4.0.1), Xcode 8.0, CocoaPods 1.1.0.rc.2 and OS X 10.11.6.

**Comment by mxcl** [comment]
Works for me. I'm using PromiseKit in four different projects. All fine.

**Comment by mxcl** [comment]
I suggest blowing away cocoapods. Updating. Clearing its cache. Etc.

**Comment by mxcl** [comment]
Go through our closed issues too. There were similar reports fixed by doing similar things to what I said.

**Comment by mxcl** [comment]
Or if you provide a sample project I can try and fix.

**Comment by mxcl** [comment]
Sample project needed. Thanks.

**Comment by PerishableDave** [comment]
@boardmain 

I was having the same problems. I tried `rm -rf Pods/` with no success. Eventually I upgraded to Cocoapods 1.0.1 and removed all my Xcode cached files as per the link below. I then removed Pods/ again, pod installed, rebuilt, and finally got a success. Give it a try and see if you have any luck?

http://stackoverflow.com/questions/5714372/how-to-empty-caches-and-clean-all-targets-xcode-4

**Comment by mxcl** [comment]
Closing, assuming CocoaPods issue.

**Comment by rupalchawla** [comment]
Thanks @PerishableDave  cleaning out ~/Library/Developer/Xcode/DerivedData manually per link worked!

**Comment by alex-vasenin** [comment]
Having the same problem `.../Pods/PromiseKit/Sources/AAA-CocoaPods-Hack.h:14:9: 'PromiseKit/PromiseKit.h' file not found` with Xcode 8.3, PromiseKit 4.1.7 and CocoaPods 1.2.0. Deleting `Pods`, `~/Library/Caches/CocoaPods/`, `~/Library/Developer/Xcode/DerivedData` and even `.../org.llvm.clang/ModuleCache` didn't helped. Any other ideas?

**Comment by mxcl** [comment]
In our experience, do it again and again until it works.

**Comment by alex-vasenin** [comment]
Thank you Max! What did helped (temporary and *very ugly*) is replacing `#import <PromiseKit/PromiseKit.h>` with `#import "PromiseKit.h"` in the pod sources everywhere (plus the same substitute for `AnyPromise.h`). Any thoughts on this?

**Comment by mxcl** [comment]
Hmm, this is due to our hack. I have figured out how to remove this hack in the PMK5 experimental branch, so I need to back port this.

**Comment by alex-vasenin** [comment]
Damn, my workaround doesn't work while archiving 😕

**Comment by mxcl** [comment]
I have removed `AAA-CocoaPods-Hack.h` in 4.2.0 (currently being pushed). Closing, reopen if not fixed.

**Comment by alex-vasenin** [comment]
For the record, for me the problem was still relevant even with PromiseKit 4.2.2 and after a lot of pain and despair I managed to solve it in two steps:

1. Error `.../PromiseKit-Swift.h:141:9: 'PromiseKit/PromiseKit.h' file not found` with following `.../MyHeader.h:9:9: Could not build module 'PromiseKit'` was solved by moving customization of FRAMEWORK_SEARCH_PATH from project level to individual targets.

2. Error `.../PromiseKit.framework/Headers/PromiseKit-Swift.h:148:1: Duplicate interface definition for class 'AnyPromise'` which appeared after step 1 was solved by changing `#import "PromiseKit.h"` to `@import PromiseKit;` in my own code.

**Comment by mxcl** [comment]
Yes, never import frameworks with quotes, always use one of the two valid framework import syntaxes.

**Comment by Voxar** [comment]
Just want to record that I had this issue where xcode was complaining about some PromiseKit umbrella header and that I was heled by @rupalchawla's comment . `rm -rf` your app DerivedData folder. 

I'm guessing it's a xcode module cache issue that isn't cleaned with an xcode clean action.
