### ISSUE TITLE
Use @discardableResult to reduce Swift warnings

### ISSUE THREAD

**Issue by stephengazzard** [mxcl/PromiseKit#551]
* PromiseKit version: 4.0.1
* Xcode version: 8.0 (8A218a)
* CocoaPods version: 1.1.0.rc.2

Given code in the following format:
```
networkService.json(fromRequest: requestConstructor).then { response -> Void in
    //…
}
```

I often get this warning:
```
Result of call to 'then(on:execute:)' is unused
```

It seems like we should be able to resolve this with `@discardableResult` (https://github.com/apple/swift-evolution/blob/master/proposals/0047-nonvoid-warn.md, http://stackoverflow.com/questions/37939573/result-of-call-to-myfunction-is-unused)

**Comment by nathanhosselton** [comment]
Intentional, but discussion is welcome.

Dupes #548 and #549.

**Comment by randomiser** [comment]
Can you add some details about how best to handle this to the documentation? Thanks in advance!

**Comment by mxcl** [comment]
Yjeee
