### ISSUE TITLE
KVOProxy.observeValue might need to be fileprivate in Xcode 8.1

### ISSUE THREAD

**Issue by ryanschneider** [mxcl/PromiseKit#557]
* PromiseKit version: 4.0.3
* Xcode version: 8.1 beta [Version 8.1 beta (8T29o)]
* CocoaPods version: 1.0.1

Ok, this one has me kind of baffled.  I just upgraded my pod from 4.0.1 to 4.0.3 and am getting a compiler error in NSObject+Promise.swift:

```
/Users/****/Pods/PromiseKit/Extensions/Foundation/Sources/NSObject+Promise.swift:51:27: error: overriding instance method must be as accessible as its enclosing type
    private override func observeValue(forKeyPath keyPath: String?, of object: Any?, change: [NSKeyValueChangeKey : Any]?, context: UnsafeMutableRawPointer?) {
    ~~~~~~~               ^
    fileprivate
Foundation.NSObject:3:15: note: overridden declaration is here
    open func observeValue(forKeyPath keyPath: String?, of object: Any?, change: [NSKeyValueChangeKey : Any]?, context: UnsafeMutableRawPointer?)
              ^
```

Basically, it wants me to change `private` -> `fileprivate`, which then compiles just fine.  What's weird is that AFAICT 4.0.1's sources always had this as `private`, but we keep our Pods checked into git and I can confirm that the one I last used for 4.0.1 also had `fileprivate`.

So, what I *think* is happening is that Xcode 8.1 requires this method to be marked `fileprivate` rather than private, and that I manually made this change the first time without noticing (I was hacking around in other Pods that hadn't been converted to Swift 3, so had chmod'ed things to stop Xcode from complaining about the files being locked).

Anyways, just a heads up as Xcode 8.1 is still beta, and there's good chance it's user error on my part somehow. :)

**Comment by ryanschneider** [comment]
Oh, also, I just realized this error was occurring when building my watchOS app, not the iPhone app, so maybe it's an issue with the watchOS SDK headers being slightly out of sync with the iOS SDK ones.

**Comment by mxcl** [comment]
Thanks for the report. I'll grab the beta and see what I can find out.

**Comment by stevenp** [comment]
This also occurs for me when trying to build a framework.
