### ISSUE TITLE
PromiseKit build failure: Duplicate Interface Definition for class 'AnyPromise'

### ISSUE THREAD

**Issue by johneke** [mxcl/PromiseKit#558]
* PromiseKit version: 4.0.3
* Xcode version: 8.0 (8A218a)
* CocoaPods version: 1.0.1

My app worked/built fine with Xcode 7. I upgraded to Xcode 8 and I start getting PromiseKit errors. I upgrade to PromiseKit ~> 4.0 and now I'm getting this error: `Duplicate Interface Definition for class 'AnyPromise'`

Here is my Podfile

```
use_frameworks!
platform :ios, '8.0'

target 'MyProject' do
	pod 'AFNetworking', '~> 3.0.4'
	pod 'PKRevealController', '~> 2.0.6'
	pod 'FXLabel', '~> 1.5.8'
	pod 'SwipeView', '~> 1.3.2'
	pod 'ActionSheetPicker-3.0', '~> 2.0.3'
	pod 'Flurry-iOS-SDK', '~> 7.3.0'
	pod 'KeenClient', '~> 3.5.0'
	pod 'PromiseKit', '~> 4.0'
	pod 'HCSStarRatingView', '~> 1.4.3'
	pod 'SPGooglePlacesAutocomplete', '~> 1.0.5'
	pod 'HMSegmentedControl', '~> 1.5.2'
	pod 'SZTextView', '~> 1.2.2'
	pod 'QBImagePickerController', '~> 3.4.0'

	post_install do |installer|
		installer.pods_project.targets.each do |target|
			target.build_configurations.each do |config|
				config.build_settings['SWIFT_VERSION'] = '3.0'
			end
		end
	end
end
```

I might be doing something wrong. Im just out of ideas as to what that could be. If you could offer some pointers, that would help a lot. Thanks a lot for your time

**Comment by mxcl** [comment]
Can you provide the full error from the build log?

**Comment by johneke** [comment]
Thanks for the speedy response @mxcl! I was able to fix the issue by taking out all spots where I had `#import "AnyPromise.h"` and replacing them with `@import PromiseKit;`

That fixed it! Error was super weird though. Sorry for the bother! Hopefully this helps someone else in the future
