### ISSUE TITLE
4.0.3 Build errors after carthage update

### ISSUE THREAD

**Issue by RoninSTi** [mxcl/PromiseKit#559]
* PromiseKit version: 4.0.3
* Xcode version: 8.0
* Carthage version: v18

A carthage update to 4.0.3 for swift 3.0 results in the error in the snapshot below.  I tried clearing derived data and the carthage cache.  Any suggestions?

<img width="1512" alt="screen shot 2016-10-01 at 7 03 44 pm" src="https://cloud.githubusercontent.com/assets/9053846/19017510/64c76f94-880a-11e6-8d21-be1d4343e505.png">

**Comment by mxcl** [comment]
Your cache is still broken somehow since 4.x does *not* have a `Categories` directory, only 3.x does.

**Comment by RoninSTi** [comment]
Thank you for the quick reply!  Yeah that's what I figured, going to try a fresh install and see if that helps.  I'll close if that fixes it.
