### ISSUE TITLE
Promise<Void> catch->Void is ambiguous

### ISSUE THREAD

**Issue by wiruzx** [mxcl/PromiseKit#56]
I thought that swift incorrectly define type of a closure, but casting doesn't help. 
Example from README.md doesn't work for me as well.
Is it bug, or i'm doing something wrong?

![screenshot](http://i.imgur.com/E1VygZ4.png)

```swift
let promise: Promise<Int> = Promise({ success, failure in
    success(10)
})
        
promise.then { number in
    self.remainingTimeLabel.text = "int is \(number)"
}.catch { error in
    self.remainingTimeLabel.text = "erorr is \(error)"
}
```

**Comment by paztis** [comment]
The catch signature is strange
```swift
(0) public func catch(body:(NSError) -> T) -> Promise<T> 
(1) public func catchbody:(NSError) -> Void) -> Void 
(2) public func catch(body:(NSError) -> Promise<T>) -> Promise<T>
```
A catch must always return a new Promise, otherwise we can not chain new promises:

```swift
promiseA.then { result -> T in
 ...
}.catch { error in
 ...
}.then {
 ...
}
```

So the signature may be
```swift
(0) public func catch(body:(NSError) -> T) -> Promise<T> 
(1) public func catchbody:(NSError) -> Void) -> Promise<Void>
(2) public func catch(body:(NSError) -> Promise<T>) -> Promise<T>
```

**Comment by mxcl** [comment]
`0` *is* `1`.

Honestly I can't remember exactly why `catch(body:(NSError) -> Void) -> Void` exists. I don't think I made it without consideration, though that consideration may have been due to compiler bugs that are fixed now.

I've been waiting on a version of Swift that has better handling for generics. Sadly 1.2 is not it. So Swift PromiseKit is still not great.

Possibly the solution is to make a `-then:(^(Id))block` method on `objc` promiseKit and to push that for now. Currently using objc PromiseKit in swift is painful because all the `then` methods take `id` as the parameter (to allow variable parameter blocks to passed).

**Comment by allen-zeng** [comment]
IMO this is definitely a compiler issue.

Given the function signatures as they currently are:
```
[0] func catch(onQueue q:dispatch_queue_t = dispatch_get_main_queue(), body:(NSError) -> T) -> Promise<T>
[1] func catch(onQueue q:dispatch_queue_t = dispatch_get_main_queue(), body:(NSError) -> Void) -> Void
```

What the compiler _should_ be able to see is the fact that there is a specialized implementation of ```catch```, i.e. ```1```, and use that implementation instead unless there is another constraint that invalidates that selection, e.g.
```
// the compiler should pick implementation 0 in this case
let p: Promise<Void> = promiseA.catch {
    error -> Void in
    ...
}
```

Otherwise the implication is a generic implementation _without very specific constraints_ always get picked over its specialized counterpart.

**Comment by mxcl** [comment]
I tend to agree, though 1.2 still doesn't fix this, so I am developing a work around for 2.0.

**Comment by pgherveou** [comment]
just noticed that in swift 1.2 you can not do that anymore 
```swift
    let p = Promise<Bool>(value: true)
    let onError = { (error: NSError) -> Void in
      println("handle some error")
    }

    let _: () = p.then { (_) -> Void in
      println(" I made it! ")
      }.catch(onError)
```

you have to write it this way
```swift
    let p = Promise<Bool>(value: true)
    let onError = { (error: NSError) -> Void in
      println("handle some error")
    }

    let _: () = p.then { (_) -> Void in
      println(" I made it! ")
      }.catch(onQueue: dispatch_get_main_queue(), body: onError)
```

calling a closure directly work though
```swift
you have to write it this way
```swift
    let p = Promise<Bool>(value: true)

    let _: () = p.then { (_) -> Void in
      println(" I made it! ")
      }.catch  { (error: NSError) -> Void in
      println("handle some error")
    }
```

**Comment by mxcl** [comment]
```swift
let _: () = p.then { _ -> Void in
      println(" I made it! ")
}.catch(body: onError)
```

is enough.

**Comment by pgherveou** [comment]
cool that works thks for the tips

On Thu, Apr 9, 2015 at 3:22 PM, Max Howell <notifications@github.com> wrote:

> let _: () = p.then { _ -> Void in
>       println(" I made it! ")
> }.catch(body: onError)
>
> is enough.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mxcl/PromiseKit/issues/56#issuecomment-91230274>.
>



-- 
--
PG

**Comment by mxcl** [comment]
I've pushed the 2.0 branch which solves this problem by introducing a new function `recover` and making catch always terminating.

**Comment by tkQubo** [comment]
I have this workaround so far:

```swift
extension Promise {
    func then(body: T -> Void) -> Promise<Void!> {
        return then { result -> Void! in
            body(result)
            return ()
        }
    }
}
```

then the code below will compile:

```swift
class SomeClass {
    func somePromiseFunc() -> Promise<Int> {
        return Promise { (fulfill, _) in
            fulfill(42)
        }
    }
    
    func someFunc() {
        somePromiseFunc()
            .then { result in
                println(result)
            }
            .catch { error in
                println(error)
            }
    }
}
```

**Comment by ivanovvitaly** [comment]
@tkQubo your extension works for me in following way. Thanks!

promiseFunction()
            .then { result in
                // code here
            }
            .catch { error -> Void in // won't compile for me without -> Void
                // code here
            }
