### ISSUE TITLE
How do I wait for multiple promises of different types?

### ISSUE THREAD

**Issue by FruitAndAShape** [mxcl/PromiseKit#564]
* PromiseKit version: >= 4
* Xcode version: 8

I want to return a promise of an array of T's. Each T needs to be fixed up with some data retrieved from a different fetch of U's. So I need to wait for two fetches before being able to return the Ts.

Something like this...

```
func fetch() -> Promise<[T]>
{
  return when (**returns a Promise<[T]>**, **returns a Promise<[U]>**)
      .then { result in
          ... do stuff
          return [T]
      }
}
```
How do I do this? "When" seems to require all the promises to be of the same type.

**Comment by mxcl** [comment]
This should work. `when` does not require the same types. Do you have an error?

**Comment by FruitAndAShape** [comment]
Here is my actual code...

```
    open func getTours(_ parameters: SearchParameters) ->
        (apiRequest: ApiRequestProtocol, promise: Promise<(count: Int64, tours: [Tour])>) {

		return when (fulfilled: tourRepository.fetchTours(parameters), iApHelper.getProducts())

			.then { results in

				
			}
    }
```

Error is...

> Cannot convert value of type '(apiRequest: ApiRequestProtocol, promise: Promise<(count: Int64, tours: [Tour])>)' (aka '(apiRequest: ApiRequestProtocol, promise: Promise<(count: Int64, tours: Array<Tour>)>)') to expected argument type 'Promise<_>'

**Comment by mxcl** [comment]
You claim to be returning a tuple, but you are returning a Promise. Fix your return type or return the tuple you say you are.

**Comment by FruitAndAShape** [comment]
oh yeah! Thanks.

**Comment by FruitAndAShape** [comment]
This works...

```
    open func getTours(_ parameters: SearchParameters) ->
        (apiRequest: ApiRequestProtocol, promise: Promise<(count: Int64, tours: [Tour])>) {

		let tours = tourRepository.fetchTours(parameters)

		_ = when (fulfilled: tours.promise, iApHelper.getProducts())

			.then { results in

				return results.0
			}

		return tours
    }
```
