### ISSUE TITLE
URLError clashes with Foundation.URLError

### ISSUE THREAD

**Issue by jsgoupil** [mxcl/PromiseKit#565]
* PromiseKit version: 4.0.4
* Xcode version: 8.0
* CocoaPods version: 1.1.0.rc.3
* Swift 3

When trying to use URLError like this:

```
            let e: Error
            switch e {
            case URLError.badResponse(_, _, _): break;
            }
```

I get the following error:
Argument type 'URLError' does not conform to expected type '_ErrorCodeProtocol'

I believe it could be due that the Foundation also declares an URLError type as struct.

Is there a way to bypass this problem? I cannot compile with this issue.

**Comment by nathanhosselton** [comment]
If the problem is due to namespacing (I have not researched yet, just going off your observations), should be able to fix by doing `PromiseKit.URLError...`.

**Comment by jsgoupil** [comment]
That seems to fix the problem.

I have removed the import Foundation from the file but I was still getting an error.
I'll let you decide what you want to do about this bug. Thanks!

**Comment by mxcl** [comment]
It was not desired to conflict with Foundation, this only started happening since Swift 3 and the removal of the NS prefixes. So I renamed the type.

**Comment by mxcl** [comment]
Strictly this should be a major version bump, but I think everyone in the Swift community has just given up on semantic versioning until Swift 4.

**Comment by jsgoupil** [comment]
Holy snap, I hate Swift 3... I seriously can't make anything work yet...
Thanks for the update.

**Comment by jsgoupil** [comment]
For people reaching this thread searching how to get the URLError.badResponse to work with PromiseKit. It has been updated with the latest version to the following

Replace:
```
PromiseKit.UrlError.badResponse
```

By:
```
PMKURLError.badResponse
```

**Comment by mxcl** [comment]
Yeah sorry, I couldn't deprecate it without maintaining this same issue, so it had to just magically move.

We *should* maintain a changelog. It's a lot of work though.
