### ISSUE TITLE
How to chain then+catch with fulfill, reject

### ISSUE THREAD

**Issue by loryhuz** [mxcl/PromiseKit#566]
* PromiseKit version: 4.0.4
* Xcode version: 8.0
* CocoaPods version: 1.1.0.rc.2

I know there is a "wrap" keyword in promiseKit 4, but for a special use case, when I try to use fulfill/reject, I should be mistaken somewhere because I can't chain then+catch in a row.

Xcode is telling me `Missing return in a closure expected to return AnyPromise`, but I don't want to return a promise as my logic is done and just want to retrieve the error in the catch closure (with reject resolver)

Here is an example of simple wrapping which cause me some troubles:

```swift
        UserService.loginWithFacebookOn(viewController: self)
            .then { result in
                if result.isCancelled == false {
                    self.performSegue(withIdentifier: "", sender: nil)
                }
            }.catch { error in // Compiler error here
                self.view.show(message: error.localizedDescription, type: .error)
            }
```

Then the loginWithFacebook method:
```swift
static func loginWithFacebookOn(viewController: UIViewController) -> Promise<FBSDKLoginManagerLoginResult> {
        ...
        return Promise { fulfill, reject in
            loginManager.logIn(
                withReadPermissions: permissions,
                from: viewController,
                handler: { result, error in
                    if error != nil {
                        reject(error!)
                    } else {
                        fulfill(result!)
                    }
            })
        }
    }
```

**Comment by mxcl** [comment]
Specify `-> Void`. See FAQ or 60% of the closed tickets.

**Comment by loryhuz** [comment]
Oh didn't see it, thanks !

**Comment by mxcl** [comment]
Fixed it?

**Comment by loryhuz** [comment]
Yes sure

**Comment by mxcl** [comment]
Great. Let us know if you have any other issues.
