### ISSUE TITLE
PromiseKit catch is chained with firstly

### ISSUE THREAD

**Issue by jsgoupil** [mxcl/PromiseKit#567]
- PromiseKit version: 4.0.4
- Xcode version: 8

A new behavior that is quite hidden and not explained seems to be that the catch returning self will bubble up its error to the next promise?

Something like:

```
        firstly {
            self.refreshTokenIfNecessary()
            }.then { urlDataPromise in
                firstly {
                    return urlDataPromise // Let's make this return a badResponse
                    }
                    .then { data in
                        fulfill(URLDataPromiseData(error: false, promise: urlDataPromise))
                    }
                    .catch { (error: Error) -> Void in
                          // Do nothing here.
                }
            }.catch { (e: Error) -> Void in
                // This catch will be called!
        }
```

To avoid the problem, I have to put _ = in front of the 2nd firstly.

This is definitely a new behavior from PromiseKit2.0 that took me a while to understand, maybe a documentation or a better "return" mechanism should handle this?

The only way I caught that was by unit tests (lucky!)

PS. This code is simplified. Obviously I handle the error.

**Comment by mxcl** [comment]
In the experimental PMK5 branch I have altered `catch` to return a half-promise that *only* has a `finally` method. Hopefully that will make situations like this identifiable.

**Comment by mxcl** [comment]
Fixed in PromiseKit 5.
