### ISSUE TITLE
URLDataPromise is incompatible with contextual type AnyPromise

### ISSUE THREAD

**Issue by hamchapman** [mxcl/PromiseKit#572]
* PromiseKit version: 4.0.5
* Xcode version: 8.0 (8A218a)
* Carthage version: 0.18-19-g743fa0f

Also using PMKFoundation version 1.0.2.

I've got a function like this:

```swift
public func request(method: String, path: String, jwt: String? = nil) -> URLDataPromise {
    if jwt == nil && self.authorizer != nil {
        return firstly { _ -> Promise<String> in
            self.authorizer!.authorize()
        }.then { (jwt: String) -> URLDataPromise in
            self.client.request(method: method, path: path, jwt: jwt)
        }
    } else {
        return self.client.request(method: method, path: namespacedPath, jwt: jwt)
    }
}
```

where `self.authorizer` looks like this (simplified):

```swift
public class MyAuthorizer {
    public init() {}

    public func authorize() -> Promise<String> {
        return Promise { resolve, reject in
            resolve("some string")
        }
    }
}
```

and the `request` method in the `self.client` object looks like this:

```swift
public func request(method: String, path: String, jwt: String? = nil) -> URLDataPromise {
    let url = self.baseUrl.appendingPathComponent(path)
    var request = URLRequest(url: url)
    request.httpMethod = method

    return URLSession.shared.dataTask(with: request)
}
```

But on the `}.then { (jwt: String) -> URLDataPromise in` line I get an error that says:

```
Declared closure result 'URLDataPromise' is incompatible with contextual type AnyPromise
```

This is the same if I remove the `_ -> Promise<String> in` part of the line returning the `firstly` result.

This variation results in an error too:

```swift
public func request(method: String, path: String, jwt: String? = nil) -> URLDataPromise {
    if jwt == nil && self.authorizer != nil {
        self.authorizer!.authorize().then { generatedJwt in
            return self.client.request(method: method, path: path, jwt: jwt)
        }
    } else {
        return self.client.request(method: method, path: namespacedPath, jwt: jwt)
    }
}
```

This results in an error saying:

```
Missing return in a function expected to return URLDataPromise
```

I've seen some issues with similar errors and the first FAQ which seems to be about this (http://promisekit.org/faq/) but I can't seem to get the compiler to be happy.

Any ideas as to what I'm doing wrong?

Thanks

**Comment by mxcl** [comment]
Like it says, you’re missing a `return`:

```swift
public func request(method: String, path: String, jwt: String? = nil) -> URLDataPromise {
    if jwt == nil && self.authorizer != nil {
        self.authorizer!.authorize().then { generatedJwt in
            return self.client.request(method: method, path: path, jwt: jwt)
        }
    } else {
        return self.client.request(method: method, path: namespacedPath, jwt: jwt)
    }
}
```

Line 3 should `return`.

**Comment by hamchapman** [comment]
Hmmm, that then produces this error:

![screen shot 2016-10-26 at 17 10 40](https://cloud.githubusercontent.com/assets/2475150/19734383/3fec98f4-9b9f-11e6-9e03-2f476de5b4f7.png)

**Comment by mxcl** [comment]
Add `-> URLDataPromise`.

**Comment by hamchapman** [comment]
It then tries to insist I turn that into an `AnyPromise`:

<img width="830" alt="screen shot 2016-10-26 at 22 15 09" src="https://cloud.githubusercontent.com/assets/2475150/19745504/cabf195a-9bc9-11e6-9e55-324eacb15cc6.png">

**Comment by mxcl** [comment]
The problem here is:

```swift
public func request(method: String, path: String, jwt: String? = nil) -> URLDataPromise {
    if jwt == nil && self.authorizer != nil {

        // this following then returns `Promise` NOT `URLDataPromise`

        self.authorizer!.authorize().then { generatedJwt in
            return self.client.request(method: method, path: path, jwt: jwt)
        }
    } else {
        return self.client.request(method: method, path: namespacedPath, jwt: jwt)
    }
}
```

This is pretty hard to solve as far as I can tell.

**Comment by hamchapman** [comment]
Yeah the way I solved it was just to create my own `Promise<Data>` instead. 

Would be cool if `then` could work with `URLDataPromise` as well. I'm not 100% clear on why it can't but that's potentially a question for another issue in the future so I'll close this one. 

Thanks for the help!
