### ISSUE TITLE
Proposal to mark `then` with `@discardableResult`

### ISSUE THREAD

**Issue by johngibb** [mxcl/PromiseKit#574]
* PromiseKit version: 4.0
* Xcode version: 8.0

I'm thinking the majority of functions, such as `then`, should be marked with `@discardableResult`, to avoid having to write code like:

```
_ = api.login(user: "test", password: "1234").then { user in
    ....
}
````

Happy to submit a PR if you agree!

**Comment by mxcl** [comment]
Dupes #561, #551, #549, #548.

We consider this a feature, see other tickets for rationale. Thanks.
