### ISSUE TITLE
Compile error with Xcode 8.1

### ISSUE THREAD

**Issue by pipacs** [mxcl/PromiseKit#575]
* PromiseKit version: 4.0.3
* Xcode version: 8.1
* CocoaPods version: 1.0.1

Error when compilingNSObject+Promise.swift:

NSObject+Promise.swift:51:27: Overriding instance method must be as accessible as its enclosing type

Fix-it recommends to replace "private" with "fileprivate".

**Comment by mxcl** [comment]
Upgrade to PromiseKit 4.0.4, we released this in advance of Xcode 8.1.

**Comment by pipacs** [comment]
Great, thanks! It was just CocoaPods catching up slowly.
