### ISSUE TITLE
Importing promisekit 3.5.1 into a mixed-language framework target causes the framework to not generate a swift-generated header

### ISSUE THREAD

**Issue by klundberg** [mxcl/PromiseKit#576]
- PromiseKit version: 3.5.1
- Xcode version: 8.0
- CocoaPods version: 1.1.1

[promisekit-bug.zip](https://github.com/mxcl/PromiseKit/files/559492/promisekit-bug.zip)

See attached project to reproduce.

When I try to import PromiseKit into a swift file in a framework, then reference the generated swift header in an obj-c file in the same framework, the code fails to build as the generated header is not actually generated. This happens on 3.5.1 and swift 2, but when I tested with promisekit 4 and swift 3, it worked properly.

The example swift file implements a function that returns a promise (which wouldn't be exposed to objc, which is expected), but I've seen it fail just by importing the module and doing nothing else.

**Comment by mxcl** [comment]
Nuts, thanks.

**Comment by mxcl** [comment]
At this point we don't actively support 3.x
