### ISSUE TITLE
watchOS deployment target not explicitly set on 3.5.1

### ISSUE THREAD

**Issue by allen-zeng** [mxcl/PromiseKit#583]
* PromiseKit version: 3.5.1
* Xcode version: 8.1

When integrating PromiseKit as a submodule, the watchOS target uses Xcode's default deployment target, because no deployment target is explicitly set. This is contrary to the other platforms (iOS, macOS and tvOS), where the values are set to match what's in the podspec.

Setting the target is straight forward enough ([here's the comparison](https://github.com/mxcl/PromiseKit/compare/master...allen-zeng:xcode81-watchos-deployment-target?expand=1)), but I'm at a loss as to how to release 3.5.2.

Moving to Swift 3 and consequently PromiseKit 4.x isn't yet an option, unfortunately.

**Comment by mxcl** [comment]
We can still publish old versions to CocoaPods if that is what you mean.

**Comment by allen-zeng** [comment]
Yeah that part is easy enough. I can't create a pull request into a tag though, so we'll have to have a branch created where 3.5.1 is

**Comment by mxcl** [comment]
I'll add a branch for you
