### ISSUE TITLE
@discardableResult and recover

### ISSUE THREAD

**Issue by gmckenzi** [mxcl/PromiseKit#584]
* PromiseKit version: 4
* Xcode version: 8.1

I know that PromiseKit doesn't use discardableResult intentionally to encourage use of catch. Which is fine. But, why doesn't recover get the same treatment as catch? In other words, when I end a chain with recover, doesn't that satisfy the same design goal, and thus shouldn't recover be marked as discardableResult?

**Comment by mxcl** [comment]
You don’t have to recover the error, you could still throw.

I guess we *could* have multiple versions `recover`, if you use the one that doesn't throw then the result could be discarded.

**Comment by gmckenzi** [comment]
True enough. I hadn't considered that. It isn't how I'm using recover, but I understand your point. Carry on.

**Comment by mxcl** [comment]
I use it that way quite regularly, only recovering from some errors.
