### ISSUE TITLE
PromiseKit provides version 0.0.0

### ISSUE THREAD

**Issue by hariseldon78** [mxcl/PromiseKit#587]
* PromiseKit version: 4.0.4
* Xcode version: 8.1
* Carthage version: 0.18.1

Hi. I am transitioning from Cocoapods to carthage, in the hope to speed up the development. I removed PromiseKit from the `podfile`, made a `pod install`, and inserted a `github "mxcl/PromiseKit"` in the Cartfile. `carthage update`, then build and run on a device from xcode and at boot i get this error:

```
dyld: Library not loaded: @rpath/PromiseKit.framework/PromiseKit
  Referenced from: /var/containers/Bundle/Application/DE5187F4-85BF-4BB9-B48A-44C706CC29BD/Municipium.app/Municipium
  Reason: Incompatible library version: Municipium requires version 1.0.0 or later, but PromiseKit provides version 0.0.0
```

did I miss something?

In the Podfile i had this block, but that don't seem related:
```
# promisekit bug workaround
		installer.pods_project.targets.each do |target|
	  		next unless (target.name == 'PromiseKit')
	  		target.build_configurations.each do |config|
		  		config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
	  		end
  		end
```
 but I don't know how to replicate that in Carthage, and don't even know if it's still needed...

**Comment by mxcl** [comment]
With Carthage you have to manually embed the frameworks you use, the error suggests you are not doing this properly.
