### ISSUE TITLE
No known class method for selector 'promiseWithResolverBlock:'

### ISSUE THREAD

**Issue by p21jerfeson** [mxcl/PromiseKit#592]
* PromiseKit version: 4.0.4
* Xcode version:  Xcode 8
* CocoaPods version: 1.2.0.beta.1

Migrating to Swift 3, I get the "No known class method for selector 'promiseWithResolverBlock:'" in after.m and in AnyPromise.m
Tried to reinstall the pod with same (unsuccessful) result.
<img width="1280" alt="captura de tela 2016-11-17 as 10 47 48" src="https://cloud.githubusercontent.com/assets/11951887/20389936/5f6baa2e-acb3-11e6-9019-42b88da5ed2a.png">

**Comment by mxcl** [comment]
I believe this is a dupe and the solution was wiping out the cocoapods cache or similar. If this doesn't work keep browsing the closed tickets.

**Comment by p21jerfeson** [comment]
I saw another ticket with a similar problem, I did the same, I changed the folder, and it worked, but I wanted to know how to solve it, is it some kind of macOS cache, in folder structures, would you say?

**Comment by mxcl** [comment]
Changed which folder?

**Comment by p21jerfeson** [comment]
My project was done in a folder structure
/Folder1/folder2/folder3/app, I changed to folderx/app

**Comment by mxcl** [comment]
dafuq?
