### ISSUE TITLE
Improve Cancelation Documentation

### ISSUE THREAD

**Issue by yuvalrakavy** [mxcl/PromiseKit#600]
* PromiseKit version: 
* Xcode: 8.1

Is there a way to "cancel" a promise.

 Right now, if I have a pending promise, and I deallocate it

let a = Promise(resolvers: ...)
a = nil

 I will get a message "Pending Promise deallocated!..."
I suggest to have an API that will state that a is "cancelled". It will never be resolved or rejected. This should eliminate the above message.
 
 So in the above example:

let a = Promise(resolvers: ...)
a.cancel()
a = nil

will not show the "Pending Promise deallocated!" message

**Comment by ldiqual** [comment]
@yuvalrakavy Please take a look at http://promisekit.org/docs/, there's a hole section about cancellation. You'll want to throw a `CancellableError` which you can catch with `policy = .allErrors` and `error.isCancelledError`.

**Comment by mxcl** [comment]
We deliberately do not provide a `cancel` method because you should have explicit control over which parts of your app and which libraries you use can cancel your operations. If we provided `cancel` then any old library you import off cocoapods that uses PromiseKit could cancel anything. Hardly robust.

Thus if you need cancelation you can (with some effort) add it where you need it.

**Comment by mxcl** [comment]
Our cancellation documentation could use some work actually, my fault, I revised it about 4 months ago.

You can add a cancel function like so:

```swift

enum MyError: CancellableError {
    case foo
    var isCancelled: Bool { return true }
}

var cancel: (()-> Void)!

let promise = Promise { fulfill, reject in
    cancel = { r(MyError.cancel) }
}
```

**Comment by mxcl** [comment]
https://github.com/mxcl/PromiseKit/blob/master/Documentation/CommonPatterns.md#cancellation

**Comment by adrixpho** [comment]
Hi @mxcl I think there's a typo in the documentation about cancellation, the example cannot return a variable inside another scope and is missing a curly braces. I did something like this fixing the typo:

`func foo() -> (Promise<Void>, cancel: () -> Void) {
        var cancelme = false
        var cancelClosure : (() -> Void)!
        let promise = Promise<Void> { fulfill, reject in
            let task = Task(…)
            cancelClosure = {
                cancelme = true
                task.cancel()
                reject(NSError.cancelledError)
            }
            
            task.completion = { value in
                guard !cancelme else { reject(NSError.cancelledError) }
                fulfill(value)
                task.start()
            }
        }
        
        return (promise, cancelClosure)
    }`

Is that correct?

**Comment by mxcl** [comment]
Can you submit the PR? Much easier to tell what is is different in a PR.
