### ISSUE TITLE
Docs should start with Pod setup information

### ISSUE THREAD

**Issue by hk0i** [mxcl/PromiseKit#604]
* PromiseKit version: 4
* Xcode version: 8.1

[The documentation][pk-docs] says if I don't feel the docs meet the requirements to open a ticket.

# Expected

**Expectation**: [the docs from the promisekit.org][pk-docs] site should start out with setting up the pod in cocoapods. Of course, we should be familiar with pods and how to use them (I am) but it always helps to have a quick reference so we know the *exact name* of the pod to include.

After being redirected to the documentation from the [GitHub](https://github.com/mxcl/PromiseKit) page, from the `README.markdown` file I could gather the information I needed. All I'm suggesting here is to duplicate the following information on the `.org/docs/` page:

## Xcode 8 / Swift 3

```ruby
# CocoaPods >= 1.1.0-rc.2
swift_version = "3.0"
pod "PromiseKit", "~> 4.0"

# Carthage
github "mxcl/PromiseKit" ~> 4.0

# SwiftPM
let package = Package(
    dependencies: [
        .Package(url: "https://github.com/mxcl/PromiseKit", majorVersion: 4)
    ]
)
```

## Xcode 8 / Swift 2.3 or Xcode 7

```ruby
# CocoaPods
swift_version = "2.3"
pod "PromiseKit", "~> 3.5"

# Carthage
github "mxcl/PromiseKit" ~> 3.5
```

# Actual

Docs start out with swift code snippets.

# Conclusion

This is just a quick suggestion because I feel there is a small hole in the docs I had to click around for a bit and actually go open a GitHub ticket, then click around some more before I found the "first step" of the docs that I was looking for.

[pk-docs]: http://promisekit.org/docs/

**Comment by mxcl** [comment]
This info would cloud the main docs section, the reason it is in the README and the FAQ is because these are the entry points for most people to PromiseKit, GitHub is the first link on Google and the first link most people provide, the README is an overview of PMK + detailed instructions on how to install it. The FAQ duplicates this information because it is a frequently asked question.

So in conclusion, the information at /docs/ was very carefully considered to provide a concise overview of the capabilities of the framework, and adding installation instructions to it would lessen that impact.

**Comment by hk0i** [comment]
How about adding a setup link to reference the GitHub README? one more line will be just as concise more or less and solve the problem of people getting lost.

I'm not sure how common of an issue this is but once I was on the PromiseKit site I felt like I had to stay there and hunt around for the documentation, which actually wasn't on the site even though there was link titled **Doc**. The problem is that the documentation is distributed across different sites. I clicked on **Doc** expecting the full story or some reference to it, anyway.

**Comment by mxcl** [comment]
Yeah that would be cool IMO. Thanks.

> I'm not sure how common of an issue this is but once I was on the PromiseKit site I felt like I had to stay there and hunt around for the documentation

I relate. I'd only have one place, but people expect a README too.

The docs you were looking for are on at http://promisekit.org though: in the FAQ… unless I'm mistaken.

**Comment by hk0i** [comment]
Yeah I'm cycling through the [README](https://github.com/mxcl/PromiseKit), the [Objective-C portion of the documentation](http://promisekit.org/docs/objc/), the [FAQ](http://promisekit.org/faq/) and [this other thing that claims to be the documentation](http://promisekit.org/docs/handbook/index.html) that I found on a whim.

It's starting to come together.

I have an add-on suggestion, if I may. The docs never talk about which headers to include for objective-c. Right now I'm using:

```objc
#import "UIView+AnyPromise.h"
#import <PromiseKit/PromiseKit.h>
```

Which I'm assuming is right, but I had started off on the assumption that I only needed to `#import "AnyPromise.h"` since it was the "Objective C" implementation. The second import encapsulates everything I'm assuming (finding `PMKAfter` took some digging) through some random hacking I managed to get it working with this, more or less.

**Comment by mxcl** [comment]
All you need is `#import <PromiseKit/PromiseKit.h>`

PR welcome to improve such things.

**Comment by mxcl** [comment]
I reckon http://promisekit.org (specifically that page) should link to this, like a contents.

**Comment by hk0i** [comment]
I still haven't taken a look at it yet, but are you saying the sources for promisekit.org are also hosted on GitHub? I took a quick peek but I couldn't find where it's at. Just point me in the right direction and I'd be glad to help out.

**Comment by mxcl** [comment]
We use the GitHub standard gh-pages branch.

**Comment by hk0i** [comment]
Wow. I never knew about this. That's pretty neat.
I'll poke around with it when I get some time and send a PR :)

Thanks!

**Comment by mxcl** [comment]
I have updated the docs.

However we still start with an introduction to PromiseKit. This is the landing page for the project, it should introduce itself.

The getting started instructions are exactly next after the introduction.
