### ISSUE TITLE
Xcode 8.2 breaks 2.3 minimal changes branch

### ISSUE THREAD

**Issue by patrickjquinn** [mxcl/PromiseKit#606]
* PromiseKit version:  2.3-miniml-changes
* Xcode version: 8.2
* CocoaPods version: 1.2.0

Seems that minimal changes branch is broken by the latest Swift changes (I swear to god, Apple need to stop radically altering Swift with each new release of Xcode) in 8.2. Any chances you could update this branch to resolve this @mxcl ?

**Comment by mxcl** [comment]
Will take a look…

**Comment by patrickjquinn** [comment]
Thanks Max, sorry you've to support us legacy users! We very much appreciate it 👍

**Comment by mxcl** [comment]
It's my pleasure.

**Comment by mxcl** [comment]
Compiles for me… what's your error?

**Comment by patrickjquinn** [comment]
A ton, mostly syntax related i.e expected ';' joining parts of multi-clause condition in NSURLCondition+Promise.swift and complaints about 'dispatch_queue_t' being unavailable in swift in AnyPromise.swift 

I've attached a screenshot of the errors for what thats worth! 

![promkit](https://cloud.githubusercontent.com/assets/1819370/21245964/9759367e-c31d-11e6-98b8-106d48cf0455.png)

**Comment by mxcl** [comment]
Seems like it is being compiled with Swift 3 to me.

Is it possible your CocoaPods is building with Swift 3 for some reason?

**Comment by patrickjquinn** [comment]
Ohhh thats possible `use_frameworks!
pod "PromiseKit", :git => "https://github.com/mxcl/PromiseKit.git", :branch => "swift-2.3-minimal-changes"
end` is how i'm including it in my pods...

**Comment by mxcl** [comment]
It should default to Swift 2.3, but you could try adding `swift_version = "2.3"` at the top

**Comment by patrickjquinn** [comment]
Adding ```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '2.3'
    end
  end
end
```
To the end of the pod file (Which is essentially exactly what you suggested, only more convoluted) did the trick! Sorry for blaming your wonderful library, the fault lies with me!

**Comment by mxcl** [comment]
np, glad it is solved!
