### ISSUE TITLE
"NSTask+AnyPromise.h"  is missing

### ISSUE THREAD

**Issue by cherishloveyou** [mxcl/PromiseKit#607]
* PromiseKit version: 4.10
* Xcode version: 8.2

in macOS target. PMKFoundation.h.  #import "NSTask+AnyPromise.h", this file is missing, I think we did not need import it any more

**Comment by mxcl** [comment]
File exists: https://github.com/PromiseKit/Foundation/blob/be45e79c0627511d02af221e6ca04ec8de119e2e/Sources/NSTask%2BAnyPromise.h

You did not specify how you install PromiseKit, are you doing it manually?

**Comment by cherishloveyou** [comment]
at firsts, I installed it by cocoa pods, I try clean all pod to install, it's now ok.
