### ISSUE TITLE
Passing Promise<()> as a parameter

### ISSUE THREAD

**Issue by hunganh0403** [mxcl/PromiseKit#608]
## Scenario
Passing a myPromise: Promise<()> as a parameter to functionX to decides to execute it or not.
## Expected Results
When functionX decides not to run myPromise, myPromise shouldn't be executed
## Actual Results
myPromise still runs anyways, it doesn't care about functionX's decision 
## Sample Code
````Swift
func somePromise() -> Promise<()> {
    print("running it")
    return Promise(value: ())
}

func runIt() {
    func runPromiseIfNeeded(promise: Promise<()>) -> Promise<()> {
        //no, i dont want to run that promise
        return Promise(value: ())
    }
    
    runPromiseIfNeeded(promise: somePromise()).catch{ print($0) }
}

runIt()

````

[Sample project](https://github.com/mxcl/PromiseKit/files/665946/PromiseKitNestedFunction.zip)
## Versions
* PromiseKit version: 4.1.0
* Xcode version: Version 8.1 (8B62)
* Carthage version: 0.18

**Comment by nathanhosselton** [comment]
You're calling `somePromise()`, so yes, its returned promise will execute. This is expected behavior.

**Comment by mxcl** [comment]
Like Nathan says, If you don't want the code in `somePromise()` to execute, then don’t call it… this isn't PromiseKit, this is Swift.

**Comment by mxcl** [comment]
You want something like this, presumably:

```swift
func somePromise() -> Promise<()> {
    print("running it")
    return Promise(value: ())
}

func runIt() {
    func runPromiseIfNeeded(promise: () -> Promise<()>) -> Promise<()> {
        //no, i dont want to run that promise
        return Promise(value: ())
    }
    
    runPromiseIfNeeded(promise: somePromise).catch{ print($0) }
}

runIt()
```

**Comment by hunganh0403** [comment]
Thank you guys, now i clearly understand. Sorry for long reply (because i feel so ashamed).
