### ISSUE TITLE
Problems when migrating to Swift3, compilation error with URLSession.GET

### ISSUE THREAD

**Issue by aziz-boudi4** [mxcl/PromiseKit#609]
* PromiseKit version: 4.0
* 'PromiseKit/OMGHTTPURLRQ'
* Xcode version: 8.2.1
* CocoaPods version: 1.0.1

I'm trying to migrate from Swift2 to Swift3 and I'm having an issue with URLSession.GET

I went through the migration tool provided by XCode, and changed my "NSURLSession" calls into "URLSession" but I keep having this error message:

    "Use of Instance member 'GET' on type 'URLSession'; did you mean to use a value of type 'URLSession' instead?"

Here is my code:
```swift
open static func getData() -> Promise<[Station]> {
  return URLSession.GET("http://api.xxx.com/api/").asDataAndResponse().then { (data: NSData, _) -> [Station] in
        
     var stations = [Station]()
     // rest of the code to retrieve the data
        ...
        ...

     return stations
    }
 }
```

**Comment by mxcl** [comment]
You need to `pod 'PromiseKit/OMGHTTPURLRQ'` this is documented in our PromiseKit 4.0.0 release notes.

**Comment by aziz-boudi4** [comment]
I already have `pod 'promiseKit/OMGHTTPURLRQ'` in my podfile

**Comment by mxcl** [comment]
It's `get` with Swift 3.

**Comment by aziz-boudi4** [comment]
If I use `get` I get the error `Type URLSession' has no member `get`

But If I do this, I don't have an error anymore and the compiler is happy : 
     return URLSession().GET("http://api.xxx.com/api/").asDataAndResponse().then { (data , _) -> [Station] in

instead of : 
     return URLSession.GET("http://api.xxx.com/api/").asDataAndResponse().then { (data: NSData, _) -> [Station] in

Is it an acceptable solution, I don't know if it works because I still have other errors, but the compiler seems to be ok with this implementation

**Comment by aziz-boudi4** [comment]
After some more digging I found a solution : 

First I have to  to init URLSession with a configuration:
    `let URLSession1 = URLSession(configuration: .default)` 

Then I can call the 'GET' method : 
     

      `open static func getData() -> Promise<[Station]> {
           return URLSession1.GET("http://api.bart.gov/api/etd.aspx?cmd=etd&orig=ALL&key=ZW44-PTQ7-9ULT-DWE9").asDataAndResponse().then { (data, _) -> [Station] in`
        
             var stations = [Station]()
             // rest of the code to retrieve the data
             ...
             ...

             return stations
             }
           }`

**Comment by mxcl** [comment]
Oh right yeah, we moved the methods to instance methods.

Next time, I suggest reading the source documentation. Seriously.
