### ISSUE TITLE
PromiseKit Result<T> and Alamofire Result<Value> ambiguous

### ISSUE THREAD

**Issue by JosephNK** [mxcl/PromiseKit#615]
* PromiseKit version: 4.0
* Xcode version: 8.2.1
* CocoaPods version: 1.1.1

```
import PromiseKit
import Alamofire

func myRequest() -> Promise<[Result<UIImage>]> {
    .......
}
```

When import two modules, 'Result' is ambiguous for type lookup in this context

fix it?

**Comment by mxcl** [comment]
Specify `PromiseKit.Result`.

**Comment by JosephNK** [comment]
```
import PromiseKit
import Alamofire

func requestPromiseForGetPortfolioImages(imageUrls: [String]) -> Promise<[Result<UIImage>]>  {
    let promises = imageUrls.map { (imageUrl) -> Promise<UIImage> in
        return Promise { fulfill, reject in
            FTAPIManager.sharedInstance.requestIgnoringCacheImage(imageUrl, { (image, error) in
                if image != nil {
                    fulfill(image!)
                }else {
                    reject(error!)
                }
            })
        }
    }
    return when(resolved: promises)
}
```

The above code is my sample code.

I think it does not seem to support `PromiseKit.Result`

Please check. and fix it :)

**Comment by mxcl** [comment]
K since you are using the resolved variant of when you have to specify `PromiseKit.Result’. This is your fix.

**Comment by mxcl** [comment]
Specifically: 

```swift
import PromiseKit
import Alamofire

func requestGetAllImages(imageUrls: [String]) -> Promise<[PromiseKit.Result<UIImage>]>  {
    let promises = imageUrls.map { (imageUrl) -> Promise<UIImage> in
        return Promise { fulfill, reject in
            FTAPIManager.sharedInstance.requestIgnoringCacheImage(imageUrl, { (image, error) in
                if image != nil {
                    fulfill(image!)
                }else {
                    reject(error!)
                }
            })
        }
    }
    return when(resolved: promises)
}
```

**Comment by mxcl** [comment]
And here's the same using `wrap`, which is what our documentation recommends:

```swift
import PromiseKit
import Alamofire

func requestGetAllImages(imageUrls: [String]) -> Promise<[Result<UIImage>]>  {
    let promises = imageUrls.map { imageUrl -> Promise<UIImage> in
        PromiseKit.wrap{ FTAPIManager.sharedInstance.requestIgnoringCacheImage(imageUrl, $0) }
    }
    return when(resolved: promises)
}
```

**Comment by JosephNK** [comment]
Thank you for your reply and resolved. 👍

**Comment by mxcl** [comment]
np, and sorry, I hate this sort of thing, but this is how we are meant to do this I believe, so this ambiguity is inevitable.

Let us know if you have any other problems.

**Comment by johndpope** [comment]
if the code is 

public func start() -> Promise<MKMapSnapshot> {
 return PromiseKit.wrap(start)
 }

how to translate this code?
you should comment this in the docs - PromiseKit.wrap 
there's a sea of this usage on github
https://github.com/search?p=2&q=PromiseKit.wrap&ref=opensearch&type=Code


it should be added to readme as breaking change and included as a removed function in code. 
I've wasted a couple of hours on this. 

Cannot convert value of type 'Resolver<_>' to expected argument type '(Error?, User?) -> ()'



<img width="1240" alt="screen shot 2018-02-13 at 3 43 47 pm" src="https://user-images.githubusercontent.com/289994/36172716-be1f68ae-10d4-11e8-9cfa-f6a48acb7fa8.png">

**Comment by johndpope** [comment]
https://gist.github.com/johndpope/26589589d4c38dd47302d4d7ec7c3306

**Comment by mxcl** [comment]
Please open a new ticket at https://github.com/mxcl/PromiseKit.

Sorry for your wasted time, but it is very hard to do this stuff, this was literally months of work and you did *not* have to upgrade to the new major version that was just released, that was your choice.

**Comment by johndpope** [comment]
Sorry to hear about closure  woes. Not to add salt to wounds, but supposedly Flat map is deprecated.... does googles’ promise iOS framework suffer same problems I wonder. 
FYI - projects I’m using are based on Carthage and think the file didn’t lock a specific version. Will look into downgrading. 

It would be nice to include this link in source code / readme with BOLD Breaking changes as there are so many >2500 repos and developers that any help to upgrade the old code to new would go a long way. I’m on train now, will attempt downgrade tomorrow or raise ticket to refactor.

**Comment by mxcl** [comment]
I've added `wrap` as a deprecated function coming in 6.0.1 to be released today. Sorry I overlooked this.

**Comment by mxcl** [comment]
> Flat map is deprecated..

No, it's not.

**Comment by mxcl** [comment]
> It would be nice to include this link in source code / readme with BOLD Breaking changes as there are so many >2500 repos and developers that any help to upgrade the old code to new would go a long way. I’m on train now, will attempt downgrade tomorrow or raise ticket to refactor.

The README includes the migration guide. When migrating it is generally recommended to read the provided migration guide. Thanks.

**Comment by mxcl** [comment]
> FYI - projects I’m using are based on Carthage and think the file didn’t lock a specific version. Will look into downgrading.

Locking with Carthage is possible and recommended by everyone, I suggest you do it in future to avoid the consequences of not doing it: Specifically your entire problem.
