### ISSUE TITLE
Typo in Documentation for Cancellation

### ISSUE THREAD

**Issue by joekamien** [mxcl/PromiseKit#619]
The documentation at http://promisekit.org/docs/ contains the following line of example code:

`alert.cencelButtonIndex = alert.addButton("Cancel")`

This is line contains a typo. The correct var is "cancelButtonIndex", not "c**e**ncelButtonIndex". See: https://developer.apple.com/reference/uikit/uialertview/1620766-cancelbuttonindex

(Also, UIAlertView is deprecated, but that's a separate issue.)

**Comment by zlangley** [comment]
Fixed, thanks.
