### ISSUE TITLE
Wrong binary version number with Carthage

### ISSUE THREAD

**Issue by cikpis** [mxcl/PromiseKit#620]
* PromiseKit version: 4.1.4
* Xcode version: Version 8.2.1 (8C1002)
* Carthage version: github "mxcl/PromiseKit" "4.1.4"

Hi guys, I'm having trouble to use your SDK with Usabilla one because looking into your binary through ```otool -L``` I got ```@rpath/PromiseKit.framework/PromiseKit (compatibility version 0.0.0, current version 0.0.0)```

That is wrong because the value should be at least ```1.0.0```

Any clue why?

I think the problem is because ```Compatibility Version``` and ```Current Library Version``` are not set and they should be set to the same value than the ```Build Version```. 

Looking forward to your answer.

**Comment by mxcl** [comment]
I don’t know where these things are set in Xcode, do you?

**Comment by cikpis** [comment]
In build setting if you look for ```Compatibility Version``` and ```Current Library Version``` you should find them.

**Comment by cikpis** [comment]
After changing the ```Compatibility Version``` and ```Current Library Version``` manually to ```4.1.4```, the Usabilla SDK runs as expected. 

Please fix this issue which should be a critical one and it could be fixed in 1 sec ;)

Keep me updated, cheers!

**Comment by mxcl** [comment]
K, will do that presently.

**Comment by mxcl** [comment]
Pushed that fix and tagged 4.1.5. LMK if there's any further trouble.

**Comment by cikpis** [comment]
Cool! Thanks!
