### ISSUE TITLE
Missing `CFBundleVersion` from Info.plist

### ISSUE THREAD

**Issue by mcfedr** [mxcl/PromiseKit#621]
* PromiseKit version: 4.1.5
* Xcode version: 8
* Carthage version: 0.18.1

As seen here: https://github.com/mxcl/PromiseKit/commit/0918a08be28ff443bd21cf8e70e4c87ee977eb7f#commitcomment-20640590

This commit breaks uploading of the framework to itunes store, as it requires a `CFBundleVersion` to be set for the framework.

**Comment by mxcl** [comment]
PR please. I cannot fix this this weekend.

**Comment by mxcl** [comment]
Tagged 4.1.6
