### ISSUE TITLE
Works great with CocoaPods, crashes with Carthage...

### ISSUE THREAD

**Issue by frizzy75** [mxcl/PromiseKit#625]
* PromiseKit version: 4.1.7
* Xcode version: 8.2.1 (8C1002)
* CocoaPods version: 1.2.0
* Carthage version: 0.18.1

The `request` method below works great in a project built with CocoaPods - but the same method crashes in a project built with Carthage. 

**Expected behavior:**
When the first, chained promise rejects with `Error.userAuthenticationRequired`, execution should jump to the `recover` closure.

**Actual behavior:**
With the CocoaPods-built project, all works great. But with the Carthage-build project, the `recover` closure is never reached, and the app crashes with an `EXC_BAD_ACCESS` error in the PromiseKit method `then<U, V, X>(q: body:)`, i.e. the variant of `then` which allows a 3-part Promise tuple as return value. (Enabling 'zombies' didn't help find the root cause...)

What could explain the difference between a CocoaPods-built project, which works fine, and the Carthage-built project which crashes?

```swift
fileprivate func request<T,U>(requestBuilder: @escaping (AuthData) throws -> URLRequest, jsonDeserializer: @escaping (U) throws -> T) -> Promise<T> {
		
		return Promise<AuthData> {
			// Get credentials
			(fulfill, reject) -> () in
			if let authData = authManager.authData {
				// Use credentials we already have
				fulfill(authData)
			}
			else {
				reject(Error.userAuthenticationRequired)
			}
		}.then {
			// Send request
			(authData) -> Promise<T> in
			let urlRequest = try requestBuilder(authData)
			return self.send(urlRequest: urlRequest, jsonDeserializer: jsonDeserializer)
		}.recover {
			// Recover from expired session token error - fail on other errors
			(error) -> Promise<T> in
			if case Error.userAuthenticationRequired = error {
				return self.authManager.authorize().then {
					(authData) -> Promise<T> in
					let urlRequest = try requestBuilder(authData)
					return self.send(urlRequest: urlRequest, jsonDeserializer: jsonDeserializer)
				}
			}
			else {
				throw error
			}
		}
	}
```

**Comment by mxcl** [comment]
Sounds like a Swift version mismatch, ensure Carthage is building with the same version of Swift that Xcode builds your project with.

**Comment by frizzy75** [comment]
@mxcl Thanks - both Swift versions are 3.0.2. Any other possible differences that might explain this?

**Comment by mxcl** [comment]
Try making Carthage compile it in debug mode?

**Comment by frizzy75** [comment]
Thanks, @mxcl. I've tried `carthage --configuration Debug` and I can step through the PromiseKit code. All works well until the `recover` closure; execution never enters `recover(on: policy: execute)` but inexplicably jumps to `then<U, V, X>(q: body:)`. I'm pulling my hair out :-)

**Comment by mxcl** [comment]
So, to provide more, this is definitely a bug in the Swift compiler, the function lookup table (or whatever) is wrong in the Carthage build or perhaps the Xcode build is using the wrong function.

If we can't figure out a work around then I can only direct you to https://bugs.swift.org

**Comment by frizzy75** [comment]
Thanks, @mxcl. I'll keep trying for a little while longer. 

I'm trying to add Carthage support to an existing framework that supports CocoaPods and depends on PromiseKit - and which uses the default CocoaPods file & project hierarchy. 

After clearing the slate (deleted derived data directories, restart Xcode, etc.), Carthage no longer builds in a test project due to a missing `PromiseKit.modulemap`. So perhaps I was using cached, but out-of-date files yesterday, when Carthage successfully built, but the app crashed?

In any case, I appreciate your help - and **love** PromiseKit.

**Comment by mxcl** [comment]
> After clearing the slate (deleted derived data directories, restart Xcode, etc.), Carthage no longer builds in a test project due to a missing PromiseKit.modulemap. So perhaps I was using cached, but out-of-date files yesterday, when Carthage successfully built, but the test app crashed?

Certainly this sounds suspicious.

**Comment by frizzy75** [comment]
@mxcl I finally got everything to work. I was probably tripping over cached builds of an earlier version of PromiseKit, built with CocoaPods. 

Thanks for the quick responses, and the suggestions, which led me in the right direction. 

Closing this issue.

**Comment by mxcl** [comment]
Glad it worked out. It's sad though that these packaging tools failed to work in this case :/
