### ISSUE TITLE
Promise.then gets called only once

### ISSUE THREAD

**Issue by namuthan** [mxcl/PromiseKit#632]
* PromiseKit version:  4.0.4
* Xcode version: 8.2.1
* CocoaPods version:  pod 'PromiseKit', '~> 4.0.4'

I have the following asynchronous code where the completion block on the first perform function is expected to be called more than once.

<img width="680" alt="screen shot 2017-03-04 at 11 34 03 pm" src="https://cloud.githubusercontent.com/assets/6484468/23585141/18a52ece-0133-11e7-8eb1-f53a2ba88d29.png">

As you can see, the second perform wraps the first one on a promise. 

and example of using this is as follow 
<img width="446" alt="screen shot 2017-03-04 at 11 27 31 pm" src="https://cloud.githubusercontent.com/assets/6484468/23585111/2de06d7c-0132-11e7-9bb9-3fa5cf79086c.png">

the problem is that (then block is called once event if the completion block is called more than once)

I am not sure if this is a bug or something that is not implemented

Thank you for this amazing library.

**Comment by mxcl** [comment]
Works as intended: promises are immutable once resolved and thus cannot be fulfilled more than once and thus a single then handler is guaranteed to only be called once or not at all.
