### ISSUE TITLE
Make it easier to work with different priority queues

### ISSUE THREAD

**Issue by gsabran** [mxcl/PromiseKit#635]
I'm wondering what's the best design to do something like:

```swift
func doFoo() -> Promise<Void> {
  // in thread A
  return somePromise.then(on: DispatchQueue.global(qos: .background)) { x in
    // some processing in the background
  }.then { y in
    // some more processing
  }.thenGoBackToOriginalQueue()
}
```

So that, while I want some parts to happen in the background in anyway, I'm sure the returned promise is returning in the thread it was called from, and that delegate methods are also called in that thread.

I know I can replace `some processing in the background` by 

```swift
return Promise { resolve, reject in
  DispatchQueue.global(qos: .background).async{
    // some processing in the background
    resolve()
  }
}
```

so that the returned promise stays in the thread it was called from, but that's quite verbose.

**Comment by mxcl** [comment]
Promises don’t exist on any thread, but handlers can be directed to any queue/thread. `then`, etc. default to the `main` thread however.

The queue on which a handler executes is entirely up to that handler.

**Comment by gsabran** [comment]
I see. So unless specified then execute in the main thread? Like

```
somePromise.then(on: DispatchQueue.global(qos: .background)) { x in
    ...
  }.then { y in
    // this is is executed in the main thread, correct?
  }
```

**Comment by mxcl** [comment]
Yes

**Comment by gsabran** [comment]
ok great thanks

**Comment by mxcl** [comment]
Is this convenient enough?

**Comment by gsabran** [comment]
It gets verbose when using promises in a background queue since at every step I've to specify to stay in the background, but I don't see a better solution since we can't remove the default being going back to the main thread as it would break a few apps for sure. So that's ok.

I've also had a few times where I'd like the promise to be executed in the thread it's called in. Like usually when you do
```swift
...
someFunction()
...
```

you'd expect `someFunction` to run in the current thread, ie the caller is responsible for choosing the thread, while promises have the opposite behavior where by default the block is dispatched in the main thread and the caller cannot specify which thread to run the promise in, and can only do so for what happens next.

**Comment by gsabran** [comment]
Also I've been surprised that, even when called in the main thread, the block doesn't run synchronously as is the case in javascript. But that just a surprise that comes with platform switch :)

**Comment by mxcl** [comment]
> Also I've been surprised that, even when called in the main thread, the block doesn't run synchronously as is the case in javascript. 

If so, this is in violation of Promise/A+ which was formulated by the JS community. https://promisesaplus.com

All the major promises implementation in JSland conform to this, and it is explicit that what you described does *not* happen.

**Comment by gsabran** [comment]
Sorry about the confusion. I was thinking about the first block, and I didn't write my test correctly. This indeed executes the first block synchronously:

```swift
print(1)
let p: Promise<Void> = Promise { resolve, reject in
  print(2)
  resolve()
}
p.then {
  print(3)
}
print(4)
// prints:
// 1
// 2
// 4
// 3
```
and not the second one as excepted.
