### ISSUE TITLE
Using `when` causes crash on linux.

### ISSUE THREAD

**Issue by euwars** [mxcl/PromiseKit#636]
* PromiseKit version: 4.18

crash error:  `fatal error: init(totalUnitCount:) is not yet implemented: file Foundation/NSProgress.swift, line 37 `

i don't think it needs extra information. but let me know if u need anything.

**Comment by mxcl** [comment]
Swift toolchain version on Linux?

Because this *did* work: https://github.com/mxcl/PromiseKit/issues/591

**Comment by euwars** [comment]
Swift version 3.0.2 (swift-3.0.2-RELEASE)
