### ISSUE TITLE
"Debbugging is hard"

### ISSUE THREAD

**Issue by jonasman** [mxcl/PromiseKit#637]
* PromiseKit version:  PromiseKit (4.0.4) I know it is not the latest
* Xcode version: 8.2.1
* CocoaPods version: 1.2.0

On this topic the docs say 

> add PMKSetDefaultDispatchQueue(zalgo)

 but for me in swift i always need to add
`__PMKSetDefaultDispatchQueue(zalgo)`

**Comment by mxcl** [comment]
In Swift it's `DispatchQueue.default = zalgo`.

**Comment by mxcl** [comment]
Reopening as we should amend the docs.

**Comment by farshadtx** [comment]
@mxcl I think you should consider adding this (or similar method) to testing documentation. specially when there are more than one Async process (in my case, RxSwift hot stream and PromiseKit) chained together.

**Comment by mxcl** [comment]
> testing documentation

I don’t understand what you mean.

> specially when there are more than one Async process (in my case, RxSwift hot stream and PromiseKit) chained together.

Sorry, I don’t know what this would look like.

**Comment by farshadtx** [comment]
I meant testing section

**Comment by mxcl** [comment]
We don’t have a “testing section” of our documentation, but if we did I don’t understand why we would put this there.

**Comment by mxcl** [comment]
PMK 5 adds #file and #line to every then instantiation. Though this only helps so much. There's not a great deal we can do without more explicit support in Xcode itself. So I think we can't do that much until Swift has `await` and well, when that happens we won't need Promises.

**Comment by nikburnt** [comment]
Use of unresolved identifier 'zalgo'
`pod 'PromiseKit', '~> 6.8'`

**Comment by richieWave** [comment]
Yeah, definitely "zalgo" is not a thing in the last PromiseKit. How can I temporary disable dispatch?
