### ISSUE TITLE
PromiseKit 4.1.8 not auto includes subspecs Foundation and UIKit 

### ISSUE THREAD

**Issue by zdiovo** [mxcl/PromiseKit#640]
* PromiseKit version: 4.1.8
* Xcode version: Xcode 8.3 beta4
* CocoaPods version: **1.2.0**

When using PromiseKit 4.1.8, I have found it not auto includes the Foundation and UIKit subspecs .🤣

**Comment by mxcl** [comment]
On the contrary, it does: https://github.com/mxcl/PromiseKit/blob/master/PromiseKit.podspec#L21

**Comment by mxcl** [comment]
What makes you say it doesn't?
