### ISSUE TITLE
Passing through arguments yields Swift compiler error

### ISSUE THREAD

**Issue by Cykey** [mxcl/PromiseKit#641]
* PromiseKit version: 3.5.3
* Xcode version: 8.2.1 Swift 2.3

```swift
createChannel([selectedUser!.userID!]).then { channelId in
     // I need to be able to pass 'channelId' to the next .then {} block below.
     return retrieveMessagesForChat(channelId).then { (channelId, $0) }
}.then { channelId, messages -> Void in
     let controller = ...
     controller.messages = messages
     controller.user = selectedUser!
     controller.chat = JXChatModel()
     controller.chat.id = channelId // <- Needed here.
     self.navigationController?.pushViewController(controller, animated: true)
}
```

I followed the example given on the FAQ page.

However, clang gives the following error:
```swift
Contextual closure type '(AnyObject?) -> AnyPromise' expects 1 argument, but 2 were used in the closure body.
```

This error happens on the following line:
```swift
}.then { channelId, messages -> Void in
````

I am not sure how to fix this. Any help would be appreciated!

Thank you,
David.

**Comment by mxcl** [comment]
Swift gives spurious error messages when errors happen in closures. Chances are the error is actually in the code inside the closure.

Split the code out into its own function:

func containingFunc() {

    func foo(_ channelId: _, _ messages: _) {
        let controller = ...
        controller.messages = messages
        controller.user = selectedUser!
        controller.chat = JXChatModel()
        controller.chat.id = channelId // <- Needed here.
        self.navigationController?.pushViewController(controller, animated: true)
    } 

    createChannel([selectedUser!.userID!]).then { channelId in
         // I need to be able to pass 'channelId' to the next .then {} block below.
         return retrieveMessagesForChat(channelId).then { (channelId, $0) }
    }.then {
        foo($0, $1)
    }
}
