### ISSUE TITLE
catch() Is not giving me my custom NSError subclass

### ISSUE THREAD

**Issue by mdhornet90** [mxcl/PromiseKit#643]
* PromiseKit version: Latest
* Xcode version: Latest

I'm wrapping a call to a networking library in `[AnyPromise promiseWithAdapterBlock:]` to promise-ify my internal API. In the event that the networking library calls my `failure:` block, I build a custom `NSError` subclass and pass it into the adapter (`adapter(nil, customError)`).

Later on, when I `catch` the associated error, I'm getting a runtime exception because I was assuming the error would be my custom subclass and hence calling a method only it possesses. But it appears to be a vanilla `NSError`, and I'm at a loss as to why. 

I could've sworn I did this yesterday successfully, but is it not a guarantee that PromiseKit will bubble up my custom `NSError` subclass in `catch`?

EDIT:
A little more info - my custom `NSError` subclass also has an instance variable pointing to the original underlying `NSError` object.

**Comment by mdhornet90** [comment]
Back to the drawing board, I think. I forgot that this particular call is also wrapped in a `PMKWhen`, so I think something screwy is happening when I try to unbox this error.

**Comment by mxcl** [comment]
Indeed, PMKWhen wraps the error. But we stopped doing that in the Swift version because it is surprising. So probably we should do the same for objc. The wrapper has useful info, but typically that isn't as important.

**Comment by mdhornet90** [comment]
I appreciate the follow up! I realized I could access the underlying error pretty easily, but I wouldn't mind a change to bring it in line with how Swift does it.

Is there any chance I could take a crack at a PR for it? I've really enjoyed using this framework, and I'd love to give back.

**Comment by mxcl** [comment]
PR is welcome but I could not merge until PMK 5, since it changes behavior and could thus break apps at runtime.
