### ISSUE TITLE
Playground can't find PromiseKit module

### ISSUE THREAD

**Issue by gottelicious** [mxcl/PromiseKit#644]
* PromiseKit version: 4.1.8
* Xcode version: 8.2.1 Swift 3.0.2

I have just cloned the project and opened it in xcode. I open the playground and I get the error "No such module 'PromiseKit'"

**Comment by mxcl** [comment]
Ensure you have built PromiseKit for iOS target first.

**Comment by lususvir** [comment]
I am having this same issue, what do you mean "built PromiseKit for iOS first"? I cloned the repo and opened the playground file.

**Comment by mxcl** [comment]
You have to open the project and build the framework for an iOS simulator target first.

**Comment by mxcl** [comment]
Latest commit change the playground execution platform to `macOS` also, since apparently a clean clone will default to building to macOS (provided no iOS devices are plugged in).

**Comment by lususvir** [comment]
So what do I do about it. I selected the iphone simulator from the dropdown, what more do I need to do?
<img width="327" alt="screen shot 2017-04-29 at 1 16 35 pm" src="https://cloud.githubusercontent.com/assets/8564043/25558562/2c1d7f5c-2cde-11e7-9e24-3dc3bc462ec8.png">

**Comment by mxcl** [comment]
You have to build the framework.

**Comment by lususvir** [comment]
My problem was I was on Swift 3.1 instead of 3.1.1. Updating Xcode fixed it.
