### ISSUE TITLE
Feature Request: Split AnyPromise API from Promise<T> API

### ISSUE THREAD

**Issue by jonbrooks** [mxcl/PromiseKit#645]
* PromiseKit version: 4.1.7
* Xcode version: 8.2.1

XCode frequently chooses `AnyPromise` signatures when trying to infer the type of PromiseKit methods.  For those of us exclusively using Swift and strongly-typed promises, it might be a better experience if we could selectively pull in PromiseKit's `Promise<T>` APIs without the `AnyPromise` APIs.

I don't know whether PromiseKit is factored in a way that this would be easy or not.  I also don't know how much this would improve things, since XCode would still have to choose between the various `then` signatures.  It just seemed possible that XCode might do a better job without `AnyPromise` confusing it.

**Comment by mxcl** [comment]
It isn't choosing that, it's just a bug in the compile errors you are getting.

I have in fact tried to remove `AnyPromise` to see if it helps, and it just gives an equally useless compile error.

**Comment by jonbrooks** [comment]
Ah well, too bad.  Nice to know that you already tried that.

What you say matches my experience.  At least half the time its my fault.  I was just hoping the latter case - where I have to be explicit in my closure's return - would have improved.

**Comment by mxcl** [comment]
In our experimental 5.0 branch I am aggressively trying to improve this sort of situation. So far I've met limited success.

**Comment by mxcl** [comment]
Though: with 5.x the diagnostic never mentions AnyPromise anymore. So it is improved in that respect.
