### ISSUE TITLE
AnyPromise issue

### ISSUE THREAD

**Issue by Phnx777** [mxcl/PromiseKit#647]
* PromiseKit version: 4.1.7
* Xcode version: Version 8.3 (8E162)
* CocoaPods version: 1.2.1

issue :
<img width="1126" alt="2017-04-05 16 56 29" src="https://cloud.githubusercontent.com/assets/10783517/24709215/d87b483a-1a21-11e7-82a9-f740e5467258.png">
 Cannot subclass a class with objc_subclassing_restricted attribute.
Hello, I got this issue after Xcode's latest update recently.
If I run or build the app, it's ok. I'm trying to archive the app and each time I get issue. 
(objective-c project)

**Comment by mxcl** [comment]
Sorry, is this an error? Can you mark up your question so the error message is explicitly marked?

**Comment by Phnx777** [comment]
Yes, this is an error: Cannot subclass a class with objc_subclassing_restricted attribute.
I tried to find solution. It means problem inheritance objective-c and swift. How can I resolve this issue in my obj-c project?

**Comment by mxcl** [comment]
No, clue. I'll have to try archiving one of my own.

**Comment by Phnx777** [comment]
how is your debugging?

**Comment by mxcl** [comment]
I am in the process for starting my own company, so this will have to wait until I have some time for PromiseKit. Or you can pay me.

**Comment by mxcl** [comment]
Cannot reproduce. One of my apps with PMK 4 archives fine.

**Comment by mxcl** [comment]
I have since archived 4 apps all with PMK, so I don’t think this is a general issue.

**Comment by mxcl** [comment]
Closing due to lack of responses.
