### ISSUE TITLE
Promise's "execute" argument label

### ISSUE THREAD

**Issue by danhalliday** [mxcl/PromiseKit#648]
* PromiseKit version: 4.1.7
* Xcode version: 8.3.1

A very small thing: is there any particular reasoning for the `execute` external argument label on `Promise.swift`?

    public func then<U>(on q: DispatchQueue = .default, execute body: @escaping (T) throws -> U) -> Promise<U> {

I have a lot of code where I feel the need to break out handlers into methods as they are a little long to do inline, and I end up with code like this, which could be a little more succinct without all the labels:

    store.save(user: user).then(execute: saveDidSucceed).catch(execute: saveDidFail).always(execute: saveDidFinish)

I don't think `execute` adds anything, and could just as well be `_`. Any thoughts? Many thanks to the contributors, PromiseKit is super useful.

**Comment by mxcl** [comment]
We followed the same naming scheme as `DispatchQueue`: https://developer.apple.com/reference/dispatch/dispatchqueue/2016098-async

I have renamed this label for `catch` and `always` in PMK 5.x

**Comment by danhalliday** [comment]
Many thanks for your carefully considered reply. For me, I'd value the brevity more, but I can understand the argument. I'll take a closer look at the v5 branch, some interesting changes there!
