### ISSUE TITLE
Return empty Promise for next ".then" or ".catch" closures

### ISSUE THREAD

**Issue by pffan91** [mxcl/PromiseKit#650]
* PromiseKit version: PromiseKit (4.1.7)
* Xcode version: Xcode 8.3.1
* CocoaPods version: PromiseKit (4.1.7)

Hello! I think this is noob question. I am straining to using PromiseKit. So my question is how I can return empty Promise<T> object? For example my current worked code is

            EventsWorker.getAllEvents().then { events in
                self.events = events
            }.then {
                fulfill()
            }.catch { error in
                reject(error)
            }

I want this to modify as:

           EventsWorker.getAllEvents().then { events in
                self.events = events
                fulfill()
                // I must return Promise<T> here, right?
            }.catch { error in
                reject(error)
            }

Thank you in advance!

**Comment by mxcl** [comment]
>  // I must return Promise<T> here, right?

No, you can return `Void`. I presume you are getting an error, although you didn't say. If so specify the return type:

```swift
  EventsWorker.getAllEvents().then { events -> Void in
```

**Comment by pffan91** [comment]
Thank you @mxcl , that's what I need!

**Comment by mxcl** [comment]
np, this is an unfortunately common problem, and there's nothing we can do, it's up to the Swift team to fix it.
