### ISSUE TITLE
Document concurrency behavior for when methods.

### ISSUE THREAD

**Issue by yood** [mxcl/PromiseKit#652]
I'm always confused as to whether the promises passed to `when` will be executed serially or concurrently, and if concurrent, how many at a time?

Could you clarify this in the documentation?

* PromiseKit version: 4.1.7

**Comment by mxcl** [comment]
Promises don't decide, that is entirely up to the tasks they wrap.

So the answer is: probably concurrently, but it depends!

**Comment by mxcl** [comment]
Well I guess the only way they would be serially is if the tasks that the promises represent knew about each other. Anyway, the point is that promises have nothing whatsoever to do with concurrency. I'm pretty sure that statement is in the docs somewhere.

**Comment by yood** [comment]
You're right, I was confused about promises. They start their work when constructed, so every promise is either executing/pending or resolved.

I'll keep using `when(fulfilled:concurrently:)`, though it's a bit awkward with the generator.

**Comment by mxcl** [comment]
There is ways to avoid that variant of when. Ping me tomorrow and I'll post them. They aren't great either though.

**Comment by yood** [comment]
Hey, what's that variant of `when` you were talking about?

**Comment by mxcl** [comment]
Not `when`, but you can do something like this:

```swift
func bar() -> Promise<Void> {
	func foo() -> Promise<Void> {
		return foo().then {
			if shouldContinue() {
				return foo()
			} else {
				return Promise(value: Void())
			}
		}
	}

	return foo()
}

bar().then {
	
}
```

**Comment by yood** [comment]
Haha thanks, but I'll stick to the generator. This is too clever for me.
