### ISSUE TITLE
How to get simple `.then {}` syntax

### ISSUE THREAD

**Issue by ded** [mxcl/PromiseKit#653]
I've been using Promises beyond network calls and other delayed actions primarily because I like the flow of using promises... however I also use them for simple `ok | cancel` dialog style prompts in our application; using `.then` for the *ok*, and `.catch` for the *cancel* action.

With that in mind, how do I get around the ugly syntax of this:

```
ok("Are you sure?").then { (_) -> Void in
  // do something
}
.catch { (_) in
  // do something else
}
```

to something easier to read like this:

```
ok("Are you sure?").then {
  // do something
}
.catch {
  // do something else
}
```

The `ok()` function is returning a promise from a `.pending` tuple.

```@discardableResult func ok() -> Promise<Void> {
  let (promise, fulfill, reject) = Promise<Void>.pending()
  self.handler = (promise, fulfill, reject)
  return promise
}
```

**Comment by zlangley** [comment]
This should basically work; if `ok` returns `Promise<Void>`, you should be able to use the `then` syntax you want. You can also omit the parentheses around `_`, leaving you with:

```swift
ok("Are you sure?").then {
  // do something
}.catch { _ in
  // do something else
}
```

**Comment by ded** [comment]
in full, `ok` looks like this:

```
@discardableResult func ok() -> Promise<Void> {
    let (promise, fulfill, reject) = Promise<Void>.pending()
    self.handler = (promise, fulfill, reject)
    return promise
  }
```

so i'm not sure why it's not letting me do this basic syntax...

**Comment by zlangley** [comment]
The following compiles for me:

```swift
class Foo {
    var handler: Promise<Void>.PendingTuple?

    @discardableResult func ok() -> Promise<Void> {
        let (promise, fulfill, reject) = Promise<Void>.pending()
        self.handler = (promise, fulfill, reject)
        return promise
    }

    func foo() {
        ok().then {
            // do something
        }.catch { _ in
            // do something else
        }
    }
}
```

What's the error you're getting?

**Comment by nobre84** [comment]
If your `// do something` has more then a single line, swift compiler is not smart enough to infer the closure return type, thus you need `_ -> Void in`. That's unfortunate.

**Comment by mxcl** [comment]
I clarified the documentation on this topic: https://github.com/mxcl/PromiseKit/blob/master/Documentation/Troubleshooting.md
