### ISSUE TITLE
Update docs to refer to URLSession instead of NSURLSession

### ISSUE THREAD

**Issue by vpdn** [mxcl/PromiseKit#655]
* PromiseKit version: 4
* Xcode version: 8.3

![image](https://cloud.githubusercontent.com/assets/387312/25393429/10170192-29a1-11e7-8be1-103e595ee852.png)

In the introductory sample, the docs still refer to "NSURLSession" which has been renamed in Swift 3 to URLSession.

**Comment by mxcl** [comment]
Specifically, where?

**Comment by zlangley** [comment]
Seems to be in a bunch of files. Just updated, thanks @vpdn.

**Comment by mxcl** [comment]
Sorry, I meant, just http://promisekit.org, or including README, sources, headers, etc. But if it was just the website then we are done. Thanks @zlangley
