### ISSUE TITLE
Linker error, when archiving project with Xcode 8.3.2

### ISSUE THREAD

**Issue by petegerhat** [mxcl/PromiseKit#660]
* PromiseKit version: 
3.5.1

* Xcode version: 
8.3.2

* CocoaPods version:
1.0.1

After updating to Xcode 8.3.2 from Xcode 8.0 I started seeing this Linker error, when **Archiving** my project:

[![Linker error][1]][1]

However, the project compiles still **Runs** with **Debug** configuration correctly.

That makes me think that the problem might have something to do with my headers configuration (Build Settings -> Other Linker Flags).

I am using PromiseKit 3.5.1.

Debug headers:

[![Headers for Release][2]][2]

Release headers:

[![Headers for debug][3]][3]

  [1]: https://i.stack.imgur.com/c72JX.png
  [2]: https://i.stack.imgur.com/Dp6EQ.png
  [3]: https://i.stack.imgur.com/odPxb.png

**Comment by mxcl** [comment]
How are you using PromiseKit 3 with Xcode 8.3? PromiseKit 3 uses Swift 2. Xcode 8.3 doesn't support Swift 2.

**Comment by petegerhat** [comment]
That's something I realized, but CocoaPods will not install higher version of PromiseKit, perhaps [PromiseKit-AFNetworking](https://github.com/csotiriou/AFNetworking-PromiseKit) requires PromiseKit 3 ?

Here is my pod configuration

```
  pod 'NUI',:git => 'https://github.com/peantunes/nui.git'
  pod 'MBProgressHUD'
  pod 'CocoaLumberjack'
  pod 'AFNetworking'
  pod 'PromiseKit'
  pod 'PromiseKit-AFNetworking'
```

**Comment by petegerhat** [comment]
As mentioned in previous post, my solution consisted of removing 'PromiseKit-AFNetworking' (requires PromiseKit) 3 from list of pods.

**Comment by mxcl** [comment]
Yeah, I dunno about `PromiseKit-AFNetworking` it is not maintained by us. Probably it will work without much modification and probably isn't more than a couple of files you can drop into your project.

**Comment by nikhilwhizdhavale** [comment]
But I get the following error when using xcode 8.3. 
I get complier error Module compiled with Swift 3.0.2 cannot be imported in Swift 3.1: .../Carthage/Build/iOS/PromiseKit.framework/Modules/PromiseKit.swiftmodule/x86_64.swiftmodule
Do I need to use older version of Xcode

**Comment by mxcl** [comment]
@nikhilwhizdhavale like I was saying in your ticket, you need to rebuild all your Carthage frameworks because they were built with Xcode 8.2 and you are now using Xcode 8.3. This is how Carthage works, for further information please see their documentation.

**Comment by mxcl** [comment]
Dupes #669

**Comment by girees** [comment]
I am also facing same problem.could you please any solution to achieve this one.Thanks in advance

**Comment by nikhilwhizdhavale** [comment]
If you have multiple Xcodes in your mac you might face the problem. Check the Xcode build version

**Comment by girees** [comment]
I deleted my previous Xcodes but still i am facing same problem. I am using AFNetworking-Promise kit frame work for web services calling.

**Comment by nikhilwhizdhavale** [comment]
use the command  xcodebuild -version

**Comment by mxcl** [comment]
@girees take @nikhilwhizdhavale's advice carefully as his problem is unrelated to this ticket.
