### ISSUE TITLE
No way to get info about what promise step actually failed

### ISSUE THREAD

**Issue by iThinker** [mxcl/PromiseKit#662]
* PromiseKit version: 4.2.0
* Xcode version: 8.3.2
* CocoaPods version: 1.2.1

When dealing with promises I found out that it is literally impossible to determine the original promise that caused error in ```catch``` block. ```DispatchQueue.default = zalgo``` does not do anything. You can see my stack trace on attached screenshot. It has 0 information from where resolution was enqueued. Setting breakpoint in ```State catch``` helps a little, but not much. It shows the code that produced error. But in my case it is wrapped asynchronous call and xcode does not show where information was enqueued from. All this together makes debugging very hard. Do you have any ideas what can be done to improve it? Thanks in advance.

![screen shot 2017-05-12 at 16 09 47](https://cloud.githubusercontent.com/assets/1224861/26015129/95ce7722-372d-11e7-893f-2370c30d5e18.png)

**Comment by mxcl** [comment]
Promises are slightly worse than general asynchronous programming for this, but this is just the nature of asynchronous programming. Sorry. There isn't much to do except add a lot of logging.

**Comment by mxcl** [comment]
As a debugging method you could make the error include `#file` and `#line` implicitly which would help a lot. If you control the errors.

if you don't control the errors I'm not sure there's much that can be done to help. You just have to add a lot of breakpoints and logging. Sorry, but this is just the nature of it, at least at this layer of our understanding.

**Comment by iThinker** [comment]
I see. That's unfortunate. Errors can may include additional information, but it is hard to include same information as request origin would provide.
How do you think, would promises allow to record chain? I mean, if I would add ```#file``` and ```#line``` information when I create any promise, would it be possible to pass this information to each next attached promise?

**Comment by mxcl** [comment]
Every handler would need to record `#file` and `#line` and then this would have to be recorded with the error objects the promise stores.

**Comment by iThinker** [comment]
Thank you for answers. Will try to do it.

**Comment by mxcl** [comment]
Thinking about it, we could probably add this as a feature to PMK 5.

**Comment by mxcl** [comment]
PMK 5 adds #file and #line to every then.

**Comment by iThinker** [comment]
Awesome! Thank you!
