### ISSUE TITLE
Polling for a async task and then waiting for either 1 success or all response rejected

### ISSUE THREAD

**Issue by balraj-hike** [mxcl/PromiseKit#663]
* PromiseKit version: 4.0
* Xcode version: 8.3.2
Hey thanks for such an awesome job. I have recently started using PromiseKit but i have already started seeing great benefits of this. 
Actually i am creating a polling HTTP request which in returns gives "completed" or "notCompleted"
I have to keep making HTTP calls after every 1 secs for a duration of 5 sec

What i need to achieve is if any 1 call gives me completed status i will return fulfilled("completed"). But if all of my request gives me a response of "notCompleted" I need to return reject("notCompleted")

```
return Promise<T> { fulfilled, reject
let timer1 =  Timer.scheduledTimer(withTimeInterval: TimeInterval(1), repeats: true) { timer in
    pArr.append(Promise<T> { f, r in
        
        doSomeAsyncTask { T in
            if success {
                f(T)
                fulfilled(T)
                timer.invalidate()
            } else {
                 r(ErrorNotCompleted)
            }
        }
        
        // timeout option
        _ = after(interval: TimeInterval(15)).then(execute: { () -> Void in
            reject(timeoutForConfirmation)
        })
    })
    }


Timer.scheduledTimer(withTimeInterval: TimeInterval(5), repeats: false) { timer in
    timer1.invalidate()
    timer.invalidate()
    when(resolved: pArr).then { results in
        let count = results.filter({ result -> Bool in
             return result.boolValue
        }).count
        
        if count == 0 {
            // TODO: then reject here
            reject(ErrorNotCompleted)
        }
        
        }.catch { error in
            print(error)
    }
}
    
}

timer1.fire()
```

How can i achieve this? Is there a better way to write the above code in PromiseKit.

**Comment by mxcl** [comment]
```
Promise { fulfill, reject in
    var x = 0
    func attempt() {
        doSomeAsyncTask { success, error in
            if success {
                fulfill()
            } else if x < 5 {
                x += 1
                after(interval: 1).then {
                    attempt()
                }
            } else {
                reject(error)
            }
        }
    }
    attempt()
}
```

**Comment by balraj-hike** [comment]
@mxcl - Just a query in you code the next call is made when the response of the previous calls come but actually i need to make the next call irrespective of previous response or not. And how can i make this thread safe as x can be called by multiple response thread?

**Comment by mxcl** [comment]
> And how can i make this thread safe as x can be called by multiple response thread? 

Promises are implicitly thread-safe. See the FAQ.

> Just a query in your code the next call is made when the response of the previous calls come but actually i need to make the next call irrespective of previous response or not.

I'm finding it very difficult to understand what you want. This is my best attempt, if this isn't correct maybe you could try to explain your needs again:

```swift
return Promise { fulfill, reject in

    success = false
    x = 0

    func go() {
        x += 1
        asyncTask {
            if $0 { success = true }
        }
        after(interval: 1) {

            if x < 5 {
                go()
            } else if success {
                fulfill()
            } else {
                reject()
            }
        }
    }
    
    go()
}
```

**Comment by balraj-hike** [comment]
Hey @mxcl thanks for your comment and i am sorry if I am not able to explain this properly. Let me try explaining question again:- 

The above code that you have posted do take care about calling async func after every 1sec irrespective of whether the previous request has been answered or not. This is 1st requirement.

The second point to take care is: If any of the existing request which has been made gives a response of success. I need to stop all the recursive callbacks and send back Fulfilled with the result.

The third point is: After making all the calls over a duration of 5 secs. If all the responses comes back as failure then i need to send back reject with an error in it.

In the above code success is checked immediately after x == 5. Due to this we are not waiting for all the responses to comeback and then check if all responses are failure. This will satisfy 3rd point.

Also on success of even a single asyncoperation I need to  stop all the recursive callbacks and send back Fulfilled. This will satisfy 2nd point.

**Comment by mxcl** [comment]
```swift
return Promise { fulfill, reject in

    enum State {
        case polling(Int)
        case finished(PromiseKit.Result<T>)
    }
    var state = State.polling(0)

    func go() {
        switch state {
        case .polling(let attempts) where attempts < 5:
            asyncTask { success, error in
                if success {
                    state = .finished(.fulfilled(success))
                } else if attempts == 4 {
                    state = .finished(.rejected(error))
                } else {
                    state = .polling(attempts + 1)
                }
                go()
            }
        case .finished(.rejected(let error)):
            reject(error)
        case .finished(.fulfilled(let success)):
            fulfill(success)
        }
    }
    
    go()
}
```
