### ISSUE TITLE
Merge two promises together and receive multiple thens

### ISSUE THREAD

**Issue by startupthekid** [mxcl/PromiseKit#665]
* PromiseKit version: 4.2.0
* Xcode version: 8.3

I'm looking for a function that would read something like:

```swift 
merge(promise1, promise2).then { value in 

}
```

where the function signature would be `func merge<T>(promises: [Promise<T>]) -> Promise<T>`.

Is that at all possible using Promises?

**Comment by zlangley** [comment]
What do you expect `value` to be in that example? There's `when` which would give you an array of the promise values once they all resolve and `race` which would give you the value of the first promise to resolve. See http://promisekit.org/docs/handbook/Functions.html.

Or are you looking for something different?

**Comment by startupthekid** [comment]
I would expect `then` to be called multiple times with `value` being of type `T` each time. The behavior I'm looking for is sort of a combination of race and when. Given a list of promises, as soon as each one resolves, send that value through the chain until they're all resolved.

So if I have two promises:

```swift
let promise1 = Promise(value: 1)
let promise2 = fetchNumberFromServer(2) // some async operation that resolves to an `Int` but not immediately
merge(promise1, promise2).then { value in 
    print(value)
}
```

In this example, the output would be `1` and then `2` in succession as each one resolves. It's similar in behavior to ReactiveSwift's `merge` operator.

**Comment by startupthekid** [comment]
A more real example might be:

```swift
let promise1 = fetchFromCoreData()
let promise2 = fetchFromNetwork()
merge(promise1, promise2).then {}
```
where one operation returns much quicker than the other but the results from both are still valid. It's like `race` but where every promise gets to finish.

**Comment by zlangley** [comment]
There's nothing that ships with PromiseKit that provides this functionality. You can store your function in a variable and pass that in to each then. Or use when.

let handle: (Type -> Void) = { val in ... }
promise1.then(handle)
promise2.then(handle)

Or

when(promise1, promise2).then { $0.forEach(handle) }

You can make your own function for this, but it's probably not common enough to belong in the library.

**Comment by startupthekid** [comment]
I think it might go against the core nature of Promises since really what I need is more ReactiveSwift-esque where I can resolve things multiple times in a row.

**Comment by startupthekid** [comment]
I'll go ahead and close this, thanks!

**Comment by joezhengyihe** [comment]
Somehow I end up also requires this feature.

**Comment by mxcl** [comment]
We have this feature:

```swift
let p1: Promise<[T]>
let p2: Promise<[U]> = p1.map { t in
    return u
}
```

I recommend reading the docs to find out about features.
