### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by WhatIsLionKing** [mxcl/PromiseKit#667]
Please help me，object-c file use swift ，how can I pass validation？
error message：
https://i.stack.imgur.com/1qvDt.png

**Comment by mxcl** [comment]
You don't want that junk in your `Podfile`. Remove it.

What is `FitShop-Swift.h` for? Usually it would be a bridging header for your ObjC code to your Swift code in your project. Is that what it is? Why is it there?

**Comment by mxcl** [comment]
Closing due to lack of response.
