### ISSUE TITLE
promise kit version

### ISSUE THREAD

**Issue by nikhilwhizdhavale** [mxcl/PromiseKit#668]
* PromiseKit version: 4.2.2
* Xcode version: Xcode 8.3
* Carthage version:0.17.2

I get complier error  Module compiled with Swift 3.0.2 cannot be imported in Swift 3.1: .../Carthage/Build/iOS/PromiseKit.framework/Modules/PromiseKit.swiftmodule/x86_64.swiftmodule
Do I need to use older version of Xcode

**Comment by mxcl** [comment]
Do a clean. You have to clean whenever you upgrade with all swift, not just promise kit.

**Comment by nikhilwhizdhavale** [comment]
Actually promise kit is used in one of the library in signal. When I open the project in Xcode 8.2 it works but in Xcode 8.3 it doesnt work. I did clean build etc.... What am I missing ?

**Comment by mxcl** [comment]
The compiler message is very clear. Something is compiled with swift 3.0 (Xcode 8.2) and something is compiled with Swift 3.1 (Xcode 8.3). When liked these things are not compatible.

Clean is the solution. Try a more thorough clean.

**Comment by mxcl** [comment]
I see you are using Carthage. Do a Carthage update

For more information see the Carthage documentation.

**Comment by nikhilwhizdhavale** [comment]
I might do that but in their doc it mentions I should not do that https://github.com/WhisperSystems/Signal-iOS/blob/master/BUILDING.md

**Comment by nikhilwhizdhavale** [comment]
For now I am using Xcode 8.2 to solve the problem.

**Comment by nikhilwhizdhavale** [comment]
Even If I take a sample project in Xcode 8.3 and try what you want to try I get same. Error it would be great if you could build it in Xcode 8.3

**Comment by nathanhosselton** [comment]
`carthage build` should take care of this, I would think. It uses xcodebuild, so ensure you've [set yours to Xcode 8.3](https://stackoverflow.com/questions/7016307/which-version-of-xcode-does-xcodebuild-use) then run `carthage build` again.

**Comment by nikhilwhizdhavale** [comment]
The problem was solved by checking the Xcode build version. It was lower to Xcode 8.2.1

**Comment by mxcl** [comment]
Learn your tooling.
