### ISSUE TITLE
Can't archive with Xcode 8.2.1 and PromiseKit 3.5.3

### ISSUE THREAD

**Issue by danielnakamashi** [mxcl/PromiseKit#669]
* PromiseKit version: 3.5.3
* Xcode version: 8.2.1
* CocoaPods version: 1.2.1

I created a fresh new Single Page Application and just added PromiseKit pod but I can't archive.
<img width="759" alt="screen shot 2017-05-26 at 22 33 39" src="https://cloud.githubusercontent.com/assets/908467/26516886/4a2e1cb8-4264-11e7-8266-89d090547636.png">
<img width="795" alt="screen shot 2017-05-26 at 22 36 57" src="https://cloud.githubusercontent.com/assets/908467/26516888/55a85694-4264-11e7-82a4-ce2569f80158.png">

**Comment by mxcl** [comment]
Dupe

**Comment by mxcl** [comment]
I closed #669 in favor of this one.

**Comment by mxcl** [comment]
I would have fixed this by now if I was provided with a test project. As it stands fixing it is otherwise a lot of work. And I already have a lot of work.

**Comment by danielnakamashi** [comment]
Thanks a lot for your attention. I updated my project to Swift 3 and it worked perfectly.

**Comment by mxcl** [comment]
At this point I think this is too old to be worth fixing.
