### ISSUE TITLE
How to avoid long compilation time

### ISSUE THREAD

**Issue by QuentinArnault** [mxcl/PromiseKit#671]
* PromiseKit version: 
* Xcode version: 8.3.2

Hi,

I love to use PromiseKit but compilation times can be very long as soon as you chain 4 then in a method. Have you any tricks in order to avoid this compilation extra times?

Regards,
Quentin

**Comment by mxcl** [comment]
I've not personally noticed this.

**Comment by nathanhosselton** [comment]
I've also not seen this. Can you provide more detail? An example would be even better.

**Comment by mxcl** [comment]
Like, a test project that proves it would be good.

**Comment by QuentinArnault** [comment]
I guess this is not directly a PromiseKit. Compilation times go exponential if you chain generic functions that returns Promises.

With this function
```func genericPromise<T>(_ value: T) -> Promise<T> {
    return Promise { fulfill, _ in
        DispatchQueue.main.async {
            fulfill(value)
        }
    }
}```

I wrote 5 promises chains with 1, 2, 3, 4, 5 successive calls.

```func testWith1GenericFunctions() {
    _ = genericPromise("a string").then {
        print($0)
    }
}

func testWith2GenericFunctions() {
    _ = genericPromise("a string").then {
        return genericPromise($0)
        }.then {
            print($0)
    }
}

func testWith3GenericFunctions() {
    _ = genericPromise("a string").then {
        return genericPromise($0)
        }.then {
            return genericPromise($0)
        }.then {
            print($0)
    }
}

func testWith4GenericFunctions() {
    _ = genericPromise("a string").then {
        return genericPromise($0)
        }.then {
            return genericPromise($0)
        }.then {
            return genericPromise($0)
        }.then {
            print($0)
    }
}

func testWith5GenericFunctions() {
    _ = genericPromise("a string").then {
        return genericPromise($0)
        }.then {
            return genericPromise($0)
        }.then {
            return genericPromise($0)
        }.then {
            return genericPromise($0)
        }.then {
            print($0)
    }
}
```

Compilation times are:
- testWith1GenericFunctions: 29 ms
- testWith2GenericFunctions: 7 ms
- testWith3GenericFunctions: 50 ms
- testWith4GenericFunctions: 450 ms
- testWith5GenericFunctions: 3276 ms

So I think that there is no bugs in PromiseKit, I just would like to have advice on how to optimise this situations with a readable solution.

**Comment by mxcl** [comment]
Possibly if you specify the return types of the closures it helps?

**Comment by QuentinArnault** [comment]
Indeed, with this function
```

func testWith5GenericFunctionsWithReturnTypes() {
    _ = genericPromise("a string").then { value -> Promise<String> in
        return genericPromise(value)
        }.then { value -> Promise<String> in
            return genericPromise(value)
        }.then { value -> Promise<String> in
            return genericPromise(value)
        }.then { value -> Promise<String> in
            return genericPromise(value)
        }.then { value -> Void in
            print(value)
    }
}```

Compilation time goes down from 3240ms to 21ms.

Thanks.

**Comment by mxcl** [comment]
Interesting, thanks for bringing this to our attention.

**Comment by mxcl** [comment]
If you will, please report this to http://bugs.swift.org

I cannot, it's quite possible that people at Apple will not listen to me anymore.

**Comment by QuentinArnault** [comment]
I'll try with swift 4 if the problem is still present. But maybe it is unavoidable, genericity has a price.

**Comment by mxcl** [comment]
Obviously I'm not the expert, but my layman's observation is this looks like an O(n) situation. Linear chain.

**Comment by mxcl** [comment]
I find Swift 4 much improves this.
