### ISSUE TITLE
'when ' function's use.

### ISSUE THREAD

**Issue by hengchengfei** [mxcl/PromiseKit#672]
<img width="881" alt="screen shot 2017-06-05 at 4 53 13 pm" src="https://cloud.githubusercontent.com/assets/3182964/26777359/78fd4fa2-4a0f-11e7-8959-33d38911b162.png">

if param is not array,compile error.
but if array,comiple OK.

thank you.

**Comment by QuentinArnault** [comment]
Actually this a normal behavior. There is no `when` signature which allow a uniq `Promise` (seen `when.swift` file.

Instead, you can use directly your `imagePromise` variable.

**Comment by hengchengfei** [comment]
@QuentinArnault thank you.
 I updated the code,the `imagePromise` is changed

**Comment by mxcl** [comment]
Swift compiler bug. Wait for Swift 4.
