### ISSUE TITLE
Is there a way to do an inline `defer` to avoid zalgo?

### ISSUE THREAD

**Issue by mxcl** [mxcl/PromiseKit#676]
The ideal way to avoid zalgo is like so (pseudocode):

```swift
var executionContextDone = false
defer {
    executionContextDone = true
}
foo.then(when: executionContextDone) {
    //…
}
```

Is there a way we can do this? The defer *must* be in the context of the function that calls `then`. I was wondering about `autoclosure`. Worth a look.

**Comment by FilipZawada** [comment]
So what you're saying is that the only solution is to require user for extra line with `defer { }`

Like this?
```swift
func test() {
    defer { foo.proceed() }
    foo.deferred.then() {
        ...
    }
    ...
}
```

or equivalent without defer:
```swift
func test() {
    foo.deferred.then() {
        ...
    }
    ...
    foo.proceed()
}
```

**Comment by mxcl** [comment]
Well, it's the only fully-proper solution. There are other ways to do it though, like the ones we already do.

I don't think we can do this, but if we could it would be perfect.

**Comment by mxcl** [comment]
Not possible.
