### ISSUE TITLE
Add NSUserCancelledError to built-in list of cancelled error identifiers?

### ISSUE THREAD

**Issue by nolanw** [mxcl/PromiseKit#680]
* PromiseKit version: 4.2.2
* Xcode version: 8.3.3 (8E3004b)

Hello! I noticed that NSUserCancelledError (of the NSCocoaErrorDomain) is not included in the default list of errors deemed "cancelled". Seems like a natural fit, so I propose including it.

I did see the `NSError.registerCancelledErrorDomain(_:code:)` extension method and am using it, so this is not at all an urgent issue. And if NSUserCancelledError is intentionally left out, that's ok too!

I'm happy to prepare a PR if we decide to include NSUserCancelledError in the list by default.

**Comment by mxcl** [comment]
Sounds sensible to me.

PR welcome. If you don't get to it, I'll do it by the next release. But it should be an easy enough PR and if you fancy it, we'd love to have it.

**Comment by CedricSoubrie** [comment]
Is this issue now handled in `PromiseKit` ?

**Comment by mxcl** [comment]
As the trail above shows: this was merged.

**Comment by CedricSoubrie** [comment]
Thanks for your quick answer !
I just get why it wasn't working in my case : I'm using "On Demand resources". The error I receive is in `OnDemandResourcesErrorDomain` and not in `NSCocoaErrorDomain`
I manage to add a fix in my code by using :
`if error.isCancelled || (error as NSError).code == NSUserCancelledError { }`

**Comment by mxcl** [comment]
This isn’t a safe fix. The integer code for `NSUserCancelledError` will overlap with many other domains.

**Comment by CedricSoubrie** [comment]
Yeap. The other solution would be to add `OnDemandResourcesErrorDomain` in the pair list.
