### ISSUE TITLE
fulfill block not being executed

### ISSUE THREAD

**Issue by skk2142** [mxcl/PromiseKit#683]
* PromiseKit version:  "~> 4.0"
* Xcode version: 8.3.3

I'm using PromiseKit for the first time. I construct a promise that wraps a firebase storage call. The promise executes but the then block is not being executed. When I add breakpoints, the fulfill block is being called i.e the breakpoint is hit when the firebase call completion block is being executed. However, the function in the then block doesn't execute. So, I don't see any print statement as expected. 

```    
func uploadImageToFirebaseStorage(data: Data) -> Promise<StorageMetadata?> {
        return Promise { fulfill, reject in
            let imageName = NSUUID().uuidString
            let storageRef = Firebase.Storage.storage().reference().child("order_images").child(imageName)
            storageRef.putData(data, metadata: nil, completion: { (metadata, error) in
                if let error = error {
                    reject(error)
                } else {
                    fulfill(metadata)
                }
            })
        }
    }
```
I'm using the promise here. I don't see any printing in the console. However, the promise is being fulfilled. 
```
    func uploadImagesToFirebaseStorage(images: [UIImage]) {
        if let data = UIImageJPEGRepresentation(images[0], 0.1) {
            uploadImageToFirebaseStorage(data: data).then { result in
                print("result is \(result?.downloadURL())")
                }.catch {error in
                print(error)
            }
        }
    }
```

**Comment by skk2142** [comment]
this is an awesome library.

**Comment by mxcl** [comment]
You solved your problem ok?

**Comment by skk2142** [comment]
yes, I was making a stupid mistake. Thanks for getting back to me.

**Comment by mxcl** [comment]
np, we're here to help.
