### ISSUE TITLE
Build errors in UIKit extension for an Objective-C++ project

### ISSUE THREAD

**Issue by sryze** [mxcl/PromiseKit#685]
* PromiseKit version: 4.0.5
* Xcode version: 8.3.3
* CocoaPods version: 1.2.1

I use PromiseKit in an Objective-C project and since recently I've been getting compile errors coming from PromiseKit's headers related to UIKit extensions:

```
PromiseKit/PromiseKit.framework/Headers/PromiseKit-Swift.h:236:12: Cannot find interface declaration for 'UIView'
PromiseKit/PromiseKit.framework/Headers/PromiseKit-Swift.h:240:12: Cannot find interface declaration for 'UIViewController'
PromiseKit/PromiseKit.framework/Headers/PromiseKit-Swift.h:244:12: Cannot find interface declaration for 'UIViewController'
```

They point to the following lines of `PromiseKit-Swift.h`:

```
@interface UIView (SWIFT_EXTENSION(PromiseKit))
@end


@interface UIViewController (SWIFT_EXTENSION(PromiseKit))
@end


@interface UIViewController (SWIFT_EXTENSION(PromiseKit))
@end
```

One strange thing is that these errors may go away after a few attempts, or after closing Xcode, doing clean, removing derived data, etc. It seems to be a bug in Xcode (or the compiler) but I wasn't sure so posting this here (feel free to close).

I've tried updating to the latest PromiseKit via CocoaPods but no success.

**Comment by sryze** [comment]
Does PromiseKit support Objective-C++? I've discovered that the only file that was producing these errors was a `.mm` file I added yesterday that imported PromiseKit.

**Comment by mxcl** [comment]
We support it in that we don't not support it. If you have a fix we will apply it.

**Comment by mxcl** [comment]
I cannot fix this, I don't know how to make an objective C++ project.

**Comment by mxcl** [comment]
The issue still exists, but I'll need your help or someone else’s.

**Comment by mxcl** [comment]
Closing due to stagnancy.
