### ISSUE TITLE
"Pending Promise deallocated! This is usually a bug" when promise is rejected with NSURLErrorDomain and NSURLErrorCancelled

### ISSUE THREAD

**Issue by acecilia** [mxcl/PromiseKit#686]
* PromiseKit version: 4.2.2
* Xcode version: 8.3.3

I am using PromiseKit when using URLSession. When the dataTask returns a networkError of session cancelled type (domain: NSURLErrorDomain, code: NSURLErrorCancelled = -999) I reject the promise, and at that point I get a "PromiseKit: Pending Promise deallocated! This is usually a bug" error. I tested others, but It only happens with that exact combination of domain and code. With other domain or code, the error is catched correctly and the execution continues as expected without any warning in the log.
See screenshot: 
<img width="1076" alt="screen shot 2017-07-17 at 15 44 49" src="https://user-images.githubusercontent.com/7938671/28270906-6088b4de-6b07-11e7-8d7f-eff96715b0cb.png">

I saw that, internally, promiseKit manages this error in some way, but I could not understand it. See screenshot of Promisekit internals:
<img width="905" alt="screen shot 2017-07-17 at 15 43 15" src="https://user-images.githubusercontent.com/7938671/28270941-84afa9b2-6b07-11e7-831d-c6c1e62f840e.png">

How can I solve the issue? After the error appears in the log, my .catch or .always closures are never called.

Thanks!

**Comment by mxcl** [comment]
> "PromiseKit: Pending Promise deallocated! This is usually a bug" 

You don't reject or fulfill the promise in one path. I just about see that path in your screenshot. Troubleshooting tips for this issue are [documented here](https://github.com/mxcl/PromiseKit/blob/master/Documentation/Troubleshooting.md#pending-promise-deallocated).

> After the error appears in the log, my .catch or .always closures are never called.

Canceled errors do not run `catch` typically. See the [cancelation documentation](https://github.com/mxcl/PromiseKit/blob/master/Documentation/CommonPatterns.md#cancellation).

**Comment by acecilia** [comment]
So, if I understand correctly:
- Some more context: in this concrete case, I am experiencing an SSL pinning error coming from TrustKit (As explained here: https://github.com/datatheorem/TrustKit/issues/39)
- This cancel error coming from TrustKit is wrongly identified by PromiseKit as a cancelation order (line 131 of the second screenshot I uploaded. NSURLErrorDomain, -999)
- My catch is not being called due to this.

Right?

**Comment by acecilia** [comment]
(After removing the line 131 of my second screenshot from PromiseKit and run the app, everything works as expected)

**Comment by acecilia** [comment]
So, after reading and testing it, the solution is to use .catch(policy: .allErrors) instead of just .catch
Thank you very much!

**Comment by mxcl** [comment]
Ah, yeah this is a dupe of some other ticket.

Apple marks this error as a cancelled error which is surprising to us and you.

I thought we had added logging for this situation though.

**Comment by acecilia** [comment]
And now I am thinking: is the policy of "not catching cancelation by default" the best one?

Because I am using TrustKit, I found myself changing all .catch in my app to .catch(policy: .allErrors) so I am sure all my flows work as expected (even when there is an SSL pinning error). I can imagine many apps using PromiseKit+TrustKit. Will it make sense to capture cancelation by default? Why cancelation is not capture by default?

I can not think in other approach to solve this issue.

Thanks!

**Comment by mxcl** [comment]
The issue is that Apple are incorrectly using a “cancelation error” for this API.

Generally this is a useful feature because it allows you to handle cancelation as you would want it to be handled in cases where things are canceled.

**Comment by mxcl** [comment]
We have justification in the 2.0 release post: http://promisekit.org/news/2015/05/PromiseKit-2.0-Released/

I am considering removing NSURLErrorCanceledError from the list of canceled error types since it causes this issue.

**Comment by acecilia** [comment]
Yes, that NSURLErrorCanceledError was consider as a promise cancelation was a surprise for me. I was expecting that a reject() would lead to a catch in each an every case, until now. 
In my mind I was sure that the code could only outcome with fulfill() [normal flow] or reject() [catch flow]. But knowing that cancelation is not catched by default, means that to be sure that all flow cases are covered I have to implement the behavior for fulfill() [normal flow], reject() [catch flow] AND cancelation: using recover [recover flow].

I would prefer that cancelation is catched by default, leading to two possible flows. But of course the implementation is as it is for some good reasons. 

This was just an idea you may consider.

**Comment by mxcl** [comment]
As I say, it's a bug, just not at a layer we can fix. So if everything worked you never would have been surprised.
