### ISSUE TITLE
.catch block with an error is called when response is success

### ISSUE THREAD

**Issue by IlyaKulbakin** [mxcl/PromiseKit#687]
* PromiseKit version: 4.2.2
* Xcode version: 8.3.2

If response received with status code differ than 200 (201 Created for example which means "Success" too) - Promise will be error and .catch block will be called

**Comment by mxcl** [comment]
Please provide a code sample or some context.

**Comment by mxcl** [comment]
I think you are using `NSURLSession`?

If so PromiseKit is merely a wrapper around the Apple API. Apple doesn't provide an error for a non 200 status code, so we don't reject the promise.

If you require this then the suggested path is to create a class that handles HTTP, or to use Alamofire.
