### ISSUE TITLE
FAQ addition:  can you explain joint & join

### ISSUE THREAD

**Issue by dgaedcke** [mxcl/PromiseKit#688]
I'd like to understand what they represent and how they work....
I read the reference material but that only show's how to call them...not what they actually do...

**Comment by mxcl** [comment]
The join resolves the promise.

**Comment by dgaedcke** [comment]
Why would I use join instead of just fulfill?  Can you show an example?

I've also been looking for docs re: dangers/best practices for saving a pending promise in an instance variable.    I have a Social login SDK that opens the Facebook App & asks the user to authenticate, and then returns the results to my AppDelegate external URL handler.   It's after that callback from the URL handler that I want to either fulfill or reject my stored promise..

**Comment by mxcl** [comment]
Joint exists to replace:

```
let (foo, fulfill, reject) = Promise.pending()
promise.then(fulfill).catch(reject)

// with

let (foo, joint) = Promise.joint()
promise.join(joint)
```

So for your situation you probably want just `.pending()`.

I'm not improving the docs on Joint as it was an experimental feature we intend to remove due to insufficient value and we have a different way to do it for PMK5.

**Comment by dgaedcke** [comment]
sure....if it's going away, I don't need to understand it....
that "pending" pattern makes much more sense to me anyway...
at least the way I've been using it....but your example is quite a bit more concise....
I think (line #2) is saying:
if "promise" succeeds, then "foo" succeeds, else "foo" fails

this teaches me something....so you can pass the completion functions any place another promise is expected.....

**Comment by mxcl** [comment]
PromiseKit 5 abandons this construct.
