### ISSUE TITLE
addition to Common patterns docs

### ISSUE THREAD

**Issue by dgaedcke** [mxcl/PromiseKit#690]
How can I return a "dummy" Promise that has already been rejected??

I have this code:
```
	func getJwtTokenString() -> Promise<String> {
		return firebaseUser?.getIDToken()
	}
```
as you can see ("firebaseUser?") our Firebase wrapper will only return the promise if there is a current user logged in.....

what can I return to my caller if there is no current user??

**Comment by mxcl** [comment]
Documented in `Promise.swift`, completable by typing `Promise` and pressing tab.

`Promise(error: err)`
