### ISSUE TITLE
PromiseKit 4.3.0 on CocoaPods

### ISSUE THREAD

**Issue by zvonicek** [mxcl/PromiseKit#691]
Hi Max! First, thanks for this fabulous library, it makes my life easier every day.

One question, is there a reason why PromiseKit 4.3.0 is not yet available on CocoaPods, although there is already a 4.3.0 tag in the repo? Thanks!

**Comment by mxcl** [comment]
It takes ~40 minutes for cocoa pods to lint PMK and every time I tried it failed. I succeeded in not killing myself in frustration, but have been unable to summon the courage to try again.

**Comment by mxcl** [comment]
You can use it without it being published (docs are online for using a tag), and next time I have the time, I will try to push again.

**Comment by mxcl** [comment]
Pushed.
