### ISSUE TITLE
Is it posible to cancel all promises?

### ISSUE THREAD

**Issue by aluco100** [mxcl/PromiseKit#692]
Please help me, I want to cancel all my promises when the user logouts. This is my code:

 
       
      public func logout(){
        
       let realm = try! Realm()
        
        try! realm.write {
            realm.deleteAll()
            let mainStoryboard: UIStoryboard = UIStoryboard(name: "Main", bundle: Bundle.main)
            let viewController = mainStoryboard.instantiateViewController(withIdentifier: "loginViewController")
            let navigation = UINavigationController(rootViewController: viewController)
            UIApplication.shared.keyWindow?.rootViewController = navigation
        }
    } 

I want when I'm deleting all in realm's database, all my promises behind the app will be reject or cancelled. ¿How I can do that?

**Comment by mxcl** [comment]
PromiseKit is a minimal wrapper around asynchronicity.

How would you cancel all the asynchronous tasks your app is doing without PromiseKit? That is how you do it with PromiseKit too.
