### ISSUE TITLE
Executing the same promise chain multiple times

### ISSUE THREAD

**Issue by sidmani** [mxcl/PromiseKit#694]
* PromiseKit version: 4.3.1
* Xcode version: latest non-beta version

I'm using Firebase to retrieve items from a list in the database, so the same async completion handler will be called multiple times. How do I wrap such a function? The obvious way seems to be to just put the promise chain inside the completion handler, but that's not clean.

``` 
func foo() {
    ref.observe(.childAdded) { snapshot in 
        // this is called many times, and I need it to execute the same promise chain each time
    }
}

func bar() {
  // I want this
    ref.observe(.childAdded).then {
        // do something for each call of observe()'s callback
    }.then {
        // do something else for each call
    }
}
```

**Comment by mxcl** [comment]
The only easy way to do this is to add the chain to the completion handler.

The harder way would be to write your own `.then` for the firebase object returned from `observe` which returns your own “promise-like” objects that do the same as above but you'll get your cleaner code.

Promises only complete once, which is their feature, and in places like this, their curse.

**Comment by sidmani** [comment]
Thanks. I'll just put them in the completion handlers, then.
