### ISSUE TITLE
Chaining more than five promises in a tuple

### ISSUE THREAD

**Issue by jaruwits** [mxcl/PromiseKit#695]
* PromiseKit version: 4.2.2
* Xcode version: 8.3

Hi is it possible to return more than five promises in a tuple ? My code looks like following
```
firstly {
    a()
}.then {
    b()
}.then {
    c()
}.then {
    d()
}.then {
    e()
}.catch {
    ....
}
```
How can I add 
```
.then {
    f()
}
```
after finishing e()

I have already tried to add f() but the compiler says 'expression was too complex to be solved in reasonable time'.

**Comment by jaruwits** [comment]
I have already try to add f() but the compiler says 'expression was too complex to be solved in reasonable time'.

**Comment by mxcl** [comment]
Yes, it is possible. Try specifying return types on your `then` blocks to see if it helps the compile solve it faster.

However you can't add a `then` to a `catch`, if that was what you were trying.
