### ISSUE TITLE
Max report

### ISSUE THREAD

**Issue by jonasman** [mxcl/PromiseKit#698]
Max you are such a rude little kid.

I started following you on twitter because of the amazing work at Promisekit.
I even made talks about it in my company to be used in our project.

Then after reading your twittes i saw you were fired from apple and i suported you.
Then i saw your negative comments all the time and backed up.

Now you are rude and called me a moron. This is unacceptable.

You are just a rude person and full of yourself. 

I will not support anymore your projects. I made some commits but never again will i help you. 

After all you deserve what happen to you.
Being fired from apple and rejected from companies. Good luck being an asshole!

**Comment by mxcl** [comment]
Just to clarify, I wasn't fired from Apple.

**Comment by chamons** [comment]
https://github.com/contact/report-abuse

**Comment by nathanhosselton** [comment]
Closing. Can confirm Max is not a child nor an asshole. Source: I know him IRL.
