### ISSUE TITLE
Help wanted: deferring promise execution

### ISSUE THREAD

**Issue by jankaltoun** [mxcl/PromiseKit#699]
* PromiseKit version: 4.2.2
* Xcode version: 8.3.3
* CocoaPods version: 1.2.1

Hello, I'd like to know if there is some standard way of deferring a Promise execution.
Currently I have this and it works but if there's something more official, I'd be happy to use it.

```
import PromiseKit

public class DeferredPromise<T> {
    
    let promiseClosure: () -> Promise<T>
    
    init(_ promiseClosure: @escaping @autoclosure () -> Promise<T>) {
        
        self.promiseClosure = promiseClosure
    }
    
    public func run() -> Promise<T> {
        
        return promiseClosure()
    }
}

public extension Promise {
    
    public static func deferred(_ promise: Promise<T>) -> DeferredPromise<T> {
        
        return DeferredPromise(promise)
    }
}
```

**Comment by mxcl** [comment]
I'd probably just do this:

```
myTask() -> () -> Promise<Void> {
    return {
        // return promise
    }
}
```

There is no API for this though, no.

**Comment by jankaltoun** [comment]
Thank you for the info! 🙂

**Comment by zlangley** [comment]
If you are queuing these DeferredPromises, you may find these classes helpful: https://gist.github.com/zlangley/e6c7ea0b49f8a3cea0df35bd20c9c865
