### ISSUE TITLE
I have installed PromiseKit, but Xcode still complaining that "use of undeclared type Promise" 

### ISSUE THREAD

**Issue by queeeentin** [mxcl/PromiseKit#702]
"use of undeclared type Promise"  when uting Promise <String> as the return type. 

what is going on?

**Comment by mxcl** [comment]
1. How did you install PromiseKit?
2. Did you `import PromiseKit`?

**Comment by queeeentin** [comment]
I have fixed it by dragging the Pod.xcodeproject to the Pods directory. But I am still having a problem as shown below:
![screen shot 2017-08-13 at 9 12 52 am](https://user-images.githubusercontent.com/15115511/29251329-be8baf86-8007-11e7-87d7-80a52ec3dfe2.png)

will you happen to know how to fix it?

**Comment by mxcl** [comment]
You are having a link error and have not provided the link error message. I cannot help until you provide the link error message. To do this you need to open up the build log and click through, then copy the message here.

**Comment by queeeentin** [comment]
here is the message:


Showing Recent Issues
Ld /Users/user/Library/Developer/Xcode/DerivedData/MyApp-hdbqgokcmjrkhjbktlbrgqjuvcfk/Build/Products/Debug-iphonesimulator/MyApp.app/PlugIns/MyAppTests.xctest/MyAppTests normal x86_64
    cd /Users/user/Desktop/MyApp
    export IPHONEOS_DEPLOYMENT_TARGET=10.3
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -bundle -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk -L/Users/user/Library/Developer/Xcode/DerivedData/MyApp-hdbqgokcmjrkhjbktlbrgqjuvcfk/Build/Products/Debug-iphonesimulator -F/Users/user/Library/Developer/Xcode/DerivedData/MyApp-hdbqgokcmjrkhjbktlbrgqjuvcfk/Build/Products/Debug-iphonesimulator -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks -filelist /Users/user/Library/Developer/Xcode/DerivedData/MyApp-hdbqgokcmjrkhjbktlbrgqjuvcfk/Build/Intermediates/MyApp.build/Debug-iphonesimulator/MyAppTests.build/Objects-normal/x86_64/MyAppTests.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -mios-simulator-version-min=10.3 -dead_strip -bundle_loader /Users/user/Library/Developer/Xcode/DerivedData/MyApp-hdbqgokcmjrkhjbktlbrgqjuvcfk/Build/Products/Debug-iphonesimulator/MyApp.app/MyApp -Xlinker -object_path_lto -Xlinker /Users/user/Library/Developer/Xcode/DerivedData/MyApp-hdbqgokcmjrkhjbktlbrgqjuvcfk/Build/Intermediates/MyApp.build/Debug-iphonesimulator/MyAppTests.build/Objects-normal/x86_64/MyAppTests_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -Xlinker -add_ast_path -Xlinker /Users/user/Library/Developer/Xcode/DerivedData/MyApp-hdbqgokcmjrkhjbktlbrgqjuvcfk/Build/Intermediates/MyApp.build/Debug-iphonesimulator/MyAppTests.build/Objects-normal/x86_64/MyAppTests.swiftmodule -framework XCTest -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/user/Library/Developer/Xcode/DerivedData/MyApp-hdbqgokcmjrkhjbktlbrgqjuvcfk/Build/Intermediates/MyApp.build/Debug-iphonesimulator/MyAppTests.build/MyAppTests.xctest.xcent /Users/user/Library/Developer/Xcode/DerivedData/MyApp-hdbqgokcmjrkhjbktlbrgqjuvcfk/Build/Products/Debug-iphonesimulator/PromiseKit/PromiseKit.framework/PromiseKit -Xlinker -dependency_info -Xlinker /Users/user/Library/Developer/Xcode/DerivedData/MyApp-hdbqgokcmjrkhjbktlbrgqjuvcfk/Build/Intermediates/MyApp.build/Debug-iphonesimulator/MyAppTests.build/Objects-normal/x86_64/MyAppTests_dependency_info.dat -o /Users/user/Library/Developer/Xcode/DerivedData/MyApp-hdbqgokcmjrkhjbktlbrgqjuvcfk/Build/Products/Debug-iphonesimulator/MyApp.app/PlugIns/MyAppTests.xctest/MyAppTests

ld: framework not found PromiseKit for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


![screen shot 2017-08-13 at 2 53 10 pm](https://user-images.githubusercontent.com/15115511/29253628-2b85a1f8-8037-11e7-92b1-f056b20d7763.png)

**Comment by mxcl** [comment]
Your project cannot find PromiseKit to link it, this means your CocoaPods installation is incorrect. I suggest following the instructions at cocoapods.org for how to integrate with an existing xcodeproj.

**Comment by mxcl** [comment]
The usual steps are:

1. Create the `Podfile`
2. `pod install`
3. open the `xcworkspace` NOT the `xcodeproj`

**Comment by queeeentin** [comment]
I have done the what you said, but same error is still showing. 

Please note that the error is occuring in the UnitTest file, not in the app level (The App run normall, just the Unit test not running) Please refer to the test example below. 

![screen shot 2017-08-14 at 8 45 40 pm](https://user-images.githubusercontent.com/15115511/29301561-e514c996-8131-11e7-992d-7eef8a3cc5e1.png)

**Comment by mxcl** [comment]
Perhaps you need to tell your Podfile to depend on PromiseKit in the test target also.

https://github.com/CocoaPods/CocoaPods/issues/4944

**Comment by alastaircoote** [comment]
I have this same issue, but my project builds (and runs) fine. Yet Xcode 9 (beta 5) syntax/error highlighting continues to show that Promise isn't defined. Is there any useful debug info I can provide?

**Comment by mxcl** [comment]
Please open a new ticket.

**Comment by mxcl** [comment]
Closing due to lack of response.
