### ISSUE TITLE
Error Ambiguous use of 'dataTask(with:)'

### ISSUE THREAD

**Issue by pffan91** [mxcl/PromiseKit#703]
* PromiseKit version: 4.3.2
* Xcode version: 8.3.3
* CocoaPods version: 1.3.1
* Carthage version: -

Just received new project's source code. They wrote own http network layer. I add PromiseKit to this project. Then I receive error

/Users/VSemenchenko/XCode/Test1/Test2/Test3/Workers/Network Layer/Http/Just.swift:792:20: Ambiguous use of 'dataTask(with:)'

Looks like there is conflict. When I removing NSURLSession+AnyPromise files from framework - all works well. How can I fix it without deleting files?

**Comment by mxcl** [comment]
1. You can not import the Foundation extensions by specifying:

    pod 'PromiseKit/CorePromise'

2. You can specify `import class PromiseKit.Promise` in files that are effected.
3. You can specify the return type of the `dataTask` type so Swift knows which version to use.

**Comment by pffan91** [comment]
Thank you @mxcl ! This solved my problem. In my case I just set correct type to variables that affected.

**Comment by mxcl** [comment]
FFR in PromiseKit 5 (unreleased next major version) we do not cause ambiguity. I regret that there is ambiguity currently.
