### ISSUE TITLE
Can a nested .catch block work similar as .recover

### ISSUE THREAD

**Issue by danlozano** [mxcl/PromiseKit#706]
* PromiseKit version: 4

I've used a .recover block before when I have a default value for a Promise that I don't mind if it fails, and I don't want to make the whole chain fail.

But sometimes I have no default value, but I still don't care if it fails. For example:

I have a couple of chained promises that compromise making a payment, tokenizing the credit card, making a request, etc...

At the end of the chain I would like to send a request to update some model, BUT it's not 100% important, and if it fails I don't care. I don't want the whole chain to "fail" and make it seem like the payment didn't work. BUT I don't have a default value either, so I cant use .recover.

Would something like this work?

```swift
tokenizeCard().then { token -> Promise<Payment> in 
  return makePayment(token)
}.then { payment -> Promise<User> in
  return updateUserModel().catch { print("I don't care if this fails") }
}.then { user in
  //
}.catch { error in 
  // I want this catch block to be called IF there's an issue with tokenize or payment, BUT if update user model fails I don't care.
  print("ERROR")
}
```

Would that work like I think?

**Comment by mxcl** [comment]
Something like this?

```
tokenizeCard().then { token -> Promise<Payment> in 
  return makePayment(token)
}.then { payment -> Promise<Void> in
  return updateUserModel().}.then { user in
  //
  }.asVoid().recover { }
}.catch { error in 
  print("ERROR")
}
```

**Comment by danlozano** [comment]
- Oooh interesting! as asVoid() ignores the promise type and let's me recover with "nothing" ?

- And just for curiosity. Would my previous code of using the nested catch work but it's considered bad practice? or would it not even work like I assume?

--- 

So, with your code

```swift
tokenizeCard().then { token -> Promise<Payment> in 
  return makePayment(token)
}.then { payment -> Promise<Void> in
  return updateUserModel().then { user in
    // Do something with user
  }.asVoid().recover { }
}.then { () -> Void in 
   // Would this still be called after all the chain finishes?
   // I don't care if update user model succeeds, BUT I only want to "continue" 
   // when updateUserModel() is finished, either by succeeding or failing, doesn't matter
      self.goToNextScreen()
}.catch { error in 
   // And this would only be called if error in tokenize and payment, correct? 
   // because of the .recover in updateUserModel()
  print("ERROR")
}
```

**Comment by mxcl** [comment]
Your two comments are correct.

`asVoid()` returns a new promise that is `Void`, it is directly equivalent to `then{ _ in }` which can be seen if you check the sources.

**Comment by danlozano** [comment]
It's all making sense now. Can't thank you enough!
