### ISSUE TITLE
Question: What's the podfile swift_version variable for?

### ISSUE THREAD

**Issue by joaomvfsantos** [mxcl/PromiseKit#708]
* PromiseKit version: 4.4
* Xcode version: 9.0 Beta 7
* CocoaPods version: 1.3.1
* Carthage version: N/A

Before all, I'm sorry If this is somehow a stupid question, but I've been scratching my head with this. 😛 
I was reading your [documentation](https://github.com/mxcl/PromiseKit/blob/master/Documentation/Installation.md) on how to use Swift 4, and it states to use:

> swift_version = "4.0"

However unless I actually add a post_install rule on the podfile to force the SWIFT_VERSION to 4.0 on all pods then the swift version will always be set to 3.2

Note: Also the same documentation points to a "swift4-beta1" which does not exist.

**Comment by faimin** [comment]
if you set swift_version to 4.x, you should use the Xcode 9.x +, Xcode 8.x not contain Swift 4.x environment

**Comment by joaomvfsantos** [comment]
Yes, I'm using XCode 9, as stated in my first post. The thing is when I do pod install, with ```swift_version = "4.0"``` in my podfile, the Pod PromiseKit framework is always using 3.2 instead.

**Comment by faimin** [comment]
you can try to look over the current swift version in your system by commond `xcrun swift -version`, 
and make sure have swift4.x environment, or use [swiftenv](https://github.com/kylef/swiftenv) library to control the swift version.

**Comment by mxcl** [comment]
According to the CocoaPods documentation `swift_version` in the `Podfile` controls the Swift version used for the generated project.

That's all I know. If you need to know more you will have to ask team CocoaPods.

**Comment by mxcl** [comment]
I have removed this instruction as it no longer seems recommended by CocoaPods.
