### ISSUE TITLE
Xcode8.3.3 compiler error with PromiseKit 4.4.0

### ISSUE THREAD

**Issue by jaz-ah** [mxcl/PromiseKit#709]
* PromiseKit version: 4.4.0
* Xcode version: 8.3.3
* CocoaPods version: 1.3.1

Promisekit 4.4.0 builds fine on Xcode9 beta6, but when building/archiving with Xcode8.3.3 I get the following error:

```.../Pods/PromiseKit/Extensions/UIKit/Sources/UIViewController+AnyPromise.m:45:34: No known class method for selector 'cancelledError'```

**Comment by mxcl** [comment]
I suggest a fresh `pod install` as the function it cannot find is absolutely part of PromiseKit 4.4.0:

https://github.com/mxcl/PromiseKit/blob/6b18b8826ea46f970d4c580614c492cb30a3f314/Sources/Error.swift#L110-L113

**Comment by mxcl** [comment]
Notably this is a function that the compiler generates the header for, so it seems like the compiler failed to generate the header.

**Comment by mxcl** [comment]
So I would clean and try again.

Like always, if you don't actually use any of PromiseKit’s UIKit extensions then you can remove them from your Podfile:

```
pod 'PromiseKit', subspecs: ['CorePromise']
```

**Comment by jaz-ah** [comment]
i had to clean out my derived data, etc.. and then it all worked fine thx @mxcl
