### ISSUE TITLE
PromiseKit implement cache and fetch feature

### ISSUE THREAD

**Issue by balrajOla** [mxcl/PromiseKit#710]
I am trying to implement caching layer as an extension to promiseKit. Where I can fetch data from cache->doaction and then refreshData from network calls->doAction. One of the solutions i found is as below:-

```
func fetch() -> Promise<Data, Promise<Data>> {
return Promise { fulfill, reject in
    let fresh = URLSession.GET(url)
    let cache = Data(contentsOfFile: cachePath)
    fulfill((cache, fresh))
  }
}

fetch().then { cachedData, freshData -> Promise<Data> in
  if let data = cachedData {
    update(data: data)
   }
  return freshData
}.then(execute: update)
```
Is there a better way to solve this problem?

**Comment by mxcl** [comment]
There is not a better solution with promises that I know of.
