### ISSUE TITLE
Problems calling PMKManifold from Objective-C++

### ISSUE THREAD

**Issue by mmahkamov** [mxcl/PromiseKit#712]
* PromiseKit version: 4.4
* Xcode version: 9.0
* CocoaPods version: 1.3.1

I have a Objective-C++ module (along with Objective-C and Swift) in my project which uses PromiseKit. If PMKManifold is called in this module, it results in a linker error:

> Undefined symbols for architecture x86_64:
> "__PMKArrayWithCount(unsigned long, ...)", referenced from:

That was easily fixed by importing PromiseKit in the .pch file this way:

```
#if __cplusplus
extern "C" {
#endif
    
#import <PromiseKit/PromiseKit.h>
    
#if __cplusplus
}   // Extern C
#endif
```

Unfortunately, after upgrading to Xcode 9 the compiler fails miserably with very strange errors when generating Objective C headers from PromiseKit's Swift modules.

Now I have only the option to patch AnyPromise.h in order to fix the build:

```
#if __cplusplus
extern "C" {
#endif
    
extern id __nonnull __PMKArrayWithCount(NSUInteger, ...);

#if __cplusplus
}   // Extern C
#endif
```

Would it be possible to include this change or would that break some compatibility with existing code?

**Comment by mxcl** [comment]
I will push the new Pod this evening.

Until then you can use this tag thus:

```
pod 'PromiseKit', :git => 'https://github.com/mxcl/PromiseKit.git', :tag => '4.4.1'
```

**Comment by chkpnt** [comment]
Unfortunately, version 4.4.1 is still not available via CocoaPods.

**Comment by mxcl** [comment]
Please forgive me, pushing to CocoaPods takes an hour, during which time my computer is out of action due to the 100% CPU usage required. Every time I do the push it fails. I have wasted tens of hours on this.

For now use the above work around is completely identical to the eventual push.

**Comment by mxcl** [comment]
K done.
