### ISSUE TITLE
"Pending Promise Deallocated" started in 4.4.0

### ISSUE THREAD

**Issue by repomies** [mxcl/PromiseKit#713]
* PromiseKit version: 4.4.0

Code that used to work for 1.5 years is now failing to return a callback because a promise gets deallocated somewhere. All was still well in branch `swift4-beta1` (which, unfortunately, is no longer available).

If it helps to know, the failing callback is for `patchCurrentUser` inside `reloadAndPatchCurrentUser` (pardon my barbarian wrapping of promises in oldskool completion callbacks):

```
    func reloadUser(_ completion: ((_ success: Bool, _ error: Error?) -> Void)? = nil) {
        userRequest.getUser().then { user -> Void in
            
            completion?(true, nil)
            
        }.catch { error in
            
            if let error = error as? KOError, error.statusCode == 401 {
                self.logOut()
                return
            }
        
            completion?(false, error)
        }
    }
    
    func reloadAndPatchCurrentUser(_ completion: ((_ success: Bool, _ error: Error?) -> Void)? = nil) {
        reloadUser { (success, error) in
            
            if success {
                
                self.patchCurrentUser { (success, error) in
                    completion?(true, nil)    // We don't care if the "update" fails
                }
                
            } else {
                
                completion?(false, error)
            }
        }
    }
    
    func patchCurrentUser(_ completion: ((_ success: Bool, _ error: Error?) -> Void)? = nil) {
        
        guard let user = session.user,
              let firstName = user.firstName,
              let lastName = user.lastName,
              let email = user.email else {
                
                completion?(false, nil)
                return
        }
        
        self.userRequest.updateUser(
            firstName: firstName,
            lastName: lastName,
            email: email,
            company: user.company).then { user in
                
                completion?(true, nil)
                
            }.catch { error in
                
                completion?(false, error)
        }
    }
```

**Comment by repomies** [comment]
Well, now after some pod reinstallations and rebuilds it seems to work again (in 4.4.0).

**Comment by mxcl** [comment]
Yeah, none of this code has changed for years. For serious.

**Comment by mxcl** [comment]
Please check our Troubleshooting guide regarding this warning. It is serious and the fact you saw it probably means that some part of your code does not handle all completion paths. If a path is not handled it *will* result in non terminating chains that to the user will look like a “task” that never completes.

**Comment by repomies** [comment]
Thanks, your Troubleshooting guide sure helped me to understand the issue. Deep in the codebase I found this piece that was the culprit:
```
if let error = error {
    reject(error)
} else if let json = json {
    fulfill(json)
}
```
(And the real reason why it appeared now was my JSON parser's changed behavior and newly introduced failabilities.)
