### ISSUE TITLE
`then block` is called only once 

### ISSUE THREAD

**Issue by hashemp206** [mxcl/PromiseKit#716]
I'm using Promisekit with Firebase, and observing a DatabaseReferencePath. Firebase observes the path and call `fulfill(snapshot)` multiple times. but problem is here, `then block` is called only once.

I read hear : http://promisekit.org/docs/cookbook/wrapping-delegation/

**Promises are one shot: they resolve once**

so how can I call then block multiple times?

**Comment by clarkcox3** [comment]
As I understand it, you cannot. A promise is meant to be fulfilled once, and only once.

**Comment by hashemp206** [comment]
so how PromiseKit observes object properties with KVO?  
does something like this works with PromiseKit? 
because by scrolling scroll view, content offset changes rapidly

``` swift
 _ = collectionView.observe(keyPath: #keyPath(UIScrollView.contentOffset)).then { [unowned self] (newValue: CGPoint) -> Void in
                
print("change happened")
            }
```

do you have any idea how can I overcome this issue? this is a big problem for me! because in my code there are a lot of dependent asynchronous tasks, which without PromiseKit, is too hard to maintain!

**Comment by mxcl** [comment]
`then` is only fulfilled once. If you need a closure to be called many times you have to use something else. Facebook's KVOController is good IMO, or if you are using Swift 4, type-safe closure-based KVO is now part of the runtime, so use that.

**Comment by hashemp206** [comment]
so it seems is not possible.🙁
Here I don't have a property to observe. instead Firebase just observe a `DatabasePathReference` for value changes and then call its completion block multiple times. 

```Swift
private func getUserChatIds() -> Promise<[String]> {
        
        let userChatIDsRef = Database.database().reference()
            .child(FireDatabasePaths.UserInfoPath.rawValue)
            .child(userID).child("chatIDs")
        
        return Promise { fulfill, reject in
            
            userChatIDsRef.observe(.value, with: { snapshot in
                
                if let chatIDdic = snapshot.value as? [String: AnyObject] {
                    let keys = Array(chatIDdic.keys)
                    fulfill(keys)
                } else {
                    reject(FirebaseError.empty)
                }
                
            })
        }
    }

func fetchChatSummaryList() -> Promise<[ChatSummary]> {
        return getUserChatIds().then { chatIDs in
            self.fetchChatSummaryList(from: chatIDs)
        }
   }
```

in this scenario I converted it to use completion block, but it makes my code ugly. 

what would you do in this case?

if there is no good solution you can close the issue.

**Comment by mxcl** [comment]
Indeed, there is no good solution for Firebase with PromiseKit. I should probably add this to the FAQ.

**Comment by mxcl** [comment]
I included an example of something you can do in the above referenced document. It's probably not what you were hoping though.

**Comment by hashemp206** [comment]
Thanks for update.
 
without using Promises Firebase absolutely needs a solution. 
how can I write a wrapper around Firebase to do multiple event chaining ?
