### ISSUE TITLE
Publish version `4.1.8` to CocoaPods

### ISSUE THREAD

**Issue by SandroMachado** [mxcl/PromiseKit#717]
Hi,

I am trying to use the version `4.1.8` but it is not available in CocoaPods, can you please publish it?

```
-> PromiseKit (4.4.0)
   Promises for Swift & ObjC.
   pod 'PromiseKit', '~> 4.4.0'
   - Homepage: http://promisekit.org
   - Source:   https://github.com/mxcl/PromiseKit.git
   - Versions: 4.4.0, 4.3.2, 4.3.1, 4.2.2, 4.2.0, 4.1.7, 4.1.4, 4.1.3, 4.1.2, 4.1.0, 4.0.5, 4.0.4, 4.0.3, 4.0.1, 4.0.0, 3.5.3, 3.5.2, 3.5.1, 3.5.0, 3.4.4, 3.4.3, 3.4.2, 3.4.1, 3.4.0, 3.3.0, 3.2.1, 3.2.0,
   3.1.1, 3.1.0, 3.0.3, 3.0.2, 3.0.1, 3.0.0, 2.2.1, 2.2.0, 2.1.3, 2.1.2, 2.1.1, 2.1.0, 2.0.6, 2.0.5, 2.0.4, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.7.2, 1.7.1, 1.7.0, 1.6.0, 1.5.3, 1.5.2, 1.5.1, 1.5.0, 1.4.3,
   1.4.2, 1.4.1, 1.4.0, 1.3.0, 1.2.5, 1.2.4, 1.2.3, 1.2.2, 1.2, 1.0.3, 1.0.2, 1.0.1, 1.0, 0.9.21, 0.9.19, 0.9.18, 0.9.17.1, 0.9.17, 0.9.16.6, 0.9.16.5, 0.9.16.4, 0.9.16.3, 0.9.16.2, 0.9.16.1, 0.9.16,
   0.9.15.3, 0.9.15.2, 0.9.15.1, 0.9.15, 0.9.14.3, 0.9.14.2, 0.9.14.1, 0.9.14, 0.9.13.2, 0.9.13.1, 0.9.13, 0.9.11.1, 0.9.11, 0.9.10, 0.9.9, 0.9.8.1, 0.9.8, 0.9.7.5, 0.9.7.4, 0.9.7.3, 0.9.7.2, 0.9.7.1,
   0.9.7, 0.9.6, 0.9.5, 0.9.4, 0.9.3, 0.9.2, 0.9.1, 0.9.0 [master repo]
```

**Comment by mxcl** [comment]
4.1.8 had a specific change for Carthage only, so had no reason to be released for CocoaPods. Why do you need it?

**Comment by SandroMachado** [comment]
Because I have a library that supports Carthage and CocoaPods and uses PromiseKit as dependency and it would be great to have the same dependencies versions.

**Comment by mxcl** [comment]
OK, well it doesn't hurt. But linting takes ~1 hour, so I can only do it last thing as otherwise my computer is out of action, plus I cannot guarantee the linting will work since I am now on Xcode 9 and this requires Xcode 8. In fact I'm pretty sure it will not work. Hmm.

**Comment by SandroMachado** [comment]
```
git checkout 4.1.8
pod trunk push PromiseKit.podspec 
```
This should work, right?

Thanks, I will wait 👍

**Comment by mxcl** [comment]
> This should work, right?

Like I said, I doubt it will lint unless I install Xcode 8 which I guess I can do, but this will be a lot of time for me to spend, and I don't have much time available currently. Linting takes an hour, it probably will fail for some other revlock issue which will then waste more time.

**Comment by mxcl** [comment]
K, I disabled lint and pushed it.

**Comment by SandroMachado** [comment]
@mxcl Thanks 👍
