### ISSUE TITLE
PromiseKit 4.1.8: Use of undeclared type 'URLDataPromise'.

### ISSUE THREAD

**Issue by Laptopmini** [mxcl/PromiseKit#723]
* PromiseKit version: 4.1.8
* Xcode version: XCode 8.3.3
* CocoaPods version: 4.1.8

I have a framework which uses PromiseKit, for which I set up the following dependency in its specs
```ruby
s.dependency 'PromiseKit', '~> 4.1.7'
```

Because of this, version up to (and not including) `4.2` are fetched. However, it was reported to me that PromiseKit 4.1.8 has a compile issue, forcing me to change my dependency to the specific version `4.1.7`. 
![Screenshot](https://i.imgur.com/gxG9DO9.png "Screenshot")

This is an easy "fix" on my end, but I was surprised to find this.

Possibly Related:
#717

**Comment by mxcl** [comment]
Confirmed, please upgrade to 4.4.2.

**Comment by mxcl** [comment]
4.1.8 is now deleted.

However, please upgrade. There is no reason I can see you'd want to stick with 4.1.x.
