### ISSUE TITLE
Promise deallocated due to slow network

### ISSUE THREAD

**Issue by damianfitpotato** [mxcl/PromiseKit#725]
* PromiseKit version: 4.4.0
* Xcode version: 9

Hi all, hope someone can point me in the right direction. 
I am calling **getSearchAdsInfo()** and most of the time it works ok. 
But in edge cases where users have bad connections, it fails and never returns.
I have managed to replicate the issue using the Link Conditioner setting "**High Latency DNS**"

When I use this high latency setting, Apple's **ADClient.shared().requestAttributionDetails** never returns and in Xcode console I get "**Pending Promise deallocated! This is usually a bug**". As it doesn't return, the app gets stuck indefinitely.

I have tried wrapping it in a retry/timeout as mentioned at [https://github.com/mxcl/PromiseKit/issues/350](https://github.com/mxcl/PromiseKit/issues/350)
But the same issue still happens.

So I can see the issue, but I am not sure how to handle it or where/what is causing the deallocation. Is this an iOS issue or a PromiseKit issue? Any insight would be greatly appreciated. 

```swift
       self.getSearchAdsInfo().then { attributionDictionary -> Void in
                self.setiAdInfoForUser(attributionDictionary: attributionDictionary)
                self.sendUserInfoToServerAndCompleteRegistration()
            }.catch(policy: .allErrors) { error in
                //if any error, ignore it and continue with registration
                self.sendUserInfoToServerAndCompleteRegistration()
            }

    func getSearchAdsInfo() -> Promise<Dictionary<AnyHashable, Any>> {
        return Promise { fulfill, reject in
            ADClient.shared().requestAttributionDetails({ (attributionDetails, error) in
                if error == nil {
                    for (type, adDictionary) in attributionDetails! {
                        let attributionDictionary = adDictionary as! Dictionary<AnyHashable, Any>
                        fulfill(attributionDictionary)
                    }
                } else {
                    reject(error!)
                }
            })
        }
    }
```

**Comment by mxcl** [comment]
If `attributionDetails` is empty you neither call `reject` or `fulfill`. We provide more details of this kind of issue in our trouble-shooting guide.

**Comment by damianfitpotato** [comment]
@mxcl Hi Max, thanks for taking the time to reply, I really appreciate it. I tried what you suggested, as per below.. but the issue still remains. I debug this and the code never reaches any lines after the requestAttributionDetails() call.

I have also tested the same thing with one of our own api calls, using AlamoFire and PromiseKit and with the High Latency DNS profile, it comes back after about 10 secs - no issues. 

But when using Apple's ADClient.shared().requestAttributionDetails() we are seeing the ***Pending Promise deallocated! This is usually a bug*** message multiple times, within about 5 seconds of the call.

I wonder if there is some DNS timeout whereby iOS cancels the request if it can't resolve a domain name within a certain time, and this somehow doesn't propagate through and the Promise just gets deallocated? Or if there is something else at play... 


```
2017-10-14 18:57:54.110485+1100  [MC] Loaded MobileCoreServices.framework
2017-10-14 18:58:01.372098+1100  PromiseKit: Pending Promise deallocated! This is usually a bug
2017-10-14 18:58:01.372306+1100  PromiseKit: Pending Promise deallocated! This is usually a bug
```

```swift
    func getSearchAdsInfo() -> Promise<Dictionary<AnyHashable, Any>> {
        return Promise { fulfill, reject in
            ADClient.shared().requestAttributionDetails({ (attributionDetails, error) in
                
                if attributionDetails == nil {
                    reject(PMKError.nilPromisable)
                } else if error == nil {
                    for (type, adDictionary) in attributionDetails! {
                        let attributionDictionary = adDictionary as! Dictionary<AnyHashable, Any>
                        fulfill(attributionDictionary)
                    }
                } else if error != nil {
                    reject(error!)
                } else {
                    reject(PMKError.nilPromisable)
                }
            })
        }
    }
```

**Comment by mxcl** [comment]
Your above sample does not correct the issue I refer to. If `attributionDetails` is **empty**, then you don't `fulfill` or `reject`.

**Comment by mxcl** [comment]
```swift
for (type, adDictionary) in attributionDetails! {
    let attributionDictionary = adDictionary as! Dictionary<AnyHashable, Any>
    fulfill(attributionDictionary)
}
reject(SomeError.emptyArray)
```

**Comment by mxcl** [comment]
```
func getSearchAdsInfo() -> Promise<[AnyHashable: Any]> {
    return Promise { fulfill, reject in
        ADClient.shared().requestAttributionDetails{ attributionDetails, error in
            if let attributionDetails = attributionDetails {
                for case let value as [AnyHashable: Any] in attributionDetails.values() {
                    fulfill(value)
                }
                reject(MyError.invalidAttributionDetails)
            } else if let error = error {
                reject(error)
            } else {
                reject(PMKError.invalidCallingConvention)
            }
        }
    }
}
```

**Comment by damianfitpotato** [comment]
Thanks again for taking time to look into this! I have tried this, but the issue still remains...

I am not sure if this is relevant, but we may not be using the same version of Swift+PromiseKit
My PromiseKit doesn't have ```PMKError.invalidCallingConvention```

I can only set one of these:
```
    public enum PMKError: Error {
        case navigationControllerEmpty
        case noImageFound
        case notPromisable
        case notGenericallyPromisable
        case nilPromisable
    }
```

Also, ```attributionDetails.values()``` did not compile (had to remove the parentheses)

```swift
    func getSearchAdsInfo() -> Promise<[AnyHashable: Any]> {
        return Promise { fulfill, reject in
            ADClient.shared().requestAttributionDetails{ attributionDetails, error in
                if let attributionDetails = attributionDetails {
                    for case let value as [AnyHashable: Any] in attributionDetails.values {
                        return fulfill(value)
                    }
                    reject(PMKError.nilPromisable)
                } else if let error = error {
                    reject(error)
                } else {
                    reject(PMKError.notPromisable)
                }
            }
        }
    }
```

**Comment by mxcl** [comment]
If all paths are covered then almost certainly *your* code in `requestAttributionDetails is not calling the callback under certain circumstances.

PromiseKit is 5 years old now, it works.

**Comment by damianfitpotato** [comment]
Cool thanks again for looking into it, I had a feeling it was an issue with Apple's ```requestAttributionDetails``` function.

**Comment by mxcl** [comment]
Oh it’s Apple's function? Well, I'd be surprised if theirs does not call the callback. I could be wrong, but that's unusual.

Still, I'd be super surprised if it's PromiseKit not working. This is so thoroughly tested at this point.

**Comment by mxcl** [comment]
I'd look elsewhere, the warning doesn't give any context (unfortunately, but fixing that is hard). Is there another promise that may be causing this warning?

**Comment by damianfitpotato** [comment]
Hi Max, in that part of the code, there is no other promise being called so nothing other than Apple's function. When I try the same test using one of our own functions that uses a Promise it works fine. But in this case where the Apple function is wrapped in a Promise, this issue is happening.

I will see if I can isolate this into a simple one-file project and replicate just to be sure though. I too don't think it is a PromiseKit issue, I thought I may have been using PromiseKit wrong. But given this now seems unlikely, I will see if I can figure it out elsewhere.

Thanks again for your feedback and advice.

**Comment by mxcl** [comment]
Well if it does turn out to be Apple's fault (bad Apple!) then you can work around by adding a timeout:

```swift
func getSearchAdsInfo() -> Promise<[AnyHashable: Any]> {
    let p1 = Promise { fulfill, reject in
        ADClient.shared().requestAttributionDetails{ attributionDetails, error in
            if let attributionDetails = attributionDetails {
                for case let value as [AnyHashable: Any] in attributionDetails.values {
                    return fulfill(value)
                }
                reject(PMKError.nilPromisable)
            } else if let error = error {
                reject(error)
            } else {
                reject(PMKError.notPromisable)
            }
        }
    }
    let p2: Promise<[AnyHashable: Any]> = after(seconds: 10).then{ throw E.timout }
    return race(p1, p2)
}
```

**Comment by mxcl** [comment]
Closing due to stagnation.
