### ISSUE TITLE
How to add http header fields while using promisekit.

### ISSUE THREAD

**Issue by udaypatial** [mxcl/PromiseKit#727]
* PromiseKit version: 4.4.0
* Xcode version: 9
* CocoaPods version: 1.3.1

**Comment by mxcl** [comment]
With what? URLSession? Alamofire? BoogieFoogiePlats?

**Comment by udaypatial** [comment]
URLSession

**Comment by mxcl** [comment]
You add them to the `URLRequest` just like if you weren't using PromiseKit.
