### ISSUE TITLE
PromiseKit no longer builds for projects targeting 10.10

### ISSUE THREAD

**Issue by saagarjha** [mxcl/PromiseKit#728]
* PromiseKit version: 4.4.2
* Xcode version: Xcode Version 9.1 beta (9B46)
* CocoaPods version: 1.4.0.beta.1
* Carthage version: N/A

It appears that 191950c006909039895a30fb13d34e1d087a4822, which changed the minimum deployment target to OS X 10.11, makes it impossible to use PromiseKit in projects that have a lower deployment target (i.e. 10.10).

**Comment by mxcl** [comment]
Sorry for my delay here, I am pressed for time currently.

**Comment by saagarjha** [comment]
As you can see by the tardiness of my replies I'm not really in a rush here.

**Comment by mxcl** [comment]
I may have to say: use Carthage. CocoaPods barely works, here is an example of it. I cannot change the macOS deployment target to a lower value or the podspec won't pass even though there is no reason for this to be the case.

**Comment by mxcl** [comment]
K this is now live on CocoaPods too for 6.0.1.

**Comment by saagarjha** [comment]
Thanks!
