### ISSUE TITLE
When PromiseKit support static framework pod

### ISSUE THREAD

**Issue by karosLi** [mxcl/PromiseKit#729]
* PromiseKit version: 4.4.0
* Xcode version: 9
* CocoaPods version: **1.4.0-beta**

The CocoaPod 1.4.0-beta currently support to upload static framework pod with swift source, like below code. So could PromiseKit pls support static framework pod?

[Reference for static framework](https://github.com/CocoaPods/CocoaPods/pull/6811)

```
s.ios.deployment_target = '8.0'
s.static_framework = true
s.source_files = 'MyLib/Classes/**/*'
s.public_header_files = 'Pod/Classes/**/*.h'
s.dependency 'GoogleTagManager', '~> 5.0'
```

**Comment by mxcl** [comment]
I need some official docs before I'm going to implement support. Been bitten otherwise in the past. IS there any?

**Comment by karosLi** [comment]
@mxcl hello, here is the cocoa pod detail info for static framework pod with swift source: https://github.com/CocoaPods/CocoaPods/pull/6811

**Comment by karosLi** [comment]
Is there any reply?

**Comment by mxcl** [comment]
I’m still waiting on some kind of  official blessing from the CocoaPods team.

**Comment by ataibarkai** [comment]
FYI, cocoapods 1.4.0 is officially out. They describe static framework support in the release notes
http://blog.cocoapods.org/CocoaPods-1.4.0/

**Comment by mxcl** [comment]
I can's support this then I guess. The docs suggest we either say we are a static or a dynamic framework, but static frameworks are less useful.

I don't really get why CocoaPods chose to implement this feature this way. Really it should be something the `Podfile` decides on and not the `.podspec`

**Comment by 0xwangbo** [comment]
I tested it. If .podspec has `s.static_framework = true` and the user declares `use_frameworks!` in the Podfile, it will get xxx.framework. If you don't declare `use_frameworks!`, you will get xxx.a 

Declaring `s.static_framework = true` in the .podspec does not directly determine the final output, but depends on the user. right? Looking forward to your reply @mxcl
