### ISSUE TITLE
Return Void

### ISSUE THREAD

**Issue by NikKovIos** [mxcl/PromiseKit#730]
`Missing return in a closure expected to return 'AnyPromise'` - it is an error which i'm getting.

I'm doing a wrapper under Firebase. Here is my chain:
```swift
0        firstly {
1            auth(email: email, password: password)
2        }.then { user in
3            self.uploadAvatar(avatarImage: avatarImage, user: user)
4        }.then { (avatarPath, user) in
5            self.uploadUserInfo(dict: dict, avatarPath: avatarPath, user: user)
6        }.then {
7            print("🧀 Yeay!")
8            self.resetValues()
9<<<<< error `Missing return in a closure expected to return 'AnyPromise` <<<<<
10        }.catch { error in
11            self.viewController.show(error: error)
12        }.always {
13            Decorator.hideLoader()
14        }
```
```swift
private func uploadUserInfo(dict: [String: Any], avatarPath: String, user: User) -> Promise<Void>
```

I read all the Faq and http://promisekit.org/faq/. But can't get rid of this =(
It's ok when there is one line at 7-8 lines, but when two and more it throws a compiler error.
`self.resetValues()` is just a simple method without any promises.

Could you please help with syntax.

**Comment by zlangley** [comment]
Adding the types should help the compiler.

```swift
}.then { () -> Void in
    self.resetValues()
}```

**Comment by NikKovIos** [comment]
I've already tried this and it didn't help:
![2017-10-19 23 58 54](https://user-images.githubusercontent.com/16647690/31794026-8d43db4a-b529-11e7-93d5-8d90ce7ee661.png)

**Comment by zlangley** [comment]
You are missing the `in` keyword.

**Comment by mxcl** [comment]
Documented workarounds here: https://github.com/mxcl/PromiseKit/blob/master/Documentation/Troubleshooting.md
