### ISSUE TITLE
No 'rejected' property in Objective-C...

### ISSUE THREAD

**Issue by jgrantr** [mxcl/PromiseKit#731]
PromiseKit version 4.4
Xcode 9.0

When upgrading an older project, I noticed that there is no longer a 'rejected' property on AnyPromise when using Objective-C.  Was that an intentional removal?  I'm using it when using PMKJoin to determine which promises succeeded and which failed.

**Comment by mxcl** [comment]
I don't think we ever had this property on `AnyPromise`.

**Comment by jgrantr** [comment]
Yep, it was there in the AnyPromise.h  header (along with 3 other properties) until July 31, 2015, when it was removed with commit 444dcdd with the message "Fixes #225", but it (and the other 3 properties) remained in AnyPromise.swift with an @objc decorator, so they were still accessible from Objective-C.  Then on Sept 7, 2016,  2 of them were put back into the AnyPromise.h header in commit 67bc256, at which time the 'rejected' property was removed from AnyPromise.swift (also in the same commit).

**Comment by mxcl** [comment]
K well, this was a long time ago.

I don't particularly want to rock the `AnyPromise` boat. It is a mess of badness due to how it uses the Swift/ObjC boundary.

Quite possibly this is how they came to be removed.

**Comment by jgrantr** [comment]
Thanks for fixing this!  Love using PromiseKit in my apps.  It's become a staple pod on every Objective-C  (and Swift) project I work on, so thanks for all you do!

**Comment by mxcl** [comment]
np, and I appreciate the thanks. I am but human too. This fix is not yet released, but will release 6.0.1 soon.
