### ISSUE TITLE
Change #if to #ifdef  to suppress Xcode 9.1 warning/error?

### ISSUE THREAD

**Issue by mpkeefe** [mxcl/PromiseKit#733]
* PromiseKit version: **~> 4.4.0**
* Xcode version: **9.1 (9B55)**
* CocoaPods version: **N/A**
* Carthage version: **0.26.2**

Since Xcode 9.1 Beta 2 and continuing with the 9.1 release, after re-building PromiseKit for Swift 4.0.1,  we get `__cplusplus is undefined, evaluates to 0` build warning when importing PromiseKit into our code. (We have warnings set to generate errors, so cannot proceed.)

Changing 
```
#if __cplusplusxx
extern "C" {
#endif
```

to 

```
#ifdef __cplusplusxx
extern "C" {
#endif
```

in `AnyPromise.h` suppresses the warning and allows the build to succeed.

Any reason not to make this change, and if not can shall I go ahead and submit a PR?

**Comment by mxcl** [comment]
K, sucks. PR welcome, or I can do it.

**Comment by mxcl** [comment]
I've done it.
