### ISSUE TITLE
Hi, I'm looking for an operator with the same semantic as the 'When' operator present in the oldest PMKPromise object, there is one in the last version of PromiseKit library? 

### ISSUE THREAD

**Issue by ludovico87** [mxcl/PromiseKit#736]
PromiseKit  4.5.0
Xcode version: 9
* CocoaPods version: **only required for build issues**
* Carthage version: **only required for build issues**

> Please format your code in triple backticks and delete this line before submitting your ticket. Failure to remove this line may result in mockery.

**Comment by mxcl** [comment]
It's `PMKWhen()`.
