### ISSUE TITLE
PromiseKit in a Framework - linking against a dylib which is not safe for use in application extensions

### ISSUE THREAD

**Issue by lucabartoletti** [mxcl/PromiseKit#737]
I have PromiseKit in a framework, if I select the Xcode option `Allow app extension API only` I get this warning.

I added PromiseKit using Cocoapods

```
warning: linking against a dylib which is not safe for use in application extensions: /Users/<...>/Products/Debug-iphonesimulator/PromiseKit/PromiseKit.framework/PromiseKit
```

What is this about? 

I turned on that flag cause I plan to add a extension to the app I'm writing, I want to make sure to not include non extension API by mistake in my framework

**Comment by mxcl** [comment]
You probably just have to run `pod update` again

**Comment by mxcl** [comment]
For your reassurance: PromiseKit is 100% extension-API-safe. You could tell be opening the xcodeproj and observing we have this checkbox set, or using Carthage which doesn't exhibit these sort of issues.

**Comment by lucabartoletti** [comment]
Yes, you are right, running `pod update` after turning on `Allow app extension API only` in my project did the trick.

Thanks @mxcl
