### ISSUE TITLE
Question regarding when(resolved:) and the order of the array

### ISSUE THREAD

**Issue by jyounus** [mxcl/PromiseKit#738]
Hey there,

I have a quick question. If I use the ```when(resolved:)``` method, is the order of the ```[Result<T>]``` array the same as the Promises I passed in?

So I'm not asking if the promises are resolved in order, but I'm asking if the results array will equal the order of the Promises I passed in. 

Here's an example:

```
var metadata = [(PHAsset, Int)]()
// some code here that adds some objects to my array above
// ...

var promises = [Promise<LocalPhotoEntity>]()
// some code here to convert data inside the metadata array into promise objects
// ...

firstly {
    when(resolved: promises)
}.then { (results: [PromiseKit.Result<LocalPhotoEntity>]) -> Void in

    for (index, result) in results.enumerated() {
        switch result {
        case .rejected(let error):
            let info = metadata[index]
            // handle error state here using the metadata array to know which "operation" failed so I can handle UI updates accordingly

        case .fulfilled(let entity):
            // code to handle success
            // ...
        }
    }
}
```

This line of code: ```let info = metadata[index]``` is that a safe assumption for me to make? Is it guaranteed that the order of the results will be the same as the order of the promises that are passed in?

If not, how would I handle such errors? I need to handle each error in the ```when(resolved:)``` method individually, so I can update the UI appropriately. But if a promise fails, I would only get an Error object, without the additional metadata when I created the promise (unless I'm missing something). 

The only other alternative I can think of is to return an Error object which has that detail (the PHAsset and Int values), but I think that would be an overkill to return back such a specific error object. Maybe I'm wrong and that's better than my solution above?

**Comment by mxcl** [comment]
> is the order of the [Result<T>] array the same as the Promises I passed in?

Yes.

**Comment by jyounus** [comment]
Thanks
