### ISSUE TITLE
cannot convert AnyPromise to Promise<Void> after upgrade to version 4, swift version 3

### ISSUE THREAD

**Issue by randy68040** [mxcl/PromiseKit#739]
* PromiseKit version: 4

While converting from swift 2.3 to 3, the 3rd line below fails to compile with error: cannot convert value of type '[Promise<Any?>]' to expected argument type '[Promise<Void>]

```
    public func uploadUnsentJobs() -> Promise<Void> {
        return self.deletingJobs().then { deletingJobs in
            
            let deletes = deletingJobs.map { $0.delete().asPromise(()) }
            
            return when(fulfilled: deletes)            
        }
```
Previously used toPromise (available in earlier version of PromiseKit) to convert AnyPromise to Promise<Void> but do not know how to use the new method "asPromise" to do the same.

Previously compiled like this in earlier version of PromiseKit: 

```
let deletes = deletingJobs.map { $0.delete().toPromise(Void) }

            return join(deletes)
```

delete() is objective-c method which returns AnyPromise

**Comment by mxcl** [comment]
You have to specify the type of `deletes`. This is in our troubleshooting guide.

**Comment by randy68040** [comment]
deletes needs to be  array of Promise<Void> ... error from the xcode build log:
error: cannot convert value of type '[Promise<Any?>]' to expected argument type '[Promise<Void>]'
            return when(fulfilled: deletes)

**Comment by randy68040** [comment]
sorry, copy and paste was not so good. Here is exact error from xcode build log (deletes has skwiggely underlined):

cannot convert value of type '[Promise<Any?>]' to expected argument type '[Promise<Void>]'
return when(fulfilled: deletes)

**Comment by mxcl** [comment]
`let deletes: Promise<YOURTYPEHERE>`

**Comment by randy68040** [comment]
How we fixed it:
```
           let deletes = deletingJobs.map { (job : ENTJob) -> Promise<Void> in
                Promise { fulfill, reject in
                    job.delete()
                }
            }
             return when(fulfilled: deletes)
```
