### ISSUE TITLE
cannot convert AnyPromise to Promise, as was possible with AnyPromise's toPromise method

### ISSUE THREAD

**Issue by randy68040** [mxcl/PromiseKit#745]
* PromiseKit version: 4

In the process of upgrading app to Swift 3, method toPromise (was in PromiseKit version 3.5) converted AnyPromise to Promise<T>. 

Here is working swift 2.3, promiseKit 3.5 implementation:

```
        let getJobtype = job.jobType.resolve.toPromise(ENTJobType)
        let getEncounter = job.encounter.resolve.toPromise(ENTEncounter)
        let getQueue = job.queue.resolve.toPromise(ENTQueue)
        
        
        when(getJobtype, getEncounter, getQueue).then { (jobtype, encounter, queue)->Void in
```

Docs say to use asPromise in place of toPromise but following change is not equivalent. The following code has error on when's arguments getJobtype, getEncounter, getQueue) "argument labels '(_:, _:, _:)' do not match any available overloads." :

```
        let getJobtype = job.jobType.resolve.asPromise()
        let getEncounter = job.encounter.resolve.asPromise()
        let getQueue = job.queue.resolve.asPromise()
        
        
        when(getJobtype, getEncounter, getQueue).then { (jobtype, encounter, queue)->Void in
```

**Comment by mxcl** [comment]
Specify types.

**Comment by randy68040** [comment]
still get the same error though have update the 3 lets as follows:
```
        let getJobtype: Promise<ENTJobType> = job.jobType.resolve.asPromise(type: ENTJobType.self)
        let getEncounter: Promise<ENTEncounter> = job.encounter.resolve.asPromise(type: ENTEncounter.self)
        let getQueue: Promise<ENTQueue> = job.queue.resolve.asPromise(type: ENTQueue.self)
```

I am swift 3 newbie -- ... my favorite upgrade to swift 3 error description: expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions.

**Comment by randy68040** [comment]
final correction: 
```
when(fulfilled: getJobtype, getEncounter, getQueue).then
```
