### ISSUE TITLE
Contextual Closure Error When Migrating to Swift 4

### ISSUE THREAD

**Issue by nathan-inge** [mxcl/PromiseKit#752]
* PromiseKit version: 4.5.0
* Xcode version: 9.2
* CocoaPods version: 1.2.1

After migrating my project to Swift 4 (using the Xcode 9 Migration Tools), I am getting the following build error in several spots throughout my codebase (I was previously not getting this error before the migration):

`Contextual closure type '() -> AnyPromise' expects 0 arguments, but 1 was used in closure body`

This error occurs on the firstly line of a chain. For example...

```
return firstly { _ -> Promise<JSON> in          // ERROR occurs here
            let getInfo = SYGAPI.Media.Blob.BlobChunk.info

            return getInfo(blobID,
                           versionID,
                           chunkNumber)

        }.then...
```

I am using the UIKit extension (`pod 'PromiseKit/UIKit', '~> 4.5'`) but also tried 

`pod "PromiseKit", "~> 4.5", subspecs: ['CorePromise']`

as was recommended in https://github.com/mxcl/PromiseKit/issues/707. 

However I am still getting this specific error using both variations. Is there something additional I must do to PromiseKit during the Swift 4 migration? Or is it neccesary to change syntax in some way for Swift 4? Any insight would be greatly appreciated.

**Comment by mxcl** [comment]
Like usual, it's possible swift is lying about the error, so try putting the code in the closure outside the closure with an inline function.

Also try `firstly { () -> Promise<JSON> in` since the error suggests it doesn't like `_`. Still I'd be surprised if that works.

Swift may in fact be erroring later in the chain, so eyeball it and see if you can spot a syntax error elsewhere.

**Comment by nathan-inge** [comment]
Thank you for the quick response. I tried using 

`firstly { () -> Promise<JSON>`

and that seemed to do the trick. In the future I will definitely remember to try putting the code in the closure outside the closure to debug as well. 

Thank for your time, I appreciate it!
