### ISSUE TITLE
Sharing data between unresolved promises

### ISSUE THREAD

**Issue by drekka** [mxcl/PromiseKit#754]
* PromiseKit version: **5.0.3**

I'm playing around with some code where I'm wrapping SpriteKit `SKNode` actions in promises. One thing I've been looking at doing is creating a chainable DSL so I can do things like this:

```swift
let animations = skNode.fadeIn().andMoveTo(...)
``` 

where my `andMoveTo(...)` function looks like this:

```swift
func andMoveTo(_ loc:CGPoint) {
    // Combine the two promises.
}
```

In order to create the new promise I want to get the `SKNode` from the first promise in order to wrap the second promise around it. However I don't want to resolve the first promise as I'm going to execute both promises at the same time using `when (resolved:...)`.

In PromiseKit 4.5 I could extend `Promise` and add a property to it to store the node. In 5.0 I can no longer do that because it's public instead of open.

Any thoughts on how I can add some form of data to a promise that is not part of the block that is executed?

**Comment by mxcl** [comment]
You could try conforming a custom object to `Thenable`

**Comment by mxcl** [comment]
Closing due to lack of response.
