### ISSUE TITLE
Hundreds of network requests in a Promise

### ISSUE THREAD

**Issue by martheli** [mxcl/PromiseKit#758]
PromiseKit version: 4.5.0
Xcode version: 9.2

I have an Alamofire request that I have to call a few hundred times. I wrapped the loop in a promise but it seems to be only loading a certain number of times and then network requests stop and hang until timeout error is thrown. Is there a way to handle hundreds of requests within the Promise framework to prevent network timeouts?

Code is as follows:

```

func getData() ->Promise<String> {

return Promise { fulfill, reject in

 let dispatchGroup = DispatchGroup()

for device in devices {   //devices array contains 300-400 devices


 dispatchGroup.enter()

          Alamofire.request("https://testurl.com\(device)").responseData { response in

                if let json = response.result.value {

                    fulfill(json)

              } else {

                  reject("Error")

               }
        dispatchGroup.leave()
         }
 } 
```

**Comment by mxcl** [comment]
PromiseKit is a light wrapper around whatever you wrap. It has no bearing whatsoever on the performance or behavior of the things you wrap. If you are having issues with Alamofire then it is Alamofire that is the problem.

As an aside, why are you using DispatchGroups? If you are using PromiseKit then I'd suggest using Promises for such things.

**Comment by martheli** [comment]
I am not sure how to get the same result with Promises. How would I control the Alamofire loop to make sure all of them finish before Promise returns without using dispatch group?

**Comment by mxcl** [comment]
With `when` obviously.
