### ISSUE TITLE
Roadmap or ETA of PromiseKit 5.0 Documentation?

### ISSUE THREAD

**Issue by billThePill** [mxcl/PromiseKit#760]
* PromiseKit version: 5.0

In attempting to research and select a Promise framework for use in an app, PromiseKit is very promising. But the version 5.0 release has been available for two months with no documentation (sans internal code documentation). The Documentation files have yet to be modified to encourage and instruct new users to adopt PromiseKit. Not knowing what changes or migration may be necessary also deters adoption of the version 4 framework. 

- Can someone provide any insight on what feature changes/enhancements are forthcoming in v5.0? 
- Is there some whitepaper or roadmap document of what v5.0 brings to the table? 
- What migration challenges will be necessary for adopters of v4.x? 
- Any ETA of the v5.0 documentation?

Thanks for any insight!

**Comment by mxcl** [comment]
If you require documentation, continue to use v4. v5 documentation will be provided when I have time. You will not have to upgrade to v5 as both v4 and v5 will be supported forever.

**Comment by Prince2k3** [comment]
I agree with this. I'd like to know what is new in PromiseKit 5.0 so that I can take advantage of the new features. If you need help updating the documentation I'm sure one of us can help do this so as not to take away from your time.

**Comment by mxcl** [comment]
Feel free to use PMK5 and then if you then feel able to update the documentation, feel free.

**Comment by mxcl** [comment]
I'm releasing PMK 6 (which is 5, with a minor breaking change) today.
