### ISSUE TITLE
Treating `recover` as a replacement for `always` with a passed value

### ISSUE THREAD

**Issue by rayray** [mxcl/PromiseKit#761]
* PromiseKit version: 4
* Xcode version: 9.2
* Swift version: 3.2

I want to use `CLGeocoder` and `always` produce a `CLLocation`, whether the geocode call fails or not.

Unfortunately, you can't get a value to `always` without capturing an outside variable, and putting `recover` directly after the geocode call requires that `recover` returns either a `CLPlacemark` or `Promise<CLPlacemark>`, which requires that I unnecessarily create a `CLPlacemark` just to produce a default `CLLocation` that I already have.

    // build error
    CLGeocoder().geocode(postalCode).recover { error -> CLLocation in

Currently, I have this workaround:

    CLGeocoder().geocode(postalCode)
                        .then { placemark -> CLLocation in
                            guard let location = placemark.location else {
                                throw GeocodeError
                            }
                            return location
                        }
                        .recover { error -> CLLocation in
                            // ... make a default CLLocation
                            return defaultLocation
                        }
                        .then { location -> Void in // this is like an always
                            // handle location
                        }

Is there a better way to achieve what I want? 

Is `recover` guaranteed to be called if the `geocode` promise fails but is not chained directly after it?

**Comment by mxcl** [comment]
> Is recover guaranteed to be called if the geocode promise fails but is not chained directly after it?

Yes, `recover` will any previous part of its chain fails.

> Is there a better way to achieve what I want?

Based on what you want, the way you are doing it is correct.
