### ISSUE TITLE
Swift 4 compile error with Promise<Void>

### ISSUE THREAD

**Issue by dboydor** [mxcl/PromiseKit#763]
* PromiseKit version: 4.5.0
* Xcode version: 9.2
* CocoaPods version: 1.3.1

How do you call fulfill() with a Void promise?  I've looked high and low in the docs and the open/closed issues and couldn't find the answer.

Example code:
```
    func test1() -> Promise<String> {
        return Promise<String> { fulfill, reject in
            fulfill("Hello")
        }
    }

    func test2() -> Promise<Void> {
        return Promise<Void> { fulfill, reject in
            fulfill()
        }
    }
```
test1() compiles fine

test2() does not compile with this error:
```
fulfill()
Expression type '(_) -> Void' is ambiguous without more context
```

**Comment by pacification** [comment]
Try to return `fulfill(())` for `Promise<Void>` statement.

**Comment by mxcl** [comment]
Yes, `fulfill(())`. This is not an issue specific to PromiseKit and is in fact an issue with Swift 4, and there are in fact maybe 4 or 5 closed issues that ask this question, but I will add it to our TroubleShooting documentation.

**Comment by dboydor** [comment]
I actually looked through the closed tickets and code as well but I guess my searching foo isn't so good.  Thank you so much.  It's frustrating to learn Swift when they syntax changes from version to version!

**Comment by mxcl** [comment]
Changes from 3 to 4 were much less severe so hopefully 4 to 5 will be hardly anything.

Searching tickets can be hard, especially when there are so many, so it's good you opened the ticket as it made me add a proper note in the trouble-shooting guide.
