### ISSUE TITLE
Consecutive catch blocks don't execute sequentially.

### ISSUE THREAD

**Issue by mayurdzk** [mxcl/PromiseKit#764]
* PromiseKit version: **4.5.1**
* Xcode version: **9.2**

Chaining multiple `catch` blocks together (to be executed on different DispatchQueues) doesn't result in the block being executed sequence.

I've attached a sample project that exhibits the problem I'm having. Here's the explanation:

Say I have a Promise that has a `catch` block that I execute on a DispatchQueue. I return this promise outside to a caller, which may also want to execute its own `catch` block on the promise. If the caller executes their `catch` on a separate dispatch queue (or just doesn't provide one, in which case the default is the main queue), it results in both `catch`s being run concurrently, not sequentially, as the programmer would expect

In the attached project, you'll see that the output is something of the form:
```
Executing catch number: 1
Executing catch number: 2
Executing catch number: 3
Executing catch number: 4
Finished executing number: 1
Finished executing number: 2
Executing catch number: 6
Finished executing number: 3
Executing catch number: 5
Finished executing number: 4
Finished executing number: 6
Finished executing number: 5
```

whereas the prints should be something like:
```
Executing catch number: 1
Finished executing catch number: 1
Executing catch number: 3    // Which block gets serviced first may change? Haven't thought it through but the 'Executing' and 'Finished' should happen one after another.
Finished executing catch number: 3
Executing catch number: 2
Finished executing catch number: 2
```
[TestPromiseCatches.zip](https://github.com/mxcl/PromiseKit/files/1642437/TestPromiseCatches.zip)

**Comment by mayurdzk** [comment]
When the programmer writes the code:

```
myPromise.catch(on: myQueue1) {
  // Block 1
}.catch(on: myQueue2) {
  // Block 2
}
```
they probably expect Block2 to definitively run **after** Block1 (while honouring their choice of queues).

Essentially,`catches should exhibit `then`-like serial execution behaviour.

**Comment by mxcl** [comment]
This is fixed in PMK5, but I can't fix it in PMK4 without changing behavior, which considering the wide usage of PromiseKit, is not responsible.

In PMK5 `catch` returns a special object (a `PMKFinalizer`) which you can call `finally` on (`finally` provides no object) but not `catch`, which IMO is the only correct behavior. PMK3 did not allow you to do anything after a `catch`, PMK4 returns the parent promise, so what you are doing above is actually this:

```
myPromise.catch{ /* block 1 */ }
myPromise.catch{ /* block 1 */  }
```

Enabling this was a mistake on my part.

I will close this ticket when PMK 5 is available on CocoaPods. Refs #760.

LMK how else I can help. More discussion welcome, justification for PMK5 behavior can be provided–just ask–etc.

**Comment by mxcl** [comment]
A work-around would be to use `recover`:

```swift
myPromise.recover(on: myQueue1) { error in
    // Block 1
    throw error
}.catch(on: myQueue2) {
    // Block 2
}
```

**Comment by mayurdzk** [comment]
Thanks for replying!

> In PMK5 catch returns a special object (a PMKFinalizer) which you can call finally on (finally provides no object) but not catch, which IMO is the only correct behavior.

Makes complete sense to me. Although you this would mean source breaking changes for users who are using their promises in the `promise.catch{...}.catch{...)` fashion, if I'm not wrong? Just a thought.

> A work-around would be to use `recover`

In my case, I've already used a recover in my promise chain (don't know whether I can call a recover on a recover--haven't tried it). If you're curious, I'll explain the use case for my `promise.catch{...}.catch{...)` usage:

```
promise.recover {
  // Attempt to recover from a certain kinds of errors
}.catch {
  // If error is `foo`: persist the error to a data store
}
```

Then in my tests:
```
// Return a failed promise that has the error foo
promise.catch {
   // Verify error stored in persistent store == foo
}
```

Having the `catch`s in concurrently executing blocks makes my test fail. I've found a workaround though.

**Comment by mxcl** [comment]
> Although this would mean source breaking changes for users who are using their promises in the promise.catch{...}.catch{...) fashion, if I'm not wrong?

PMK5 includes many, many source breaking changes, this is the least of them.

> don't know whether I can call a recover on a recover--haven't tried it

Yes, it works as you would expect.

**Comment by mayurdzk** [comment]
> many, many source breaking changes, this is the least of them.

Ah, never mind then. Looking forward to it.

Thanks for your great work!

**Comment by mxcl** [comment]
I'm releasing PMK 6 (which is 5, with a minor breaking change) today.
