### ISSUE TITLE
thenIfKeyNotSet - not compiling

### ISSUE THREAD

**Issue by sdgandhi** [mxcl/PromiseKit#765]
* PromiseKit version: 4 (v4 branch)
* Xcode version: Version 9.2
* Swift version: 4

Hey PromiseKit team,

I'm trying to create a new `then` that executes if a key is not set, otherwise returns a default promise.

Firstly, is this the right way to go about solving that problem?

Secondly, any idea why the following code is causing the compiler to spin indefinitely?

```swift
extension Promise {
    @discardableResult
    public func thenIfKeyNotSet<U>(key: String, defaultPromise: Promise<U>, on q: DispatchQueue = .default, execute body: @escaping (T) throws -> Promise<U>) -> Promise<T> {
        guard UserDefaults.standard.bool(forKey: key) == false else { return defaultPromise }
        then(on: q, execute: body)
    }
}
```

**Comment by mxcl** [comment]
> Firstly, is this the right way to go about solving that problem?

Provided stuff that uses `thenIfKeyNotSet` understands the semantics, then it's cool. I've never personally ever done things like that, but I don't have your context. I'm sure it's fine.

> Secondly, any idea why the following code is causing the compiler to spin indefinitely?

You don't have a `return`?

**Comment by sdgandhi** [comment]
Oh lol, the compiler kept spinning instead of highlighting that. Thanks!
