### ISSUE TITLE
How to add headers to a request made with PromiseKit/OMGHTTPURLRQ?

### ISSUE THREAD

**Issue by bellebethcooper** [mxcl/PromiseKit#768]
* PromiseKit version: 4.4

I can't figure out how to add headers to my requests when I make them in the same format as the examples in [the README](https://github.com/PromiseKit/OMGHTTPURLRQ-/tree/5b0afa54c7a3b286ded2ca467b6c76b2ad0c7a5c). Is there a way to do so?

Thanks!

**Comment by mxcl** [comment]
Yes, you use OMGHTTPURLRQ directly. There's some docs here: https://github.com/mxcl/OMGHTTPURLRQ

Though not for Swift, but should give you some initial direction.

**Comment by bellebethcooper** [comment]
Got it, thanks.
