### ISSUE TITLE
Optional promise with reload first promise

### ISSUE THREAD

**Issue by freedoom1984** [mxcl/PromiseKit#770]
HI,
I read all documentation but I don't response my question with successfull.
I have this scenario
- I call the authenticated api point
1. If the response is 200 to 299 I fullfill
2. If the response is 401 I call the api for refresh the token

If i refreshed the API token I need to re-call the first api point (for recovery the needed data).
Can you help me with this problem?
Thanks

**Comment by mxcl** [comment]
```swift
func firstThing() -> Promise { /*…*/ }

firstly {
    firstThing()
}.then {
    if !ok {
        return refreshToken().then(firstThing)
    } else {
        return Promise(value: something)
    }
}
```

**Comment by freedoom1984** [comment]
Thanks mxci
I have another situation
1- I call the authenticated api point
2- I create the object if the call work fine
If the response is 401 I call the api for refresh the token and I need to return the point 1
If I want to return at the first point of the Promise?

With your example in this point
if !ok {
        return refreshToken().then(firstThing)
    } else {
        return Promise(value: something)
    }

I work out of the Promise workflow
Thanks

**Comment by mxcl** [comment]
Sorry I don’t understand your question.

**Comment by freedoom1984** [comment]
Hi,

`    @IBAction private func loadNotification(){
    
        firstly{
            
            provaRequest()
            
            }.then { dictionary -> Void in
                
                print(dictionary)
                
            }.catch{ (error) in
                
                if true{
                    
                    self.provaRefresh().then{ dictionary -> Void in
                        
                        self.loadNotification()
                    }
                }
        }
    }`

In this moment I solved my problem like this...but I don't like
I need restart (from the firstly) when the self.provaRefresh is executed (in the catch I capture the expiring of token, I refresh it end I recall the first endpoint "provaRequest()"

Thanks

**Comment by mxcl** [comment]
```
@IBAction private func loadNotification(){

    func foo() -> Promise {
        firstly {        
            provaRequest()
        }.then { dictionary -> Void in
            //…
        }
    }

    firstly {        
        provaRequest()
    }.recover { error in
        if case Error.foo = error {
            return provaRequest()
        } else {
            throw error
        }
    }.then { dictionary -> Void in
        //…
    }.catch { error in
        // other errors
    }
}
```

**Comment by freedoom1984** [comment]
Thanks @mxcl but I have the warning
`firstly{
            
            provaRequest()
            
            }.recover { (error) -> Promise<Any> in
                
                if true {
                    
                      return self.provaRefresh().then { dictionary -> Void in
                        
                        print(dictionary)
                        # self.provaRequest()
                    }
                    
                } else {
                    
                    throw HttpRequest.errorObject()
                }
                
            }.then { dictionary -> Void in
                
                print(dictionary)
                
            }.catch{ (error) in
                
                print(error)
        }`

Result of call to 'provaRequest()' is unused

**Comment by freedoom1984** [comment]
Hi,
I solved with this but I'm not sure it's okay

`let refresh:Promise<Any> = provaRefresh().then{_ in
            
            self.provaRequest()
            
        }
        
        
        firstly{
            
            provaRequest()
            
            }.recover { (error) -> Promise<Any> in
                
                if true {
                    
                    return refresh
                    
                } else {
                    
                    throw HttpRequest.errorObject()
                }
                
            }.then { dictionary -> Void in
                
                print(dictionary)
                
            }.catch{ (error) in
                
                print(error)
        }`

**Comment by mxcl** [comment]
The async tasks in `refresh` immediately start executing, so no, it isn't doing what you want. You need to wrap the whole thing in a function that returns the promise just like the example code I provided.

**Comment by mxcl** [comment]
You got a warning because you didn't `return`… just like the warning said…
