### ISSUE TITLE
PMKJSONError not available

### ISSUE THREAD

**Issue by ksathireddy** [mxcl/PromiseKit#771]
PMKJSONError is not available in fwd.h. So what is the replacement for it? The available error types are:

#define PMKUnexpectedError 1l
#define PMKInvalidUsageError 3l
#define PMKAccessDeniedError 4l
#define PMKOperationCancelled 5l
#define PMKOperationFailed 8l
#define PMKTaskError 9l
#define PMKJoinError 10l

Why other Error types removed in new version?

**Comment by mxcl** [comment]
Hi, the template for issue tickets explicitly asks for the promiseKit version you are using. You chose to ignore the template. How am I expected to help you if you won't help me?

**Comment by ksathireddy** [comment]
Hi mxcl, I am using PromiseKit version 4.4

**Comment by mxcl** [comment]
Hi, we removed it for version 4 because the framework didn't use it. There is no replacement.

**Comment by ksathireddy** [comment]
Hi mxcl, Where can i find docs related to PMKError types. Can you please post a link?

**Comment by mxcl** [comment]
There is no documentation for these constants.

**Comment by ksathireddy** [comment]
Ok mxcl. Thank you so much for your help.
