### ISSUE TITLE
Add information that .always was renamed to .ensure in migration guide

### ISSUE THREAD

**Issue by timbms** [mxcl/PromiseKit#775]
* PromiseKit version: 6.0
* Xcode version: 9.3

It took me some time to understand that I had to rename .always to .ensure 
It would helpful for followers to add a link to the remark in 
https://github.com/mxcl/PromiseKit/blob/master/Documentation/GettingStarted.md#ensure 

Tim

**Comment by mxcl** [comment]
Sure, I'll just do that for you right away.
