### ISSUE TITLE
How to migrate `Promisable` UIViewController to PromiseKit 6

### ISSUE THREAD

**Issue by QuentinArnault** [mxcl/PromiseKit#777]
Hi,

I'm migrating to PromiseKit 6 following the migration guide (very helpful, thanks). But I do not know how to migrate my ViewControllers implementing  the deprecated `Promisable` protocol. Any hint?

Regards,
Quentin

* PromiseKit version: 6

**Comment by mxcl** [comment]
Hi, I'll add this to the guide, I forgot. I removed this from the library because I didn't feel it was a good general solution (as well as a bad pattern due to violating encapsulation) and instead I recommend a custom solution each time. Our common-patterns guide contains this:

```swift
class ViewController: UIViewController {

    private let (promise, seal) = Guarantee<…>.pending()  // use Promise if your flow can fail
    
    func show(in: UIViewController) -> Promise<…> {
        in.show(self, sender: in)
        return promise
    }
    
    func done() {
        dismiss(animated: true)
        seal.fulfill(…)
    }
}

// use:

ViewController().show(in: self).done {
    //…
}.catch { error in
    //…
}
```

What do you think?

**Comment by QuentinArnault** [comment]
The custom solution seems good to me. Thanks.
In my case, I will extract `show` and `dismiss` in another object (like a Coordinator) in order to remove navigation logic from view controller.
And thanks for PromiseKit, I love this tool. ❤️

**Comment by mxcl** [comment]
LMK if you have any new ideas about it that we can supplement our guides with.
