### ISSUE TITLE
Documentation on Getting Started

### ISSUE THREAD

**Issue by timbms** [mxcl/PromiseKit#778]
Hi Max,

Getting Started still needs some rework

func fetch(completion: (String?, Error?) -> Void)
How do we convert this to a promise? Well, it's easy:

func fetch() -> Promise<String> {
    return Promise { foo(completion: $0.resolve) }
}

-->  return Promise { fetch(completion: $0.resolve) }

You may provde the expanded version more readable:
--> Typo

func fetch() -> Promise<String> {
    return Promise { seal in
        foo { result, error in
            seal.resolve(result, error)
        }
    }
}

foo { result, error in
--> 
fetch { result, error in

* PromiseKit version: 6.0
* Xcode version: 9.2

**Comment by mxcl** [comment]
This is unreadable. Can you please use markdown to format your ticket? Even better, fork the project and fix these issues yourself.

**Comment by nathanhosselton** [comment]
This was fixed by 762e322d9f8832ba56fb2eaa4442375f4e80e570 which seems to have been lost?

**Comment by mxcl** [comment]
Restored, very sorry. I need to get the hang of force pushing with “receipt” so it cannot lose new commits.
