### ISSUE TITLE
podspec development: AnyPromise or PMKPromise?

### ISSUE THREAD

**Issue by theodelrieu** [mxcl/PromiseKit#780]
* PromiseKit version: 1.7

Hello,

I'm currently developing a pod in Objective-C, which will be used by Objective-C and Swift projects.
I've seen in the docs that you advise people to use the 1.x version for stability reasons.

The 1.x releases expose a `PMKPromise` type.

However, in your [docs](http://promisekit.org/docs/objc/) you mention a `AnyPromise` that can be used in Swift as well.

The API is the same as `PMKPromise`, so I'm wondering which one I should expose in my API?

Can I use the latest PromiseKit version and still use pure Objective-C? Or sticking to 1.x?
Are `PMKPromise` and `AnyPromise` interchangeable?

Thanks a lot for the library by the way :)

**Comment by mxcl** [comment]
For PMK 2+ we renamed `PMKPromise` to `AnyPromise`. Not sure how to document this without being confusing to the 90% of people who use PMK 2+.

It's saf*er* to use PMK6 nowadays since Swift is less volatile, so perhaps we should reconsider our recommendation. Certainly, it's a lot better code and API than 1.7 is at this point.

If your intent is for people to use your library with both Swift and ObjC then honestly, PMK6 is much better for that.

**Comment by theodelrieu** [comment]
Thanks for the clarification!

I'm quite new to iOS development, but from what I've understood using PMK6 will force my consumers to link against the Swift standard libraries, which might be unacceptable to some of them.

Just to be sure: If a consumer depends on PMK6, will it be possible to use `PMKPromise` from my API without depending also on PMK 1.7?

**Comment by mxcl** [comment]
>  from what I've understood using PMK6 will force my consumers to link against the Swift standard libraries, which might be unacceptable to some of them.

Yes, it will, but TBH nowadays avoiding Swift is pretty hard.

> Just to be sure: If a consumer depends on PMK6, will it be possible to use PMKPromise from my API without depending also on PMK 1.7?

No, the APIs are different. In addition CocoaPods will refuse to install two versions of the same library side by side.

**Comment by theodelrieu** [comment]
>Yes, it will, but TBH nowadays avoiding Swift is pretty hard.

True. I hope I'll be able to drop Objective-C then!
