### ISSUE TITLE
Type of expression is ambiguous without more context

### ISSUE THREAD

**Issue by cmtrounce** [mxcl/PromiseKit#781]
* PromiseKit version: 6
* Xcode version: 9.2
* CocoaPods version: 1.4.0

So this is the code.

```swift
try service.fetchAll().then({ (result) in
      self.projects = result.projects
})
```

error: Type of expression is ambiguous without more context
happens on line: ```swift self.projects = result.projects```

function ```fetchAll()``` return type is a ```Promise<ProjectsResponse>``` which contains the ```projects``` variable

```self.projects``` and ```result.projects``` are same data type, and even the compiler auto completes the .projects value for me, correct with data type and code highlighting.

When I come to build time, I receive this error, which is really confusing.

**Comment by mxcl** [comment]
See our release notes and migration guide, you need to use `done`, then requires you to return a promise.

Next time something is confusing, check the function signature of the thing you are using (`then` here), it would make it clear what is expected of you when Swift is incapable of telling you.
