### ISSUE TITLE
Unable to infer closure return type. PromiseKit 6 + Alamofire + Codable

### ISSUE THREAD

**Issue by duyngn** [mxcl/PromiseKit#786]
* PromiseKit version: 6.0.2

Hello,
I'm having a bit of a hard time wrapping my head around the new changes to PromiseKit 6.
With PromiseKit 4, I was able to utilize a convenient trick to have Alamofire response with a generic decodable object in a Promise.  As described here: https://skyebook.net/blog/2017/09/swift-codable-with-alamofire-promisekit/

From that article, "Swift can infer the generic type to use when calling responseCodable() based on the return type. "  With PromiseKit 6 changing the main initializer, Swift doesn't seem to be able to infer the type anymore.  I've tried changing the old init of (fulfill, reject) to the new (seal) and then use seal.fulfill() and seal.reject() respectively, but Swift kept erroring with: "Unable to infer complex closure return type; add explicit type to disambiguate"

Is it possible to alter the below code to conform to PromiseKit 6's initializer and still make use of this convenient trick?

Here's the existing code that worked with PromiseKit 4:

```swift
struct NetworkObject: Decodable {
    var id: Int
    var name: String
}

func loadNetworkObjects() {
    self.fetchNetworkObjects().then { myNetworkObject -> Void in
        // Use the network object here
        let id = myNetworkObject.id
        let name = myNetworkObject.name
    }.catch { error in
        print("Something went wrong")
    }
}

func fetchNetworkObjects() -> Promise<NetworkObject> {
    return Alamofire.request("http://url.to/fetch/network/object").responseDecodable()
}

extension Alamofire.DataRequest {
    // Return a Promise for a Codable
    public func responseDecodable<T: Decodable>(queue: DispatchQueue = DispatchQueue.main) -> Promise<T> {
        return Promise { fulfill, reject in
            responseData(queue: queue) { response in
                switch response.result {
                case .success(let value):
                    let decoder = JSONDecoder()
                    do {
                        fulfill(try decoder.decode(T.self, from: value))
                    } catch let e {
                        reject(e)
                    }
                case .failure(let error):
                    reject(error)
                }
            }
        }
    }
}
```

I tried this and it doesn't seem to fix the issue:

```swift
extension Alamofire.DataRequest {
    // Return a Promise for a Codable
    public func responseDecodable<T: Decodable>(queue: DispatchQueue = DispatchQueue.main) -> Promise<T> {
        return Promise { seal in
            responseData(queue: queue) { response in
                switch response.result {
                case .success(let value):
                    let decoder = JSONDecoder()
                    do {
                        seal.fulfill(try decoder.decode(T.self, from: value))
                    } catch let e {
                        seal.reject(e)
                    }
                case .failure(let error):
                    seal.reject(error)
                }
            }
        }
    }
}
```

**Comment by mxcl** [comment]
Specifically what line is the error happening on?

**Comment by mxcl** [comment]
OK, I just added your code to the PMKAlamofire project and it compiles fine…

Suggests to me the error is elsewhere in your code and Swift is lying.

**Comment by mxcl** [comment]
I'm adding your code to the next PMK release, thanks!

**Comment by mxcl** [comment]
Travis: https://travis-ci.org/PromiseKit/Alamofire-/builds/343143339

**Comment by mxcl** [comment]
https://github.com/PromiseKit/Alamofire-/commit/0eff96092fadf5e23a7365a155a3660853d64266

**Comment by duyngn** [comment]
Oh sorry!  I should point out where it's complaining.

It's throwing me the error in the function "loadNetworkObjects()" on the line
```
self.fetchNetworkObjects().then { myNetworkObject -> Void in
```
It's complaining that it can't infer the type for "myNetworkObject"

**Comment by mxcl** [comment]
Like the migration guide says, you need to use `done`.

**Comment by duyngn** [comment]
Oh wow... Thanks so much for the quick responses!  Cheers!

**Comment by Patrick3131** [comment]
I have a question regarding your code, if I try to run your code I get an error in line:

> return Promise { fulfill, reject in

The error is:

> Contextual closure type '(Resolver<_>) -> Void' expects 1 argument, but 2 were used in closure body

I am wondering why?

Thanks.
