### ISSUE TITLE
Cannot catch cancellations anymore?

### ISSUE THREAD

**Issue by peres** [mxcl/PromiseKit#787]
* PromiseKit version: **5.0.0**

Commit 47367f1df656bf8e976e28fb59e553639efcf73a dropped ```catchWithPolicy``` without explanation. How do I catch all errors, including cancellations, in PromiseKit 5.0.0 and newer, in Objective-C code?

**Comment by mxcl** [comment]
The ObjC AnyPromise interface no longer supports cancellation. All errors go to the `catch`.

**Comment by mxcl** [comment]
I updated the migration guide to include this. Sorry it was missing.

**Comment by peres** [comment]
Thank you. I will hold off updating for the moment, then.
