### ISSUE TITLE
Promise.map has ambiguous behavior when manipulating collections

### ISSUE THREAD

**Issue by ldiqual** [mxcl/PromiseKit#795]
* PromiseKit version: 6
* Xcode version: 9.2
* CocoaPods version: 1.3.1

One thing I've noticed while converting from Promise 4 to 6 is that returning a collection from a promise of collection is really hard to do:

```swift
// func getFooList() -> Promise<[Foo]>

// Ambiguous reference to member 'map(on:_:)'
getFooList().map { list in
  return [Bar()]
}

//  'map(on:_:)' is deprecated: See: `mapValues`
getFooList().map { list in
  return list
}
```

This can only be solved by specifying the return type for both cases. For instance:

```
getFooList().map { list -> [Bar] in
  return [Bar()]
}
```

I believe this is due to the following deprecated `map` https://github.com/mxcl/PromiseKit/blob/57de813c42fe0ab8a4a6e29974cca2fc0cfafdd7/Sources/Deprecations.swift#L54 and it seems that the simplest fix would be to remove it altogether.

Does that sound reasonable? If yes I'll go ahead and PR that.

**Comment by mxcl** [comment]
Considering this variant only existed for 4 days I'm cool to remove it.
