### ISSUE TITLE
throw PMKError.cancelled doesn't resolve promise?

### ISSUE THREAD

**Issue by samrayner** [mxcl/PromiseKit#799]
* PromiseKit version: 6.1
* Xcode version: 9.3 beta 3

```
// Warns "pending promise deallocated"
Promise<Void> { _ in
    throw PMKError.cancelled
}.cauterize()

// Does not give warning
Promise<Void> { seal in
    seal.reject(PMKError.cancelled)
}.cauterize()
```

This may not signify anything important but:
1. I would expect throwing a cancellation error to resolve the promise? Am I wrong?
2. I'm pretty sure I didn't get warnings throwing the cancellation NSError in PromiseKit 4.

I'm happy to use `seal.reject` for now. The `throw` syntax is nicer for `guard` statements though.

**Comment by mxcl** [comment]
Here's the code:

```
public init(resolver body: (Resolver<T>) throws -> Void) {
    box = EmptyBox()
    do {
        try body(Resolver(box))
    } catch {
        box.seal(.rejected(error))
    }
}
```

So it's hard to see how the behavior would be different. Do you have a minimal testcase to hand?

**Comment by mxcl** [comment]
```swift
public extension Resolver {
    func reject(_ error: Error) {
        box.seal(.rejected(error))
    }
}
```

And here’s the code for `Resolver.reject`.

**Comment by samrayner** [comment]
Just includes the above code in the AppDelegate:
https://github.com/samrayner/pmkerror

**Comment by mxcl** [comment]
6.2.0 release coming up.

**Comment by samrayner** [comment]
Excellent, thanks
