### ISSUE TITLE
Cannot convert value of type '(_) -> Void' to expected argument type '(_) -> _'

### ISSUE THREAD

**Issue by Patrick3131** [mxcl/PromiseKit#801]
PromiseKit version: 6.2.0
Xcode version: 9.2

Hey!
I updated PromiseKit yesterday, before the update everything worked fine now it does not anymore.

I am using it with Alamofire to make network requests, I have a problem now:

```
       func apiCall() -> Promise<[Class]>  {
            
            return Promise { accepted, reject in
                
                Alamofire.request(
                    URL(string: apiUrl)!,
                    method: .get
                    )
                    .validate()
                    .responseJSON { response in
                        switch response.result {
                        case .success(let value):
                            let json = JSON(value)
                            let jsonString = json.description
                            let output = Class.decode(json: jsonString)
                            accepted(output)
                            
                        case .failure:
                            reject(response.error!)
                            
                        }
                }
            }
        }
```

I get this error in the line "return Promise...":

>  Contextual closure type '(Resolver<_>) -> Void' expects 1 argument,
>  but 2 were used in closure body

I could not find anything related to it in the migration guide.
I tried fixing it by deleting reject. But it does not work.
Thank you!

**Comment by Patrick3131** [comment]
Also tried this approach:
https://github.com/mxcl/PromiseKit/issues/752

but could not get it fixed.

**Comment by Patrick3131** [comment]
Also if i try to run his code:
https://github.com/mxcl/PromiseKit/issues/786

I get the same error as above.

**Comment by mxcl** [comment]
See our release notes and migration guide for PromiseKit 6. You are writing PromiseKit 4 code with PromiseKit 6.

You could easily figure this out by looking at the function definition for `Promise.init` please in future read the definitions of the functions you are using.

Consider using our Alamofire extension, it does all the work of using Alamofire and promises for you. The fact this extension exists is documented in many places.

The error message was a complete hint as to what you had to do, it said (literally) that you are providing two arguments to a function that expected one:

```swift
 func apiCall() -> Promise<[Class]>  {
    return Promise { seal in
        Alamofire.request(URL(string: apiUrl)!, method: .get)
            .validate()
            .responseJSON { response in
                switch response.result {
                case .success(let value):
                    let json = JSON(value)
                    let jsonString = json.description
                    let output = Class.decode(json: jsonString)
                    seal.fulfill(output)
                case .failure:
                    seal.reject(response.error!)
                }
        }
    }
}
```

**Comment by mxcl** [comment]
> I updated PromiseKit yesterday, before the update everything worked fine now it does not anymore.

Specify the major version of your dependencies so that they do not update to new major versions. This is how versions work, new major versions have breaking changes.

Learn to use your tools.

**Comment by Patrick3131** [comment]
Thanks for the answer.
I just started coding two months ago, I am still trying to learn.
