### ISSUE TITLE
Cannot convert return expression of type 'Promise<>' to return type 'Guarantee<[]>'

### ISSUE THREAD

**Issue by chrisnguyens** [mxcl/PromiseKit#807]
PromiseKit version: 6.2.0
Xcode version: 9.2

Hi guy!
I have some problems when updating from ver 4.x to 6.x. However, mostly I can resolve by reading doc. But I have the only issue:

```
let promise = Promise<[DAIPNumber]>.pending()
        
firstly{
    UIApplication.shared.isNetworkActivityIndicatorVisible = true
    return getIPNumbers(withAPI: .incomingPhoneNumber)
}.done{ ipNumbers in
    promise.resolver.fulfill(ipNumbers)
}.ensure {
    UIApplication.shared.isNetworkActivityIndicatorVisible = false
}.catch { error in
    promise.resolver.reject(error)
}

return promise.promise
```

It always shows me the error when I put 2 lines in the firstly. If I remove the first line, it's ok. Please show me my issue if I missing something.

Thanks!

**Comment by mxcl** [comment]
Impossible to help since you don't say what the error is or which line it happens on.

**Comment by mxcl** [comment]
Like at the very least your code is identical to the much shorter:

```swift
UIApplication.shared.isNetworkActivityIndicatorVisible = true

return firstly {
    getIPNumbers(withAPI: .incomingPhoneNumber)
}.ensure {
    UIApplication.shared.isNetworkActivityIndicatorVisible = false
}
```

**Comment by chrisnguyens** [comment]
Hi mxcl,

Thanks for your response.
```
firstly{
    UIApplication.shared.isNetworkActivityIndicatorVisible = true
    return getIPNumbers(withAPI: .incomingPhoneNumber)
}
```

Got the error at the return.

**Comment by mxcl** [comment]
Specify the return type or do what I did in my above example where I make the firstly one line.

**Comment by chrisnguyens** [comment]
Yes, because of it could be 2 line in the firstly with the previous version and I still see in your doc, we could put 2 lines. Thanks for your help.
