### ISSUE TITLE
Recover still results in catch in the chain even after fulfilling the recover

### ISSUE THREAD

**Issue by Can-Sahin** [mxcl/PromiseKit#808]
Currently on 6.2.1 and there is a weird behaviour I'am struggling with recover and catch combination

Normally recover works fine when you create the promise and .recover it immediately at the same line. But when you do it in the next line (by referring to the promise) it runs, but the main chain still results in `catch` block. Is this a bug? (It should be a bug in my opinion, there is no reason to do this intentionally) 

Working example. `done` block is executed as its expected
  ``` swift
 func testFunction(){
        let p = createPromise()
        p.done{ result in
            print("Result: " + result) 
        }.catch{error in
            print("ErrorResult: " + error.localizedDescription)
        }
    }
    func createPromise() -> Promise<String>{
        let p = Promise<String> {seal in
            after(seconds: 1).done {
                seal.reject(CustomError.Unauthorized)
            }
        }.recover{error -> Promise<String> in
            print("Error: " + error.localizedDescription)
            return Promise.value("Recover")
        }
        return p
    }
```

But when you change the `createPromise` function to this (moving the recover next line). It goes to catch `block`. Notice the difference
```swift
    func createPromise() -> Promise<String>{
        let p = Promise<String> {seal in
            after(seconds: 1).done {
                seal.reject(CustomError.Unauthorized)
            }
        }
        // assigning recover here instead
        p.recover{error -> Promise<String> in
            print("Error: " + error.localizedDescription)
            return Promise.value("Recover")
        }
        return p
    }
```

**Comment by nathanhosselton** [comment]
```swift
// assigning recover here instead
p.recover{ … }
return p
```
This creates a new promise and that's not the promise you're returning. You should even be receiving a warning indicating such (`Result of call to 'recover' is unused`).

Instead, you should be returning the result of `p.recover{ … }`:

```swift
return p.recover{ … }
```

**Comment by mxcl** [comment]
Yes, this is expected behavior.

You returned the chain before it `recover`s.

**Comment by mxcl** [comment]
If you have any insights about why you thought this would work we can update our docs to help others avoid this situation.

**Comment by Can-Sahin** [comment]
Of course. My bad late at this night. The reason is simply the 'chain' word I read many times while reading migration guide. I guess it made me believe that everything you do on a promise adds something to the chain.. Its been couple months of break to this library and now I am back. Kinda forgot how it works. But 100% my bad. Thanks
