### ISSUE TITLE
The new catch method is not good enough (?)

### ISSUE THREAD

**Issue by knguyen2708** [mxcl/PromiseKit#816]
I often used the following pattern in the older version:

```
func executeJob() -> Promise<Void> {
  request()
  .done {
     // Do something
  }.catch { e in
     // Schedule a local push notification, etc
  }
}
```

Basically I "tapped" the error and process it, but I still wanted it to be passed back to whatever that called `executeJob` (thing like logging, or scheduling push notifications really belongs to `executeJob`, not its caller).

This pattern is no longer possible with PMK 6.0. An alternative is to use the `tap` function, but it seems to be designed for debugging purpose -- e.g. it executes async and I have to do stuff like `guard case .rejected(let error) = result else { return }`.

I understand the reasons why `catch` has been changed, but how I can produce the same effects in PMK 6.0?

**Comment by mxcl** [comment]
Use `recover`.

**Comment by mxcl** [comment]
I feel I must ask, what situations are you doing something but only for an error condition? It suggests misuage.

**Comment by knguyen2708** [comment]
Thanks @mxcl. It does solve my problem.

Not sure if I understand what you asked... My use case is: I have jobs (which are basically network requests). These are initiated by users and may complete or fail. Push notifications are used in both cases to notify users. These jobs are managed by a manager so that they can be retried later if they fail. It is this manager that processes the errors further, e.g. saving error messages so that they can be displayed later, or when the app restarts.

I guess my issue comes down to responsibility separation between components: a component may want to do something (most likely logging, or push notification in my case) when an error happens, but still want to pass it along the chain.
