### ISSUE TITLE
Recover with a promise

### ISSUE THREAD

**Issue by lanephillips** [mxcl/PromiseKit#817]
I'd like to do something like this:

```
firstly {
    // try to request from the web, which could fail
}.recover { error in
    // try instead to load from disk, which also could fail
}.done { json in
    // process results
}.catch {
    // handle error
}
```

but I guess this is not possible because recover has to return a Guarantee.

**Comment by mxcl** [comment]
> but I guess this is not possible because recover has to return a Guarantee.

This is untrue, what you want to do is possible. LMK if I can help.

**Comment by lanephillips** [comment]
Okay, my problem was solved by explicitly declaring the return type of my recover block:
```
firstly {
    // try to request from the web, which could fail
}.recover { error -> Promise<Any> in
    // try instead to load from disk, which also could fail
}.done { json in
    // process results
}.catch {
    // handle error
}
```

**Comment by mxcl** [comment]
Yes, this is the main suggestion in our [Troubleshooting](https://github.com/mxcl/PromiseKit/blob/master/Documentation/Troubleshooting.md) guide.
