### ISSUE TITLE
why offer PMKRace interface while not offer implementation 

### ISSUE THREAD

**Issue by SuperMarioBean** [mxcl/PromiseKit#818]
After pod install, I found the new release offer the `PMKRace` interface in `fwd.h`, however there is no `race.m` file. 
so I clone the repo, I found in `sources` fold there indeed has a `race.m`, then I check the podspec:

```ruby
cc << 'Sources/{after,AnyPromise,GlobalState,dispatch_promise,hang,join,PMKPromise,when}.m'
``` 

a missing a file named `race.m`?

**Comment by mxcl** [comment]
This is an omission.

I am assuming you are talking about PromiseKit 6, since you didn't specify even though the issue template asked for.

**Comment by mxcl** [comment]
a37e91a0fa3c6b2b01d8a65918aa661cc348081e

Will be available on CocoaPods in ~30 minutes. Provided the `trunk push` lint succeeds.

**Comment by mxcl** [comment]
Live.
