### ISSUE TITLE
Is there a plan to support swift static library?

### ISSUE THREAD

**Issue by 0xwangbo** [mxcl/PromiseKit#819]
If your issue is a Swift compile issue then read our Troubleshooting guide first:

    https://github.com/mxcl/PromiseKit/blob/master/Documentation/Troubleshooting.md

---    

In your ticket PLEASE specify the PromiseKit version (major version is enough).

---

Please format your code in triple backticks and ensure readable indentation:

     https://help.github.com/articles/creating-and-highlighting-code-blocks/
-------

Is there a plan to support swift static library?
http://blog.cocoapods.org/CocoaPods-1.4.0/

**Comment by mxcl** [comment]
The documentation that CocoaPods is not clear but to me it looks like I have to make PromiseKit either static or dynamic with no choice to the end-user, thus no, we cannot become static, it makes us much less useful to everyone.

If you want static, use Carthage or SwiftPM, which both alllow the end-user to choose how their libraries are packaged.

**Comment by 0xwangbo** [comment]
I tested it. If .podspec has s.static_framework = true and the user declares use_frameworks! in the Podfile, it will get xxx.framework. If you don't declare use_frameworks!, you will get xxx.a

Declaring s.static_framework = true in the .podspec does not directly determine the final output, but depends on the user. right? Looking forward to your reply @mxcl

**Comment by mxcl** [comment]
I see, well if there is documentation or some kind of information on the Internet that guarantees this, then I'll do it. Otherwise I cannot risk >1M installs with this change of metadata.

**Comment by mxcl** [comment]
Thanks for the info @nolanw and don't apologize; you helped!
