### ISSUE TITLE
PromiseKit for android?

### ISSUE THREAD

**Issue by john1452** [mxcl/PromiseKit#820]
Hi There, first of all thank you so much for this amazing library I absolutely love it!  

I have a question regarding the FAQ:

Do you want to be able to use Promises with Swift 3.x, Swift 4.x, ObjC, iOS, tvOS, watchOS, macOS, Android & Linux? Then pick PromiseKit.

As per the FAQ above, Is there a Android version of this library? i
I really want to use it for android as well. If not, can you please recommend a alternative android library that has similar patterns?

**Comment by mxcl** [comment]
To use PromiseKit with Android use SwiftPM.

**Comment by john1452** [comment]
Hi @mxcl thanks for responding. I am just trying to understand how it is technically possibly to use promiseKit with android. promiseKit kit is written in swift and android is a totally different echo system which uses java or kotlin. Does SwiftPM compile promiseKit to java or kotlin?

**Comment by mxcl** [comment]
No, it is Swift. You can use Swift on Android since a while, you can google it. Thanks.

**Comment by huntj88** [comment]
There is a kotlin port of this library that was just released by InMotion software.
https://github.com/inmotionsoftware/promisekt

@mxcl if possible we would like to work with you to try and keep parity between your swift version and the kotlin port

**Comment by mxcl** [comment]
@huntj88 happily accept the PRs and have this be in the official repo for sure!
