### ISSUE TITLE
Function `ensure` is not defined on PMKFinalizer, what happens to order?

### ISSUE THREAD

**Issue by colinta** [mxcl/PromiseKit#822]
PromiseKit 6.2.3

I like the changes to the API, despite there being a lot to make - gotta do what's right.

But this one is making me pause:

```swift
// turns off some stuff
postNotification(NewContentNotifications.pause, value: ())

service.create(content: content)
    .done { post in
        // this needs to finish before NewContentNotification.resume is posted
        self.emitSuccess(post)
    }
    .catch { error in
        self.stopSpinner()
        self.contentCreationFailed(error)
    }
    .ensure {  // Value of type PMKFinalizer has no member 'ensure'
        // this turns the stuff back on
        postNotification(NewContentNotifications.resume, value: ())
    }
```

I haven't looked at the code, maybe it's possible to hack `ensure` onto PMKFinalizer, but I wanted to know what you thought of this situation.

In other places I've just moved `ensure` above `catch`, but it looks funny to have them in that order.

**Comment by colinta** [comment]
Oh and I was surprised that the return signature of `Guarantee<T>.pending()` is `(Guarantee<T>, (T) -> Void)`, I expected `(Guarantee<T>, Resolver<T>)`.

**Comment by mxcl** [comment]
I don't understand your main question. You can call `finally` on `catch` that's it.

`Guarantee` doesn't provide a resolver because it cannot error, `Resolver` provides functions that take work for completion handlers that error.

**Comment by colinta** [comment]
Oh yeah I kinda forgot to ask the question (how can I use `ensure` but have the order of operations as I need to have it), but `finally` is the method I was searching for, thanks.

I wasn't trying to criticize, just sharing my upgrade experience.  First I switched all my `let (promise, fulfill, reject)` to `let (promise, seal)`, then when I switched to using `Guarantee` I had to revert to `let (guarantee, fulfill)`, and that surprised me, I expected `Guarantee.pending` and `Promise.pending` to have similar return types.  But they don't!  No worries.  Thanks as always!

**Comment by mxcl** [comment]
> I wasn't trying to criticize, just sharing my upgrade experience. First I switched all my let (promise, fulfill, reject) to let (promise, seal), then when I switched to using Guarantee I had to revert to let (guarantee, fulfill), and that surprised me, I expected Guarantee.pending and Promise.pending to have similar return types. But they don't! No worries. Thanks as always!

np, I didn't take anything personally. I'm just saying: it's logically impossible to have Guarantee take a `Resolver`, so I can't really do anything to aid people's migrations there.

**Comment by colinta** [comment]
Yes, actually I was thinking it would return something other than a resolver, but you would still call `resolve` on it, so the API would line up... now that I say it out loud it's a bit silly.

I'm on gitter now, btw, typing another question...
