### ISSUE TITLE
[objc] Generic type annotation for PMKPromise

### ISSUE THREAD

**Issue by theodelrieu** [mxcl/PromiseKit#833]
Hello,

I'm using PromiseKit v1.7.6, and I have `PMKPromise*` everywhere in my APIs.

Users must rely on the documentation to know what is the type of the promise.

I would really like to have:

```objc
- (nonnull PMKPromise<NSString*>*)foo;
```

I don't know if this is implementable for types that are not `NSArray/NSString` etc...

But if it's possible that would bring a lot of clarity in APIs. Also, adding that to `AnyPromise` might help Swift users too.

What do you think?

**Comment by mxcl** [comment]
I expect it can be done, but I do not have experience with it. PR welcome.

**Comment by theodelrieu** [comment]
I won't be available for two weeks, but I'll try to do that after.

**Comment by mxcl** [comment]
Closing since this is a feature-request, the PR is welcome but I do not leave feature requests open, the tracker is for bugs.
