### ISSUE TITLE
Migration to 6.0

### ISSUE THREAD

**Issue by laxmorek** [mxcl/PromiseKit#835]
I have an problem with migration to 6.0. Here is my question form StackOverflow:
https://stackoverflow.com/questions/49811888/promisekit-6-0-migration

If it is not a good place for this link please delete it or give me an info, I will do it.

PS. I love this lib, very nice and good job guys.

**Comment by mxcl** [comment]
Use `.value` this is detailed in our migration guide which I recommend reading: http://promisekit.org/news/2018/02/PromiseKit-6.0-Released/

**Comment by laxmorek** [comment]
It generates: “Cannot convert return expression of type 'Promise<_.T>' to return type 'Promise<[JSON]>'” error message :/

**Comment by mxcl** [comment]
This means you are returning the wrong type

**Comment by mxcl** [comment]
Try splitting out the function, like our Troubleshooting Guide recommends:

```swift
func fetchSettings(forAnimalsGuids animalsGuids: [String]) -> Promise<[JSON]> {
    let packageSize = 100
    let animalsPackages = animalsGuids.chunked(chunkSize: packageSize)

    func fetch(_ animalsPackage: Foo) -> Promise<[JSON]> {
        let predicates = animalsPackage.map { .atomic(.equal("Animal.ObjectGuid", .string($0))) }
        let predicate = !predicates.isEmpty ? .or(predicates) : nil
        return gatewayConnector.fetchObjects(type: AnimalMilkSetting.self, predicate: predicate)
    }

    return firstly {
        when(fulfilled: animalsPackages.map(fetch)
    }.map {
        Array($0.joined())
    }
}
```
