### ISSUE TITLE
Migration to 6.0 - Passing Errors

### ISSUE THREAD

**Issue by laxmorek** [mxcl/PromiseKit#836]
My another problem with migration to 6.0

StackOverflow's question:
https://stackoverflow.com/questions/49813133/promisekit-6-0-passing-catched-errors-to-caller

And again:
If it is not a good place for this link please delete it or give me an info, I will do it.

Tnx for any advice.

**Comment by mxcl** [comment]
```
let p = Promise()
p.catch {
    //…
}
return p
```
