### ISSUE TITLE
"_PMKRace", referenced from:

### ISSUE THREAD

**Issue by fabcz** [mxcl/PromiseKit#837]
PromiseKit version: 6.2.1
Xcode version: 9.3 (9E145)

ObjC support PMKRace？
PMKWhen，PMKJoin is work for me，but when i user PMKRace it will throw error like that
![image](https://user-images.githubusercontent.com/18094291/38935334-b012dcec-4350-11e8-9e98-cc133366fab2.png)

here is my code
`
    
    PMKJoin(@[[self commissionRequest],[self adminEntryRequest]])
    .then(^(id request){
        YBLog(@"2、JoinRequest：%@",request)
    })
    .catch(^(NSError *err){
        YBLog(@"JoinErr:%@",err)
    });
    
    PMKWhen(@[[self adminEntryRequest],[self commissionRequest]])
    .then(^(id request){
        YBLog(@"1、WhenRequest：%@",request)
    })
    .catch(^(NSError *err){
        YBLog(@"WhenErr:%@",err)
    });

    PMKRace(@[[self commissionRequest],[self adminEntryRequest]])
    .then(^(id request){
        YBLog(@"3、RaceRequest：%@",request)
    })
    .catch(^(NSError *err){
        YBLog(@"RaceErr:%@",err)
    });`

**Comment by mxcl** [comment]
Update, this was fixed in 6.2.2

**Comment by fabcz** [comment]
same problem in 6.2.2
but 6.2.3 is OK
