### ISSUE TITLE
PromiseKit 6 Polling

### ISSUE THREAD

**Issue by igorvoytovich** [mxcl/PromiseKit#844]
Hello! What is best practice for polling in PromiseKit 6? Thank you!
For example if I need to make some request every N seconds.

**Comment by mxcl** [comment]
```swift
func poll() -> Guarantee<Void> {
   task()
   return after(.seconds(N)).done(poll)
}
```

Further reading:

* https://github.com/mxcl/PromiseKit/issues/594
* https://github.com/mxcl/PromiseKit/issues/387
* https://github.com/mxcl/PromiseKit/issues/659

**Comment by igorvoytovich** [comment]
@mxcl Ty so much! But is there any more general solution? For example where I can specify delay and function and pass them as parameters

**Comment by mxcl** [comment]
```swift
func poll(seconds N: Int, task: () -> Void) -> Guarantee<Void> {
   task()
   return after(.seconds(N)).then(poll)
}
```

**Comment by mxcl** [comment]
Probably you need task to return `Promise`, you weren't specific.

```swift
func poll(seconds N: Int, task: () -> Promise<Void>) -> Promise<Void> {
   return task().then{ after(.seconds(N) }.then(poll)
}
```

**Comment by mxcl** [comment]
Please refer to the other issues I already highlighted, I literally copy and pasted from them.
