### ISSUE TITLE
Is there a way to both fulfill and reject a promise and then handle both?

### ISSUE THREAD

**Issue by bryan1anderson** [mxcl/PromiseKit#845]
PromiseKit (6.2.5)

There are cases that my API will return user facing error messages during successful responses. These responses are included in the JSON in addition to the successful JSON response I normally need to parse.

I'd like to remove the Error JSON from the response, fulfill the promise using the successful JSON, and then catch the error created from the Error JSON.

Right now, if I fulfill the JSON, then the promise catch closure is never hit. 

Here is my example:

```
return Promise<JSON> { seal in

//Alamofire request is made
            _ = defaultManager.request(url, method: method, parameters: params, headers: headers).responseJSON { (response) in
                do {
                    guard let data = response.data else { throw DataError.failed(response) }
                    let json = try JSON(data: data)
                    seal.fulfill(json)
                    let jsonError = JSONError(json: json)
                    seal.reject(jsonError)
                }
                catch {
                    seal.reject(error)
                }
            }
        }
```

So I make the request. I want to parse the successful JSON response in addition to handling the error created from the JSON.

```
        APIPosts.getPosts(id: 2).done { (json) in
           //HANDLE THIS Separately from the Error
            print(json)
            }.catch { (error) in
                //ALSO HANDLE THIS, but separately from the success 
                print(error)
        }
```

**Comment by mxcl** [comment]
This is impossible with promises, they either fail or succeed. You will need to carry the error-message through the chain separately presumably with a custom object.
