### ISSUE TITLE
fullfill with void

### ISSUE THREAD

**Issue by superandrew** [mxcl/PromiseKit#846]
When I create a promise, probably because I am doing something wrong, I am forced to call fullfill(()) passing a Void inside the fullfillment, not sure why.

    func checkBackend()-> Promise<Void>{
        
        return Promise{fullfill, reject in
           
            fullfill(())     
                
            }) { (code, error) in
               
                reject(error)
            }
            
            
            
        }
      }

Otherwise it won't compile. Is there any obvious mistake or is it a bug?

Thanks

**Comment by mxcl** [comment]
This is what Swift 4 requires. We have discussed this previously:

* #763
* #697

We also document the fix and talk about the problem in our [Troubleshooting Guide](https://github.com/mxcl/PromiseKit/blob/master/Documentation/Troubleshooting.md)

**Comment by superandrew** [comment]
sorry then. In my defense I only can say that I searched for this, but probably wasn't good enough. Maybe adding it in the readme would help other people, what do you think?

Thanks a lot

**Comment by mxcl** [comment]
I can't add everything to the README, it's already pretty full.
