### ISSUE TITLE
Compile errors after installing PromiseKit

### ISSUE THREAD

**Issue by aeguss** [mxcl/PromiseKit#847]
Version: PromiseKit 6.0

After installing PromiseKit ever time I try to compile, I get errors in the framework files. 
<img width="1440" alt="screen shot 2018-04-30 at 6 23 36 pm" src="https://user-images.githubusercontent.com/31681864/39456505-0b9ee310-4ca4-11e8-823e-833309b150f9.png">

This is after deleting a project, and starting a new one and installing the pod then trying to compile. It doesn't compile at all. 

I haven't even tried to right any code using promises as it won't recognize in autotype or even the types.

**Comment by nathanhosselton** [comment]
You are using an older version of PromiseKit. We are currently at 6.2.5, with numerous fixes and improvements in between. I recommend upgrading.

You likely either specified 6.0.0 in your Podfile, or you need to `pod update`.

If you're still experiencing errors after upgrading I'll help you debug.

**Comment by aeguss** [comment]
Thank you, that worked! It would be worth changing the readme.md, because it states to use 6.0, not the latest one. That is what I followed. Thanks again,

**Comment by mxcl** [comment]
The README specifies ~> 6.0 which means the latest version of version 6. So the README is correct.
