### ISSUE TITLE
Act upon error without doubling up promises

### ISSUE THREAD

**Issue by pimnijman** [mxcl/PromiseKit#849]
PromiseKit 6.2.5

I've read about [doubling up promises](https://github.com/mxcl/PromiseKit/blob/master/Documentation/Appendix.md#doubling-up-promises) and I see why that should be avoided.

But here's my issue: I'd like to act upon an error before it gets send up to the calling object.
Here's how I've achieved this now:

```
func register(facebookAccessToken: String) -> Promise<Void> {
	return Promise { seal in
		firstly {
			service.registerUser(facebookAccessToken: facebookAccessToken)
		}.map { accessToken in
			self.storeAccessToken(accessToken) // returns Void
		}.then {
			self.updateAuthenticatedUser() // returns Promise
		}.done {
			NotificationCenter.default.post(Notification(name: .userAuthenticated, object: self))
			seal.fulfill(())
		}.catch { error in
			self.discardAccessToken()
			seal.reject(error)
		}
	}
}
```

Is there a way I can achieve the same without "doubling up promises"?

Also, I'd like to know if I used map (5th line) in the way that was intended, since I'm not returning anything from that method.

**Comment by nathanhosselton** [comment]
Does `service.registerUser` return a promise? It looks like it probably does since there’s no completion on it. In which case the wrapping `Promise { seal in … }` is unnecessary and would constitute doubling up. You could simply `return firstly { …`.

Otherwise this looks good to me!

Though if for whatever reason you needed the token again in your `then` you could use `tap` in place of `map`.

**Comment by pimnijman** [comment]
@nathanhosselton `service.registerUser` returns `Promise<String>`.
When I omit `return Promise { seal in` and return `firstly` I get the following error:
```
Cannot convert return expression of type 'PMKFinalizer' to return type 'Promise<Void>'
```
To me this indicates that I cannot use `catch`when I return `firstly`.

**Comment by nathanhosselton** [comment]
Apologies, I haven't written this pattern recently and it appears that it has in fact changed due to `catch` returning `PMKFinalizer` which cannot be chained with another `catch`.

For the moment at least, you could do this instead which accomplishes the same though a little less succinctly:

```swift
func register(facebookAccessToken: String) -> Promise<Void> {
    let promise = firstly {
        service.registerUser(facebookAccessToken: facebookAccessToken)
    }.map { accessToken in
        self.storeAccessToken(accessToken) // returns Void
    }.then {
        self.updateAuthenticatedUser() // returns Promise
    }.done {
        NotificationCenter.default.post(Notification(name: .userAuthenticated, object: self))
    }

    promise.catch { error in
        self.discardAccessToken()
    }

    return promise
}

//elsewhere
register(facebookAccessToken: token).catch { error in
    //this catch will get called as well
}
```

**Comment by nathanhosselton** [comment]
Ah, in fact this is in our [migration guide](https://promisekit.org/news/2018/02/PromiseKit-6.0-Released/) even (scroll to the bottom). And the above is the given solution for catching before and after the return.

**Comment by nathanhosselton** [comment]
Alternatively, you could check the status of the chain with `tap` and perform your failure cleanup there instead of in a catch:

```swift
return firstly {
    service.registerUser(facebookAccessToken: facebookAccessToken)
}.map { accessToken in
    self.storeAccessToken(accessToken) // returns Void
}.then {
    self.updateAuthenticatedUser() // returns Promise
}.tap { result in
    if case .rejected = result { 
        self.discardAccessToken()
    }
}.done {
    NotificationCenter.default.post(Notification(name: .userAuthenticated, object: self))
}
```

**Comment by pimnijman** [comment]
Thank you @nathanhosselton. I personally prefer the first solution. I love that I no longer need the double promises.

**Comment by mxcl** [comment]
We should add this to doubling promised entry. It’s stumped a few for sure.
