### ISSUE TITLE
How to report progress in a single task?

### ISSUE THREAD

**Issue by alexlee002** [mxcl/PromiseKit#851]
eg, If I download a big file from server,  How to report the progress in promise?

**Comment by samrayner** [comment]
The concept of Promises doesn't really determine how you should report progress. The promise will be pending until the download completes, resolving the promise.

Check out PromiseKit's URLSession extension:
https://github.com/PromiseKit/Foundation/blob/a6b1a30ec9f326b2485f1383fadc02b158de00dd/Sources/NSURLSession%2BPromise.swift

URLSession offers this delegate method to track progress:
https://developer.apple.com/documentation/foundation/urlsessiondownloaddelegate/1409408-urlsession

Alternatively you could pass a Progress object into your method and update it periodically.
https://developer.apple.com/documentation/foundation/progress

**Comment by mxcl** [comment]
Sorry, this is outside the bounds of PromiseKit, you will need to research how to use NSProgress:

https://www.google.com/search?client=safari&rls=en&q=urlsession+nsprogress&ie=UTF-8&oe=UTF-8

**Comment by mxcl** [comment]
NSProgress already supports progress and you can use it to monitor the progress of your URLSession, so we don't intend to add this feature. Thanks.
