### ISSUE TITLE
How can I know which promises is failed in .catch?

### ISSUE THREAD

**Issue by Banck** [mxcl/PromiseKit#854]
Hello! I have 2 promises, which have to execute one by one.
First I need to upload images on server, then I need to update user info (not in a row).
So I wrote this code:

```
        firstly {
            ProfileManager.uploadImages(photos)
        }
        .then { (photos)  in
            ProfileManager.updateProfile(name, bio: bio ?? "", birthdayDate: birthdayDate ?? "")
        }
        .done { (result) in
                self.view?.showAlert(title: nil, message: "Данные успешно изменены")
        }
        .catch { (error) in
                print() // how can I know uploadImages or  updateProfile was failed??
        }
        .finally {
                        self.view?.stopLoading()
                }

```
how can I know in the .catch section uploadImages or  updateProfile was failed??

And if I want to do something with "photos", which uploadImages returned , I need to write .done section before .then, right?

As I understand I need to write `(photos)  in` in .then section, but I can't do anything with this variable.

**Comment by Banck** [comment]
I can do nothing with photos in then, there is error then:
![image](https://user-images.githubusercontent.com/6259254/39930397-cb000f0e-5564-11e8-8cae-87e20610343f.png)

**Comment by nathanhosselton** [comment]
Swift can’t infer the return type of closures with 2+ lines. You’ll have to specify the type of promise you’re returning from the closure.

**Comment by Banck** [comment]
Ok, thanks!

But I thought, that there is something like `when(fullfiled)` when I can get each promises .
Thought that in `.done` I can get all of previous completed results 
And that `.catch` will return promise which failed.

Or that I can write something like that:

```
 firstly {
            ProfileManager.uploadImages(photos)
        }
        .catch { (error) in
                print() // error for photos
        }
        .then { (photos)  in
            ProfileManager.updateProfile(name, bio: bio ?? "", birthdayDate: birthdayDate ?? "")
        }
        .done { (result) in
                self.view?.showAlert(title: nil, message: "Данные успешно изменены")
        }
        .catch { (error) in
                print() // error for profile
        }
        .finally {
                        self.view?.stopLoading()
                }
```
So thanks for your help, I think all is fine now..

**Comment by nathanhosselton** [comment]
We do have `when` which behaves as you describe. Though I assumed that you wouldn’t want to update he profile until after the photos upload. If you want to do them at the same time, then `when` is what you want, and the following closure will contain the results of each of the promises passed in.

You can’t chain anything after a `catch` except for a `finally`. A catch will get called for any promise the errors prior in the chain. It’s up to you to determine which promise failed via the error object. This is a feature of promises. It reduces your error handling to a single place. Though there are alternatives when you really them.

`done` does not in fact contain the results of all prior promises in the chain as you describe. We don’t have a method for that. Though it sounds like `when` will fit the bill for you in this case.

**Comment by Banck** [comment]
I meant, that it’s cool that in .when i can get each promises. 
Nevermind) anyway than you so much)
