### ISSUE TITLE
CancellablePromise (was: Define Promise class as "open")

### ISSUE THREAD

**Issue by johannesd** [mxcl/PromiseKit#855]
Hi, I was thinking about creating a subclass of Promise that has some additional functions (like cancelation). This is not possible however since Promise is defined as "public". Is there any chance that you change that to "open"?

Since I'm using AwaitKit, I would like to keep the clean syntax without cancelation:
`let result = try await(makeNetworkRequest())`

and 

`let request = makeNetworkRequest()`
`let result = try await(request)`
`// Some place else:`
`request.cancel()`

Instead of having my network function return a tuple:
`let result = try await(makeNetworkRequest().promise)`

respectively

`let request = makeNetworkRequest()`
`let result = try await(request.promise)`
`// Some place else:`
`request.cancel.cancel()`

I can only achieve that with a subclass.

**Comment by mxcl** [comment]
Basically I removed `open` because things often don’t behave as you like when chaining, where you return your subclass in a chain and then out the other end pops good 'ol `Promise`, so you only have a very specific time where your subclass exists, which for most people is confusing.

I could add it back, there's nothing dangerous (I can foresee) about allowing it. But will it actually be as useful to you as you think?

**Comment by johannesd** [comment]
You're making a good point – maintaining the class while chaining would be essential for my needs...

**Comment by mxcl** [comment]
Originally I tried to make it so the chains returned `Self` but Swift is difficult about this, maybe with Swift 4.1 it is now possible…

**Comment by johannesd** [comment]
I've implemented my `CancelablePromise` now as an independent class that conforms to `Thenable` and adds a `cancel` function. Calling `then` on an instance returns an ordinary `Promise`, which is fine because this promise does not support cancelation. I could overload `then` to return a `CancelablePromise`. When calling `cancel` on that instance, it would have to propate to the preceeding promise(s) to cancel that one / those as well. 

`let a = CancelablePromise(...)`
`let b = CancelablePromise(...)`
`let c = a.then(b)`
`c.cancel() // Should call cancel on a and b`

Is there already a mechanism in PromiseKit that I could use for that? I think it's similar to rejecting a promise which somehow finds the `catch` handler in the chain. However, this would have to run in the opposite direction.

Furthermore, I'm thinking about calling `cancel` automatically when using `CancelablePromise`s in a `race`. After one promise has resolved, the other ones would then be cancelled. 

`let a = CancelablePromise(...)`
`let b = CancelablePromise(...)`
`let c = race([a, b])`
`// when a fulfills, b should be cancelled`

For that, I would overload `race(cancelablePromises: [CancelablePromise])`, call the original `race(thenables: [Thenables])` in it,  analyse which promise has fulfilled and call  `cancel` on the other ones. Is that correct? Or is there any function already called on the loosing promises in the `race` call, that I could overwrite?

Thank you for your help!

**Comment by johannesd** [comment]
I have put a little lib together, maybe it is useful to somebody: https://github.com/johannesd/CancellablePromiseKit

It provides a `CancellablePromise` that has a `cancel()` function. It also adds overloads for `when` and `race` that can automatically cancel the promises did not finish in time.

Would be nice to hear what you think about it. And thanks for PromiseKit!

**Comment by mxcl** [comment]
Want to add a link to this in our cancellation documentation?

**Comment by johannesd** [comment]
That would be an honor ;-)
