### ISSUE TITLE
Problem with archiving version 3.5.0 on xcode 7.3.1

### ISSUE THREAD

**Issue by muratyasarr** [mxcl/PromiseKit#857]
I successfully build and launch my app on the simulator but when I try to upload the app to the app store, I cannot archive the app. I have been trying to solve this issue for a week, nothing worked up to now :/ 

Can you please help? 

![image](https://user-images.githubusercontent.com/5808346/40079634-33e897d2-5891-11e8-889e-a076fdd2725e.png)

![image](https://user-images.githubusercontent.com/5808346/40079739-8330aae6-5891-11e8-8b17-e5f84a87d5d1.png)

**Comment by mxcl** [comment]
Dupes #660. We have no solution, it's a Swift bug. You have to upgrade PromiseKit. v4 is not much different.

**Comment by muratyasarr** [comment]
Does v4 support Swift 2.3?

**Comment by muratyasarr** [comment]
Ok removing the UIKit resolves the issue for now. Thanks a lot for the help! 👍
