### ISSUE TITLE
Promises are executed immediately after creation

### ISSUE THREAD

**Issue by Igor-Palaguta** [mxcl/PromiseKit#868]
Hello,

Is there any way to make lazy promise. To start execution just when someone subscribed to it? Like hot/cold in ReactiveCocoa.

Thanks

**Comment by mxcl** [comment]
func makePromise() -> Promise<Foo> {
    return Promise {
        //…
    }
}

**Comment by mxcl** [comment]
If you need a lazy promise, use the `lazy` keyword. If you need a new promise every time you call a function, make it a function like in my example above.

Your test is a normal way of creating a promise, and the closure you pass is always executed immediately.

**Comment by Igor-Palaguta** [comment]
I see. Thank you for clarification!

**Comment by mxcl** [comment]
Closing but re-open if your question is still not answered.
