### ISSUE TITLE
PromiseKit Framework - Ambiguous reference to member 'then()'

### ISSUE THREAD

**Issue by guidupas** [mxcl/PromiseKit#869]
I am using a PromiseKit framework version 1.7.7 (I need to use this version due another framework that needs it). I tried to found the problem in the troubleshooting document but I couldn't find it.

So, in this framework that uses the PromiseKit framework has this method:

    - (PMKPromise *)paymentTokenForCreditCard:(GNCreditCard *)creditCard {
        NSDictionary *cardDict = [creditCard paramsDicionary];
        NSString *jsonCard = [self getJSONStringFromDictionary:cardDict];
        
        return [self encryptData:jsonCard]
        .then(^(NSString *encryptedData){
            NSDictionary *params = @{@"data":encryptedData};
            return [self request:kGNApiRouteSaveCard method:@"POST" params:params];
        })
        .then(^(NSDictionary *response){
            return [[GNPaymentToken alloc] initWithDictionary:response];
        });
    }

And it shows this example on how to use it:

    GNConfig *gnConfig = [[GNConfig alloc] initWithAccountCode:@"YOUR_ACCOUNT_CODE" sandbox:YES];

    GNApiEndpoints *gnApi = [[GNApiEndpoints alloc] initWithConfig:gnConfig];

    GNCreditCard *creditCard = [[GNCreditCard alloc] init];
    creditCard.number = @"4012001038443335";
    creditCard.brand = kGNMethodBrandVisa;
    creditCard.expirationMonth = @"05";
    creditCard.expirationYear = @"2018";
    creditCard.cvv = @"123";
    
    [gnApi paymentTokenForCreditCard:creditCard]
    .then(^(GNPaymentToken *paymentToken){
    NSLog(@"%@", paymentToken.token);
    })
    .catch(^(GNError *error){
    NSLog(@"An error occurred: %@", error.message);
    });

Well, how I am using Swift instead of Object-C, I am trying to use it this way:

    let gnConfig = GNConfig(accountCode: "3f62976bea79971730b67cd62806c256", sandbox: true)
    let gnEndpoints = GNApiEndpoints(config: gnConfig)
        
    let gnCreditCard: GNCreditCard! = GNCreditCard(number: "4012001038443335", brand: kGNMethodBrandVisa, expirationMonth: "05", expirationYear: "2018", cvv: "123")
        
    gnEndpoints?.paymentToken(for: gnCreditCard).then({ tokenPagamento in
        if let aToken = tokenPagamento?.token {
            print("\(aToken)")
        }
    }).catch({ error in
        if let aMessage = error?.message {
            print("An error occurred: \(aMessage)")
        }
    })

And it is showing me this error:

> Ambiguous reference to member 'then()'

I also tried:

    gnEndpoints?.paymentToken(for: gnCreditCard).then{ tokenPagamento: GNPaymentToken in
            if let aToken = tokenPagamento?.token {
                print("\(aToken)")
            }
        }.catch{ error in
            if let aMessage = error?.message {
                print("An error occurred: \(aMessage)")
            }
        }

Ant it brings me the error:
> Cannot invoke 'then' with an argument list of type '(() -> ())'

Another approach was download the versions 2.0.0 and 2.2.2 using Carthage but as they were built using an old Swift version, Carthage could not build it. So I downloaded the framework directly from the Github but it didn't work either again because of the Swift version.

How could I fix it?

**Comment by mxcl** [comment]
There's existing tickets that show how to do this, I am going to say go find them because I cannot remember exactly what you have to do, it comes down to the way we return a block to a block in objc, so you have to double unwrap to use them from Swift.

Basically, we do not recommend using Swift with PMK 1.x. Upgrade.

**Comment by guidupas** [comment]
Solved using this code

```
gnEndpoints?.paymentToken(for: gnCreditCard).then({ token -> () in
            if let token = token as? GNPaymentToken {
                print(token)
            }
        }, { (error) -> () in
            // catch your error
        })
```

**Comment by mxcl** [comment]
K glad you found a solution.
