### ISSUE TITLE
Mapping values in a guarantee with array

### ISSUE THREAD

**Issue by drekka** [mxcl/PromiseKit#870]
Here's a very simple example of what I'm trying to do (PK6).

    // Function that does some asynchronous stuff and returns a guarantee.
    func do1(_ with:Int) -> Guarantee<Int> { ... }
    func do2(_ with:Int) -> Guarantee<Int> { ... }

    Guarantee<Int>.value([1, 2, 3])
    .thenMap(self.do1)
    .thenMap(self.do2).asVoid()
    .done { ... }

The problem seems to be that I need to use `thenMap` to call `do1()` and `do2()` on each value in the array, but it returns a promise which causes the done to expect a catch. All my functions return guarantees so I want to be able to call them without converting to promises.

So my question is there another way to do this? or is there a way to map and return a guarantee instead of a promise?

**Comment by mxcl** [comment]
This is an omission, PR welcome.

As a workaround do: `recover{ fatalError("\($0") }`

If you are sure there are only guarantees above this is safe.

**Comment by drekka** [comment]
PR Submitted. The change seem to be working in my code base.

**Comment by mxcl** [comment]
PR merged.
