### ISSUE TITLE
Can't compile PromiseKit in a fresh empty project

### ISSUE THREAD

**Issue by ArtemBogush** [mxcl/PromiseKit#873]
Hey I'm starting new swift project and just came across your repo.

I've added the latest version of it with pods (6.0.0) but I'm getting a bunch of errors in PromiseKit sources itself - I didn't even had a chance to start using it in the project:

![screen shot 2018-06-10 at 6 48 04 pm](https://user-images.githubusercontent.com/8145834/41203966-e0accf5e-6cde-11e8-9449-18505596d050.png)

What I'm doing wrong here?

I'm using Xcode 9.3.1 with swift 4.1

podfile:

use_frameworks!

target 'ProjectVision' do
  pod 'SlideMenuControllerSwift', '4.0.0'   #left slide menu
  pod 'PromiseKit', '6.0.0'                 #promises to make async stuff easier
end

**Comment by mxcl** [comment]
Specify:

```
pod 'PromiseKit', '~> 6.0.0'
```

You specified exactly 6.0.0, we have release 28 bug fix releases since then, one of which fixes this issue for > Xcode 9.2. I expect you want that.
