### ISSUE TITLE
Release 6.3.0 breaks PMKFoundation

### ISSUE THREAD

**Issue by FSMaxB-divae** [mxcl/PromiseKit#874]
I use PromiseKit and PMKFoundation with carthage and since PromiseKit 6.3.0 PMKFoundation doesn't build anymore.

`Cartfile`:
```
github "mxcl/PromiseKit" ~> 6.0
github "PromiseKit/Foundation" ~> 3.0
```

It worked before
-----------------
`Cartfile.resolved`:
```
github "PromiseKit/Foundation" "3.0.5"
github "mxcl/PromiseKit" "6.2.9"
```

It doesn't work now
--------------------
`Cartfile.resolved`:
```
github "PromiseKit/Foundation" "3.0.5"
github "mxcl/PromiseKit" "6.3.0"
```

How to reproduce:
-------------------
1. Make an empty directory containing the abore Cartfile
2. Put in the non-working `Cartfile.resolved`
3. Run `carthage checkout`
4. Run `carthage build`
5. Wait for the build to fail.

**Comment by mxcl** [comment]
Please provide the build errors.

**Comment by FSMaxB-divae** [comment]
I forgot to mention: This is with Xcode 9.4

[carthage-xcodebuild.log](https://github.com/mxcl/PromiseKit/files/2090917/carthage-xcodebuild.log)

**Comment by mxcl** [comment]
Ok, your building against macOS, FYI that is important omitted information.

Fix coming. Thanks for the report.

**Comment by mxcl** [comment]
K pushed Foundation 3.1.0 which bumps the macOS deployment target to match PromiseKit 6.3.0’s updated deployment target.

Sorry for the issue. Sadly this level of testing is not automated.
