### ISSUE TITLE
No way to specify queue for tap

### ISSUE THREAD

**Issue by Igor-Palaguta** [mxcl/PromiseKit#884]
Hello,

We use PromiseKit 6.2.5

Is there any way to specify queue for ```tap```. Currently it can be called on any queue main or background. Looks like ```done/ensure/get/catch``` by default executes on queue mentioned in configuration. And we can pass queue to these functions but not for ```tap```

**Comment by mxcl** [comment]
This is an omission. PR welcome. I can assist with directions.

**Comment by GarthSnyder** [comment]
I believe this is fixed in master already with Igor's PR.

**Comment by Igor-Palaguta** [comment]
Yes, it works, issue can be closed
