### ISSUE TITLE
How can I prevent showing Xcode warning <Result of call to 'done(on: flags:_:)' is unused>?

### ISSUE THREAD

**Issue by huyvoduc** [mxcl/PromiseKit#885]
I am newbie in PromiseKIT. I am using version 6. 
I get Xcode warning message <Result of call to 'done(on: flags:_:)' is unused> in some case that I dont care about the result of function and do nothing after finishing processing ( dont implement ensure / catch / finally ) 

My func is like this : 

    func test(id:String) -> Promise<Void> {
        return Promise { seal in
            
            if id == "1" {
               // fulfill
            } else if id == "2" {
               // reject
            }
        }
    }

and I get the message when I call it 

    test(id: "1").done { // Xcode warning here
            print("Test OK")
            }

So Can you help me to prevent showing this Xcode warning message ? 
Thank you very much for reading my issue

**Comment by mxcl** [comment]
This is in the troubleshooting guide.

**Comment by mxcl** [comment]
[Troubleshooting Guide](https://github.com/mxcl/PromiseKit/blob/master/Documentation/Troubleshooting.md)

**Comment by huyvoduc** [comment]
Thanks so much ! You saved my day
