### ISSUE TITLE
Guarantee.get returns Promise

### ISSUE THREAD

**Issue by dermaaarkus** [mxcl/PromiseKit#889]
Hi,

```swift
firstly {
    print("thank you for your great kit!")
} 
```

I have an issue calling `.get` on a `Guarantee`, because it returns a `Promise` and the compiler tells me to write catch block. But it can never fail and a catch block doesn't make sense here!

As Developer I expect to be able to call `.get` without defining a catch block

```
firstly {
    fetchUser() // returns Guarantee<String>
}.get {
    self.user = $0
}.done { user in // Compiler Warning: Result of call to 'done(on:flags:_:)' is unused
    self.label.text = user.name
}
```

* PromiseKit Version: 6.30.0

**Comment by dermaaarkus** [comment]
Example Project: [PromiseKitExample.zip](https://github.com/mxcl/PromiseKit/files/2141096/PromiseKitExample.zip)

**Comment by mxcl** [comment]
Many thanks 👍🏻
