### ISSUE TITLE
Resolving multiple promises using `when(resolved:)`

### ISSUE THREAD

**Issue by elimence** [mxcl/PromiseKit#892]
PromiseKit 6

I have a function that fetches a list of alerts from a db, I then need to use the `contentId` property on each to fetch the content and attach to the appropriate alert item.

Maybe there's a better way (@mxcl you mentioned you hardly use `when`, and that `when(resolved:)` is not a good idea since errors get ignored)

But what I came up with is to collect the promises into a list and call `when(resolved:)`. I chose that because if any promise fails, I want to be able to return all those that can pass.

If there's a better approach, I'd be happy to get some pointers. Thanks :)

```swift
private func getContent(for alert: Model) -> Promise<ViewModel> {
  return firstly { () -> Promise<Any> in

    if let contentType = AlertContentType(rawValue: alert.type) {
      switch contentType {
      case .news:
        return newsService.get(contentId: contentId, superareaId: superareaId).compactMap { $0 as Any }

      case .insight:
        return insightService.get(contentId: contentId, superareaId: superareaId).compactMap { $0 as Any }
      }
    } else { throw DataError.Missing(error: "Could not retrieve type!") }
  }.compactMap { content in
    var viewModel = alert.toViewModel()
    viewModel.content = content
    
    return viewModel
  }
}
    
private func attachContents(to alerts: [Model]) -> Promise<[ViewModel]> {
  return firstly { () -> Guarantee<[Result<ViewModel>]> in
    let contentPromises: [Promise<AlertViewModel>] = alerts.map {
      return self.getContent(for: $0)
    }
    return when(resolved: contentPromises)
  }.map { (vModels: [Result<ViewModel>]) in
    vModels.flatMap { (vm: Result<ViewModel>) in
       //
       let viewModelsWithContent: [ViewModel?] = vModels.flatMap { (vm: Result<ViewModel>) in
            if case let .fulfilled(alert) = vm {
                return alert
            } else {
                return nil
            }
        }
    }
  }
}
```

**Comment by mxcl** [comment]
Seems like a fine use of `when(resolved:)`.

> you mentioned you hardly use `when`

To be clear, I hardly use `when(resolved:)`, I use the other `when` variants all the time though.

I cleaned this up, maybe (I had to infer some bits):

    private func getContent(for alert: Model) -> Promise<ViewModel> {
        return firstly { () -> AlertContentType in
            switch AlertContentType(rawValue: alert.type) {
            case .news?:
                return newsService.get(contentId: contentId, superareaId: superareaId)
            case .insight?:
                return insightService.get(contentId: contentId, superareaId: superareaId)
            default:
                throw DataError.Missing(error: "Could not retrieve type!")
            }
        }.map { content in
            var viewModel = alert.toViewModel()
            viewModel.content = content
            return viewModel
        }
    }
    
    private func attachContents(to alerts: [Model]) -> Promise<[ViewModel]> {
        return firstly {
            when(resolved: alerts.map{ self.getContent(for: $0) })
        }.compactMapValues {
            $0.value
        }
    }

**Comment by mxcl** [comment]
Closing but re-open if your question is still not answered.
