### ISSUE TITLE
Alamofire Extension Type Errors

### ISSUE THREAD

**Issue by asikand-view** [mxcl/PromiseKit#893]
PromiseKit 6.2.8 Alamofire Extension Installed 

Here are multiple iterations of the same code fragment

### Code 1
```
func apiCall() {

     let Endpoint: String = "eventbrite/api/categories"

     Alamofire.request(Endpoint, method: .get)
          .responseJSON().then { (json, response)  in
               print(JSON(json)["categories"])
          } 
}
```
### Error 1
**Closure tuple parameter '(json: Any, response: PMKAlamofireDataResponse)' does not support destructuring**

### Steps Taken
**Follow Xcode's advice to correct it, pass the closure tuple parameter as just one name, grab the two parts later.**

### Code 2
```
func apiCall() {

     let Endpoint: String = "eventbrite/api/categories"

     Alamofire.request(Endpoint, method: .get)
          .responseJSON().then { args  in
               let (json, response) = args
               print(JSON(json)["categories"])
          } 
}
```

### Error 2
**Unable to infer complex closure return type; add explicit type to disambiguate**

### Steps Taken
**Add explicit type to the closure**

### Code 3
```
func apiCall() {

     let Endpoint: String = "eventbrite/api/categories"

     Alamofire.request(Endpoint, method: .get)
          .responseJSON().then { args -> Void  in
               let (json, response) = args
               print(JSON(json)["categories"])
          } 
}
```

### Error 3
**Cannot convert value of type '(_) -> Void' to expected argument type '(_) -> _'**

[https://stackoverflow.com/questions/45163720/swift-4-cannot-convert-value-of-type-to-expected-argument-type](url)

**In order to remove this error, I remove the useless Void keyword, which sends me straight back to Error 2**

**Comment by mxcl** [comment]
Per the troubleshooting guide, you need to use `done` and not `then`. Please read our documentation since it contains full instructions on how to use PromiseKit 6.
