### ISSUE TITLE
HomeKit support

### ISSUE THREAD

**Issue by ChrisChares** [mxcl/PromiseKit#901]
Hi there! Thank you for all your hard work with PromiseKit, it's a truly wonderful library.

I've been writing PK extensions for HomeKit for a project I'm working on at the moment.  I've recently created a standalone project for these extensions, using PromiseKit/CoreLocation as a template. 

You can view progress so far [here](https://github.com/ChrisChares/PromiseKit-HomeKit).

Is this something you'd like to include in the PK org once completed?  And if so:

- What level of test coverage are you looking for?
- Is objc support required?
- Is coverage of 100% of HomeKit's async APIs required?

Thanks for your time,
Chris

**Comment by mxcl** [comment]
Superb!

> What level of test coverage are you looking for?

As much as you can be bothered with. IME this stuff is hard to test and the tests are not often that useful (for the extensions that is, the core library is about as close to 100% as we can get it).

> Is objc support required?

Nowadays? No.

> Is coverage of 100% of HomeKit's async APIs required?

No, any amount is great. If other people come along and find they need more, they can supplement the library.

LMK when you want to go forward and I'll create the repo at the PromiseKit organization. Many thanks.

**Comment by ChrisChares** [comment]
Awesome sounds good.  Will get back to you when I'm ready for next steps.

**Comment by ChrisChares** [comment]
Wow you weren’t kidding about testing this stuff. 

Mocking went okay until I hit `HMHome`, which was kind enough to mark `init() NS_UNAVAILABLE`.  Interesting behavior after that. Apparently without any available superclass initializers, a subclass will still compile, yet vends uninitialized objects from it’s own initializers.   

I tried a few different things to make the code more testable, but the results weren’t great and I wasn’t comfortable with the corresponding loss in readability.  At the end of the day I felt I was just writing tests for either HomeKit or Swift’s own type system and scrapped most of it.  Your swizzle method from the core location tests proved useful for testing a delegate wrapper.

It built as a dependency via Carthage, not sure how to test it as a Pod subspec.  Anything else that should be tested or done?

**Comment by mxcl** [comment]
> not sure how to test it as a Pod subspec

I can handle that, the podspec is on this repo, but it's a bitch of a podspec so I can do it.

> Anything else that should be tested or done?

Nope! Looking forward to your submission. I'll create the repo.

**Comment by ChrisChares** [comment]
@mxcl Thanks for creating the repo.  Just pushed to it.  I'll keep adding things here and there, please let me know if you need anything else in the meantime.

**Comment by mxcl** [comment]
> Specifically, should I tag the initial release and if so does the version have to be anything specific?

Oh sorry, just did that for you. Carthage needs a version, so I added it.

**Comment by ChrisChares** [comment]
Thanks!
