### ISSUE TITLE
Quick question about using `recover`

### ISSUE THREAD

**Issue by elimence** [mxcl/PromiseKit#902]
Promisekit Version: 6
==================

I have two functions that fetch data, one from a local db and the other from a remote server. `attachContent` hydrates the model.

```js
func daoClient.get(id: String) -> Promise<Model>
func apiClient.get(id: String) -> Promise<Model>
func attachContent(model: Model) -> Promise<Model>
func save(content: JSON) -> Promise<Void>
```

I have another function that fetches data by first checking the local db and going online if not found. I made use of `recover` but it seems  that might not be how it was intended to be used. I'd be glad if anyone could point me towards a better approach or let me know if this is a good use-case.

```js
func service.get(id: String) -> Promise<Model> {
    return daoClient.get(id: id).recover { _ in
        self.apiClient.get(id: id)
            .then { self.save(content: $0) }
            .then { _ in self.daoClient.get(id: id) }
    }.then { self.getContent(for: $0) }
}
```

Many thanks :)

**Comment by mxcl** [comment]
This is a fine usage, though you may want to log the error to something like Sentry.

**Comment by elimence** [comment]
Great thanks 👍
