### ISSUE TITLE
Quick question about ObjectMapper library

### ISSUE THREAD

**Issue by avjiang** [mxcl/PromiseKit#903]
Is there any possibility to combine the PromiseKit/Alamofire with [ObjectMapper](https://github.com/Hearst-DD/ObjectMapper) library? 

Thanks

**Comment by mxcl** [comment]
Everything is possible, I have no experience with this library though so could not write the PromiseKit extension.

**Comment by avjiang** [comment]
okay @mxcl  thanks for your fast reply. I really would like to implement this library onto my current project that using ObjectMapper. But it seems I couldn't apply it for now. 

Thank you so much
