### ISSUE TITLE
when(resolved: guarantees).done { results in     //… }

### ISSUE THREAD

**Issue by spearway** [mxcl/PromiseKit#904]
I really would like to be able to write the following:
when(resolved: guarantees).done { results in
    //…
}
Think this would be in the spirit of the guarantees. At the moment we need to use fulfilled that force us to add a useless recover clause (these are guarantees so they cannot fail). I would suggest that we can do it by hiding the recover clause in the PromiseKit code. Of course you may have abetter idea>

`public func when<U: Thenable>(resolved guarantees: U...) -> Guarantee<Void> where U.T == Void {
    return _when(guarantees).recover(on:nil) { _ -> Guarantee<Void> in .value(()) }
}
`

**Comment by mxcl** [comment]
This is unreadable, please format it then I will help.

**Comment by spearway** [comment]
I will do a pull request if you like the idea

**Comment by mxcl** [comment]
This is still unreadable.

**Comment by spearway** [comment]
The idea is that we have now an API with when(fulfilled: tenables) that return a guarantee I would like a when(resolved: guarantees) that return a guarantee

**Comment by mxcl** [comment]
> `when(resolved: guarantees)` that return a guarantee

Guarantees cannot error so they always `resolve`. This is why there is only one variant of `when` for Guarantees.

> when(fulfilled: tenables) that return a guarantee

Well, we don’t have that actually, `when(fulfilled:)` returns a Promise.

**Comment by spearway** [comment]
as you the problem is that we return a Promise and that force us to write a recover clause that is absolutely worthless at it will never be called

**Comment by mxcl** [comment]
https://github.com/mxcl/PromiseKit/blob/master/Sources/when.swift#L256

**Comment by spearway** [comment]
Yes but that only works with void. This is a very narrow case I typically return some value from the calls.

**Comment by mxcl** [comment]
Yes, do this:

https://github.com/mxcl/PromiseKit/blob/master/Documentation/Appendix.md#voiding-promises

We don’t provide `when<T>`(guarantees:)` because the Swift compiler breaks. This has been discussed in several other tickets.
