### ISSUE TITLE
Compiling for WatchOS fails on latest Xcode 10 Beta.

### ISSUE THREAD

**Issue by drekka** [mxcl/PromiseKit#907]
Just being trying to build the latest PromiseKit on the latest Xcode 10 Beta. Yep, all the new shiny bells and whistles :-)

Anyway, Carthage builds PromiseKit as a dependency fine for tvOS and iOS, but if I don't specify a platform, it trys to build the WatchOS version and throws an error. The Carthage build logs show the following error:

    xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:watchOS Simulator, id:B453B7E5-03D5-45CD-A2A0-C99DFAC7E527 }

	The requested device could not be found because no available devices matched the request.

	Available destinations for the "PromiseKit" scheme:
		{ platform:macOS, arch:x86_64, id:A336B469-E941-5AA3-B031-E1D2A3664588 }
		{ platform:iOS, id:1bbaae93cab5e11484b6f9b000313d0712c0e23c, name:Litttle byte }
		{ platform:tvOS Simulator, id:3105CEFB-06BB-48EA-9973-8314BEA19ED3, OS:12.0, name:Apple TV }
		{ platform:tvOS Simulator, id:D538FBB7-F216-4908-B9B8-94A1E51F864B, OS:12.0, name:Apple TV 4K }
		{ platform:tvOS Simulator, id:91D53FF8-BD7A-4ED7-8203-D2E8FA5BF55D, OS:12.0, name:Apple TV 4K (at 1080p) }
		{ platform:watchOS Simulator, id:C8A604E1-CE76-45AF-B8A9-D4A229BDE57D, OS:5.0, name:Apple Watch Series 2 - 38mm }
		{ platform:watchOS Simulator, id:4E2CE6A7-EF55-4E1B-96C1-EFB3ABE0F53F, OS:5.0, name:Apple Watch Series 2 - 42mm }
		{ platform:watchOS Simulator, id:2FA8F0F7-6DB2-4A26-B6EB-747F746FC460, OS:5.0, name:Apple Watch Series 3 - 38mm }
		{ platform:watchOS Simulator, id:C6FA5B05-CE63-4441-8140-0835290E94BC, OS:5.0, name:Apple Watch Series 3 - 42mm }
		{ platform:iOS Simulator, id:D374A6AC-A7CD-4BE2-AD17-104218F3D641, OS:10.3.1, name:iPad (5th generation) }
		{ platform:iOS Simulator, id:065AF4B3-C0C2-406E-ADB8-747B31A73A40, OS:12.0, name:iPad (5th generation) }
		{ platform:iOS Simulator, id:0EEA310D-75A8-4A86-B18C-345B6BEE2D1B, OS:12.0, name:iPad (6th generation) }
		{ platform:iOS Simulator, id:8E91CFC8-EFDF-4459-9E51-0C646919E580, OS:10.3.1, name:iPad Air }
		{ platform:iOS Simulator, id:5704CC48-B611-476D-824F-27A2EA4EFF6D, OS:12.0, name:iPad Air }
		{ platform:iOS Simulator, id:68DD51CB-4038-45F9-8DC8-0007BB9DB9D5, OS:10.3.1, name:iPad Air 2 }
		{ platform:iOS Simulator, id:C2A1CC81-C753-4F45-8410-5275121DA0E0, OS:12.0, name:iPad Air 2 }
		{ platform:iOS Simulator, id:FEBDA295-4EB4-48E2-BE42-74EB856A7F5F, OS:10.3.1, name:iPad Pro (9.7 inch) }
		{ platform:iOS Simulator, id:7CD6FEB9-C574-4345-A9F2-6756CDF71AB5, OS:12.0, name:iPad Pro (9.7-inch) }
		{ platform:iOS Simulator, id:DFBE8306-7446-48D5-9016-13AE87B4EB56, OS:10.3.1, name:iPad Pro (10.5-inch) }
		{ platform:iOS Simulator, id:0AF0EA2E-8271-4DDF-B48C-934E5C7BCF30, OS:12.0, name:iPad Pro (10.5-inch) }
		{ platform:iOS Simulator, id:57CDDE7C-A0A4-41B1-A4C5-D9BDEF38B14F, OS:10.3.1, name:iPad Pro (12.9 inch) }
		{ platform:iOS Simulator, id:7653DE59-65ED-4A2D-8DF9-38F6B3519FDF, OS:12.0, name:iPad Pro (12.9-inch) }
		{ platform:iOS Simulator, id:C484D665-9151-4E21-9659-FB720B3736B5, OS:10.3.1, name:iPad Pro (12.9-inch) (2nd generation) }
		{ platform:iOS Simulator, id:F7D82006-7540-4D6A-860C-B800AEBFDC49, OS:12.0, name:iPad Pro (12.9-inch) (2nd generation) }
		{ platform:iOS Simulator, id:283D0B2B-CF65-4230-A9A8-9E3E57AF9418, OS:10.3.1, name:iPhone 5 }
		{ platform:iOS Simulator, id:52D10410-E7BE-4088-BA3C-B4BC3DE0957E, OS:10.3.1, name:iPhone 5s }
		{ platform:iOS Simulator, id:E021C6A1-B6CE-42E1-97E6-6ECF5C554344, OS:12.0, name:iPhone 5s }
		{ platform:iOS Simulator, id:D422865C-38F1-46B7-82F1-5968C41241C2, OS:10.3.1, name:iPhone 6 }
		{ platform:iOS Simulator, id:E7B23DC0-C0EA-4AC2-BF36-D3E56B778FD6, OS:12.0, name:iPhone 6 }
		{ platform:iOS Simulator, id:1F2D587C-1A13-4462-BCBC-1A0B6F060CE1, OS:10.3.1, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:08B39E8C-5342-48C5-8F5A-E18EFC3ED571, OS:12.0, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:76F8F3FF-65ED-4251-BC59-8EBB98B3A0E6, OS:10.3.1, name:iPhone 6s }
		{ platform:iOS Simulator, id:271B0237-F516-44A0-BF3D-DC3AAEE627F5, OS:12.0, name:iPhone 6s }
		{ platform:iOS Simulator, id:F1B4283F-06AD-426E-84C4-3205A10DAE7E, OS:10.3.1, name:iPhone 6s Plus }
		{ platform:iOS Simulator, id:79206EA4-6D05-4936-92F0-A4AB660B5DF2, OS:12.0, name:iPhone 6s Plus }
		{ platform:iOS Simulator, id:75B9B66C-3D69-43B0-8A1C-FAAE936097AC, OS:10.3.1, name:iPhone 7 }
		{ platform:iOS Simulator, id:37080F99-4085-4957-A10F-FD3E462A5C28, OS:12.0, name:iPhone 7 }
		{ platform:iOS Simulator, id:712637B1-4BC0-4F03-970D-660AA4A9E3F1, OS:10.3.1, name:iPhone 7 Plus }
		{ platform:iOS Simulator, id:43D008B1-B1EA-4523-8A76-998F442EB6C4, OS:12.0, name:iPhone 7 Plus }
		{ platform:iOS Simulator, id:0B9BB956-0617-417A-82FD-670F811EF7C0, OS:12.0, name:iPhone 8 }
		{ platform:iOS Simulator, id:4D0795A8-E141-4BA0-81A0-E53E31B9BEAB, OS:12.0, name:iPhone 8 Plus }
		{ platform:iOS Simulator, id:84CF6ADB-BF02-41E5-B38F-A6C869B308D5, OS:10.3.1, name:iPhone SE }
		{ platform:iOS Simulator, id:80600F6F-FB3B-4EDF-9F1B-9A693B400186, OS:12.0, name:iPhone SE }
		{ platform:iOS Simulator, id:5951E8ED-55B2-4E70-BDE3-0858F47C7C40, OS:12.0, name:iPhone X }

	Ineligible destinations for the "PromiseKit" scheme:
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }
		{ platform:tvOS, id:dvtdevice-DVTiOSDevicePlaceholder-appletvos:placeholder, name:Generic tvOS Device }
		{ platform:tvOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-appletvsimulator:placeholder, name:Generic tvOS Simulator Device }
		{ platform:watchOS, id:dvtdevice-DVTiOSDevicePlaceholder-watchos:placeholder, name:Generic watchOS Device }
		{ platform:watchOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-watchsimulator:placeholder, name:Generic watchOS Simulator Device }

**Comment by mxcl** [comment]
This is a Carthage bug, since it builds fine in Xcode itself.

Leaving open for others to find. The workaround is not to build platforms you don’t need, eg:

    carthage bootstrap --platform iOS

I am not reporting the bug against Carthage, I never do, I have only so much time and energy, other people with time and incentive should do so.

**Comment by drekka** [comment]
Cool. Luckily I actually don't need the WatchOS build, just happened to come across this :-) Thanks.

**Comment by mxcl** [comment]
According to the referenced issue this is fixed, though maybe not yet released.

**Comment by mxcl** [comment]
The new Carthage is released and in Homebrew, closing.
