### ISSUE TITLE
Chaining flow error - Cannot convert value of type '(_) -> Promise<Item>' to expected argument type '(_) -> _'

### ISSUE THREAD

**Issue by ArtemBogush** [mxcl/PromiseKit#908]
Checked the troubleshooting guide and the docs but still can't figure out how to make work the following scenario:

- create `Item`
- if `Item` has image, upload the image
- return `Promise<Item>`

In the last `then` I get `Cannot convert value of type '(_) -> Promise<Item?>' to expected argument type '(_) -> _'`

I need to return `Promise` from this method since it will be used furhter in the app, so I can't use `done` here.

The code looks like the following:

```
    func itemCreate(_ item: Item) -> Promise<Item?>{
        var createdItem : Item? = nil
        return itemCreateInternal(item)
            .then { item in
                createdItem = item
                return self.uploadImageIfNeeded(item)
            }.then { arg in      //  <- getting the error in this line
                return Promise{callback in
                    callback.fulfill(createdItem);
                }
        }
    }



    func uploadImageIfNeeded(_ item: Item?) -> Promise<Item?>{
        if let item1 = item, let image = item1.imageObj{
            return itemUploadImage(item1, image) //returns  Promise<Item?>
        }
        return Promise<Item?>{callback in
            callback.fulfill(expenseItem);
        }
    }

```

That looks like a trivial task for promisis but seems like I'm totally stuck. Any help is much appreciated

**Comment by mxcl** [comment]
Specify the return type of the closure of the first `then`.

**Comment by mxcl** [comment]
Optional promises are generally considered a code-smell, I suggest reading our common misusage documentation, also our troubleshooting guide includes the above fix I suggested, so probably read that too.

**Comment by ArtemBogush** [comment]
Thanks a lot @mxcl. Following your suggestion fixed it as below:

```
return itemCreateInternal(item)
            .then { item -> Promise<Item?> in
```

Though I'm a bit confused about your `generic promises` statement - checked [this common misusage guide](https://github.com/mxcl/PromiseKit/blob/master/Documentation/Appendix.md), but can't find any alternatives to the generic approach. Could you please suggest what is the intended usage in this case?

**Comment by mxcl** [comment]
What `generic promises` statement?

**Comment by ArtemBogush** [comment]
Sorry, misread your message - you were talking about optional, not generic. Please disregard my message.

Thanks again for the quick help and great library!
