### ISSUE TITLE
PromiseKit version of .observe conflicts with Apple's defined .observe for KVO operations

### ISSUE THREAD

**Issue by alexpersian** [mxcl/PromiseKit#911]
PromiseKit version: 5.0.1

Today I was attempting to use KVO to monitor the title attribute within a WKWebView. Using the definition provided by Apple presented some very odd compiler warnings referring to `PMKNamespacer`. Digging in shows that PromiseKit has a wrapper of sorts for working with KVO in a promise fashion. I'm confused why this function is conflicting with the standard library's definition though as they don't match in type or even parameter order.

```swift
// Error: Cannot convert value of type 'KeyPath<WKWebView, String?>' to expected argument type 'PMKNamespacer'
webView.observe(\WKWebView.title) { (_, title) in
    print("Title: ", title)
}

// Error: Extra argument 'options' in call
webView.observe(\WKWebView.title, options: [.initial]) { (_, title) in
    print("Title: ", title)
}

// Error: Incorrect argument label in call (have '_:changeHandler:', expected '_:keyPath:')
// The compiler's autocorrect wants to swap the two parameters here.
webView.observe(\WKWebView.title, changeHandler: { (_, title) in
    print("Title: ", title)
})

// Apple's method definition (with WKWebView context)
observe(
    keyPath: KeyPath<WKWebView, Value>, 
    options: NSKeyValueObservingOptions, 
    changeHandler: (WKWebView, NSKeyValueObservedChange<Value>) -> Void
)

// PromiseKit's definition
public enum PMKNamespacer {
    case promise
}

public func observe(_: PMKNamespacer, keyPath: String) -> Guarantee<Any?> {
    return Guarantee { KVOProxy(observee: self, keyPath: keyPath, resolve: $0) }
}
```

Wondering if there is a way to address this conflict, or if we are forced to use the PromiseKit version. This doesn't seem to be an "ambiguous context" issue since the definitions are very obviously different. Note: this is also in a file that doesn't import PromiseKit.

**Comment by mxcl** [comment]
I imagine swift is lying and there’s another syntax error there actually. This is usually what it is.

**Comment by alexpersian** [comment]
@mxcl I think you are right. This was causing enormous issues yesterday, and I even tested within a Playground to ensure I wasn't using incorrect syntax. Sure enough though this morning I went back to it and the compiler started behaving and no longer flagging the line as an error.

I'll close this issue as resolved then. Thanks.

**Comment by endresjd** [comment]
So what was/is the resolution to this?

**Comment by endresjd** [comment]
OK.  Nevermind.  It taks a string.
