### ISSUE TITLE
API to tapping Error

### ISSUE THREAD

**Issue by Igor-Palaguta** [mxcl/PromiseKit#916]
Hello,

For tapping value we can use `get`, for tapping both value and error we can use `tap`. But there is no api for tapping just error

So we have to use `tap` with check inside:

```
promise.tap { result in
    guard case .rejected(let error) = result else {
        return
    }
    // use error
}
```

If you agree, can perform PR for this

**Comment by mxcl** [comment]
Can you provide example code that justifies this addition?

**Comment by mxcl** [comment]
I guess I have recently found a situation this would be useful. But I just used recover. Using recover here was a little unwieldy, but still I am hesitant to add more API that makes learning PromiseKit less straight forward.

**Comment by hani-ibrahim** [comment]
I would to have this addition as well. `recover` would make the chain success however we want to do something if error happens but couldn't use catch as catch terminate the chain.

**Comment by mxcl** [comment]
> `recover` would make the chain success

You can re-throw:

```swift
.recover { error -> Promise<Foo> in
    // do something
    throw error
}
```

**Comment by Igor-Palaguta** [comment]
Is it fine we will have side effects inside `recover`?

**Comment by hani-ibrahim** [comment]
@mxcl yeah true, but it's not so readable as recover is meant to recover from an error and return a valid value, so when I read recover I would expect that. But throwing an error again in recover means that we are not really recovering and it's a bit confusing.

I think something like this would be more readable. no?  
```swift
.grab { error in
    print("Do something")
}
```
could be `grab`, `check`, `grasp `

**Comment by mxcl** [comment]
I agree it's more readable, but I have already specified my concerns above. My concerns would be mitigated somewhat with a good name for the function.

**Comment by mxcl** [comment]
> Is it fine we will have side effects inside recover?

I don't really understand; the same caveats apply to whatever you do inside the function as for all other PromiseKit handlers.

**Comment by Igor-Palaguta** [comment]
We have good places for side effects (like updating UI) `done`/`catch`/`tap`/`get`/`ensure`
Other functions like `map`/then`/`recover` should just modify promise, without any side effect

**Comment by mxcl** [comment]
It's as fine to have side-effects that affect UI or global state in any PromiseKit handlers, typically though it is a better pattern to avoid this until the end of the chain though, since it allows you to reason about the process better, 1) set UI state 2) promises 3) set UI state.

Therefore, it doesn't matter if you modify the state in `map` or `then`, it's just not typical since they are usually mid-chain functions.

There are no hard and fast rules in programming, just understandings and patterns.

**Comment by mxcl** [comment]
Closing since I closed the PR. Again, thanks so much and sorry this wasn’t accepted!
