### ISSUE TITLE
Documented example doesn't compile

### ISSUE THREAD

**Issue by aodhol** [mxcl/PromiseKit#918]
In PromiseKit 6.4, should the examples from the documentation compile?

` let fetchImage = URLSession.shared.dataTask(.promise, with: URL(string: "https://www.apple.com")!)` doesn't compile because: `Argument labels '(_:, with:)' do not match any available overloads`. A variation with a string URL argument doesn't work either.

**Comment by aodhol** [comment]
pod 'PromiseKit/Foundation' needs to be included!

**Comment by mxcl** [comment]
The foundation pod is included in the default PromiseKit pod. So to not be able to use the URLSession extensions you had to explicitly exclude them at some point. Also the docs say how you need this in the comment above…

**Comment by aodhol** [comment]
My error entirely, for some reason I only included: `pod 'PromiseKit/CorePromise"`
