### ISSUE TITLE
HealthKit extension

### ISSUE THREAD

**Issue by bellebethcooper** [mxcl/PromiseKit#920]
Hello again!

Re #824 comments, @mxcl offered to maybe add a HealthKit extension if I suggested the methods I use that need wrapping. I'm about to look at refactoring my app's HealthKit code to use PromiseKit, so this would be super useful! Here are the methods I personally use:

`HKStatisticsQuery`:
- `init(quantityType: HKQuantityType, quantitySamplePredicate: NSPredicate?, options: HKStatisticsOptions = [], completionHandler: (HKStatisticsQuery, HKStatistics?, Error?) -> Void)`

`HKStatisticsCollectionQuery`:
- `init(quantityType: HKQuantityType, quantitySamplePredicate: NSPredicate?, options: HKStatisticsOptions = [], anchorDate: Date, intervalComponents: DateComponents)`

`HKStatisticsCollectionQuery` takes a results handler as a property, rather than in the initialiser:
`var initialResultsHandler: ((HKStatisticsCollectionQuery, HKStatisticsCollection?, Error?) -> Void)?`

`HKSampleQuery`:
- `init(sampleType: HKSampleType, predicate: NSPredicate?, limit: Int, sortDescriptors: [NSSortDescriptor]?, resultsHandler: (HKSampleQuery, [HKSample]?, Error?) -> Void)`

`HKObserverQuery`:
- `init(sampleType: HKSampleType, predicate: NSPredicate?, updateHandler: (HKObserverQuery, HKObserverQueryCompletionHandler, Error?) -> Void)`

`HKAnchoredObjectQuery`:
- `init(type: HKSampleType, predicate: NSPredicate?, anchor: HKQueryAnchor?, limit: Int, resultsHandler: (HKAnchoredObjectQuery, [HKSample]?, [HKDeletedObject]?, HKQueryAnchor?, Error?) -> Void)`

`func`s on `HKHealthStore`:

- `func requestAuthorization(toShare: Set<HKSampleType>?, read: Set<HKObjectType>?, completion: (Bool, Error?) -> Void)`
- `enableBackgroundDeliveryForType(_ type: HKObjectType, frequency frequency: HKUpdateFrequency, withCompletion completion: (Bool, NSError?) -> Void)`

These are all for reading data from HealthKit; I don't write any data into it so I haven't included methods for doing so, but I could look into those as well if that's helpful.

I'm not confident about giving this a go myself, or else I would do it to save you the effort, but if it's too much to take on, feel free to just close this issue.

Thanks again for PromiseKit!

**Comment by mxcl** [comment]
Thanks, I won't have time for at least a week, but I'll revaluate near the 24th.

**Comment by bellebethcooper** [comment]
Thank you!

**Comment by mxcl** [comment]
I'm on this today. I'm not doing `HKObserverQuery` because it calls the callback multiple times. Will advise if there are others.

**Comment by mxcl** [comment]
Not adding `HKObserverQuery` as it completes more than once.

**Comment by mxcl** [comment]
PR referenced above, please review the API.

**Comment by bellebethcooper** [comment]
@mxcl That was so quick, thank you! Looks perfect for my usage. I really appreciate your effort—this is going to make my code soooo much better 👍

**Comment by mxcl** [comment]
If you or your employer found this work useful please consider donating to [my patreon](https://patreon.com/mxcl), thank you.

**Comment by bellebethcooper** [comment]
Done! Thanks again :)

**Comment by mxcl** [comment]
Many thanks!
