### ISSUE TITLE
NSURLErrors URLSession.shared.dataTask

### ISSUE THREAD

**Issue by Jarvey** [mxcl/PromiseKit#921]
**NSURLErrors URLSession.shared.dataTask**
I'm using this code found in one of you're examples.
And it looks like it's working just fine. But I do receive NSURLErrors in the Xcode console when testing my app. Is this normal? How can I fix them?

``` swift
firstly {
   URLSession.shared.dataTask(.promise, with: try makeUrlRequest()).validate()
   // ^^ we provide `.validate()` so that eg. 404s get converted to errors
}.then { xml in
   //parse received data
}.then { parsedItems in
    //clean up parsed items
}.done { result in
    //build ui
}.catch { error in
    print(error)
}.finally {
    //hide loading label
}

func makeUrlRequest() throws -> URLRequest {
  //variables for the url...
            
  // credentials encoded in base64
  let username = "username"
  let password = "abC123"
  let loginData = String(format: "%@:%@", username, password).data(using: String.Encoding.utf8)!
  let base64LoginData = loginData.base64EncodedString()
  let url = URL(string:"https://website.com?item1=\(itemOne)&item2=\(itemTwo)&date=\(dateTime)")
            
  var rq = URLRequest(url: url!)
  rq.httpMethod = "GET"
  rq.setValue("Basic \(base64LoginData)", forHTTPHeaderField: "Authorization")
  return rq
}
```

**NSURLErrors that show up in Xcode console**
2018-09-18 09:17:46.895665+0200 Appname WatchKit Extension[543:655766] Task <35BD7874-4D16-4BBF-90E5-E936F35E41B1>.<2> load failed with error Error Domain=NSURLErrorDomain Code=-2000 "can’t load from network" UserInfo={NSLocalizedDescription=can’t load from network, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <35BD7874-4D16-4BBF-90E5-E936F35E41B1>.<2>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <35BD7874-4D16-4BBF-90E5-E936F35E41B1>.<2>"
), NSErrorFailingURLStringKey=https://website.com?item1=WD&item2=GVC&date=2018-09-18T09:47, _kCFNetworkErrorConditionalRequestKey=<CFMutableURLRequest 0x1574fbc0 [0x35841098]> {url = https://website.com?item1=WD&item2=GVC&date=2018-09-18T09:47, cs = 0x0}, _kCFNetworkErrorCachedResponseKey=<CFCachedURLResponse 0x15751110 [0x35841098]>, NSUnderlyingError=0x157506d0 {Error Domain=kCFErrorDomainCFNetwork Code=-2000 "(null)" UserInfo={_kCFNetworkErrorCachedResponseKey=<CFCachedURLResponse 0x15751110 [0x35841098]>, _kCFNetworkErrorConditionalRequestKey=<CFMutableURLRequest 0x1574fbc0 [0x35841098]> {url = https://website.com?item1=WD&item2=GVC&date=2018-09-18T09:47, cs = 0x0}}}, NSErrorFailingURLKey=https://website.com?item1=WD&item2=GVC&date=2018-09-18T09:47} [-2000]

**Comment by mxcl** [comment]
You'd get the same error without the promises, so yes, this is normal. Looks like the watch doesn't have networking capabilities in some manner.

**Comment by Jarvey** [comment]
OK thank you for you're answer
