### ISSUE TITLE
Support for swift 4.2 

### ISSUE THREAD

**Issue by techmehra** [mxcl/PromiseKit#928]
[PLEASE READ THE TROUBLESHOOTING GUIDE](https://github.com/mxcl/PromiseKit/blob/master/Documentation/Troubleshooting.md).

---

You read the guide but it didn’t help? OK, we’re here to help.

* Please specify the PromiseKit major version you are using
* [Please format your code in triple backticks and ensure readable indentation](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

**Comment by mxcl** [comment]
We already support Swift 4.2. Of you have a specific issue please open a new ticket.

**Comment by ghowen** [comment]
@mxcl I just updated a project to the latest pods, and Xcode 10 still claims that there is a conversion to Swift 4.2 available for the PromiseKit.framework. It's just a warning that Swift code in the framework has not been converted to Swift 4.2 yet, but the library runs without a problem. Maybe this is what @techmehra meant.

**Comment by mxcl** [comment]
I ported everything months ago, but maybe I didn’t update the UIKit extension.

You probably don’t even use it specify your pod request without as shown in the README.

**Comment by mxcl** [comment]
K, I did indeed port this: 

https://github.com/PromiseKit/UIKit/commit/9c686799d23b12d01596ec1a0844265511acb586

And it's part of PromiseKit 6.4.0, so check you are up-to-date, if you still have problems then we will have to investigate further, but very much looks like issue with your cocoapods checkout to me.

**Comment by ghowen** [comment]
That is indeed weird. I am on PromiseKit 6.4.0 and if I open the pod and look at the source I can see the `#if swift(>=4.2)` directive. But Xcode 10 GM still wants to convert the part after the `#else` to Swift 4.2 which does not make any sense really. TBH I'm a bit at a loss now.

**Comment by mxcl** [comment]
Most likely because Cocoapods generates the `Pod.xcodeproj` for Swift 4.0 and Xcode is not being very smart here.

I imagine there's a ticket open to get pod to generate its project for 4.2 that you can subscribe to.

**Comment by techmehra** [comment]
![screenshot 2018-09-27 at 10 37 31](https://user-images.githubusercontent.com/18284379/46124374-5d5f7580-c241-11e8-968a-f0c9ca10a893.png)

**Comment by mxcl** [comment]
As already stated this is Cocoapods’ fault, I suggest opening a ticket there. PromiseKit is Swift 4.2 ready and has been for months.

**Comment by Kaspik** [comment]
It's not really CocoaPods' fault, it's XCode that recognises that you use Swift 4.0 code there (which is true even tho you have condition there.)
I would probably suggest either using only PromiseKit Core (user) or removing the condition and having the library Swift 4.2 fully (you as an author of the library).
(it doesn't mean that Swift 4 users can't install it, they still can use the library even if it's Swift 4.2).

**Comment by mxcl** [comment]
CocoaPods defines what version of Swift its generated project supports and they provide no way for pods to specify what versions of Swift they support. So it’s up to CocoaPods.

The other way to prevent this is for CocoaPods to generate the Xcodeproj with the flag that states this warning has been ignored. Which is something CocoaPods would have to do, so again, it's up to CocoaPods.

> I would probably suggest either using only PromiseKit Core (user) or removing the condition and having the library Swift 4.2 fully (you as an author of the library).

CocoaPods generate the Xcode-project, it's up to CocoaPods.

> I would probably suggest either using only PromiseKit Core (user)

This would have no impact on the warning since the warning is due to generated Xcodeproj specifying its Swift version as 4 and not containing the ignore-this-warning-flag and that is up to CocoaPods.

**Comment by mxcl** [comment]
> having the library Swift 4.2 fully

We 100%, completely and totally support Swift 4.2 fully. 100%. Totally. Fully. Please don’t think otherwise.

**Comment by Kaspik** [comment]
> > I would probably suggest either using only PromiseKit Core (user)
> 
> This would have no impact on the warning since the warning is due to generated Xcodeproj specifying its Swift version as 4 (and not 4.2) and not containing the ignore-this-warning-flag and that is up to CocoaPods.
Using `pod 'PromiseKit/CorePromise', '~> 6.3'` means no warning in `PromiseKit/UIKit` so for user - it does fix the warning.

> > having the library Swift 4.2 fully
> 
> We 100%, completely and totally support Swift 4.2 fully. 100%. Totally. Fully. Please don’t think otherwise.

Sorry to not be clear - "Having the library only Swift 4.2" without `#if swift(>=4.2)` conditions is what I meant. :)

**Comment by mxcl** [comment]
> Sorry to not be clear - "Having the library only Swift 4.2" without #if swift(>=4.2) conditions is what I meant. :)

We support all the way back to Swift 3.2 so that our library is more useful to people who cannot or do not upgrade their Swift versions. While this warning is irritating to CocoaPods users, we do not think the trade-off of losing backwards compatibility makes sense.

Thanks for your input.

**Comment by ghowen** [comment]
Looks like this was resolved with the latest update to 6.5.0. Out of curiosity and the learn from it: What was the culprit at the end and how did you fix it? Thanks.

**Comment by mxcl** [comment]
I did nothing towards this fix. If anything changed it was in cocoapods.

**Comment by mxcl** [comment]
Just to investigate this further I have been trying to reproduce the warnings for the UIKit extensions, and I cannot. No combination of Xcode settings or `Podfile` settings will produce these warnings for me. Maybe someone could provide me with a testcase?

**Comment by mxcl** [comment]
Maybe this will help in your `Podfile`:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'PromiseKit'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end
```

**Comment by ghowen** [comment]
The Xcode upgrade warning. I did update the `gem xcodeproj` today as Cocoapods suddenly started to throw an error.
