### ISSUE TITLE
[Obj-C]Promises further down the chain called before previous ones are fulfilled or rejected

### ISSUE THREAD

**Issue by ivan-konov** [mxcl/PromiseKit#930]
Environment: Xcode 10, PromiseKit 6.4.1
This only occurs in Objective-C. To illustrate the problem consider the following chain:

```
 [self firstMethodReturningAPromise].then(^(someValue){
            [weakSelf secondMethodReturningAPromise:location];
 }).then(^(someValue){
            [weakSelf thirdMethodReturningAPromise:location];
}).then(^(someValue){
            [weakSelf fourthMethodReturningAPromise:location];
 }).catch(^(NSError *error){
           error handling here
}).ensure(^{
           clean up here
});

```
For example the 3rd method might be called before the promise returned by the 2nd one is either fulfilled or rejected. This happens whenever there is asynchronous code inside the promise body.
The issue is NOT present if the same code is written in Swift. I worked around this problem in a previous occurrence by writing a helper class in Swift. However in my current case I would prefer to only do that as a last resort and I am curious to figure out the issue.

Thanks in advance!

**Comment by mxcl** [comment]
We have a lot of tests designed to prove that this doesn’t happen, so basically: cannot reproduce. Can you provide a test-case?

**Comment by mxcl** [comment]
I supplemented an existing test adding more subsequent calls. One can see they occur in order. Travis passed.

**Comment by ivan-konov** [comment]
I am unable to paste actual code here because of company trade secrets.
The 2 occurrences of this problem I had were connected to indirect dispatches to another thread like network calls or the Core Location geocoding API. I have promises written in Swift doing network calls on background threads and no problem.

**Comment by mxcl** [comment]
Oh, you forgot to `return`, this is why you are seeing the behavior you are seeing. If you don’t `return` the next `then` runs before the promise completes.

Easy mistake to make, in this time of Swift, where “implicit return” is a thing.

**Comment by mxcl** [comment]
```objective-c
[self firstMethodReturningAPromise].then(^(someValue){
    return [weakSelf secondMethodReturningAPromise:location];
}).then(^(someValue){
    return [weakSelf thirdMethodReturningAPromise:location];
}).then(^(someValue){
    return [weakSelf fourthMethodReturningAPromise:location];
}).catch(^(NSError *error){

}).ensure(^{

});
```

**Comment by ivan-konov** [comment]
(facepalm) thanks so much!

**Comment by mxcl** [comment]
nps, glad it wasn't more serious.
