### ISSUE TITLE
Not sure I installed correctly

### ISSUE THREAD

**Issue by dmesparza** [mxcl/PromiseKit#931]
Hi,

I am new to programming. Therefore, installing PromiseKit has been difficult for me. Upon investigating the various installation methods, I attempted to install via Carthage (unsuccessfully it turned out because than I had to figure out how to install Carthage, which I was never able to do). 

I then tried to install manually since it appeared simpler. While the instructions say to "You can just drop PromiseKit.xcodeproj into your project and then add PromiseKit.framework to your app’s embedded frameworks," even that is unclear to me.

I ended up dropping it here:

<img width="445" alt="screen shot 2018-09-30 at 5 15 30 pm" src="https://user-images.githubusercontent.com/24434716/46262810-8e0b0d80-c4d4-11e8-81fe-02389d6f6d2a.png">

This seemed to work because now when type "import" at the top of my ViewController.swift file, "PromiseKit" appears as a viable answer.

However, here is where things go bad. Based on the documentation, I expect to be able to write code like this:

`firstly {
    login()
}.then { creds in
    fetch(avatar: creds.user)
}.done { image in
    self.imageView = image
}`

So, I went to the code for the button in my app.

`@IBAction func AddElectionEvents(_ sender: UIButton) {
        deleteEvents()
        createEvents()
    }
}`

I want to use PromiseKit to first delete my events and then create new events. When I type "firstly", however, this is what I see:

<img width="541" alt="screen shot 2018-09-30 at 5 20 34 pm" src="https://user-images.githubusercontent.com/24434716/46262840-2acdab00-c4d5-11e8-91f8-415cf71c537f.png">

I expected to be able to write:

`firstly {
    deleteEvents()
}.then { 
   createEvents()
}.done {
}`

I'm feeling stuck. Can anyone help?

**Comment by mxcl** [comment]
You didn't install it manually.

Please use Carthage or CocoaPods if you are new to programming, doing it manually is definitely for advanced users.

**Comment by mxcl** [comment]
I suggest cocoapods for beginners, use homebrew to install it: https://brew.sh

Then do `brew install cocoapods`, then follow our cocopods instructions, please refer to CocoaPods documentation if you need to.

**Comment by dmesparza** [comment]
Thank you, that is exactly the direction I was looking for. Very helpful to me.

**Comment by mxcl** [comment]
I'll close, but if you need more help, feel free to reopen.
