### ISSUE TITLE
Trying to figure out how to use firstly{}

### ISSUE THREAD

**Issue by dmesparza** [mxcl/PromiseKit#939]
PromiseKit 6.5

Here's what I'm trying to do:

```
@IBAction func AddElectionEvents(_ sender: UIButton) {
        return firstly {
            deleteEvents()
        }.map {
            createEvents()
        }
    }
```

The user clicks a button, which causes deleteEvents() to trigger first, and then, once it's finished, createEvents() is triggered. 

Of course, Swift throws the error: "Cannot convert value of type '() -> ()' to expected argument type '() -> Guarantee<_>'"

Based on the [troubleshooting page](https://github.com/mxcl/PromiseKit/blob/master/Documentation/Troubleshooting.md), I thought that using .map instead of .then would fix this. However, the example on the troubleshooting page included more complex functions then I'm using. 

My respective functions delete events in a user's calendar, and creates them. Nothing is returned. Very cut and dried.

So, what do you think?

**Comment by mxcl** [comment]
You have no `return` on your function.

**Comment by mxcl** [comment]
Closing due to stagnation. Reopen if you still need assistance.
