### ISSUE TITLE
Installing manually PromiseKit with Extensions support

### ISSUE THREAD

**Issue by Marcin-Kapusta** [mxcl/PromiseKit#941]
I just read [here](https://github.com/mxcl/PromiseKit/blob/master/Documentation/Installation.md) that it is possible to install PromiseKit manually. Now I need to use it with some PromiseKit Extensions like CoreLocation. How can I do this using manual installation without CocoaPods or Carthage?

I just embedded PromiseKit project into my project and embedd PromiseKit framework. Normal features of PromiseKit works but I'm not sure how to enable extensions? Does anybody have idea?

I'm using PromiseKit 6.5.2 in xCode 9.4.1

--
Thanks in advance
Marcin

**Comment by mxcl** [comment]
1. Clone the extensions you want
2. Drag and drop the sources for the extensions you want into your project.

**Comment by mxcl** [comment]
We have some details about this here: https://github.com/mxcl/PromiseKit/blob/master/Documentation/Installation.md#using-git-submodules-for-promisekits-extensions

**Comment by mxcl** [comment]
Closing due to stagnation.
