### ISSUE TITLE
Cannot invoke 'then' with an argument list of type '((String, String) -> Promise<Data>)'

### ISSUE THREAD

**Issue by JamesSawley** [mxcl/PromiseKit#943]
PromiseKit Version: 6

I have a when(fulfilled: [Thenable]) that returns Promise<(String, String)>, however when I try to use these arguments in my 'then' block I receive the following error:

Cannot invoke 'then' with an argument list of type '((String, String) -> Promise<Data>)'

My code is as follows:

```
func fetchAll(includeClosed: Bool) -> Promise<AccountInformation> {
    return when(fulfilled: [auth.currentUserIdPromise(), auth.getIdToken()])
        .then { (uid, token) in self.db.get(userID: uid, uri: "accounts", token: token) }
        .then { /* Some more stuff */ }
   }
}
```

In case it isn't clear, auth.currentUserIdPromise() and auth.getIdToken() both resolve to String and db.get returns a promise.

Things I've tried:

- Explicitly expressing types
- Clean and build

Please can you help?

**Comment by mxcl** [comment]
This usually means one of the promises is returning a type that the next part of the chain is not using, or the chain itself returns a different type to what is specified `Promise<AccountInformation>`

If you provide the signatures for *all* the above functions I can probably help more.

**Comment by mxcl** [comment]
Well also you are using the wrong version of `when`, the version you are using takes an array and gives an array, so you cannot destructure it into a tuple, so instead use the tuple version of `when`:

```swift
func fetchAll(includeClosed: Bool) -> Promise<AccountInformation> {
    return when(fulfilled: auth.currentUserIdPromise(), auth.getIdToken())
        .then { (uid, token) in self.db.get(userID: uid, uri: "accounts", token: token) }
        .then { /* Some more stuff */ }
   }
}
```

**Comment by JamesSawley** [comment]
Ah! Thank you 👍

**Comment by mxcl** [comment]
Many thanks 👍🏻

If you found my work helpful, please consider [supporting its development](https://patreon.com/mxcl).
