### ISSUE TITLE
Apple Watch Extension failing - No such module "PromiseKit"

### ISSUE THREAD

**Issue by Guardiannw** [mxcl/PromiseKit#945]
* Please specify the PromiseKit major version you are using
6.5.2
* [Please format your code in triple backticks and ensure readable indentation](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

I am currently working on an Apple Watch app extension that uses PromiseKit.  I installed the project by following the instructions: Dragging the project into my project folder in xcode, then adding the embedded binary to both the iOS and Watchkit Extension project.

After a long time fumbling around, trying to figure out why it says, `No such module "PromiseKit"`, I was finally able to deploy it to a simulator after running a build for PromiseKit on that same device before deploying the WatchKit Extension.

Unfortunately, there appears to be no solution to solving this problem when running on the actual Apple Watch device, as it is not an option in the build configuration to build it on the device first.

Is this supposed to be expected behavior?  That it must be built on the device first?  Is there something that might be going wrong?

 I am using XCode 10.1 beta 3 BTW

Thank you very much,

**Comment by mxcl** [comment]
You should use CocoaPods. It manages this stuff for you. Manual installation is much harder to do.

**Comment by Guardiannw** [comment]
I would, but I really don't like CocoaPods.  I would prefer to use manual installation if at all possible.

**Comment by mxcl** [comment]
PromiseKit id no different to any other framework. There are resources online that describe how to install frameworks. Please note it is substantially more complicated once you have extensions like watch apps. I cannot provide support beyond Cocoapods and Carthage for free.

You can support [my Patreon](https://Patreon.com/mxcl) and I provide paid support.

I suggest googling and or stavkoverflow.com. Sorry.

**Comment by mxcl** [comment]
That's kind thanks 👍🏻. There are several things to watch for:

1. Check that PromiseKit is listed as a dependency in the build phases for both your iOS app and watch app targets (probably just the watch extension since the app is just a wrapper). See first screenshot, you'll want to tap the plus.
2. Check the framework search paths for both targets (see second screenshot)
3. Try building just PromiseKit.framework, you can select it from the target/platform chooser (third screenshot) select a Watch platform, if it builds then that is good news.

<img width="596" alt="screen shot 2018-10-19 at 6 26 47 pm" src="https://user-images.githubusercontent.com/58962/47246576-97e5a980-d3cc-11e8-8a24-76ba082b2b51.png">

<img width="596" alt="screen shot 2018-10-19 at 6 26 47 pm" src="https://user-images.githubusercontent.com/58962/47246597-c19ed080-d3cc-11e8-809c-2aca544d67c7.png">

<img width="596" alt="screen shot 2018-10-19 at 6 26 47 pm" src="https://user-images.githubusercontent.com/58962/47246617-ded39f00-d3cc-11e8-8af3-33a000a9de88.png">

**Comment by mxcl** [comment]
LMK if any of this works, we can work further based on your feedback.

**Comment by Guardiannw** [comment]
Thanks!  PromiseKit framework does build against the watch simulator, but the error still shows when building for the app extension for the physical device.  I had not previously specified any framework search paths, so I went ahead and filled that in, but that didn't solve it.  The framework had been placed automatically in the Target Dependencies slot when I added it to the Embedded Binaries, so that was good.

Note, it has worked fine for the iPhone build and run, no error ever.  I didn't even need to build for the iOS simulator first I don't believe.  But it simply won't run in in the build scheme for the watch target.

**Comment by Guardiannw** [comment]
Also, this might be of some value: I am able to replicate the issue by:

1. creating a new Watchkit project.
2. putting the PromiseKit repo folder in the $(SRCROOT) of the project folder
3. then dragging the PromiseKit xcodeproj file into the Xcode File browser above the project folder
4. and then adding the embedded binary to all targets.

When I try to run the extension to the simulator or the physical watch, I receive the `No such module "PromiseKit"` error

**Comment by mxcl** [comment]
I have created a new project with a watch app to try and replicate this, and indeed, Xcode won’t build the  watch version of PromiseKit in this scenario (strictly only for watch-app + iOS app).

I know why, we're using a hack to have a single target in the Xcodeproj for all platforms, and apparently, it doesn't work here.

As a workaround, in the PromiseKit node in your project: 

1. Duplicate the main target and name it `PromiseKit.watchOS`
2. In the build settings search for Supported Platforms and edit it, select only `watchOS`
3. Make your watch extension depend on this new target and not `PromiseKit`-vanilla.

It will now build.

I don't think this is acceptable, so I will be creating this target and adding it to the main release, this may take a few days however as I need to do a bunch of testing to make sure it doesn't break anything.

Sorry for this issue, hopefully Apple will support multiple platform frameworks better in Xcode 11.

PromiseKit 6.6 will have the fix.

**Comment by mxcl** [comment]
<img width="1112" alt="screen shot 2018-10-20 at 1 12 04 am" src="https://user-images.githubusercontent.com/58962/47251689-2aa23a80-d405-11e8-8557-8fec1bde1864.png">

Screenshot for reference.

**Comment by mxcl** [comment]
LMK if anything isn't clear.

**Comment by Guardiannw** [comment]
Thanks Max,

I believe I followed the instructions correctly, however, I am still having a couple of problems even on the test-case project.

When I try to build and run the `PromiseKit.watchOS` Target on the simulator, I now get a great many errors:

<img width="1574" alt="screen shot 2018-10-20 at 11 25 05 am" src="https://user-images.githubusercontent.com/6014316/47258012-f35e7880-d45a-11e8-987e-d94b69096278.png">

And then, when I changed out the dependency in the extension and tried to run on the device, I still get the same error:

<img width="1574" alt="screen shot 2018-10-20 at 11 27 20 am" src="https://user-images.githubusercontent.com/6014316/47258061-610aa480-d45b-11e8-8972-f6ba34e5bb2a.png">

Thank you very much for your continued help with this,

**Comment by mxcl** [comment]
Also note that when using PromiseKit in the watchOS target you will need to:

```
import PromiseKit_watchOS
```

This is ugly, but I don't think we should try to fix it until everything is working.

**Comment by Guardiannw** [comment]
Ok, for now I am only using PromiseKit in swift, so that should be ok.

However, it looks like it might still be doing the same thing on the build of the project, even after those changes.  I tried to clean the build folder, but no avail.

Here are some screenshots of the changes and the errors:

<img width="1574" alt="screen shot 2018-10-20 at 12 42 59 pm" src="https://user-images.githubusercontent.com/6014316/47258792-36721900-d466-11e8-9c0c-779fc744e459.png">
<img width="1574" alt="screen shot 2018-10-20 at 12 45 30 pm" src="https://user-images.githubusercontent.com/6014316/47258793-36721900-d466-11e8-8146-025fb6f06818.png">

**Comment by mxcl** [comment]
K, I did some more things and they seem necessary, for the `PromiseKit.watchOS` target:

1. Remove `AnyPromise.swift` from the *Compile Sources* build-phase
2. Add `SWIFT_PACKAGE` to *Active Compilation Conditions* build-setting

**Comment by mxcl** [comment]
You also need to remove this code from the end of `Resolver.swift` since the module name is now different:

```swift
public extension PromiseKit.Result {
    var isFulfilled: Bool {
        switch self {
        case .fulfilled:
            return true
        case .rejected:
            return false
        }
    }
}
```

**Comment by Guardiannw** [comment]
Ok, thank you!  I just tried it, and it built, but it still gave the same error when I imported it in my test project.  However, I then changed the Target, both in the import and in the Target list for PromiseKit (instead of just in the import statement), to `PromiseKit_watchOS` instead of `PromiseKit.watchOS` and then it worked from there.

This is an interesting issue, do you know why this was happening?

**Comment by Guardiannw** [comment]
Hey @mxcl, I am about to upgrade to the latest code from PromiseKit.  Have you been able to implement these fixes out of the box?  Or will I need to go through and adjust?

Thanks!

**Comment by mxcl** [comment]
I couldn’t get it working well. I’ll take another stab today.

**Comment by mxcl** [comment]
Seeing if this passes CI: #1010

**Comment by mxcl** [comment]
It passed, can you try the branch?

**Comment by mxcl** [comment]
Re-open if you want this still.
