### ISSUE TITLE
is tap called for cancellation errors?

### ISSUE THREAD

**Issue by Igor-Palaguta** [mxcl/PromiseKit#948]
Hello,

Have a small question, is tap called for cancellation errors? Looks like cancelation error is just checked inside `catch`

**Comment by Igor-Palaguta** [comment]
Just checked and it is called for cancelled errors also. `recover` and `catch` handles properly it

**Comment by Igor-Palaguta** [comment]
Please check https://github.com/mxcl/PromiseKit/pull/949

**Comment by Igor-Palaguta** [comment]
Also one of recovers that returns Guarantee does not check cancellation

**Comment by mxcl** [comment]
`tap` and `ensure` are called for all errors by design.

`tap` is for debug purposes, and `ensure` is a guaranteed handler for everything, including cancellation.

**Comment by Igor-Palaguta** [comment]
In case if it is needed catchPolicy can be passed the same like in catch and recover
We are using tap not just for debug

**Comment by Igor-Palaguta** [comment]
We added:
```
extension Thenable {
    public func takeWhileAlive(_ object: AnyObject) -> Promise<T> {
        return map { [weak object] result in
            guard let object = object else {
                throw PMKError.cancelled
            }
            _ = object
            return result
        }
    }
}
```
And then we can use unowned references, without writing guard let everytime
```
promise
   .takeWhileAlive(self)
   .tap { [unowned self] _ in /**/ }
   .ensure { [unowned self] /**/ }
   .catch {[unowned self] _ in /**/}

```

**Comment by mxcl** [comment]
Can you please provide usage examples justifying this desired feature?

**Comment by Igor-Palaguta** [comment]
Also not clear why for one recover cancelation is handler, but for second - not

**Comment by mxcl** [comment]
> Also not clear why for one recover cancelation is handler, but for second - not

Can you please provide a link to the recover you refer to which is incorrect.

**Comment by Igor-Palaguta** [comment]
https://github.com/mxcl/PromiseKit/blob/master/Sources/Catchable.swift#L109

**Comment by mxcl** [comment]
Hi, this recover returns a `Guarantee`, guarantees cannot error, so it is logically impossible for this `recover` to be able to ignore some kinds of error.

Please note the documentation for this function explicitly states this.

**Comment by Igor-Palaguta** [comment]
But if we throw cancel error above, why do we need recover anything?

**Comment by Igor-Palaguta** [comment]
Currently there is no way stop to chain. Cancel looked like the one way to do it. But strategy for handling is not shared among all handlers. It would be great if we have common

**Comment by mxcl** [comment]
> But if we throw cancel error above, why do we need recover anything?

If you don’t want to `recover` cancellations in such a chain use the other variant of `recover` that returns a `Promise`.

As said, this variant is provided so you can recover *everything* and return a `Guarantee`, this implies that you are also recovering cancellations.

If you don't want to recover cancellations use the `recover` variant that returns `Promise`.

**Comment by mxcl** [comment]
To clarify my position, I am not against this feature, however I would like to see usage examples so I can understand your need.

Also we cannot break existing code, so the catch-policies for both `tap` and `ensure` would have to be defaulted to `allErrors`.

**Comment by mxcl** [comment]
IMO, there is no sensible catch-policy situation for these functions, they are designed to be called in all scenarios, especially `ensure`. It would be confusing to add the parameter to them thus reducing the clarity of our API. A user would wonder why a function that has no relation to catching or errors has a catch-policy.

**Comment by mxcl** [comment]
I am remiss: thank you for your effort and the thought here though. I suggest in future though, opening the ticket before making the pull request to save potentially wasted effort.
