### ISSUE TITLE
I'm confused about `PMKUnambiguousInitializer`

### ISSUE THREAD

**Issue by lacklock** [mxcl/PromiseKit#950]
During reading source code, I saw Promise and Guarantee have special init method:
```
    init(_: PMKUnambiguousInitializer) {
        box = EmptyBox()
    }
```
I remove PMKUnambiguousInitializer, using default init method to init, code is still running good. 
I don't know why there need a useless parameter PMKUnambiguousInitializer.

**Comment by mxcl** [comment]
This is a private method. And if you remove it PMK won’t compile. So I don’t recommend it.
