### ISSUE TITLE
Promise Kit 6 AWSTask Extension is not thenable

### ISSUE THREAD

**Issue by bennnjamin** [mxcl/PromiseKit#951]
I have taken the BFTask extension and changed it to use AWSTask instead like below:

```swift
import PromiseKit
import AWSCore

extension Promise {
    /**
     The provided closure is executed when this promise is resolved.
     */
    public func then<U>(on q: DispatchQueue? = conf.Q.map, body: @escaping (T) -> AWSTask<U>) -> Promise<U?> {
        return then(on: q) { tee -> Promise<U?> in
            let task = body(tee)
            return Promise<U?> { seal in
                task.continueWith(block: { task in
                    if task.isCompleted {
                        seal.fulfill(task.result)
                    } else if let error = task.error {
                        seal.reject(error)
                    } else {
                        seal.reject(PMKError.invalidCallingConvention)
                    }
                    return nil
                })
            }
        }
    }
}
```

When I use an AWS SDK method and try to call then(), I get this error ```Value of type 'AWSTask<AWSCredentials>' has no member 'then'```

So then I thought, lets extend AWSTask to add a then function:

```swift
extension AWSTask {
    func then<U: AnyObject>(_: PMKNamespacer, task: AWSTask<U>) -> Promise<U> {
        return Promise { seal in
            task.continueWith(block: { (task) -> Any? in
                if let res = task.result {
                    seal.fulfill(res)
                } else if let error = task.error {
                    seal.reject(error)
                } else {
                    seal.reject(PMKError.invalidCallingConvention)
                }
                return nil
            })
        }
    }

}
```

This does not compile with error ```Extension of a generic Objective-C class cannot access the class's generic parameters at runtime``` possibly a swift compiler bug that's 2 years old (https://bugs.swift.org/browse/SR-1576, https://bugs.swift.org/browse/SR-2708).

My last attempt was to just make a global func that could take an AWSTask and return a promise. Obviously a global func is not ideal and I'm looking for a better solution but it works, here it is:

```swift
public func PromisifyAWSTask<U: AnyObject>(_: PMKNamespacer, task: AWSTask<U>) -> Promise<U> {
    return Promise { seal in
        task.continueWith(block: { (task) -> Any? in
            if let res = task.result {
                seal.fulfill(res)
            } else if let error = task.error {
                seal.reject(error)
            } else {
                seal.reject(PMKError.invalidCallingConvention)
            }
            return nil
        })
    }
}
```

Xcode 10
Swift 4.2
PromiseKit 6

**Comment by mxcl** [comment]
AWSTask [doesn't seem to derive BFTask](https://github.com/aws/aws-sdk-ios/blob/master/AWSCore/Bolts/AWSTask.h), so that’s why it has no `then`.

I believe this is possible because we do it ourselves here and we have CI that proves this compiles and can be used:

https://github.com/PromiseKit/Bolts/blob/master/Sources/BFTask%2BPromise.swift

Is it intentional that your `then` can only “then” with other AWSTasks? I would have thought you'd want it to then with a closure that returns a `Promise` like is typical for `then`.

**Comment by bennnjamin** [comment]
@mxcl That's correct, which is why in my code snippet above I changed all instances of ```BFTask``` to ```AWSTask```, and ```AWSTask``` still has no ```then```. Perhaps I'm missing something else.

The first code snippet does compile, however, it's the second snippet where I am adding an extension to ```AWSTask``` directly. You do not add an extension to ```BFTask``` directly but to ```Promise``` instead which should be enough. That's why I'm having trouble figuring out why just copying the ```BFTask``` and changing it to use ```AWSTask``` does not work

No, I'm pretty new to the framework and certainly would want a typical then but can't get it to work by simply modifying the ```BFTask``` extension.

**Comment by mxcl** [comment]
Oh OK, well in your first example AWSTask doesn’t have `then`, it's an extension of Promise, you will need to return AWSTask in a `then` off a promise for that one to work.

Perhaps the second example indeed will never compile.

I suggest something like:

```swift
Promise().then {
    return awsTask
}.then {
    //…
}
```

Using your first code example.

**Comment by bennnjamin** [comment]
I see so can I use ```Promise()``` like a ```Void```, always fulfilled promise to start a chain of ```AWSTask```s? That would work pretty well. What do you think of third example as far as an approach? I really wish I could add a ```then``` to ```AWSTask``` as that would be the most syntactically clear, and a pretty useful extension.

**Comment by mxcl** [comment]
> I see so can I use Promise() like a Void, always fulfilled promise to start a chain of AWSTasks?

It's a hack, but if the AWSTask extension won't compile then it'll do.

>  What do you think of third example as far as an approach?

Whatever works and you like is good IMO.

> I really wish I could add a then to AWSTask as that would be the most syntactically clear, and a pretty useful extension.

It's a shame Swift hasn't fixed this objc-generics/swift-bridge issue yet.

**Comment by bennnjamin** [comment]
Thanks for all of your help, I'm closing this issue. If you think this would be a useful extension to PromiseKit I'd be happy to assist with that.

**Comment by mxcl** [comment]
> If you think this would be a useful extension to PromiseKit I'd be happy to assist with that.

You can add a PMKAWSKit to https://github.com/PromiseKit if you want. Though we may be better off just adding it as a snippet to this repo and linking there.

Glad to have helped, if you found my work helpful, please consider [supporting its development](https://patreon.com/mxcl).

**Comment by bennnjamin** [comment]
Agreed on it being a snippet seeing as it’s so similar to BFTask.

**Comment by mxcl** [comment]
If you want to submit it, add it the Documentation directory on this repo under a new folder “Snippets”
