### ISSUE TITLE
'Symbol not found'?

### ISSUE THREAD

**Issue by frizzy75** [mxcl/PromiseKit#952]
* PromiseKit 6.5.2
* Xcode 10.0 (10A255)
* Swift 4.2
* Carthage for dependency management
* A 3rd party framework whose Cartfile contains:

```
github "mxcl/PromiseKit" ~> 6.0
github "PromiseKit/Foundation" ~> 3.0
```

And my project's resulting Cartfile.resolved file contains:
```
github "PromiseKit/Foundation" "3.3.0"
github "mxcl/PromiseKit" "6.5.2"
github "realm/realm-cocoa" "v3.11.1"
# ... (some other stuff)
```

My app compiles fine, but immediately crashes with the error below. If I read the error right, then the 3rd party framework is expecting to find the `URLRequest` extension method in `PromiseKit.framework` rather than in `PMKFoundation.framework`? 

```
dyld: Symbol not found: _$S10Foundation10URLRequestV10PromiseKit0B11ConvertibleADWP
  Referenced from: /Users/XXXX/Library/Developer/CoreSimulator/Devices/37D783DD*/data/Containers/Bundle/Application/4073D393*/XXXXX.app/Frameworks/XXXXX.framework/XXXXX
  Expected in: /Users/XXXXX/Library/Developer/CoreSimulator/Devices/37D783DD*/data/Containers/Bundle/Application/4073D393*/XXXXX.app/Frameworks/PromiseKit.framework/PromiseKit
 in /Users/XXXXX/Library/Developer/CoreSimulator/Devices/37D783DD*/data/Containers/Bundle/Application/4073D393*/XXXX.app/Frameworks/XXXXX.framework/XXXXX

```

Thanks

**Comment by mxcl** [comment]
Let’s verify: 

1. That both PromiseKit.framework and PMKFoundation.framework are in both the link and embed parts of your project settings.
2. That you are importing both `PromiseKit` and `PMKFoundation` in any places you are using PromiseKit’s Foundation extensions

Can you confirm how many targets your app has, and the platforms you are targeting.

**Comment by frizzy75** [comment]
@mxcl:
1. Both PromiseKit.framework and PMKFoundation.framework are in the "Linked Frameworks and Libraries" section of the target's "General" tab. But if I add them to the "Embedded Binaries" section, too, then the project doesn't compile.
2. I've removed all calls that required importing PromiseKit or PMKFoundation, and the import statements; cleaned the build directory, deleted derived data, and restarted Xcode and the app in simulator is still crashing.
3. I have 2 targets, one of which is test target
4. Targeting only iPhone, with iOS 12.

Thanks

**Comment by mxcl** [comment]
They must both be in the embedded binaries section, what issue do you get if you add them there.

**Comment by frizzy75** [comment]
The compiler error results from conflict with the 'Run Script' phase I set up, per Carthage's instructions. The error is:

```
error: Multiple commands produce '/Users/frizzy/Library/Developer/Xcode/DerivedData/XXXX*/Build/Products/Debug-iphonesimulator/XXXXX.app/Frameworks/PMKFoundation.framework':
1) Target 'XXXXX' has copy command from '/Users/frizzy/Documents/Projects/XXXXX/Carthage/Build/iOS/PMKFoundation.framework' to '/Users/frizzy/Library/Developer/Xcode/DerivedData/XXXXX*/Build/Products/Debug-iphonesimulator/XXXXX.app/Frameworks/PMKFoundation.framework'
2) That command depends on command in Target 'XXXXX': script phase “Run Script”
```

**Comment by mxcl** [comment]
Delete that script, does it work now?

**Comment by frizzy75** [comment]
@mxcl The project does compile now, but the app still crashes with same error

**Comment by mxcl** [comment]
Have you tried rebuilding the frameworks with `carthage bootstrap`? Could be the binaries are old and Swift is not ABI compatible.

**Comment by frizzy75** [comment]
@mxcl I tried rebuilding all frameworks with `carthage bootstrap` -- same result: app crashes with `symbol not found` error.

**Comment by mxcl** [comment]
> My app compiles fine, but immediately crashes with the error below. If I read the error right, then the 3rd party framework is expecting to find the URLRequest extension method in PromiseKit.framework rather than in PMKFoundation.framework?

Do you have some third party framework that uses PromiseKit?

**Comment by frizzy75** [comment]
@mxcl yes - that framework has a Cartfile that looks like this:

```
github "mxcl/PromiseKit" ~> 6.0
github "PromiseKit/Foundation" ~> 3.0
```

**Comment by mxcl** [comment]
Is that framework binary only, did it get compiled from source in the same `carthage bootstrap` operation?

Check it is also getting correctly installed, then go to the folder it is installed into and run:

```
otool -L foo.framework/foo
```

Let’s examine the output.

**Comment by frizzy75** [comment]
@mxcl will do - that framework was compiled from source in the same `carthage bootstrap` operation. Thanks.

**Comment by mxcl** [comment]
Sorry I wasn't specific, I need the same command run but on the installed version, in the built .app bundle.

**Comment by mxcl** [comment]
It is odd that it doesn't link to PMKFoundation though. If it uses it that is. Is it possible it has a vendor copy of PromiseKit it builds with?

**Comment by frizzy75** [comment]
@mxcl - hopefully I did it right this time; ran `otool` in the derived data directory and got the output below. Again seems that `PMKFoundation` is not included. 

What is a 'vendor copy of PromiseKit'? -- I know the framework was built from the Github source here, and originally with Cocoapods in mind. Carthage supported was added more recently. Does it look like the framework's Carthage configuration is off?

Thanks

```
$ pwd
/Users/frizzy/Library/Developer/Xcode/DerivedData/XXXXX/Build/Products/Debug-iphonesimulator/XXXXX.app/Frameworks

$ otool -L Foo.framework/Foo
Foo.framework/Foo:
	@rpath/Foo.framework/Foo (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Foundation.framework/Foundation (compatibility version 300.0.0, current version 1556.0.0)
	@rpath/PromiseKit.framework/PromiseKit (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
	/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation (compatibility version 150.0.0, current version 1556.0.0)
	/System/Library/Frameworks/SafariServices.framework/SafariServices (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Security.framework/Security (compatibility version 1.0.0, current version 58286.202.3)
	/System/Library/Frameworks/UIKit.framework/UIKit (compatibility version 1.0.0, current version 61000.0.0)
	@rpath/libswiftCore.dylib (compatibility version 1.0.0, current version 1000.11.37)
	@rpath/libswiftCoreFoundation.dylib (compatibility version 1.0.0, current version 1000.11.37)
	@rpath/libswiftCoreGraphics.dylib (compatibility version 1.0.0, current version 1000.11.37)
	@rpath/libswiftCoreImage.dylib (compatibility version 1.0.0, current version 1000.11.37)
	@rpath/libswiftDarwin.dylib (compatibility version 1.0.0, current version 1000.11.37)
	@rpath/libswiftDispatch.dylib (compatibility version 1.0.0, current version 1000.11.37)
	@rpath/libswiftFoundation.dylib (compatibility version 1.0.0, current version 1000.11.37)
	@rpath/libswiftMetal.dylib (compatibility version 1.0.0, current version 1000.11.37)
	@rpath/libswiftObjectiveC.dylib (compatibility version 1.0.0, current version 1000.11.37)
	@rpath/libswiftQuartzCore.dylib (compatibility version 1.0.0, current version 1000.11.37)
	@rpath/libswiftUIKit.dylib (compatibility version 1.0.0, current version 1000.11.37)
```

**Comment by mxcl** [comment]
Oh ok, sounds like the third party framework expects CocoaPods then. with CocoaPods everything is built into PromiseKit.framework, including the PMKFoundation extensions.

Sounds like they are giving you a binary framework, otherwise I don't see how it could be in this state.

I don't really know enough other details to offer more specific advise, but they shouldn't be building a binary (if that is what is happening) which is built with CocoaPods, since that ties you to CocoaPods, they should build it using Xcode, we support that, for this purpose explicitly.

**Comment by frizzy75** [comment]
@mxcl they support both Carthage and CocoaPods; I was just thinking maybe the Carthage support isn't entirely correct. It did work fine for me in another CocoaPods project *and* another Carthage project - but that was before I upgraded to Xcode 10 so there are still too many variables for me to figure this out...
Thank you for your help.

**Comment by mxcl** [comment]
It certainly seems like they have given you a binary that linked against a pod-built PromiseKit. But it’s hard to say. I prefer Carthage personally but you may have better luck using pods here.

**Comment by frizzy75** [comment]
@mxcl Thank you - I appreciate the help. I may give up and go with CocoaPods.

**Comment by mxcl** [comment]
Sorry I want more use. LMK how it goes.

**Comment by frizzy75** [comment]
@mxcl I finally got it to work. I forked the 3rd party framework and made some corrections & changes. The key was changing the framework's Podspec dependency from `PromiseKit` to `PromiseKit/CorePromise` after reworking the code so it didn't require the `PromiseKit/Foundation` `URLSession` extension -- I couldn't get it work with the `PMKFoundation` extension.

If useful, I'd contribute a pull request with code sample for others who are trying to create a framework that depends on PromiseKit and properly supports both Carthage and CocoaPods -- at least without any PromiseKit extensions. I'd need some help with syntax to support the extensions.

Thank you again very much for your help, your responsiveness and for creating & maintaining the great PromiseKit!

**Comment by mxcl** [comment]
Thanks but I don't think it would be much use, this third party is packaging their framework wrongly, anyone who follows the instructions CocoaPods and Carthage provide wouldn't provide a framework in this mixed and failing state. You should report the bug to them.

**Comment by frizzy75** [comment]
I have reported it.

**Comment by mxcl** [comment]
I would certainly be interested in learning what it is they are doing exactly, so if there's anything for us to do to mitigate it I can. I would be surprised if how they package for Carthage is legitimate, I expect they are building a binary using CocoaPods and distributing that, which really, is a hack, and they have suffered the consequences here with your wasted time.

**Comment by frizzy75** [comment]
It's not a binary - I was always rebuilding from source. I also had multiple issues with Xcode's new build system, another framework that was acting up, etc etc. So still not sure about the root cause - may very well have been on my side. It's working now, so far, so I'm moving forward.

**Comment by mxcl** [comment]
OK, well thanks, and if you found my work and assistance here helpful, please consider [supporting PromiseKit’s development](https://patreon.com/mxcl).

**Comment by frizzy75** [comment]
Will do!
