### ISSUE TITLE
hot patch(jspatch)  & PromiseKit

### ISSUE THREAD

**Issue by zhuxiaohan** [mxcl/PromiseKit#953]
i use hot patch(jspatch) to solve problem code that use Promisekit, and the callback block "then" "catch" can not callback, why????? 
Thanks

**Comment by mxcl** [comment]
Please provide the example code that fails.

**Comment by zhuxiaohan** [comment]
> Please provide the example code that fails.

 i use the old version promisekit (version 4), this is example code( js patch code):

//
SKPromise.promiseWithResolver(block('NSBlock*', function(resolve) {
            var strongSelf = __strong(weakSelf);

            AppDelegate.printLog("TRIPSessionSendUserInfoProcessor send start");
            var task = SKModuleTask.alloc().initWithScheme_module_processor_params("native", "mtop", "mtop_normal_sign", paramas);
            strongSelf.sendModuleTask_parentTask_resolver(task, parentTask, resolve);
            AppDelegate.printLog("TRIPSessionSendUserInfoProcessor send end");

        })).then()(block('id,SKModuleTask*', function(result, task) {
            AppDelegate.printLog("TRIPSessionSendUserInfoProcessor then");
            alert("then");
            parentTask.taskResolve_task(null, task);

        })).catch()(block('SKPromiseError*', function(error) {
            alert("catch");
            AppDelegate.printLog("TRIPSessionSendUserInfoProcessor catch");
            parentTask.taskResolve(error);

        }));
//

**Comment by mxcl** [comment]
I'm sorry I have no experience with JSPatch, I don’t know how it works or have heard of it and cannot help you.

**Comment by zhuxiaohan** [comment]
> I'm sorry I have no experience with JSPatch, I don’t know how it works or have heard of it and cannot help you.

thanks again
