### ISSUE TITLE
.ensure may fire before .catch block completes

### ISSUE THREAD

**Issue by neallester** [mxcl/PromiseKit#962]
Is this the intended behavior?

```swift
extension CatchableTests {

    func testCatchRace() {
        var runCount = 0
        while runCount < 10 {
            var caughtError = false
            var succeeded = false
            let dataQueue = DispatchQueue(label: "dataQueue")
            let workQueue = DispatchQueue(label: "workQueue", attributes: .concurrent)
            let firstThrows = arc4random_uniform(2) == 0
            let expectation1 = expectation(description: "1")
            let expectation2 = expectation(description: "2")
            firstly { () -> Promise<Int> in
                let p = Promise<Int>.pending()
                workQueue.async {
                    usleep(arc4random_uniform(100000))
                    if firstThrows {
                        p.resolver.reject(Error.dummy)
                    } else {
                        dataQueue.sync {
                            succeeded = true
                        }
                        p.resolver.fulfill(1)
                    }
                }
                return p.promise
            }.done { result in
                XCTAssertEqual (result, 1)
            }.ensure {
                expectation1.fulfill()
            }.catch { error in
                dataQueue.sync {
                    caughtError = true
                }
            }
            firstly { () -> Promise<Int> in
                let p = Promise<Int>.pending()
                workQueue.async {
                    usleep(arc4random_uniform(100000))
                    if !firstThrows {
                        p.resolver.reject(Error.dummy)
                    } else {
                        dataQueue.sync {
                            succeeded = true
                        }
                        p.resolver.fulfill(2)
                    }
                }
                return p.promise
            }.done { result in
                XCTAssertEqual (result, 2)
            }.ensure {
                expectation2.fulfill()
            }.catch { error in
                dataQueue.sync {
                    caughtError = true
                }
            }
            waitForExpectations(timeout: 10.0, handler: nil)
            dataQueue.sync {
                if !caughtError || !succeeded {
                    print ("runCount: \(runCount)")
                }
                XCTAssertTrue (caughtError, "caughtError")
                XCTAssertTrue (succeeded, "succeeeded")
            }
            runCount = runCount + 1
        }
    }
}
```

**Output**

Test Case '-[PMKCoreTests.CatchableTests testCatchRace]' started.
runCount: 1
/Users/neal/xcode/PromiseKit/Tests/CorePromise/CatchableTests.swift:324: error: -[PMKCoreTests.CatchableTests testCatchRace] : XCTAssertTrue failed - caughtError
runCount: 3
/Users/neal/xcode/PromiseKit/Tests/CorePromise/CatchableTests.swift:324: error: -[PMKCoreTests.CatchableTests testCatchRace] : XCTAssertTrue failed - caughtError
runCount: 4
/Users/neal/xcode/PromiseKit/Tests/CorePromise/CatchableTests.swift:324: error: -[PMKCoreTests.CatchableTests testCatchRace] : XCTAssertTrue failed - caughtError
runCount: 5
/Users/neal/xcode/PromiseKit/Tests/CorePromise/CatchableTests.swift:324: error: -[PMKCoreTests.CatchableTests testCatchRace] : XCTAssertTrue failed - caughtError
runCount: 9
/Users/neal/xcode/PromiseKit/Tests/CorePromise/CatchableTests.swift:324: error: -[PMKCoreTests.CatchableTests testCatchRace] : XCTAssertTrue failed - caughtError
Test Case '-[PMKCoreTests.CatchableTests testCatchRace]' failed (0.737 seconds).

**Comment by mxcl** [comment]
This is hard to understand, can you succinctly explain your question?

**Comment by neallester** [comment]
When chaining promises, the closure in the .ensure block may or may not
fire before the closure in the .catch block. This is not the behavior I was
expecting. I expected them to fire in a deterministic order: ensure last. I
wanted to confirm that the observed behavior is consistent with your design
intention. If not, the test is there to demonstrate the issue.

**Comment by mxcl** [comment]
This still isn't clear to me. I will provide examples and you can tell me if I have it right:

```swift
foo.ensure {
}.catch {
}
```

Here ensure will always fire first, closures fire in the order they are added to the chain.

**Comment by neallester** [comment]
Yes, I see and that makes sense. I need to use PMKFinalizer.finally() not .ensure. 

It was the function name "cleanup()" in the CommonPatterns.Chaining section of the documentation which gave me the clearly incorrect impression that ensure would run after catch (because in my mind cleaning up is something you do last).

I think adding a .finally block to that example would make it less likely for a reader to confuse the functionality of .ensure with .finally.

**Comment by mxcl** [comment]
K thanks 👍🏻 I’ll amend the docs to make this clearer. 

If you found my work helpful, please consider [supporting its development](https://patreon.com/mxcl). You
