### ISSUE TITLE
Migrated PK4 to PK6, now everything crashes

### ISSUE THREAD

**Issue by SolorzanoJose** [mxcl/PromiseKit#964]
I am using the latest version of PK6, after migrating all my code to the new "Seal", everything is crashing : 

``
private func getAuthInfo() -> Promise<UserInfo> {
        return Promise { seal in
            seal.fulfill(UserInfo())
        }
    }
``

As soon as I call getAuthInfo().then or done, the app crashes with SIGABRT

**Comment by mxcl** [comment]
Please provide the crash log.

**Comment by SolorzanoJose** [comment]
@mxcl I'm getting `SIGABRT`, no crash log, this is the last call in thread 1:

``
dyld`__abort_with_payload:
    0x1057062f0 <+0>:  mov    x16, #0x209
    0x1057062f4 <+4>:  svc    #0x80
->  0x1057062f8 <+8>:  b.lo   0x105706310               ; <+32>
    0x1057062fc <+12>: stp    x29, x30, [sp, #-0x10]!
    0x105706300 <+16>: mov    x29, sp
    0x105706304 <+20>: bl     0x105705990               ; cerror_nocancel
    0x105706308 <+24>: mov    sp, x29
    0x10570630c <+28>: ldp    x29, x30, [sp], #0x10
    0x105706310 <+32>: ret    

``

**Comment by mxcl** [comment]
How about a screenshot of the backtrace.

**Comment by SolorzanoJose** [comment]
<img width="1407" alt="screen shot 2018-12-03 at 9 43 42 pm" src="https://user-images.githubusercontent.com/42447389/49412935-9ede3680-f744-11e8-9dea-856dd602d534.png">

This is just one example, it happens for all couple hundred promises in my codebase

**Comment by mxcl** [comment]
It's crashing in the dynamic linker which suggests to me the binary for PromiseKit is corrupt. You didn't specify how you installed PromiseKit, whichever method you used, clean it, and rebuild it. Ensure all build artifacts are cleaned including your app.

**Comment by SolorzanoJose** [comment]
@mxcl I've uninstalled the app from the device, cleaned build folder and removed derived data, should I do something else? I'm using PK6 through cocoapods

**Comment by mxcl** [comment]
You should delete the Pods directory, and then deintegrate and reintegrate. Of course, quit Xcode first.

**Comment by SolorzanoJose** [comment]
@mxcl using the cocoapods-deintegrate tool? I will give it a shot

thanks man, you are really helpful

**Comment by mxcl** [comment]
nps lmk if it doesn't work.

**Comment by mxcl** [comment]
Make sure to clean Xcode before reintegrating.

Deleting all Derived Data may help too (in Terminal):

    rm -rf ~/Library/Developer/Xcode/DerivedData

**Comment by SolorzanoJose** [comment]
Thanks, it worked @mxcl

**Comment by mxcl** [comment]
Great 👍🏻

If you found my work helpful, please consider [supporting its development](https://patreon.com/mxcl).

**Comment by SolorzanoJose** [comment]
@mxcl just out of curiosity, the pod reintegrate tool doesn't exist, you mean't regular por install? cheers

**Comment by mxcl** [comment]
Yes. Just `install`.
