### ISSUE TITLE
How to return different promise in a then closure?

### ISSUE THREAD

**Issue by YiYiZheng** [mxcl/PromiseKit#965]
```
firstly {
    UIDevice.microphoneAuthorized()
}.then {
    UIDevice.cameraAuthorized()
}.then {
    UIDevice.checkNetworkOnWifi()
}.then { isOnWifi in
    if isOnWifi {
        return Promise.value(true)
    } else {
        return viewController.showAlertView(content: "Are you sure?", cancelTitle: "exit", confirmTitle: "confirm")
    }
}.done { success in
   .....
}.catch { error in
   .....
}
```

The code above compiled error. 
As you can see, in the third `then` closure after having checked whether the device is on Wifi. If is  on Wifi, fine, continue to next closure. On the opposite, I just want to show an alertView to let user confirm. The `showAlertView` method will also return a Promise<Bool>. After user selects an option, I still want to continue the chain. 
Throw an `Error` may seem not to be a solution in this case.
Could you pls give some advice on how to achieve this feature? Thx very much.

**Comment by mxcl** [comment]
Looks fine, what’s the error?

**Comment by YiYiZheng** [comment]
Ambiguous reference to member 'firstly(execute:)'. 
When I just replace
```
if isOnWifi {
        return Promise.value(true)
    } else {
        return viewController.showAlertView(content: "Are you sure?", cancelTitle: "exit", confirmTitle: "confirm")
    }
```
with 
```
return Promise.value(true)
```

Which means only return one promise, It was all right..

**Comment by mxcl** [comment]
Specify the return type for that `.then`. This solution and others provided in our 
[Troubleshooting Guide](https://github.com/mxcl/PromiseKit/blob/master/Documentation/Troubleshooting.md).

**Comment by mxcl** [comment]
```swift
firstly {
    UIDevice.microphoneAuthorized()
}.then {
    UIDevice.cameraAuthorized()
}.then {
    UIDevice.checkNetworkOnWifi()
}.then { isOnWifi -> Promise<Bool> in
    if isOnWifi {
        return .value(true)
    } else {
        return viewController.showAlertView(content: "Are you sure?", cancelTitle: "exit", confirmTitle: "confirm")
    }
}.done { success in
   //…
}.catch { error in
   //…
}
```

**Comment by YiYiZheng** [comment]
Yes, it works. Thanks.

**Comment by mxcl** [comment]
Great 👍🏻

If you found my work helpful, please consider [supporting its development](https://patreon.com/mxcl).
