### ISSUE TITLE
Runtime Warnings with PromiseKit/Alamofire GET Request

### ISSUE THREAD

**Issue by Empiezan** [mxcl/PromiseKit#967]
I realize this issue may be off-topic, but I am unable to pin down the exact cause of two runtime warnings that are associated with my PromiseKit/Alamofire GET Request.

I installed PromiseKit/CorePromise and PromiseKit/Alamofire from Cocoapods.

I have the following method for performing GET requests with PromiseKit/Alamofire:

```
    func getRequest<T: Decodable>(url: String, params: Parameters? = nil, type: T.Type) -> Promise<T> {
        
        let headers: HTTPHeaders = [
            "Authorization": "Bearer " + (SessionManager.shared.credentials?.accessToken ?? ""),
            "Accept": "application/json"
        ]
        
        let requestURL = Server_Url + url
        
        return firstly {
            Alamofire.request(requestURL, method: .get, parameters: params, headers: headers)
                .validate(statusCode: 200..<300)
                .validate(contentType: ["application/json"])
                .responseJSON()
            }.map { (arg) -> T in
                let (_, response) = arg
                guard let getData = response.data else {
                    throw NetworkControllerError.NilResultError
                }
                let decodedData = self.decodeJson(data: getData, type: type.self)
                if decodedData == nil {
                    throw NetworkControllerError.DecodingError
                }
                return decodedData!
            }
    }
```

Using Xcode's breakpoints, I found that the following runtime warnings would appear directly after the Alamofire request was finished. I realize that other processes might be occurring at the same time on other threads, but I'm not sure how to resolve these issues. Can anyone point me in the right direction?

```
objc[24119]: Class _TtGCs23_ContiguousArrayStorageFT_T__ is implemented in both ?? (0x7fdf3b08a870) and ?? (0x7fdf380f5638). One of the two will be used. Which one is undefined.
```
and
```
[framework] CUICatalog: Invalid asset name supplied: ''
```

**Comment by mxcl** [comment]
The first warning is a Swift symbol: https://developer.apple.com/documentation/swift/contiguousarray

This suggests you maybe have a build system issue that is causing 2 versions of some swift symbols to be used in your final binary. Not PromiseKit related.

The second is related to XCAssets management. Not PromiseKit related.

**Comment by Empiezan** [comment]
Thank you! This helps a lot.
