### ISSUE TITLE
Addition of print stmt breaks sample code in common patterns

### ISSUE THREAD

**Issue by brynjar** [mxcl/PromiseKit#968]
Version 6, with XC 9.4.1 (also 10.1)

Following your sample code https://github.com/mxcl/PromiseKit/blob/master/Documentation/CommonPatterns.md
the following compiles:

```
import Foundation
import PromiseKit

class User {
    let imageUrl: URLRequestConvertible = URL(string: "")!
    init(dict: [String: Any]) {
    }
}

let url = URL(string: "")!

class MyRestAPI {
    func user() -> Promise<User> {
        return firstly {
            URLSession.shared.dataTask(.promise, with: url)
            }.compactMap {
                try JSONSerialization.jsonObject(with: $0.data) as? [String: Any]
            }.map { dict in
                User(dict: dict)
        }
    }
    
    func avatar() -> Promise<UIImage> {
        return user().then { user in
            //print(user)
            URLSession.shared.dataTask(.promise, with: user.imageUrl)
            }.compactMap {
                UIImage(data: $0.data)
        }
    }
}
```
however, uncomment that print line renders the dreaded error:
```
Unable to infer complex closure return type; add explicit type to disambiguate
```
So I add the type info with ```  (user: User) in ```
which updates said dreaded message to the equally dread-able
```
Cannot convert value of type '(User) -> ()' to expected argument type '(_) -> _'
```

I guess the answer to this is - wait for future versions of the swift compiler to infer better, but it does seem awkward that adding a print stmt breaks everything...

**Comment by mxcl** [comment]
Per our 
[Troubleshooting Guide](https://github.com/mxcl/PromiseKit/blob/master/Documentation/Troubleshooting.md), you need to specify the return types for multiple line `then` statements.

**Comment by brynjar** [comment]
ah yes thanks. Hadn't noticed the part about multi-line closures.
