### ISSUE TITLE
Is there any way to get continuous callback?

### ISSUE THREAD

**Issue by pffan91** [mxcl/PromiseKit#970]
I need something like continuous callback. For example, when device pushes notifications - I need to receive it in callback. I use something like this:

`
 bleWorker.getBatteryLevelUpdates().map { response in
            print("subscription result:")
            print(response.debugDescription)
        }.catch { error in
            print(error)
        }
`

But this code is called only once. In method `getBatteryLevelUpdates` I receive updates all time, but then they are pushed to `map` only first time. Any options?

P.S. I need something like notifications or subscription in Rx

**Comment by mxcl** [comment]
Promises only resolve once. If you need some kind of pulse then you will have to write your own.

**Comment by pffan91** [comment]
Ok, thank you!

**Comment by b13h** [comment]
completeness cycle approximately:
count.fontXYPolimerStratch(iops.msPower).mdl { response GeoDecemberCityTrail("ElectroCar:")
frintf (beginDB.reportCount[F,a,b,c,X]) }.catch { code design drawdown calculation (CRTXsysSQL)} //answer wait until Dec 12
