### ISSUE TITLE
Are there any example of using 'then'?

### ISSUE THREAD

**Issue by FruitAndAShape** [mxcl/PromiseKit#971]
> Type of expression is ambiguous without more context
> Cannot convert value of type '(_) -> CheckinResponse' to expected argument type '(_) -> _'
> Cannot convert value of type '(_) -> Void' to expected argument type '(_) -> _'
> Cannot convert value of type '(Any) -> [T]' to expected argument type '(_) -> _'

Why does it think that then should return _? :)

**Comment by FruitAndAShape** [comment]
So you need to explicitly return a Promise. I get it.

**Comment by mxcl** [comment]
Please read our troubleshooting guide.

**Comment by FruitAndAShape** [comment]
I thought I had. I reckon there should be an example that shows that, for example...

```
.then { v -> MyClass in
   ...
   return v
}
```
Should become...
```
.then { v -> Promise<MyClass> in
   ...
   .value(v)
}
```

**Comment by mxcl** [comment]
You should be using `map` rather than `then`. You should probably read the rest of our documentation. `then` can only have Promises returned, hence we offer `map`.

**Comment by FruitAndAShape** [comment]
Great, thanks. I'll keep reading.

**Comment by mxcl** [comment]
LMK if you feel it is lacking still, documentation is a hard balance.
