### ISSUE TITLE
At a loss on how to create a Promise<T> from AnyPromise

### ISSUE THREAD

**Issue by jfahrenkrug** [mxcl/PromiseKit#974]
I'm at a loss. I just can't seem to satisfy the Swift compiler. Here's my problem:

I have an Objective-C method that returns `AnyPromise *`:

```
- (AnyPromise * _Nonnull)fetchThings 
{
    return [AnyPromise promiseWithValue:@[@"a", @"b", @"c"]];
}
```

What is the correct way to turn this into `Promise<[String]>` to be used from Swift? The `toPromise` method mentioned here https://github.com/mxcl/PromiseKit/issues/388 doesn't exists anymore. I'm using Swift 4.2 and PromiseKit 6.5.3.

This obviously doesn't work:

```
thingFetcher.fetchThings().done { (things: [String]) in
                
}.catch { error in
                    
}
```

This doesn't work (says "Type of expression is ambiguous without more context")

```
let specificPromise: Promise<[String]> = Promise<[String]>(thingFetcher.fetchThings())
```

I must be missing something very obvious or doing something very stupid. Thank you for your help! If I overlooked the answer in the Troubleshooting guide, I do apologize in advance.

**Comment by mxcl** [comment]
AnyPromise feeds `Any` (as per its definition), therefore:

```swift
thingFetcher.fetchThings().map {
    $0 as! [String]
}
```

**Comment by jfahrenkrug** [comment]
@mxcl Thank you so much! It makes sense that a force-downcast is required. Thanks for your hard work on this fantastic library!

**Comment by mxcl** [comment]
nps 👍🏻

If you found my work helpful, please consider [supporting its development](https://patreon.com/mxcl).
