### ISSUE TITLE
Do multiple Alamofire request and waiting for every one?

### ISSUE THREAD

**Issue by martin-one** [mxcl/PromiseKit#978]
I have a code to fetch data from API, it gets a list of IDs in string, an then I have to check every string and fetch the data for that specific ID.
The part of getting the list of IDs works but the part of fetching every result, it just dont work.
My code:

```
       firstly {
            getAListOfIds()
            }.then { data in
                getDataForEveryId(listId: data)
            }.done { data in
                print("ListMatches: ",data.count)
        }

```

getlistOfIDs works perfectly, on getDataForEveryId I count the results an they are okay, but in the .done the result of the print of data.count is 0. (it should be the same nuber as last one).

```
    func getDataForEveryId(listId: [String]) -> Promise<[JSON]> {
        return Promise { seal in
            var listOfResults = [JSON]()
            for id in listId {
                Alamofire.request(APIURLWITHid, headers: head).responseJSON { response in
                    if let status = response.response?.statusCode {
                        switch (status) {
                        case 200:
                            if ((response.result.value) != nil) {
                                let jsonResult = JSON(response.result.value!)
                                self.listOfResults.append(jsonResult)
                            }
                            break
                        default:
                            break
                        }
                    }
                }
            }
            seal.fulfill(listOfResults)
        }
    }
```

the problem is in getDataForEveryId, how can I do every request before the metod finishes, debugging my app I can see that it does continue doing the requests after it gets to the .done part fo the code.

Thanks in adavnced :3

**Comment by mxcl** [comment]
```
func getDataForEveryId(listIds: [String]) -> Promise<[JSON]> {
    return when(fulfilled: listIds.map {
        Alamofire.request(APIURLWITH($0), headers: head).validate().responseJSON()
    })
}
```

**Comment by mxcl** [comment]
Incidentally the reason your code didn't work is asynchronicity. The Alamofire callbacks all happen in the future, but you fulfill immediately with an empty array.

**Comment by martin-one** [comment]
With that code I will just do the request for one 'id', right?, not every [id] on the list?

**Comment by mxcl** [comment]
It will do a request for every id, as the documentation for thenMap states. please read our documentation.

**Comment by mxcl** [comment]
If you found my help useful, please consider reimbursing my time by contributing to [https://patreon.com/mxcl](my Patreon).
