### ISSUE TITLE
Promises Never Resolves

### ISSUE THREAD

**Issue by kamalrajvenkatesan** [mxcl/PromiseKit#979]
### Never Executes done

**Version: 6.7.0**
**Swift Perfect HTTP Project**

```
class Example {

  init() {

      firstly(execute: {
        when(resolved: getName())
      }).done({ (name) in
        // Never Executes done.
        print(name)
      })

  }
  
  private func getName() -> Promise<String> {

    return Promise {
      seal in
      seal.resolve("My Name", nil)
    }
  }

}
```

I'm trying to print the name in **done block**. but it never happens.

Same thing works fine in iOS Project. But not working with Swift Perfect HTTP Project.

**Comment by mxcl** [comment]
Do `done(on: .global())`.

See our FAQ for more information on server-side promises.

**Comment by mxcl** [comment]
If you found my help useful, please consider reimbursing my time by contributing to [my Patreon](https://patreon.com/mxcl).
