### ISSUE TITLE
Swift: reject a 'then' with an NSError

### ISSUE THREAD

**Issue by dtrukr** [mxcl/PromiseKit#98]
I've been really enjoying using PromiseKit for Objective-C, thanks for all your work.
I'm trying to rewrite some of my logic with PromiseKit for Swift and cannot seem to figure out how to reject a 'then' with an NSError. Is this possible in the Swift version?

```
    let p = Promise{(fulfiller, rejecter) in
            fulfiller(true)
        }

        p.then{_ -> Bool in
            println("then 1")
//          the following line does not compile
//          return NSError(domain: "error", code: 100, userInfo: nil)
            return true
        }.then{_ -> Bool in
            println("then 2")
            return true
        }.catch{(error:NSError) -> Void in
            println(error.localizedDescription)
        }
```

If I replace the first 'then' with the following it compiles fine but does not reject the promise (e.g. it goes into the second 'then' instead of going to the 'catch'):

```
...
      p.then{_ -> AnyObject in
            println("then 1")
           return NSError(domain: "error", code: 100, userInfo: nil)
        }
...
```

**Comment by michael-mckenna** [comment]
@mxcl So just to revisit this a bit later from when it was asked - is this still your recommended solution, or is there a new suggested flow?

**Comment by mxcl** [comment]
No, nowadays you `throw`. See our “Getting Started” documentation for more details.

**Comment by michael-mckenna** [comment]
Thanks for the quick response.

I was getting an error which brought me here. I'm following [the failing chains section](https://github.com/mxcl/PromiseKit/blob/master/Documentation/CommonPatterns.md#failing-chains) and I'm getting an error.

**Comment by mxcl** [comment]
You have no return in your then.

**Comment by mxcl** [comment]
Your then returns void. There is not a version of then that allows this. You must return a promise from then.

**Comment by michael-mckenna** [comment]
@mxcl Whoops! Thanks for your quick help. By the way, I recently used your library to rewrite a lot of our syncing/networking logic. You've done an excellent job.

**Comment by mxcl** [comment]
Thanks! I appreciate that. Also your `guard` body doesn't ensure an “exit”.

```
}.then { confirmed -> Void in
    guard confirmed else { try throwError() }
    API.sendInvite(to: user)
}
```
