### ISSUE TITLE
I wonder if Promise(function) might now work correctly in PMK 7

### ISSUE THREAD

**Issue by GarthSnyder** [mxcl/PromiseKit#982]
The [Getting Started](https://github.com/mxcl/PromiseKit/blob/master/Documentation/GettingStarted.md#making-promises) doc mentions:

```
func fetch() -> Promise<String> {
    return Promise { seal in
        fetch { result, error in
            seal.resolve(result, error)
        }
    }
}
```

> Note: We tried to make it so that you could just do Promise(fetch), but we were not able to make this simpler pattern work universally without requiring extra disambiguation for the Swift compiler. Sorry; we tried.

Since disambiguation has changed recently in some subtle ways, I wonder if this is still true for Swift 4 (or Swift 3 under current compilers, since the new scheme seems to apply to both). If PMK 7 is going to require current compilers, it might be possible to try this again.

If you can remember what the sticking point was for this form, I'll take a look at the current state.

**Comment by mxcl** [comment]
Usually it was greedy inferment, where sometimes:

```swift
let foo = Promise { seal in
   //…
}
```

`foo` would (in some cases) be inferred to `Promise<(Resolver) -> Void)>`.

I cannot off hand remember an example case though.

**Comment by GarthSnyder** [comment]
Ah, yes, that makes sense. I'll poke around a bit.

**Comment by GarthSnyder** [comment]
After considering this a bit more, I'm thinking that the larger problem here is that relatively few callback-invoking functions have no arguments other than the callback, so the utility of this specific form is probably pretty limited. More typical would be something like

```
func fetchThing(thingName: String, _ callback: (Thing?, Error?) -> Void)
```

I would imagine the closest you could come to handling these cases would be something like

```
Promise(fetchThing, "thing name").done { ... }
```

but that would seem to require a lot of different templates to implement (# of non-callback arguments X various callback signatures). It doesn't preserve argument names, and it's also kind of mysterious for readers who don't understand exactly what's going on.

Just passing `seal.resolve` as the callback is nearly as concise, and it handles most cases without any additional PromiseKit code.
