### ISSUE TITLE
Documentation Error 

### ISSUE THREAD

**Issue by vade** [mxcl/PromiseKit#984]
---
Hi

Firstly, thanks for Promise Kit.

Im looking to get up to speed on Promise Kit and am reading the documentation, specifically Common Patterns.md, and I think the example code has an issue. 

Please see https://github.com/mxcl/PromiseKit/blob/master/Documentation/CommonPatterns.md#abstracting-away-asychronicity

And notice that the refresh function has no return signature, yet the function returns a promise? 

Apologies if I am missing something, but that appears to be an issue. 

Should it not be : 

`refresh() -> Promise<SomeType>`

Thanks.

**Comment by vade** [comment]
Thats some response time ;) Thank you.

**Comment by mxcl** [comment]
Glad to please! LMK if you have any other trouble or questions.
