### ISSUE TITLE
Restart complete promiseChain on catched error

### ISSUE THREAD

**Issue by shi-rudo** [mxcl/PromiseKit#985]
* PMK 6.7 (installed with CocoaPods)
----

I wonder if there is a possibility to restart a complete PromiseChain again if an error is thrown until the chain resolves without error (like a while loop). putting the promiseChain into a while or repeat loop does not work, it does not respond. 

The chain should restart until it either runs without an error or returns a default or an otherwise specified error.

```swift
firstly{
    generateRandomID()
}.then { ID in
    checkIfIdIsValid(ID) 
}.then { ID in
    loadDocument(ID)
}.then { document in
    validateDocument(document)
}.done { doument in
    displayDocument(document)
}.catch { error in
    switch error {

    case Error.IDInvalid:
    -> restart promiseChain until a valid ID is generated

    case Error.documentInvalid:
    -> restart promiseChain again until a document is generated

    case Error.foo
    //Handle foo error

    case default:
    //Handle unspecified error

    }
}
```

Thanks a lot!

**Comment by mxcl** [comment]
Yes: https://github.com/mxcl/PromiseKit/blob/master/Documentation/CommonPatterns.md#retry--polling

**Comment by shi-rudo** [comment]
ah, thanks!

is this the right way?

```swift
func attempt<T>(maximumRetryCount: Int = 3, delayBeforeRetry: DispatchTimeInterval = .seconds(1), _ body: @escaping () -> Promise<T>) -> Promise<T> {
    var attempts = 0
    func attempt() -> Promise<T> {
        attempts += 1
        return body().recover { error -> Promise<T> in
            guard attempts < maximumRetryCount else { throw error }
            return after(delayBeforeRetry).then(on: thread, attempt)
        }
    }
    return attempt()
}

func repeatIfNeeded() -> Promise<Void> {
    return Promise {seal in
        firstly{
            generateRandomID()
            }.then { ID in
                checkIfIdIsValid(ID)
            }.then { ID in
                loadDocument(ID)
            }.then { document in
                validateDocument(document)
            }.done { doument in
                displayDocument(document)
                seal.fullfill()
            }.catch { error in
                seal.reject(error)
            }
        }
}

attempt(maximumRetryCount: 3) {
    repeatIfNeeded()
    }.catch { error in
        log.error(error)
}
```

It runs :-) But how can I handle that it only retries on case Error.IDInvalid and Error.documentInvalid, without breaking the maximumRetry cycle?

**Comment by mxcl** [comment]
Don’t double up promises: 
https://github.com/mxcl/PromiseKit/blob/master/Documentation/Appendix.md#doubling-up-promises

>  But how can I handle that it only retries on case Error.IDInvalid and Error.documentInvalid, without breaking the maximumRetry cycle?

Use `recover`.

**Comment by shi-rudo** [comment]
thanks for pointing out! I just started working with PromiseKit. Therefore I am grateful for the help! 

Is this the right approach? 
```swift

func attempt<T>(maximumRetryCount: Int = 3, delayBeforeRetry: DispatchTimeInterval = .seconds(1), _ body: @escaping () -> Promise<T>) -> Promise<T> {
            var attempts = 0
            func attempt() -> Promise<T> {
                attempts += 1
                log.debug(attempts)
                return body().recover { error -> Promise<T> in
                    
                    //Handle to many attempts with retries
                    guard attempts < maximumRetryCount else {
                        log.error("to many attempts")
                        throw error
                    }
                    
                    //Handle specified errors with retries
                    if error ==  Error.IDInvalid: {
                        log.error("ID does not comply with rules")
                        return after(delayBeforeRetry).then(on: nil, attempt)
                    }

                    if error ==  Error.documentInvalid: {
                        log.error("document does not comply with rules")
                        return after(delayBeforeRetry).then(on: nil, attempt)
                    }
                    
                    //Throw error if error is unspecified -> does not retry
                    throw error
                }
            }
            return attempt()
        }

//chain
func repeatIfNeeded() -> Promise<Void>  {
            return firstly{
                generateRandomID()
            }.then { ID in
                checkIfIdIsValid(ID)
            }.then { ID in
                loadDocument(ID)
            }.then { document in
                validateDocument(document)
            }.done { doument in
                displayDocument(document)
            }
}

//run
attempt(maximumRetryCount: 20) {
    return repeatIfNeeded()
        }.catch { error in
            log.error(error)
}

```

Thanks!

**Comment by mxcl** [comment]
Looks good 👍🏻

**Comment by mxcl** [comment]
Closing but re-open if your question is still not answered.

If you found my help useful, please consider reimbursing my time by contributing to [my Patreon](https://patreon.com/mxcl).

**Comment by JetForMe** [comment]
This approach seems to require a helper method for each set of operations that needs to be retried, am I understanding that correctly (assuming each set of operations has different error/retry conditions). In my case, I'm making a series of network calls: one to get my user's subscriptions, then three more for each subscription to get information about the subscriptions (I know, it's a mess). For each subscription, the three calls can be done in parallel, and all the subscriptions can be done in parallel. If any individual call fails, I want to retry it three times, depending on the error, but if three attempts fail (or if there is a "harder" error), I want to send an error all the way up the chain to the very first call.

Is there no way to reduce all the boilerplate this seems to require?

**Comment by mxcl** [comment]
My gut tells me this isn't that hard to achieve. You use the retry function above as an inline function and have a `Int` counter outside that scope that when is `> 3` you stop retrying. If you need custom errors for each retry then pass as a parameter to check against.
