### ISSUE TITLE
When I re-indent(press control + i), the structure become a bit confusing.

### ISSUE THREAD

**Issue by YiYiZheng** [mxcl/PromiseKit#995]
Version 6.7.0
Installed by CocoaPods.

When I press control + I, the code become:

```
firstly {
      checkNetwork(viewController: popViewManager)
      }.done { success in
          checkCompletion(success)
      }.catch { error in
          checkCompletion(false)
          handleError(error, popViewManager: popViewManager, enterType: enterType)
}
```

What I want is something like this:
```
firstly {
  checkNetwork(viewController: popViewManager)
}.done { success in
  checkCompletion(success)
}.catch { error in
  checkCompletion(false)
  handleError(error, popViewManager: popViewManager, enterType: enterType)
}
```
 Is there anything I can do about this? Thanks.

**Comment by mxcl** [comment]
You can report the bug to Apple, maybe they will fix it.

**Comment by mxcl** [comment]
There is nothing we know that can be done about it.

**Comment by dev-xdyang** [comment]
Is there anything I can do to make code like this format
```swift 
firstly {
    Promise.value(1)
}.map { _ in
        2
}
```
when I press `enter` key, the code will code like this:
```swift
firstly {
    Promise.value(1)
    }.map { _ in
        2
}
```
I am not use re-indent, only input by manually. Any solutions? Thanks a lot.

**Comment by dev-xdyang** [comment]
There is a [talk](https://gitter.im/mxcl/PromiseKit/archives/2017/01/20) about this. Perhaps no solution now. Sadly.
