### ISSUE TITLE
Consider unarchiving PMKEventKit repo

### ISSUE THREAD

**Issue by interstateone** [mxcl/PromiseKit#999]
* Please specify the PromiseKit major version you are using
**6**
* [Please format your code in triple backticks and ensure readable indentation](https://help.github.com/articles/creating-and-highlighting-code-blocks/)
* Please specify how you installed PromiseKit, ie. Carthage, CocoaPods, SwiftPM or other. If other provide DETAILED information about how you are integrating PromiseKit.
**SPM**

I wanted to use EventKit with PromiseKit the other day (for [a swift-sh script](https://github.com/interstateone/dotfiles/blob/master/work/bin/slack-calendar-status.swift)) and later found that [PMKEventKit](https://github.com/PromiseKit/EventKit) existed, but was archived. I'd reached out [on Twitter](https://twitter.com/interstateone/status/1088985991434579968) and am following up here.

> My opinion was it wasn't possible to provide a sensible promise for this library.

It's very likely I'm ignorant of the details that make the following implementation not sensible, and I'd love to learn why if that's the case!

This makes a slight change to the existing implementation by moving it into an extension and accepting the same argument as the original API. Most of the EKEventStore methods are synchronous, with the exception of `fetchReminders(matching:completion:)` which could also have a Promise version.

```swift
// I've omitted EventKitError here

extension EKEventStore {
    public func requestAccess(to entityType: EKEntityType) -> Promise<EKEventStore> {
        return Promise { seal in
            switch EKEventStore.authorizationStatus(for: entityType) {
            case .authorized:
                seal.fulfill(self)
            case .denied:
                seal.reject(EventKitError.denied)
            case .restricted:
                seal.reject(EventKitError.restricted)
            case .notDetermined:
                requestAccess(to: entityType) { granted, error in
                    if granted {
                        seal.fulfill(self)
                    } else if let error = error {
                        seal.reject(error)
                    } else {
                        seal.reject(EventKitError.denied)
                    }
                }
            }
        }
    }
}
```

[This PMKCoreLocation authorization method](https://github.com/PromiseKit/CoreLocation/blob/master/Sources/CLLocationManager%2BPromise.swift#L153) is interesting to compare to because it guarantees a CLAuthorizationStatus, which I think could be mimicked here, but I don't know if that's more or less sensible or simply change for change's sake. In the admittedly simple use case of my script that I linked at the top I only care about getting access to the store or not, so `Promise<EKEventStore>` is more straightforward.

Thanks for taking the time to explain more about this to me and consider the proposal.

**Comment by mxcl** [comment]
I think it's cool if we do it like so:

```swift
extension EKEventStore {
    public func requestAccess(to entityType: EKEntityType) -> Promise<EKAuthorizationStatus> {
        return Promise { seal in
            let status = EKEventStore.authorizationStatus(for: entityType)
            switch  {
            case .authorized, .denied, .restricted:
                seal.fulfill(status)
            case .notDetermined:
                requestAccess(to: entityType) { granted, error in
                    if let error = error {
                        seal.reject(error)
                    } else {
                        seal.fulfill(EKEventStore.authorizationStatus(for: entityType))
                    }
                }
            }
        }
    }
}
```

I'm not sure we should do the initial call to `EKEventStore.authorizationStatus` though. Maybe we do in `CLLocationManager` but that code is pretty complex for all the different things it handles. Generally we try not to do more than call through to Apple API we claim we will.

**Comment by interstateone** [comment]
:+1: That makes sense, thank you. I agree about removing the initial `EKEventStore.authorizationStatus` call. I can submit a PR with this change when the repo is unarchived.
